### ISSUE TITLE
Horus Heresy Book V: Tempest

### ISSUE THREAD

**Issue by battlebrother** [BSData/horus-heresy#100]
Is anyone looking at updating the CAL with the latest additions and the Ultramarines-specific rules? - I have the book, so I can assist with the rules if needed.
I'd be happy to help out with the Imperial Militia and Cults rules if someone wanted to take that on too, same goes for updating Word Bearers (though I'm not sure how much has changed from their last iteration).

**Comment by Millicant** [comment]
Hey there,

I'll be updating it as soon as my copy arrives! It's in the mail now. For the moment, I'd like to hold off on any updates until I can take a look at it. Once I do, I may have a job for you!

Thanks!

**Comment by battlebrother** [comment]
Fantastic :) It's a lovely book, though I imagine you will be cursing at some of the interdependencies that the new units have, probably nothing worse than you've seen before though. Anything I can do to help just let me know!

**Comment by Millicant** [comment]
Ha!  Yes, this catalogue is quite a beast already.  I'm sure the new Militia/Cults list will be just as much fun.  And thanks, I'll definitely let you know how you can help!

**Comment by Caprera** [comment]
If not before, I will receive my copy in couple weeks.

**Comment by Millicant** [comment]
This has begun!  Since I'll be rolling out the updates progressively as I finish them, I'm going to close this issue.  Feel free to re-open as necessary.  :)
