### ISSUE TITLE
Tactical Support Squad extra CCW calculation

### ISSUE THREAD

**Issue by kryanth** [BSData/horus-heresy#1008]
Extra CCW is 2pts per model in the unit, and a base unit is 4 marines and 1 sergeant. The initial CCW cost is calculated at 12, rather then 10. Adding models increases by 2 each time correctly, but is initially wrong.

**Comment by capitaladot** [comment]
@kryanth So, HSSquads can't take additional CCWs. Are you referring to their costs for weapons?

**Comment by kryanth** [comment]
Tactical support squad (non compulsory troop choice), not heavy support squad
