### ISSUE TITLE
Transport mistake for "Wrath of Angels" Rite of War

### ISSUE THREAD

**Issue by fjramsay** [BSData/horus-heresy#102]
The Wrath of Angles Rite of War gives units that can take a Rhino access to a Legion Drop Pod or Legon Dread Claw Drop Pod,
 however when selected it instead removes the rhino and adds the Storm Eagle Assault Gunship.

This was present in every squad I checked.

BattleScribe v1.15.07
Warhammer 30,000 - The Horus Heresy v29 by Millicant

**Comment by Millicant** [comment]
I'm afraid you are incorrect about how this Rite of War works.  The Orbital Assault Rite of War does what you are describing, while the Angels Wrath Rite of War is working exactly as it should.
