### ISSUE TITLE
Validation Error - Perturabo and Legiones Astartes

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1024]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.01.03

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** In an Iron Warriors list, am getting a validation error of 'The Primarch Perturabo cannot have any selections of Legiones Astartes (hidden)

**Comment by capitaladot** [comment]
I guess someone should make a roster with every possible unit to track down all of the erroneous Legiones Astartes entries?
