### ISSUE TITLE
Grouping error on Tactical Support Squad weapons

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1025]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.01.03

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Tactical support squad has an unnecessary sub-level on one of its options

On the entry for the Tactical Support Squad, pressing 'Entire Squad may exchange their Flamers for:' does not present the user with the options list, instead it go to a new page that again shows the option of 'Entire squad may exchange...' (the only entry on this new page) pressing that option will then finally present the user with the options list

**Comment by capitaladot** [comment]
This isn't so much a bug as a problem with the level of nesting.
