### ISSUE TITLE
DA acid shell not having a point value for jetbike squad - HH v8.4.6

### ISSUE THREAD

**Issue by z258** [BSData/horus-heresy#1028]
Just recently updated the Horus heresy data files and making a ravenwing list, that the 5pts per heavy bolters upgrade for the acid shells is not there for the jetbike squad. 
![img_0737](https://user-images.githubusercontent.com/25120579/27694012-3d4b08aa-5d2e-11e7-891f-c034a909d6e6.PNG)
![img_0738](https://user-images.githubusercontent.com/25120579/27694014-3d8a15fe-5d2e-11e7-8465-26e6fedc5065.PNG)

**Comment by capitaladot** [comment]
Fixed.
