### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by ArioKnowles** [BSData/horus-heresy#103]
Hi there, I've created a Battlescribe Catalog for the Imperial Militia and Cults list from Horus Heresy Book 5 - Tempest. It was originally just going to be for personal use, but I've not seen anything similar posted online, so I would like to publish it as part of your project.

**Comment by Millicant** [comment]
Hey there,

Sounds good.  I plan on making my own, but I will gladly use yours for reference and shameless idea stealing!  

Feel free to upload your work, but please do not publish any releases.  

Thanks!

Jordan

**Comment by amis92** [comment]
@ArioKnowles so you'd like to join the team, or just share the catalogue once and be done? If the latter, a simple pull request will suffice.

If you want to contribute more, confirm it and I'll send you an invitation.

**Comment by ArioKnowles** [comment]
I'd like to join the team. There's quite a few other catalogues I'd be interested in contributing to.

**Comment by amis92** [comment]
Okay, invitation sent. Welcome aboard!

**Comment by Millicant** [comment]
Welcome ArioKnowles!
