### ISSUE TITLE
Daemons missing force orgs and all entries are uncategorised

### ISSUE THREAD

**Issue by zopha** [BSData/horus-heresy#1030]
![2017-07-02 17_26_55-roster editor v2 01 03 - new roster warhammer 30 000 - the horus heresy v86](https://user-images.githubusercontent.com/1666415/27771692-ed1da2a0-5f4b-11e7-91c7-7716e66cc1f0.png)

![2017-07-02 17_27_38-new roster](https://user-images.githubusercontent.com/1666415/27771687-cd324c48-5f4b-11e7-9a83-b5e913ff74b9.png)

**Comment by capitaladot** [comment]
I have made a couple of passes at fixing this but have really had a hard time getting anything to work.

**Comment by capitaladot** [comment]
Rebuilding the Allied Detachment sorted it out.
