### ISSUE TITLE
Magos Reductor appears to have disappeared from my Matrix of Ruin Mechanicum lists

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1042]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** Yes

**Description:** The option for the Magos Reductor appears to have disappeared from my Matrix of Ruin Mechanicum lists. I have tried creating a new roster but this has not helped. I believe the issue is that the allegiance option is either missing or not showing. This appears to be restricted to the Matrix of Ruin as it displays normally when creating an Age of Darkness detachment.

**Comment by capitaladot** [comment]
@zopha fix this when you fix the Archmagos?

**Comment by zopha** [comment]
I'll have a look at this later today.

**Comment by zopha** [comment]
Sorry, haven't gotten a chance as work is eating up all my time. I'll make some time tomorrow for this after I look at some other issues.
