### ISSUE TITLE
Can't open Legiones Astartes File on Windows 10

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1046]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** Yes

**Description:** The Legion Astartes roster choice won't work. Other army rosters load

**Comment by gothmogbalrog** [comment]
Getting the same error. Causes BS to freeze or crash

**Comment by zopha** [comment]
Same issue we're seeing in #1043
