### ISSUE TITLE
Legiones Astartes: Age of Darkness Army List will not load

### ISSUE THREAD

**Issue by 59tiger95** [BSData/horus-heresy#1063]
Battlescribe Version: v2.01.04

Platform: Windows 10

More info:
Hi, I've been having troubles getting the listed army list to load. It simply acts like its loading but nothing ever loads. It is only the Legiones Astartes: Age of Darkness list that has this problem. Other armies such as the Talons of the Emperor and the Mechanicum: Taghmata load just fine. This has continued after deleting the data multiple times. It still persists after completely uninstalling and then reinstalling battlescribe. Any help would be greatly appreciated.

**Comment by capitaladot** [comment]
Recommend updating Java to 64 bit.

**Comment by kenny64mc** [comment]
I have the same trouble, updated Battlescribe and data files, have the latest JAVA,  It is only the Legiones Astartes: Age of Darkness list that has this problem. all other lists work all other data files work.

Is this Heresy?

**Comment by capitaladot** [comment]
Please post Java version (and note 32 bit vs 64 bit) and system specs
(memory, processor, hard disk type/speed, etc). We are having trouble
reproducing this.

**Comment by 59tiger95** [comment]
installing the 64 bit of Java specifically fixed the issue for me. Thanks for the help

**Comment by capitaladot** [comment]
Glad to learn as much!

**Comment by kenny64mc** [comment]
Hi

as advised just installed Java 64bit, all working now.
sorry for the messing around. thanks for the help
