### ISSUE TITLE
Horus Heresy Data not available to download in repository list.

### ISSUE THREAD

**Issue by Jesse1220** [BSData/horus-heresy#1065]
https://battlescribedata.appspot.com/#/repos

Sorry for asking, but where did it go?

**Comment by capitaladot** [comment]
Thanks for for letting us know. @amis92?

**Comment by TomTheHand** [comment]
The data still isn't available on the repo (or it's missing again).

**Comment by capitaladot** [comment]
The build bot is notoriously flaky. Are you re-downloading it from the web everytime, or are your seeing it go missing or something within the app?

**Comment by TomTheHand** [comment]
In the app I noticed that it hadn't updated the Heresy file since mid-June, so I went to the web site and it wasn't there either.

**Comment by TomTheHand** [comment]
The file was available for a short while yesterday, but is missing again, both from the web site and when attempting to download it through Battlescribe itself.

**Comment by amis92** [comment]
It works for me now, and quite stably.

**Comment by TomTheHand** [comment]
Download's missing again :-/
