### ISSUE TITLE
Master of the Legion: Rites of war: the Hammer of Olympia 

### ISSUE THREAD

**Issue by AnUnearthlyChilde** [BSData/horus-heresy#107]
Each time I attempt to add the additional heavy support slot, granted by the above rule, it tells me I have one too many heavy support options selected. It also doesn't modify only allowing one less fast attack option or needing an additional compulsory troops selection.

**Comment by Millicant** [comment]
Unfortunately Battlescribe does not provide for modifying the Force Organization Chart like that.  You'll just have to know when it's legal or not legal.  If it is ever implemented - you can be sure I will add it!

Thanks!
