### ISSUE TITLE
Legion Termy Sergeant weapon options pts

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#1073]
The costs of replacing power weapons on terminator sergeant are all wrong.
It lists Chainfist as free (should be +10pts)
Lightning claw free (should be +5pts)
Power fist 15pts (should be +5pts)
Thunder Hammer 20pts (should be +10pts)

**Comment by capitaladot** [comment]
Thanks for the report. I suspect ill-considered global changes elsewhere have had undesirable downstream effects. PR welcome.
