### ISSUE TITLE
Militia bug

### ISSUE THREAD

**Issue by amis92** [BSData/horus-heresy#1078]
While doing the "Reopen and save"  9f058d3 I've stumbled upon an existing bug:

![2017-08-23](https://user-images.githubusercontent.com/2671396/29606994-28c95520-87f0-11e7-8777-1c73e91e4b04.png)

I've temporarily fixed it so as to save the file, but I don't know how it should be, so you might want to re-fix it.

**Comment by capitaladot** [comment]
Hey @alphalas... are you the one who knows how this was supposed to work, or was that @zopha ?

**Comment by alphalas** [comment]
It was me and @Kohato - think it went off LA in GST iirc
