### ISSUE TITLE
Legion Command Squad issues

### ISSUE THREAD

**Issue by TomTheHand** [BSData/horus-heresy#1079]
There are a few issues with Legion Command Squads. If I'm incorrect about any of these, I apologize!

- [x] The "Bodyguard" section (listing Command Squads) appears under "Master of the Legion" twice.
- [ ] Terminator Command Squads should only be available to Masters of the Legion with Terminator Armor or Primarchs.
- [ ] Command Squads should only be able to take Jump Packs, Bikes, or Jetbikes if their Master of the Legion also has that equipment (I am not sure about Primarchs).
- [x] Command Squads with Jump Packs, Bikes, or Jetbikes should no longer be able to take a Dedicated Transport.
- [x] Terminator Command Squads should not have the option to take Dreadclaw Drop Pods... unless Sons of Horus, I think.
- [x] Combat Shields should be capped at 5.
- [x] Hand Flamers should not be available to Command Squads.
- [x] The weapons for Terminator Command Squads are not validated correctly.

Currently the validation ensures the following:
1. No more than 5 total selections are made from "Exchange Combi-bolter for:"
2. No more than 5 total selections are made from "Exchange Power Weapon for:"
3. No more than 10 total selections are made from Weapons.
As a result, it is possible to select, for example, five Combi-Bolters, a Heavy Flamer, and four Chainfists. Additionally, Pairs of Lightning Claws are considered a single weapon; one could take five of them plus five of some other type of weapon.

The validation should work like this instead:
1. No more than 5 total selections are made from "Exchange both Power Weapon and Combi-bolter for:" (Lightning Claws), "Exchange Combi-bolter for:", and "One model may exchange their Combi-bolter for:" (Heavy Weapons).
2. No more than 5 total selections are made across "Exchange both Power Weapon and Combi-bolter for:" (Lightning Claws) and "Exchange Power Weapon for:".

Hope this makes sense; if it doesn't, let me know.

**Comment by alphalas** [comment]
Tom, please join us on Gitter - we can try to talk though this there

- Jon[K]

**Comment by TomTheHand** [comment]
Could you post a link?

**Comment by capitaladot** [comment]
https://github.com/BSData/horus-heresy

**Comment by capitaladot** [comment]
@TomTheHand these write-ups are great.
