### ISSUE TITLE
Datafile is broken on Android and Windows

### ISSUE THREAD

**Issue by falxcerebri** [BSData/horus-heresy#1089]
After running git bisect v8.0.0 (which was fine) and current master (75a236b4b28807597f3e69d039ccd84fcbfac08d), and testing it on my Android Device (Ubuntu version works fine), I've found that following commit breaks the datafile:

commit 94f14689a29126ce35576c27560be8cd2509687d
Author: capitaladot <austinitor@gmail.com>
Date:   Thu Jul 6 23:39:44 2017 -0400

    Many more small Legiones Astartes fixes
    
    - cost for Scimitar Molecular Acid
    - Legiones Astartes for Blackshields and Shattered Legions
    - Headhunters as Compulsory Troops in Headhunter Leviathal
    - Correct Legiones Astartes for Consuls and Praetors

On Windows users are unable to load/create rooster at all, while on Android, users are able just to load/create user in Low Memory Mode.

I'll do my best to debug the issue further and perhaps prepare fix myself.

P.S. I've used master branch and tried also the one from June that was released to BD Data repository

**Comment by capitaladot** [comment]
> On Windows users are unable to load/create rooster at all, while on Android, users are able just to load/create user in Low Memory Mode.

That's not really accurate. Please try 64 bit Java on your desktop devices. Android is working fine for myself and other users.

**Comment by falxcerebri** [comment]
So perhaps it's either particular Android version (5.1.1). You're correct about Windows and x32 Java. However, I can run BattleScribe with -Xmx512m flag, and even on x32 it works fine.

So I guess, that it's not really an issue, rather a fact that BattleScribe is hoarding lots of memory.

That's an exception I'm getting without -Xmx512m flag:
https://pastebin.com/YxmBJqEi

**Comment by capitaladot** [comment]
Sadly, memory usage in this file is indeed a big problem, so you're basically correct in your report. Any debugging with the editor (or a text editor) to see reduced memory would be most welcome!
