### ISSUE TITLE
Previan HQ

### ISSUE THREAD

**Issue by Caprera** [BSData/horus-heresy#109]
Hello,

I see in the Pc version the cortex controller attached to the Previan Consul is not recognized and an error is listed below when I added a Thallax cohort.

**Comment by Millicant** [comment]
Interesting. I'll take a look and see what the problem is.  Thanks for letting me know!

**Comment by Caprera** [comment]
I hope you can find this useful. 

http://www.bolterandchainsword.com/topic/309665-previan-rules-question/
