### ISSUE TITLE
LA: Army of Dark Compliance

### ISSUE THREAD

**Issue by archonkain** [BSData/horus-heresy#1092]
Army of Dark Compliance incorrectly limits legion choice (must be traitor, but shouldn't prevent traitor variants of the traditionally loyalist legions)

Also, a Praetor, even checking the Praetor/Cent box, does not fulfill the Praetor/Centurion validation check.  A centurion (without even having the Praetor/Cent box to check) however does.

**Comment by capitaladot** [comment]
I've done some work trying to make this work with Categories... but there may be core limitations in BattleScribe preventing such a strategy due to immutability of Categories from Game Systems inside of Catalogs.

**Comment by archonkain** [comment]
Would Legion Praetor being under root selection entries and having a Selection Entry Type of "Model" when the Legion Centurion is under Shared Selection Entries and has a Selection Entry Type of "Unit" have something to do with why the praetor cannot be included in the validation check?  The check only looks for centurion and army of dark compliance right now.

**Comment by capitaladot** [comment]
Maybe not... it would seem that attempts in the UI to create and save Modifiers on Categories just don't work.
