### ISSUE TITLE
Issues with Imperial Militia and Cults

### ISSUE THREAD

**Issue by TomTheHand** [BSData/horus-heresy#1097]
I've gone through the Imperial Militia and Cults army (v55, the version currently available for download) and checked everything against the army list. Here's a list of issues; I apologize in advance if I've made any mistakes:
- [x] The entry for **Lascannon** should have a range of 48" (it's currently 96", which is the range for an Icarus Lascannon).
- [ ] Militia and Cults Armies should not receive the **Warmaster's Due** special rule unless they are using the Army of Dark Compliance theme.

* Some **Provenances of War** cannot be taken together:
   - [ ] Cyber-augmetics and Gene-crafted can't be taken together.
   - [ ] Cult Horde can't be taken with Survivors of the Dark Age.
   - [ ] Tainted Flesh can't be taken with Survivors of the Dark Age, Gene-crafted or Alchem-jackers.
  *Currently, only one element of this is implemented: taking Survivors of the Dark Age, Gene-crafted or Alchem-jackers removes Tainted Flesh as an option.  The reverse isn't true (taking Tainted Flesh does not remove the others) and none of the other rules are implemented.*
- [x] When the Cult Horde Provenance is selected, the **Force Commander** should gain the Daemon and Preferred Enemy (Loyalists) rules, and should have Tainted Weapon added as a 5-point weapon (RAW, it only says it can replace the close combat weapon, so perhaps it should only go on that list and not the laspistol/autopistol list). If feasible, his name should be changed to Cult Demagogue.
- [x] The **Cult Horde** and **Tainted Flesh** Provenances are Traitor-only and should disappear and/or throw a validation error when Loyalist allegiance is selected.
- [x] Currently there is no **Provenance** special rule (though there is a "Provenance" selection entry group which is used for provenance-specific special options). The Provenance special rule determines which units are affected by Provenances of War, so it's important to include in unit profiles.

* Not all selections can be used to fill compulsory slots:
   - [ ] **Discipline Masters** can't be used as compulsory HQs.
   - [ ] **Fire Support Squads** and **Reconnaissance Squads** can't be used as compulsory Troops.
   - [ ] When the Warrior Elite Provenance is selected, **Inducted Levy Squads** can't be used as compulsory Troops and should have the Support Squad rule added to their unit entry.
   - [ ] When the Survivors of the Dark Age Provenance is selected, only **Grenadier Squads** can be used as compulsory Troops and **Inducted Levy Squads** should have the Support Squad rule added to their unit entry.
   - [ ] When the Tainted Flesh Provenance is selected, only **Inducted Levy Squads** can be used as compulsory Troops.
- [x] **Discipline Masters** should have the Instil Order special rule.
- [x] **Inducted Levy Squads** should not have the Support Squad special rule (unless given the rule by a Provenance).
- [x] **Grenadier Squads** with Grenade Launchers pay 5 points per launcher for Fireburst or Gas Grenades, not a flat 5 points for the squad.
- [x] **Imperialis Militia Reconaissance Squad** is misspelled; it should be "Imperialis Militia Reconnaissance Squad" (with two Ns).
- [x] The **Reconnaissance Squad's** weapon selection should have a Lascarbine or Autogun option; this is their default weapon.
- [x] For **Ogryn Brute Squads**, the weapon selection boxes should be capped at 10, since that is the maximum size of the squad.
- [x] For the **Heavy Ordnance Battery**, the Provenance upgrade options should be listed at the root level instead of on each individual crew member.
- [x] For the **Heavy Ordnance Battery**, the upgrade to Medusa Siege Guns should be at the unit level, not the individual gun level (though RAW, it looks like breacher shells are still selected at the gun level).
- [x] For **Battle Tank Attack Squadrons**, Hunter-Killer Missiles and Extra Armour should cost 5 points each.
- [x] For the **Enginseer Auxilia** unit, the weapon selection boxes should be capped at 8, since that is the maximum number of servo-automata that can be taken.
- [x] Each **Enginseer Adept** in an Auxilia unit should have the option to take melta-bombs for 5 points.
- [x] The **Arvus Lighter** should not have the option to take a Flare Shield or Extra Armour (these are options on the Solar Auxilia's version, but are not listed for Militia/Cults).
- [x] For **Auxilia Sentinels**, a multi-melta should cost 10 points, not 5.
- [x] The **Baneblade** should not be able to take a pintle-mount Autocannon or Heavy stubber.
- [x] Militia and Cults should not be able to take **Titans** as Lords of War... or at least I haven't found anything explicitly saying that they can.

**Comment by capitaladot** [comment]
Thanks for this. Will look at it post NoVA Open.
