### ISSUE TITLE
LACAL Crashes on Load - Mobile devices

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1105]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Every time I try to create an army list for astartes it crashes.

**Comment by capitaladot** [comment]
@Jonskichov

**Comment by capitaladot** [comment]
@Jonskichov

**Comment by AndrewPowell124** [comment]
Getting the same issue

**Comment by capitaladot** [comment]
@Jonskichov another

**Comment by WW40k** [comment]
Same - crashes when trying to use the Legion Astartes List. I am using BS on PC.

**Comment by alphalas** [comment]
For PC upgrade your java to 64 bit

**Comment by WW40k** [comment]
Java upgrade seemed to work. Big thanks.

**Comment by zopha** [comment]
Battlescribe has been updated to 2.06 and added support for rules linked to Categories. We're testing it out now to find out it's limitations and what it'll enable us to do, I'm hoping moving some of the LA and legion rules to this category will help with the memory issue.
