### ISSUE TITLE
Followup Command Squad issues

### ISSUE THREAD

**Issue by TomTheHand** [BSData/horus-heresy#1109]
I've had the opportunity to look at Legion Command Squads again, and there are just a couple of outstanding issues.

- [x] Legion Command Squads without Terminator Armour should be able to select a Rhino or Land Raider Proteus as Dedicated Transport, unless they have Bikes, Jetbikes, or Jump Packs.
  _When I made my previous report, Command Squads were incorrectly allowed to take a Dedicated Transport even if they had Bikes, Jetbikes, or Jump Packs._
  _Now, a validation error is thrown whenever a Dedicated Transport is selected, even if they don't have an alternate mobility option and should therefore be allowed to take a transport._

- [x] Space Marine Chosen in Terminator Armour have accidentally been given the option to exchange their Combi-bolters for "Cult Arcana: Pyrae (Pyromancy) (no cost)".

**Comment by capitaladot** [comment]
I think the simplest solution would involve putting the transport options in an entry in the same selection group as Jetbikes, Bikes, and Jumppacks.
