### ISSUE TITLE
Issues with Legions taking Mechanicum units

### ISSUE THREAD

**Issue by TomTheHand** [BSData/horus-heresy#1110]
I've looked over the various ways that Legions can take Mechanicum units (Thallax and Battle-automata), and found some issues.

**Cortex Controllers (AoDAL, pg 131)**

For each cortex controller present in a detachment, 0-1 Thallax, Castellax, or Vorax may be taken.

- [x] Currently, a cortex controller must be taken to cause Thallax and Castellax to appear as Heavy Support options. However, you can currently take any number of maniples; you should only be able to take one per controller.
- [x] There is no validation disallowing Thallax or Castellax if the cortex controller is removed. Also, none are present in the army, the options disappear, but if one or the other _are_ present, the option to add more remains available.
- [x] Vorax should be available as Heavy Support if cortex controllers are present.
- [x] The text states that if Thallax take a Triaros, Marines can't be transported in it; this implies that Thallax should be given the option to take a Triaros dedicated transport.

**Rite of War: Brethren of Iron (AoDAL, pg 101)**

- [x] If Brethren of Iron is taken, no Battle-Automata may take Paragon of Metal.
  _This is currently not implemented; Domitar, Castellax, and Vorax that become available through this Rite have access to Paragon of Metal._
  _Interesting extra twist: RAW, although the Rite allows Castellax as Troops and Vorax as Fast Attack, it does not REMOVE them from Heavy Support, so it seems that they should appear in both places and none of them should be able to take Paragon if this Rite is used (even though RAW the automata in Heavy Support slots would be able to take it if the Rite were not used)._

- [x] It appears that the Castellax in Troops (enabled by this Rite) and the Castellax in Heavy Support use different profiles. Am I right about this, and if so, can they be combined to save memory? (Emperor knows we need that)

- [ ] If Brethren of Iron is taken, Forge Lords and Praevians should be the only Consuls allowed.

- [x] At least one model with a cortex controller must be included for every three cybernetica codex units.
  _Currently, there is a check to ensure that there is at least one cortex controller present. However, there is no one-per-three check._

- [x] The detachment can't have more automata maniples than Legiones Astartes units.

**Praevians (AoDAL, pg 22)**

- [x] The Praevian's unit of automata should not be able to take Paragon of Metal.

- [x] Do the Praevian's Castellax and Vorax use the same profile as the Castellax and Vorax from Brethren of Iron? If not, can they/should they?

**Comment by capitaladot** [comment]
Great report!

**Comment by zopha** [comment]
Castellax in Troops and Heavy Support - It looks like they're separate entries and at first glance, they can be combined to one entry. The Heavy Support one is prefixed with Legion.

Yeap, the Praevian's Castellax and Vorax use the shared entries for both units. That's probably where it's picking up Paragon of Metal.

**Comment by capitaladot** [comment]
@zopha they are different because one needs Category Legiones Astartes.

**Comment by TomTheHand** [comment]
@capitaladot I don't think that's the case; neither the automata supplied by a Cortex Controller nor the ones supplied by the Brethren of Iron rite should have Legiones Astartes so I would imagine they could be combined. The entries that are _already_ combined are those used by the Praevian and the Brethren rite.

The automata that belong to the Praevian have the _option_ of having Legiones Astartes, or can instead take Furious Charge, Tank Hunters, or Scout, which sounds... fun to implement. I hadn't thought about this before (I figured the explanation in the Praevian's rules was sufficient), but I had forgotten about those "Can't take more [x] than Legiones Astartes" rules.

I guess the automata used by the Praevian might need to be broken out to implement their selectable rules.

**Comment by zopha** [comment]
The Praevian automata also get optional extras on top of the LA rule for particular legions.

A simple way would have a Selection Entry Group, hidden, with Min0/Max1 selections with conditionals that change on the presence of a Praevian and choices of
* Legiones Astartes - Legion Inductees (A rules with text: This unit inherits the Legiones Astartes special rule possessed by the Legion Praevian)
* Furious Charge
* Tank Hunters
* Scout

The Praevian will have the rules already and this will save adding 50 links for legion specific rules. We'd just need to decide where the Legion additionals go.

I've been working on the Mechanicum cat so I can practice some of the simpler Category restrictions and get familiar with Mechanicum units again while other work is being done on CAL file so I'll hopefully be ready to tackle this early next week.
