### ISSUE TITLE
Issues with Legion Lords of War

### ISSUE THREAD

**Issue by TomTheHand** [BSData/horus-heresy#1111]
Next up, I looked over the Legion Lords of War and found some issues. I don't feel like I exhaustively tested _everything_, but I've run out of steam and I did find quite a few things.  As usual, I apologize if I've made any mistakes.

**War Machine Detachment (AoDAL pg. 9)**
_Up to 2 Lords of War of the same unit type with less than 9 hull points can be taken in a War Machine Detachment._

- [ ] A decision should be made as to whether to use a "War Machine Detachment" entry or break all <9HP super-heavies into standalone entries, and entries should be moved/deleted accordingly.
  _Currently, Imperial Knights, the Malcador, and the Spartan-based super-heavies (Cerberus and Typhon) are found under the War Machine Detachment._
  _The Spartan-based super-heavies and Malcador are listed as standalone entries as well._
  _The Macharius variants, Crassus variants, and Minotaur are only listed as standalone entries._

The following issue is only relevant if the decision is made to use standalone entries rather than a single War Machine Detachment entry.
  - [ ] The Praetor and the standalone entries for the Malcador and the Spartan-based super-heavies should allow being taken in pairs, but they do not.
    _The War Machine Detachment entry correctly supports its constituents being taken in pairs, and correctly forces the second to be the same type as the first._
    _The Macharius variants, Crassus, Dominus, and Minotaur correctly allow being taken in pairs._	

**Sub-orbital Strike Wing (AoDAL pg. 9)**
_Up to 3 Flyers of the same type with up to 3 hull points (from a specific list) can be taken as a Sub-orbital Strike Wing._

- [ ] As above, a decision should be made as to whether to use a "Sub-orbital Strike Wing" entry or standalone entries, and entries should be moved/deleted accordingly.
  _Currently, the Sub-orbital Strike Wing entry contains Avenger, Lightning, and Xiphon options._
  _The Avenger has a standalone entry as well.
  _The Thunderbolt only has a standalone entry.

The following issues are only relevant if the decision is made to use a single Sub-orbital Strike Wing entry instead of multiple standalone entries.
- [ ] The Sub-orbital Strike Wing entry currently allows a mix of fighters. It should force all fighters to be the same type.
- [ ] The Thunderbolt should be available in the Wing, but currently it is not.
- [ ] The Lightning and Xiphon currently do not appear to be allowed, RAW.
  _They were supported in the original Crusade Army List, which simply specified three <3HP Flyers, but AoDAL appears to specify only Flyers from the list on pg 10 (which contains the Avenger and Thunderbolt). This may be a FW error; I think they meant the Wings can contain fighters the Marines already have access to PLUS the fighters on pg 10. Even if the Wing is meant to be a non-Astartes supporting force, the Lightning is used throughout the Imperium and it seems like a mistake to exclude it._

**Mighty Fortification (AoDAL pg. 9)**
_A single fortification which has a cost >= 500 pts or has any D weapons must be taken as a Lord of War; it can't be taken in a standard Fortification slot._

* The Imperial Castelum Stronghold can be loaded out so that it costs more than 500 points.
  - [ ] If taken as a Fortification and made to cost >= 500 pts a validation error should be thrown.
  - [ ] It should be available as a Lord of War, but if made to cost < 500 pts a validation error should be thrown.

- [ ] The Primus Redoubt should only be available as a Lord of War. Its minimum cost is 650 pts, and it has a D weapon.

* The Imperial Strongpoint and Wall of Martyrs Imperial Defense Network can be loaded out to cost more than 500 points.
  - [ ] If taken as a Fortification and made to cost >= 500 pts a validation error should be thrown.
  - [ ] They should be available as a Lords of War, but if made to cost < 500 pts a validation error should be thrown.

_I am personally a bit unsure that Forge World intends for "formations of fortifications" to be taken as a single formation in Age of Darkness lists, but if consensus is that these are allowed then I won't argue._

**General Lords of War issues**

- [ ] Currently all Baneblade variants can replace sponsons with Targeters. This should not be an option for the Baneblade or Stormlord.

- [ ] The Stormlord should be able to replace any sponson-mounted twin-linked heavy bolters with heavy flamers.

* Many Lords of War have incomplete profiles. I don't know how much detail you want to fill in (hull-mounted bolters and the like), but some important stuff is missing.
  - [ ] The Banehammer, Doomhammer, Dominus, and Macharius variants have no stats for their main guns.
  - [ ] The Macharius Heavy Tank, Macharius Vanquisher, Macharius Vulcan, and Praetor have no statline.
  - [ ] The Thunderbolt is missing most of its statline.
  - [ ] The Marauder has no stats for its bomb loads.

- [ ] The Crassus, Praetor, and Dominus should be able to swap out one or both of the heavy bolters.
  _Currently the Crassus can swap out its side sponsons, but none of these vehicles can currently swap its front sponsons._

- [ ] The Praetor currently forces the user to choose a single missile type.
  _For this unit, the player selects which missile type it carries before the game and notes it down; we should print out information for all three types and include this requirement as a special rule rather than forcing the user to choose one type at the time of army list creation._

**Comment by capitaladot** [comment]
I implemented the War Machine detachment but the others later partially broke things out... I guess because users weren't looking in that container?

As to Targeters being disallowed on Baneblade and Stormlord hulls, can I get a citation on that?

The sub-orbital strike wing as I implemented it allowed only one type. This may be a regression as a mistaken "fix". As to what is included, we should implement RAW and not try to glean intent from background.

The Imperial Strongpoint is itself basically a Formation of Fortifications, so I would take it that others are allowed on this basis as nothing seems to indicate otherwise.

As to missing statlines and weapons, a checklist would be awesome.

**Comment by TomTheHand** [comment]
The ability to take War Machines in pairs works fine in the container and for several of the standalone entries, but the entries that I listed are totally missing that functionality; it's not broken so much as it is nonexistent.

RE: Targeters, I can't prove a negative - if you think they should get Targeters, you should provide a citation showing that they are allowed to take them - but I can give you some places I've checked:

Source | Baneblade | Stormlord
--------|-------------|------------
Crusade Imperialis | pg. 52 | pg. 53
The Horus Heresy Book Four: Conquest | pg. 284 | pg. 285
Escalation: Super-heavy units of the 41st Millenium | pg. 40 | pg. 46
Imperial Armour Volume One - Second Edition - Imperial Guard | pg. 91 | N/A

The Imperial Strongpoint is not explicitly allowed by the Age of Darkness rules, and so it can't be used to justify taking other formations of fortifications.

I have already provided a checklist for the missing statlines and weapons; I'll do a format tweak to make it more obvious.

**Comment by capitaladot** [comment]
Fair point; work log of what you've checked is sufficient on those.
I must have assumed they were more templated than they actually are.

**Comment by HydraulicGold2** [comment]
Only Shadowswords should have the Laser Targeters. I can provide a picture of the various entries from both the Apocalypse book, and Warzone Damocles on Wednesday

**Comment by zopha** [comment]
Is there a definitive book that is considered the correct one to use for all particular type of superheavies? Like Escalation for baneblade chassis tanks (if that's the correct one)

I'll see what can be done quickly and easily for this one, like adding in the main guns and missing profiles/rules but I have a feeling we'll see these in the new HH rule book. My main reason for that is the other sources for rules are now out of print or discontinued after the migration to 8th.

**Comment by capitaladot** [comment]
@zopha No, not one book.

**Comment by capitaladot** [comment]
I would load the 1.x file to copy over the stats for the LoW, which were migrated from there.

**Comment by capitaladot** [comment]
@zopha can you check off what was fixed from the checklist here in your commit, https://github.com/BSData/horus-heresy/commit/5f84718f2bd473349b3b4db3c24f5dc0ed888aa1?

**Comment by zopha** [comment]
I'll start working on this again once I'm finished with Cults and Milita.

Although some of the changes I was aiming for aren't relevant now. The war machine squadron doesn't specify type anymore so it looks like it can be mixed. Also now the detachments are across the game rather than army specific, we need to make a decision to either move the shared ones to the GST (and if they should be moved to the GST at all), maintain individual ones in each catalogue or make a separate Lords of War catalogue that can be loaded as a sub-force (probably the worst option in terms of user comprehension).

**Comment by capitaladot** [comment]
Most of these changed as to how the AoDRB changed LoW choices.
