### ISSUE TITLE
Remove superfluous Legiones Astartes-conferred rules from Legion specific Units

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#1112]
My script that added the rules conferred by Legiones Astartes to all units with Legiones Astartes was not able to discriminate between Legion-specific units and generic units.
Therefor, many Legion specific units have rules on them that will never display (due to modifier/constraint pairs looking for a difference Legion than they belong to).

- [x] Make a list of all rules added by Legiones Astartes and post it on this ticket
- [x] Make a list of all Legion specific units and characters
- [ ] Remove all non-matching Legion specific Legiones Astartes rules (except for Alpha Legion; only show these if the specific Legion a Legion specific Unit belongs to is not in the Force if RoW Coils of the Hydra is in the Force!)
- [ ] Show all Legion specific Units (not Characters or Vehicles) if Coils of the Hydra is in the Force, but limit these to one selection total in the Force

**Comment by zopha** [comment]
I have some of the lists done on a google spreadsheet.

https://docs.google.com/spreadsheets/d/1YWxVlwnBQgC8WJqznWJsrqS2MbaZGDe4dhy0jA93wIs/edit?usp=sharing

Thousand Sons and Spaces Wolves need to be cleaned up but the rest of them will have specific legion units and the name of rules conferred by Legiones Astartes. If anyone wants to add to it then please do, my aim with it was for a quick reference guide by legion for sorting through Battlescribe issues and for tabletop play. I'll expand it to other armies once the legion portions are finished.

**Comment by capitaladot** [comment]
List added as a new tab to the spreadsheet.

**Comment by capitaladot** [comment]
I am going to add a link to the spreadsheet to the Wiki

**Comment by capitaladot** [comment]
List of special units added

**Comment by zopha** [comment]
I've completed the special units from the following

Imperial Fist
Iron Warriors
Emperors Children

File size has decreased 220kb so far. Hopefully, this will be more than 1mb saved when the legion specific units are complete and we'll get below the Java memory threshold on mobile devices.

**Comment by zopha** [comment]
Down to 6.08mb from 6.66mb.

Still have Blackshield, Thousand Sons and Space Wolf units to do.

**Comment by capitaladot** [comment]
Yeoman's work. Shame it isn't more size reduction. I wonder where else
we can make significant reductions?

**Comment by zopha** [comment]
Closing this as it's superseded by the new category rules feature.
