### ISSUE TITLE
Chaplain Power Weapon Missing Free Power Weapon Bug

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#1113]
Seems like with a few of the changes to the weapon profiles it removed the reduction of the power weapon cost for Centurion Chaplins. So should have a reduction of 15pts on the first (and only the first) Power Weapon that they take.
This bonus should be for any "Power Weapon" of Sword, Maul, Axe. It also counts for Nostroman Chainglaive (Nightlord), and Power Glaive (White Scars) at the reduced cost as they are allowed to trade any option of being able to take power weapon for free to these items.

**Comment by Mayegelt** [comment]
Also noticed similar issue for Librarian. You have the option to "Upgrade power weapon to:" but again you are being charged for the power weapon and not given a selection option for that power weapon to be a force weapon. And are still getting charged the 15pts for it.

**Comment by alphalas** [comment]
>Seems like with a few of the changes to the weapon profiles it removed the reduction of the power weapon cost for Centurion Chaplins. So should have a reduction of 15pts on the first (and only the first) Power Weapon that they take.
This bonus should be for any "Power Weapon" of Sword, Maul, Axe. It also counts for Nostroman Chainglaive (Nightlord), and Power Glaive (White Scars) at the reduced cost as they are allowed to trade any option of being able to take power weapon for free to these items.

You're half right - the current implementation is broken; however, the Power weapon options (Axe/maul/sword) are very different from the Legion Specific "power weapons"; LS PW are not listed as part of the basic group and as such no eligible for the crozius.

>Also noticed similar issue for Librarian. You have the option to "Upgrade power weapon to:" but again you are being charged for the power weapon and not given a selection option for that power weapon to be a force weapon. And are still getting charged the 15pts for it.

This is also an incorrect implementation - the only way a librarian can exchange a PW for FW is actually if he's in TDA - in PA, he can only exchange a CCW/Chainsword for a FW.

Both fixes will be applied for *correctly* align with LA:AODAL

**Comment by Mayegelt** [comment]
The Nostroman Chainglaive thing had been answered by Alan Bligh and quoted in a thread long long ago on here.
"Any character or independent character with the legiones astartes (night lords) special rule eligible to take a power weapon as part of their options, may instead take a nostraman chainglaive for the same listed cost."
This meant that the Centurion taking the. Chaplain option gains a power weapon, what is then able to be exchanged for the chainglaive. So their weapon of office is actually the glaive for them if they wish.
Same goes for Whitescars.

Again nothing was ever posted as an FAQ, but repeated emails had come back to those who asked with the same answer, as they were weapon options that could be exchanged.

**Comment by alphalas** [comment]
If it's not in an FAQ, we are not implementing it

**Comment by alphalas** [comment]
We do not trust Forge World emails, and the word of Bligh has been often miss quoted.

**Comment by Mayegelt** [comment]
Well it used to be on here. Aldo if read above then it says directly that a power weapon can be exchanged for the weapon. So in black amd white it is written, so can be done.

**Comment by Mayegelt** [comment]
That quote being from the nightlords section of red/black books. Not a quote from forgeworld

**Comment by alphalas** [comment]
But it's not a PW - it's a crozius; which is a type of PW defined by the model. It's not happening.

**Comment by Mayegelt** [comment]
Crozuis Arcanum - power weapon (type as shown on model).
Direct quote from the chaplin consul bit.
It clearly says it is a Power Weapon.
As much as you don't want it to be one it is.
I believe Capitaladot was the one who agreed it last time when i had to mess with the files to fix it as i had to make some bizarre code solution just incase someone wanted a glaive and power axe or whatever, so only 1 would be discounted.

**Comment by alphalas** [comment]
Fine, fine - I'll implement it later

**Comment by alphalas** [comment]
Also, for future reference @Mayegelt; discussions like this belong in the Gitter chat, not here.

**Comment by Mayegelt** [comment]
Sorry to be a pain about it.
I have once again petitioned for an update to the 30k FAQ to clarify this. Hopefully they will.

I appreciate the work you are others do on here. I used to help with some around a year or 2 ago, but mainly tried to keep it up to date before BS2 hit.

**Comment by capitaladot** [comment]
@Mayegelt I wouldn't hold your breath. With the loss of Mister Bligh, and the obviously hackneyed and rushed jobs of HH Book 7 (Inferno) and the IA Indices for 8th, I think it is clear that the Eye of Sauron has turned away from any kind of quality control or product support.

**Comment by capitaladot** [comment]
@alphalas ready to merge?
