### ISSUE TITLE
References for Unique Characters 

### ISSUE THREAD

**Issue by HydraulicGold2** [BSData/horus-heresy#1136]
So I'm not sure if this is an isolated issue or not, but I have noticed at least 1 Unique character (Khyr Vhalen) doesn't have the rules reference for his weapons in his profile (Paragon Blade, Volkite Charger). Would it be possible to get this fixed?

**Comment by capitaladot** [comment]
Thanks for the report. 
The original maintainer didn't see fit to include these things, but we're trying to fill in as we go.
Feel free to report as many of these as you like, especially if you can list the things that are missing like you've done here.

**Comment by zopha** [comment]
Yeap, lists are great and will help get through stuff fairly fast.

Since you mentioned Khyr Vhalen, he's one I looked at recently and the updates will be in the next release, I'm just trying to get #1112 finished before that. Chances are I'll get most of this done with that update so might wait a few days for it before creating a list and finding half of it is done.

Here is his updated profile, anything missing?
![2017-10-10 06_41_50-view roster_ new roster warhammer 30 000 - the horus heresy v89](https://user-images.githubusercontent.com/1666415/31371074-05312b6c-ad87-11e7-8fd6-5c6145bdd579.png)

**Comment by zopha** [comment]
I've pushed a release and it should be live by tomorrow morning. @HydraulicGold2 can you update and have a look through the Unique Characters when you have time and see if I've missed any of them. Should have gotten most of them outside the Thousand Sons and Space Wolves.

**Comment by HydraulicGold2** [comment]
Will do

**Comment by HydraulicGold2** [comment]
Every Character from the Legion Specific Red Book, and Book 6 besides any Dreadnoughts, I will double check them soon
Lord Commander Eidolon needs Frag and Krak
Captain Tarvitz needs Frag and Krak
Fulgrim needs Plasma and Krak Grenades
Erasmus Golg entry missing
Khyr Vhalen needs Frag and Krak, Melta Bombs
Perturabo needs Cognis Signum, and Frag
Alexis Polux needs Power Fist, Combi-Melta, Frag and Krak
Rogal Dorn needs Frag Grenades, and rules for Teleport Homer
Flaymaster Mawdrym entry missing 
Sevetar mention Master Crafted on Chainglaive, Frag and Krak
Konrad Curze needs Frag Grenades
Castrmen Orth needs Frag and Krak
Ferrus Manus Grenade Harness should mention unlimited use
Centurion Shabran Darr needs Master Crafted Chainaxe, Frag and Krak
Kharn needs Frag and Krak 
Angron needs Frag
Captain Remus Ventanus needs Power Sword, Bolt Pistol, Melta bombs, Frag and Krak
Guilliman needs Frag
Section Leader Crysos needs Combi-Flamer, Frag, Krak and Rad
Marshall Durak Rask needs Frag and Krak 
Mortarion needs Frag
Maloghurst needs Power Sword, Boltgun, Bolt Pistol, Frag and Krak 
Loken needs Frag and Krak 
Horus needs Cognis Signum and Frag
Erebus needs Frag and Krak 
Kor Phaeron needs pair of Lightning Claws 
Zardu Layak needs Bolt Pistol, Frag and Krak 
Hol Beloth needs Frag and Krak 
Anakantis Kul Blade Slaves need Plasma Pistols
Lorgar needs Frag
Cassian Draco needs Smoke Launcher and Search Light
Lord Chaplain Nomus needs Boltgun part of Combi-Flamer, Frag and Krak 
Vulkan needs Furnace's Heart (Rg 18", Str 6, AP 2, Assault 1, Rending, Line of Effect: 1mm wide line 18" long drawn out from Vulkan, that may not cross Friendly models. Units hit suffer a number of hits equal to Models crossed by the line)
Strike Captain Alvarex needs Frag and Krak 
Moritat Prime Kaedes needs Frag and Krak, and Melta bombs 
Corvus Corax needs Frag, and to specify 2x Archeotech Pistols. Sable Armour should degrade to 3+ when Deadly Prey selected
Dynats Artificer Armour makes him 10pts too expensive, should be Venom Spheres instead of Frag Grenades
Exodus needs Melta Bomb, Frag should be Venom Spheres
Alpharius needs Master Crafted Plasma Blaster, and profile for Venom Spheres 
Nathaniel Garro needs Master Crafted Bolt Pistol, Frag and Krak 
Tylos Rubio has blank entries for Psychic Hood and Force Sword. Needs Master Crafted Bolt Pistol, Frag and Krak
Nemean Reaver needs Master Crafted Bolt Pistol, Frag and Krak 
Endryd Haar needs Frag and Krak 
Autilon Skorr needs Frag and Krak, and Master Crafted Power Axe entry is blank
Gahlan Surrlakk needs Frag and Krak 
Shadrak Meduson needs Master Crafted Boltgun
Narik Dreygur needs Frag and Krak, and Master Crafted Bolt Pistol
Kheron Ophion needs Melta bombs, Frag and Krak 
Xiaphas Jurr needs Master Crafted Power Maul, Frag and Krak

**Comment by capitaladot** [comment]
Thanks for this list, @HydraulicGold2

**Comment by Mayegelt** [comment]
@capitaladot I think this might be the first port of call for old fixes. I will assume most if not all are already done. But its worth having a check and making sure.

**Comment by Mayegelt** [comment]
All complete and about to be thrown in the push
