### ISSUE TITLE
Dark Compliance - Not counting Praetor or Centurions

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1137]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.01.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Legiones Astartes: In 'Armies of Dark Compliance', an error message says that the army must have 1 or more selections of praetor/cent (minimum 1). 
However, I already have a few centurions and a praetor, with Power Armor(praetor/cent).

Make an empty Armies of Dark Compliance list and add some centurions. The error message won't go away.

**Comment by archonkain** [comment]
Overlapping issue with bug #1092

**Comment by zopha** [comment]
I'll close this one off as a duplicate and work on #1092
