### ISSUE TITLE
Imperialis Militia and Cults - Warmaster's due rule active when it should not be

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1144]
**File:** (HH) Imperialis Militia and Cults Army List.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** Imperialis Militia and Cults always has the warmaster's due rule. Even when creating a brand new roster with the detachment chosen being "age of darkness" or "allied" and not army of dark compliance

**Comment by TomTheHand** [comment]
This was reported [here](https://github.com/BSData/horus-heresy/issues/1097), but the issue was closed before it was addressed.
