### ISSUE TITLE
Legion Centurion Default Selection Issues

### ISSUE THREAD

**Issue by archonkain** [BSData/horus-heresy#1161]
Please set the default Terminator Weapons choices to none.
Also, could you please set the mobility default selection to "On Foot" and armor to "Artificer Armor" so that when the praetor is added there are minimal errors thrown?

Thanks

**Comment by zopha** [comment]
Just to make sure, the Terminator Weapons choice is for the Centurion only?

And "On Foot" and "Artificer Armour" is Praetor only?

**Comment by capitaladot** [comment]
No in either case. Something has gotten confused.

**Comment by zopha** [comment]
The default terminator weapon choice was set so the Preator entry had a validation error when innitially added, you had to change to terminator armour, set the weapon group to none and then go back to power armour.

On Foot and Artificer armour has been set as the default selection as it's the default in the profile and to minimise validation errors when innitially added.
