### ISSUE TITLE
Typhon pintle weapons costs

### ISSUE THREAD

**Issue by archonkain** [BSData/horus-heresy#1163]
The costs for pintle weapons on the Typhon are incorrect

they should be
twin-linked bolter - 5
combi weapon - 5
heavy bolter - 10
heavy flamer - 10
multi-melta - 15
havoc launcher - 15

right now the incorrect ones are
combi weapon - 10
heavy bolter - 15
heavy flamer - 15
multi-melta - 20

**Comment by zopha** [comment]
What book are you using? These costs got updated with the last release of the legion army list red book.

**Comment by archonkain** [comment]
This is what I am working from

![image](https://user-images.githubusercontent.com/31388903/32146593-a3e5c978-bca7-11e7-8149-21d64be284d1.png)

**Comment by capitaladot** [comment]
Looks like I missed that most superheavy pintle costs didn't change... except the Typhon.
