### ISSUE TITLE
Fellblade Missing 

### ISSUE THREAD

**Issue by thebiggeordiegeek** [BSData/horus-heresy#1175]
Just updated my datafiles and the Fellblade has disappeared as an option for a Lord of War.

Obviously I am assuming something got broken somewhere.

**Comment by zopha** [comment]
It's there for me using the most current files, are you looking under L for Legion Fellblade instead of F For Fellblade, Legion?

[Lord of War list in battlescribe](https://i.imgur.com/psJxA4p.png?1)

**Comment by thebiggeordiegeek** [comment]
Found it, but had to add another force org to get it to show up, it’s simply missing from the Lord of War list I have here in this particular force org.

**Comment by zopha** [comment]
Which force org are you using and is it the only LoW tank missing from that one?

**Comment by capitaladot** [comment]
Non-response, so closing.
