### ISSUE TITLE
Forge Lord Errors

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1189]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.01.05

**Platform:** Windows

**Dropbox:** No

**Description:** There are two errors in the Forge Lord Consul entry. The first is that Forge Lords come with Artificer Armour. Currently I am forced to check "Artificer Armour" in the Consul entry, at a cost of 10 points. Thus I either have a validation error, or my army list is 10 points overcosted. The second is that the power weapon option is listed at 10 points, when it should be 15. Thanks so much for your hard work!

**Comment by capitaladot** [comment]
This was fixed.
