### ISSUE TITLE
Blood Angels - Day of Revelation - restrictions for Elite/Flyer choices

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1194]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.01.09

**Platform:** Android

**Dropbox:** No

**Description:** Blood Angels Day of Revelation adds a required flyer for every elites choice selected.

**Comment by capitaladot** [comment]
I had implemented this but I believe it was removed by someone else's bug report. I'll look again at the actual text and make another pass.
