### ISSUE TITLE
Testing rules linked to Categories

### ISSUE THREAD

**Issue by zopha** [BSData/horus-heresy#1198]
Test branch has been created called CALCategoryRuleTest - https://github.com/BSData/horus-heresy/tree/CALCategoryRuleTest 

A new Category has been created solely for testing purposes called TestCALEntry in the "(HH) Legiones Astartes - Crusade Army List.cat" file.

The only unit that it has been linked to is the Tactical Support Squad, Legion.

-------

**Bugs**
Rules don't update if you swap legions 
**Setup and Testing**

1. Create a new roster using the Legiones Astartes catalogue, using The Age of Darkness Force Org.
2. Add "and Allegiance, Legion" from the Allegiance Category.
3. Set Allegiance (choose loyalist or traitor for testing) I went with Loyalist and Space Wolves.
4. Select one legion.
5. Add the "Tactical Support Squad, Legion" to your roster.
6. You should now see legion specific rules in View Roster.
7. Go back to "and Allegiance, Legion" and change your legion to another.
8. View Roster will show the same Space Wolf rules.
9. Delete the "Tactical Support Squad, Legion" unit and re-add it, it will now show the correct rules for the selected legion.

-------

**Bugs**
Instance of Ancestor condition does not trigger
**Setup and Testing**
More testing is required to verify this and create steps to reproduce this.

-------

**Comment by zopha** [comment]
**Bug**
If you delete a Category and have entries that use it you have no option available to remove that defunct Category from the entry.

**Comment by zopha** [comment]
**Possiable Bug/Working as intended - Clarification needed**
Rules added to a Category will only appear in View Roster if the category is selected on the Root Selection Entry.

**Comment by capitaladot** [comment]
I would say this is a bug, as we need the feature for the Legion Centurion
entry.

**Comment by zopha** [comment]
Yeap. It would be very handy for the Knights as well. They're in the GST so
setting up a Super-heavy walker category as its outlined in the book would
be handy as it would trickle down the each catalog. Same for primarchs,
Super-heavy tank, etc.

**Comment by Jonskichov** [comment]
Fixed in:
2.01.08 (desktop)
2.01.11 (Android)
2.01.10 (iOS)
