### ISSUE TITLE
Iron Warriors Warsmith - Father of the Brethren of Iron

### ISSUE THREAD

**Issue by archonkain** [BSData/horus-heresy#1199]
Father to the Brethren of Iron: *Not a real entry/rule/wargear. Fabricated by Millicant to ensure Battlescribe works correctly with the Brethren of Iron Rite of War.

This artifact is still in.

**Comment by zopha** [comment]
Yes, I'll remove the rule with that text for now for a minor cosmetic fix to this.

The real solution will be to transition that entry to a category and this entry can be deleted completely.

**Comment by capitaladot** [comment]
Warsmith was actually a bit more screwed up, but I have sorted it out.

**Comment by capitaladot** [comment]
So, deleting this caused many problems.
