### ISSUE TITLE
Power Weapons - Lance

### ISSUE THREAD

**Issue by archonkain** [BSData/horus-heresy#1201]
Power Lances should not be an option but they are listed when selecting power weapons.  Lances are in the 7th 40k book,  but excluded in the HH ones.

![20171210_150318](https://user-images.githubusercontent.com/31388903/33809362-4bc35ba4-ddbb-11e7-9a4a-d17bc23da051.png)

**Comment by zopha** [comment]
Since all indications are pointing to a heresy rule book release in the next few weeks we might leave this until then and see what it contains on the Power Lance.

**Comment by archonkain** [comment]
That sounds like a good plan

**Comment by zopha** [comment]
Power Lance is in the new HH rule book.

![Power weapons from HH rule book](https://i.imgur.com/NTCxz7A.png)
