### ISSUE TITLE
Praetor, always registers as Wolf Lord/Claw Leader

### ISSUE THREAD

**Issue by InfiniteFreedom** [BSData/horus-heresy#1208]
No matter what Legion I choose to use, the Praetor, Legion entry always says it is a Wolf Lord/Claw Leader.

**Comment by zopha** [comment]
It was hidden before Battlescribe was updated to display categories in the roster. I'll see what I can do to hide it again or fix it.

**Comment by capitaladot** [comment]
Appears fixed.
