### ISSUE TITLE
Imperial Knight Crusade, some knights undercosted.

### ISSUE THREAD

**Issue by InfiniteFreedom** [BSData/horus-heresy#1209]
Hi,
I've noticed that the Questoris Knights Warden, Gallant and Crusader are 10 points under their listed cost in the Crusade Imperialis Red Book.  Just an FYI.

**Comment by zopha** [comment]
This has been updated and pushed out in #1206 

I didn't put the # in front of 1209 in the commit so it didn't auto close this when merged.
