### ISSUE TITLE
VI Legion: Grey Slayers - Power Weapon Selection

### ISSUE THREAD

**Issue by rsimmerm** [BSData/horus-heresy#1210]
When selecting a power weapon upgrade for a Grey Slayer, it's supposed to exchange their combat blade/chainsword, instead it says "Hidden" and gives an error/invalid list in red.  The combat blade/chainsword is still under the Grey Slayer along with the new power weapon chosen.  

[greyslayer_error.docx](https://github.com/BSData/horus-heresy/files/1584607/greyslayer_error.docx)

**Comment by zopha** [comment]
Fixed in #1224, it'll be in the main files when #1219 is merged so I'll close this off.
