### ISSUE TITLE
Outrider Squad - Meltabombs / Sergeant cost issue

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#1214]
It seems like when you add meltabombs to your outrider if you have a sergeant upgrade. It charges you an additional 5 points. As if it treats him as an extra model, rather than an exchange of a normal outrider to sergeant. 
Seems like Jetbike Sky Hunter squads are not affected in the same way

**Comment by capitaladot** [comment]
Appears someone re-factored them and marked Sergeant as a Model (when it is priced only as an Upgrade).
