### ISSUE TITLE
Sub Orbital Strike Wing - Avenger

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#1225]
The Sub Orbital strike wing for marines is showing the 'Imperial avenger strike fighter'
It should be the 'Crusade fleet avenger strike fighter' from the Mecanicum book.
Also the weapon options seem to have mistakes (or it might be imperial had different to crusade).
The 2 autocannon, 2 missile launchers, 2 multilasers should all be 20pts rather the 30pts listed.
It should not have an option for Hellstrike Missiles. But should have option for 2 Kraken Penetrator heavy missiles for 25pts.

**Comment by capitaladot** [comment]
Good catch; the old entry was for the Avenger from Imperial Armour (as that was previously where one was directed to take the rules from). Now, you are directed to take them from other red books, so this should indeed change.
