### ISSUE TITLE
What on earth happened to the legion list interface??

### ISSUE THREAD

**Issue by Zuul-DG** [BSData/horus-heresy#1226]
Somebody made it basically model by model.  Makes putting together an army list of any size a much more time intensive.

**Comment by alphalas** [comment]
You should only need to select the legion checkbox in a shattered legions list iirc

**Comment by capitaladot** [comment]
He us complaining about the refactors that broke out things like Veterans
as model by model. It might be more exact, but it is a lot more clicks to
build a unit.
