### ISSUE TITLE
Rename entries that contain Legion Specific Replacements

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#1230]
E. G., if a Thunderhammer allows a Solarite Power Gauntlet, rename the containing label to include both options.

**Comment by zopha** [comment]
Do mean change entries so they look something like this?

![image](https://i.imgur.com/T5PafEb.png)

**Comment by capitaladot** [comment]
I mean rename the outside container dynamically when the number of interior
choices increases because of a Legion specific option. We can append text
to make the Thunderhammer fieldset text above the options say
"Thunderhammer or Solarite Power Gauntlet" so the output makes more sense
in the print view.
