### ISSUE TITLE
Dark Angels - Acid rounds on Attack Bike

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1238]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** Yes

**Description:** In the legions Astartes attack bike entry, specifically for Dark Angels, acid rounds are 0 points instead of 5 each

**Comment by capitaladot** [comment]
Thanks, will fix.
