### ISSUE TITLE
 Imperialis militia and cults army list "Imperialis Militia Platoon Command Cadre" is not considered a legal compulsory HQ choice 

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1240]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Imperialis militia and cults army list "Imperialis Militia Platoon Comand Cadre" is not considerd a legal compulsory HQ choice by Batelscribe, it Reports list must have 1 more selection from Compulsory HQ. Imperialis Militia Platoon Comand Cadre should be edited to be a legal compulsuary HQ. Information based on the "Crusade Imperialis Army lists" (Red Book)

**Comment by capitaladot** [comment]
Thanks for the report. Will fix.

**Comment by capitaladot** [comment]
This is super borked by the move of Categories to the GST.
