### ISSUE TITLE
Linked Terminator Armor Cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1242]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** No

**Description:** In Space wolves rules the Hvarl Red-Blade cost is wrong when added to a list. The cost of a terminator armor seems to be added to the base cost. 
Same thing happens when you add a terminator pattern to terminator Command Squad.

**Comment by capitaladot** [comment]
Probably good to check all characters with Terminator armor for this and 0 out the cost... Or 0 out global cost and set on Praetor, Consul, Space Wolves characters.

**Comment by capitaladot** [comment]
Could just be linked to the wrong Terminator Armor entry.

**Comment by zopha** [comment]
Set points to 35 if Ancestor Instance of HQ is doing this. I've moved the entries around and it's changed from this

[Imgur](https://i.imgur.com/b1v9Bn4.png)

To this

[Imgur](https://i.imgur.com/Sc8cEKL.png)

Better/Worse/Does the job :shipit: ?

**Comment by capitaladot** [comment]
That's probably my goof. Maybe use a Centurion/Praetor category instead of HQ?

**Comment by zopha** [comment]
The first has linked selection entries with profiles linked in them. The second is just linked profiles. While the output isn't exactly the same the recent upgrades make the Unit and wargear standout more. This wasn't the case before and didn' clearly lay out what each unit had. 

Using profiles instead may be viable now, this means we can eliminate Selection Entries for wargear that doesn't change, so will help shrink the CAL file. 

Although some work will need to be done to get the bodyguard unit in Master of the Legion working so it hides PA if the Parent has Terminator armour selected. That used to work so I'm not sure where it got removed but it's not essential.
