### ISSUE TITLE
Legion selection issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1245]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.09

**Platform:** Linux

**Dropbox:** No

**Description:** Legiones Astartes: Age of Darkness Army List v505: Only traitor legion appear even when selecting Loyalist. Show up today (February the 8th) after data file were updated. Regards

**Comment by capitaladot** [comment]
That's super weird. Will investigate.

**Comment by zopha** [comment]
Tested on android and windows with fresh data files and I'm not seeing the same problem.

I'd suggest clearing out your catalogue data and see if that helps. You can delete data from the menu in Manage Data. Take a look at this: https://battlescribe.net/?faq=refreshData

**Comment by zopha** [comment]
No response/update on this so closing.
