### ISSUE TITLE
Talons seekers cost

### ISSUE THREAD

**Issue by Hasfodel** [BSData/horus-heresy#1253]
Seeker squad invalid point cost for demolition charge (should be 10pts) and grenade launcher (should be 5pts/model)

**Comment by zopha** [comment]
@Hasfodel which unit is this? I had a look at Legion Seekers and they can't take a Demolition charge. There's a unit in Solar Aux/Milita that can but I'm not sure if that's the one.

**Comment by Hasfodel** [comment]
In Inferno

**Comment by Hasfodel** [comment]
And in fact, the incorrect point cost for the grenade launcher option only occur when the demolition charge is selected
Jumping from 25 (correct) to 30, for 5 models

**Comment by zopha** [comment]
That's intended for the unit. The Breacher Charge option is actually adding another model "Seeker w/ breaching charge" w/ seems to be shorthand for with so it's adding an additional Seeker (+10 points) with a breaching charge (+10 points) and as that's an additional model the Grenade launcher goes up by 5 (6 models x 5 points)

Just decrement the Seekers count by 1 for a five model unit with a breaching charge.

**Comment by Hasfodel** [comment]
Oh right ! 
Didn't noticed because it's less clear on that unit than on the troop choice that it's another model, and not the same presentation
