### ISSUE TITLE
Legiones Astartes - Grey Slayers - missing option for Huscarl

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1258]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.09

**Platform:** Mac

**Dropbox:** No

**Description:** Space Wolves Legions Astartes List, Grey Slayers Entry; Huscarl should have access to list “Any model in unit may take one of the following: (none), bolter (2pts), Combat shield (3pts), Heavy Chainsword (3pts), power weapon (5pts)

**Comment by zopha** [comment]
This is covered in #1241 and will be in the main files once we review the changes.
