### ISSUE TITLE
Rite of war question

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1259]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.01.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Rite of Wars im Horus Heresy v92 cant be choosen/aint there.

**Comment by capitaladot** [comment]
Look under Legion/Allegiance/Theme.

**Comment by zopha** [comment]
Rite of War has moved from the unit entry.

Add in your master of the legion and then scroll down to the Allegiance section and Rite of War entry to choose one. Set your Allegiance (Traitor/Loyalist) and legion first for the legion specific ones to appear.
