### ISSUE TITLE
Cyber-augmentics provenance valadation error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1261]
**File:** (HH) Imperialis Militia and Cults Army List.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Whatever choice made in an allied detachment of Imperialis Militia and Cult Army list will result in "has X too many selections from Allied Detachment (maximum 0)".
Whenever choose Cyber-augmetics from the Muster of Worlds of a Force Commander, even without choosing Gene-crafted, will result in "has 1 too many selections of Cyber-augmetics (maximum 0)"

**Comment by capitaladot** [comment]
Possibly that was a condition that should have been on Tainted Flesh or Cult Horde?

**Comment by zopha** [comment]
Could be, I have some of the provenances working now and I'm working through the rest of them.
