### ISSUE TITLE
LoW limit not validating properly on optional force orgs

### ISSUE THREAD

**Issue by zopha** [BSData/horus-heresy#1264]
It seems to be working fine with the The Age of Darkness (Crusade) force org but not on the others like Onslaught.

Onslaught
![Imgur](https://i.imgur.com/hISL0Uj.png)

Crusade
![Imgur](https://i.imgur.com/NhgoNWx.png)

so we should standardise it across force orgs.

Source: http://www.bolterandchainsword.com/topic/344651-onslaught-low-question/

**Comment by capitaladot** [comment]
Onslaught has max 25% LoW?

**Comment by capitaladot** [comment]
So it does...

**Comment by capitaladot** [comment]
@zopha yeah, these should definitely be 25% in Force.

**Comment by capitaladot** [comment]
I guess I am confused now how one is ever to take a Warlord Titan in any Force.

**Comment by capitaladot** [comment]
Mystery solved!
Leviathan Army Special Rule:The Leviathan Lord of War

The centre and destructive heart of this army is its Leviathan. This must be a Lords of War of either the Engine of Destruction or Great Beast type. **Unlike usual Lords of War, this may represent any percentage of your army value (and indeed constitute your entire force in a single model if you are so inclined, brave enough and your opponent agrees!).** In contrary to the usual rules, this Leviathan is both your force’s Warlord effectively (and uses its own special Warlord trait listed here) and is also a scoring unit.
