### ISSUE TITLE
Magos reductor paragon blade option does not display correctly. It appears to be set to hidden if no selection of archmagos is made, however reductor has a separate and bespoke selection of archmagos reductor instead of archmagos (shared) and it doesn't trigger as it should.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1269]
**File:** (HH) Mechanicum - Taghmata Army List.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** Magos reductor paragon blade option does not display correctly. It appears to be set to hidden if no selection of archmagos is made, however reductor has a separate and bespoke selection of archmagos reductor instead of archmagos (shared) and it doeesn't trigger as it should.

**Comment by capitaladot** [comment]
Thanks, will address.
