### ISSUE TITLE
Power Weapon costs for Power armour and Artificer Armour should be +15 points, currently showing as +10 points (Age of Darkness Army List, pg 18)

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1270]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** Yes

**Description:** Centurion, Legion
Power Weapon costs for Power armour and Artificer Armour should be +15 points, currently showing as +10 points
(Age of Darkness Army List, pg 18)

**Comment by capitaladot** [comment]
Thanks, will address.
