### ISSUE TITLE
 Legion Praetor, when choosing the Salamanders legion option, does not show the option for taking a Dragonscale Storm Shield for +10 Points when in Artificer Armour (Age of Darkness Legions, pg. 107)

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1271]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** Yes

**Description:** Legion Praetor, when choosing the Salamanders legion option, does not show the option for taking a Dragonscale Storm Shield for +10 Points when in Artificer Armour
(Age of Darkness Legions, pg. 107)

**Comment by capitaladot** [comment]
Thanks, will address.
