### ISSUE TITLE
HH Mechanicum

### ISSUE THREAD

**Issue by lacyj3** [BSData/horus-heresy#128]
iPhone 5S

Legio Cybernetica Castellax Class Battle-Automata Maniple - Weapon profiles not showing:  Darkfire Cannon, Multi-Melta, Flamer, standard bolters.   Most weapons not showing.

* Same unit - When no optional weapon is chosen the standard Mauler Bolt gun and Stock Chargers don't show on the profile.

Mago - Abeyant - not showing on the HQ descriptions or in hte summary.

Mechanicum Thallax Cohort - Heavy  Chan Blade not showing.

Tech-thrall Adsecularis - there weapons are not showing on the profile at all.

Scyllax Guardian-Automata Covenant  - Their standard weapons aren't showing at the top where it shows their specials and all.

Navigator - Digital Lasers not showing under weapons or summary.

**Comment by capitaladot** [comment]
Please re-check against the new Taghmata Army List file.
