### ISSUE TITLE
Allied Detachment says "(Roster Name) has (Number of selections) too many selections from Allied Detachment".

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1281]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Allied Detachments still don't work... Now it just says "(Roster Name) has (Number of selections) too many selections from Allied Detachment".

**Comment by capitaladot** [comment]
Which parent detachment? Can't reproduce on desktop.
