### ISSUE TITLE
Profiles/Stats missing from view roster

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1282]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** When making a list with this file. I can not view the stats on anything I input. Other people I know don't have this problem but it has been an issue before

**Comment by zopha** [comment]
Battlescribe can do this sometimes when it hits a memory limit.

First check that low memory mode isn't enabled. It's menu option in android.
![Imgur](https://i.imgur.com/JlOALzG.jpg)

Second. Clear out your catalogue data and see if that helps. You can delete data from the menu in Manage Data. Take a look at this: https://battlescribe.net/?faq=refreshData
