### ISSUE TITLE
Castallax / Vorax option not appearing for Praveian unit

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1290]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.99

**Platform:** Windows

**Dropbox:** No

**Description:** The Praverian upgrade for the Astartes consul does not have the option to add a Castallax or Vorpian(?) robot squad as an upgrade.

**Comment by zopha** [comment]
Vorax also not appearing as a Heavy Support choice when a cortex controller is included in the army.

**Comment by capitaladot** [comment]
Looks like someone deleted all of the Legion Inductee units and rules and made some additional bogus links in the root for the Praevian's unit (not where they should be; they are children of his unit entry).
I believe this will be the third time I have entered these rules
