### ISSUE TITLE
When selecting the Type on consul from Centurion, legion it disappears and you can no longer choose its type

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1297]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.01.10

**Platform:** Windows

**Dropbox:** No

**Description:** When selecting the Type on consol from Centurion, leion it dissapeaers and you can no longer choose its type

**Comment by capitaladot** [comment]
Seems related to https://github.com/BattleScribe/Release/issues/7

**Comment by capitaladot** [comment]
Bug appears fixed. Please re-update Battlescribe for Windows and re-test.
