### ISSUE TITLE
Xiphon is missing the 2 twin-linked lascannons .

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1300]
There are no "heavy weapon" options for the tactical veterans and the Xiphon is missing the 2 twin-linked lascannons .

**Comment by capitaladot** [comment]
The Xiphon complaint is legit.

The Vet Heavy Weapons are under the Vet with Special Weapons, so I am re-naming that entry to contain Heavy in the name (it is not a book entry, so someone must have created it for convenience or something; in any case, it led to user confusion and complaint).
