### ISSUE TITLE
Move all Shared Selection Entries of type Upgrade, and without Modifiers or Constraints, into the GST

### ISSUE THREAD

**Issue by ghost** [BSData/horus-heresy#1310]
My hope is that this will help the performance of the Astartes file. It should also give us an opportunity to further consolidate duplicate Profiles.

**Comment by capitaladot** [comment]
Aiming to fix cases like https://github.com/BSData/horus-heresy/issues/1286

**Comment by Mayegelt** [comment]
@capitaladot I think to do this, I would need a list generated of what needed to be moved. Big issue seems to be that a lot of things if moved to GST then can't interact with the Legions or RoW for modifications.
I've made several attempts to move as many profiles / rules as I can up to the GST which are shared, but I think I need a lot more help with that.
