### ISSUE TITLE
Compulsory Troops choices within the army must use the same Arcana as the army’s Warlord (or in the case of an Allied Detachment, the same Arcana as the Detachment’s compulsory HQ choice).

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#1324]
This is going to be very tricky to implement... I suppose it will involve min1 on the  Cult Arcana in Compulsory Troops based on the selection of Cult Arcana among Compulsory HQ.

**Comment by capitaladot** [comment]
And, of course, implementing this on the shared entries and the links to them doesn't work.

**Comment by capitaladot** [comment]
![categoryselectorsdon twork2](https://user-images.githubusercontent.com/1619329/38783205-262665ec-40cd-11e8-902a-05644744d322.png)

**Comment by capitaladot** [comment]
![categoryselectorsdon twork1](https://user-images.githubusercontent.com/1619329/38783240-952a6a9c-40cd-11e8-9e43-742b195d6954.png)

**Comment by capitaladot** [comment]
Neither of the above screenshots have any effect. I guess this is either something that is bugged, or just not implemented (despite UI options that allow it). @Jonskichov

**Comment by Mayegelt** [comment]
@capitaladot maybe time to revisit this? Do something similar to compulsory scions.
Though this would need to be a separate box to tick that only showed if the unit has "compulsory" category flagged on. And like the scions only flags if the right arcana is on.
Link the min requirement to multiple categories that flag on if warlord is selected to match that Arcana.

**Comment by Mayegelt** [comment]
@capitaladot Looks like I've just got this one sorted in my latest pull request. Just waiting on testing from friends and yourself if you want :D
