### ISSUE TITLE
Create an Experimental Category with the Experimental Rule Attached, and Tag Items

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#1326]
So, I mistakenly brought a Sicaran Arcus to Adepticon not even having considered that (because of very low output from FW) this tank is still not in a book, along with the other turreted Sicaran variants, the new Termite, and probably a bunch of other models. Let's mark things so such mistakes are harder to make.

- [ ] Termite
- [ ] Sicaran Arcus
- [ ] Sicaran Punisher
- [ ] Sicaran Omega

**Comment by eaxexe** [comment]
The Termite isn't marked as "Experimental" in the PDF's from FW, unlike the Sicarans :)

**Comment by capitaladot** [comment]
Most interesting. Perhaps the experimental black mark is no longer a thing?

**Comment by eaxexe** [comment]
Might be! I still see it in the Sicaran's PDF's, but it'd make sense for them to no longer release models with it.

**Comment by Mayegelt** [comment]
No more experimental units.
