### ISSUE TITLE
Abbaddon, says he cannot have legionnaires astartes selection on his selection

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1335]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.01.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Sons of Horus error with abandon, says he cannot have legionnaires astartes selection on his selection, please fix

**Comment by capitaladot** [comment]
Will do, thanks for the report.
