### ISSUE TITLE
Age of Darkness - HH VI Legion - Priest of Fenris (Caster of Runes) Missing Runic Weapon

### ISSUE THREAD

**Issue by rsimmerm** [BSData/horus-heresy#1336]
The choice for the Caster of Rune does give them their Force weapon or allow you to swap it for something else.  It let me swap my bolt pistol for a power weapon, but never said I had a Force weapon like the entry from HH: Inferno lists.

![screenshot 5](https://user-images.githubusercontent.com/8026848/39106198-1c12c0f8-4688-11e8-9acb-0795f490cd7f.png)

**Comment by capitaladot** [comment]
Thanks, will address.
