### ISSUE TITLE
Fix Exodus' Power Armor

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1341]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.01.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Exodus error, power armour has a power armour selection, files say this cannot be

**Comment by capitaladot** [comment]
Clarify, please?

**Comment by capitaladot** [comment]
Now I see... it looks like someone gave Exodus a nested Power Armor entry under his Power Armor entry.
