### ISSUE TITLE
These files will not load on iPhone 6

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1350]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** These files will not load on iPhone 6. 8th edition 40k data files will load. BattleScribe just quits when trying to create a list with Horus heresy data files.

**Comment by capitaladot** [comment]
Bummer, isn't it? The 6mb file is just too big for BS to render in iOS.
@Jonskichov?

**Comment by capitaladot** [comment]
Appears to still be an issue. See #1449

**Comment by FrisoDenijs** [comment]
I have the same issue

**Comment by Mayegelt** [comment]
Duplicated in #1464
