### ISSUE TITLE
FW Mechanicum  -  Thallax

### ISSUE THREAD

**Issue by lacyj3** [BSData/horus-heresy#137]
Thallax need a listing added to Fast and Heavy that marks them with the upgrade option.  You can buy Ferrox on a Thallax making them become Fast Attack or Icarian making them Heavy Support.

Ferrox = Fast
Icarian = Heavy

Lock those choices in as Fast/Heavy Thallax and prevent their upgrade selection on the Troop section.

Make sense?

**Comment by capitaladot** [comment]
This was addressed in the new Taghmata Army List.
