### ISSUE TITLE
Incorrect price on Myrmidon Destructors

### ISSUE THREAD

**Issue by eaxexe** [BSData/horus-heresy#1381]
File: (HH) Mechanicum - Taghmata Army List

BattleScribe version: 2.01.14

Platform: Windows

Dropbox: Yes

Description:
Myrmidon Destructors are 15pts too expensive, due to them being forced to pay 5pts/model, for their Power Fists, which should included for free.

This was fixed a while back, but has resurfaced as an issue.

**Comment by capitaladot** [comment]
Myrmidon Destructors power fists are already zero-costed.
