### ISSUE TITLE
Legion Fellblade missing Hull-mounted demolisher siege cannon

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1382]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.01.20

**Platform:** Android

**Dropbox:** No

**Description:** Legion Fellblade missing Hull-mounted demolisher siege cannon as default weapon as described on Pg 86 of the Horus Heresy Legion Army List Rulebook.

**Comment by capitaladot** [comment]
Thanks, will add. Still finding these forgotten default items from the
project creator, years later.
