### ISSUE TITLE
Incorrect prices for Militia Special Weapons Grenadiers

### ISSUE THREAD

**Issue by Poik12** [BSData/horus-heresy#1383]
File: (HH) (HH) Imperialis Militia and Cults Army List

BattleScribe version: 2.01.14

Platform: Windows

Description:
Militia Special weapon grenadiers are 10pts too expensive across the board. the point cost in the Crusade imperialis list is written as "Per model", meaning the 10pt cost for adding the grenadier is incorrect. 

According to Crusade Imperialis list, they should only cost the following:
Heavy stubber .......................................+10 points per model
Rotor cannon.........................................+10 points per model
Flamer . +10 points per model
Melta gun........+15 points per model
Plasma gun .....+15 points per model
Grenade launcher (frag & krak).........+10 points per model

**Comment by capitaladot** [comment]
Thanks for the report. Feel free to submit a pr to fix.
