### ISSUE TITLE
Blackshield Marauder Squads missing chainaxes, Heavy Flamer misspelled

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1386]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.01.18

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Blackshield Marauder Squads do not posses any chainaxes, despite having the chainaxe as a part of their standard equipment. In addition the Heavy Flamer option is listed as “Heay Flamer” in their equipment list.

**Comment by capitaladot** [comment]
Will fix

**Comment by tw6464** [comment]
Thanks @capitaladot.

Also, when one selects the Bolter profile on Blackshield Mauraders, there is not a weapon stat listed.

**Comment by capitaladot** [comment]
Got held up fighting with the new beta and trying to split things by Legion
into files. Short answer: hard, with diminishing returns.

**Comment by tw6464** [comment]
Alrighty, I’ll take your word for it.
