### ISSUE TITLE
World Eaters - compulsory troops

### ISSUE THREAD

**Issue by tmigliorini** [BSData/horus-heresy#1389]
When you make an army list with the berserker assault rite of war, there is a bug wich notify you an error about the number of compulsory troops - even if you have 3 of them

**Comment by capitaladot** [comment]
Are you adding the Berzerkers before selecting the Rite? If so, try the
other way around.

There are two copies of Berzerkers. The non-compulsory copy gets hidden
when that Rite is selected and the Compulsory should appear.

This a dumb BattleScribe quirk, but is the only way to validate units that
are only sometimes Compulsory Trrops.

**Comment by tmigliorini** [comment]
There is no berserker troop.
"Berserker assault" is the rite of war.

I usually select First of all the rite, than the troops (tactical squads and assault squads)

**Comment by capitaladot** [comment]
Huh. I will play with this and try to reproduce.

**Comment by capitaladot** [comment]
Yeah, something is certainly hosed up with this RoW. Will fix.

**Comment by capitaladot** [comment]
Fixed. Also Oprah'd chainaxes.
