### ISSUE TITLE
Blackshield marauders have no option to select a melee weapon that is required for them, and the pariah Bolter can’t be taken in a quantity greater than one.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1390]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.01.18

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Blackshield marauders have no option to select a melee weapon that is required for them, and the pariah Bolter can’t be taken in a quantity greater than one.

**Comment by capitaladot** [comment]
I tried a quick fix on it last night. Will try again tonight or tomorrow.
