### ISSUE TITLE
The Vigil Opertii Mission rite of war of the Ultramarines make the Legion Reconnaissance Squad lose its "support squad" rule and enabling it to be taken as compulsory troop

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1399]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** The Vigil Opertii Mission rite of war of the Ultramarines make the Legion Reconnaissance Squad lose its "support squad" rule and enabling it to be taken as compulsory troop. However, after choosing this rite of war Legion Recon Squads are still not recognized as compulsory troops.

**Comment by capitaladot** [comment]
Yeah, that was busted. Fixing now.
