### ISSUE TITLE
World Eaters - compulsory troops / Imperial fists shields

### ISSUE THREAD

**Issue by tmigliorini** [BSData/horus-heresy#1401]
Good morning,
issue  #1389 is not solved yet, still got the same problem with that rite of war

Also: storm shield for a cataphractii praetor of Imperial fists is 15pts, when it should be 10

Thank you so much

**Comment by capitaladot** [comment]
The bug you described is solved (just re-tested).

I do see that it should be requiring 3 Compulsory Troops, though, and does not seem to be.

Please file bugs in individual tickets.
