### ISSUE TITLE
Legion Tactical Support Squad - Costing Broken for Sergeant

### ISSUE THREAD

**Issue by Pantsworth6573** [BSData/horus-heresy#1402]
Equipping Support squads with Volkite Calivers is only applying the 45 points instead of 50 to the roster, looks like the 5 points for the sergeant isn't being applied.  Even manually selecting the Caliver over the flamer keeps the cost unchanged. 
Thanks for your work

**Comment by tmigliorini** [comment]
Keep in mind that if the sergeant exchanges his weapon (flamer) for a combi weapon he does not pay the weapon upgrade

**Comment by capitaladot** [comment]
Check the overall cost. There is a modifier that increments unit cost based
on Sergeant option. Confirm it works or isn't working.

**Comment by Pantsworth6573** [comment]
Can confirm with at least Volkite Calivers that it isn't working. 45 points on the unit sheet, 'no cost' on the Sgt. Overall cost 220 (175 for ten men with flamers, 45 to exchange flamers for Volkite Calivers at 5 ppm) should be 225 (175 + 50)
I also went into the Sgt unit entry and reselected his weapon to a Caliver with no change to the cost anywhere on the sheet. 

Melta or plasma however is 150 for unit, 'no cost' for sgt (squad of 10)
I'm less educated with melta and plasma and how they interact with the Sgt, but it also seems like The Sgt pays a 15 point premium for his combi weapon if the rest of the squads takes plasma or melta, is that intentional? (At work ATM, can't check the book was just something else I noticed off hand)

Thanks for your time and hard work, very appreciated

**Comment by capitaladot** [comment]
Cost will change on the squad, not the Sergeant.

**Comment by capitaladot** [comment]
Sounds bugged.

**Comment by Pantsworth6573** [comment]
Yeah overall squad price sits on 220 instead of the expected 225

**Comment by capitaladot** [comment]
Fix PR welcome
