### ISSUE TITLE
Possible LoW % Calculation Bug

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1410]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** I'm writing a 2k list for my Alpha Legion army. I have added Alpharius. "Roster errors" tells me that I have spent more than 25% of my points on lords of war! According to this data file 302.5 is 25% of 2000! This is obviously and demonstrably false! If you could sort it out I'd appreciate it.

**Comment by capitaladot** [comment]
Woah, that's pretty weird. I will try to recreate it.

**Comment by capitaladot** [comment]
Can't reproduce.
