### ISSUE TITLE
Dark Angels Veteran Tactical Squad to have 2 heavy bolters, the program gives an error message unless you take 2 molecular acid shells for each heavy bolter marine

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1416]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** If you select a Dark Angels Veteran Tactical Squad to have 2 heavy bolters, the program gives an error message unless you take 2 molecular acid shells for each heavy bolter marine. This should not be possible, since Acid Shells are not a limited ammo-type weapon, and instead are an alternate firing mode you can purchase for 5 points a model. The way the program is seeing it is that you must pay 5 points for Acid Shells on each heavy bolter times the number of heavy bolters in the squad (I.e. Taking 2 heavy bolters makes the program think each heavy bolter must pay for acid shells twice, costing 10 points per Heavy Bolter, when it should cost only 5 points). This is only a bug with the Veteran Tactical Squad, and it happens whether those Veterans are taken as Troops or Elites (Depending on the Rite of War being used)

**Comment by capitaladot** [comment]
Thanks for the report, will take a look at the validation.
