### ISSUE TITLE
Automatically include Rite of War option list, without making Blackshields remove it.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1422]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** So.... it would appear that by removing master of the legion from Blackshields, it’s unintentionally caused it to not work when making a new list.

Specifically, the error is “(List) has 1 too many selections of Master of the Legion (maximum 0)

**Comment by capitaladot** [comment]
Huh.

So, to automatically have the Rite of War item (present in the vast
majority of lists and hard to find for less experienced users, based on
many "where is it" issues submitted), but to have the correct validation
work for 95% of cases, Blackshields players (probably a teensy percentage
of users) are sadly going to have to remove Rite of War to clear validation.

The better option may be moving Rite of War up to a Primary Category (and
then show it in the list of FoC slots).
