### ISSUE TITLE
Crusade Fleet Avenger Strike Fighter is missing the two "wing-mounted lascannons" 

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1427]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.02.00

**Platform:** Android

**Dropbox:** No

**Description:** The data card for Crusade Fleet Avenger Strike Fighter is missing the two "wing-mounted lascannons" as listed on Page 272 of The Horus Heresy - Book 1 Betrayal "Black Book".

**Comment by capitaladot** [comment]
Will add.
