### ISSUE TITLE
Veteran Sergeant and power weapon

### ISSUE THREAD

**Issue by Polnor** [BSData/horus-heresy#1428]
When you choose pw for sergeant in veteran squad it costs x points for pw and another x points for choosing pw, Please fix it. Thanks!

**Comment by capitaladot** [comment]
Check the points. It is correct even though it doesn't show on the type.

**Comment by Polnor** [comment]
It doesn't add to Sergeant total cost, but adds to whole squad cost.
Method to check it - you add veteran squad. It costs A points, sergeant cost B points. You add power weapon to sergeant and he costs B+X point (which is fine). But whole squad will cost A+X+X points, which is a problem.
Please recheck it.

**Comment by capitaladot** [comment]
Ah, I see what you mean. Will fix.

**Comment by Polnor** [comment]
Thanks a lot!
