### ISSUE TITLE
Army of Dark Compliance Force Type 

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#1440]
When choosing Army of Dark Compliance it keeps asking for selections of it.

Seems to be a 2 instead of a 1 in the box.

![image](https://user-images.githubusercontent.com/20280410/46244101-02a95380-c3d2-11e8-9f48-7d3f574e966e.png)

**Comment by Mayegelt** [comment]
Not sure if anything else is linked with it that will cause issue. Seemed to fix the roster when i put it down to min 1. But might affect something else, so didn't want to make the change.

**Comment by capitaladot** [comment]
You have to select two copies of it, one per catalog (one Astartes, one Militia).
