### ISSUE TITLE
Admech : Thallax Icarian upgrade

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#1446]
Thallax units in Taghmata can gain the Icarian upgrade. This makes them change from "Troops" to "Heavy Support" choices. This does not seem to happen on battlescribe currently.

A work around would be to create a duplicate entry for Thallax under "Heavy Support". This entry must take the Icarian upgrade (or just has it added to their base profile and points). Then remove the option for the Icarian upgrade from the "Troops" choice.

**Comment by capitaladot** [comment]
@Mayegelt did your PR fix this?

**Comment by Mayegelt** [comment]
No I haven't fixed this one yet. I can do it as i said as the duplicate entry that i could do now.

**Comment by Mayegelt** [comment]
Just submitted my fix. Looks like it is working :)
