### ISSUE TITLE
Corvus Corax, Shadowed Lord Rule

### ISSUE THREAD

**Issue by atagorn** [BSData/horus-heresy#1453]
Hello, when I check corvus corax shadowed lord it says   Unless part of a unit himself, if Corax is not the closest target to the firing unit or the firing unit is a Psyker, Daemon, or Primarch, only Snap Shots may be fired against him. At the beginning of any of the players turns, Corax may be removed from play and placed in on-going reserves, even from close combat (as long as his initiative is higher than his opponents). (HH:LAICL p113)

But when I check the LA AOD Legions It says Corax' controllers players turn not Any players turn. Is there an faq that I have missed or is this an error?

**Comment by Mayegelt** [comment]
Might have taken a long time, but should be done now...
