### ISSUE TITLE
On Command Squad of Legion Astartes, Legion Scimitar Pattern Jetbike with heavy bolter costs +45 each, rather than +35 each. 

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1455]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** On Command Squad of Legion Astartes, Legion Scimitar Pattern Jetbike with heavy bolter costs +45 each, rather than +35 each. Is it a mistake of mine or not?

**Comment by Mayegelt** [comment]
Strange this one was left so long. Fixed in my current pull request. Hopefully approved soon.

**Comment by Mayegelt** [comment]
This one is fixed as well.

**Comment by zopha** [comment]
Did this get added into the current files? If so we can close it.

**Comment by Tomakokamikaze** [comment]
also, no power spears available for command squad

**Comment by Tomakokamikaze** [comment]
@Mayegelt what is teh source for this?
its not in the FAQ, and not in the latest rules I know of

**Comment by Mayegelt** [comment]
@Tomakokamikaze he was saying at the time that the formula had been worked out wrong, it was charging 45pts per jetbike, rather than 35pts.
Also added the power spears to the command squad termy and normal guys. Wonder why no one brought it up before (other than they suck :P)

**Comment by Tomakokamikaze** [comment]
@Mayegelt they are worth it if you know your oponent is majoritarily 4+ saves like solar aux or Imp Army, or if you use white scars with hit and run, then you are always charging. ;-)

**Comment by Mayegelt** [comment]
Issue pushed
