### ISSUE TITLE
Legion Rapier Battery, selected Quad launcher option

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1456]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.15

**Platform:** Mac

**Dropbox:** No

**Description:** Legion Age of Darkness List, Legion Rapier Battery, selected Quad launcher option, but there appears to be no option to select ammunition options such as Shatter shell at 10pts, Splinter at 10pts or incendiary at 5pt.

**Comment by capitaladot** [comment]
Look under Quad Launcher Support Battery.
