### ISSUE TITLE
New Unit - Warbringer Nemesis Titan

### ISSUE THREAD

**Issue by zopha** [BSData/horus-heresy#1457]
https://www.forgeworld.co.uk/resources/fw_site/fw_pdfs/Horus_Heresy/HH-Legio-Titanicus-Warbringer-Nemesis-Titan.pdf

**Comment by thebiggeordiegeek** [comment]
I believe this has been added with the latest release.

**Comment by Mayegelt** [comment]
Able to be closed @capitaladot
