### ISSUE TITLE
Old iPhone still can't handle big file.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1464]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** my iphone software is up to date, battlescribe data is up to date. Everything on Horus Heresy works except legion astartes when i try to choose that to make a army list it loads for a while then force closes. i tried to delete then re download and that did not work

**Comment by thebiggeordiegeek** [comment]
What model iPhone are you using?

**Comment by capitaladot** [comment]
Gotta be an old one

**Comment by capitaladot** [comment]
I still wonder if it would be possible to re-factor things out into more individual files to reduce memory consumption, given some of the cool cross file link things that are now possible in later BS releases. With luck, it might help performance for everyone (not just those with ancient iPhones).

**Comment by Mayegelt** [comment]
Discussed, but unfortunately though this may be possible in theory... the practicality of this is unworkable due to issues such as shattered legions and alpha legion using coils.
