### ISSUE TITLE
Legio Custodes Custodian Venatari - New Unit

### ISSUE THREAD

**Issue by thebiggeordiegeek** [BSData/horus-heresy#1470]
Rules found here - https://www.forgeworld.co.uk/resources/fw_site/fw_pdfs/Horus_Heresy/LegioCustodesVenatariSquad.pdf

**Comment by Mayegelt** [comment]
Already on it. Just about to upload a fork with it in and the Dominus and Armigers :)

**Comment by Mayegelt** [comment]
Venitari are in the latest update.
Issue can be closed.
