### ISSUE TITLE
FAQ and Playtest changes

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#1474]
We know they are here (Feb 2019 FAQ). I will try to work on changes over the next few days.

Seeking clarification on Playtest changes, to if we will just overwrite original entries or maybe clone units and have (Playtest) / (PT) or something like that before or after name. As some may not wish to have the playtest rules in live version until approved.

https://whc-cdn.games-workshop.com/wp-content/uploads/2019/02/Horus-Heresy-General-Errata-and-FAQ-v1.1-Final.pdf

**Comment by thebiggeordiegeek** [comment]
I’d go with cloning for now, simply because I think you are right some people will want to use the originals for a period of time.

**Comment by Mayegelt** [comment]
Looks like i can add an option for Playtest Rules in selection, that hides and shows options :D

**Comment by Mayegelt** [comment]
OK my pull request is ready to go. If people want to test my one out and notice any issues then that would be great.

**Comment by 6guenther** [comment]
Lightning Claw on the Destroyer Sergeant is free, supposed to be 10 pts.
Phalanx Warder Squad Combi weapons is 10 pts, supposed to be 5 pts.

**Comment by capitaladot** [comment]
@6guenther not the place for laundry list bug reports, please submit these elsewhere.

**Comment by Mayegelt** [comment]
Ok just putting those fixes in now. Thanks for the report @6guenther
