### ISSUE TITLE
The Coils of the Hydra: Detachments using this rite of war must take an additional compulsory troop

### ISSUE THREAD

**Issue by Tomakokamikaze** [BSData/horus-heresy#1478]
Detachments using this rite of war must take an additional compulsory troop (this is not beeing implemented automatically).

Also Ammitara Occult Intercession Cabal aalows you to take a 99+ squad (in rewards of Treason)

I imagine most selections of the rewards of treason could be upgraded.

Also Qin Xa cant take a rite of war, and he should
plus his keshig bodyguards all start with no weapons selected, and its kind of annoying.

**Comment by Mayegelt** [comment]
Found the issue, fixed it now in the latest pull request.
