### ISSUE TITLE
The cost of volkite chargers on the Medusan Immortal Sargeant is 5pts instead of 2pts using the beta rules

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1480]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.22

**Platform:** Android

**Dropbox:** No

**Description:** The cost of volkite chargers on the Medusan Immortal Sargeant is 5pts instead of 2pts using the beta rules

**Comment by Mayegelt** [comment]
Just made a fix that should work. Waiting for pull request approval.
