### ISSUE TITLE
I'm unable to get a Praetor with both Bolt Pistol and Chainsword/Combat Blade swapped for a pair of Raven's Talons or Lightning Claws to pass validation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1481]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** When creating a Legion Crusade list, I'm unable to get a Praetor with both Bolt Pistol and Chainsword/Combat Blade swapped for a pair of Raven's Talons or Lightning Claws to pass validation. With the Exchange Bolt Pistol option under Artificer Armour Weapons set to "None" the error is "Praetor, Legion must have 1 more selections from Exchange Bolt Pistol for: (minimum 1)", but if anything else is selected the error just changes to "Praetor, Legion has 1 too many selections from Exchange Bolt Pistol for: (maximum 0)". This is using the most recent 11.4 data file for the Horus Heresy.

**Comment by Mayegelt** [comment]
Just made a fix that should work. Waiting for pull request approval.

**Comment by capitaladot** [comment]
Some change seems to have broken the same thing for Terminator armor and paired claws.
