### ISSUE TITLE
Rite of War Day of Revelation should not require a third compulsory troop choice.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1482]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.14

**Platform:** Windows

**Dropbox:** No

**Description:** Rite of War Day of Revelation should not require a third compulsory troop choice.

**Comment by Mayegelt** [comment]
Just made a fix that should work. Waiting for pull request approval.
