### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by bilewinters** [BSData/horus-heresy#149]
Hi there, I've already submitted a pull request for adding Leviathan Dread Talons, but thought I'd also ask to be added as a dev. I'm not sure what your review process is though?

**Comment by amis92** [comment]
The current project maintainer would be @Millicant - I'll invite you to the organization if he agrees. Also contact him mainly in case of doubts etc.

**Comment by Millicant** [comment]
Thanks for the inputs!  I'm afraid that I'm keeping a pretty close eye on my pet project here - I'd love for you to keep giving inputs, but I'd like to retain the final authority on additions so I can QA everything before it goes anywhere.  Thanks!

**Comment by amis92** [comment]
Ok, so I think that means @bilewinters you should keep making pull requests here :)

**Comment by bilewinters** [comment]
No problem, will keep doing pull requests :-)
