### ISSUE TITLE
 Legio Custodes Sagittarum Guard Squad has a wrong cost - 195 instead of 185

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1494]
**File:** (HH) Talons of the Emperor Army List.catz

**BattleScribe version:** 2.01.22

**Platform:** Android

**Dropbox:** No

**Description:** Legio Custodes Sagittarum Guard Squad  has a wrong cost - 195 instead of 185

**Comment by Mayegelt** [comment]
Fixed
