### ISSUE TITLE
Sicaran punisher now cost 190 according to book 8 Malevolence and taking a squadron

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1496]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 1.17.17

**Platform:** Windows

**Dropbox:** No

**Description:** Sicaran punisher now cost 190 according to book 8 Malevolence and taking a squadron. and destroer squad cost 115 according to a new faq
https://www.warhammer-community.com/2019/02/11/11th-feb-an-faq-from-the-age-of-darknessfw-homepage-post-3/

**Comment by Mayegelt** [comment]
I'm working on book 8 changes. Just need previous pull request to be checked and approved, then will work on updates from new book.
The Destroyer change is a Playtest rule. Click to use them at the bottom.

**Comment by Mayegelt** [comment]
Sorry @capitaladot this one was fixed a while ago. Must have forgotten to reference it.
