### ISSUE TITLE
No Rites of War

### ISSUE THREAD

**Issue by Basiczombie** [BSData/horus-heresy#1499]
I have attempted to see the rites of war for loyalist Salamanders and the list is always empty.
I have tested this on the following operating systems.
Android
iOS
OS X
Win 10

**Comment by alphalas** [comment]
Do you have 1; a character with Master of the Legion and 2; at least 1k points in the list? You need both to qualify for a rite.

**Comment by Mayegelt** [comment]
Should just need a master of legion char in list. I don't think you need then 1k

**Comment by alphalas** [comment]
You did at one point in BS. Might have removed that restriction though; it’s a thing in the books though

**Comment by Basiczombie** [comment]
Ok, I will try that. I wasn't aware of those conditions. thanks for the speedy reply.
