### ISSUE TITLE
Daemons of the Ruinstorm

### ISSUE THREAD

**Issue by martijndoornik** [BSData/horus-heresy#1502]
With Book on its way, I will take on adding the Daemons of the Ruinstorm, unless someone else is already doing so. I will work on this this week and hope to have something ready to test this weekend. The list of things to do:

- [x] Adding the units;
- [x] Special Rules and such

- Applying the Emanations of Horror;
- [x] Bracket one;
- [x] Bracket two;
- [x] Bracket three;

- Applying the Aetheric Dominions
- [x] Crimson Fury;
- [x] Maddening Swarms;
- [x] Lurid Onslaught;
- [x] Creeping Scourge;
- [x] Mirror of Hatred;
- [x] Presplendent Terror;

**Comment by Mayegelt** [comment]
I did a very basic start to it. Then got distracted. I had made all units and stats for them and points. But hadn't added emination, dominions, special rules.

**Comment by martijndoornik** [comment]
Currently added the units (bar Unique units) and Emanations. Currently applying Dominions and such.

Track progress on https://github.com/BSData/horus-heresy/tree/daemons/initial this branch

**Comment by Mayegelt** [comment]
Tested, but due to reimplementation of the old daemon codex and this one seemingly been created using it as a template, it either removes the new or old daemons from the current files and places the other in backup.

**Comment by martijndoornik** [comment]
Fixed in the latest commit
