### ISSUE TITLE
 Daemon prince of Slaanesh has no points cost, and can not be entered for upgrades

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1507]
**File:** (HH) Chaos Daemons Army List.catz

**BattleScribe version:** 2.01.24

**Platform:** Android

**Dropbox:** No

**Description:** Daemon prince of Slaanesh has no points cost, and can not be entered for upgrades

**Comment by Mayegelt** [comment]
This one is no longer fixable in the current state, as the 7th Edition Daemons list has been removed.
