### ISSUE TITLE
Jump Packs giving wrong special rules

### ISSUE THREAD

**Issue by EricSmailys** [BSData/horus-heresy#1509]
For many units, Jump Pack equipment appears to be adding the special rules Very Bulky and Relentless to the unit special rules. The correct rule for Jump Packs is Bulky, and they should not have Relentless (barring the unit getting the rule from something else).

Specific examples I've encountered, all while building a Blood Angels Loyalist list with the Day of Revelation Rite of War: Centurion (Chaplain) with Jump Pack selected (removing the jump pack also removes the special rules). Apothecaries with Jump Packs. Dawnbreaker squads. Of note, Angel's Tears squads (which come with Jump Packs by default) do not have this issue.

**Comment by Mayegelt** [comment]
Fixed in latest update to be posted soon.
