### ISSUE TITLE
Ruinstorm daemons

### ISSUE THREAD

**Issue by MountyChris** [BSData/horus-heresy#1515]
Sundering fangs doesn't appear to be scaling points with number of models in the unit like the other emanations

**Comment by MountyChris** [comment]
Same for stupefying musk

**Comment by MountyChris** [comment]
Lord of sorcery is missing for shrikes

**Comment by Mayegelt** [comment]
Fixed the top 2 in my latest pull request.

Daemon Shrike can't get Lord of Sorcery though.
QUOTE : Only Daemon Lords, Chosen and Greater Daemons may purchase this Emanation and only Daemon Lords may purchase more than two levels of Mastery.
