### ISSUE TITLE
Battlescribe 2.02 errors "Hidden"

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#1528]
Seem to be an error with multiple "Hidden functions in the system.
So for instance an issue for Assault Squad Sergeant, if he takes a Combat Shield it flags an error that it should be hidden.  Or a Praetor if he has a Divining Blade
Same for Melta Bombs on Assault squad Sergeant and a few others i tested.

Please list any you find here. This may need a major rework to fix or something minor, I'm not sure. I think it is a case of items linking to the same entry seem to be counting as the same entry.

**Comment by capitaladot** [comment]
@Jonskichov

**Comment by amis92** [comment]
I'd expect it to be the same underlying issue (with `Shared?` checkbox): https://github.com/BattleScribe/Release/issues/43

**Comment by Jonskichov** [comment]
If this hasn't been resolved in 2.02.02 (desktop), please raise an issue here: https://github.com/BattleScribe/Release/issues

**Comment by Mayegelt** [comment]
Seems fixed now
