### ISSUE TITLE
combi-weapon on sergeant of veterans cost twice.

### ISSUE THREAD

**Issue by Polnor** [BSData/horus-heresy#1529]
I pay price x for combi-weapon, and also pay again when I choose what kind of combi-weapon I use.

**Comment by capitaladot** [comment]
Somebody no doubt set a cost on the shared entry. We've gone round and
round on this so many times...

**Comment by Mayegelt** [comment]
Fixed, though still looks messy with it showing as 0 pts to buy, but costing 10pts per one bought added to unit cost with no explanation.
