### ISSUE TITLE
Conflicts

### ISSUE THREAD

**Issue by Millicant** [BSData/horus-heresy#153]
We are running into major conflicts in our code.  I have had to debug it twice already, and I am not a git expert.  Currently I am unable to commit an update with Garro in it because of unknown errors.  

Please do not make commits, especially for things that have already been updated (assault cannon, chainsword, etc).  

Capitaldot - if you have any experience with debugging this nonsense, please do so now.  

At this point, I'm going to ask that any commits are not made without a pull request so that I can manage and evaluate them.

**Comment by capitaladot** [comment]
Yeah... with the backlog that built of my pill requests, some stupid
whitespace/line number conflicts occurred. I was able to go through,
re-open those pull requests that got closed, and get the conflicts
resolved, and then get the pull request to merge. I do intend to continue
to put my stuff in as pull requests, and will of course perfrom the merges
myself and resolve conflicts if necessary. If I take your point correctly
to be that doing things per branch and pulling in each branch is The Right
Way to do things, I believe we agree. This does involve working in a Forked
branch and backmerging the BSdata branch inti it occasionally  (ideally
before making a new "feature" branch).

Basically, all this entails is opening the file in a text editor that
supports Git diffs (I use Eclipse), attempt the merge, and look for the
conflicted lines (the Git diff will have put in extra lines that tell you
where the conflicts are and show you the content from each branch).

Mostly, these are basically bogus conflicts where something was added at
the same line (e.g. a new shared profile at the last line of the shared
profile block), so all one need do is delete the Git-added extra lines and
make sure the XML is still properly encapsulated. That's what I did to
resolve and merge my re-opened pull requests.

If you want to to put in your Garro changes this way, I will go through and
get it merged and fix the conflicts.

Another option is to replace your local/forked branch with the latest from
BSData proper and "reflow" your changes from your Garro feature on top of
that. This workflow is supported by many IDEs.

Ain't SCM-mediated collaboration grand? ;)

**Comment by Millicant** [comment]
Okay I'm quite confused.  I can't do anything via the github desktop app anymore.  It says there are errors and must be debugged.  I downloaded the files and put them in my directory and synced, hoping that would clear it up but no dice.  

I'm not an expert at github, to be perfectly honest.  This is the only time I've ever used it, and until you came along @capitaladot it has been exclusively me (one input earlier on from a single guy).  I haven't had to deal with collaboration because there hasn't been any collaborating...

You'll have to forgive me for being testy about this - this has been my pet project for quite a while now, so having somebody else join in is new and scary.  :P 

Okay, 

As for the latest merges - I'm not sure what happened.  I didn't just merge what you had in your pull requests, I took what you made and added it directly to the original file and committed that locally.  So by re-opening the issues and merging your pull requests I think there has been double additions done.  I'm not sure, I'm quite lost at the moment.  

So to make sure that I follow what you're suggesting, it's that we have a separate branch for updates, which is merged occasionally for release?  We both make updates to the branch, then merge as appropriate?

**Comment by capitaladot** [comment]
I know it is a hassle (SCM conflicts suck!), so apologies for that.
Obviously you've done yeoman's work making the HH more accessible to many
gamers, and that's awesome.

Yeah, that's right;
best practice with Git is to clone the code,
then fetch and pull from Github,
then make a new branch for your workset,
then make your changes,
then try to merge your branch (via pull request),
then, if you can't just do a simple "fast-forward" merge (i.e.
automatically on the pull request page or in Github desktop), do a
"backmerge" from BSData/horus-heresy HEAD (merge BSData/horus-heresy into
your branch you are trying to merge),
then resolve any remaining conflicts (with a text editor that knows about
Git diffs) and/or fix incrementing the file version numbers,
then "add" the formerly conflicted file (marking the conflicts resolved),
Then try to merge your branch again.

I think now, as a contributor, I don't need to be working out of a fork on
Github (I can do as you have done and checkout the repo locally and just
make branches to pull in). I suspect me working out of a fork and you
working out of the repo may be partially why we saw the conflicts we have
seen of late. It was also another step of backmerging.

**Comment by amis92** [comment]
From the experience of watching multiple repos under our brand:

It really helps if you strictly follow the guidelines presented in wiki https://github.com/BSData/bsdata/wiki/Developer-Guide

Specifically the important part is *not* to work on the same file at the same time. That can be achieved by setting yourself as assignee for the issue you're currently working on; and naturally checking before that if no one else has taken that file on workshop. Another way is to divide the files between you, but with that amount of files and just you two it's unviable.

As @capitaladot correctly suggested, it's also safer to work on your local branch and sync often. Pull requests are good for rarely-active contributors, which can help us from time to time. @Millicant if you don't like the looks of something that got pushed to master, you can always revert it and do yourself :)

**Comment by Millicant** [comment]
Thanks @amis92!  That's very helpful.

We'll have to develop our system a little better.  Assigning ourselves to issues is a solid idea and should help eliminate some of the conflicts.  Since I also gather issues from other sources (most importantly the Bolter & Chainsword) I will make an effort to replicate those issues here as well.  

Up until now, I've been dealing directly with the master.  I'll try to start working on a branch for my updates.  

As far as work division - I don't want to divide up the files between us.  That isn't realistic and also creates a split in "style."  

Most pressing is that currently the files that are the most "up to date" are jacked.  As in Battlescribe currently calls the LACAL catalogue corrupt and deletes it.  Sooooo yeah.  I'm going to be reverting some stuff.  Specifically the last 3 merges since I have already written those updates into the file.  I suspect those 3 are part of the issue.  

Additionally, I'd like to retain the exclusive authority for releases.  I have a great deal of time and pride invested in these catalogues; I hope that doesn't seem like a jerk move.  

Thanks for being so open to dialogue @capitaladot, we will make this work yet!  Between the two of us I'm sure the catalogues will only get better.  :)

**Comment by capitaladot** [comment]
@Millicant Sorry for those merge-bugs; I have resolved them and fixed the "corrupted" status of the file.

**Comment by Millicant** [comment]
Neither of the last two worked - Still corrupted.  At this point, I'm nuking it.  I'm going to re-upload a working version with all the latest nonsense.  Please re-start from there and we'll get this figured out.

**Comment by capitaladot** [comment]
@Millicant works for me (after "Delete all Data" on phone, and both loading the file manually and pulling it from appspot on desktop). I presume you are likewise deleting all data?

**Comment by Millicant** [comment]
Haha yup.  Except I have my phone set to not link to dropbox - it grabs it from the appspot instead.  That way I can test that my changes have made it down the pipe, as they say. 

I'm only deleting the LACAL file.  The rest are fine.  Should be re-uploading now. 

Yikes!

**Comment by capitaladot** [comment]
@Millicant I'm not using Dropbox, either... what I mean is, there is a "delete all data" option in the Android app that clears out all files (Appspot, Dropbox,manually "sideloaded"). I likewise deleted my local desktop files and re-downloaded from Appspot and was able to successfully load LACAL rosters.

**Comment by Millicant** [comment]
Yeah the rosters weren't the problem.  The catalogue editor crashed opening the LACAL .cat.

But that should be all fixed now!  Let me know if you run into any more issues. 

I'd like to propose that we broadcast any updates we intend to make via issues as well.  That way we can prevent the craziness that just occurred.

**Comment by capitaladot** [comment]
@Millicant doing issue broadcasts makes sense.

**Comment by capitaladot** [comment]
So, it is looking like "issue broadcasts" really meant "check with me first so I can close your proposal-in-issue".

**Comment by Millicant** [comment]
No need to get snippy.  

In this particular case, yes.  I had already stated that I did not wish to implement that particular issue.  I'm sorry if that bothered you.  I look forward to seeing more of your contributions, like the Mechanicum catalogue.
