### ISSUE TITLE
Thousand son's missing data

### ISSUE THREAD

**Issue by zarmaglorg** [BSData/horus-heresy#1530]
When creating a thousand son's heresy list on battlescribe I noticed that sekmet terminators don't seem to appear in either the elites slot or the troops when using Magnus

It would be appreciated if these entries could be added

**Comment by Mayegelt** [comment]
They seemed to appear for me in Elites slot. But were not for the Troops slot with Magnus in the army.

Have corrected this, and also corrected issue of being able to take them as Elites in a PotL RoW. Have also corrected lack of Terminator Squads being Troops if Magnus is in the army.
