### ISSUE TITLE
Command section generates error when only special Weapons Veterans Are selected

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1537]
**File:** (HH) Solar Auxilia - Crusade Army List.catz

**BattleScribe version:** 2.02.01

**Platform:** Android

**Dropbox:** No

**Description:** Command section generates error when only special Weapons Veterans Are selected. The list however allows to select 2 special weapons as minimum squad.

**Comment by Mayegelt** [comment]
Just made a fix for this. Will put it in my next pull request. Probably either in the next hour or after work, depending on when i can get other fixes done.
