### ISSUE TITLE
Promethium Relay Pipelines are missing from fortifications

### ISSUE THREAD

**Issue by czuzak** [BSData/horus-heresy#1539]
Using the desktop program and data version v12.003 (updated May 12) I do not see an option to add Promethium Relay Pipelines to a force when looking under fortifications

**Comment by Mayegelt** [comment]
I think this is no longer a usable building type as far as i am aware. They removed various ones, or at least have not released data sheets for them for the current version of the game rules. The only ones that are currently in game i believe are the ones from the rule book itself.

**Comment by capitaladot** [comment]
Sorry @czuzak , @Mayegelt has the right of it. Many Fortifications were deleted due to the red rulebook's omission of them.
