### ISSUE TITLE
Mechanicum (Red Book)

### ISSUE THREAD

**Issue by Ackoogin** [BSData/horus-heresy#154]
Couple things with the new Mechanicum cat:
- [x] I cannot see Djinn Skien option.
- [x] Castellax seems to be set to minimum of two models
- [x] Castellax seems to have maximum of 1 bolter replacement.

**Comment by Millicant** [comment]
Thanks for the info - I'll look into it shortly!

**Comment by Ackoogin** [comment]
Additionally the Dominus is missing the new weapons options (thruster/fusil etc).
Thanks for all your hard work btw :)

**Comment by capitaladot** [comment]
I should have read the history before self-assigning. ;)

**Comment by Millicant** [comment]
Haha I got this.  I'm still editing and updating all the good work you did on the new Taghmata book so this fits in perfectly.  I'm just going to take any Mechanicum stuff until the proper release.  Should only be a few days - probably after this weekend.

**Comment by Ackoogin** [comment]
Couple more things ;)
Drop capsules for sentry guns should be 20 points.
Magos prime has maxselections of 0 for paragon blade.

**Comment by Millicant** [comment]
This is taking slightly longer than expected.  A lot of the entries still contain older options, so I'm going through them one by one to ensure accuracy.  

@Ackoogin those were some solid catches - I've incorporated them already.  Thanks for pointing them out!

**Comment by capitaladot** [comment]
@Ackoogin: who is missing the Djinn Skein?

**Comment by Ackoogin** [comment]
Magos Prime.

**Comment by capitaladot** [comment]
Djinn Skein is not missing; it is only allowed to the Archmagos Prime, per the unit entry.

**Comment by Ackoogin** [comment]
Aha found the option. Didn't realise I had to select the magos field to get
the option to appear!

It does appear to complain about taking two gun choices for myrmidax now
though? (Set max selections to 2 if 0 myrmidax).

**Comment by capitaladot** [comment]
Just fixed that; typo in the mod that should have allowed multiple
Myrmi-guns.
