### ISSUE TITLE
Specialized (Legion/Legio/Rite of War Specific) Detachments

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#155]
- [x] Decapitating Strike
- [x] Matrix of Ruin
- [ ] Maru Scara
- [ ] The Reaping

Please comment to add others with FoC slot number changes.

**Comment by Millicant** [comment]
Sorry, this is one I don't like getting implemented.  

The Matrix of Ruin is explicitly listed as a NEW Force Organization chart.  The others are modifications to the Age of Darkness FOC and I don't want to include them.  Putting in those modifications for every single Legion and Rite of War is hugely overkill.  

Not only does that add even more clutter to the choices of FOC, it means that making a list is then bound to that Rite of War until you make a new detachment.  

I'm aware that this results in errors for lists using these modified FOCs, but that is a software limitation and I dislike this style of workaround.  Accessibility and simplicity are more important to me than 100% no-errors accuracy.  The HH system is too complicated for that given the tools we have.  Perhaps if FOC modifying becomes available in Battlescribe at some point, we will implement this.

**Comment by capitaladot** [comment]
There are what, 10 FoC options in the HH as it stands? That isn't much; the 40k file has something like 30 or 40.

@Jonskichov has made it clear that he doesn't intend to implement mutable FoCs. http://battlescribe.uservoice.com/forums/55066-general/suggestions/1626271-move-the-force-org-chart-from-the-gamesystem-to

**Comment by Millicant** [comment]
I'm aware of how many there are for 40k, and that is specifically why I don't want to do that here.  It's incredible ungainly and painful.  

I read Jon's bit about not implementing FOC changes when it was written.  I suspect it will remain that way, however we can always hold on to hope.... :)
