### ISSUE TITLE
Magnus the Red missing Psychic Mastery

### ISSUE THREAD

**Issue by phantam23** [BSData/horus-heresy#1559]
When using the RoW which allow a Primarch to be selected as the HQ choice, selecting Magnus causes a Roster Error noting that the list requires a selection of psychic mastery.

**Comment by Mayegelt** [comment]
Sorted in a still to be applied update.

**Comment by zopha** [comment]
The update has been merged and released. Should be live for devices to update in 12-24 hours if it didn't get in the last one.
