### ISSUE TITLE
Missing Knight Atrapos, no option for Legendary Free Blade in Elites section

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#157]
**File:** (HH) Mechanicum - Questoris Knight.catz
- [ ] Missing Knight Atrapos and 
Will enter this once the model appears in a book.
- [ ] no option for legendary free blade in Elites section

**Comment by capitaladot** [comment]
Will enter this once the model appears in a book.

**Comment by capitaladot** [comment]
Is Legendary Free Blades in Book 4?

**Comment by capitaladot** [comment]
It is also absent from the new FAQ.
Closed. Will potentially re-open once these rules appear in a book.

**Comment by Millicant** [comment]
Agreed - closing this one until it is officially added.
