### ISSUE TITLE
 Maru Skara - Champion for compulsory second HQ

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1570]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.03.02

**Platform:** Android

**Dropbox:** No

**Description:** When selecting the rite of war maru skara for emperors children i am not getting an option to select a champion for a co1mpulsory second HQ.

**Comment by Mayegelt** [comment]
Had a quick look at this, and what was happening, is that it wasn't making you take a 2nd compulsory HQ. It was just insisting you take a Champion.
So previously you could have just taken the Champ and Fulgrim and it would have allowed it. This should not have been the case. So now you MUST take the Champ as 1 compulsory HQ and also take the additional Compulsory HQ of your choice.
Will post the fix when i'm done fixing other bits to go with it.

**Comment by zopha** [comment]
Closed by #1574
