### ISSUE TITLE
Erebus counts as both a Chaplain and Diabolist for both the Word Bearers Special Rules and Rites of War but if the Dark Brethren Rite of War is selected in Battlescribe it still states that the Diabolist requirement is unfulfilled.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#158]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** In the FAQ here http://www.forgeworld.co.uk/resources/fw_site/fw_pdfs/Horus_Heresy/Horus_Heresy_7th_Edition.pdf It states that Erebus counts as both a Chaplain and Diabolist for both the Word Bearers Special Rules and Rites of War but if the Dark Brethren Rite of War is selected in Battlescribe it still states that the Diabolist requirement is unfulfilled.

**Comment by Millicant** [comment]
Interesting.  I'm aware of the FAQ, I just need to fix that guy.  Thanks for the heads up!

**Comment by Millicant** [comment]
Hey @capitaladot 

Looks like you've been busy!  Great work! 

I finally have time to dive back in to this again.  Please sync up any updates you have, as I'm going to be editing the files starting tomorrow.  If possible - I'd like to avoid any more conflicts!

Thanks!
