### ISSUE TITLE
Fanmade - Asuryani Army List (Optional addition)

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#1583]
Hello.
A few months ago i stumbled onto Dono from http://www.facebook.com/AUS30K fanmade Eldar army list for 30K. I decided to make a battlescribe version of it. And wondered how others would feel about it being added to the other files.

It seems like a nice addition, but i can also see why it may not be appropriate to add, as it could set a president for anyone to add any fan made stuff to the lists. It causes no interference to the other lists, and as far as i am aware the only bug with it is, because Knights are in the gst file, rather than copies of each file, but that makes no real issue.

If its OK to do so, I can add the proper file to my next pull request, if not then I won't.

Location of the PDF version
https://drive.google.com/file/d/1F9LtytfQdQj47IDJO1wFunTkE2NMxYKu/view?fbclid=IwAR3ywjDu4Y7nBl3RzGzl5wfTNOPoL1oTht3nby9EX7ygKRI4XQCAlSnw0_A

Location of my Catz file version of it.
https://www.dropbox.com/s/mmeciqwrptj58rr/%28HH%29%20Craftworld%20Eldar%20-%20Asuryani%20Army%20List.catz?dl=0

@capitaladot @zopha I think you are the main admins of this repository of Github. So I assume it is up to you to give comment of Yay or Nay, and any feedback about the idea or maybe alternative solutions.

**Comment by capitaladot** [comment]
I am okay with it. I bought the hardcover. ;)

**Comment by zopha** [comment]
Sounds good to me as well. Separate from all the other catalogues so easy to manage.

Looking forward to the Necron version if they can keep going.

**Comment by amis92** [comment]
See https://github.com/BSData/catalogue-development/issues/5

**Comment by alphalas** [comment]
Which arguably means all the information for centurion mode should be stripped out

**Comment by capitaladot** [comment]
And yet, Centurion mode is widely played at the event/tourney level, all
around the world, including by the guy at Forgeworld who is now the HH
rules writer! I see no need to fragment the repo, and think marking fanmade
is plenty.

**Comment by amis92** [comment]
I'll just clarify, I've merely linked to the general policy we have in the organization, and also to collect the reference in that issue for all such requests.

As current maintainers of this repository, you make the call.

**Comment by alphalas** [comment]
Austin; that’s like saying if Robin Cruddace plays in ITC tournaments that use the ITC terrain rules the ITC terrain rules should be in the data files. It is *NOT* what BS is for.

**Comment by Mayegelt** [comment]
Ok. So mixed bag of opinions here.

Can I get clarification of opinion. I'm not sure who the full list of admins are currently.
A) put in with the rest
B) work out how to make it separate (if so I will likely need help with that)
C) just leave it as sharable via other means

**Comment by capitaladot** [comment]
I vote A. I invite anyone else who's submitted, reviewed, or merged a PR in
the last year (in short, a contributor) to likewise vote their preference.

**Comment by Mayegelt** [comment]
Side note (though same theme) I've also almost completed BSing the 30k Necron Dex from the same guy/guys.
Learning a bit about how to make the entries. Might mean I can tidy up or make some things easier to use on other lists.

**Comment by Revan1988** [comment]
To be honest, the Asuryani army list is widely embraced by a large portion of the Dutch 30k meta. We'd love to see it added. Clearly, a lot of work went into writing the list and making the PDF/hardcover book. It's that which sets it apart from other fanmade stuff. I sincerely hope it gets added to the BS data file proper.

**Comment by Mayegelt** [comment]
Looks like no others are chiming in. So I think I will try to finish off the Necron Dex as well. Then add both.

**Comment by Mayegelt** [comment]
Ready to pull. Also got the Necron one in there as well

**Comment by zopha** [comment]
Did these get added? (hope so :D )

**Comment by Mayegelt** [comment]
@zopha yes it did

**Comment by EberleG** [comment]
Any chance of doing the Aus30k Ork list as well?
