### ISSUE TITLE
Legion Roster errors since update 15.10.2019

### ISSUE THREAD

**Issue by Ozymandias1989** [BSData/horus-heresy#1589]
Since the battlescribe update yesterday all special characters and Legion Specific gear are available regardless of Legion chosen. Also, the Captain's Artificer Armour is now free (there are probably more errors like this but I haven't looked for them yet). I don't know if the errors extend to the other Army lists but it's quite likely. 

As it stands the Legion list is currently unusable.

**Comment by capitaladot** [comment]
Last release was 29 days ago... delete all data and try again.

What platform?

**Comment by alphalas** [comment]
It’s a known bug with the new release of battlescribe on windows and android - hide conditions just going fuckoff

**Comment by Mayegelt** [comment]
Just had this myself. Android 2.03.04 has messed it up for me as well

**Comment by Ozymandias1989** [comment]
@capitaladot The Android version of battlescribe was updated on the 15.10.2019. 

I've tried re-downloading and reinstalling everything multiple times now. Doesn't help.

**Comment by alphalas** [comment]
Like I said – it’s a known bug with BattleScribe itself. We’re just gonna have to wait for a fix.

**Comment by alphalas** [comment]
Dev Jon is aware of the issue - we should see if fix in the next day or two would be my guess - max a few days wait.

**Comment by Mayegelt** [comment]
I'm glad I didn't update my PC one.
Though tbh if I did I would have the old install files anyway to just go back.

**Comment by Mayegelt** [comment]
Looks like they have done a rollback. So hopefully should be working again

**Comment by Ozymandias1989** [comment]
@Mayegelt I can confirm that the problem seems to be fixed on Android. I assume this applies to the pc version as well.
