### ISSUE TITLE
Bug report: (HH) Mechanicum - Taghmata Army List.catz

### ISSUE THREAD

**Issue by ash-rid** [BSData/horus-heresy#1597]
There is a display issue with the Thallax troop entry. The unit is shown with the correct value of 135 points however in the expanded view the 3 Thallax are shown as 120 points

In the entry for the Ordo Reductor artillery battery the twin-linked bolter upgrade is treated as mandatory
![artillery](https://user-images.githubusercontent.com/56189952/68092420-d8eb1780-fe82-11e9-8ce4-0f47dd52c29d.JPG)
![thallax](https://user-images.githubusercontent.com/56189952/68092425-db4d7180-fe82-11e9-96e0-7a2fb574c397.JPG)

**Comment by Mayegelt** [comment]
You should notice that with a lot of entries.
Basically some units have a Unit tax. For a lot of marine units and things like that, the amount may be rolled into the cost of the sergeant.

**Comment by Mayegelt** [comment]
Fix will be added to my latest pull request momentarily.
