### ISSUE TITLE
Bug report: (HH) Talons of the Emperor

### ISSUE THREAD

**Issue by ash-rid** [BSData/horus-heresy#1598]
Valdor's points value is incorrect - In both Book 7 and the Custodes Errata is it 275 not 325

Arae-Shrikes points values are incorrect. They should be 2 points per model not 45 points per squad

**Comment by Mayegelt** [comment]
Check book 8. Custodes pts values were redone.

**Comment by ash-rid** [comment]
My apologies, I did not appreciate the Talons were also in book 8
