### ISSUE TITLE
Bug report: (HH) Questoris Knights

### ISSUE THREAD

**Issue by ash-rid** [BSData/horus-heresy#1599]
The Knight Crusader entry has multiple issues:
1. The primary weapon is not shown in the Roster view
When the Avenger cannon is exchanged....
2. Only the rapid fire battle cannon option is listed (the Questoris battle cannon option is missing)
3.  The detail view shows 3 weapons (Avenger cannon, Battle cannon & Thermal cannon)
![knight](https://user-images.githubusercontent.com/56189952/68092413-b0631d80-fe82-11e9-8087-2a7a35cb830f.JPG)

**Comment by Mayegelt** [comment]
I'll take a look into these ones. Should be a quick fix.

**Comment by Mayegelt** [comment]
Fix will be added to my latest pull request momentarily.
Did a bit of an overhaul of the knights. A lot of them suffered from this issue.

**Comment by Mayegelt** [comment]
Fixed
@capitaladot please close
