### ISSUE TITLE
Legiones Astartes: Crusade Army list

### ISSUE THREAD

**Issue by Toreador13** [BSData/horus-heresy#1610]
Thousand sons Praetors with psychic powers no longer can replace or add force weapon for 5 points when a power weapon is chosen, unless I can't find it somehow. It seems to be with the second (and) (or). If the second or with the specific leaders is removed the force weapon shows back up. (Praetor, Centurion, wolf lord, consol). I didn't get too much further into it as I am not sure how this data file is setup. But the root of the issue seems to be in there. 
![image](https://user-images.githubusercontent.com/6875311/69469202-2efdfd00-0d55-11ea-8900-3470050f8fd6.png)

**Comment by Mayegelt** [comment]
Fixed
