### ISSUE TITLE
(HH) Legiones Astartes - Crusade Army List-Terminator weapon validation

### ISSUE THREAD

**Issue by Toreador13** [BSData/horus-heresy#1612]
The same validation for weapons that is on Artificer armour needs to be applied to the terminator armour for exchanging both power weapon and combi-bolter for: 

Right now if you choose a pair of lightning claws or raven's talons the validation still requires you to have the basic weapon selections. This works for artificer armour. 

![image](https://user-images.githubusercontent.com/6875311/69485293-13e9c680-0e03-11ea-8d08-143cbdb015aa.png)

![image](https://user-images.githubusercontent.com/6875311/69485297-1e0bc500-0e03-11ea-8086-80de9682cc46.png)

**Comment by Mayegelt** [comment]
Fixed
