### ISSUE TITLE
(HH) Legiones Astartes - Crusade Army List

### ISSUE THREAD

**Issue by Toreador13** [BSData/horus-heresy#1613]
Seeker squads are right now not paying for their Combi-weapons. (+5pts), it looks like because the validation is not working to increase points. 
![image](https://user-images.githubusercontent.com/6875311/69561656-6649f500-0f73-11ea-898a-cd97b3f52724.png)
It looks like if the validation is moved up one level, it works correctly. 
![image](https://user-images.githubusercontent.com/6875311/69561980-e6705a80-0f73-11ea-8c32-08670b72e7ad.png)

![image](https://user-images.githubusercontent.com/6875311/69562002-eff9c280-0f73-11ea-9363-c1ec6b4e9bea.png)

**Comment by Polnor** [comment]
Hello everyone.
Same goes to assault squads, power weapons are free now.

**Comment by capitaladot** [comment]
This must be a BattleScribe bug/change.

**Comment by Polnor** [comment]
Hi there. maybe you are right, problem is on mobile version, pc version is fine.

**Comment by Toreador13** [comment]
Odd, I am using PC for these, and not working here.  Assault power weapons were fixed already, just not released.

**Comment by capitaladot** [comment]
I am wondering if this is a BattleScribe change or a misguided fix (aimed
at resolving whining about how Power Weapons/Combi Weapons were
cost-accumulated across multiple model squad selection groups).

**Comment by Mayegelt** [comment]
I had changed on my pull request the assault squad one. Nothing else. It seems one of the updates broke some points cost from linked sub menus.

**Comment by Mayegelt** [comment]
Just checking it. It seems like any link to a Selection Group Entry that has a points value assigned to it. Isn't assigning the points value to the purchase, unless it has it linked within a selection entry in the unit.

So fixed. But probably a whole heap of other issues out their with Power Weapons and many Combi

**Comment by Toreador13** [comment]
Ouch. We have been making lists recently, so I will keep submitting things we find. Typically I look in the actual data file before posting to see what's going on, and things that were working previously just don't seem to be working now the same way.

**Comment by Mayegelt** [comment]
I think this is also what did #1608 
As ogryn are charged 20pts a power weapon. And before it was charging 10+10pts. But since the issue only charged 10pts.

**Comment by Mayegelt** [comment]
Done
