### ISSUE TITLE
Mor Deythan Don't Have Sniper Profiles

### ISSUE THREAD

**Issue by JPGlaser** [BSData/horus-heresy#1616]
Hey all,
We are still missing the sniper profiles and a few other weapon profiles for the Mor Deythan. Any updates on this getting addressed?

~ Joe G.

**Comment by capitaladot** [comment]
The original file author didn't GAF about profiles and we have been filling
them in my dribs and drabs, over the years, in between changes. Keep filing
'em and we'll keep fixing' em.

**Comment by Mayegelt** [comment]
Will get on to it now

**Comment by Mayegelt** [comment]
Done
