### ISSUE TITLE
Legiones Astartes small fixes/improvements Alpha Legion & White Scars

### ISSUE THREAD

**Issue by Tomakokamikaze** [BSData/horus-heresy#1618]
Jetbike Sky Slayer Squad -> chainswords/CB not coming as default selection. & bolt pistol (sargent) not coming as default selection
Exodus is missing his Melta Bomb = 2016 red book
Alpharius Traits in "Sire of the Alpha Legion" as Counter Attack, Crusader and Others should be in his profile
Shamshir jetbike not giving riders +1 Toughness and +2 Armor Save. (Scimitar Bike working fine)

**Comment by Mayegelt** [comment]
Sky Slayer Squad chainswords now default option, and sergeant fixed to have their bolt pistol and chainsword as default selection..
Exodus given his melta bombs
Alpharius fixed.
Shamshir fixed for Praetors and Centurions.

**Comment by Tomakokamikaze** [comment]
ALso, before I forget, Tsolmon Khan not getting his +1 Toughness for beein on a scimitar bike

**Comment by Tomakokamikaze** [comment]
> ALso, before I forget, Tsolmon Khan not getting his +1 Toughness for beein on a scimitar bike



> Sky Slayer Squad chainswords now default option, and sergeant fixed to have their bolt pistol and chainsword as default selection..
> Exodus given his melta bombs
> Alpharius fixed.
> Shamshir fixed for Praetors and Centurions.

Also, before I forget, Tsolmon Khan not getting his +1 Toughness for beign on a scimitar bike

**Comment by Mayegelt** [comment]
Fixed @Tomakokamikaze, i should have done better. I was the one who added almost all of book 8 :D

**Comment by Tomakokamikaze** [comment]
Don't worry mate, I only play the Unpopular Legions, so I'm used to it. I could help with these minor fixes myself if you'd like?

> Fixed @Tomakokamikaze, i should have done better. I was the one who added almost all of book 8 :D

**Comment by Tomakokamikaze** [comment]
> Fixed @Tomakokamikaze, i should have done better. I was the one who added almost all of book 8 :D

Also
Chogorian Brotherhood Rite of War demand army's warlord to be mounted on a bike or jetbike
that would mean a SM bike, a Scimitar Jet-bike, a Shamshir Jetbike, or a Shojutsu Jetbike (Jagathai's bike)

also noting that if Jagathai is in LoW he is still the warlord, letting the compulsory HQ go on foot/jump pack.

**Comment by Tomakokamikaze** [comment]
@Mayegelt please take a look

**Comment by Mayegelt** [comment]
@Tomakokamikaze you have stumbled on to something that makes me a very sad panda

![image](https://user-images.githubusercontent.com/20280410/70349268-47454000-185c-11ea-9640-c2ad76b36b63.png)


Only Bike and Scimitar Jetbikes count for the Warlord. So no Shamshir or Shojutsu ones allowed. Meaning the Khan can't lead it.

He also has TWO Master-crafted Heavy Bolters! But has no rule allowing him to fire more than 1 a turn, and no way that they can be destroyed or anything, so rather stupid, as they don't even count as twin linked or anything.

Also Jagathai has no invulnerable save vs Interceptor (and some other thiings) as it happens in the Movement Phase, or Psychic, as that happens in the Psychic Phase.

![image](https://user-images.githubusercontent.com/20280410/70348998-c1c19000-185b-11ea-8213-ad946b020273.png)


Also as to your offer to help fix. the more the merrier. But I'm happy to do them. Just need time to do them sometimes, and like this, have to check old posts to see they have been added to.

**Comment by Tomakokamikaze** [comment]
@Mayegelt I am a very sad panda indeed. why are my Legions always so callously neglected by the rule writers?

found another Bug by the way:
Apothecaries: when choosing SM Bike 
-> Toughness +1 not applied
-> Weapon on bike is Bolter (should be Twin Linked Bolter)
-> Not saying the guy is very bulky now

Centurions: Not showing twin linked weapon profile

Outriders & Centurion: Don't have the SM Bike box that the Apothecaries have (either add it to them, or remove from apothecaries)
