### ISSUE TITLE
Vigilator Sabatoge Error

### ISSUE THREAD

**Issue by JPGlaser** [BSData/horus-heresy#1622]
Currently the rule for Sabotage is outdated and should refect the Red Book included below.

![SmartSelect_20191205-005215_Kobo Books](https://user-images.githubusercontent.com/11276213/70208195-e3efcc80-16fa-11ea-98ac-4063916d7d75.jpg)

**Comment by Mayegelt** [comment]
Fixed.

Just noticed that they have an ! at the end, and the Alpha Legion Saboteur doesn't and very slightly different rule.
 
![image](https://user-images.githubusercontent.com/20280410/70273125-659a3580-17a1-11ea-997d-87d761238d61.png)
