### ISSUE TITLE
(HH) Legiones Astartes - Crusade Army List.catz (World Eaters)

### ISSUE THREAD

**Issue by EberleG** [BSData/horus-heresy#1625]
Legion option for World Eaters to select Chain Axe (deselcting Chainsword) produces an error "chainsword or combat blade must have 1 more selection"

**Comment by Mayegelt** [comment]
I'll take a look. Any particular units, or just all of them.

**Comment by EberleG** [comment]
Tactical and Assault squad.  Also if additional close combat weapons are selected for Tacticals, no option appears to change that to chain axe (legion specific rules).

**Comment by Mayegelt** [comment]
Ok, found the issue and fixed,
Just needed to throw in a set min to 0 if world eaters.

**Comment by zopha** [comment]
Should be fixed in the latest merge and release.
