### ISSUE TITLE
Alternate Force Org Fortifications weirdness.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1636]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.03.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When using the Castellan force organisation and the Sacrificial Offering Rite of War, once any further selection is made the Fortification slot disappears or it’s existing selections have ‘hidden’ errors and all fortification options not already selected disappear.

**Comment by Mayegelt** [comment]
Interesting...
Though to note you can't use a RoW and an optional FoC at the same time anyway.

**Comment by capitaladot** [comment]
Maybe add that validation in re: RoW and Force Organizations that ban them

**Comment by Mayegelt** [comment]
Just rechecking my bookywook.
Seems you can take RoW, but only in really special situations. So not really sure if i should code it out.
![image](https://user-images.githubusercontent.com/20280410/71623129-40e38300-2bd2-11ea-8605-f12d1fa8ee96.png)

**Comment by capitaladot** [comment]
Great citation @Mayegelt
