### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by jpdorrian** [BSData/horus-heresy#165]
Hi I'd like to request to join, my are of interest is Ordo Reductor as it doesn't appear to run the way it should in the red books.

**Comment by capitaladot** [comment]
Checkout the new file (Taghmata complete) and file bugs as you like. It endeavors to handle all possibilities from the new Taghmata Army List red book, including Ordo Reductor.

**Comment by jpdorrian** [comment]
Awch thanks will download now thanks

Sent from my BlackBerry — the most secure mobile device — via the vodafone UK Network
