### ISSUE TITLE
Legiones Astartes: White Scars: Golden Keshig

### ISSUE THREAD

**Issue by Tomakokamikaze** [BSData/horus-heresy#1652]
Golden Keshig: Power Lance price is 0pts, should be 10pts
should also be a max for the number of chainswords/power weapons the unit can take.

Best wishes,

**Comment by Mayegelt** [comment]
The min/max seems to me working for me on weapons on Android. Or at least it flags errors if not enough taken.
Though the power Lance cost isn't, do will look into.

**Comment by Tomakokamikaze** [comment]
@Mayegelt The sergeant has no max on power weapons

**Comment by Mayegelt** [comment]
Fixed

**Comment by Mayegelt** [comment]
@capitaladot closable
