### ISSUE TITLE
Host of Angels / Flesh Over Steel

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#1653]
It seems these rules are not being flagged as issues for the LA data.
Will need to work on them. Though might be a pain in the arse to fix. Much like Orbital Assault still isn't in. And up to players to check their own stuff.

Host of Angels: With the exception of Dedicated Transports, a Blood Angels Detachment may not have more units with the Vehicle type than it has units with the Legiones Astartes (Blood Angels) special rule. Note that because of this, certain Rites of War may be unavailable to Blood Angels armies

Flesh Over Steel: A Raven Guard detachment may not have more units in total with the Vehicle (Tank) type than it does with the Legiones Astartes (Raven Guard) special rule. Note that because of this, certain Rites of War may be unavailable to Raven Guard armies.

**Comment by capitaladot** [comment]
This used to work.

**Comment by Mayegelt** [comment]
No idea when it stopped then. I tried blood angels, and couldn't get it to give me errors. I assume something in the force orgs has been removed at some point  as I couldn't see anything under vehicles or whatever.

**Comment by capitaladot** [comment]
Could have been gutted in people monkeying with the Legiones Astartes entries or the Force Orgs?

**Comment by Mayegelt** [comment]
No idea. Never played Bloods or Ravens. So never encountered the issue. I knew Orbital never worked. Because it's an arse to code as you don't know how many units are in non dedicated drops or vehicles

**Comment by Mayegelt** [comment]
Seems to be working, but needs the Legion restriction removed with shattered legion.

**Comment by Mayegelt** [comment]
Fixed
