### ISSUE TITLE
New Zone Mortalis Restrictions

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#1655]
- [ ] Add base size to Units
- [ ] Bar units with a >60mm base size
- [ ] Add model width to Vehicles 
- [ ] Bar units with >4" model width

**Comment by Mayegelt** [comment]
Might be worth just adding a catagory of "too big for ZM"
Then just tick the box for all tanks, Levi, Amiger/Moriax knights (and all other knights), Artillery platforms (I think, not sure with Rapiers), Telemon.
Never been sure, but can speeders be used? If not also Jetbikes have the same bases.
For Daemons it's only allow Swarm, Lesser, Beast, Brute, Chosen, Cavalry.

Can't think of any more. But if someone wants to write a quick list of anything I've missed out or got wrong, I could throw it in my next pull request.

**Comment by capitaladot** [comment]
I think tagging base size will be easier than that sounds like a big blacklist?

**Comment by Mayegelt** [comment]
Really? Adding every individual units base size rather than 1 catch all for everything not allowed.
With my suggestion, you could then just add something in the ZM Force org as a Max 0 "Too big for ZM". Rather than having to have multiple.

**Comment by Mayegelt** [comment]
I guess also it might need a hide function on units to hide unless equal to 1 in roster of
Zone Mortalis Attacker or Defender or Combatant.

**Comment by stvnksslr** [comment]
For what its worth im with Mayegelt on this one, a binary flag would make it alot easier to track here vs keeping track of base sizes for every unit and then filtering off that.

**Comment by Mayegelt** [comment]
Ok so I think my list is complete for LA

ZM Unusable
Arquitor
Deredeo
Land Raiders
Leviathan
Spartan
Typhon
Rhino (as it is only available as a dedicated transport, though like the Whildwind Scorp or Predators is actually less than 4" wide)
All Flyers

Also added restriction to max 15 models for:
Assault
Blackshield Marauders
Breachers
Grey Slayers
Medusan Immortals
Phalanx Warders
Tacticals

**Comment by Mayegelt** [comment]
Militia. Same as above for flyers, FMC, dedicated transports

Also added restriction to max 15 models for Grenadiers (including taking any special weapon guys).
Also with Levy and Militia Infantry Squads, 2 optional rules have been added. The first is to be able to split the squads like Solar are allowed to, or to reduce the unit down to 15models at the same cost.
