### ISSUE TITLE
Red Book - Ordo Reductor list update request

### ISSUE THREAD

**Issue by jpdorrian** [BSData/horus-heresy#166]
Hi 

Theres a few minor issues, a local tournament wants everything in battle scribe and I've noticed issues with my list via battlescribe that I cant see in the book.

- [x] Calleb Decima option for Decima Invictus is missing or I just cant see it,

- [x] The Ordo Reductor War coven seems to want to make you take battle automata rather than restricting you to half the units and states an error when you don't select any, Is it possible this was left over or copied from legio cybernetica? 

- [x] too many Macrocarid Explorator (dedicated transport for Calleb) max 0 if roster has equal to 0 sections of Thanatar

- [x] too many myrmadon secutors, max 0 if roster has equal to 0 sections of Thanatar

- [x] too many myrmadon destructors max 0 if roster has equal to 0 sections of Thanatar

- [x] 3 too many choices of Krios Battle tank squads, max 0 if roster has equal to 0 sections of Thanatar

- [ ] Only allows you to take 3 heavy supports rather than 4, 
Can't implement this one in BattleScribe without a separate Force Org for Reductor (other than Matrix of Ruin), and @Millicant has put the kibosh on that.

**Comment by capitaladot** [comment]
The idea with the Thanatar thing is to implement the Cybernetica Cortex restriction; you have to take Cybernetica Cortex Heavy Support before you may take the rest.

**Comment by jpdorrian** [comment]
Sorry I wasn't aware that order reductor had to take cybernetica as heavy support, I'll check when I get home as I don't have the book with me.  Just goes to show every days a school day

**Comment by capitaladot** [comment]
I will likewise double-check. :)

**Comment by capitaladot** [comment]
Looks like you were right, and the Cybernetica restriction was behaving incorrectly.

**Comment by jpdorrian** [comment]
Lol I was going nuts looking for the restriction and not finding it :)

**Comment by capitaladot** [comment]
I think these are all fixed. @jpdorrian, can you download the file and confirm for me?

**Comment by jpdorrian** [comment]
Thanks working much better, I still can't see the invictus upgrade for Calleb and the 4 heavy support slots, which you said would be an issue.  

Just to make sure I'm using the correct data set, I'm building the list using Togmhatta  army list v2 (Togmhatta Army List) then selecting ordo reductor from the legion option

**Comment by capitaladot** [comment]
@jpdorrian Are you downloading the file manually? I wanted you to test before releasing it. :)

**Comment by jpdorrian** [comment]
No can you send me the link to the file and I'll download it, that way there can be no confusion?

**Comment by capitaladot** [comment]
https://github.com/BSData/horus-heresy/blob/master/(HH)%20Mechanicum%20-%20Taghmata%20Army%20List%20(Complete).cat

**Comment by jpdorrian** [comment]
Sorry I'm getting the following error message when I try to use that file

Details:
Errors occurred updating data files from repositories
> https://github.com/BSData/horus-heresy/blob/master/(HH)%20Mechanicum%20-%20Taghmata%20Army%20List%20(Complete).cat: Error updating from repository https://github.com/BSData/horus-heresy/blob/master/(HH)%20Mechanicum%20-%20Taghmata%20Army%20List%20(Complete).cat: net.battlescribe.a.c.e: Data file is too old and is no longer supported (null)
	at net.battlescribe.desktop.b.j$1.a(BattleScribe:63)
	at net.battlescribe.desktop.b.j$1.doInBackground(BattleScribe:40)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by capitaladot** [comment]
Oh, indeed; rather than using that as a repo, you'll need to import it.

**Comment by jpdorrian** [comment]
Got it thanks, invictus upgrade working well thanks

**Comment by capitaladot** [comment]
Awesome, thanks.
