### ISSUE TITLE
Primaris Nullificator forced to pay for Cataphractii Terminator Armour.

### ISSUE THREAD

**Issue by TheRavingRaven** [BSData/horus-heresy#1665]
A centurion with the Primaris Nulificator upgrade is meant to get the Cataphractii terminator armour for free but is having to play points for it in the app. 
It needs to be edited so that Cataphractii armour is reduced to being free when the Primaris Nulificator Consul upgrade is selected.

**Comment by Mayegelt** [comment]
Thanks for this one, will get on that one now.

**Comment by Mayegelt** [comment]
In latest release
