### ISSUE TITLE
Dreadwing Interemptors Plasma Incinerator Mis-Priced

### ISSUE THREAD

**Issue by TheRavingRaven** [BSData/horus-heresy#1667]
The Plasma Incinerator for Dreadwing Interemptors is currently listed as free in the app and is meant to cost 15 points as per their datasheet.

**Comment by Mayegelt** [comment]
Yep. Already fixed and pulled yesterday. Just waiting for appspot push.

**Comment by Mayegelt** [comment]
In latest release
