### ISSUE TITLE
Combi-Grenade Launcher single use?

### ISSUE THREAD

**Issue by boada** [BSData/horus-heresy#1669]
From LAADAL: Page 124 (emphasis mine)

> Combi-weapons (Heresy-era)
> These are boltguns that incorporate a modified secondary weapon system with limited ammunition. Only one weapon may be fired at a time, with the boltgun component unlimited in its use **while the secondary component may only be used once during the game.** The following secondary weapon types are available to combi-weapons in Heresy-era games:

> 
> Flamer
> Meltagun
> Plasma gun
> Grenade launcher
> Volkite Charger

The HH main rule book: Page 177

This also gives rules for combi-weapons. It specifies that melta (and the like) are single use, but the grenade launcher and volkite charger are not listed as single use.. 

Right now, BS specifies the meltas are single use, and cites the HH main book for the grenade launchers. Does this need to be changed?

**Comment by Mayegelt** [comment]
Age of Darkness Rulebook FAQ Pg6

On page 177 of the Age of Darkness Rulebook, combi-volkite chargers and combi-grenade launchers aren’t ‘one use’, is this intentional?
Yes. This is intended to balance these varieties of combi-weapons against combi-plasma gun and combi-meltagun weapons.

**Comment by boada** [comment]
Thanks @Mayegelt. I guess I need to get myself a copy of this FAQ.
