### ISSUE TITLE
Perturabo of Iron warriors can take Tormentor as his transport in 3k+ games and its not counted as LoW.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#168]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** Hello I'm not sure but probably you have error in 30k data, LoW can take up to 25% of points but Perturabo of Iron warriors can take Tormentor as his transport in 3k+ games and its not counted as LoW. Doing my 3k list in battlescribe I get error that LoW take too much points.

**Comment by capitaladot** [comment]
Perturabo is a Lord of War...
