### ISSUE TITLE
[Bug] Upgrading to Forge Lord does not have Tech-Marine Options

### ISSUE THREAD

**Issue by JPGlaser** [BSData/horus-heresy#1681]
As the title says, when you upgrade a consul to a Forge Lord, you should be able to take extra war-gear that is given to Tech-Marines as well as having all of their defaults. However, this is not the case.

How can we go about fixing this up?

~ Joe G.

**Comment by Mayegelt** [comment]
Works for me

![IMG_20200414_093509](https://user-images.githubusercontent.com/20280410/79203693-4b4d2400-7e33-11ea-941d-2740d23b1109.jpg)
![Screenshot_2020-04-14-09-34-09-072_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/20280410/79203704-50aa6e80-7e33-11ea-97cb-2a97151542b0.jpg)
