### ISSUE TITLE
Word Bearers Chaplain can’t select Tainted Weapon

### ISSUE THREAD

**Issue by crackedgear** [BSData/horus-heresy#1684]
As I understand it, the Chaplain Consul can upgrade his crozius to a Power weapon, and then exchange that for a tainted weapon. If I select a power weapon and then tainted weapon, it tells me I have too many weapons selected. If I just select tainted weapon, I’m told I need to select a crozius.

**Comment by Mayegelt** [comment]
The Crozius is itself a type of power weapon. As per FAQ the Crozius can't be exchanged for anything.
