### ISSUE TITLE
Shattered legions Rite of War after isstvan bug

### ISSUE THREAD

**Issue by chewiexd** [BSData/horus-heresy#1685]
Hello!

The shattered legion: Rite of war - After isstvan: says veteran tactical squads can be taken as non-compulsory troops but does not come up as an option in troop choices and battlescribe doesn't show an error code when we the number of tactical squad selected exceeds veteran tactical squads (as the RoW specifically states you can not have more base tactical squads over veterans).

**Comment by Mayegelt** [comment]
Thanks for the report, just put a fix up. Should be live when i do another big update.
Also fixed the requirement for a Centurion/Praetor (or equal character) to be from Salamanders, Ravens or Ironhands.

**Comment by Mayegelt** [comment]
Pulled and pushed today. Hopefully live in the next couple of days.
