### ISSUE TITLE
When using legion word bearers an additional chaplain or centurion is not made necessary as is required by "charismatic leadership". 

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#169]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** Yes

**Description:** When using legion word bearers an additional chaplain or centurion is not made neccesary as is required by "charasmatic leadership". Furthur  more erabus does not register as a diabolist when fullfiling the requirements for dark bretheren.

**Comment by Millicant** [comment]
Erebus is covered by another issue - I'm going to leave that one in place.

The additional chaplain/centurion requirement is not realistic to implement in Battlescribe, unfortunately, as I cannot specify which is the first vs an "additional" - it's just one of those things you'll have to track yourself when making a list!  Sorry!
