### ISSUE TITLE
Imperialis militia and cults LOW

### ISSUE THREAD

**Issue by TheRavingRaven** [BSData/horus-heresy#1710]
Can you please add the option to use the panoply of war rules for selecting a Lord Of War in the militia and cults army, the rules in the Crusade Imperialis red book have been superseded by the rules on pg 131 of the Horus Heresy main rule book, as mentioned in the Horus Heresy General Errata and FAQ V1.1

**Comment by Mayegelt** [comment]
Are there currently any missing entries? Or is it just that they are spread out currently?

**Comment by TheRavingRaven** [comment]
What is missing is all the flyers, all baneblade varients apart from the baneblade and storm hammer, all the macharius varients and also the crassius varients.

**Comment by Mayegelt** [comment]
Ok cool. I'll spend some time on that in the next week if I can. Probably combining with #1696 
Not sure why this has been missed for so long.

**Comment by TheRavingRaven** [comment]
Probably because no one plays militia as a primary detachment
