### ISSUE TITLE
Militia And Cults cyber augmented Issue bug.

### ISSUE THREAD

**Issue by TheRavingRaven** [BSData/horus-heresy#1712]
Selecting the cyber augmented providence of war causes an error to appear stating that "too many instances of cyber augmented have been selected (max 0)"

**Comment by Mayegelt** [comment]
Looks like a transplanted error. It seems when I select traitor Legion it doesn't give an issue but when I selected loyalist it did. So I assume that a hidden function has been put on that and may not have been put where it was meant to be, or what it was meant to reference.
I think if I remember rightly you cannot have this one and Gene crafted at the same time.
