### ISSUE TITLE
Caleb Decima's Isstvan III Survivor Force

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#172]
- [ ] Unique FoC
- [ ] Copy all units allowed
- [ ] Copy all Legion Heavy support choices, of which one can be taken.
- [ ] Add first turn only Stealth special rule

**Comment by capitaladot** [comment]
This is a bunch to do for a very, uh, unique option.

**Comment by Millicant** [comment]
I'm afraid this is far too specific to be engaged.  The restrictions are so tight and come from too many sources - it would almost be simpler to create a new catalogue to cover them!  Users following these restrictions will simply have to keep themselves honest.
