### ISSUE TITLE
Drop Pods do not conform to FAQ (normal) Drop Pod rule.

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#175]
Drop Pods should follow the FAQ'd ruling and behave as normal Drop Pods, not as assault-proof bunkers.

http://www.forgeworld.co.uk/resources/fw_site/fw_pdfs/Horus_Heresy/Horus_Heresy_7th_Edition.pdf

“Once a Drop Pod lands, all passengers must disembark and no models can embark for the rest of the game.”

**Comment by Millicant** [comment]
Agreed, they do act that way.  This ultimately has no bearing on the catalogue, however. That rule is not even written out in the LA:CAL.
