### ISSUE TITLE
HH V1 - Let's add Zone Mortalis Stratagems (Optional Rule)

### ISSUE THREAD

**Issue by Tomakokamikaze** [BSData/horus-heresy#1751]
*Out of topic: Armies of Dark Compliance is not working right.

Unless specified in their description each stratagem may only be taken once per force.
In a Zone Mortalis Mission it is recommended that each side has an allowance of 1 Stratagem point, plus an extra 1 Stratagem point for every full 500 points of their force, (SO A 1000 point Zone Mortalis force would have 3 Stratagem points to spend, etc).

**Declaring the use of Stratagems**
Players should declare the use of their stratagems when indicated in their description. In most cases this will be readily apparent anyway such as in the case of extra units or special terrain, but if for nay reason both sides have a stratagem whose effects would occur at the time, they should roll-off to determine which one takes effect first.

**Special terrain**
Some stratagems provide unique terrain pieces with game effects, if this is the case then these should be placed by the owning player after the deployment zones have been decided on, but before any models in the force are deployed.

**Istvaan III Zone Mortalis Stratagems:**
_-General Stratagem (Available to attacker and Defender):_
->Tunnel Access [Terrain][3SP]
Declare when placed. You may place three hatch markers anywhere on the table no less than 12" apart from each other, and not in impassable terrain. Should you wish it, any units with the infantry type in your reserve may enter the game via the deep strike rule using one of these hatches only as the chosen arrival point from which their arrival may scatter as normal.

->Breacher Charges [Gear][1SP]
Choose two infantry models other than an Independent Character. These models are now each equipped with a single breacher charge, a combat explosive device designed for breaking into bunkers and blasting apart bulkheads.
This stratagem may be taken multiple times.
*Add Breacher Charge Gear rule

->Flanking Counter Assault [Tactic][2SP]
Before the game begins, the player may nominate (by writing it down) a single unit that is to be held in reserve to be their flanking force. When this unit becomes available to enter play normally via the Reserves rule, it may use their opponent's deployment zone table edge to do so if they wish.

->Lascutter [Gear][1SP]
Choose a single infantry model other than an Independent Character, and that is not already equipped with this weapon bought as a unit upgrade. This model is now equipped with a Lascutter, a powerful industrial tool that can be used for cutting through armored bulkheads or as a makeshift but devastating close-quarter weapon.
This stratagem may be taken multiple times.
*Add Lascutter Gear rule

->Spearhead Sentry Gun [Terrain][2SP]
Deployed with Spearhead Forces. Both attacking Zone Mortalis forces and Defenders often deploy automated weapons system to provide them with fire support, usually covering a vital area or important access chamber. This weapon is a light artillery mount equivalent to an Imperial Tarantula, Heavy gun servitor or defense platform. It may not move once deployed but may freely engage enemy targets in the Shooting phase with a 360 degree arc of fire, so choose its location wisely! It h sno crew but is self-targeting and so in the control of the Owning Player. the Sentry Gun may make an Overwatch Snap-shot if assaulted.

WS	BS	S	T	W	I	A	Ld	Sv
-	2	6	2	-	-	-	-	4+

Unit type: Artillery (60mm base)
Wargear: Searchlight
	Choose one of the following weapons:
		-Twin-linked heavy bolter
		-Twin-linked heavy flamer
		-Twin-linked rotor cannon

*Add Tarantula profile

_-Attacker's Stratagem:_
->Interdiction Assault [Terrain][2SP]
During the Attacker's first turn they may place a Blast (3") marker anywhere on the board that is not either touching an enemy model, impassable terrain or an objective. This then scatters D6" (with the Hit symbol indicating the breach is bang on target.) If this scatters off the table or into impassable terrain, simply move it as close as possible away from the terrain or board edge. This blast marker now represents a breach point and remains in place for the rest of the battle. Up to one infantry unit per turn arriving as reserves may use this breach to enter play as normal.

->Sustained Assault [Tactic][3SP]
Before the game, the Attacker may choose a single infantry unit taken as a Troops choice for the army and secretly marks it down. Should that unit be wiped out or fall back, the Attacker may reveal this stratagem and remove the unit form play (if still present) and return it at full strength to their reserves. This may only be done once.

->Fire Wasp [Unit][1SP]
The Fire Wasp is a single model with the following profile which is deployed in addition to the players's spearhead forces.

WS	BS	S	T	W	I	A	Ld	Sv
2	2	3	5	2	2	1	10	4+

Unit Composition: 1 Fire Wasp
Unit type: Infantry (40mm base)
Wargear: Searchlight, Flamer and Close Combat Weapon
	Choose one of the following weapons:
		-Twin-linked heavy bolter
		-Twin-linked heavy flamer
		-Twin-linked rotor cannon
Special Rules: Fearless, Move through Cover and Scout

*Add Fire Wasp profile

_-Defender's Stratagem:_
->Defensive Strongpoint [Terrain][3SP][†]
After deployment areas are worked out but before any models are deployed, the Defender may either nominate one enclosed or semi-enclosed area of terrain to their defensive strong-point (alternatively a new piece of terrain such as a small pill box or square of Aegis line may be added to the set-up to represent the stronghold). A small model should also be placed within this area to represent the stronghold's power generator. Defending troops within the strong-point benefit from a 4+ cover save, and in addition, while the stronghold's power generator is intact (this may be targeted separately as previously stated), models within the strong-point may re-roll failed shooting attacks which roll a 1 to hit, and the Defending side gets +1 to all Reserve rolls.

->Barricades [Terrain][1SP]
Declared when placed. The defender has three 4" wide barriers or barricades they can place anywhere on the board after their deployment area has been decided, but before any models are deployed. These barriers provide a 4+ cover save for any model firing from behind them and count as difficult ground for any model trying to cross them.
This stratagem may be taken multiple times.

->Traps [Terrain][2SP]
Declare when placed. This stratagem may be taken multiple times.
The Defending player gains six trap markers (you can use models on a 20mm base, poker chips or nay other convinient counters to represent these). These may be placed by them anywhere on the board after the deployment areas have been decided, but before any models are deployed. Any model within 2" of the centre point of one of these markers during the game has a chance of setting off a trap. In the case of squads, move the whole squad before seeing if the trap goes off. If this happens roll a D6 and apply the following effect:
D6	Result
1	No effect
	(remove the marker from play)
2-3	Not this time
	Nothing happens but the marker remains where it is)
4-6	Boom!
	Place the Large Blast (5") marker centered on the center point of the trap marker. All models caught in the blast suffer a Strenght 4 AP 5 hit. models with an Armor Value (AV) are hit on their rear armour. The trap marker is removed from play.

**Zone Mortalis Boarding Assault Stratagems:**
_-General Stratagem (Available to attacker and Defender):_
->Void Hardened Armour  [Gear][1SP]
Chose a single unit in your force of any type. This unit is equipped with specialised additional armour and life support systems and now counts as being Void Hardened (see the Cold Void mission special rules from Betrayal).
This stratagem may be taken multiple times.

_-Attacker's Stratagem:_
->Shock and Awe [Tactic][1SP]
This stratagem may be declared an used at the start of any of the Attacker's turns in the Movement phase. The attacker rolls a D6 for every Defending unit in play and not engaged in an assault. On a 4+, the target takes a Pinning test. The Defender now does the same for Attacker units not engaged in an assault, and they suffer a Pinning test on a 6.

->Phase Field Generator [Gear][2SP]
Show on Model. Choose a single Infantry model other than an Independent Character. This model is now equipped with a Phase Field Generator. This can be modeled as a back pack-mounted system, and does not preclude the model from using other weapons. Once per game, the model and their squad (including any Independent Characters that have joined it) may move through a closed bulkhead door or through a single Zone Mortalis wall section. This counts as dangerous terrain, representing the phase field flickering out of sync and trapping a warrior within the stuff of the bulkhead, and so any model that fails its Dangerous terrain test is slain outright.

->Devastation Drone [Unit][2SP]
The Devastation Drone is a single model witht he following profile, and is deployed in addition tot he player's spearhead forces.

WS	BS	S	T	W	I	A	Ld	Sv
2	-	3	5	1	1	-	10	4+
Unit Composition: 1 Devastation Drone
Unit type: Infantry (20mm base)
Wargear: Implosion Charge and Void Hardened Armor
-Implosion Charge: The Devastation Drone may be detonated at any point in one of its controlling player's Shooting phases. Place the Large Blast (5") template over the center of the Drone. Everything caught by the blast suffers a Str 8 AP 3 hit and the Devastator Drone, along with any removable terrain models (including bulkhead doors), is removed from play. The Drone may be detonated even if it is engaged in an assault at the time.
If the Devastation Drone suffers a wound, the attacker should roll a D6. On the roll of a 1, the Drone detonates where it is as per the Implosion Charge rules just described. On a 2+ the Drone is removed normally.

Special Rules: Fearless and Move through Cover

_-Defender's Stratagem:_
->Security Airlocks and Bulkhead Doors [Tactic][2SP]
After deployment but before the roll for the first turn, the Defender indicates up to D3+1 bulkhead doors anywhere on the table. These doors are controlled by the Defending player, as per the rules for bulkhead doors on page 170 of Betrayal.
This stratagem may be taken multiple times.

->Murder Servitor Auto-clade [Unit][2SP]
Declared when deployed.

WS	BS	S	T	W	I	A	Ld	Sv
5	1	5	3	1	3	3	8	-

Unit Composition: 3 Murder Servitors
Unit type: Infantry
Wargear: Close combat weapon (Rending)
Special Rules: Fearless and Failsafe Mindlock
-Failsafe Mindlock: Unless it has been joined by an Independent Character, an unengaged Murder Servitor Auto-Clade that does have line of sight to an enemy model must roll a D6 at the start of its turn. On a 4+, there is no effect. on a 1-3, the unit (and any attached Independent Characters) may not move, shoot or charge until their next turn.

->Voidsmen Gang [Unit][1SP]

WS	BS	S	T	W	I	A	Ld	Sv
2	2	3	3	1	3	1	7	5+

Unit Composition: 6 Voidsmen
Unit type: Infantry
Wargear: Close combat weapon, Shotgun or Laspistol and Void Hardened Armour

**Comment by Mayegelt** [comment]
Sadly Army of Dark Complience has never really worked.
Basically it is both Militia and LA rolled into 1, and the specifications are a pain in the arse due to this.
I think the only way to make AODC to work is a separate army selection type (must like Mech, Aux, Knights, Talons...) in which is is just cross linked to both files. However i predict issues with this as "Troops" "Elites" "Fast Attack" and all those categories have unique ID's to the army. Rather than a universal one to the GST. As such it will start demanding you have a compulsory marine HQ and 2 troops & a compulsory Militia HQ and 2 troops.

As for the Stratagems it would be a nice to do, but currently will sit here unless anyone else wants to work on it, unless i get bored.

**Comment by alphalas** [comment]
AODC *did* work - then logic was changed for other things because AoDC was considered “less important”.

**Comment by Mayegelt** [comment]
> AODC _did_ work - then logic was changed for other things because AoDC was considered “less important”.

Ahhh I never realised it worked. I knew there were 2 different entries for it. One inside the Legions list and there was also one for FoC, But never saw them both working together to get both to work at the same time.

**Comment by Mayegelt** [comment]
Moved to new repo for HH1 located here.
https://github.com/BSData/horus-heresy-1e
