### ISSUE TITLE
Bug Report: Sons of Horus Reaver Attack Squad

### ISSUE THREAD

**Issue by PatentedGraph53** [BSData/horus-heresy#1752]
When creating a Reaver Attack Squad, of the squad is equipped with Hardened Armour, the error "Reaver Attack Squad cannot have any selections of The squad (including the Sergeant) may be equipped with one of the following: (hidden)". 
If Artificer Armour is selected (instead of hardened armour) the same error is still present, as well as "Reaver Attack Squad must have 1 more selections of Hardened Armour (minimum 1). 
If (None) is selected, the first error is removed but the second error remains, with the category "The squad (including the Sergeant) may be equipped with one of the following:" is no longer present.

**Comment by Mayegelt** [comment]
Fixed. Had a Min 1 selected when it shouldn't have been.
Will hopefully go live today with the remaining issues fixed.
