### ISSUE TITLE
Missing Mechanicum Abilities

### ISSUE THREAD

**Issue by Catgut** [BSData/horus-heresy#1761]
- Archmagos Dominus should have a 5+ FNP.

- Domitar should have Atomantic Shielding on its profile.

- Magos Prime's Ordinator order should have Armourbane, not Tank Hunters.

(Apologies if these are accurate and it is my information that is out of date; I am working from the Taghmata army book + latest FAQ/errata)

**Comment by Mayegelt** [comment]
Will get them fixed up. Did a bunch of fixes I noticed the other day. But still missed a load it looks like. A lot of weapons didn't have profiles or rules attached.
