### ISSUE TITLE
Bug Report: Fulmentarus Terminaors

### ISSUE THREAD

**Issue by PatentedGraph53** [BSData/horus-heresy#1763]
When a Fulmentarus Terminator Squad is created, the error "Fulmentarus Terminator Squad must have 1 more selections from Entire Squad may exchange their Combi-bolters for: (minimum 1)". 

Selecting Combi-Bolter does solve the the error, however if the user also selects in the "Entire Squad may take: " section, the "Cyclone Missile Launcher" option, a new error apears, "Fulmentarus Terminator Squad has 1 too many selections from Entire Squad may take: (maximum 0)".

If the user instead leaves the selection for "Entire Squad may exchange their Combi-bolters for: " to "(None)" an selects the Cyclone Missile Launcher option mentioned before, the initial error remains present, and selecting the "Combi-Bolter" option also leads to the second error again.

**Comment by Mayegelt** [comment]
Interesting bug. Not sure when it appeared, but just fired through a fix now. Thanks for the report.
