### ISSUE TITLE
Vultarax Stratos Automata FAQ changes

### ISSUE THREAD

**Issue by Frobbe** [BSData/horus-heresy#1778]
the Vultarax has lost its Flare Shield but gained Atomantic Shielding
It has gained Night Vision 
It has Gained Reactor blast (like all other automata from the mechanicum)
the Power blades are paired weapons (if chosen)
and it has the linked Neural nodes, see text in attached picture. 

No changes to the statline. 
<img width="375" alt="vultaraxFAQ" src="https://user-images.githubusercontent.com/18627008/93991188-49956e00-fd8c-11ea-98c1-7424de02162b.png">

**Comment by Mayegelt** [comment]
Interesting. I thought these had already been done. But at some point they either haven't been or they got reverted.
Thanks for the report.

**Comment by Frobbe** [comment]
Fast changes, but it appears it didn't gain Atomantic shielding in the update :D
