### ISSUE TITLE
Bugs from the Book 9 merge

### ISSUE THREAD

**Issue by Gschlotter** [BSData/horus-heresy#1783]
Good morning,

I see some bugs in the data, that are happening since the merge of the book 9 to the master.

Dark Angels:

Combi-Grenade Launcher:
- [ ] change Stasis Shells from free and must to take to 5 points and optional  (even if every DA player will buy them anyways)

Plasma Burner choices:
- [ ] Plasma Burner are missing as an option for all modells that can recieve a plasmagun and twin-linked plasmagun

Deathwing Companion Detachment:
- [ ] the Combi-Grenade Launcher is in the selection named as "Grenade Launcher"

Jetbike Sky Seeker
- [ ] change Stasis Shell points from 5 per quad to 5 per modell

Older Issue: Destroyer Grenade Launcher:
- [ ] Should be able to get Stasis Shells

Night Lords:
Night Raptor Squad:
- [ ] change the Nostraman Chainglaive of the Huntmaster with a Headsman's axe

General:

Master of Legion:
- [x] When I select a Praetor or named, I get the error that I have to many Master of Legions (maximum 0)

Sabre Strike Tank:
- [ ] Volkite Saker got changed in Book 9 to 0 
- [ ] Sabre Strike Tank lost the Missle Lock rule, which was added to the Sabre Missiles directly

Every Legion
- [ ] remove "The Unbroken Vow" RoW fomr other legions than the Dark Angels

I hope that helps you a bit

**Comment by Mayegelt** [comment]
Thanks for reports. I found another

- [ ] tactical squads not counting as compulsory in many RoW that they should be.

I think I know where the issue is, but I'm at work for the next 7 hours, so will push a fix when home, if it's what I think it is.

**Comment by Mayegelt** [comment]
The Master of the legion one should go away when you go above 1000 points

**Comment by Gschlotter** [comment]
It is goes away at 750 points for some reason, but ok this is fine

**Comment by Gschlotter** [comment]
- [ ] Breacher Squad can take Rad Grenades in the Eskarton Imperative without Dreadwing Rule

**Comment by Mayegelt** [comment]
> * [ ]  Breacher Squad can take Rad Grenades in the Eskarton Imperative without Dreadwing Rule

Looks like a few others fell into that trap as well.

**Comment by Gschlotter** [comment]
Deathwing Companion Detachment: Melterbombs wrong point costs, should be 25

**Comment by Mayegelt** [comment]
Will get onto that when home as well. Managed to crack a bunch out at work at lunch

**Comment by Mystic1027** [comment]
One more from the Book 9 stuff.  Alpha Legion - Rewards of Treason entry looks to be missing the option for Contekar Terminator Elite.

**Comment by Gschlotter** [comment]
one mor thing

Night Lords:
Contekar Terminator Elite:
- [ ] Escaton Power Claw should cost 15 points, not for free.

**Comment by Mayegelt** [comment]
#1785 fixed
