### ISSUE TITLE
The Steel Fist Independant Character Transports

### ISSUE THREAD

**Issue by TheRavingRaven** [BSData/horus-heresy#1784]
Independent characters with the Scion of the Ironwing, in The Steel Fist, cannot buy a Land Raider Phobos or Land Raider Proteus even though RAW they should be able to.

**Comment by Mayegelt** [comment]
Interesting, hadn't thought about being able to do that, but yeah its possible. Same for Tech Marines.

**Comment by Gschlotter** [comment]
I also saw that Breacher with 15+ man should be able in the Steelfist to take Spartans, for Tactical it works.

**Comment by Mayegelt** [comment]
Will get onto that as well in an hour or 2

**Comment by Mayegelt** [comment]
#1785 fixed
