### ISSUE TITLE
Mechanicum issues

### ISSUE THREAD

**Issue by Frobbe** [BSData/horus-heresy#1786]
**Secutarii Hoplites:**
Listed as peltasts in the rendered list, shown correctly everywhere else

**Vultarax Stratos-Automata**
Missing Atomantic Shielding

**Thallax Cohort:**
the upgrade augments are listed weirdly, they're otherwise correct. Perhaps have them be radio buttons on the unit entry itself instead of having to choose the option to give them the upgrades, navigate to the upgrade and then selecting?

**Vorax Class Battle-Automata**
Missing the monstrous creature rules:
Fear, Hammer of Wrath, Move Through Cover, Relentless, Smash, 

**Paragon Of Metal** 
Does not add Rampage rule to model which it is purchased for. 

**Archmagos Prime**
Relics of the dark age of technology

Contagium Mechanica missing description
> The virus is directed at a vehicle using the profile below. If the damage results in the vehicle losing a Hull Point but not being destroyed, there is a chance the virus will spread to another vehicle. So long as the vehicle is still in play in the bearer's next Shooting phase, every vehicle(friend or foe) within 12" of the original target sustains a single Haywire attack. the process is continued in each of the bearer's Shooting phases, with every vehicle that loses a Hull Point but which is not destroyed "infecting" the next, until no more vehicles are eligible to be infected. 

Cloaking array missing description
> Once per game, at the beginning of any game turn, the cloaking array may be activated. For that entire turn, the bearer may not be targetet by shooting or declared as the subject of a charge. Enemy models with the psyker or Daemon rule are not affected by the cloaking array, as they have other means of perceiving their foe. Should such a model shoot or assault the bearer, the cloaking array ceases to function immediately. The bearer may not use the array if joined to another unit, or engaged in an assault, and may not move, shoot, charge or declare any other actions while it is in effect. 

Combat Augment Array missing description
> Once per game, Declared at the beginning of the controlling player's player turn, the character may count any dice roll as automatically rolling a 6. At the end of that player turn, the model should make a Toughness test for every wound they have remaining. each failed test results in the character sustaining a wound, with no saves of any kind of Feel No Pain rolls possible.

Cortica Primus missing description

> The cortica Primus counts as a Cortex Controller. In addition, if the bearer uses a Cybertheurgy power to target a friendly unit, the effect of the power used applies not to one model in that unit, but to all eligible models in that unit. If the power is failed however, the subsequent roll on the Cybertheurgy Mishap table is modified by the number of models over the first it was attempted on. For example, if target unit consisted of three Battle-Automata, the roll on the Mishap table would be modified by a +2.

Phase Walker missing description
> Instead of moving normally in the Movement phase, the bearer may be removed and replaced anywhere else on the table, so long as they are not engaged in an assault or inside a transport vehicle or building. If the model is to be repositioned in a location that is within their line of sight, they are simply positioned where the player desires. If the target location is outside of the character's line of sight, make a Dangerous Terrain test for every solid object along the parth (including all models, vehicles, terrain pieces, buildings, etc) and so long as the character survives, place them in the desired position. Having been moved, the character counts as having deployed via Deep Strike and so counts as having moved, but may shoot, run, etc, as normal.

Void Shield Harness missing description

> The void shield harness has an area of effect equal to a Large Blast (5") marker, centred on the bearer. Any shooting attack that originates from outside of the protected area and hits a target inside it instead hits the void shield - which has an armour value of 12. A glancing or penetrating hit (or any hit from a Destroyer weapon) causes it to collapse. Once the shield is collapsed, further hits strike the original target instead. If the shield is collapsed, at the end of each of the controlling player's player turns roll a D6. on a roll of 5+, the shield is instantly restored. 
When rolling to penetrate the void shield, a result of Explodes! indicates a catastrophic overload. In this instance, resolve a Large blast (5") attack centred on the bearer at Str 6 AP 4 Pinning, after which the shield may not be used again for the remainder of the game. 

Warp Shunt Field missing description
> The warp shunt field provides the bearer with a 3+ invulnerable save against Shooting attacks only. In addition, for every 6 rolled when saving against an enemy attack that draws a direct line of sight between shooter and target, the enemy unit that fired the shot takes D6 Str 5 AP- hits.

I'll probably find more as i use more models in my army lists :D

**Comment by Mayegelt** [comment]
Will get onto them. I was sure I had previously fixed some of those.

**Comment by Mayegelt** [comment]
#1785 fixed
