### ISSUE TITLE
Legio Cybernetica Archmagos Point value 

### ISSUE THREAD

**Issue by thorgrimbloodskull** [BSData/horus-heresy#179]
Point value for archmagos dominus is 155, currently only 100 with upgrade

**Comment by thorgrimbloodskull** [comment]
Also save is now. 2+ in the Taghmata book.

**Comment by capitaladot** [comment]
Which one? There are several in the book.

**Comment by thorgrimbloodskull** [comment]
Legit Cybernetica archmagos dominus of 75.

**Comment by capitaladot** [comment]
I am afraid then that you are looking at the wrong unit entry.
Select Legio Cybernetica as Legion, then select the Archmagos Dominus entry that appears.
I know this is confusing; this is the nature of this book.

**Comment by thorgrimbloodskull** [comment]
Ah.  Thanks
