### ISSUE TITLE
NIght Lords Raptor wargear options and points

### ISSUE THREAD

**Issue by Gschlotter** [BSData/horus-heresy#1790]
Night Raptor Squad:
Huntmaster:
- [x] Plasmapistol change to 10 points
- [x] Add Trophies of Judgement for 5 points
- [x] Remove all Meele Weapon options except for Headsman's axe

**Comment by Mayegelt** [comment]
Done. Though the weapon options are still the same as "All members of the unit may..." for those ones. So that includes him.

**Comment by Gschlotter** [comment]
oh, yeah right, good that 2 persons saw it wrong.

**Comment by Mayegelt** [comment]
Issue for a lot of the Night Lords stuff is I did it all once, but then that version of the Cat had to be scrapped due to issues made with it and conflicts with the main file. So I rush jobbed it to redo it.
