### ISSUE TITLE
Terror assault

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#1793]
Note to self
Limitation on consols removed. Error showing.

**Comment by Hamemer** [comment]
Hope you don't mind if I put it here since its also about night lords , but shouldn't the headsman's axe for independent character cost 10 instead of 25?

**Comment by Mayegelt** [comment]
They may replace a power weapon with a headsman's act for 10 points.
So it's 10 if in Termy armour, 25 if in power/arty as a power weapon costs 15. (15 PW + 10 Heads)

**Comment by Hamemer** [comment]
Derp on my side, of course! Thanks mate.
