### ISSUE TITLE
RoW Alpha Legion - The Coils of the Hydra

### ISSUE THREAD

**Issue by Benymely** [BSData/horus-heresy#1798]
Hello,
I have a little problem with the RoW "The Coils of the Hydra" for the Alpha Legion Army.
Indeed, I think that each unit of the other legions that I put in this RoW keeps its own options available in its profile (Example: the Blade of Perdition for the Blood Angel Crimson Exemplar).
In addition I think that his units recover the options for Legion Astartes (Alpha Legion) units such as the Power dagger for the characters

Please correct this or tell me if I'm wrong.

**Comment by Mayegelt** [comment]
Yep you are right. Do you know which ones are missing? Most should be working correctly. But as a non AL player I'm not sure which ones are missing.
Obviously they don't get the legion options for that legion if they are not included on the profile page.

**Comment by Benymely** [comment]
yes, I made the checklist of what is missing

**Comment by Mayegelt** [comment]
Cool. If you can post it on here I will get to fixing it

**Comment by Benymely** [comment]
Hello
The fist 9 Legions :

**Dark Angels**
- Inner Cercle Knights Cenobium
Order Preceptor : Miss Power dagger

**Emperor Children**
- Phoenix Terminator Squad
Dedicated Transport : Delete Land Raider Proteus and Anvilus Dreadclaw
Champion : Miss Power dagger
- Palatine Blade
Miss Phoenix power lance for everyone
- Kakophoni
Miss plasma pistol for the Orchestrator

**Iron Warrior**
- Tyrant Siege Terminator
Dedicated Transport : Delete Ancilus Dreadclaw
Siege Master : Omniscope isn't an option
- Iron Circle Domitar : Detele the choice - Indeed the unit must have the Legion Astartes rules

**White Scars**
- Kyzagan Speeder : Delete the choice - Indeed the unit must have the Legion Astartes rules

**Space Wolves**
- Deathworn : Miss Frost blade option
- Varagyr Terminator : Problem with the frost weapon and miss the second frost weapon
Teghn Terminator : Miss Power dagger
- Grey Slayer
Huscarl : Miss Power dagger

**Imperial Fist**
- Phalanx Warden
Sergeant : Miss Solarite power fist

**Blood Angel**
- Downbreaker Cohorte
Champion : Miss Power dagger
- Crimson Paladin
Miss Iliastus Assault Cannon
Exemplar : Miss Blade of perdition

**Comment by Mayegelt** [comment]
Ok I think I have just done all those first ones.
Looks like many units that shouldn't have were given the option for Anvilus Drop pods

As per the "Remove due to needing to be LA (__), I can't see that in the rules. It is just any LA (__) is replaced with LA (AL)

**Comment by Mayegelt** [comment]
Issues here should have be getting fixed with new pull today.
Will leave this open in case of others

**Comment by Mayegelt** [comment]
@Benymely any more?

**Comment by Benymely** [comment]
The end for tonight.
And you have right. Not deleted the Speeder and the Domitar.

**Comment by Mayegelt** [comment]
@Benymely 
"The Rewards of Treason: An Alpha Legion force whose primary detachment is using this Rite of War may select a single Legion specific unit normally allowed only to another Space Marine Legion (note this does not include independent characters or unique units) as an Elites choice on their Force Organisation chart. This unit has the equipment and special rules that they would normally, however they have the Legiones Astartes (Alpha Legion) special rule where this is relevant, not the Legiones Astartes special rule of their parent Legion."

Doesn't seem to say it has to be a Legion Astartes. But just a legion specific unit. Though if it is LA, then the LA switches to LA Alpha Legion from which ever it came from.
I guess they can steal a flyer or steal/reprogram a robot.

**Comment by Benymely** [comment]
Yes, I'm ALPHARIUS lol

The end : 


**Iron Hands**
- Medusan Immortal
Dedicated Transport : Delete Anvilus Dreadclaw

**Word Eaters**
- Red Butcher
Dedicated Transport : Delete Anvilus Dreadclaw
- Rampager
Miss Meteor Hammer and Excoriator for everyone

**Ultramarine**
- Fulmentarus
Dedicated Transport : Delete Anvilus Dreadclaw and add Spartan

**Death Guard**
- Grave Warden
Dedicated Transport : Delete Anvilus Dreadclaw

**Thousand Sons**
- Sekhmet
Dedicated Transport : Add Spartan
Inceptor : add Dagger
- Khenetai
Blademaster : add Dagger
- Amitarra
Fate : add Dagger

**Son of Horus**
- Reaver
Chieftain : add dagger

Salamander
- Firedrake
Dedicated Transport : Delete Anvilus Dreadclaw

Raven Guard
- Mor Deythan
Dedicated Transport : Delete Anvilus Dreadclaw and add Darkwing
- Dark Fury
Chooser of the Slain : add dagger

And its all
