### ISSUE TITLE
[Anon] Bug report: (HH) Craftworld Eldar - Asuryani Army List.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1800]
**File:** (HH) Craftworld Eldar - Asuryani Army List.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Some vehicles, such as the Vyper and Falcon, produce an error when both the turret and hull mounts have a Shuriken Cannon. The rules do not impose such a limit.

**Comment by Mayegelt** [comment]
Interesting. Haven't had a bug for them for ages. Probably popped up during the same time as all the melta bomb sergeant/squad issues arose.

**Comment by Mayegelt** [comment]
Fixed. Will be pushed soon.
