### ISSUE TITLE
Further mechanicum issues

### ISSUE THREAD

**Issue by Frobbe** [BSData/horus-heresy#1801]
mostly nitpicky stuff this time around!

Magos Reductor/Archmagos Reductor
Phosphes bombs are Assualt, should be Assault 
Missing Poisoned (3+) 
Lingering Death Description missing
> When a Blast weapon with this rule is used, after the attack is resolved leave the Blast marker in play for the rest of the game and mark it with a counter of some kind. This area is now treated as dangerous terrain for all models with a Toughness value and open-topped vehicles. 

**Scyllax Guardian-Automata**

Mechadendrite Combat Array (Dismemberment) under Type it says Unwieldly, should be Unwieldy
Giving Enhanced array to Scyllax should remove their scyllax bolter from their profile. this currently does not happen

**Thallax**
change "trust move" to Thrust move
Change "skybourne" to Skyborne

**Comment by Mayegelt** [comment]
No worries about being not picy. There are a lot of errors like that just down to typing or copy paste from OCR having issues
