### ISSUE TITLE
Unbroken Vow Hasl Errors

### ISSUE THREAD

**Issue by TheRavingRaven** [BSData/horus-heresy#1805]
The rules and limitations text for The Unbroken Vow is still incomplete it should read as follows.
Effects.
Hammer of Caliban: Legion Veteran Squads and Legion Terminator Squads may be selected as Troops choices in this detachment.
Marshal of the Unbroken Vow: Independent Character models with the Legiones Astartes (Dark Angels) and Scion of the Deathwing special rules in this detachment gain +1 Attack while within 12" of an objective.
Death is not the End: Any unit with the Legiones Astartes (Dark Angels) special rule that includes at least one model with the Scion of the Deathwing special rule gains the Feel No Pain (6+) special rule while it has at least one model within 6" of any objective. If it already has the Feel No Pain special rule then the value of the rule is increased by one step (from 6+ to 5+, for example)

**Comment by TheRavingRaven** [comment]
Limitations
All compulsory Troops must be filled by Legion Veteran Tactical Squads or Legion Terminator Squads.
All compulsory Troops choices with the Legiones Astartes (Dark Angels) special rule in this detachment must include at least one model with the Scion of the Deathwing. 
After deployment has been completed, the Dark Angels player must place a single additional objective at the centre of the table or as close as possible. At the end of any game turn in which the Dark Angels player does not control this objective with a unit that includes at least one model with the Scion of the Deathwing special rule, the opposing player gains +1 victory point, or +3 Victory points if the opposing player controls it.
The Army's Warlord must have the Scion of the Deathwing special rule or be Lion El'Jonson
The army may not include an Allied Detachment.
No unit from a detachment using this Rite of War can be joined by Independent Characters that are not part of this detachment.

**Comment by Mayegelt** [comment]
Cool. Will get on this. Didn't realise it wasn't working. Likely chance is it was put in, then ended up getting lost when needing to be redone.

**Comment by capitaladot** [comment]
He is just complaining about the rules text.

**Comment by Mayegelt** [comment]
Looks like most of them have same issue or similar.
Also Storm of War as well needs completion. Currently it has a rule called "the storm of war to do"
Unless you do it later today @capitaladot I'll try to do it when my eye is a bit better. Hopefully tomorrow or by weekend.

**Comment by Mayegelt** [comment]
Done, and will be uploaded and pushed momentarily. Hopefully no spelling errors, but I'm sure if they exist they will be pointed out if needed.
