### ISSUE TITLE
Heavy Support Slots for Hammer of Olympia Rite of War.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#181]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 1.15.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Under rites of war:hammer of Olympia, the heavy support allowance should be 4 but is listed as still only 3.

**Comment by capitaladot** [comment]
Presently unfixable due to immutable FoC in BattleScribe and data file maintainer decision not to implement alternate FoCs for Rites of War that differ in slot numbers from the Age of Darkness FoC.

**Comment by Millicant** [comment]
As capitaldot mentioned, this is currently unsupported.  If it ever becomes available, we will implement it!
