### ISSUE TITLE
Mechanicum issues

### ISSUE THREAD

**Issue by Frobbe** [BSData/horus-heresy#1822]
I've got new models for my army, therefore i'm finding new issues!

Karacnos Assault Tank

Change:
Lighting-blaster sentinels to "Lightning-blast Sentinels"
Change description to the below as the current is a bit confusing 
> Each lightning blaster sentinel may target units separately from the Karacnos' main weapon. If reduced to firing Snap Shots, it may do so at BS 2

Triaros Conveyor

Maulter bolt cannon is missing "twin linked" in the weapon profile, but the rule does appear in the "rules selection" bit. 

FAQ Changes: 

Flare shield mentions the Vultarax. this unit no longer has that option, and i believe no other monstrous creatures do? so that bit could be removed :)

spelling errors: 

change "karacnos motar battery" to Karacnos Mortar battery
change "lightning blaster sentinal" to Lightning-blaster sentinel

**Comment by Mayegelt** [comment]
Thanks, will try to do them tonight.

**Comment by Mayegelt** [comment]
Took a little while but managed to sort those bits out.
Only one I didn't do is slim down the description on the Lightning-Blaster Sentinels. We tend to use the rules as written in the book, so it is still going to be them.
