### ISSUE TITLE
HH V1 - Fan Made list additions - (Optional)

### ISSUE THREAD

**Issue by Tomakokamikaze** [BSData/horus-heresy#1830]
Would be nice to add the following list options from Unity B4 Heresy

http://unityb4heresy.blogspot.com/2020/08/the-great-crusade-enemies-of-emperor.html

**Comment by Mayegelt** [comment]
Might be something I get on to. Had some RL issues recently. Need to finish off the to-do lists and go back and fix the the Mounival stuff to latest release version. And add the Solar Aux and Imperial Militia stuff in. Lots to do. So little eyesight to do it with...

**Comment by Tomakokamikaze** [comment]
Also adding Solar Auxilia and Mechanicum to Mournival rules, since we are doing them

**Comment by LachrimallusExterminator** [comment]
> Might be something I get on to. Had some RL issues recently. Need to finish off the to-do lists and go back and fix the the Mounival stuff to latest release version. And add the Solar Aux and Imperial Militia stuff in. Lots to do. So little eyesight to do it with...

😔

**Comment by Mayegelt** [comment]
Closing this as 2.0 seems to be the thing, and time wont be dedicated to more fan stuff for 1.0.
