### ISSUE TITLE
Bug Report: Contemptor Dreadnought

### ISSUE THREAD

**Issue by PatentedGraph53** [BSData/horus-heresy#1834]
For the list of weapons to replace the Dreadnought Close Combat Weapon and/or Twin-Linked Heavy Bolter seem to be missing one option each.
The Dreadnought Close Combat Weapon can be replaced with a Dreadnought Chainfist, while the other can not, and the Twin-Linked Heavy Bolter can be replaced with a Heavy Conversion Beamer, while the other can not. 
I belief that both default weapons are meant to be able to be replaced with Dreadnought Chainfists, but I could be wrong, but Im pretty sure thats meant to be an option.

**Comment by Mayegelt** [comment]
The entry is correct. The original heavy bolter can be exchanged for a conversion beamer but not be exchanged for a chain fist
The combat weapon is able to be exchanged for a chainfist and unable to be exchanged for a conversion beamer.

Basically no dual Chainfists or conversion beamer.
