### ISSUE TITLE
[Anon] Bug report: (HH) Mornival Units.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1853]
**File:** (HH) Mornival Units.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The Gunnery Centurion selection under HQ automatically equips metor hammer cadre weapon without an option to unselect it. This happens regardless of legion selection

**Comment by Mayegelt** [comment]
Strange bug. Seems it had auto selected by default, but could be removed. Either way I've just fixed it.
Hopefully should over the next week or so be updating the Mournival stuff so long as I'm feeling well.
