### ISSUE TITLE
Mournival Units World Eater Triarrii

### ISSUE THREAD

**Issue by twizted86** [BSData/horus-heresy#1854]
World Eaters Triarii should also have the option to take a Land Raider Phobos as a dedicated transport under 10 models.  
Also per the FAQ they should also have the option to take a power weapon per every 5 models for 10 points.
Thanks

**Comment by Mayegelt** [comment]
Hi ya. I'm going through (though it is slow going) to get the Mournival stuff up to date from 3.3 up to 3.5.
I'm also playing around as it seems there are confirmed new rules and errata, and experimental ones. So I'm putting in an additional tickbox for the experimental stuff.
#1682 clicking the hashtag here will take you to the thread. Though posting things as new issues is better for me, as I don't seem to always get updates to the threads.

**Comment by Mayegelt** [comment]
This is now up on my fork, hopefully will have all the other bits done soon
