### ISSUE TITLE
[Anon] Bug report: (HH) Craftworld Eldar - Asuryani Army List.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1858]
**File:** (HH) Craftworld Eldar - Asuryani Army List.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Please add the alternative Force Organisation Charts such as Onslaught, Leviathan etc. I know this is not in the rules as written, but it would allow a lot more flexibility. Thank you.

**Comment by Mayegelt** [comment]
That should be doable... ish...
I think there may be issues with adding some of them. Leviathan I can see would defo be an issue, as the force structure requires a leader and such.

I've added them all now. BUT I expect that there may be issues with it, that would take me ages to work out, so would need external testing and bug reporting.

**Comment by CodicierDio** [comment]
Cool, thanks.
