### ISSUE TITLE
Mechanicum: Taghmata list missing Ordinatus Aktaeus unit entry

### ISSUE THREAD

**Issue by Mystic1027** [BSData/horus-heresy#1860]
Mechanicum: Taghmata army list is missing Ordinatus Aktaeus unit entry under Lord of War (currently only available as pdf download from forgeworld website - https://www.forgeworld.co.uk/resources/fw_site/fw_pdfs/Horus_Heresy/Ordinatus_Aktaeus.pdf)

**Comment by Mayegelt** [comment]
I thought this had been added in already. I will have a looky in a bit. Just put out a major patch. Will likely have a few days off, as I think I've spent about 12hrs+ in the couple of weeks battlescribbling to do a whole bunch of fixes and updates.

**Comment by Mayegelt** [comment]
Managed to get it done and just pushed it. Hopefully should be live as soon as Appspot picks it up.
