### ISSUE TITLE
Necron Fan List - Nodal Command too many fast attack options

### ISSUE THREAD

**Issue by mholmberg153** [BSData/horus-heresy#1862]
When building a list with the nodal command force org, regardless of line formations added any fast attack options are throwing a validation error saying there is a maximum of 0. From my reading of the list each line formation should be unlocking a heavy support and fast attack.

Steps to Reproduce:
Create a Necron list using the nodal command force org
Add a line formation with a lord and a troop choice
Add a fast attack

Expected:
No Validation Error

Actual: 
"Necron Army List (Fanmade) v6 (Nodel Command Force Organization Chart) has 1 too many selections from Fast Attack (maximum 0)

**Comment by Mayegelt** [comment]
Thanks for the report. Worked out what's going on here. Between version I originally encoded and the current (though still old) the ability to take fast attacks was limited to having a Reserve Command detachment on there. When it was updated, I updated the Force org allowances, but forgot to remove all the hidden if entries that went along with it.

**Comment by Mayegelt** [comment]
Managed to get it done and just pushed it. Hopefully should be live as soon as Appspot picks it up.
