### ISSUE TITLE
Download issue.

### ISSUE THREAD

**Issue by mikefellhanded** [BSData/horus-heresy#1876]
Isn't allowing downloads of the Heresy Repository. It keep showing the error page after selecting.

**Comment by capitaladot** [comment]
Thanks @mikefellhanded . The thing that sends the repos to BattleScribe from Github is borked.
Check out these alternate instructions:
https://www.facebook.com/photo/?fbid=1371616946507432&set=pcb.3749031941852313&__cft__[0]=AZWzlmZX06GMTinPvc4gBHrsp1Mm4K6_ajClN-o4Y-_U1JP8KEwYLcZ08zwpK1uOjXiBHCdTH_RUb2oMaR2am18HzJspbhEVrWQik6H0pggWQmXOKKX-ErVe4H2Or8XiOpUZi5sXa5VLfV8xwJBft4w57pu6cQBUs05bWy-SRE3YoHsbdQTBaWLWbzp7LZUwFBU&__tn__=*bH-Rhttps://www.facebook.com/photo/?fbid=1371616976507429&set=pcb.3749031941852313&__cft__[0]=AZWzlmZX06GMTinPvc4gBHrsp1Mm4K6_ajClN-o4Y-_U1JP8KEwYLcZ08zwpK1uOjXiBHCdTH_RUb2oMaR2am18HzJspbhEVrWQik6Hhttps://www.facebook.com/photo/?https://www.facebook.com/photo/?fbid=1371617059840754&set=pcb.3749031941852313&__cft__[0]=AZWzlmZhttps://scontent.fdet1-2.fna.fbcdn.net/v/t1.0-9/144744259_1371617106507416_983165675929455941_n.jpg?_nc_cat=109&ccb=2&_nc_sid=b9115d&_nc_ohc=wlDEPvJj_y0AX87eiHl&_nc_ht=scontent.fdet1-2.fna&oh=1c76c97489ecf56ffb241cbca6fa27fa&oe=603BC032X06GMTinPvc4gBHrsp1Mm4K6_ajClN-o4Y-_U1JP8KEwYLcZ08zwpK1uOjXiBHCdTH_RUb2oMaR2am18HzJspbhEVrWQik6H0pggWQmXOKKX-ErVe4H2Or8XiOpUZi5sXa5VLfV8xwJBft4w57pu6cQBUs05bWy-SRE3YoHsbdQTBaWLWbzp7LZUwFBU&__tn__=*bH-Rfbid=1371617016507425&set=pcb.3749031941852313&__cft__[0]=AZhttps://www.facebook.com/photo/?fbid=1371617016507425&set=pcb.3749031941852313&__cft__[0]=AZWzlmZX06GMTinPvc4gBHrsp1Mm4K6_ajClN-o4Y-_U1JP8KEwYLcZ08zwpK1uOjXiBHCdTH_RUb2oMaR2am18HzJspbhEVrWQik6H0pggWQmXOKKX-ErVe4H2Or8XiOpUZi5sXa5VLfV8xwJBft4w57pu6cQBUs05bWy-SRE3YoHsbdQTBaWLWbzp7LZUwFBU&__tn__=*bH-RWzlmZX06GMTinPvc4gBHrsp1Mm4K6_ajClN-o4Y-_U1JP8KEwYLcZ08zwpK1uOjXiBHCdTH_RUb2oMaR2am18HzJspbhEVrWQik6H0pggWQmXOKKX-ErVe4H2Or8XiOpUZi5sXa5VLfV8xwJBft4w57pu6cQBUs05bWy-SRE3YoHsbdQTBaWLWbzp7LZUwFBU&__tn__=*bH-R0pggWQmXOKKX-ErVe4H2Or8XiOpUZi5sXa5VLfV8xwJBft4w57pu6cQBUs05bWy-SRE3YoHsbdQTBaWLWbzp7LZUwFBU&__tn__=*bH-Rhttps://scontent.fdet1-2.fna.fbcdn.net/v/t1.0-9/144744259_1371617106507416_983165675929455941_n.jpg?_nc_cat=109&ccb=2&_nc_sid=b9115d&_nc_ohc=wlDEPvJj_y0AX87eiHl&_nc_ht=scontent.fdet1-2.fna&oh=1c76c97489ecf56ffb241cbca6fa27fa&oe=603BC032https://scontent.fdet1-2.fna.fbcdn.net/v/t1.0-9/145343991_1371617143174079_8103144948382614739_n.jpg?_nc_cat=111&ccb=2&_nc_sid=b9115d&_nc_ohc=Bw5EJLGqMZgAX_KRfHF&_nc_ht=scontent.fdet1-2.fna&oh=6836bbbcfda3ba18e90ec8cfe49488a3&oe=603E7D85https://scontent.fdet1-1.fna.fbcdn.net/v/t1.0-9/145054798_1371617183174075_5769816195702520978_n.jpg?_nc_cat=101&ccb=2&_nc_sid=b9115d&_nc_ohc=nFK7X7_nB9IAX9QZOBb&_nc_ht=scontent.fdet1-1.fna&oh=2ddc3203e3891f679027997d61778fb2&oe=603B6C9Ahttps://scontent.fdet1-2.fna.fbcdn.net/v/t1.0-9/145010693_1371676846501442_1651803286225107865_o.jpg?_nc_cat=108&ccb=2&_nc_sid=b9115d&_nc_ohc=ZHjfh35uvRMAX-Q5QkU&_nc_ht=scontent.fdet1-2.fna&oh=26fcf3814a068288ef28de8abb17fb3a&oe=603E264A

**Comment by Mayegelt** [comment]
I've put the guide up and pinned it to the top, so hopefully people will see it and it will work for them, rather than a redirect.
My god that is a hell of a long link though isn't it.

**Comment by amis92** [comment]
You *could* upload pictures directly here though ;) And links can also be hidden, watch this!

**Comment by mikefellhanded** [comment]
Perfect. Thanks Maye. Got it working. Cheers all for the replies.
