### ISSUE TITLE
Data update issue 

### ISSUE THREAD

**Issue by Tntm1ner** [BSData/horus-heresy#1878]
Hi everytime I try to update my data i get these two errors
1)https://battlescribedata.appspot.com/repos/horus-heresy
2)https://battlescribedata.appspot.com/repos/horus-heresy/index.bsi
This has been going on for about two or three weeks now with no noticeable bugs or changes while using the data

**Comment by capitaladot** [comment]
Check this out for a workaround. https://github.com/BSData/horus-heresy/issues/1877
