### ISSUE TITLE
The Black Reaving wants three masters of signal

### ISSUE THREAD

**Issue by Tntm1ner** [BSData/horus-heresy#1880]
When I use the black reaving rite of war I get three errors that I need a master of signal if I buy on one dissappears but the other two remain

**Comment by capitaladot** [comment]
Is it possible some say Master of the Legion? You can only have one such per 1000 points.

**Comment by capitaladot** [comment]
Nope, totally checks out; totally broken.

**Comment by Mayegelt** [comment]
This will be the same issue as #1865 then by the sounds of it. I will be able to fix in the same way.

**Comment by Mayegelt** [comment]
Same issue was affecting Logos Lectora. Fixed but just need to push
