### ISSUE TITLE
Justearin terminators weapons

### ISSUE THREAD

**Issue by Tntm1ner** [BSData/horus-heresy#1881]
When I buy justearin terminators in either elite or troop slot and give them anything else than a combi-bolter or combi-weapon option like a pair of lightning claws or a heavy weapon it say i need more selections from exchange combi-bolter if I buy more combi-bolter it obviously gives me the error that I have too many weapon selections

**Comment by capitaladot** [comment]
It works for me if I just type a 5 in the Combi-Bolter space.

**Comment by Mayegelt** [comment]
Reopening this one. Needs a fix. Looks like the issue it's it's not counting correctly. Will try to push out a fix today.

**Comment by Mayegelt** [comment]
Fixed but just need to push
