### ISSUE TITLE
Ahriman's Cabal

### ISSUE THREAD

**Issue by TroyNH** [BSData/horus-heresy#1883]
I've noticed that since the changes to the way command squads are handled in Battlescribe, a squad taken for Ahriman can't be given their Psychic Mastery 2 upgrade (locked to Corvidae). It is also possible that I'm just really dumb and can't find the option.

**Comment by Mayegelt** [comment]
Interesting. I'll be able to solve that one. Just requires me to add something to Ahrimans entry to flag to them to be able to take it. Might even be able to get that done tonight.

**Comment by Mayegelt** [comment]
Fix put in latest pull request. Just needs testing and approval to pull and release.
