### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Antyctus** [BSData/horus-heresy#1887]
Hello all, I'm on the Discord and wanted to contribute.

**Comment by Mayegelt** [comment]
Great. Any particular part you want to start on?
Basic advice is download the latest files from the code section on here. Have a play around with one of them to add something. See if it works then upload it as a branch. Then flag myself & capitaladot to review it.

**Comment by Antyctus** [comment]
@Mayegelt I would like to tinker a bit and see if there are any rules updating required. There are some unusual restrictions in how armies are built I've noticed in BattleScribe (also could be due to my unfamiliarity with the rules) that I'd like to update. Looking forward to contributing!

**Comment by Mayegelt** [comment]
#863 has a load of things that were brought up a long time ago and need checking in regards to that.
I've been slowly making my way through it. But can always do with a 3rd pair of eyes.

**Comment by capitaladot** [comment]
Probably no need for a join request at this time. Issues can be filed
without it and unfamiliarity with both git and the rules have to be seen as
crucial limiting factors.
