### ISSUE TITLE
Missing option for Reaver Chieftains to have a Hand Flamer

### ISSUE THREAD

**Issue by CodicierDio** [BSData/horus-heresy#1890]
Sons of Horus Reaver Chieftains should be able to take a Hand Flamer for 5 points. Using 2.03.15 on iOS without Drop Box.

**Comment by Mayegelt** [comment]
I'll get on it.
Still feeling sick today. Hopefully should feel better soon, then get a hole bunch of stuff done.

**Comment by CodicierDio** [comment]
Whenever you’re ready. No rush.

**Comment by CodicierDio** [comment]
How are you feeling?

**Comment by Mayegelt** [comment]
Still a bit sick, but recovering. Don't worry, not Covid or anything. Had my vaccination for that last week. Just picked got other stuff causing me to feel unwell.

**Comment by Mayegelt** [comment]
Looks like for some reason the link for the hand flamer was linked to the blood angels only one. Not sure why. But been corrected. Should be in the next push.
