### ISSUE TITLE
Cannot add Bikes to Command Squads

### ISSUE THREAD

**Issue by eaxexe** [BSData/horus-heresy#1893]
Data Version: v14.240 (From the BSData repository)
Platform: Laptop (macOS)
Issue:
There's no option to add Bikes (or Jump Packs) to Command Squads, under the Bodyguard section.
The only option I have for Mobility, is "On Foot"

**Comment by Mayegelt** [comment]
The warlord (who is the only one who can take a command squad) must be
equipped with jump pack for the command squad to have them. Same goes for
bikes, jetbikes and terminator armour.

**Comment by Mayegelt** [comment]
The warlord (who is the only one who can take a command squad) must be equipped with jump pack for the command squad to have them. Same goes for bikes, jetbikes and terminator armour.

**Comment by eaxexe** [comment]
@Mayegelt Oh! That explains it thanks! 
It doesn't look like it's possible for me to set Warlord on one of my HQ's though.
I suspect it might be because I have three Praetors? (This is a list of my collection, hence the amount of Praetors)

**Comment by Mayegelt** [comment]
You should be able to set 1 character to be your warlord unless you container primarch in your list.
automatically gives them the warlord tag. Or a herald or Delegatus who also must be the warlord if included.

**Comment by eaxexe** [comment]
@Mayegelt That was the issue! Thanks very much! Sorry for disturbing with a non-issue!

**Comment by Mayegelt** [comment]
No worries
![Nbc_the_more_you_know](https://user-images.githubusercontent.com/20280410/111308507-ae05fb80-8652-11eb-8085-859e95c1579e.jpg)
