### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by ardliath** [BSData/horus-heresy#1898]
When I try to download in BattleScribe For iPhone I get a 500 error. HH data file only, others work fine

**Comment by Mayegelt** [comment]
Hi ya please check the pinned post at the top. Or click this link to it. That should resolve the issue.

https://github.com/BSData/horus-heresy/issues/1877

Please post if it works or doesn't work. Then I can either advise or remove the issue

**Comment by ardliath** [comment]
Doh!

I’m sorry - thank you!
