### ISSUE TITLE
Word Bearers Legion restriction on HQ not validated

### ISSUE THREAD

**Issue by EricSmailys** [BSData/horus-heresy#1900]
One of the restrictions on the Word Bearers' Legionnes Astartes rule is that they must include a second mandatory HQ choice, and it must be either a Centurion or a Chaplain Consul. Currently validation does not check for this requirement.

**Comment by capitaladot** [comment]
This existed and must be a regression.

**Comment by Mayegelt** [comment]
Yeah, I think this used to be working at some point as well.
I'll prob fix in the same way as I did for Maura Skara and such. Should be an easy fix and I'll get to it.
Did a couple of bits today, but feeling unwell IRL. So will try to do when I can.

**Comment by Mayegelt** [comment]
Fixed on pull request. Hopefully will go live soon
