### ISSUE TITLE
Collection of Issues I found while making lists

### ISSUE THREAD

**Issue by Lord-Falkenrath** [BSData/horus-heresy#1902]
I apologize if some of these have been fixed in the latest update, but I have been collating these issues as I found them while making lists so that I could post them all at once instead of separately. I also do not know how to tag on Github, so I apologize if this post isn't tagged or is improperly tagged.

1) Blood Angels Legion: Chapter Master Raldoran counts as 2 Master of the Legion, should only count as 1. Lacks "Compulsory HQ" tag. Cannot be selected as warlord, but should be.

2) Rite of War: Fury of the Ancients. RoW Requirements on BS are 3 Forge Lords and 3 Primus Medicae, should only be 1 of each.

3) Rite of War: Angels Wrath: The RoW as written has no explicit requirement for "fliers per unit of non-fliers", but BS forces one. Perhaps add a "Check infantry transport capacity manually" warning and remove the requirement?

4) Iron Hands Legion: Gorgon Terminator Hammer Bearers have no weapons options, and their weapon choice cannot be accounted for on the main unit weapon selection. Ie, in a unit of 5 terminators you can only select 4 weapon options, with no further options presented on the Hammer Bearer section.

5) Iron Hands Legion: Castrmen Orth cannot be selected as Warlord, but should be.

6) Various Primarchs: Leman Russ, Angron, and Fulgrim lack the Bulky keyword. Perturabo, Horus, and Mortarion lack the Very Bulky keyword.

7) Salamanders Legion: When selecting a heavy flamer for a weapon option on a DT for a Firedrake terminator squad, BS will flag a warning that the squad as 1 too many weapon selections, despite the weapon being on the DT and not the squad itself.

8) Iron Warriors and Imperial Fists Legions: Taking the Primarch's special DT (the Tormentor and Aetos Dios, respectively) is supposed to be possible in 3000+ point lists. However, it still flags an error "[Primarch] has 1 too many selections" unless the list is 3001+ points. This might be me misunderstanding the intent of the wording, however.

Edit: Added issue 8.

**Comment by Mayegelt** [comment]
Thanks for the list. Will try and get those fixed. I know where some will have sprung from. Others not do sure. But all should be fixable.

**Comment by Lord-Falkenrath** [comment]
Fresh update to issue 7. The too many weapons selection flag pops up when the DT takes _any_ weapon, not just a heavy flamer. Just discovered this while doing some further testing.

**Comment by Mayegelt** [comment]
Ok just had a look at these again. Should all be easy fixes. Though about point 8.
"Perturabo may take the  Tormentor  as a Dedicated Transport in any game of 3,001 points or more."
"Rogal Dorn may take the  Aetos Dios  as a Dedicated Transport in any game of 3,001 points or more."
As per the FAQ

**Comment by Lord-Falkenrath** [comment]
Must've missed the FAQ, then. My bad!

**Comment by Mayegelt** [comment]
3) Rite of War: Angels Wrath: The RoW as written has no explicit requirement for "fliers per unit of non-fliers", but BS forces one. Perhaps add a "Check infantry transport capacity manually" warning and remove the requirement?
 
Removed the requirement. I think I put it in, but then ended up not being able to complete what I was attempting to do. But then for whatever reason it didn't get removed.

4) Iron Hands Legion: Gorgon Terminator Hammer Bearers have no weapons options, and their weapon choice cannot be accounted for on the main unit weapon selection. Ie, in a unit of 5 terminators you can only select 4 weapon options, with no further options presented on the Hammer Bearer section.

The Hammer Bearer can not exchange his Thunder Hammer for any other option, as all the options require the exchange of a power axe for them.

**Comment by Mayegelt** [comment]
Fixes are on my version now. Hopefully will push out live soon. But I've done about 3hrs of stuff today. So likely chance is some point during this week or next I'll push some more stuff in from the #1903 then put up a pull request.
