### ISSUE TITLE
Talons of emperor bug

### ISSUE THREAD

**Issue by Dorn1512** [BSData/horus-heresy#1904]
Hello, i found a mistake at legio custodes sentinel guard squad.
At BS magisterium vexilla changes shield for free, but at armylist it costs 10 pts.

![sentinel](https://user-images.githubusercontent.com/82025950/113686722-3dda1b00-96d0-11eb-92a3-ff724a78fe44.JPG)

**Comment by Mayegelt** [comment]
Thanks for the catch. Will put it in the To-Do pile

**Comment by Dorn1512** [comment]
PS: and please fix a special rule of legio custodes:
Preternatural Skill: Any model with this special rule gains a bonus of +1 to their Initiative in the Assault phase if their Weapon Skill is **equal to or** greater than the majority Weapon Skill of the unit or units they are fighting. (White Dwarf)

It must be:
Preternatural Skill: Any model with this special rule gains a bonus of +1 to their Initiative in the Assault phase if their Weapon Skill is greater than the majority Weapon Skill of the unit or units they are fighting (HH8)

![Preter](https://user-images.githubusercontent.com/82025950/113687618-3404e780-96d1-11eb-9e73-31d0328dbfef.JPG)

**Comment by Mayegelt** [comment]
Looks like that was a change from book 7 to book 8 which was overlooked
