### ISSUE TITLE
Zone Mortalis unit size limit incorrectly applied for Astartes units

### ISSUE THREAD

**Issue by ntyrrell** [BSData/horus-heresy#1905]
In the Legiones Astartes army list, there is a modifier that sets the maximum number of models in a unit to 15 if the force is using one of the Zone Mortalis Force Organisations.

There are two errors here; 
1. The rules as presented in the latest PDF from FW (https://www.warhammer-community.com/wp-content/uploads/2019/11/HHZone_Mortalis_Rules.pdf) suggest that only a unit with a starting size of 15 is not allowed in ZM. This limitation comes from using the Zone Mortalis Assault Force RoW, which limits units to 15 models (Red book, p. 104).
2. The modifier is incorrect, as it does not account for the sergeant, allowing for units to have 16 models.

The fix would be to drop the maximum unit size to 14 and to apply this modifier if the Zone Mortalis Assault Force RoW.

Thank you for your time reading this issue.

**Comment by ntyrrell** [comment]
Slight amendment to my issue - upon further review, it appears that the word "starting" is referring to the start of the game, rather than the minimum starting strength of the unit.

However, the second issue is still valid, I believe.

**Comment by Mayegelt** [comment]
Thanks for the report. I'll get on it soon.

**Comment by Mayegelt** [comment]
Ok corrected Assault, Breacher, Medusan Immortals, Phalanx Warders, Tactical.
Not sure if there are any others.
