### ISSUE TITLE
(Mournival) Night Lords Terror Squad points incorrect.

### ISSUE THREAD

**Issue by MCStanden** [BSData/horus-heresy#1906]
Terror Squads are supposed to have a starting cost of 125 points, the Mournival list has them at 100 points instead. I believe it's not counting the points for the Headsman.

**Comment by Mayegelt** [comment]
@MCStanden can you link the source of the points reduction. I had a quick look in the Mournival Events FAQ and Experimental Errata v3.6 and couldn't see a points reduction.

**Comment by MCStanden** [comment]
@Mayegelt Here are the official points from Book 9. There wasn't any points reduction in the Mournival documents, that's the issue. The Mournival data has incorrectly given them a 25 point discount at their starting size.
![Terror Error](https://user-images.githubusercontent.com/47582303/116378539-93c85b80-a855-11eb-90d6-5418d323a0c0.png)

**Comment by Mayegelt** [comment]
Ahhh, kk. Hopefully should be resolved soon. Did a load of the 3.3 -> 3.6 upgrades about a month ago. They still haven't gone live. Though should be soon.

**Comment by MCStanden** [comment]
@Mayegelt I've just noticed another points discrepancy; may I also list it here, or should I open it as a separate issue?

**Comment by Mayegelt** [comment]
Post here will be fine

**Comment by MCStanden** [comment]
The data version, or the Mournival document version? My data v31 and the document is 3.6.

As for the issue, Mournival FAQ 3.6 lists the price of the Deredeo Dreadnought's Plasma Carronade and Lascannon Batteries as 15 points each. Battlescribe shows them as 35 and 50 points instead.

**Comment by Mayegelt** [comment]
Ok cool that is taken care of. Must have been one I missed when doing the original 30+ hours for 3.2 :D
