### ISSUE TITLE
Talons of Emperor

### ISSUE THREAD

**Issue by Dorn1512** [BSData/horus-heresy#1912]
Hello, I found some mistakes.
1. Shield captain, custodian guard squad and sentinel guard squad don't have a ccw (chainsword/combat blade)
2. Contemptor-Achillus Dreadnought must have refractor field at selections (it is standard wargear).
3. Custodian guard squad, Hetaeron Guard Squad, Sentinel guard squad, Venatari Squad, Contemptor-Galatus Dreadnought and Sagittarum Guard Squad have  "refractor **Feild**" instead of "refractor **Field**" :)

**Comment by Mayegelt** [comment]
Wow those mistakes must be going back to book 7...
I'll get on them when I get home tonight

**Comment by Dorn1512** [comment]
Yeah, these mistakes from book 7, because there was no description of misercordia wargear, and at FAQ for talons it was fixed.

**Comment by Mayegelt** [comment]
Ok looks like The shield captain... all do have the CC Weapon on there already on the version I have. Its not a selectation option as its a min/max1 for the unit. 
The Achillus did also have the refractor field, but like with extra armour it didn't have a selection option, it was just included in the blub. So I've cleared that up a bit and same with Armoured Ceremites and Flare shields.
Corrected the spelling mistake.

**Comment by Dorn1512** [comment]
My bad, I didn't check before making issue.
