### ISSUE TITLE
Release Thread (OLD)

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#1913]
Data Developers - Please use this issue to push new releases if doing so via comment.

Explainer
Create an issue comment that starts with /release on the first line.
Second (non-empty) line will be used as a release title/name.
All following lines will be interpreted as a release description/body.
Description (even if empty) will always be appended with a comparison link to the previous release, unless there is no previous release.
How to
Add a comment with one of the following to push a release:

For a standard release:
given latest release v1.0,0 will create a release v1.0.1 (increases patch)

/release
PUT THE TITLE HERE (This is title of v1.0.1)

For a New Book / Big FAQ initial releases (game-wide updates):
given latest release v1.0,0 will create a release v1.1.0 (increases minor, resets patch)

/release bump=minor
PUT THE TITLE HERE (This is title of v1.1.0)

For a new game edition:
given latest release v1.0,0 will create a release v2.0.0 (increases major, resets minor and patch)

/release bump=major
PUT THE TITLE HERE (This is title of v2.0.0)

**Comment by Mayegelt** [comment]
/release
Talons of Emperor fixes
Added Achillus refractor field and extra armour as mandatory selection options (so they show up better), it was just included in the blub. So I've cleared that up a bit and same with Armoured Ceremites and Flare shields on various other vehicles.
Corrected the spelling mistake on refractor fields.

**Comment by Mayegelt** [comment]
/release
Various LoW and a bit of Mournival and Talon fixing
#1915 Coronus grav-carrier was lacking its searchlight for free, and mistakenly having to pay 1pt for it.
#1916 Fixes for Macharius tanks lacking pintle weapons in marine lists and also lacking sponsons. Some also needed the "Hull-Mounted" added to the heavy stubbers. In addition the Crassus Armoured Assault Transport had an issue with its sponsons and armour plates. and the Praetor variant lacked the ability to take as 2 in 1 LOW and its sponsons.
#1917 Fix for Mournival stuff for Alpha Legion who weren't getting their ammo as a hidden swtich had switched on at some point. Likely cause being a random issue from data editor.
#1918 Fix for Grey Slayers and Heavy Support squads who were getting Land Raiders by mistake due to logic maze error or lack of "Hidden" being applied. Assume this has been one of those random switches.

**Comment by Mayegelt** [comment]
/release
Lots of little legion fixes
#1920 Thousand sons psyker level can be bought by psykers
Excluded consul Nullificator, Esoteris and Librarian from selecting option
#1921 Space marine crew missing in sub orbital strikewing
Added the option to Sub Orbital Strike wing, however it will not apply the buff to the statline cos of the way it is formed. May look for alternative solution later such as separating the sub orbital strike win into its component parts.
#1922 Point cost of battle servitor controls missing in sub orbital strikewing 
Added repeating cost based on the number of each of the types of planes in the wing. Previously this was linked to the "model" count, however when the "units" change was put in, this inadvertently broke the math.
#1923 Legion Exoterist missing psyk-out grenades
Added Exoterist to the flag list for unhiding the grenades and added a cost of 5pts for them.
#1925 Veterans in a chosen duty rite of war do not count as minimum compulsory
Fixed a larger issue that seemed to be affecting this one. It seemed in all cases it wasn't applying the veteran unit as compulsory choice.

**Comment by Mayegelt** [comment]
/release
Delegatus LOW issues
Fixed an issue that was hiding all lords of war when a Delegatus was taken, rather than just when he was warlord.

**Comment by Mayegelt** [comment]
/release
Wizards, Relics and a Big Tank
Fixes for Esoterist options / costs. Also fixed an issue for wolf priests who were receiving errors if they tried to take anything except a bolt pistol.
Also fix for the Dominus tank.
Fixes to Relics of the dark age stuff (as if anyone uses them...)

**Comment by Mayegelt** [comment]
/release
Raltac FOC for Varangian Heresy Events 
This is a first test of the Reltac FoC added to lists. If you are a player please test it and feedback. If it works or not let me know and it can be rolled out to the other force types (like mech, solar, militia...) if successful.

To access the list type you have to like with Mournival have a new Force type. Inside there you have all the regular stuff you can choose for legions, but also the Reltac FOC chart. Only thing to watch out for is that the 350pts cap is not enabled as I don't know how to make it work without a big rewrite of the LA file that could have many knock on effects which I do not which to do.

![image](https://user-images.githubusercontent.com/20280410/121352361-afc71e80-c924-11eb-8a26-33575e6d4cbb.png)

Having the new force will also allow the addition of any units that are Varangian exclusive stuff. I would like assistance in adding such things as some of you know that I am unwell, and it would be great if the Varangian guys and gals could look after the repo themselves as they add and take away or change anything as I already have a lot on my plate when it comes to doing the normal stuff, and that I took on trying to do a fair bit of the Mournival stuff.

**Comment by Mayegelt** [comment]
/release
Opps spelling mistake...

**Comment by Mayegelt** [comment]
/release
Lets try this again. Worked my end on PC, not on phone...

**Comment by Mayegelt** [comment]
/release
Updates and fixes for rules and restrictions.
Many thanks to Tar Aziel, Jason Ortega, Olivia Marie Valmin for checking off some of these from big list for me to fix.

Hammerfall Strikeforce
The Stone Gauntlet:
FIXED - Cannot take more Elites and Fast Attack choices in total than Troop choices

Sons of Horus
The Black Reaving
FIXED - Must take more Fast attack then Heavy Support
FIXED - +1 compulsory troop (3+ instead of 2+)

Salamanders
The Covenant of Fire
Hopefully fixed (might be some exceptions) - All Meltaguns, Inferno Pistols, and Multi-Meltas are Master-Crafted
Hopefully fixed (might be some exceptions) - All Vehicles have a 5++ vs Melta, Volkite, Plasma, and flamer weapons, and also against meltabombs
FIXED - All units gain Move through cover
FIXED - May not take more HS AND FA then total of Troops

**Comment by Mayegelt** [comment]
/release
A lot of RoW fixes
Angel's Wrath
Error: Jump Infantry Gains Hit & Run
FIXED by adding to category

Error: Storm Eagle and Fire Raptors gain Strafing Run
FIXED for Storm Eagle. The Fire Raptor must be a relic ROW thing as they come with it by default in current book.

Also Storm Eagles start without their Vengeance Launcher selected
FIXED all free options are now selected on both versions of the Storm Eagle

Error: No Tanks (Unless Skimmer/Flyer)
FIXED: Added the category of Non Flyer/Skimmer Vehicle to add of them (even though its tanks, it basically functions the same way, just didn't add it to the walkers and superheavy.

Pride of the Legion
Error: More Units with LA then without
FIXED: PotL Requirement Legiones Astartes added to Categories and force entries, linked to Units and Legiones Astartes

Armoured Breakthrough
Error: Tanks with 3HP or less gain Fast
FIXED: Added rule and append to profiles.

Error: No more Skimmers then Flyers then it has Tank
FIXED: Added min requirement to tanks repeating based on skimmers and flyers. Also moved skimmer category to land speeder and javelin from unit.

Primarch's Chosen
Error: More Units with LA then without
FIXED: Same as PotL fix.

Orbital Assault
Error: Terminators gain Deep Strike
FIXED: Added to Terminators Category

Brethren of Iron
Error: No more Automanta then units with LA
FIXED: Added new category

Error: No Paragon of Metal
FIXED: Changed link for Vorax

Outcast Sons
Error: More troops then Elites
FIXED: Same as some of the other ones above.

Orphans of Betrayal
Error: More Troops then HS
FIXED: Same as some of the other ones above.

Legion Recon Company
Error: must include additional compulsory legion recon squad
FIXED: Added a min requirement of 1 to the unit from Troops selection.

Error: Units limited to 15 marines at most.
FIXED: Added limitation on assault, breacher, immortals, phalanx, tacticals.

Sacrificial offering:
Error: No units with Immobile or Slow and Purposeful rules
FIXED: Added to restricted list

**Comment by Mayegelt** [comment]
/release
Fixes for DA RoW
Looks like a logic puzzle failed again. Fixed it in a new improved way! Which hopefully will last this time.

**Comment by Mayegelt** [comment]
/release
Fixes for minor issues
#1943 Bladeslaves had wrong points (seems like the plasma pistol was costing pts when it shouldn't
#1945 Mournival issue of Justarian no longer get those vigil shields
#1946 Flying Monstrous Creatures had been given rules they shouldn't have got. Looks like an issue of misallocation of rules.
#1947 Lancer and Castigator weren't showing up in legions LOW lists. They were available in the War Machine Detachment. But no reason not to be in both.

**Comment by Mayegelt** [comment]
/release
Spelling mistakes and a couple of missing options.

**Comment by Mayegelt** [comment]
/release
More old ROW fixes. Space Wolves this time.

**Comment by Mayegelt** [comment]
/release bump=minor
Overhaul 1 The Decimator of Stuff
Actually shouldn't cause any major issues and should allow the Army of Dark Compliance to work (Kinda. The Militia>LA limitation need a fix)!
Also fixed Crozius not being hidden as well.
Leviathan's also got Frag Grenades

**Comment by Mayegelt** [comment]
/release
Fix as a min/max had been reversed for traitor.
Also fix for Hussar cost.

**Comment by Mayegelt** [comment]
/release
3 units fixed
#1958 Priests of Fenris now have access to Psyarkana which was previously missed.
#1960 Nullificators are not compulsory troops unless in pride of the legion & Nullificators no longer get access to Mournival ammo without the rules being on.
#1961 Mournival Gunnery Centurion was missing Master-crafted from weapon names and stats.

**Comment by Mayegelt** [comment]
/release
Servo Arms

**Comment by Mayegelt** [comment]
/release
Couple of Mechanicum fixes for cyber

**Comment by Mayegelt** [comment]
/release
Cortex Controllers fixed. Seemed to be an issue on some lists as some of the big overhaul missed some elements of changing things over.

**Comment by Mayegelt** [comment]
/release
Bunch of fixes, mainly LoW and mini-knights
Fixed a replication of ignores cover rule in GST.
Fixed issue of multiple LoW squads costing more than they should.
Fixed issue of multiple LoW choices having either bad or no scripting enhancement to when adding space marine crew giving the bonus BS up to 4.
Added missing weapon rules to Armigars, Dominus and Moriax knights which were missing.

**Comment by Mayegelt** [comment]
/release
More missing weapon profiles

**Comment by Mayegelt** [comment]
/release bump=minor
OMG NEW UNIT AND CONTENT
So added the Huscarl unit to Imperial Fists (and those sneaky Alpha Legoinaires...
Fixed issue of Crimson Paladins Exemplar not having his W2 and Blade of Perdition costing to much for them.
Fixed Raldaron who was missing Furious Charge
Fixed issues with Dark Angels Legiones Astartes and Legion rules.
Fixed lack of weapon specific rules for the carapace mounted autocannons on 5 knights.
Made a quick fix for Solar Aux tank commander so you choose which rule he is getting.

**Comment by Mayegelt** [comment]
/release
OMG NEW UNIT AND CONTENT (fixed 1 extra issue)
So added the Huscarl unit to Imperial Fists (and those sneaky Alpha Legoinaires...
Fixed issue of Crimson Paladins Exemplar not having his W2 and Blade of Perdition costing to much for them.
Fixed Raldaron who was missing Furious Charge
Fixed issues with Dark Angels Legiones Astartes and Legion rules.
Fixed lack of weapon specific rules for the carapace mounted autocannons on 5 knights.
Made a quick fix for Solar Aux tank commander so you choose which rule he is getting.
Minor Tweek as the Huscarl Warden could in theory be the Warlord as an HQ and Compulsory HQ choice if you take them as an HQ choice rather than Bodyguard.

**Comment by Mayegelt** [comment]
/release
OMG NEW UNIT AND CONTENT part 3 Vigil Stormshield Ambiguity

**Comment by Mayegelt** [comment]
/release
OMG NEW UNIT AND CONTENT part 4 Vigil Stormshield Ambiguity fixed

**Comment by Mayegelt** [comment]
/release
More RoW fixes (Almost there now, RG, AL & Shattered to go)
Day of Revelation
ERROR: Compulsory HQ and Troops must have Jump Packs.
ERROR: Compulsory (1) Fast Attack must have Flyer or Deep Strike rule.
X Legion - Iron Hands
Company of Bitter Iron
ERROR: Detachment that gains Hatred on Legiones Astartes
XIII Legion - Ultramarines
The Logos Lectora
ERROR: Must include Vigilator
XV Legion - Thousand Sons
The Axis of Dissolution
ERROR: Troops Choices must be max size
ERROR: May not have more vehicles with the Tank or Flyer type than they have Infantry units
The Guard of the Crimson King
ERROR: Wreathed in Lightning, they Rend the Veil
ERROR: The Initiates of the Scarab (Must have Sekhmets as Compulsory Troops, Sekhmets may be taken as Optional Troops choices of desired)
ERROR: Must have Magnus, Ahriman or Praetor with psychic Mastery Level 3
ERROR: May not have more Vehicles than Legiones Astartes units.
ERROR: May not take Allied Detachments or Fortifications
XVII Legion - Word Bearers
The Dark Brethren
ERROR: all IC have Preferred Enemy (Loyalist SM)
ERROR: Max1 HS
The Last of the Serrated Sun
XVIII Legion - Salamanders
The Awakening Fire
ERROR: Infantry have Fear
ERROR: Librarian has access to Fury of the Salamander
ERROR: Must Include Chaplain
ERROR: No Vulkan
ERROR: Only one each of Jump Infantry, Jet Bikes, Skimmers, or Flyers

**Comment by Mayegelt** [comment]
/release
RoW no more
This should be the last of the RoW that are possible to fix without a major rework done.
XIX Legion - Raven Guard
Decapitation Strike
ERROR: all LA units gain Preferred Enemy (Independent Characters) FIXED 07/Sept/21 Part 2
ERROR: Max1 Consul FIXED 07/Sept/21 Part 2
XX Legion - Alpha Legion
Coils of the Hydra
ERROR: max1 Consul, except for Vigilator FIXED 07/Sept/21 Part 2
Shattered Legions
After Istvaan
ERROR: Legion Veteran Tactical Squads may be taken as non-compulsory Troops FIXED 07/Sept/21 Part 2
Hunter-Killer Mission
ERROR: Must contain units from at least two different Legions FIXED 07/Sept/21 Part 2
ERROR: Warlord must be from Emperor's Children FIXED 07/Sept/21 Part 2

**Comment by Mayegelt** [comment]
/release
Mournival 3.7 updates (Saturnine Armour anyone...)
This will likely be my last on this spree of updates unless I need to fix some random bug that comes up.

**Comment by Mayegelt** [comment]
/release
Fix for Heavy Support limit
Seems like the Heavy Support option was being taken to 1 choice for all due to a 1 being changed to a 0 between internal testing and it going on to the public
Also fixed an AV value for Aurox in Militia

**Comment by Mayegelt** [comment]
/release
More bug fixes of the long long ago
Fix for Invictarus Suzerain Squad lack of Bolt Pistols and Frag & Krak Grenades
Fix for Blackshields who shouldn't have been able to take command squads, but had been able to.
Fix for Falchion "may take any of the following" limitation was listed as Max 1 and as such couldn't select all 3 options.

**Comment by Mayegelt** [comment]
/release
Another surprise drop with Argel Tal release
Argel Tal added
Also finished adding Warlord traits

**Comment by Mayegelt** [comment]
/release
Seeker's Arrow fix
Fix for Seeker's Arrow and Jetbike Sky Hunters with Scion of Ravenwing.

**Comment by Mayegelt** [comment]
/release
Many little fixes
Fixes for some Primarch weapons.
Moving a few bits up to GST to save on duplication (like Havok launchers).
Removal of Gitter link (cos no one ever looked)
Addition of the 2 Mech units from Mournival Battle Manual V1.5. Work has also started on agents, but will be a while so not uploaded yet.

**Comment by Mayegelt** [comment]
/release
More little fixes
Moved some stuff up to GST.
Fixed some issues with Knight carapace weapons having the twin-linked rule when they shouldn't have.
Fixed a Mournival issue for destroyer company and Angels Tears
Fixed an issue for Salamanders Covenant of Fire RoW mistakenly allowing pyroclast to be compulsory troops. 
Enhancement for Spartan by preselecting its hull weapon to default, and having a min/max 1 in unit.
Fix for Lord Chaplin Rhy'tans weapon to give +2 strength, rather than just 2 strength.
A few other bits are probably in there as well.

**Comment by Mayegelt** [comment]
/release bump=minor
Atramentar added from HH - EBotAoD - The Defence of Aotha - Aegidas Lament

**Comment by Mayegelt** [comment]
/release
Domitar and Multilaser fixes
Domitar in LA didn't have the FAQ update to Grav Hammer.
Multiple Multilasers were showing the profile for Multimelta's instead of Multilasers.

**Comment by Mayegelt** [comment]
/release
More fixes from a very unwell person
#1999 Legion command squad - Jetbike points error
#2000 Heavy support squad seargent has wrong profile
#2001 Deathwing companions: Deathwing retinue has incorrect wording
#2002 Terminator deathwing companion - wargear cost error
Also added IW Dominator unit
Also fixed description of Psy-Lash on Divining Blades and Lance

**Comment by Mayegelt** [comment]
/release bump=minor
Whole lot of fixes and a WE unit
#2004 #2005 #2006 #2007 #2008 #2009 #2010

**Comment by Mayegelt** [comment]
/release
Few fixes such as Raven's Talons for Vets

**Comment by LachrimallusExterminator** [comment]
E🅱️IC

**Comment by Mayegelt** [comment]
/release
Fix for Falax Blades on Red Hands

**Comment by Mayegelt** [comment]
/release
1 RoW and some Drop pod fixes
Fixed 1 RoW issue that was causing an error as a "and child entires" box had become unticked.
Also fixed a drop pod issue that several where counting themselves as having cortex controller for no apparent reason.

**Comment by Mayegelt** [comment]
/release
fix for Contemptors attacks and a couple of other bits.

**Comment by Mayegelt** [comment]
/release bump=minor
A Gift of Stuff - Mainly Mournival Battle Manual Agents

**Comment by Mayegelt** [comment]
/release
2 new units and some QoL

**Comment by Mayegelt** [comment]
/release
Nemesis is here
Added Nemesis Destroyer squads and fixed an issue for Destroyer squads

**Comment by Mayegelt** [comment]
/release
More Loyalist stuff Fafnir and Dominion
Fafnir and Dominion added
Dark Heralds are back in Black-shields
Hetaron Guard can take a Divining Blade (who knew)
Burning Lore isn't as freely available as it was previously showing (should have only been Praetors, Chaplains, Diabolists and Centurion)

**Comment by Mayegelt** [comment]
/release
Minor Diving Blade fix for Talons and Solar

**Comment by Mayegelt** [comment]
/release
Maybe the last one for HH 1.0
