### ISSUE TITLE
Talons of Emperor coronus grav-carrier bug

### ISSUE THREAD

**Issue by Dorn1512** [BSData/horus-heresy#1915]
Good day again :)

Coronus grav-carrier have a bug - searchlight is an additional wargear and cost 1 pts, despite that it is basic wargear.
Sorry for my 3rd issue.
![coronus](https://user-images.githubusercontent.com/82025950/117818082-ef8cde80-b270-11eb-8a5e-5354abd9ce2a.JPG)

**Comment by Mayegelt** [comment]
Fixed but not gunna go live yet. Gunna try to do a few more fixes first hopefully later today or tomorrow depending how I feel.
