### ISSUE TITLE
Macharius Options Missing

### ISSUE THREAD

**Issue by LachrimallusExterminator** [BSData/horus-heresy#1916]
Most weapon options for all Macharius-pattern tanks are missing. It may also be a good idea to check other Imperial Guard-based superheavies.

**Comment by Mayegelt** [comment]
I'll take a look at some point. Hopefully soon.
Not feeling very well IRL currently. So haven't had a play around.
If you could check the other tanks to see what is missing it will make it easier

**Comment by LachrimallusExterminator** [comment]
Okay

**Comment by LachrimallusExterminator** [comment]
Crassus Armoured Assault Transport:
It should be possible to upgrade the front sponsons while still replacing the side sponsons with armour plates. As it is, upgrading the side armour prevents other selections. Also, sponsons should be replaced individually, not in pairs.

Praetor Armoured Assault Launcher:
The sponson upgrades and profiles are missing. Also, it should be possible to take 2 of these vehicles in a Warmachine Squadron.

The only Open-topped Macharius is the Omega. All types of Macharius or Crassus hull vehicles can take a pintle-mounted heavy stubber or storm bolter according to the IA book. The storm bolter option could be replaced by a combi-bolter. It should be possible to take a pintle weapon and an HKM. All Macharius tanks have a hull-mounted twin-linked heavy stubber.

**Comment by Mayegelt** [comment]
All should be done now when I put this one up live.
The only exception to what you put that I could see is that the Omega doesn't get the Hull-Mounted Twin-Linked Heavy Stubber.
I've also left the weapons as Stormbolters, as it has had to be in the other ones that have it as a not updated to 30K vehicle (I think one of the baneblade types has it).
