### ISSUE TITLE
Missing special ammo for Alpha Legion and weapon option for Jetbikes in Mournival rules

### ISSUE THREAD

**Issue by Yekeran** [BSData/horus-heresy#1917]
In Battlescribe Alpha legion infantry such as tacticals cant take their special ammo banestrike bolts.

Sky stalkers on Corvex bikes also dont have the multi melta option in their entry.

Just 2 small bugs i found in the file

**Comment by Mayegelt** [comment]
Ok the Banestrike seems to have been a hidden modifier at some point got reversed (love the battlescribe data editor...)
Also added the Multi Melta. Not sure if they could always take it or maybe an update from 3.2 when I first started it to 3.3 or 3.6.
