### ISSUE TITLE
Land Raider option for certain infantry.

### ISSUE THREAD

**Issue by Yekeran** [BSData/horus-heresy#1918]
Ive noticed that Legion heavy support squads and Space Wolf grey slayer squads can pick a Phobos LR as their DT but they are not supposed to have access to this. I dont know if other squads also have this glitch or not, these are just the 2 entries I found have the issue.

**Comment by Mayegelt** [comment]
Fixed but not live yet. Hopefully will be later today.
Looks like at some point a flag had reversed in 1 case and a logic maze had an OR rather than AND in 1 post.
