### ISSUE TITLE
Relics from the Dank age of Technology

### ISSUE THREAD

**Issue by Tomakokamikaze** [BSData/horus-heresy#1929]
Solar Auxilia/ Imperialis Auxilia -> Apex Digital Weapon, Cloaking Array, Combat Augment Array, Metaphasic Reader, Phase Walker, Void Shield Harness and Warp Shunt Field  are blank

Legiones Astartes ->
The Parthinian Serpent - its rules for Skyfire, Precision Shots, Interceptor, Pinning, Preternatural Targeting are not described
haven't checked every entry but this does seem to happen to other legions relics too, the rule is named, but not described.

**Comment by Mayegelt** [comment]
No doubt this is old code stuff. I'll look into it when I can.

**Comment by Mayegelt** [comment]
Looks like having a search through someone asked for an update to the relics and for whatever reason the Parthinian Serpent was forgotten. The Solar/Imperial Militia one look like laziness on my part when I updated the LA & Mech catalogues I didn't then also update those 2.
