### ISSUE TITLE
Dominus Armoured Siege Bombard.

### ISSUE THREAD

**Issue by LachrimallusExterminator** [BSData/horus-heresy#1932]
The sponson options for the other Crassus tanks and the Macharius variants are fixed, but this one does not allow you to have more than one of the same sponson weapon.

**Comment by Mayegelt** [comment]
Fixed the Dominus. Hadn't put the new sponson thing in there as I forgot it existed as its not in apoc, its in IA 1 Second Edition as the latest version.
This also means that its hunter killer costs 10pts and it can get a dozer blade as well (the Crassus and Praetor used to be able to, but removed in IA Apoc).

**Comment by LachrimallusExterminator** [comment]
Thanks. I thought it might have been in that book, but thanks for confirming it. I was never quite sure which order the books were in.
