### ISSUE TITLE
Demons of the Ruinstorm - Flying Monstrous Creatures

### ISSUE THREAD

**Issue by Mystic1027** [BSData/horus-heresy#1946]
Flying Monstrous Creature category entry:

Erroneously contains:
Fearless
Feel No Pain
Strikedown

Missing:
Jink

Citation - AoD Rulebook pages 67-69 (Monstrous Creatures, Monstrous Flying Creatures)

**Comment by Mayegelt** [comment]
That's a bit of a strange one. Seems like at some point there has been a movement of rules in which its eaten the rules for Gargantuan Flying Monsters. Should be fixed in next push.
