### ISSUE TITLE
Space wolves FAQ

### ISSUE THREAD

**Issue by VoxVulpus** [BSData/horus-heresy#1957]
The SW FAQ from 2019 made it so that they have to take 2 HQ units per 1K instead of 1HQ per 1K.

Battlescribe keeps giving me an error.

**Comment by Mayegelt** [comment]
Working fine my end. Remember it is only going to give you a warning on it per 1000pts in the army. So if you are going to play a 3k game but only take 2999 PTS you are in the 2000-2999 bracket of 3 hqs required.
The wording you used isn't exactly what the FAQ says. It is at least 1hq per 1000pts or part of. So 1 8n 0-999, 2 in 1000-1999, 3 in 2000-2999, 4 in 3000-3999
