### ISSUE TITLE
Master of Signal and Moritat points cost

### ISSUE THREAD

**Issue by DornVII87** [BSData/horus-heresy#196]
Hey both of these on mine are showing up as 45 points each. I'm looking in the betrayal book and they're both meant to be 35 points unless I'm missing an FAQ that upped their points cost. Cheers.

**Comment by capitaladot** [comment]
I will double-check this.

**Comment by DornVII87** [comment]
Don't worry about it, apparently the black book is out of date there was just no update that I could find. 
Thanks for looking though.

**Comment by capitaladot** [comment]
No problem; I have a time or two gotten mixed up with the various contradictory errata.
