### ISSUE TITLE
The base cost of a Praetor Armoured Assault Launcher should not be 300

### ISSUE THREAD

**Issue by LachrimallusExterminator** [BSData/horus-heresy#1965]
![F5DDE878-24E4-4874-8EF0-4607F7D1E02B](https://user-images.githubusercontent.com/84422145/130826639-0c24f8aa-1f6b-4b7c-bf6c-aff8ce60a82d.png)

**Comment by LachrimallusExterminator** [comment]
This means that the first vehicle selected cannot have any upgrades.

**Comment by LachrimallusExterminator** [comment]
@Mayegelt Can anyone help you with fixing issues or is it just you?

**Comment by Mayegelt** [comment]
> This means that the first vehicle selected cannot have any upgrades.

Sorry, need better clarification on what you are meaning with this one.
I've worked out the cost issue on them. But is this a different issue?

**Comment by Mayegelt** [comment]
I've put a pull through, I think it's all fixed, unless the issue I quoted from above was a separate issue.

**Comment by LachrimallusExterminator** [comment]
Thank you. What I meant was that, when you add a PAAL, the base cost is 300 and almost no available upgrades. You can only change sponsons, etc, for a second subsequent vehicle.
