### ISSUE TITLE
HH V1 - Last 2 RoW to be fixed.

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#1976]
*Ultramarines
- [ ] Vigil Opertii Mission (Hopefully fixable later)
  - [ ] Must have Militia Allied detachment, with Gene-Crafted & Warrior Elite provenance
  - [ ] No Levy Squads
  - [x] Loyalist only
  - [x] Must include Vigilator  FiXED 07/Sept/21

Any
- [ ] ZM Assault Force
  - [ ] Restrict Teleport Assault to only appear when ZM Assault Force Rite is selected NEED TO GET BACK TO LATER!
  - [x] Units limited to 15 marines at most. FIXED: 16/06/21
  - [ ] No Vehicles other then walkers NEED TO GET BACK TO LATER!
  - [ ] no SHV/GC NEED TO GET BACK TO LATER!

**Comment by Dorn1512** [comment]
note please, that not all walkers can be taken at army (only simple and contemptor) 
![ZM](https://user-images.githubusercontent.com/82025950/154855962-f7a93a6b-9619-49e5-bda1-bf9b46e6c7c3.JPG)

**Comment by Mayegelt** [comment]
Moved to new repo for HH1 located here.
https://github.com/BSData/horus-heresy-1e
