### ISSUE TITLE
[admin request] Gitter purge

### ISSUE THREAD

**Issue by amis92** [BSData/horus-heresy#1984]
Since we're no longer using Gitter as a communication medium and Discord is now the only approved community place outside of GitHub:

> ➡ Please remove any gitter references in datafiles.

For `Author URL` field, we suggest linking to `https://www.bsdata.net/contact`  as it's the main contact page with all available mediums linked.
For `Author Contact` field, there's not much guidelines. Consider `Discord: @HH Data Dev` or `Discord: #hh-data`.

**Comment by Mayegelt** [comment]
I don't think we have any anymore. I've just removed the link from the wiki on here. Don't think there was anymore.

**Comment by amis92** [comment]
You've got it in two files:
- (HH) Mechanicum - Questoris Knight.cat
- (HH) Daemons of the Ruinstorm Army List.cat
https://github.com/search?q=org%3ABSData+gitter&type=code

**Comment by Mayegelt** [comment]
Ok cool. I'll cull them tomorrow hopefully. Kinda ill again. Should feel better tomorrow
