### ISSUE TITLE
Legion Command Squads not having Legion-Exclusive Options

### ISSUE THREAD

**Issue by Lord-Falkenrath** [BSData/horus-heresy#1994]
As stated in the title, Legion Command Squads, both terminator and not terminator variants have numerous issues pertaining to legion-specific wargear and options, listed below:

- [x] IW Jetbike Command Squads do not have access to Shrapnel Bolts. 
- [x] WE Command Squads do not have access to Chainaxes. Every model with a chainsword, as well as every terminator model with a power weapon, is supposed to be able to exchange that weapon for a chainaxe for the same price as the original weapon (typically free)
- [x] RG Terminator Command Squads have a restriction of one Pair of Raven's Talons per squad, which they should not have. Every model should be able to take a pair of Raven's Talons. Taking individual Raven's Talons does not trigger this limit.

*Slightly separate issue:*

- [x] There is a RAW vs RAI debate about WS terminator command squads and Qin Xa. From the wording of his *Master of the Keshig* ability, it would seem to imply that merely including him in the army is sufficient to arm a terminator command squad with Power Glaives for +10pts per model, regardless of whether he is the warlord. RAW, this seems to be legal so long as the actual warlord allows for a terminator command squad (ie, a terminator character or the Khan). RAI would likely be that Qin Xa has to be the warlord for this ability to apply, but I have not found a FAQ clarifying the issue.

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version [e.g. 2.03.21]
 - Release version [v15.3.0]

**Comment by Mayegelt** [comment]
If you could edit that list please with all the non-character options, as the standard bearer unfortunately isn't a character.

**Comment by Lord-Falkenrath** [comment]
Edited. I feel mildly foolish for not realizing that the Standard Bearer is not a character

**Comment by Lord-Falkenrath** [comment]
Second edit to re-add the WS terminator command squad issue
