### ISSUE TITLE
Legion command squad - Jetbike points error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1999]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 3.25.33

**Platform:** Android

**Dropbox:** No

**Description:** Legion command squad mobility: jetbike option is to expensive by 45pts, should be 105 pts for the initial upgrade not 150.

**Comment by Mayegelt** [comment]
Sorry about the delays, Been really ill lately, so not really getting anything done. Hopefully will soon.
