### ISSUE TITLE
Heavy support squad seargent has wrong profile

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2000]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The heavy support squad seargent has artificer armour when it isn’t selected, and normal armour when it is selected.

**Comment by zopha** [comment]
Seems to be a profile swapped around. 

Standard armour 
![Screenshot_20211117_123810.jpg](https://user-images.githubusercontent.com/1666415/142202893-7bf831c8-8213-49d5-84c9-6b1883b99814.jpg)


With artificer armour selected. 
![Screenshot_20211117_123838.jpg](https://user-images.githubusercontent.com/1666415/142203707-03e2b59d-fb7d-4ccc-88d9-e742f3b74d76.jpg)

**Comment by Mayegelt** [comment]
Sorry about the delays, Been really ill lately, so not really getting anything done. Hopefully will soon.
