### ISSUE TITLE
Terminator deathwing companion - wargear cost error

### ISSUE THREAD

**Issue by zopha** [BSData/horus-heresy#2002]
Reported by hrobar on Discord.

Terminator deathwing companions have two errors, 

The option to exchange into pair of LC is listed as +15 pts while it should be free.

Also basic combi bolters are listed as 7pts/ppm, and should be free instead.

**Comment by Mayegelt** [comment]
Sorry about the delays, Been really ill lately, so not really getting anything done. Hopefully will soon.

**Comment by zopha** [comment]
@Mayegelt No worries, I still have access so I can make a branch and put some of the fixes for the simpler stuff in that.

Cost for combi-bolters looks fine, I've asked for claification

![image](https://user-images.githubusercontent.com/1666415/142235103-db83efe8-e28e-40d9-afae-a0386b03bd7d.png)

**Comment by zopha** [comment]
Found it, 

![image](https://user-images.githubusercontent.com/1666415/142237593-293c9a78-15c4-46b5-8e45-9424d244030d.png)

I'm not very familar with Mournival rules though.
