### ISSUE TITLE
Artificer Armour

### ISSUE THREAD

**Issue by LachrimallusExterminator** [BSData/horus-heresy#2004]
Artificer armour has no points cost for sergeants. This in all legions and FOCs. Should cost 10 points usually.

 - OS: iOS
 - BattleScribe version: 2.03.15
 - Release version: Legiones Astartes v666

**Comment by Mayegelt** [comment]
Any particular unit or units?

**Comment by Mayegelt** [comment]
All these ones working. Centurion, Tact Squad, Tact Support Squad, Apothecary
![Screenshot_2021-11-24-11-10-38-049_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/20280410/143228523-f34c5e04-41a3-483b-84ac-f71a319d8b7e.jpg)
![Screenshot_2021-11-24-11-10-58-430_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/20280410/143228529-bf6f2bbe-4d2c-4baa-bd1b-755da56ec403.jpg)
![Screenshot_2021-11-24-11-11-02-110_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/20280410/143228530-fa631dab-cc8d-481e-ad51-f6e77f9e7592.jpg)
![Screenshot_2021-11-24-11-11-25-401_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/20280410/143228532-62f6f70f-0fe2-498e-8f06-b2d885ef49fc.jpg)
![Screenshot_2021-11-24-11-11-56-951_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/20280410/143228534-603cf1ae-d08f-4774-b576-eef83bf975a2.jpg)

**Comment by LachrimallusExterminator** [comment]
You are correct. Here is what I have found.

![E751D770-E084-4D85-87E3-C184639CCA86](https://user-images.githubusercontent.com/84422145/143323903-812e843d-b1c7-41e3-8c98-f1af3b8aa7be.png)
![CB65B39E-584C-4213-85F8-AE10AF0B13A8](https://user-images.githubusercontent.com/84422145/143323908-a2b68d8d-4564-4863-a81b-881cb98ac3d9.png)
![57954858-8C37-4558-A4F1-256AAB0C5AF5](https://user-images.githubusercontent.com/84422145/143323913-35524099-b9da-422a-8371-abeec0236c77.png)
![60D99F27-3CEB-42E2-8541-1D977BA4DF42](https://user-images.githubusercontent.com/84422145/143323916-8e7c3a64-a781-4f2b-950f-9679b771b5eb.png)
