### ISSUE TITLE
Dark Angels Unification war veterans RoW

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#2008]
Dark Angels Unification war veterans
A missing feature, when in terminator armour neither legion centurions ans preators are able to select a volkite caliver (for the same points as a combi weapon) 
Works fime for power armour variants but it's missing for terminators
The RoW allows any model that can take a combi weapon to exchange it for a volkite caliver with suspensor web (bigger than charger, smaller than culverin) 
For the same points

**Comment by LachrimallusExterminator** [comment]
Woooooooooooooooooaaah! What is this? Where is this Rite of War?

**Comment by Mayegelt** [comment]
> Woooooooooooooooooaaah! What is this? Where is this Rite of War?

Its a Mournival RoW
