### ISSUE TITLE
HH V1 - Mournival Rules

### ISSUE THREAD

**Issue by LachrimallusExterminator** [BSData/horus-heresy#2024]
You may prefer to merge this to something else. A few things caught my eye. 

Sky Stalker Jetbike squads are currently restricted to two Power Lances per squad, even at maximum strength, instead of one in three.

![0B19D1C4-B024-48DF-B93F-421FBBEAF989](https://user-images.githubusercontent.com/84422145/150404073-3ffc7709-f687-43c0-ba9f-5422070dac8b.png)
![6BD9A7DF-83B7-4810-A1CC-B51E120A710D](https://user-images.githubusercontent.com/84422145/150404077-85cd91ce-fdf9-4eb5-835a-bc2bbcde2ac0.png)

Apothecaries need the option to take Bullock Jet Cycles or Corvus Jetbikes, and associated weapons, so they can join these squads.

Deredeo Dreadnoughts need to be available in squadrons.

 - OS: iOS 14.8.1
 - BattleScribe version: 2.03.15
 - Release version: Mournival v46

**Comment by Mayegelt** [comment]
Thanks for the report. Should hopefully get to it soon. I thought I had added the Apoth ones, but maybe I missed it or missed something with it.

**Comment by LachrimallusExterminator** [comment]
Knew I was forgetting something. By the way I read it, HQs with Bolters can have the Mournival Special Issue Ammunition if it is not expressly forbidden by the ammunition’s rules entry.

![9E374099-2020-4F02-AAC0-0ACDBE89A7D5](https://user-images.githubusercontent.com/84422145/150657943-fa06ed1c-3a94-482a-9ed7-e28b30590d45.png)
![AB2F02E7-3D16-4EAE-9434-A36D27232D2F](https://user-images.githubusercontent.com/84422145/150657945-4951a821-5a31-4cc7-a9b1-5b7435d36c8c.png)

**Comment by LachrimallusExterminator** [comment]
Knew I was forgetting something. By the way I read it, HQs with Bolters can have the Mournival Special Issue Ammunition if it is not expressly forbidden by the ammunition’s rules entry.

**Comment by Mayegelt** [comment]
Had a look at it today. Added the options to Centurions and Praetors.
I've not restricted the option to only when bolters or bolt pistols or whatever are taken. But of course the rules themselves do say what they apply to.

Release should be ready soon as I need to test it as well. If not released in a week then send me a reminder. Its a bit random when I can spend time on stuff.

**Comment by Mayegelt** [comment]
Still need to do the
Apothecaries need the option to take Bullock Jet Cycles or Corvus Jetbikes, and associated weapons, so they can join these squads.
&
Deredeo Dreadnoughts need to be available in squadrons.
I think. But fixed the power weapons and additional ammo things.

**Comment by LachrimallusExterminator** [comment]
Hello. Some additions from the Mournival FAQs. Please add the Banesword (yiss!), Doomhammer and Hellhammer (yiss!).

**Comment by LachrimallusExterminator** [comment]
Just want to draw attention to my previous post.

**Comment by LachrimallusExterminator** [comment]
Hello. I know it’s out of date, but if you could add the rest of the blade/sword/lord/hammer Baneblade variants when you can. Thanks.

**Comment by Mayegelt** [comment]
Closing this as Mournival adopted HH2. So no need anymore.
