### ISSUE TITLE
Legio custodes can't take divining blades

### ISSUE THREAD

**Issue by Dorn1512** [BSData/horus-heresy#2037]
Hi.
Problem:
at psyarkana we have a divining blades, which can take _**one model**_ with paragon blade for +30pts.
Legio custodes Hetaeron guard suqad can take paragon blade. It means, that one Hetaeron guard model can upgrade paragon blade to divining blades.
Could you make a emerging line with divining blades when you choose a paragon blade? or make a separate line "one of hetaeron guard squad can take divining blades - 55 pts"
![Blade](https://user-images.githubusercontent.com/82025950/154855641-2cf60ec6-919c-436d-9682-6f93e5825a13.JPG)
![hetaeron](https://user-images.githubusercontent.com/82025950/154855643-2e3edaac-8dbc-4997-8a4d-e4ece778430f.JPG)

**Comment by Mayegelt** [comment]
This is one I missed. I had included it for the Sister of Silence Knight Centura.
Will be fixed in next push.

**Comment by Dorn1512** [comment]
> This is one I missed. I had included it for the Sister of Silence Knight Centura. Will be fixed in next push.
And one more fix please)))
Solar auxilia legate commander has a same problem. When he is upgaded to Lord Marshal, he can take paragon blade, but can't upgade to divining blades

![LM](https://user-images.githubusercontent.com/82025950/154956820-1c99b2df-0002-4329-bbf6-f1f60a11be08.JPG)

**Comment by Dorn1512** [comment]
After depositary upgrade, hetaeron guard still can't take divining blades(((

**Comment by Mayegelt** [comment]
Seems it didn't take. I'll give another look. I probably accidentally hit a hide box ticked by accident before uploading.
