### ISSUE TITLE
Master of armour bug

### ISSUE THREAD

**Issue by Dorn1512** [BSData/horus-heresy#2038]
Hi again.
It's unsolveble problem to hide master of armour HQ choice, if you don't take a RoW armoured breakthrough?

**Comment by Mayegelt** [comment]
I could program it to hide the master of armour unless armoured breakthrough is selected.
However as they are an option to gain Master of the Legion to be able to have the RoW they have not been in the past. It is the same as with Primarch who appear in the HQ choice, but is only available as an HQ choice if you take Primarchs Chosen.
Instead having it show an error that you need to have armoured breakthrough if you select it is a good option.
