### ISSUE TITLE
Word Bearers burning lore

### ISSUE THREAD

**Issue by Dorn1512** [BSData/horus-heresy#2039]
Hi again))
Now one problem with Word Bearers burning lore. This wargear can be taken by Praetor, centurion and only chaplain and diabolist. But now it can be taken by any consul.

![lore](https://user-images.githubusercontent.com/82025950/154969882-be774092-584e-463f-9650-290de25de53e.JPG)

**Comment by Mayegelt** [comment]
Thanks for the spot. got that fixed now. Will go out next push in a few mins hopefully. Just getting a couple of people to test and feedback.
