### ISSUE TITLE
EC Sunkillers and WS Dark Sons of Death squad

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#2046]
New units for EC and WS

https://www.warhammer-community.com/wp-content/uploads/2022/03/V7pz4FAPFUM2apkb.pdf

**Comment by Mayegelt** [comment]
EC unit finished.
Will hopefully get the WS one done in the next few days.

**Comment by LachrimallusExterminator** [comment]
Epic. Excited for Sunkillers.
