### ISSUE TITLE
3rd Company Elite

### ISSUE THREAD

**Issue by LachrimallusExterminator** [BSData/horus-heresy#2054]
This Rite of War allows Kakophoni to be taken as troops, but it does not require all compulsory troops to be Kakophoni. Also, please make sure Mournival additional Consul options are available. I cannot find the Kakophonix Prime, for example.

![6DF0062B-5920-4AD4-A4AB-9AF33C72951B](https://user-images.githubusercontent.com/84422145/160484631-3febbe98-22e0-4753-9350-afff883dfe44.jpeg)
![F2C16C52-DA12-4858-B059-B72B5791C19A](https://user-images.githubusercontent.com/84422145/160484640-dd2056e6-fa0d-477c-914a-ac091033283a.jpeg)

 - OS: iOS 15.3
 - BattleScribe version: 2.03.15
 - Release version : Mournival v48

**Comment by Mayegelt** [comment]
fixed in next push
