### ISSUE TITLE
Always 1 too many Master of the Legion

### ISSUE THREAD

**Issue by asteroidrules** [BSData/horus-heresy#2065]
Adding a praetor or praetor tribune to the roster will cause it to claim there's too many selections of Master of the Legion (maximum 0) this occurs regardless of points level, oddly enough the consul delegatus does not have this issue, adding both a delegatus and a praetor to the same list still causes it to say there's too many Masters of the Legion, but now it lists a maximum of 1.

**Comment by Mayegelt** [comment]
You can only have 1 MOTL per 1000 points spent in the army.
This should be working as intended.
Remember a delegatus does not have Master of the Legion. But does have a
similar rule that interacts with it.

**Comment by asteroidrules** [comment]
The problem is the data currently sets a hard limit of 0 masters of the legion regardless of points level, any praetor will cause it to claim I've exceeded this limit. The delegatus appears to count as a master of the legion as well, but unlike the praetor his presence increases the maximum amount of masters of the legion allowed.

I've tested this at 1000, 1001, 2000, and 3000 points limits and it occurred every time.

**Comment by Mayegelt** [comment]
Which version are you using of both files

**Comment by Mayegelt** [comment]
Remember the Delegatus has MoTL kind of. But allows you to have it in under 1000pts games. However in over 1000pts games it doesn't

**Comment by asteroidrules** [comment]
I think I found the issue: it checks the amount of points spent rather than the points limit, so unless you actually have added 1000 points to your list it'll say you can't have a MotL.

**Comment by Mayegelt** [comment]
> I think I found the issue: it checks the amount of points spent rather than the points limit, so unless you actually have added 1000 points to your list it'll say you can't have a MotL.

So the answer I said in my first reply ;P
"You can only have 1 MOTL per 1000 points spent in the army."
