### ISSUE TITLE
HH V2 - Apple devices not working 

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2083]
**File:** 2022 - Horus Heresy.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When you select crusade LA and hit ok to go to build a list, it throws you back to the select force screen

**Comment by Mayegelt** [comment]
Unfortunately this seems to be an issue that I have no idea why it's not working and as such no idea how to fix it.
The likely chance is when the Mech file (or whatever is next) comes out then it will give a better idea of if it's the legion cat file that is messing it up or the heresy gst file.

**Comment by graysddoman** [comment]
![error](https://user-images.githubusercontent.com/84330452/177190115-9181ebfa-aeb0-4f4b-8e7f-a35dc82d1664.jpg)

Don't know if this helps, I'm not familiar enough with the data format, so I'm not sure what this is telling us. But I get the error message if I follow these steps:

1. Create new List
2. Select the Catalogue
3. Select the Force Org "New ForceEntry"
4. Save the list
5. Select Edit Forces from the menu
6. Select the Catalogue
7. Select the Force Org "(HH V2) Legion Astartes v3)
8. The Error is then displayed

**Comment by Mayegelt** [comment]
My prescriptions will be ready on Friday. So I'll come in for a short time
in the afternoon for a brief chat and send the invoices across.

In other news, I had a pre-op assessment today. Also found out my insulin
pump is likely 3-6 months away at earliest. So bad news on getting the
pump, but also means I'll likely have the shoulder surgery before that, so
won't have to wait which is good.

I was told I'll need to isolate for 3 days prior to surgery as that is
standard procedure now. Recovery time will be a bit random depending on how
successful the op is, and ability to have pain management.
As such it may be a case that I might need to buy some annual leave.
Especially if I end up getting both done within the year.

Feeling slightly happier today, and after my Pre-Op as I was in town I went
to the Mind Drop-in for an hour or so. On the way back I briefly popped
into work as I needed to have an injection (hadn't taken a pen with me as I
thought I would have been home sooner, but going to Mind delayed me) so
also talked to everyone quickly before departing.

**Comment by Mayegelt** [comment]
So just released a random test with a random theory to maybe randomly solve the iOS issue. Please someone update and try and let us know.

**Comment by Mayegelt** [comment]
Test again. Another release pushed. I think "Techno" on discord solved the problem. If it isn't that then he seemed to have another fix anyway that seemed to work for him.

**Comment by Mayegelt** [comment]
Had a couple of people now confirm it is fixed. So gunna close this.
A HUGE thank you to Techno for finding the error and fixing it.
