### ISSUE TITLE
Tartaros Sergeant Issue

### ISSUE THREAD

**Issue by DedusJovus** [BSData/horus-heresy#2099]
Hi
There seems to be an additional Lightning claw in the Tartaros Sergeant options, that shouldn't be there, as it allows what should be illegal loadout for the model.
Screenshot provided for clarity
![Capture](https://user-images.githubusercontent.com/26274301/178140191-1e917ece-4fde-4771-aba8-336480e90174.PNG)

Also, both terminator units have pairs of Lighntning claws for free, while they should cost 10pts

The issue is present with the Mayegelt's latest commit from July 10

**Comment by nstephenh** [comment]
Thanks. I think the single lightning claw entry is leftover from before paired weapons were a selection entry group. I'll try and fix that tonight.
