### ISSUE TITLE
HH Destroyer assault squads dont have jump packs

### ISSUE THREAD

**Issue by AstorathTheGrimm** [BSData/horus-heresy#2112]
destroyer assault squads dont have jump packs

**Device and data (please complete the following information):**
 - BattleScribe version [e.g. 2.03.45]
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by Toreador13** [comment]
Confirmed Destroyer Assault squads do not have the jump pack listed as well as missing their Special Rules. I can update in my patch.
