### ISSUE TITLE
Standard weapon profile

### ISSUE THREAD

**Issue by Tyther** [BSData/horus-heresy#212]
I noticed there were no standard weapon profiles for things like Boltguns and other 40k weapons (essentially any basic weapons, pre upgrades, such Auxilia Rifles)

Was there a reason for this (like everyone should just know the 40k profile off by heart/get a printoff with standard weapon profiles on it) or is it okay for people to start adding them to the profiles?

**Comment by capitaladot** [comment]
I have gotten the idea from @Jonskichov that an eventual future version will be changing the relationship of datafiles, game systems, and catalogs, perhaps making shared information between catalogs more plausible (basically, a gamesystem is both the container for attributes, unit types, and FoCs, but also shared Rules, Profiles, etc.).
While I would be happy to review and merge pull requests adding these "from the core rulebook" items, I'll hold off on adding many of these things myself until the above changes come through.

**Comment by Tyther** [comment]
Ah okay, I felt like it must have been something like that to warrant the basic profiles missing from all armies. Looking forward to the BS update. Thanks for all the hard work!

**Comment by capitaladot** [comment]
@Tyther: here's the comments from @Jonskichov I mentioned: http://battlescribe.uservoice.com/forums/55066-general/status/269848
