### ISSUE TITLE
Book 6 Rites of War

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#213]
Generic
- [x] rite representing traitors from loyalist legions, gives boosts against loyalist marines, especially from the same legion 
- [x] rite making jetbikes troops, all units must be skimmers, jetbike or flyers 
- [x] rite representing loyalists from traitor legions, similar to other rite but different boosts
- [x] rite making contemptor and regular dreadnought talons troops not elites, must take forge lord and primius medicea as additional HQs.
- [x] rite making predator squadrons troops, sicarans (regular only) elites and allowing a single predator or sicaran as a HQ choice, all non-vehicle units must have transports
- [x] rite making the primarch a HQ choice not LoW (still has the price of failure) allowing him under the 2k limit, no LoW slot. but he dies, all scoring units cease to be scoring, only denial
- [x] rite allowing any battle-automata (castellax, vorax, domitar) as their respective FoC slots in a legion army (non-complusory), must include 1+ cortex controller, a forge lord must be taken, and only more forge lords or praevain may be taken as consuls
- [x] rite allowing assault squads to deep strike turn 1, on the turn they arrive, they can only be snap fired at, and gain hit and run from turn 2 onwards, all units in the army must be able to deep strike or be transported in flyers
- [x] rite removing 'support squad' rule from recons marines, all units deployed with scout or infiltate (actively used) gain shrouded during turn 1, no terminator units may be taken
zone mortalis rite, terminators are troops, 1 unit of terminators may be given deep strike for free, breachers when all in base contact gain +1 to invuln saves
- [x] rite of war for traitor legions only, must take an allied detachment of militia/cults. detachment gains stubborn in their deployment zone, and do not yeild victory points for being killed. primary detachment all gains outflank, must hold whole primary in reserves and can't deep strike

Legion-Specific
- [x] Sons of horus gain relentless while in their own deployment zone, fleet in no mans land, and crusader while in the enemy deployment zone, may also re roll all rolls of 1 to hit in the first turn. legion terminators are troops
- [x] death guard gain a cover save of 5+ while in the open as long as no enemy models are within 12", also rolls a D6 for each woodland terrain piece on the board, on a 4+, the piece has -1 to its cover save and is dangerous terrain to all non-DG units, all frag grenades and missiles are str5, must include siege breaker
- [x] world eaters gain FNP while in enemy deployment zone, ICs also gain IWND as well, enemy team gains +1 VP if WE player doesn't achieve 'attrition' or 'linebreaker' secondary objectives
emperor's children gain kakophoni squads as troops and they gain relentless, any infantry model in power armour or artificer armour may take sonic shriekers for cost
- [x] word bearers gain gal vorbak as troops, they may take drop pods and dreadclaws as DT. any unit that can take a rhino can instead take a drop pod, any enemy unit within the drop pods final landing spot (post scatter) takes a pinning test. all infantry units must deploy by deep strike
- [x] night lords gain night raptors as troops, any unit can take trophies of judgement for a fixed cost, any unit of 10 or more men, may take kharybdis assault claws as DT. must always charge if in range.
- [x] iron warriors: barrage weapons fired within 12" of friendly iron warriors only scatter D6, counters are left in the center of barrage attacks, if more barrage attacks are made within 18" of a counter and within 6" of friendly IWs do not scatter. also any IWs within 6" of a counter is fearless
- [x] alpha legion gain head hunters as troops, reroll who goes first, and any enemy unit shooting at an alpha legion unit must pass a leadership test first, unless they have already been shot at by alpha legion. enemy gains D3 VP if AL do not kill their warlord, all vehicles are held in reserves
- [x] imperial fists get phalanx warders as troops, any infantry unit can buy teleport arrays for a cost, units gain shrouded the turn they arrive via teleport array, plus enemy units with LoS and within 12" of the teleporting unit, must take a blind test at the of the phase
- [x] ultramarines must take a milita allies detachment with gene-crafted and warrior disciplines provenances, all infantry units in allied detachment gain infiltrator and implacable advance. recon marines lose 'support squad' rule.
- [x] iron hands gain medusan immortals as troops which are stubborn while in enemy deployment zone, also gain 'hatred(traitors)' rule across the whole army, no allies and no ferrus manus
- [x] raven guard for one turn only (of their choice) entire army gains zealot, gains D3 VPs for slay the warlord, allied militia are fearless while within 6" of raven guard infantry
- [x] salamanders cause fear, may chose to play additional game turn if random length in is use (instead of rolling) librarians gain special psychic power, which is a replacement 'pyromancy' primus power. str5 ap1 beam 18" range, and units that take casualties from it must take a morale check regardless of the 25% rule, with a negative modifier equal to the number of unsaved wounds caused.

**Blood Angels**
- [ ]  A
- [ ]  B

**Dark Angles**
- [ ]  A
- [ ]  B

**White Scars**
- [ ] A
- [ ] B

**Comment by Millicant** [comment]
Hey @capitaladot same goes for book 6 as the new LA army book - none of this will get added until I have it in hand.  There are a lot of unknowns about how this is going to look, I need to read and digest it before we start changing things, especially as it may result in new catalogues or significant changes to existing ones!

Thanks!

**Comment by Millicant** [comment]
Complete with merge of #252
