### ISSUE TITLE
Cataphractii sergeant 

### ISSUE THREAD

**Issue by ashtroboy79** [BSData/horus-heresy#2133]
Cataphractii sergeant appearing as a Tartaros Sergeant 

**To Reproduce**
1. Go to Elites
2. Click on Terminator Cataphractii Squad
3. Return to roster

**Expected behavior*
Expect it to be a Cataphractii Sergeant 

**Screenshots**

**Device and data (please complete the following information):**
 - OS: iOS
 - BattleScribe version  2.03.15
 - Release version v6

**Additional context**

**Comment by Mayegelt** [comment]
Looks like the profile for Tart was just copied over, but some names weren't changed.
I'll fix in in a the next few mins.
