### ISSUE TITLE
Book 6 New Legiones Astartes rules and equipment.

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#214]
- [ ] Blood Angels
     - [ ] LA rules 
     - [ ] Assault Cannon exchange for heavy flamers
     - [ ] flamesword consul/praetor weapon 
     - [ ] hand flamer option for vulkite pistol eligible models
     - [ ] inferno pistol for plasma pistol eligible characters
- [ ] Dark Angels
     - [ ] LA rules
     - [ ] Terranic Greatsword for characters who get powerfists
     - [ ] Molecular acid shells on heavy bolters on infantry or dreadnoughts
     - [ ] Plasma repeater for plasma gun eligible models
     - [ ] Stasis Shells for grenade and missile launchers
     - [ ] calibanite war blade for power sword eligible characters
- [ ] White Scars
     - [ ] LA rules
     - [ ] power glaive for characters
     - [ ] Cyber raven for characters
- [x] Black Shields
     - [x] LA rules

**Comment by Millicant** [comment]
Replaced by individual Legion issues for easier tracking
