### ISSUE TITLE
Book 6 Mechanicum: new units.

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#216]
- [ ] new dark archmagos dominus named character, f**k ton of special rules giving minor boosts to automatabut the highlight is his melee weapon with is AP2 and each sucessful hit, auto-wounds D3 times. no FNP allowed and can't regain the wounds with IWND.
- [ ] Arlatax-class battle-automata: roughly the same stats as a castellax but is a JUMP PACK MONSTROUS CREATURE! has a plasma blaster and two power claws (+2str ap2, shred) which have built in mini-assault cannons (24" str6 ap4 heavy3). may upgrade one of the claws to a arc scourge, which is confers rampage and armourbane (must choose which weapon is being used)
- [ ]  knight-atrapos
- [ ] Anarchos Scoria

**Comment by Millicant** [comment]
I've got the book in-hand!  Let's get to work...

I figure these probably don't need to be added to the older Mechanicum lists - they are more or less obsolete at this point.  

As far as the rest - please just ensure that the current entries match the new ones in the book (for those that have already been entered, like the Knight Atrapos).

**Comment by Millicant** [comment]
Hey @capitaladot as I finish off the Legiones Astartes additions, you mind if I tackle this one too?  Let me know if you'd rather do it yourself.

**Comment by Millicant** [comment]
Hey @capitaladot I'm going to take silence as consent here.  Go ahead and make any further adjustments as needed!
