### ISSUE TITLE
Inner Circle Knights Cenobium

### ISSUE THREAD

**Issue by Doreo** [BSData/horus-heresy#2162]
The Thunder Hammer instead of Terranic Greatsword option is a radio button rather than letting you set up how many of the Cenobites you want to be with Thunder Hammers. (Can be like the 40K Terminator options where you can add new terminators and decide on equipment per Terminator).

Might be better to have the Preceptor cost 75pts rather than have a hidden cost.

**Comment by revivedtitan** [comment]
We are currently discussing moving to individual terminators instead of unit based.
