### ISSUE TITLE
Warsmith upgrade misplaced

### ISSUE THREAD

**Issue by XenoTechnian** [BSData/horus-heresy#2168]
In the current version (HH2 v16.0.11, Legions Astartes v22) the Iron Warriors “Warsmith” character upgrade is available to Centurions, however in Liber Hereticus, it states that the upgrade is for Praetors.

**Comment by UrsinePatriarch** [comment]
Yeah, that's on me and I'll have a fix up this weekend alongside some other updates.

**Comment by XenoTechnian** [comment]
Kk, thanks for all your time and effort, no rush ok?

>
