### ISSUE TITLE
[Join Request] Zippededo1/Allena360

### ISSUE THREAD

**Issue by Allena360** [BSData/horus-heresy#2169]
### Your Discord

Zippededo1

### Additional information

Hi All, 

Looking to join the community and learn to update the BS Data set files. Once I know what I'm doing I would be keen to help out and have a particular interest in keeping the Warhammer 40K & new Warhammer HH AoD 2.0 files up to date, as I have been a supporter of BS for years and the app has had such a positive influence on my experience playing these games as part of my hobby.  

I am a web developer by trade, however now run an IT system and so have some experience in data management and data warehousing. I expect this will be something completely new to me but i am keen to learn and support the community.

Thanks in advance 
Adam

**Comment by UrsinePatriarch** [comment]
Welcome to the party!
If you're already in the BS Discord, drop by the HH channels and get acquainted; were there any particular parts of HH you wanted to work on?
https://github.com/BSData/horus-heresy/issues/2070 <- This is our current checklist as we work on everything, so feel free to swing by their and figure out what you'd maybe like to look into.
