### ISSUE TITLE
New Red Legiones Book (release date March 16th): rules and unit changes.

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#217]
LEGION UPDATES FROM THE NEW LEGION RED BOOK
IF A UNIT IS NOT MENTIONED, THEN IT IS UNCHANGED
 
**Emperor's Children**
- [x] All models with the LA rule gain +1 initiative on the charge
sonic shriekers are now -1WS to enemy models in base contact which aren't immune to fear. Effects the full length of the combat (not just first round), not just if you charge.
- [x] phoenix terminators are WS5
- [x] phoenix terminator sergeant now have 3 attacks
- [x] the cacophony weapons are heavy2, previously heavy1

**Iron Warriors**
- [x] iron circle added, elites choice, single unit can be taken as a command squad to perturabo. said unit gains a minor buff of their choice from a list.
- [x] tyrant seige terminator squads now heavy support choices
- [x] iron havocs are BS5

**Imperial Fists**
- [x] phalanx warder squads 'shield wall' rule fixed, now confers +1WS instead of +1I.
dorn's chainsaw has 'unwieldy' replaced with 'reaping blow' (see DG section)

**Night Lords**
- [x] 'from the shadows' confers 5+ cover save, use to be 6+
- [x] 'talent for murder' confers +1 to hit and wound, use to be just to wound
- [x] terror squads gain 'precision strike'
- [ ] sevatar has his additional psyker rules from the FAQ added to his profile, also gains precision strike

**Iron Hands**
no changes 

**World eaters**
- [x] 'blood lust' is now on a 4+ rather than a roll of a 1.
previous version of 'incarnate violence' replaced with may re-roll 1's to wound on the turn they charge

**Ultramarines**
no changes

**Death Guard**
- [x] may re-roll dangerous terrain tests, regardless of what the terrain is
- [x] instead of forcing successful rolls to wound with poison and fleshbane, DG get FNP(4+) instead
- [x] power scythes lose unwieldy and the ability to replace attack value with number of enemy models in base contact with the following
'reaping blow': -1 initiative, if in base contact with more than one model at their initiative step, they gain +1 attack
- [x] grave warden toxin rule replaced with 'poison(3+)' on death cloud and grenade launcher
- [x] deathshroud can be taken as a HQ or elites choice, plus as a command squad for a terminator praetor or mortarion. 
- [x] mortarion's scythe is no longer unwieldy, replaced with 'reaping blow'.
- [x] mortarion's witch spite only affects malediction powers affecting him or his squad 

**Sons of Horus**
- [x] gain 'death dealer' to their legiones astartes rule, +1BS if shooting at an enemy within 12" with a pistol, rapid fire or assault weapon, doesn't effect snap fire, overwatch or fury of the legion shots.
- [x] justearins terminators start off at 255pts for 5 men, may still take up to 7 additional men. they now have 2 wounds
- [x] abaddon has precision strike

**Word bearers**
rules unchanged from tempest

**Salamanders**
- [ ] ​firedrakes are now 60pts each and 1 wound*

**Raven Guard**
- [x] Mor deythan are 10pts more expensive at base cost (additional men are still same price)
- [x] all dark furies have raven talons by default, no price increase
- [x] dark fury sergeant gains 'precision strike'
- [x] Kaedes nex gains precision shots

**Alpha Legion (or are they?)**
- [x] saboteur's sabotage attack now AP3 against things with a toughness value, and AP2 against vehicles
- [x] saboteur can no longer take a jum pack
- [x] headhunters come with combi-bolters as standard, may upgrade them to combi-weapons for the same cost as terminators can.
- [x] headhunters replace 'preferred enemy' with 'precision shots'

**Comment by Millicant** [comment]
Hey CapitalDot - I'm all about adding the new stuff when it becomes available.  

Two notes on this process: 
1) None of this is to be added until the books are in-hand.  That goes for the new Red Book as well as Book 6.  
2) Please no releases.  I will manage releases. 

Thanks!

**Comment by capitaladot** [comment]
I certainly agree on point 1, and am simply tabulating the reported changes for when one of us does have the new book in hand.
On point two, I think I'd like to hear @amis92 and some of the rest of the @BSData/data-authors-gw team way-in. I don't think "top down" is quite how these projects work.

**Comment by amis92** [comment]
@capitaladot Well as my input is requested, I want to know your stances here better. @Millicant when you said "no releases" you meant it as "let me do releases exclusively at all times" or more in context, as in "do not release *these* changes"?

I mean, I sure understand you wanting to keep HH under control, but making contribution management control exclusive to a single person in internet is just not a good idea - a simple example is that you may take a week off, or just plain simple be unactive for some time - and then the updates would stall.

Clearly you could agree on some timeout, for example: if there is no response for say 72 hours, or a week, anyone can do release. (it's *just an example!*)

**Comment by Millicant** [comment]
Specifically, no releasing of these changes!  This is going to be massive and it could easily get out of hand.  I'd like to QA it all properly (like I said I would and totally failed to do with HH:MT). These are awesome lists though, @capitaladot and will definitely help us stay organized while adding it all!

As far as regular releases, let's go with immediately for bugfixes/changes, but for any features/additions, I'd like to have a chance to review it.  I think 72 hours is reasonable, thanks @amis92!

I'll start using branches/merges properly, and @capitaladot and I can assign ourselves/each other to fixes to ensure we aren't causing errors.  Sound good?

**Comment by amis92** [comment]
I'm only happy if you both are, that's my job here ;)

**Comment by cowomo404** [comment]
@Millicant @capitaladot @amis92 I'm happy to help where I can. I'm an ideation and design manager (read: UX) by profession, but I can certainly help QA catalogs as needed.

**Comment by capitaladot** [comment]
@cowomo404 Speaking just for myself, of course, QA help would be very
welcome!
Are you familiar enough with git to merge pull requests?

**Comment by cowomo404** [comment]
@capitaladot I'm familiar with the basics and I'm surrounded by git enthusiasts. I am not, however, familiar with the architecture of BattleScribe (just downloaded Pro yesterday) but I assume the catalogs are some kind of XML schema... in either case I can get up to speed pretty quick.

**Comment by Millicant** [comment]
@cowomo404 we'd love to have you join/help out!  QA here shouldn't need to deal with the XML directly unless we run into conflicts, I would imagine.  @capitaladot probably knows more about that, I have dealt with the Battlescribe editors almost exclusively for this entire project.  

Side note - my copy of Retribution is en-route!  It may take a minute, as I'm currently deployed overseas.  Either way, once it's here I will start the inevitable and long process of restructuring as needed.

**Comment by capitaladot** [comment]
Pardon my delay.

I have merged your pull request into master; pray, take a look and see if I
resolved the Git conflicts without losing anything you'd expect to see?

**Comment by Millicant** [comment]
Thanks!  That was great!  No worries on the delay - I'm just excited to keep adding all the new stuff.

There were a couple weird conflicts - three duplicate items with identical IDs - I sorted that already.  I'll go through tonight and check on the rest to make sure it survived.  

Thanks again!  I'm glad you're around to solve this stuff, I'm mostly lost.

**Comment by Millicant** [comment]
@capitaladot I'm going to be away from the internet/computer for about 3 weeks.  My copy of the book is enroute, but won't arrive before I leave.  

You've got this for action!

**Comment by HorustheWarmaster** [comment]
I got my red book early this past week- can't wait for the update!  Thanks for your work guys!

**Comment by Lunawolvesofhorus** [comment]
Just wondering when the new rules will be applied to the Battlescribe data? Sick of my "friend" using the rules still on there which give his salamanders an advantage over my Justaerins even though he knows the new rules are out :\

**Comment by capitaladot** [comment]
Despite promises to the contrary, I have been slow to start on this; BattleScribe is about to change in a huge way (with all core rules being contained under the game system), and I wonder if it would make sense to start that effort first before we work over another book.

**Comment by Millicant** [comment]
I'm back from my trip to the land of no interwebz.

What's the status?  I plan to dive in immediately and start writing these changes, probably tonight or tomorrow.  Let me know before I overwrite anything you've already accomplished.
