### ISSUE TITLE
Unexpected Charnable Sabre Cost on Palatines (IIIrd Legion)

### ISSUE THREAD

**Issue by ThatEvilOne** [BSData/horus-heresy#2171]
In the Palatine Blades entry for the Emperors Children when prompted to have "all models must choose from" the charnable sabre is listed at 5 points per sword despite being default wargear. The Tabar and Glaive are unaffected.

**Comment by UrsinePatriarch** [comment]
Thanks for bringing this to our attention!
We should have it all fixed by this Wednesday.

**Comment by UrsinePatriarch** [comment]
Fixed in merge #2172
