### ISSUE TITLE
Iron Warriors - Graviton Weapons not limited to ICs.

### ISSUE THREAD

**Issue by parkerPWNT** [BSData/horus-heresy#2186]
**Describe the bug**
Graviton weapons should only be available to ICs. 
Currently an entire terminator squad could take Graviton Crushers or a vet squad members could take Graviton Maces.

**To Reproduce**
Set legion to IW
Add a terminator squad. 
View weapon options.

**Expected behavior**
Graviton melee weapons should only be available to sergeants or other ICs. 

**Device and data (please complete the following information):**
 Windows 
BattleScribe v2.03.21.166
Horus Heresy (2022) v7

**Comment by UrsinePatriarch** [comment]
Independent Characters only is incorrect (Sgts are not ICs), but Characters only is correct; this will be addressed. This'll be a pain, but fairly workable with more constraints.

Thank you for bringing this to my attention.

**Comment by UrsinePatriarch** [comment]
Still working to mark everyone relevant as character/IC, but Graviton weapons now properly check for those things, so this is as "closed" as it will be for some time.
