### ISSUE TITLE
Incorrect point cost on Dark Angels dreadwing Interemptors

### ISSUE THREAD

**Issue by Chawk95** [BSData/horus-heresy#2189]
**Describe the bug**
The points are incorrect on the upgrade options on the dark angels dreadwing Interemptor. 

The plasma incinerator and missile launcher should be 15pts not free, 
The artificer armour and melts bombs should also be 10 pts each not free.

**Device and data (please complete the following information):**
 -Android
 - BattleScribe version v2.03.25.338
 - Release version v16.0.11

**Comment by revivedtitan** [comment]
Dreadwing Intermeptor point costs have been fixed in the PR mentioned above, you'll see this in the app once its been merged in for release.
