### ISSUE TITLE
Iron Warriors Errors in HH V2, v22

### ISSUE THREAD

**Issue by IVLegionnaire** [BSData/horus-heresy#2193]
**Describe the bug**
Omission of Tyrant Seige Terminators for Iron Warriors Legion
Vulkan is set as the Iron Warriors Primarch.

**To Reproduce**
1. Select Iron Warriors as the Legion
2. Tyrant Seige Terminators not present in Heavy Support3. 
3. Primarch is incorrectly linked to Vulkan4. 

**Expected behavior**
Tyrant Seige Terminators present in Heavy Support
Primarch should be Perturabo

**Device and data (please complete the following information):**
 - OS: iOS
 - BattleScribe version 2.3.15
 - Release version (HH V2) Legions Astartes v22

**Comment by UrsinePatriarch** [comment]
Please update your data and see if this persists.

**Comment by IVLegionnaire** [comment]
> Please update your data and see if this persists.

I've updated the data (07/08/2022 21:40:59) and:

1) Tyrant Siege Terminators are still missing from Heavy Support.

2) The "Primarch" option is now missing completely. I've attached a screenshot.

![image](https://user-images.githubusercontent.com/111022669/184075887-18dc2a1f-7d42-4d4f-8f68-0c113d22661a.png)

**Comment by UrsinePatriarch** [comment]
Don't suppose you're using the specific Iron Warriors catalog? I recently moved the IW stuff to that catalog so it's actually an error if any of the IW stuff shows outside of it.

**Comment by Mayegelt** [comment]
> Don't suppose you're using the specific Iron Warriors catalog? I recently moved the IW stuff to that catalog so it's actually an error if any of the IW stuff shows outside of it.

Remember that isn't in the current release. If something gets pushed to the main file, that isn't what people download the normal way till a "/ release" has been done

**Comment by IVLegionnaire** [comment]
> Don't suppose you're using the specific Iron Warriors catalog? I recently moved the IW stuff to that catalog so it's actually an error if any of the IW stuff shows outside of it.


Im using the HHV2 v22 datafile/catalogue.
Hope thats helps?

![image](https://user-images.githubusercontent.com/111022669/184247953-2b1715ff-bec0-4da3-b34d-2dfea04c2231.jpeg)

![image](https://user-images.githubusercontent.com/111022669/184247971-74153e62-ae03-4f86-9991-59f3e8a4c2b7.jpeg)

**Comment by UrsinePatriarch** [comment]
Seems like the current datafile's got that problem, yep; I'll see about fixing that up for yah this weekend, mate.
Appreciate you pointing it out.

**Comment by IVLegionnaire** [comment]
> Seems like the current datafile's got that problem, yep; I'll see about fixing that up for yah this weekend, mate.
> 
> Appreciate you pointing it out.

Happy to identify any errors I come across if it is helpful? It's very much appreciated that you and others take the time to build the datafiles.
