### ISSUE TITLE
Iron Hands Gorgon hammer bearer Combi-Bolter points incorrect.

### ISSUE THREAD

**Issue by Project39** [BSData/horus-heresy#2204]
**Describe the bug**
Iron Hands Gorgon Hammerbearer Combi-Bolter costs 10pts

**Expected behavior**
Combi-Bolter is included with cost of model and should be free

**Device and data (please complete the following information):**
 - OS: iOS and PC
 - BattleScribe version 2.03.15 (iOS)
 - Release version v10

**Comment by figjam-bohica** [comment]
whoopsie doodles. I'm transporting the IH units over to the new file structure and will fix this.

**Comment by figjam-bohica** [comment]
@UrsinePatriarch Go to bed!

**Comment by UrsinePatriarch** [comment]
Addressed in #2212
