### ISSUE TITLE
Legion still required with LA-X: Iron Hands v1

### ISSUE THREAD

**Issue by KarlKrieger** [BSData/horus-heresy#2207]
**Describe the bug**
Legion still required with LA-X: Iron Hands v1

**To Reproduce**

1. Create a Crusade Force Organisation Chart with LA - X : Iron Hands v1

**Expected behavior**
Redondant with new org with legion-specific forces.

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version 2.03.21
 - Release version v16.1.2

**Comment by IVLegionnaire** [comment]
This also happens with the IV-Iron Warriors v2 data file.

**Comment by UrsinePatriarch** [comment]
I'm not getting this error; could we see a screenshot, please?
![image](https://user-images.githubusercontent.com/46959832/185393663-65b4b3a1-843c-4426-92dc-8eeb13e66932.png)

**Comment by Mayegelt** [comment]
Are you remembering you still need to pick if you are trailor or loyalist?

**Comment by KarlKrieger** [comment]
My bad, I had a problem while updating data.

It's ok now.
