### ISSUE TITLE
Incorrect power weapon available 

### ISSUE THREAD

**Issue by KarlKrieger** [BSData/horus-heresy#2208]
**Describe the bug**
Calibanite Warblade and Carsoran Power Axe listed in power weapons list (without being DA or SoH).

**To Reproduce**

    Create a Crusade Force Organisation Chart (tested with Iron Hands and Thousand Sons)
    Create any squad/character with Power weapon option

**Expected behavior**
Calibanite warblade is a DA specific weapon but is an option for both tested legion, Carsoran Power Axe is a SoH specific weapon but is an option with Thousands Sons.

**Device and data (please complete the following information):**

    OS: Windows
    BattleScribe version 2.03.21
    Release version v16.1.2

**Comment by UrsinePatriarch** [comment]
I'm seeing the Calibanite (this was a known problem), but I'm not seeing the Carsoran. Can we see a screenshot? 
![image](https://user-images.githubusercontent.com/46959832/185394503-990c9c27-bc13-4e9c-9d06-90ebb8051983.png)

**Comment by KarlKrieger** [comment]
My bad, I had a problem while updating data.

It's ok now.
