### ISSUE TITLE
Missing IH specific options on some vehicles

### ISSUE THREAD

**Issue by KarlKrieger** [BSData/horus-heresy#2209]
**Describe the bug**
Iron Hands specific options for vehicles are present on some but not all vehicles (Blessed Auto-simulacra and Armatus Necrotechnika)

**Expected behavior**
Vehicles concerned : 

- Kratos
- Land Raider Proteus Explorator
- Land Raider Proteus Carrier
- Land Raider Spartan
- Scorpius 
- Vindicator

**Device and data (please complete the following information):**

    OS: Windows
    BattleScribe version 2.03.21
    Release version v16.1.2

**Comment by figjam-bohica** [comment]
I hadn't built the entries for them yet but will try to get there soon.
