### ISSUE TITLE
Contemptor Dreadnought Talon Power Fist weapons requirement conflict

### ISSUE THREAD

**Issue by Srlojohn** [BSData/horus-heresy#2213]
On the Contemptor Dreadnought Talons, when power fists or chainfists are added, you should be able to add a twin-linked weapon into each fist. However, it instead throws two contradictory errors. If you add the weapons, it will give an error claiming you have too many and that the minimum is 0, however, if you remove them it will claim you don't have enough and say the minimum is X (Where X is the number of fist weapons chosen). 

Example images:

![Untitled](https://user-images.githubusercontent.com/92633652/185467771-a50c974f-2baf-4654-a02b-9311ed505a18.png)
![Error2](https://user-images.githubusercontent.com/92633652/185467794-716ac6a8-e502-466e-b9a9-b3876b5d9f40.png)

**Comment by UrsinePatriarch** [comment]
I'm aware of this error and have fixed it in my most recent PR; should be released sometime this weekend.
