### ISSUE TITLE
Allegiance Error

### ISSUE THREAD

**Issue by twizted86** [BSData/horus-heresy#2215]
On the World Eater list I'm getting a too many allegiance selections, but if I delete any of them I get the error that they are required. 

![Screenshot_20220818-175143](https://user-images.githubusercontent.com/8060951/185509026-7e03dcdf-e503-445c-98bf-09a8fb867aa0.jpg)
![Screenshot_20220818-175154](https://user-images.githubusercontent.com/8060951/185509029-ebaf4f25-5d36-421a-a868-218737c39266.jpg)

**Comment by Mayegelt** [comment]
Do the Delete / refresh data and that should fix it when you make a new list.
![IMG_20220818_235930](https://user-images.githubusercontent.com/20280410/185509630-76b692e0-f3b5-4d3e-ae6d-42aabbd22032.jpg)

**Comment by twizted86** [comment]
Thanks
