### ISSUE TITLE
Blood Angels Catalogue Missing

### ISSUE THREAD

**Issue by SanguineAngel09** [BSData/horus-heresy#2219]
Latest update “All legions now have a seperate catalogue”. IXth Legion: Blood Angels are missing.

**To Reproduce**
1. Go to 'create roster’
2. Click on '(HH V2) Horus Heresy (2022) v10
3. IXth legion entry is not present.

**Screenshots**
![B50FB29A-9859-453A-93E4-7B04F139FDEE](https://user-images.githubusercontent.com/111572801/185606132-d6ee6177-dc6e-4d96-bfa0-da6b950b2f13.png)
![FFD20B99-B86C-4374-AE16-4D56D4CDA21E](https://user-images.githubusercontent.com/111572801/185606139-deb5f9f1-490c-4758-851c-f314807c180e.png)

**Device and data (please complete the following information):**
 - OS: 15.6.1
 - BattleScribe version 2.03.15
 - Release version 10

**Comment by Mayegelt** [comment]
It will be coming soon. It was unfortunately delayed.
