### ISSUE TITLE
Magos Prime has 1 too many selections of Paragon Blade (maximum 0)

### ISSUE THREAD

**Issue by cowomo404** [BSData/horus-heresy#222]
I'm confused by this error: "Magos Prime has 1 too many selections of Paragon Blade (maximum 0)" I expect to be able to exchange the Archmagos prime's power weapon for a paragon blade - rule error?

Options selected are:
- Archimagos Prime
- Malaga
- Paragon Blade

**What I am doing wrong?**

**Comment by capitaladot** [comment]
@cowomo404 : probably nothing; that's probably my bug. Thanks for the report! I will look into it.

**Comment by cowomo404** [comment]
No problem. Love the project. just wanted to help.

Also if it helps track down the issue, I don't think the regular Magos Prime has access to the Paragon Blade, I believe the magos must be upgraded to an Archmagos for the option to be available.

**Comment by Millicant** [comment]
Interesting.  I may have broken this when I was updating HH:MT.  Thanks for the heads up!
