### ISSUE TITLE
Incorrect reference for Machinator Array

### ISSUE THREAD

**Issue by cowomo404** [BSData/horus-heresy#223]
Data file lists the reference for the Machinator Array as HH3 p240

HH3 p240 is the Sicaran Venator Tank Destroyer

Rules for the Machinator Array are shown on HH3 p208

**Comment by capitaladot** [comment]
@cowomo404: which datafile?

**Comment by cowomo404** [comment]
@capitaladot Taghmata Army List v15

**Comment by Millicant** [comment]
@capitaladot This leads into another discussion for down the road: Once 1.16 is released (a long time from now) we're going to have to start reconciling rules and profiles into the gamefile.  Once we do, reference will probably have to be maintained by most recent release with said rule/profile.  That will likely make things easier, as updating a bunch of rules/profiles across multiple catalogues is untenable. 

Back on topic: we'll fix it!  Thanks for noticing.

**Comment by cowomo404** [comment]
@Millicant @capitaladot I would recommend considering some kind of timeline based catalog organization, rather than just newest stats, as the legions lists WILL change as the timeline progresses. Players can choose which area of the HH to play (Istvaan III Purge being very different from Shadow War revenge) Maybe something similar to what Flames of war does with early war, mid war and late war?

**Comment by capitaladot** [comment]
@cowomo404: As we haven't made an effort to segregate lists by book, spare
in the this case, my view is that it is probably best just to deprecate the
separate Mechanicum catalogs pre-Red Book Taghmata Army List, but as I did
not create them (credit there goes to @Millicant, and likewise for the
basis for many or most units in this new file), I didn't feel comfortable
doing so in a manner that might appear cavalier.
Doing the kind of "periodic" segregation you propose isn't practical, at
this point, as there are haphazard updates in numerous books (including red
books, which are not chronological campaign books), and given that even the
seemingly-sequential Book 6 might not necessarily be considered a book that
fits cleanly into a timeline (when did there stop being broken legions?
Never inside the Heresy, as far as I can tell).

**Comment by cowomo404** [comment]
@capitaladot - At some point we might presume that some units will change because the story, not necessarily because of the game...

One potential issue I see with deprecation is how do you handle the Mechanicum attached units which were gifted to the legions?  Not all Taghmata units are available and it's not required for them to be a separate formation. i.e. my Sons of Horus can take Thallax as heavy support. These Thallax do not have all the same options as the troop Thallax of the Taghmata. 

Perhaps these units are just added to the Astartes Crusade List (per the red book)?

**Comment by capitaladot** [comment]
100% agreed on consolidating to one file. with shared entries for
everything. Whenever I touch something, I try to update it to a shared
profile/rule while I am in there.

**Comment by zopha** [comment]
@cowomo404 Wasn't the Thallax/Castellax entry updated in the last FAQ to address that issue?

"The following updated entry which matches that found in the Mechanicum Taghmata Army List book replaces the entry found in the Legiones Astartes Crusade
Army list and Solar Auxilia Crusade Army list."

**Comment by cowomo404** [comment]
@zopha you are correct - I completely missed that little call out box. So using the most recent publication for the reference seems to make sense.
