### ISSUE TITLE
HH v2.0 - Leviathan - Grav-Flux Bombard AP4

### ISSUE THREAD

**Issue by elspammo** [BSData/horus-heresy#2239]
**Describe the bug**
File: [2022 - Horus Heresy.gst]
Line : 1594
Leviathan Dreadnought - Grav-Flux Bombard rules

Grav-Flux Bombard is AP4, not AP2 - pg 131 Astartes rules

**Comment by UrsinePatriarch** [comment]
This is correct and will be fixed in a coming release.
