### ISSUE TITLE
Vorax Incorrect Points

### ISSUE THREAD

**Issue by Guardbuddy** [BSData/horus-heresy#225]
Sorry to post so many things just for one specific unit, but I feel it is important :>
It seems the Vorax is 10 points too much.  It is listed as 75 pts per model on Battle Scribe while the Taghmata Red Book classifies it as 65 pts on Page 46.

**Comment by Millicant** [comment]
Gah!  I thought I fixed this, but it was in HH:LACAL!  The advent of gamesystem shared files is going to be incredible... :)
