### ISSUE TITLE
Selection Rules Issue: World Eaters Caedere Weapons

### ISSUE THREAD

**Issue by Srlojohn** [BSData/horus-heresy#2250]
Currently Caedere Weapons for World Eaters are listed under power weapons, and their points are added on-top-of the cost for a power weapon, however this is incorrect.

As per page 219 of Liber Hereticus, Caedere weapons replace a **Chainsword** on a character for 15pts, not a power weapon.

![Caedere_Weapons](https://user-images.githubusercontent.com/92633652/186142669-ee1838fd-9a15-459f-b9ce-366749e59ed6.png)

**Comment by UrsinePatriarch** [comment]
This has been fixed in a recent commit and will be publicly released as of tomorrow.
