### ISSUE TITLE
Issue with MotL

### ISSUE THREAD

**Issue by gb1924** [BSData/horus-heresy#2252]
**MotL Restrictions Showing Up Where They Shouldn't**
^. Master of the Legion should be fine per 1K points, app is restricting it.
**To Reproduce**
Place any Master of the Legion into a list in a new force org chart (not an Allied one)
**Expected behavior**
Per 1K points MotL should be fine
<img width="1440" alt="Screenshot 2022-08-24 at 16 23 44" src="https://user-images.githubusercontent.com/16256070/186474822-a8f6a821-033c-450e-a287-054886fee2c5.png">

**Screenshots**
See attached screenshot 

**Device and data (please complete the following information):**
 - BattleScribe version [e.g. 2.03.45]
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by Mayegelt** [comment]
Already fixed for next push
