### ISSUE TITLE
Retinue squad missing on special characters

### ISSUE THREAD

**Issue by clement-lpr** [BSData/horus-heresy#2259]
**Describe the bug**

**To Reproduce**
1. Go to any special character
2. Retinue option is missing

**Expected behavior**
Having access to the retinue for all master of the legion characters.
.

**Device and data (please complete the following information):**
 - OS: android 
 - BattleScribe  v2.03.25.338
 - Release version v16. 1.3

**Comment by UrsinePatriarch** [comment]
Can you show us an example of this happening? Most MotL characters have the option so it'd be most helpful if you let us know who we missed.

**Comment by UrsinePatriarch** [comment]
It's been 6 days with no reply; if user replies after this point, the issue can be re-opened.
