### ISSUE TITLE
Laslock weapon missing from Adsecularis Covenant

### ISSUE THREAD

**Issue by Guardbuddy** [BSData/horus-heresy#226]
It appears that when selecting the weapons for the Adsecularis it is only possible to select heavy chainblades or mitralocks.  Laslocks appear as the default weapon but it can't be clicked upon since there is no button indicating they have the weapon available.

**Comment by Millicant** [comment]
This is working as intended.  The option is "may exchange laslocks for:" and there are two options. You do not need to select "laslocks" anywhere, as that is the default weapon.  

If Laslocks still appears as a selection, please update!  That has been changed and should be working correctly now.
