### ISSUE TITLE
Alpha Legion missing HQs

### ISSUE THREAD

**Issue by Ecoli360** [BSData/horus-heresy#2262]
**Describe the bug*
Alpha Legion specific HQs are missing.

**To Reproduce**
When making a new Alpha Legion army list

**Expected behavior**
Armillus Dynat and Exodus are missing

**Device and data (please complete the following information):**
 - OS: iOS
 - BattleScribe version 2.03.15
 - Release version 16.1.3

**Additional context**

**Comment by Ecoli360** [comment]
![03B56E87-35B8-4E8A-9712-A6418F24D9AF](https://user-images.githubusercontent.com/112111573/186727854-aef8b7df-fabb-427b-8add-f2e8c6a5e48e.png)
![F2BB56D0-B174-4BC6-A933-26C01C6D4D29](https://user-images.githubusercontent.com/112111573/186727863-e1ac2619-08e2-465a-9320-7f9f7c564c7d.png)

**Comment by Ecoli360** [comment]
![A8F1AD13-B04C-4788-8C39-1D35DDA8D944](https://user-images.githubusercontent.com/112111573/186728056-94c02379-72ba-4f13-9719-fd772676edbb.png)
![A10C8616-D03F-4E38-9EF5-21C8082E65D9](https://user-images.githubusercontent.com/112111573/186728063-5a0199b2-bbbf-459b-9a3c-28058e666311.png)
![42F9AF9C-5F69-41CB-9C6F-622FBAC036C5](https://user-images.githubusercontent.com/112111573/186728064-4b8a6a33-e8f6-4366-aa7e-d5d2aefc7aa9.png)

**Comment by Bantheowl** [comment]
Im having the same issue with imperial fists. Sigismund is gone D:

**Comment by UrsinePatriarch** [comment]
The AL file is very WIP for many, many reasons, but Sigismund seems to be working fine on my end.
