### ISSUE TITLE
Feature request - QoL

### ISSUE THREAD

**Issue by Torquejunkie** [BSData/horus-heresy#2264]
I've got a quick quality of life suggestion. When customising a character or terminator squad and you select a combi weapon, is it possible to have all of the options listed (eg. combi plasma, melta, disintegrator etc), rather than selecting a magna or minor combi weapon then going back, clicking on it again to select which type you want?

Thanks.

**Comment by UrsinePatriarch** [comment]
This is possible but is technically a formatting change; I don't disagree, but it does make some implementation odd at times since some Legion-specific wargear will need to be added and configured separately.

We'll take it under consideration for now, but thank you for your feedback.

**Comment by Torquejunkie** [comment]
All good, thanks for having a think about it :)
