### ISSUE TITLE
Thousand Sons - Osiron Contemptor Removed

### ISSUE THREAD

**Issue by Asvaldrz** [BSData/horus-heresy#2273]
Upon updating to 16.1.3 the Contemptor Osiron was removed for the Thousand Sons legion.

Thanks

**Comment by Mayegelt** [comment]
Are you loading in through the dedicated thousand sons catalogue. Or though
the old Legions Astartes one?
If you can select multiple Legions then it's the old one. The roster will
need to be remade.

**Comment by Asvaldrz** [comment]
I double checked creating a new roster.  I'm using the one where you select the legion. Thousand sons are on version 4

**Comment by UrsinePatriarch** [comment]
This is a known issue and has been addressed in #2268 .
