### ISSUE TITLE
Raven Guard LX Wargear

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2290]
**File:** 2022 - LA - Raven Guard.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Here's a quick summary of missing items for the HH2.0 Raven Guard:

* Corvid Jump Pack upgrade for Independent Characters
* Infravisors for Independent Characters, ~~ ~~Mor Deythan Sergeants, or Dark Fury Sergeants~~ ~~ has been updated
* Cameleoline for Independent Characters
~~ ~~* Dedicated Transport options for Mor Deythan (Rhino or Storm Eagle)~~ ~~ Has been updated
* Legion Specific Warlord Traits

**Comment by Chaosmasters** [comment]
Dark Fury Choosers of the Slain also get melta bombs for 10 pts per model… currently costs 0 at the top of the entry… this should be a per model (Chooser) upgrade
