### ISSUE TITLE
Legion Units Gone

### ISSUE THREAD

**Issue by Alphariea** [BSData/horus-heresy#2298]
Battlescribe will not show legion specific units for me to add into my list.
I select Alpha Legion as my legion, but their are no extras their, like the primarch or the learnean terminators.
Does the same if I try other legions aswell.

**Comment by Mayegelt** [comment]
Remake the list. You are likely still using the old catalogue file instead of the dedicated one for your legion.

**Comment by Mayegelt** [comment]
Please reply if my suggestion works then I will close the issue.

**Comment by Alphariea** [comment]
Brilliant yeah that worked thankyou
