### ISSUE TITLE
Assault Squad Sgt

### ISSUE THREAD

**Issue by twizted86** [BSData/horus-heresy#2300]
The updates to the Assault Sgt produces an error when selecting weapons. 

Error says "1 too many selections of Chainsword (maximum 0)". Chainsword can not be deselcted. 

Selecting a pair of lighting Claws then creates the error "1 too many selections from 1) bolt pistol/chainsword options (maximum 1)"

Data was deleted with new update

**Comment by UrsinePatriarch** [comment]
The 2nd error stems from the first; this was a missed constraint on my part and has been fixed.
Thank you for your assistance in finding this.
