### ISSUE TITLE
Centurion - Power/Charnabal Weapon, Vigilator MC Nemesis Bolter

### ISSUE THREAD

**Issue by gkmashi** [BSData/horus-heresy#2302]
Centurion's Power Weapon/Charnabal selections are free, not costing points

Vigilator doesn't get to select a Master-crafted Nemesis Bolter for free

**Comment by UrsinePatriarch** [comment]
It sure seems like all of those are indeed correct, as per the rules and the data; Centurions are supposed to have free PW/CW (they are) and Vigilators are indeed currently getting free MC Nemesis Bolters. If any of this is incorrect, please show screenshots and verify that you've deleted and updated your data.
