### ISSUE TITLE
Nomus Rhy'tan - Rules Missing?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2307]
**File:** 2022 - LA - Salamanders.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Lord Chaplain Nomus Rhy’tan

I dont know if I am wrong but the Keeper of the Keys special rule is not the right one. Also relentless, stubborn and hatred rules are missing. Or did i miss errata?

**Comment by UrsinePatriarch** [comment]
Have you updated your data recently? It certainly seems like he has all of these rules; how is Keeper of the Keys incorrect? 
![image](https://user-images.githubusercontent.com/46959832/188258372-6bce9c2f-3fa3-4e8d-bb6e-065addc14794.png)
![image](https://user-images.githubusercontent.com/46959832/188258376-67f30cac-7fee-47b5-a3aa-38220e077e94.png)
