### ISSUE TITLE
Night Lords - Preysight Implementation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2309]
**File:** 2022 - LA - Night Lords.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Preysight option is missing on several units, for example Contemptor Dreadnoughts and Spartan Assault Tanks. These should be able to get the upgrade, as they are Legiones Astartes (Night Lords) units and any unit with that special rule is eligible for this upgrade

**Comment by Mayegelt** [comment]
Everything done. Though pushing 3 fixes. Sokar Stormbird, Outriders and Spartha Combat Bike units lacked a "Max 1".
