### ISSUE TITLE
Thousand Sons - Achea Force Weapon Implementation

### ISSUE THREAD

**Issue by Countshard** [BSData/horus-heresy#2310]
**Describe the bug**
It's not possibile to give a sergeant of a tactical squad a achea force weapon

**To Reproduce**
in the list of CC weapons for the sergeant is present the power weapon but not the achea force weapon

**Comment by UrsinePatriarch** [comment]
Have you updated your data?
![image](https://user-images.githubusercontent.com/46959832/188242045-10fc1ed9-9a6d-4eca-8f9d-168d571245ff.png)

**Comment by Countshard** [comment]
My bad: I didn't notice I had to select power weapon to choose the type. I thought I would find it in the sergeant menu. thanks!

**Comment by UrsinePatriarch** [comment]
No worries! They're technically replacements for power weapons, so all of those are nested this edition rather than being simple entries.
