### ISSUE TITLE
Bug Reports 2022

### ISSUE THREAD

**Issue by Arkangelmark5** [BSData/horus-heresy#2318]
Recon Sergeant can't take artificer armor
Destroyers missing power lance

Seeker Units have their weapons connected.

To reproduce:
Create a Seeker Unit and replace one of the Kraken Bolters with a Combi-Melta
Add a new Seeker Unit and you'll see it has a Combi-Melta already when it shouldn't.

**Comment by UrsinePatriarch** [comment]
Seeker Units fixed in #2320.
Destroyer lances fixed in next update; Recon Sgt does indeed have the option currently built in the public version. It's not supposed to be free, sure, but are you saying you don't see it?

**Comment by Arkangelmark5** [comment]
Recon Sgt, shouldn't have the option to take Artificer Armor.

**Comment by UrsinePatriarch** [comment]
Oh, silly me; I was looking at Tac Support Squads. Yes, you're correct.
