### ISSUE TITLE
XVIII: Salamanders bugs

### ISSUE THREAD

**Issue by Kardiwargaming** [BSData/horus-heresy#2321]
When choosing combi-weapons for the Firedrakes by clicking the weapon it makes every member take it, not just one

Dragon shield should be 5p per Firedrake model and it is everybody or nobody option for the unit. 

Veteran Squad (I'm not sure if this is the Salamanders file issue or in every file, but Veteran Squad's Charnabal weapons don't cost anything, even though they should

Same applies to Centurion's Charnabal weapons. 

Centurion Armistos is not able to take his Master-crafted heavy weapon options

**Comment by UrsinePatriarch** [comment]
The combi-weapon problem is known, but can you show me what you mean about Dragonscale shields and the Armistos? Both seem to work fine on my end.

**Comment by Mayegelt** [comment]
I can see on live (not sure about pre release) that the default melee weapon isn't selected on firedrakes

**Comment by UrsinePatriarch** [comment]
I've fixed the Dragonscale problem, but I still don't see what's wrong with Armistos.
![image](https://user-images.githubusercontent.com/46959832/188599691-2dc680ab-1b1a-4cf1-a95c-10288a916eb8.png)

**Comment by Mayegelt** [comment]
Well the picture there says it's twin linked in the middle bottom

**Comment by UrsinePatriarch** [comment]
No worries! Just wanted to make sure I wasn't missing anything on Armistos.
Yep, went through Firedrakes and fixed everything; just seems like a bunch of links broke when we moved it to the subcat, so pretty much every constraint and modifier was broken in some way.

**Comment by Kardiwargaming** [comment]
Legion Outrider squadron ranged weapon upgrades seem to be broken, flamer atleast. When you click on the twin-linked flamer for example, it adds a whopping 45 points to the unit cost, when it should be +5 p per model upgraded for example.
