### ISSUE TITLE
Bug LA - XX: Alpha Legion v14

### ISSUE THREAD

**Issue by Benymely** [BSData/horus-heresy#2323]
File: 2022 - LA - XX: Alpha Legion v14.catz

BattleScribe version: 2.03.21

Platform: PC

Description: Many standard choices are doubled or tripled

![image](https://user-images.githubusercontent.com/72247272/188583760-34e23f54-e592-409a-8fba-8be64002acf9.png)

**Comment by UrsinePatriarch** [comment]
This is a known bug and will be fixed in the coming days as we reformat the base files; Alpha Legion's data structure is very complex, so we apologize in the meantime.

**Comment by alphalas** [comment]
This SHOULD be fixed as of the newest release; please update data and confirm.
