### ISSUE TITLE
Chain Bayonet Issue on Tactical Marines

### ISSUE THREAD

**Issue by Matterfall** [BSData/horus-heresy#2339]
Whenever attempting to select any Chain Bayonets to Marines with a Bolter, it tells me if I have too many, with the maximum selection being 0

To replicate it, crates a Roster with Alpha Legion, add a squad of Tactical Legionnaires, and add Chain Bayones
![Uploading BE8C6151-D3E2-4E38-86AB-B0FA323C10B2.png…]()

**Comment by crazytobuildmc** [comment]
This also occurs with normal bayonets and the Ultramarines roster, haven't tested it elsewhere though
