### ISSUE TITLE
Ultramarine Fulmentarus has no transport option and no cost for powerfist

### ISSUE THREAD

**Issue by yiliangliu08** [BSData/horus-heresy#2342]
![Screenshot_20220909-072930](https://user-images.githubusercontent.com/9515534/189374223-a2b0328b-7252-49f1-b859-80034fcd7df9.jpg)
![Screenshot_20220909-072947](https://user-images.githubusercontent.com/9515534/189374230-d42de5f5-58af-4fcc-9c06-a3c1def60c62.jpg)

**Comment by UrsinePatriarch** [comment]
Addressed and added in next release ~
