### ISSUE TITLE
Night Lords Raptor squad Huntsmaster

### ISSUE THREAD

**Issue by Sjoson** [BSData/horus-heresy#2345]
**Describe the bug**
Missing options for close combat weapons for Night Lords Raptor huntsmaster. Can´t choose any. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - BattleScribe version [e.g. 2.03.45]
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by vonryszardo** [comment]
Can check this.

**Comment by Sjoson** [comment]
Thx, Quick repons
________________________________

**Comment by UrsinePatriarch** [comment]
The implementation isn't yet uniform as in other units, but the options sure seem to be there as it stands.
![image](https://user-images.githubusercontent.com/46959832/189478224-5fd4ab28-ddd6-40a3-b411-918635813d7e.png)

**Comment by Sjoson** [comment]
Hi. I cant take the Headmans Axe on the Huntsmaster still.



Skickat från min Galaxy



-------- Originalmeddelande --------
Från: Nikola Beo ***@***.***>
Datum: 2022-09-10 11:55 (GMT+01:00)
Till: BSData/horus-heresy ***@***.***>
Kopia: Sjoson ***@***.***>, Author ***@***.***>
Ämne: Re: [BSData/horus-heresy] Night Lords Raptor squad Huntsmaster (Issue #2345)


The implementation isn't yet uniform as in other units, but the options sure seem to be there as it stands.
[image]<https://user-images.githubusercontent.com/46959832/189478224-5fd4ab28-ddd6-40a3-b411-918635813d7e.png>

**Comment by UrsinePatriarch** [comment]
That is indeed an oversight on the maintainer's part because it's not listed directly in the unit profile; thank you for catching this and we'll have it fixed in the next update :)

**Comment by Sjoson** [comment]
Hi. Yes is a legion spec upgrade and not in the Raptors entry.  Thx for Quick response



Skickat från min Galaxy



-------- Originalmeddelande --------
Från: Nikola Beo ***@***.***>
Datum: 2022-09-10 13:49 (GMT+01:00)
Till: BSData/horus-heresy ***@***.***>
Kopia: Sjoson ***@***.***>, Author ***@***.***>
Ämne: Re: [BSData/horus-heresy] Night Lords Raptor squad Huntsmaster (Issue #2345)


That is indeed an oversight on the maintainer's part because it's not listed directly in the unit profile; thank you for catching this and we'll have it fixed in the next update :)
