### ISSUE TITLE
Deligatus missing in force without praetor/termy praetor when roster has one

### ISSUE THREAD

**Issue by Andrewtheh** [BSData/horus-heresy#2353]
**Describe the bug**
Centurion consul list missing Delegatus option, pg 108 Astarte books.

**To Reproduce**
1. Go to centurion
2. Click on consul
3. Delegatus option missing.

**Device and data (please complete the following information):**
 Andriod

**Comment by alphalas** [comment]
Assuming this is duplicate #2340

**Comment by UrsinePatriarch** [comment]
There's actually a good chance they have a Praetor selected, which disallows Delegatii, so not duplicate but misunderstanding rules.

**Comment by Andrewtheh** [comment]
I only have a centurion for that allied detachment. I have a praetor in the main detacent legion. I also have less than 700 points in the allied det.

**Comment by UrsinePatriarch** [comment]
Wish you'd included all of these details before, but yes, this can be fixed; in the future, providing these kinds of specifics up front will help us to solve the issue more effectively ~
This is now fixed for the next release.

**Comment by Andrewtheh** [comment]
Im sorry. This was my first time.
