### ISSUE TITLE
Bayonets throw up an error when taken on Tactical Squads

### ISSUE THREAD

**Issue by Cryorm** [BSData/horus-heresy#2354]
**Describe the bug**
A Legion Tactical Squad throws up an error (Tactical Squad has x too many selections from 1.5 Any model with a bolter may take: (maximum 0)

**To Reproduce**
1. Go to Legion Tactical Squad
2. Add a bayonet or a chain bayonet
3. See error

**Expected behavior**
Allowed to take an amount of bayonets equal to number of bolters in the squad

**Device and data (please complete the following information):**
 - OS: Android
 - BattleScribe version: Most Recent
 - Release version 16.1.16

**Comment by alphalas** [comment]
Duplicate #2339
