### ISSUE TITLE
Bug: Armillus Dynat 

### ISSUE THREAD

**Issue by Zithaska** [BSData/horus-heresy#2361]
**Describe the bug**
Armillus Dynat in the Alpha Legion cat does not have a cost (185 pts). His artifice armor is also selectable. 

**To Reproduce**
1. Go to Armillus Dynat in Alpha Legion cat and add as an HQ choice
2. Open and view wargear

**Expected behavior**
Cost should be 185, Artifice Armor should be preset wargear

**Device and data (please complete the following information):**
 - OS: Android 
 - BattleScribe version 2.03.45
 - Release version v16.1.6

**Additional context**

**Comment by UrsinePatriarch** [comment]
All set now; look for this in the next release and thanks for noticing this ~
