### ISSUE TITLE
Alpha Legion Lernaean Terminator incorrect costs

### ISSUE THREAD

**Issue by MaineQat** [BSData/horus-heresy#2366]
**Describe the bug**

* Harrower Chain Fist and Power Fist have no cost, should be same as regular Lernaean
* "Heavy Weapon Lernaean" cost for Power Axe and Power Fist are swapped
* All non-"Heavy" options have a numerical option for Volkite Charger, which defaults to 0 and can be set to any number.  These models should have exactly 1 Volkite Charger, as it is a default and non-swappable weapon (since the Heavy entry exists).

**Device and data (please complete the following information):**
 - OS: macOS
 - BattleScribe version 2.03.21
 - Release version v16.1.6

**Comment by UrsinePatriarch** [comment]
Should be all set in next release; thanks for pointing this out ~
