### ISSUE TITLE
HH2 Space Wolves æther rune armour missing

### ISSUE THREAD

**Issue by Camyron** [BSData/horus-heresy#2367]
The option to take Æther-rune armour is missing. "Any model with both the _Legiones Astartes (Space Wolves)_ and _Independent Character_ Special rules that does not have the _Unique Unit_ Sub-type may exchange _artificer armour_ for _Æther-rune armour_ for +25 points each."

Æther-rune armour gives a +2 armour save, increases Wounds by +1, and gives _Adamantium Will (4+)_

I can't find it on Consuls nor Praetors. I also can't find it on Geigor Fell-hand, but as a named character I can't remember if he's allowed to take it.

**Comment by UrsinePatriarch** [comment]
Geigor can't take it cause he's unique, mate.
As for the others, this hadn't been implemented yet, but it has now, so this'll be available in the next release.
