### ISSUE TITLE
HH2 Space Wolves named MoTL retinues, Legion-specific Deathsworn Retinue.

### ISSUE THREAD

**Issue by Camyron** [BSData/horus-heresy#2368]
Geigor Fell-Hand and Hvral Redblade's data entries don't include the option for the Retinue that they are able to take as Master of The Legion. Additionally, two of the Space Wolf specific consul choices (Caster of Runes and Speaker of the Dead, but NOT Pack Thegn) should each be able to take a unit of Deathsworn as a retinue squad, which is also currently missing.

**Comment by UrsinePatriarch** [comment]
Took a bit of doing, but this has now been fixed and will be available in the next release ~
