### ISSUE TITLE
Veteran Sargent Upgrades

### ISSUE THREAD

**Issue by Lukemon97** [BSData/horus-heresy#2379]
Hi I use android and on my battlescribe when I click on veteran squads, and then click on veteran Sergeant, I don't have the option to give my Sergeant a metabomb.  
Was just wondering if this was a bug or was forgotten 🤔 
![inbound3986423695918476121](https://user-images.githubusercontent.com/113340422/189609465-40cf7ae4-b3b4-475b-9800-d77b4fac918c.jpg)

**Comment by UrsinePatriarch** [comment]
This does seem to be missing!
Veteran Squads are in decent need of a full overhaul, so this'll likely be added in as we do that, whether it be this next Wednesday release or the week after; either way, thanks for noticing this ~
