### ISSUE TITLE
Primarch Warlord Default Implementation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2380]
**File:** 2022 - LA - White Scars.catz

**BattleScribe version:** 1.11.11

**Platform:** Windows

**Dropbox:** No

**Description:** Jaghatai Khan isn't being given Warlord by default. Don't know if other Primarchs have the same issue.

**Comment by vonryszardo** [comment]
Liber Astartes don't that he have to be warlord
<img width="481" alt="image" src="https://user-images.githubusercontent.com/39730954/189662273-bdec6417-3d51-4157-9478-df7124645dbb.png">

**Comment by UrsinePatriarch** [comment]
It's part of the Primarch rule, unfortunately, Vonryszardo; I thought the same.

This'll be fixed in a coming release.
