### ISSUE TITLE
Chain Bayonet Issue #8; now only 10c!

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2383]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** When selecting bayonets/chain bayonets on Tacticals that can, it gives error "Tactical Squad has [x] too many selections from 1,5)Any model with a bolter may take (maximum 0)

**Comment by UrsinePatriarch** [comment]
Duplie #2339
