### ISSUE TITLE
Predator Lacking Pintle Mounted Options

### ISSUE THREAD

**Issue by MaelRH** [BSData/horus-heresy#2384]
The predator should have the option to take pintle mounted weaponry but it isn't presented as an upgrade option in battlescribe. The main thread for updating Battlescribe to HH2.0 lists the predator as complete so I thought I'd mention this.

**Comment by UrsinePatriarch** [comment]
![image](https://user-images.githubusercontent.com/46959832/189784130-7b4d6cc9-1a43-4d16-881a-b97962f6e497.png)
Please make sure your data is updated to the newest release.

**Comment by MaelRH** [comment]
![BS Bug 01](https://user-images.githubusercontent.com/69280029/189785555-12d34eeb-4454-40cc-ba01-8b2d3b063a40.png)

**Comment by UrsinePatriarch** [comment]
Did you delete the data as you updated it? This is often a problem of the app not realizing there's new data.

**Comment by MaelRH** [comment]
Just did that and it worked, thanks. Sorry to essentially waste your time

**Comment by UrsinePatriarch** [comment]
Hey, not a problem!
It's a super common issue just cause of how data works with Battlescribe, but people like you reporting these bugs is how we make things better for everyone, so keep it up 😄
