### ISSUE TITLE
Ultramarines Praetorian Breacher squad options missing and bug

### ISSUE THREAD

**Issue by CaptainIdaho** [BSData/horus-heresy#2386]
Good evening.

The Ultramarines Praetorian Breacher squad doesn't have options to equip squad members with Legatine Axes.

There is also a bug with the Praetorian Primus showing he has too many Bolt Pistols, but the options cannot drop the additional Bolt Pistol. Note when a Plasma Pistol is equipped instead the error message disappears.

**Comment by Mayegelt** [comment]
Max 1 in parent will need shared unticked in data editor to fix.
Hopefully will be updated quickly as easy fix.

**Comment by UrsinePatriarch** [comment]
I'll update these guys; their current formatting is old and I'm surprised this error wasn't reported sooner cause they have a slew of other problems.
