### ISSUE TITLE
Sicaran Arcus lacking point values for some upgrades

### ISSUE THREAD

**Issue by MaelRH** [BSData/horus-heresy#2387]
File: 2022 - Horus Heresy.gstz

BattleScribe version: 2.03.21

Platform: Windows

Dropbox: No

Description: The Sicaran Arcus doesn't have point values for the Helical Targeting Array, Hunter-Killer Missile, or Searchlights

**Comment by UrsinePatriarch** [comment]
Have you updated your data recently? This particular issue was addressed in this weekend's release, I believe.

**Comment by MaelRH** [comment]
Turns out I needed to delete my data before updating, sorry to create a bum thread

**Comment by UrsinePatriarch** [comment]
Like I said in my other reply, please keep posting issues like this; at worst, it's been fixed, right?
At best, though, we have another issue that may be similar to another but needs to be handled differently.
However, in the future, please feel free to drop by the Discord and ask questions about these kinds of things just in case it's ever something simple like this 👍

**Comment by MaelRH** [comment]
Can you link me the discord? I'd be happy to join
