### ISSUE TITLE
IW - Sharpnel bolts should not have shred.

### ISSUE THREAD

**Issue by parkerPWNT** [BSData/horus-heresy#2392]
**Describe the bug**
Shrapnel bolters are listed as having shred. 
They should only have rapid fire and pinning.
No other shrapnel weapons are impacted that I can see.

**To Reproduce**
Select IW.
Add tactical squad.
Add shrapnel bolters.
Select view the roster. 

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version v2.03.21.166
 - Release version 16.1.6

**Additional context**

**Comment by parkerPWNT** [comment]
<HTML><BODY>

Shrapnel Bolter | 18" | 4 | - | Rapid Fire, Shred, Pinning
-- | -- | -- | -- | --


<br class="Apple-interchange-newline"></BODY></HTML>

**Comment by UrsinePatriarch** [comment]
This has been fixed in a recent commit and will be updated in tomorrow's release.
