### ISSUE TITLE
Figured out my problem, can someone link me the discord I've heard mentioned?

### ISSUE THREAD

**Issue by MaelRH** [BSData/horus-heresy#2395]
I was trying to make an Iron Warriors list when I noticed Perturabo was not an option to take. I'm pretty sure I remembered seeing Guilliman for the Ultramarines so I went and checked couldn't find Guilliman either. Did they disappear for some reason? Sorry if this isn't the right place/way to ask but I'm not sure what else I could do. I've been told there was a discord but couldn't find a link to it.

**Comment by MaelRH** [comment]
Nevermind, I just realized I hadn't selected my allegiance for either. 

Still interested in that discord link though.

**Comment by UrsinePatriarch** [comment]
https://www.reddit.com/r/BattleScribe/comments/b4oedy/bsdata_team_is_now_on_discord/

No worries, mate; happens all the time :)
