### ISSUE TITLE
Iron Warrior Dominator Cohort (Exemplary Battles) doesn't have the dedicated transport option it should.

### ISSUE THREAD

**Issue by MaelRH** [BSData/horus-heresy#2396]
The Dominator Cohort should be able to take a Land Raider Proteus Carrier if it has 5 model but the option isn't listed.

**Comment by UrsinePatriarch** [comment]
This is correct! I swear it was present at one point, but it might've been lost in the shuffle.
This'll be live for tonight's release and thank you for your bugtesting :)

**Comment by MaelRH** [comment]
NP, I use the data all the time so helping is easy
