### ISSUE TITLE
Illiastus AC Implementation

### ISSUE THREAD

**Issue by Hamemer** [BSData/horus-heresy#2404]
Aside from the sponsons that are implemented, some other vehicles should have access on them
compile them here for 20 pts ea

FA:
Sabre tanks (hull - front)

HS:
Arquitor (sponsons)

LoW:
Mastodon (front sponsons)

**Comment by UrsinePatriarch** [comment]
Yes, we haven't fully implemented all Legion-specific gear yet, so many options across many Legions are not yet available, unfortunately.

**Comment by Hamemer** [comment]
I understand, just trying make sure the rest isn't left out and went through some tanks
