### ISSUE TITLE
LA - Delegatus Retinue

### ISSUE THREAD

**Issue by Arkangelmark5** [BSData/horus-heresy#2410]
Centurion in Tartaros armor with Delegatus upgrade is missing its retinue.

BattleScribe Mobile
v16. 1.8

**Comment by UrsinePatriarch** [comment]
![image](https://user-images.githubusercontent.com/46959832/190617148-fb03d347-3d8c-4259-8394-16ddfd0c3805.png)
Doesn't seem like it, mate. You sure?

**Comment by Arkangelmark5** [comment]
It's not on mine 
![image](https://user-images.githubusercontent.com/53609638/190651201-69abcd3e-92e4-46c3-9fb7-15d5a7d6cead.png)
