### ISSUE TITLE
Tactical Sargent cannot be equipped with Bayonet

### ISSUE THREAD

**Issue by divercraig** [BSData/horus-heresy#2421]
**Describe the bug**
When configuring a legion tactical squad you have 1 sargent who can be configured + the option to add multiple legionaries in different configurations (including 1 which is bolter, bolt pistol, Bayonet). But there is no option to give the Sargent a Bayonet

**To Reproduce**
1. Add a legionary tactical squad as a troop choice
2. Edit the Squad
3. Click the ... to edit the legionary tactical Sargent
4. Look at the wargear section

**Expected behavior**
Bayonet should be an option for the Sargent as long as they haven't replaced their bolter with another weapon.

**Screenshots**

**Device and data (please complete the following information):**
 - OS: Android
 - BattleScribe version: 2.03.25.338
 - Release version: 16.1.8

**Additional context**

**Comment by alphalas** [comment]
Duplicate #2408, fixed in next release
