### ISSUE TITLE
LA - Dark Angels legacy units implementation

### ISSUE THREAD

**Issue by Hamemer** [BSData/horus-heresy#2424]
Achilles squad currently missing from the HS section

**Comment by revivedtitan** [comment]
Is that a legacy units? I'm not familiar with the Achilles squad

**Comment by Hamemer** [comment]
https://www.warhammer-community.com/wp-content/uploads/2022/07/iazzsaaE4LtT5jQk.pdf

Pg. 23

**Comment by revivedtitan** [comment]
Ahhh the Legion Land Raider Achilles. Sorry wasn't sure what you meant when you said Achilles squad. That's a liber astartes selection, not dark angels but I will create the data entry tomorrow for the LA catalog.

**Comment by UrsinePatriarch** [comment]
It uh
That exists, mate.
_I_ made that SE; for some reason, DA is missing it in Roots, but it's there in most of the others.
Damn, now I have to see who missed some Roots, apparently.

**Comment by UrsinePatriarch** [comment]
Fixed in #2426 .
