### ISSUE TITLE
New Exemplary Battles Unit - Thousand Sons Numerologist Cabal

### ISSUE THREAD

**Issue by nottsknight** [BSData/horus-heresy#2435]
Apologies if this has already been recorded somewhere, couldn't tell if it had been. Thousand Sons just got a new Exemplary Battles unit - https://www.warhammer-community.com/wp-content/uploads/2022/09/3mVvZrTG9XOWeVxv.pdf

**Comment by UrsinePatriarch** [comment]
This unit has actually already been completed by one of our contributors and will be live for the next release ~
