### ISSUE TITLE
Destroyer Squad DT options missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2439]
**File:** 2022 - LA - Dark Angels.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Destroyer squad transport options are missing, nowhere to select

**Comment by UrsinePatriarch** [comment]
Presuming this is about _Mortalis_ Destroyers because normal Destroyers don't have a DT as far as I can tell.
