### ISSUE TITLE
Blood Angels Legion missing Blade of Perdition

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#245]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** Blood Angels Legion missing Blade of Perdition. Available to Praetors, Centurions and
Consuls who have access to powerfists. It's an Ap 2, Strength User, master crafted and
Special rule Deathfire (successful rolls to would count as 2 wounds each, before saves)

**Comment by Millicant** [comment]
This is also technically a duplicate - it's being worked on.  See #214
