### ISSUE TITLE
SoH Reaver Attack Squad Bolt Pistol swap problem

### ISSUE THREAD

**Issue by SirTainly** [BSData/horus-heresy#2458]
Using v18 of the datafile, when trying to equip a unit of 8 SoH Reavers (7 + Chieftain), I get into a pair of conflicting errors.

If I select exchange a Bolt Pistol for a Hand Flamer, (setting one in the selection box) I see 

"Reaver Attack Squad must have 7 more selections  from Any model in the unit may exchange their bolt pistol for a: (minimum 8)"

if I then modify the Bolt pistol line to have 7, so as to make the total 8, I see

"Reaver Attack Squad has 7 too many selections of Bolt Pistol (maximum 1)"

Something is going loopy here.

**Comment by alphalas** [comment]
likely same answer as the Justarin issue, just sit tight.
