### ISSUE TITLE
SoH Justaerin ranged weapon problems

### ISSUE THREAD

**Issue by SirTainly** [BSData/horus-heresy#2459]
Using v18 and trying to equip a squad of Justaerin, I running into conflicting error messages when trying to add a heavy weapon to the squad.
 
It's not accepting that if I have a squad of 5, then 4 Banestrikes and one Reaper is valid. It's showing "..1 too many selections from one in five may take: (maximum 0)"

If I select 5 Banestrike bolters, then add a Reaper cannon, it says I have too many ranged choices, I can't win! :)

**Comment by alphalas** [comment]
v18 of WHAT? SoH rev on master is v12, the LA file is v51, and GST is v19. if you SoH file is older then v11, just hang on for the next release there's a major refactor coming to bring them in like with TS/TSS/AsM
