### ISSUE TITLE
Alternate Weapons for Assault Destroyers

### ISSUE THREAD

**Issue by FinnyD73** [BSData/horus-heresy#2465]
The points costs for the Hand Flamers and Volkite Serpentias seem to be twice as much as the Army Books are asking for them?
For example, the book says you can replace a pair of bolt pistols for a pair of volkite serpentia for 10 points per model, whereas the app seems to be charging 10 points per pistol

**Comment by UrsinePatriarch** [comment]
This has been fixed in the most current release :)
If you update your data and this persists, please reply here again.

**Comment by FinnyD73** [comment]
I've updated the data and it's still giving me the same problem

**Comment by alphalas** [comment]
The initial bug was fix, but there was an additional bug where the SE of the weapons also had points on them, so it was adding the two together.
