### ISSUE TITLE
Salamander Roster Issues

### ISSUE THREAD

**Issue by andyakins** [BSData/horus-heresy#2477]
**Describe the bug**
I'm playing Salamanders, and these are what I've found in the Salamanders roster. I believe these are all correct, I double checked my books and FAQs.

1. Salamander Master Crafting Weapons should cost +10 points its coming up as free (Lib Astartes, Page 312)
2. All characters should have the Salamander Master Crafting Weapon Option (Lib Astartes, Page 312). I'm not seeing it on the Firedrake Master, Pyroclast Warden.
3. Castra Ferrum Dreadnought Flamestorm Cannon should cost +15 points its coming up as free (Legacies of AoD, page 13)
4. Support Squad Multi-Meltas should be +10 points per model (Lib Astartes, Page 68) - it's coming up as 55 points for a 5 man unit

**Device and data (please complete the following information):**
 - OS: Windows 10 Pro
 - BattleScribe version v2.03.21.166
 - Release version 16.1.9

**Additional context**
Salamanders Roster

**Comment by UrsinePatriarch** [comment]
1-3 are implementation fixes because no one's finished Salamanders yet, but #4 has been completed in a previous commit.
The others should be done for next week's release.
