### ISSUE TITLE
Salamanders Land Raider Proteus Carrier/Explorator doesn't have Dragons Breath flamer hull option

### ISSUE THREAD

**Issue by andyakins** [BSData/horus-heresy#2495]
The Land Raider Proteus Carrier/Explorator , when selecting the optional weapon, it lists Twin-Linked Heavy Flamer. This should be Twin-Linked Heavy Dragon's Breath Flamer for Salamanders (and the corresponding weapon should be correct on the roster, so strength 6 and Dragon's Breath abilities). 

For reference, the Land Raider Spartan and Land Raider Phobos are correct.

**Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version v2.03.21.166
 - Release version Horus Heresy v16.1.10
 - Roster version XVIII: Salamanders v10

**Comment by UrsinePatriarch** [comment]
As an aside, it actually has access to both TLHF and TLDBHF rather than "it should be X instead of Y".
