### ISSUE TITLE
Space Wolves Speaker of the Dead Loadout

### ISSUE THREAD

**Issue by Stubram** [BSData/horus-heresy#2499]
Should have access to frost claw, sword,axe and great frost blade.

**Comment by UrsinePatriarch** [comment]
![image](https://user-images.githubusercontent.com/46959832/196058100-e3626f22-2d16-4401-bfc7-e72318d359e4.png)
To my knowledge, they do, indeed, have access to them currently.

**Comment by Stubram** [comment]
Doh.  Sorry.  Not sure how I missed that.

Keep up the amazing work!

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by UrsinePatriarch** [comment]
Wouldn't be the first time the whole "weapons nested in Power Weapon" thing got confusing, so no worries, mate; you've been a huge help in pointing out all kinds of bugs n whatnot, so I appreciate you, as well ~
