### ISSUE TITLE
Typo in Rites of War Section

### ISSUE THREAD

**Issue by GooseLikesCereal** [BSData/horus-heresy#2524]
**Describe the bug**
The Rite of War "Underworld Assault" has a small typographical error in its name on the selection screen.

**To Reproduce**
1. Open a new Roster
2. Select a Rite of War for the Army List
3. Error is displayed at the bottom of the List in the name of the rite: "Underworld Assault", which is mistakenly spelled as "Underworld **Aaasult**".

**Screenshots**
![image](https://user-images.githubusercontent.com/116656593/197800718-45d37d28-05f6-4212-801c-b88de2a50f7c.png)

**Device and data (please complete the following information):**
 - OS: Windows 11 | 21H2
 - BattleScribe version 2.03.21
 - Release version v22

**Comment by Mayegelt** [comment]
Will be fixed in next release.
