### ISSUE TITLE
Crysos Mortug

### ISSUE THREAD

**Issue by Caprera** [BSData/horus-heresy#2528]
Missing Character
Grysos Mortug is missing from Death Guard selection window after choosing "loyalist" as Allegiance.

**To Reproduce**
1. Create new Death Guard Roster
2. Click on Loyalist from allegiances
3. Switch to roster window
4. See Crysos Mortug is missing from characters

**Device and data**
 - OS: Win
 - BattleScribe version 2.03.21
 - Release version v.16.1.10

**Comment by Mayegelt** [comment]
This is already fixed. Just needs to go live in next release.
