### ISSUE TITLE
Legiones Astartes Centurion equipment issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2534]
**File:** 2022 - Legiones Astartes.catz

**BattleScribe version:** 1.11.11

**Platform:** Android

**Dropbox:** No

**Description:** Thunder hammers on termy Centurion are showing that you can swap for Graviton Crusher  regardless of what legion you select.

**Comment by Mayegelt** [comment]
Checked this, also seems they are having access to chain axes as well.

**Comment by Mayegelt** [comment]
Also looks like librarian and stormseer is lacking the option to swap their combi-bolter for a force weapon.
