### ISSUE TITLE
The Angel's Tears Arch-Erelim Weapons Points

### ISSUE THREAD

**Issue by Jonathan-Blazeby** [BSData/horus-heresy#2561]
The Angel's Tears Arch-Erelim (sergeant equivalent) doesn't have any points changes attached to taking a power weapon (+10pts) or a perdition weapon (+15pts).

**Comment by Mayegelt** [comment]
Fixing that, also noticed that Heavy Chainswords were not the correct 2pts each.

Also made the weapon selections easier on Crimson Paladins, Dawnbreaker and Angel Tear characters.
