### ISSUE TITLE
Drop Pod Assault - Tactical Support & Heavy Support Squads

### ISSUE THREAD

**Issue by chronocobra** [BSData/horus-heresy#2567]
Tactical Support & Heavy Support Squads include Drop Pods when calculating total points costs for weapon selections.

i.e. Selecting Rotor Canons for a 5 man Tactical Support Squad should cost 25pts but when a Drop Pod is selected for the squad it costs 30pts (Registering the Drop Pod as a 6th member of the squad).

**Comment by Mayegelt** [comment]
Will get this one fixed in next push
