### ISSUE TITLE
Alpha Legion - Pride of the Legion bug

### ISSUE THREAD

**Issue by DedusJovus** [BSData/horus-heresy#2580]
**Describe the bug**
When making a list for Alpha Legion, when I select Pride of the Legion RoW, in the troops section there are also Deathshroud Terminators listed as an option, regardless of which Rewards of Treachery option I select.

![~BS2](https://user-images.githubusercontent.com/26274301/200782992-ae4801fd-dc35-4709-9bff-b1d852b3c039.PNG)

![~BS1](https://user-images.githubusercontent.com/26274301/200782901-a0831e07-e321-4e63-8d3d-e6581519d191.PNG)

**Comment by Mayegelt** [comment]
fixed in next release
