### ISSUE TITLE
Word bearers diabolist roster error

### ISSUE THREAD

**Issue by mooftak** [BSData/horus-heresy#2597]
Is it intended that when selecting a diabolist centurion for word bearers that you get an error that it cannot have any selections of psychic discipline diabolist (hidden)? On desktop I can delete a subitem in the list view to remove the error, but there's no obvious fix on Android.
Heresy data version 16.3.0
Android client version 2.03.25.338

**Comment by Mayegelt** [comment]
Looks like a tick box for hidden is wrongly ticked inside of Diabolist
