### ISSUE TITLE
Assault Marine Sergeant- no dual Lightning Claw

### ISSUE THREAD

**Issue by Stubram** [BSData/horus-heresy#2598]
As above.  No option to have dual Lightning Claws for 15pts

**Comment by Mayegelt** [comment]
Yes there is.

![Screenshot_2022-11-14-07-14-48-570_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/20280410/201597716-d44371b7-3e44-44f7-a204-2c47f376e38d.jpg)

**Comment by Stubram** [comment]
Oh ok.  Normally it’s a separate option, but that works.  Cheers for clarity

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
