### ISSUE TITLE
Rapier units menu

### ISSUE THREAD

**Issue by Caprera** [BSData/horus-heresy#2600]
I'm a big Rapiers fan but really bothers me to add those pistols and bolters every time I add a new gun. 

Would be great to have it removed altogether.

At least, if  it's needed to be shown that the marines have those guns, to make it added along the main gun. 

Thank you!

**Comment by UrsinePatriarch** [comment]
Removing it isn't an option, unfortunately, mate; RAW, all of those pistols/bolters are swappable.
I can make it an addition, though, like "1x normal Rapier" and "1x Legion-wargear rapier."
