### ISSUE TITLE
Heart of the Legion rule question

### ISSUE THREAD

**Issue by DedusJovus** [BSData/horus-heresy#2606]
Why do Veterans and both Terminator variants have the Heart of the Legion rule? Is it an error or am I missing something? Because, AFAICS, they don't have that rule in the books

**Comment by nstephenh** [comment]
My guess is it's supposed to be hidden unless they have pride of the legion?

**Comment by DedusJovus** [comment]
Does it give them that at all, tho?

**Comment by alphalas** [comment]
it's Stone Gauntlet, not PoTL that gives it

**Comment by alphalas** [comment]
and Broken Vow
