### ISSUE TITLE
Fulmentaris Issues

### ISSUE THREAD

**Issue by Valgaav2** [BSData/horus-heresy#2608]
Ultramarines have no Fulmentaris in their Allied Detachment options, and for some reason have them twice - Elites, where they belong, and Troops - in their Crusade Detachment options.
![Fulmen1](https://user-images.githubusercontent.com/83484778/202559354-71b333a2-f21d-4998-b32a-0554797f7bd2.png)
![Fulmen2](https://user-images.githubusercontent.com/83484778/202559355-17b0137d-6510-488c-8c1e-99eb14b73634.png)

**Comment by Mayegelt** [comment]
Probably a "Force" need changing to 'Roster" in the root
