### ISSUE TITLE
Word Bearer Unique Unit

### ISSUE THREAD

**Issue by Drlove42** [BSData/horus-heresy#2612]
Morning.

Appreciate all the effort that the creators are doing.

The Word Bearer selection includes Ashen Circle, but does not include Gal Vorbak (as far as i can see)

**Comment by reilly-cuauhtemoc-8178** [comment]
Do you have Loyalist selected? Gal Vorbak are Traitor-locked, which might be why.

**Comment by Mayegelt** [comment]
They are there I'd traitor selected 

![Screenshot_2022-11-23-15-36-48-800_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/20280410/203587261-7f8b2b0d-0d96-4712-b8db-23a08c9ec9e5.jpg)
