### ISSUE TITLE
Alpha Legion - Saboteur is missing 5pt Nemesis Bolter Upgrade

### ISSUE THREAD

**Issue by ddarz** [BSData/horus-heresy#2615]
Hi :)
Submitting a bug report for the Alpha Legion catalogue, in case it hasn't been noticed yet

In the Liber Hereticus book (p335), the Alpha Legion Saboteur Consul upgrade gets the option to select Nemesis Bolter for 5pts
Essentially a discount on the 10pts Nemesis Bolter that all the centurions can get

In the current version of the catalogue, the 10pt option exists, but the discounted one does not

Steps to reproduce:

- Make a new Alpha Legion list
- Add a centurion, apply the Saboteur upgrade
- Options do not include the 5pt Nemesis Bolter Upgrade

I hope this helps!

OS: Windows
Battlescribe version: v2.03.21.166
Release version: 16.3.0

**Comment by chronocobra** [comment]
![7bfdca3187850b6fb63aae4c4765494c](https://user-images.githubusercontent.com/73602615/203864224-c75198c9-07e3-4ad4-bd93-a4d5bc07c8fd.png)

Works for me, check again but look where it is highlighted orange in this picture.

**Comment by ddarz** [comment]
Ah I see!
It adds the option one level up on the centurion entry, not the saboteur entry with the rest of the gear.
Thank you for the clarification :)

**Comment by chronocobra** [comment]
No problem, might want to close the issue since this has been solved.

**Comment by ddarz** [comment]
Apologies, GitHub UI got the better of me
