### ISSUE TITLE
Iron hands Tactical support squad can’t select grav weapons 

### ISSUE THREAD

**Issue by Driscal** [BSData/horus-heresy#2620]
**Describe the bug*
with the head of Gorgon rite of war infantry should be able to swap their flamers for grav shredders or grav guns

**To Reproduce**
1. Select “head of the Gorgon” rite of war
2. Add tactical support squad
3. Change squadron weapon option from flamer 

**Expected behavior**

1. Select “head of the Gorgon” rite of war
2. Add tactical support squad
3. Change squadron weapon option from flamer to grav gun/ shredder

**Device and data (please complete the following information):**
 - OS: iOS
 - BattleScribe version [e.g. 2.03.15.

**Comment by Mayegelt** [comment]
Still not complete. I think only ones done ATM is a couple of DA ones, both the WS ones and all universal ones.

![IMG_20221126_111636](https://user-images.githubusercontent.com/20280410/204085969-83f2b06a-22f9-4490-930b-e101b5ccc8f7.jpg)

**Comment by Driscal** [comment]
Ah k, thanks. Was not aware. RegardsRyan ***@***.*** 26 Nov 2022, at 10:17 pm, Mayegelt ***@***.***> wrote:﻿
Still not complete. I think only ones done ATM is a couple of DA ones, both the WS ones and all universal ones.
