### ISSUE TITLE
Death Guard HHv2 alchem cannon and deathshroud and (grave wardens in Creeping Death)

### ISSUE THREAD

**Issue by Morturg** [BSData/horus-heresy#2621]
**Describe the bug**

Deathshroud Terminators are inexplicably selectable as Troops (regardless of RoW)

Castra-Ferrum Dreadnoughts, also under DG, have no option to upgrade their Flamestorm Cannon to an Alchem Cannon (when it's selectable for any Flamestorm Cannon)

under Creeping Death RoW, Grave Wardens are supposed to be able to be taken as Troops, they are not able to

windows

**Comment by Morturg** [comment]
FYI, I just loaded this in, and the castra ferrum isn't fixed (exchanging flamestorm cannon for alchem cannon)

**Comment by alphalas** [comment]
it was on weapon 2 but not weapon one. will be fixed in next commit.
