### ISSUE TITLE
Lions Retinue options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2626]
**File:** 2022 - LA - Dark Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** The Lion is unable to take Deathwing Companion Detachment (or any retinue), despite having the Master of the Legion keyword.

**Comment by Mayegelt** [comment]
Should be being fixed in next pull I think.
