### ISSUE TITLE
IH Contemptors are able to select graviton shredders but should not be able to

### ISSUE THREAD

**Issue by Idunnoguy** [BSData/horus-heresy#2630]
**Describe the bug**
Only Iron Hands Infantry are able to swap graviton guns for graviton shredders. And contemptors are not infantry. But battlescribe incorrectly lets you select graviton shredders

**Device and data (please complete the following information):**
 - OS: Android
 - BattleScribe version 2.03.25
 - Release version v16.3.0

**Comment by Mayegelt** [comment]
Should be able to fix on the next sweep though. Probably me being over zelous when I was fixing a lot of stuff and misreading.
