### ISSUE TITLE
New Explarary Battles units (Alpha Legin and Salamanders)

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2636]
**File:** 2022 - Horus Heresy.gstz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Alpha Legion and Salamanders got units. Hadn't got release recently. Updated files today.

https://www.warhammer-community.com/wp-content/uploads/2022/11/tY1xCtj3G3KDp1KS.pdf

**Comment by Mayegelt** [comment]
Fixed in release [v16.4.0](https://github.com/BSData/horus-heresy/releases/tag/v16.4.0)
