### ISSUE TITLE
Road mapping out Loyalist RoWs (don't want to lose ideas)

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#2638]
A few notes I have are... And I'll try to do all GST and LA in 1 swipe, then the individual legions.

SW RoW only need to edit SW and GST (modifier to 1 unit and a Heavy Support limitation)

IH - Company of Bitter Iron. Root for Immortals as troops, and when troops they get Line and Heart of the Legion. All the units with Bitter Duty get Hatred Traitors (so need LA access). All independent Characters (so praetors, centurions) can be given Bitter Duty if they want it.
Must be loyalist (so need GST edit) 
No Ferrus.

IH - The Head of the Gorgon. Infantry get Stubborn in their own deployment zone. This can be added to infanty in GST with a name change for Stubborn (In own Deployment Zone) rename. Also needs all infantry with flamers to have option of graviton guns or graviton shredders (This one needs access to LA and IH, and has been asked for a lot).
Castellax as elites and they gain IWND (5+) which will need modding in Mech, unless I already did it. 
Ironfather and tech marines get cortex controllers for pts
All Vehicles get Outflank (can add in GST)
Limit 1 Fast Attack choice (GST)

UM - The Logos Lectora. Compulsory HQ of either MoS or Damocles Rhino (add selection entry to both in LA with min/max1, and min in force set to 0, modified to 1 if RoW is taken).
Add +1 max HQ & +1 min compulsory HQ & +1 compulsory Troops in GST for RoW
Hide Drop Pods and Termites.

Sal - Covenant of Fire. 
Pyroclast with dragonbreath flamers get line and are compulsory troops. Sal cat.
Tact support with dragon flamers also get line (but not compulsory). Need LA file change.
Predators with Dragons breath cannon and dragons breath heavy flamers only become troops. Might be best to make a new limited version of predators in Sal file. Could do the same for the tact support squad above.
Hide Drop Pods, both types of destroyers and Moritat. Requires Sal and LA changes.

Sal - The Awakening Fire
Option to give fear (1) to all infantry Salamanders (might be able to add options to the roots in most cases, but not for ones like praetor/centurion who can buy bikes.
Could add rule to GST infantry for RoW to say ignore modifiers to LD for pinning
Give librarian option for Fury psychic powers.
Add +1 HQ choice in GST, but must be Chaplain. Also list must include a chaplain. So add +1 min in force.
Set max jump packs to 0. Hide assault and the jump pack destroyers.
Set max of 1 for all cavalry excluding Apoth and Techmarines. Probably make a category in LA for  outriders, jetbikes, attack bikes. 
Hide Vulkan

RA - Decapitation Strike
Add Preferred Enemy (independent characters) to add unit types. Easy to do in GST
Limit heavy support to 1
No fortifications (also hide them).

RG - Liberation Force.
Max 0 of Slow, Heavy, Artillery, Bombard, Automated Artillery. Hide all units with that, include hide option for boarding shield on centurion and praetor. Done over RG, LA and GST
Set min 1 for loyalist
Set max 0 for allied detachment for force (must be primary).
Roster must include Solar or Militia at min 1 as allied

Jon will be doing IF and BA
IF - Stone Guantlet
Phalanx Warders as troops / compulsory and get line and heart of the legion.
Remove compulsory troop from all normal compulsory troops (Assault, Breacher, Despoiler & Tactical)
No drop pods or termites
May only take a max of Elite & FA as it has Troops. Add category in LA with category add if RoW is taken. Did similar to Pride I think. This is also in Templar RoW so can be done together.

IF - Hammerfall Strike Force
Phalanx Warders as troops / compulsory
All Infantry can buy Deepstrike option and gain shrouded 5+ on deepstrike.
No drop pods or termites. 
All vehicles can have reserve only tag.
No fortifications

IF - Templar Assault
Templar Brethren as troops / compulsory troops (root in IF) also gain Line and Heart of the Legion
Rage (2) (turn they disembark) might need adding to Brethren as well.
Remove compulsory troop from all normal compulsory troops (Assault, Breacher, Despoiler & Tactical)
Min 1 loyalist in GST.
May only have LA loyalist allies (no Custodes, mech, Knights, Titans, Sisters, Solar...)
May only take a max of Elite & FA as it has Troops. Add category in LA with category add if RoW is taken. Did similar to Pride I think 

BA - Day of Rev needs to play with LA file for Jump packs on Compulory HQ, then hide all fortifications, tarantula & termites

BA - Day of sorrows requires a bit of BA root access to make Crimson Paladins into troops.
Hide drop pods and termites as you can't use reserves.
Also access to GST to give Infantry a rule to make them have stubborn near objectives and if they already have stubborn they get fearless. And Heart of the Legion and Hatred (Everything) when under 50% (Though both of those changes can be left out as they are situational on the RoW rather than constant).

**Comment by Toreador13** [comment]
I am working with SW, NL and RG. SW should be done. NL is close to done. 
NL Swift blade has some interesting HQ requirements. 
Terror Assault needs Fear(1) added to all characters in it. 
RG Liberation Force requires some checks for an allied detachment of Solar Auxilia and 4 units. 
Everything else for those RoW should be complete.

**Comment by Mayegelt** [comment]
> I am working with SW, NL and RG. SW should be done. NL is close to done. NL Swift blade has some interesting HQ requirements. Terror Assault needs Fear(1) added to all characters in it. RG Liberation Force requires some checks for an allied detachment of Solar Auxilia and 4 units. Everything else for those legion RoWs should be complete.

Is that a request for help on a way to do the remaining things, or just saying they are left to do?

**Comment by Morturg** [comment]
Pride of Legion, PoL need all the legion specific terminators selectable as Elites as Troops, when selected

**Comment by Mayegelt** [comment]
> Pride of Legion, PoL need all the legion specific terminators selectable as Elites as Troops, when selected

I think that is already done. And I think released

**Comment by Morturg** [comment]
ah, then it doesn't work :D

**Comment by Mayegelt** [comment]
> ah, then it doesn't work :D currently, but that could be due to the release being older than the corrections 🤷

Which one isn't working?

**Comment by Mayegelt** [comment]
![Screenshot_2022-12-15-08-52-49-120_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/20280410/207815275-1479f7ad-f60d-4325-819b-73461cbef8c2.jpg)

Example of EC working

**Comment by Morturg** [comment]
I stand corrected, I have just redownloaded files, I must have edited a catalogue myself

the thing I was seeing was that the elite Deathshroud was fully selectable without a ROW as troops, but that was fixed in

https://github.com/BSData/horus-heresy/issues/2621

which hasn't been released yet

my confusion 👎 

all good
