### ISSUE TITLE
Allied Detachments Unable to take Legacies/Exmplary Units

### ISSUE THREAD

**Issue by Srlojohn** [BSData/horus-heresy#2648]
I was working on an Ultramarine allied detachment, but there is no option to add these units, nor does the stock list include the units therein. I am unsure if this a purely UM problem, or all legions.

**Comment by alphalas** [comment]
The selector is only available in a main detachment
Basically you cannot unlock them unless you have a main detachment with the selector because you technically can't take an allied detachment without a main detachment.

**Comment by Srlojohn** [comment]
> The selector is only available in a main detachment Basically you cannot unlock them unless you have a main detachment with the selector because you technically can't take an allied detachment without a main detachment.

I am aware, the issue is that I have the main detachment with the selector, but it still does not appear.
![UM_issues](https://user-images.githubusercontent.com/92633652/206933389-062bfcc2-b187-43ae-aa41-c7dc67dbf53c.png)
The main detachment, WE has the selector (red), but the UM list of Elites is missing it's non-Liber units, such as Fulmentaris Terminators or the Nemesis Destroyer Squad.

**Comment by Mayegelt** [comment]
![Screenshot_2022-12-12-10-57-58-622_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/20280410/207028620-b207db9d-9908-427a-9f20-fc8fa1386ffa.jpg)

Seems to be working for me. Though might be that it's not on live but on pre-release
