### ISSUE TITLE
Death Guard Catalogue , The Reaping RoW

### ISSUE THREAD

**Issue by Morturg** [BSData/horus-heresy#2651]
**Describe the bug**
when The Reaping is selected, 
- Legion Veteran Squads are not selectable as Troops
- Legion Heavy Support Squads are not selectable as Troops (non-compulsory)
- Characters Are not able to equip rad-grenades for 10pts (all character sub-types inc sergeants)

**Comment by Mayegelt** [comment]
Fixed in release [v16.4.0](https://github.com/BSData/horus-heresy/releases/tag/v16.4.0)
