### ISSUE TITLE
Kharybdis unavailable as Leviathan DT

### ISSUE THREAD

**Issue by WetworkSicknote** [BSData/horus-heresy#2660]
**Describe the bug**
In the Leviathan Dreadnought Talon entry, a single-Dreadnought Talon should be able to select a Kharybdis Assault Claw as a Dedicated Transport but can't currently. 

**To Reproduce**
(select Leviathan Talon; only DT option is Dreadnought Drop Pod) 

**Expected behavior**
Should see Kharybdis alongside Dreadnought Drop Pod as DT option

**Screenshots**

**Device and data (please complete the following information):**
 - OS: Android 13
 - BattleScribe version v2.03.25.338
 - Release version 16.3.0

**Additional context**

**Comment by Mayegelt** [comment]
Fixed in release [v16.4.0](https://github.com/BSData/horus-heresy/releases/tag/v16.4.0)
