### ISSUE TITLE
Word Bearers - Dark Channelling

### ISSUE THREAD

**Issue by chronocobra** [BSData/horus-heresy#2665]
I am 99% sure Independant Characters (Infantry so not on Jet Bikes) should be able to select Dark Channelling as an upgrade due to them technically being their own units before being deployed.

If this is not the case then feel free to ignore.

**Comment by Mayegelt** [comment]
Yes they should

**Comment by Mayegelt** [comment]
Fixed in release [v16.4.0](https://github.com/BSData/horus-heresy/releases/tag/v16.4.0)
