### ISSUE TITLE
DG catalogue, Leviathans not being able to take heavy alchem flamers

### ISSUE THREAD

**Issue by Morturg** [BSData/horus-heresy#2666]
**Describe the bug**
all flamers are optionally able to swap out for their equivalent alchem -type flamers

the leviathan's hull weapons, do not have the option currently

I'm very sure there are other unit entries where this is also true

**Comment by Mayegelt** [comment]
Fixed in release [v16.4.0](https://github.com/BSData/horus-heresy/releases/tag/v16.4.0)
