### ISSUE TITLE
Anacharis Scoria Not Present in Taghmata

### ISSUE THREAD

**Issue by Guardbuddy** [BSData/horus-heresy#267]
Thanks for the awesome updates!  

Just wanted to say that Anacharis Scoria for some reason does not appear in the default Taghmata list and only shows for Legio Cybernetica.  I understand Ordo Reductor cannot bring him but I believe basic Taghmata can.

**Comment by Millicant** [comment]
Hey thanks for the feedback.

I'm currently seeing him correctly in both Taghmata and Legio Cybernetica lists.  Not sure what the problem is.  Let me know if it persists!
