### ISSUE TITLE
Death Guard RoW

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2672]
**File:** 2022 - Horus Heresy.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Hi - unless I'm being a total muppet, it appears Grave Wardens are missing as elite choices for DG (and also as troops when Creeping Death RoW)

**Comment by chronocobra** [comment]
Grave Wardens are Heavy Support.

They also show up as troops for me when I select the Creeping Death RoW.

If you're using the last Battlescribe download then faction specific RoWs haven't been pushed there yet. If you use the github master it'll work.

**Comment by Mayegelt** [comment]
Fixed in Master, not put out for release yet.

**Comment by Mayegelt** [comment]
Fixed in release [v16.4.0](https://github.com/BSData/horus-heresy/releases/tag/v16.4.0)
