### ISSUE TITLE
Dark Angels: missing Special Issue Ammunition rule for Heavy Support Squad

### ISSUE THREAD

**Issue by VanNostrand** [BSData/horus-heresy#268]
Heavy Support Squad misses the Legion-specific upgrade available with Missile Launchers:
- Stasis Shell (missile) 24" Str 4 AP - Heavy 1, Blast 3", Stasis Anomaly  (+5pts/model) (Book 6 page 267)

Stasis Anomaly: All models in a unit hit by one or more weapons with this specual rule suffers a -1 penalty to their Weapon Skill and Initiative (to a minimum of 1) until the end of the turn.

**Comment by Millicant** [comment]
Nice catch - thanks!
