### ISSUE TITLE
DG catalogue (with new unpublished catz) sergeants Reaping RoW

### ISSUE THREAD

**Issue by Morturg** [BSData/horus-heresy#2681]
**Describe the bug**
using the new unpublished cat, sergeants cannot take Rad Grenades for 10pts in The Reaping 

(all character types should be able to)

**Comment by Mayegelt** [comment]
How long ago did you update?

**Comment by Mayegelt** [comment]
Should be fixed now.

**Comment by Morturg** [comment]
that alone is fixed, though there's one more issue

Mortus Poisoners are not listed as having Rad Grenades (they have them by default, all ROW)

**Comment by Mayegelt** [comment]
> that alone is fixed, though there's one more issue @Mayegelt
> 
> Mortus Poisoners are not listed as having Rad Grenades (they should have them all, everyone, by default, all ROW) and thus their sergeant should not have the option
> 
> which is actually quite cool as a sniper can't stop them from using it

Updated again to fix. Saw they didn't have any of the basic stuff like Frag, Krak, Bolt Pistols as well.
