### ISSUE TITLE
DG catz all reverted, again

### ISSUE THREAD

**Issue by Morturg** [BSData/horus-heresy#2690]
**Describe the bug**
manually using the latest version (which oddly seems to be an older version, as fixes were implemented before, have now been overwritten) 

characters cannot take Rad Grenades, again
Leviathan hull weapons cannot be upgraded to Alchem-cannons
Mortus Poisoners, have no individual equipement, again

**To Reproduce**

using latest DG catz manually

#2666
#2651

both seem to have been reverted to before they were 'done'

**Comment by Mayegelt** [comment]
Can you tell me what version it says you are using of the DG cat?

**Comment by Mayegelt** [comment]
![IMG_20230120_160829](https://user-images.githubusercontent.com/20280410/213747523-e5a70ccb-112d-447e-8a12-1ef82647adf0.jpg)
![Screenshot_2023-01-20-16-08-00-710_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/20280410/213747529-acbf9e12-994a-4d9a-823e-23254ff8c387.jpg)
![Screenshot_2023-01-20-16-07-24-755_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/20280410/213747533-9d854229-72d5-450f-9d32-f779979c12dc.jpg)
