### ISSUE TITLE
Sons of Horus rites of battle don't correct troops choices

### ISSUE THREAD

**Issue by fishking1702** [BSData/horus-heresy#2693]
**Describe the bug**
When you selected the Black Reaving rite of war, the Reaver Assault squad should be the one that is now allowed to be troops, not the Reaver Aggressor squad. Also the Long Walk rite of war says that Tartaros, Cataphractii, and Justaerin squads are supposed to be selectable as non compulsory troops, which they currently can't be selected to do.

**To Reproduce**
To see what I mean, select the rites of war mentioned and go to troops (for the Long Walk they should appear after 2 compulsory troops are selected)
**Expected behavior**
For the Black Reaving, Reaver Assault squads should selectable as troops. For the Long Walk, Tartaros, Cataphractii, and Justaerin should be selectable as troops after 2 normal troops have been selected

**Comment by Mayegelt** [comment]
Currently this is working on pre-release. But not current live  release
