### ISSUE TITLE
Scouts should have Skirmish Unit Type in hover over/pop out

### ISSUE THREAD

**Issue by Morturg** [BSData/horus-heresy#2694]
**Describe the bug**
Scouts don't have Skirmish Unit Type rules displayed on hover over (like Night lords Terror Squad do)

**Expected behavior**
Scouts to have skirmish unit type in hover over

**Comment by Morturg** [comment]
terror squad skirmish rules are descibred
![image](https://user-images.githubusercontent.com/25342188/214470883-4ee0af08-a3af-4984-99db-0e93a18cfdce.png)
scout sqaud rules, are not
![image](https://user-images.githubusercontent.com/25342188/214470938-693a4f4c-1787-42de-ad09-b6d3ec8a34af.png)

**Comment by Morturg** [comment]
![image](https://user-images.githubusercontent.com/25342188/214471036-5a850306-ac21-48d2-8376-dbe37e7ef1c7.png)
scout squad, are not

**Comment by Mayegelt** [comment]
Will be fixed in a moment. Then the expected release is going to go LIVE!
