### ISSUE TITLE
AL Banestrike on independent Char

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2695]
**File:** 2022 - Horus Heresy.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** No option to use the banestrike combi bolter upgrade for Alpha Legion independent characters. I've tested centurions, and praetors and it's missing for both.

**Comment by Mayegelt** [comment]
The options appear to be there for me on latest release.
For praetor and centurion they can upgrade a bolter to banestrike
For praetor or centurion in termy armour they can upgrade their combo bolter to banestrike combi bolter.
Though does seem to be a Pts issue on Tart and Cata centurion upgrades

**Comment by Mayegelt** [comment]
Will be fixed in the next release
