### ISSUE TITLE
Speaker of the dead weapons issue

### ISSUE THREAD

**Issue by sirofsake01** [BSData/horus-heresy#2702]
the Speaker of the dead upgrade comes with a master crafted power as part of the upgrade cost however when selecting the speaker of the dead the only way to add a power maul is to pay an additional power maul

**To Reproduce**
1. Go to '...' space wolf army list
2. Click on '....' centurion
3. Scroll down to '....' upgrade and select speaker of the dead

**Expected behavior**
should get a master crafted power maul as part of the 65 points paid

**Screenshots**

**Device and data (please complete the following information):**
 - OS: [e.g. iOS] andriod
 - BattleScribe version [e.g. 2.03.45]
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by Mayegelt** [comment]
They have already got it.

![IMG_20230127_232619](https://user-images.githubusercontent.com/20280410/215224638-8f50be19-aa66-4d58-a0df-d99abc6a9760.jpg)
![IMG_20230127_232635](https://user-images.githubusercontent.com/20280410/215224643-fbdcd4fe-aea4-4900-98b0-14169624b62d.jpg)
