### ISSUE TITLE
Silent Judge Questora Cadre points for Augury scanner and Nucino Vox

### ISSUE THREAD

**Issue by Komrad33** [BSData/horus-heresy#2705]
**Describe the bug**
When you add a "sister with options" both the scanner and vox should cost 10 pt ea (pg 49 Liber Imperium)

**To Reproduce**
Select Sister with options. 

No points values for Vox and Scanner 

**Expected behavior**
Costing 10 pt ea

**Screenshots**
![image](https://user-images.githubusercontent.com/123283918/215349483-1af39d7d-bb96-4aa8-8399-40dba6c59e7a.png)

**Device and data (please complete the following information):**
 - OS: windows
 - BattleScribe version 2.03.21.166
 - Release version HH v47 ( i think this is what yall are looking for)

**Additional context**
I tried all the other cadres and they all seem to work in every combo of judge, but I may have missed one.

**Comment by Mayegelt** [comment]
Fixed in v16.5.0
