### ISSUE TITLE
Thousand Sons Crimson King issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2706]
**File:** 2022 - LA - Thousand Sons.catz

**BattleScribe version:** 3.21.16

**Platform:** Windows

**Dropbox:** No

**Description:** When utilizing the Guard of the Crimson King RoW, a Praetor upgraded to have a Psychic Discipline is not correctly being identified as fullfilling the requirements for the RoW.

**Comment by Mayegelt** [comment]
Working for me with all 3.
I'll investigate more later.

![Uploading Screenshot_2023-01-30-07-17-35-251_net.battlescribe.mobile.rostereditor.jpg…]()
![Screenshot_2023-01-30-07-18-01-703_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/20280410/215412227-94629b90-3fb1-44f2-9b22-316e2a30dfde.jpg)
![Screenshot_2023-01-30-07-18-25-933_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/20280410/215412233-ab2fa636-7b55-413d-9429-d752fe4a52df.jpg)

**Comment by Mayegelt** [comment]
Very strange logic issue. Was working individually for preators of all forms. But once you put a 2nd one in for no apparant reason it was breaking. Needed to modify the condition to only loot at that Praetor, rather than Parent...

**Comment by Mayegelt** [comment]
Fixed in v16.5.0
