### ISSUE TITLE
RoW and some allied detachment restrictions

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2707]
**File:** 2022 - LA - World Eaters.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The World Eaters' Rite of War “the Crimson Path” has a limitation that reads “A Detachment using this Rite of War may include only a single Heavy Support choice.” however, when this Rite of War is used in an Allied Detachment, this restriction is applied to the Crusade Force Organization Chart.

**Comment by Mayegelt** [comment]
Strange one. Might be a "roster" rather than "force" somewhere

**Comment by Mayegelt** [comment]
As I thought, there was few "Roster" that needed to be changed to "Force". No idea how so many were there, but included things like Terror Assault as well.

**Comment by Mayegelt** [comment]
Fixed in v16.5.0
