### ISSUE TITLE
Dedicated Transports for Dreadnoughts in Drop Pod Assault

### ISSUE THREAD

**Issue by Hfran-Morkai** [BSData/horus-heresy#2724]
**Describe the bug**
In Drop Pod Assault RoW: Casta Ferrum, Contemptor Dreadnoughts and Leviathans are unable to take Dreadclaws and Deredos are unable to take either Dreadclaw or Dreadnought Drop Pod.

**To Reproduce**
1. Go to 'Legion Contemptor Dreadnought/Leviathan Dreadnought/Deredo Dreadnought)'
2. Click on 'Drop Pod'
3. No option for Dreadclaws and Deredo has no option whatsoever.

**Expected behavior**
Each Dreadnought to have the option for Dreadclaw or Dreadnought Drop Pod as a Dedicated Transport.

**Device and data (please complete the following information):**
 - OS: Android
 - BattleScribe version 2.03.25
 - Release version 16.5.0

**Additional context**
Page 98 of Liber Astartes under "Rite of War: Drop Pod Assault- Effects" states: 'When taken as part of a Detachment using this Rite of War, any units composed of models with the Dreadnought Unit Type must be given either Legion Dreadclaw Drop Pods or Legion Dreadnought Drop Pods as Dedicated Transports.' No Dreadnought has native access to Dreadclaw Drop Pods so I believe that both of these options should apply to Contemptors, Leviathans, Deredos and the Casta Ferrum pattern Dreadnoughts as they all comply with the 'Dreadnought Transport' rule.

**Comment by Mayegelt** [comment]
Will be fixed in next release. Also fixed for the BA and UM special dreads as well.
