### ISSUE TITLE
Tsolmon Khan no waifu Silent Sister option

### ISSUE THREAD

**Issue by Tomakokamikaze** [BSData/horus-heresy#2726]
**Describe the bug**
Tsolmon Khan (White Scars Character) is missing the option to take the Sister of Silence as retinue. Probably because thete were no profile for her when his profile was added.

**Comment by Mayegelt** [comment]
Hi ya.
The SoS knight Centura isn't a retinue. It is a non compulsory HQ choice, who may themselves take a retinue.
![IMG_20230216_151936](https://user-images.githubusercontent.com/20280410/219410622-a80f6066-0aca-4d90-8a33-f51515889b33.jpg)
