### ISSUE TITLE
Ultramarines Fulmentarus stats

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2729]
**File:** 2022 - LA - Ultramarines.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes

**Description:** Fulmentarus Terminators are currently have 3 attacks each, should be 2. 

Fulmentarus Decurion currently has leadership 7, should be 8.

**Comment by Mayegelt** [comment]
Will be fixed in the next release
