### ISSUE TITLE
Salamander Jetbike HF Options

### ISSUE THREAD

**Issue by Jonathan-Blazeby** [BSData/horus-heresy#2731]
Salamanders on Scimitar Jetbikes (Sky-Hunter Squadrons, Jetbike Command Squads, and Characters on Jetbikes) need the option made available to swap their built in Heavy Bolters for Dragon's Breath Heavy Flamers as per the Artifice and Flame rule.

**Comment by Mayegelt** [comment]
Fixed for next release. Also did the same for Shrapnel Cannons for IW.
Also included Apoths and Tech Marines as well.
