### ISSUE TITLE
Archmagos Inar Satarael

### ISSUE THREAD

**Issue by Xabre1342** [BSData/horus-heresy#274]
He's in the Taghmata list, but he's also an option for the Legio Cybernetica list.  Can he be ported over?

**Comment by capitaladot** [comment]
Cybernetica is a legacy list. Anything starting with the Red book is in the
Taghmata Army List file.

**Comment by Xabre1342** [comment]
HH Taghmata red book, page 74.  Rules for a Legio Cybernetica battle cohort.

Or am I looking at the lists wrong in the data files?

**Comment by capitaladot** [comment]
The Cybernetica file is the legacy list from Book 1.
The Taghmata Army List (red book) supplants this and replaces it. Select
Cybernetica under Legion to use it in that file.
