### ISSUE TITLE
Agamatus Jetbike Squad - No solerarite Power lance

### ISSUE THREAD

**Issue by Komrad33** [BSData/horus-heresy#2740]
**Describe the bug**
The Lance does not show up on the profile

**To Reproduce**
Add to roster or view, Lance is not present 

**Expected behavior**
Stat block for lance

**Screenshots**
![image](https://user-images.githubusercontent.com/123283918/221739499-f2d1d1ff-4081-45e2-8f42-3b19164c08b5.png)

**Device and data (please complete the following information):**
 - OS: Win 11
 - BattleScribe v2.03.21.166
 - Release version v4

**Additional context**

**Comment by Mayegelt** [comment]
Will be fixed in next push
