### ISSUE TITLE
Custodes

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2742]
**File:** 2022 - LI - Custodes.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Adding a Custodes Tribune to a 3000pts army still shows an error that he can't be added to the army, despite rules saying that he can be played in am army with at least 3000pts.

**Comment by Mayegelt** [comment]
I'll have a look at that today. It used to work I think.

**Comment by Mayegelt** [comment]
Additonally Heteron Guard and Velatari were not working as intended. This will be fixed next push.
