### ISSUE TITLE
Mechanicum, Arcuitor Magisterium - wrong base cost

### ISSUE THREAD

**Issue by Cylindryk** [BSData/horus-heresy#2747]
**Describe the bug**
Base cost is caltulated wrong - while it shows 85 like in book, it somehow count it as 110 - 25point more.

**To Reproduce**
Just add him to roster - it should show 85points used, and yet, it shows 110.

**Comment by Mayegelt** [comment]
The cosy paid is correct.
The reason it shows as 110 per model is that in a court of executioners they cost 110 PTS each. So the easiest way in BS to have the unit tax be -25pts. The numbers do work.

![IMG_20230303_082545](https://user-images.githubusercontent.com/20280410/222669739-40e5c51d-0825-4cc1-8012-380ef72302f4.jpg)
