### ISSUE TITLE
Sister of Silence - wrong BS in 2 units

### ISSUE THREAD

**Issue by Cylindryk** [BSData/horus-heresy#2750]
**Describe the bug**
Expurgator Cadre and Sanctioner Cadre - for both of this unit BattleScribe shows BS3, while in Liber Imperium they have BS4.

**Comment by Cylindryk** [comment]
And actually Sanctioner Cadre shows S4, where should be S3.

**Comment by Mayegelt** [comment]
Will be fixed in next release
