### ISSUE TITLE
Weird issue with removing Dawnbreakers from Dawnbreaker Cohort units

### ISSUE THREAD

**Issue by krobb001** [BSData/horus-heresy#2751]
**Describe the bug**
If you have multiple instances of the unit in a roster, removing options for dawnbreakers (either Dawnbreaker w/ Falling-Star Power Spear or Dawnbreaker w/ Equinox Power Blade Case), it removes the option from all Dawnbreaker Cohorts on the roster

**To Reproduce**
1. Create new Blood Angels HH 2.0 roster (loyalist, likely not relevant)
2. Add 2 or more Dawnbreaker Cohort units
3. Edit one, remove any number of Dawnbreakers
4. Return to roster overview, see that all Dawnbreaker Cohort units have had that many Dawnbreakers removed from the unit

**Expected behavior**
Only Dawnbreakers from the unit I am modifying should be removed if I remove any

**Screenshots**

**Device and data (please complete the following information):**
 - OS: Android
 - BattleScribe version v2.03.25.338
 - Release version v16.5.1

**Additional context**
None

**Comment by Mayegelt** [comment]
Will be fixed in next release.
Found an extra tickbox of "Collective" 1 tier to high was selected, which meant it applied to all copies of the unit, rather than that the individual.
