### ISSUE TITLE
Predator Pintle mounted Multi-Melta cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2754]
**File:** 2022 - Legiones Astartes.catz

**BattleScribe version:** 2.03.21

**Platform:** Mac

**Dropbox:** No

**Description:** Predator Squadron. The pintle mounted Multi-Melta should cost 20 not 30 points.

**Comment by Mayegelt** [comment]
Will need to also check the Salamanders only one

**Comment by Mayegelt** [comment]
Will be fixed in next release.
