### ISSUE TITLE
Primus Medicae missing Needle Pistol

### ISSUE THREAD

**Issue by Cylindryk** [BSData/horus-heresy#2755]
**Describe the bug**
FAQ for both Liber Astartes and Heretics gave Legion Primus Medicae this option:
Replace the second sentence with:
‘A Legion Primus Medicae may exchange a bolt pistol or
combi-bolter with a needle pistol for +5 points, but may
not select two lightning claws, or a boarding shield.’

There is no such option in BS right now (16.6.0)

**Comment by Mayegelt** [comment]
Will be fixed in next release.
