### ISSUE TITLE
Deathshroud Terminator Bodyguard

### ISSUE THREAD

**Issue by Cylindryk** [BSData/horus-heresy#2756]
**Describe the bug**
When selecting "may exchange power scythe for:
legion standard & power weapon * 15pts", in sub-option of power weapon it is option to choose Power Scythe - which shouldn't be here, since Deathshrouds are not characters, and Power Scythe option is "character only".

While they have "chosen warriors", it doesn't mean that they have "character sub-type".

**Comment by Mayegelt** [comment]
Will be fixed next release.
