### ISSUE TITLE
Scimitar Jetbike always have heavy bolter profile even if you change the weapon

### ISSUE THREAD

**Issue by binaryspica** [BSData/horus-heresy#2757]
After the update, I found that my lists' Scimitar Jetbikes are requires a heavy bolter. The problem is, Sky-Hunter Squadron also requires this, despite they can swap the heavy bolter to the other weapon.

**To Reproduce**
1. Just put any unit with Scimitar Jetbike(Sky-Hunter Squadron, a HQ unit with Scimitar Jetbike upgrade.)

**Expected behavior**
1: The option of heavy bolter should be removed fron the Scimitar Jetbike.
2: Else, for Sky-Hunter Squadron, these should be moved for each squad member, and the weapon option is added on the bike, not the individual squad member. For now they are the only unit which is able to change the weapon on the Scimitar Jetbike, so Praetor/Centurion/Command Squad are not need to have a change. But if Command Squad could change the weapon on their Scimitar Jetbike, then they should have it individually as well.

**Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version 2.03.21.
 - Release version 16.6.0

**Comment by Mayegelt** [comment]
Yeah this was part highlighted due to Salamanders and iron Warriors being able to swap their loadout to legion specific ones on things like command squads, characters, tech marines and apothecaries.
Did a bit of a half job to get it sorted. Might need to revisit it.
