### ISSUE TITLE
Techmarine Upgrades incorrect

### ISSUE THREAD

**Issue by Idunnoguy** [BSData/horus-heresy#2759]
**Describe the bug**
The techmarine upgrades for an augury scanner, cognis-signum, cyber-familiar, meltabombs, and nuncio vox are all incorrect. The rules state that "Any Legion Techmarine may take one of the following:" meaning that a techmarine cannot have both a cognis-signum and an augury scanner for example. However the data lets you take both.

**Device and data (please complete the following information):**
 - OS: Android
 - BattleScribe version v2.03.25
 - Release version v16.6.0

**Comment by Mayegelt** [comment]
Fixed in next release.
