### ISSUE TITLE
The Logos Lectora Rite of War

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2760]
**File:** 2022 - Horus Heresy.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When using The Logos Lectora Rite of War for Ultramarines, the error message when the required consul is not selected reads ‘Master of Sigil’ rather than ‘Master of Signals’.

**Comment by Mayegelt** [comment]
Will be fixed next release.
