### ISSUE TITLE
master of Signals - wrong description

### ISSUE THREAD

**Issue by Cylindryk** [BSData/horus-heresy#2764]
**Describe the bug**
MoS have wrong descriptions in 2 places:
Vox Array (it has description from Liber instead from FAQ, where it was changed)
Strategic Comms (where there is description of Vox Array instead of Strategic Comms).

![obraz](https://user-images.githubusercontent.com/51954441/224914884-ec022b40-d303-4e8c-9b7b-9ede77264cc4.png)
![obraz](https://user-images.githubusercontent.com/51954441/224914925-cd3fb6b9-94de-4f84-836e-3123e07b7311.png)
![obraz](https://user-images.githubusercontent.com/51954441/224914959-6d7d2b21-a24c-445d-ae4b-e9a06c4f8a92.png)
![obraz](https://user-images.githubusercontent.com/51954441/224914983-065f237e-ae6b-4324-b0d8-b8df359cece9.png)

**Comment by Mayegelt** [comment]
Should be fixed next release
