### ISSUE TITLE
DA - Steel Fist RoW dedicated transports

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2768]
**File:** 2022 - LA - Dark Angels.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Using the steel fist right of war, there is an error when a tactical squad of more than 10 is given a land raider spartan as a dedicated transport

**Comment by Mayegelt** [comment]
Same happened on multiple units it seemed when taking dedicated transports.
Should be fixed next update.
