### ISSUE TITLE
primus nullificator consul choice missing upgrades

### ISSUE THREAD

**Issue by Outrider5** [BSData/horus-heresy#2770]
**Describe the bug**
no option to add athershock maul or any specific weapons after choosing consul choice. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - OS: [e.g. iOS] PC, windows 11 
 - BattleScribe version [e.g. 2.03.45] 2.03.21
 - Release version [e.g. v1.2.3] 16.6.1

**Additional context**

**Comment by Mayegelt** [comment]
Will be fixed in next release
