### ISSUE TITLE
Apothecary displaying artificer armour and white scar category in wrong catalogue

### ISSUE THREAD

**Issue by Morturg** [BSData/horus-heresy#2771]
**Describe the bug**
salamanders catalogue selected

apothecary unit

![image](https://user-images.githubusercontent.com/25342188/226157462-7b6d44f9-1f1e-487f-b86a-624650cda229.png)

as you can see it shows artificer armour and something about white scars

**Comment by Mayegelt** [comment]
This will be fixed in next release. Basically tried to tag in some modifiers to make it show the right movement values when you had certain bits of wargear and stuff and it was including the White Scars part of the modifier, even when inactive.
