### ISSUE TITLE
Castellan consul can select Solarite Power Gauntlet and cannot select Thunder Hammer

### ISSUE THREAD

**Issue by binaryspica** [BSData/horus-heresy#2784]
**Describe the bug**
Per 229, Liber Astartes, a Castellan may not select a Legion Warhawk jump pack, Legion Spatha combat bike, Legion Scimitar Jetbike, combat shield, boarding shield, power fist, **Solarite power gauntlet**, lightning claw(s) or any weapon with the Two-handed special rule.

But, for now Solarite Power Gauntlet is on the list of weapon options despite the rules explicitly says that he is not allowed to select it, and Thunder Hammer is removed from the option for unknown reason meanwhile.

I have checked the errata as well but the page is left untouched.

**To Reproduce**
1. Pick the VII legion, Imperial Fists on either Crusade or Ally option.
2. Add a Centurion to the detachment of the VII legion.
3. Check the lists of 1) Bolt Pistol/Chainsword Options.

**Expected behavior**
The Castellan should allowed to select Thunder Hammer, since none of the restriction says he cannot select it(it's not the prohibited weapons nor it's a Two-handed weapon). 

Also he is not allowed to use Solarite power gauntlet for the rules of the consul option says he is not allowed to do so.

**Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version 2.03.21
 - Release version 16.7.1

**Comment by Mayegelt** [comment]
will be fixed next release
