### ISSUE TITLE
Some units must allowed to select Stasis Missiles upgrades on Dark Angels.

### ISSUE THREAD

**Issue by binaryspica** [BSData/horus-heresy#2786]
**Describe the bug**
For now, either options of Destroyer Squads(both Destroyer Assault Squad and Mortalis Destroyer Squad), Armistos Consul option, Veteran Squad, Storm Eagle Gunship, Caestus Assault Ram, and Heavy Support Squad can access for Missile Launcher(and also do have Legiones Astartes rule), and that's the prerequisite of the Stasis Missiles upgrade of the I legion, Dark Angels.

But for now, only Heavy Support Squad can access for Stasis Missiles upgrade.

**To Reproduce**
1. Choose the Dark Angels legion.
2. Add a unit with Missile Launcher other than Heavy Support Squad and equip it.
3. Check its Missile Launcher line

**Expected behavior**
These units are should be allowed to select Stasis Missiles upgrade.

**Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version 2.03.21
 - Release version 16.7.1

**Comment by Mayegelt** [comment]
Looks like Destroyer Assault Squad and Mortalis Destroyer Squad, Veteran Squad, and Heavy Support all had them, but Armistos Consul, Storm Eagle Gunship, Caestus Assault Ram didn't.
Should be fixed next release.
