### ISSUE TITLE
[Anon] Bug report: 2022 - LA - Alpha Legion.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2788]
**File:** 2022 - LA - Alpha Legion.catz

**BattleScribe version:** 3.25.33

**Platform:** Android

**Dropbox:** No

**Description:** Alpha Legion is currently unable to add a Delegatus Upgrade to the Legion Centurion in Horus Heresy 2.0

**Comment by Mayegelt** [comment]
#1484 duplicate
