### ISSUE TITLE
Salamanders Catalogue Dragons Breath Flamer variants

### ISSUE THREAD

**Issue by Morturg** [BSData/horus-heresy#2798]
**Describe the bug**
Dragon's Breath upgrade is missing from a lot of the flamer weapons

**To Reproduce**
Chaplain, can't exchange hand flamer for DBF pistol
Leviathan, can't exchange heavy flamers for DBF heavy

I'm sure there's other

v56
salamanders v25

**Comment by Mayegelt** [comment]
Fixed in release 16.7.4
