### ISSUE TITLE
Rogal Dorn Frag Grenades

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2799]
**File:** 2022 - LA - Imperial Fists.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** When selecting a normal Command Retinue for Rogal Dorn and error message pops up saying he cannot select Frag Grenades

**Comment by Mayegelt** [comment]
Fixed in release 16.7.4
