### ISSUE TITLE
Reconcile with development efforts on the WH40k game system.

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#280]
Chatter on gitter has indicated that the big BattleScribe 2.0 push will see core rules brought under the game system (and outside of the individual catalog files). 

I think it would be excellent if we can get this project aligned "downstream" to benefit from these changes.

This will probably entail a lot of text-editor "find and replace" of entities with new links to the game system, and it may involve changing how the game system is setup (i.e., perhaps making a new clone of the 40k game system once the USRs and Weapon profiles from the core rules are in it), and then merging the HH specific stuff (i.e. Legion selection) back into it.

**Comment by Millicant** [comment]
I'm already planning/working this.  

I do plan to input all the "Basic" weapons and USRs into the gamesytem, however, I do NOT plan on doing a copy/paste as there is far too much work to do for that to be effective.

I plan on re-writing the gamesystem and catalogue to allow for Force Organization Chart modification. 

As a result, I do not want to merge "Downstream" as that will only increase the workload by a significant amount.  I do plan to liberally copy/paste from the 40k guys, however.
