### ISSUE TITLE
Alpha Legion - rewards of treachery 

### ISSUE THREAD

**Issue by S1xSh0t** [BSData/horus-heresy#2803]
Can't add Reward of Treachery unit(s) to Alpha Legion in Horus Heresy

I can select the unit that i want to take, but it doesn't add it to the roster in the corresponding unit slot. Therefore, I am unable to add any options or add the points.

Also reward of treachery is spelled incorrectly (trechery).

**Comment by S1xSh0t** [comment]
Hey,

So, forgive me if I'm missing something here, but - when I select the unit under Allegience (in this case an exemplary unit), I can't actually select it to add any of the unit's options etc. I can only select the unit's name.

**Comment by S1xSh0t** [comment]
![Screenshot_20230414_211037](https://user-images.githubusercontent.com/120862917/232145779-8e15582d-97b9-4cf5-817c-03fd6a0009d4.jpg)
![Screenshot_20230414_211050](https://user-images.githubusercontent.com/120862917/232145785-7da7a312-4cbd-4862-8439-fe91123f18ef.jpg)
![Screenshot_20230414_211126](https://user-images.githubusercontent.com/120862917/232145787-b8e0b799-6c50-4e56-ba13-268c229e1ad0.jpg)

**Comment by S1xSh0t** [comment]
Where do I find the unit entry and it's further options?

**Comment by Mayegelt** [comment]
Huscarls are HQ choices I believe

**Comment by S1xSh0t** [comment]
Oh man, I'm sorry! You're right! That's so bizarre! Thank you for your help and your time. Peace

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
