### ISSUE TITLE
Allied Detachments Expanded Army Lists

### ISSUE THREAD

**Issue by Jonathan-Blazeby** [BSData/horus-heresy#2805]
Allied Detachments do not have access to the 'Expanded Army List Profiles:' option, and so can't access Exemplary Battle & Legacy Units like the Crusade Force and Mortalis Assault Force can.

**Comment by Mayegelt** [comment]
When you create a roster you need to add both the main and any supplementary detachments in the same force.
The legacy and exemplary units selection will carry over.

![IMG_20230417_113124](https://user-images.githubusercontent.com/20280410/232459784-b38c27de-3966-40ee-9e6e-2d2e5f7ff4e1.jpg)
