### ISSUE TITLE
Models in Companion Sections, Tactical Command Tercio of SA lacks Laspistol&CCW option

### ISSUE THREAD

**Issue by binaryspica** [BSData/horus-heresy#2808]
**Describe the bug**
As title says. Any model in the unit may exchange their lasrifle for Laspistol and close combat weapon, but the list lacks the option. Perhaps that's not that important for the others(other than cannot pick a chansword option), but it also prevents the Adjutant to take the other pistol options and/or a Power Fist as well, for the Adjutant needs to pick 'Laspistol and CCW' option first in order to choose these options.

Nothing on the errata changes anything, neither upgrade to Adjutant line gives any extra upgrades.

Note that the Command Section(which is the section that is on the same Tercio) does **not** have the same option and only the captain or marshal can do this, while everyone can do this on the **Companion Section**. Perhaps that's the reason why the devs on the part are make a mistake.

**To Reproduce**
1. Pick Solar Auxilia faction
2. Add a Tactical Command Tercio
3. Add a Companion section
4. Check 'May exchange Lasrifle for: ' list of Companions.

**Expected behavior**
Any models in the Companion Section are must be allowed to choose 'Laspistol and close combat weapon' on 'May exchange Lasrifle for: '.

**Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version 2.03.21
 - Release version 16.7.4

**Comment by Mayegelt** [comment]
Fixed by ShadowCore67 and will be in todays release.
