### ISSUE TITLE
Tart termy Lightning Claws and Ravens Talons

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2811]
**File:** 2022 - Horus Heresy.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Horus heresy Tartaros Terminators. You can not select the upgrade option to take 2 lightning claws or 2 ravens talons on the sergeant or the unit. Also points costs for the ‘Raven’s talons’ that are available show 45 points each. This is incorrect
To add ravens talons it should be 30 points for the pair, the same as the other units

**Comment by Mayegelt** [comment]
Fixed by ShadowCore67 and will be in todays release.
