### ISSUE TITLE
Gilded Panoply - wrong Inv save in description

### ISSUE THREAD

**Issue by Cylindryk** [BSData/horus-heresy#2812]
![obraz](https://user-images.githubusercontent.com/51954441/234679942-a38b2da5-f5d1-4aa2-9fe7-4db34f977482.png)
This is what BS is showing.

![obraz](https://user-images.githubusercontent.com/51954441/234679993-82fd6ce5-f970-4b0e-ade5-67a93de3b86c.png)
This is what it should be shown.

**Comment by Mayegelt** [comment]
Fixed by ShadowCore67 and will be in todays release.
