### ISSUE TITLE
Warlord Trait Missing Malefic Supplicant

### ISSUE THREAD

**Issue by Morturg** [BSData/horus-heresy#2814]
**Describe the bug**
in the daemons of the ruinstorm expansion

https://www.warhammer-community.com/wp-content/uploads/2023/03/JXRAKYvl3BrGbGjD.pdf

the burning of Ohnm-mat, Malefic Supplicant is available to all traitors as an optional warlord trait

**Comment by Mayegelt** [comment]
It's there

![Screenshot_2023-04-29-10-09-55-216_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/20280410/235294841-e4ac754e-01b7-435f-9a7b-add500bad08d.jpg)
![Screenshot_2023-04-29-10-09-52-576_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/20280410/235294844-311ef75c-e3eb-4862-bfaa-c5c8471efe75.jpg)

**Comment by Morturg** [comment]
no it's not 

![image](https://user-images.githubusercontent.com/25342188/235296544-1eaa2882-5cb2-461f-8c7f-ab19a42aa149.png)

**Comment by Mayegelt** [comment]
![IMG_20230429_105618](https://user-images.githubusercontent.com/20280410/235296754-2351bcbf-b8c0-42f7-b5b3-fd25ec800298.jpg)

The screen shot you submitted shows you haven't selected an allegiance.
