### ISSUE TITLE
Cannot select a regular Droppod as dedicated transport for Rampagers in the Drop Pod Assault Rite of War

### ISSUE THREAD

**Issue by Chaobaozi** [BSData/horus-heresy#2817]
**Describe the bug**
The Rite of War rules states that "All units in a Detachment using this Rite of War eligible to take a Legion Rhino Transport or Legion Land Raider Proteus Carrier Dedicated Transport may instead select Legion Drop Pods or Legion Dreadclaw Drop Pods as Dedicated Transports"

The Rampager unit states: "A Rampager Squad numbering 10 models or fewer ... may take a Legion Land Raider Proteus Carrier as Dedicated Transport..."

Currently, I am unable to select the regular Drop Pod as a Dedicated Transport option for the Rampager unit (and probably for all units that only have the Legion Land Raider Proteus Carrier as a Dedicated Transport option)

**To Reproduce**
1. Add the Rite of War "Drop Pod Assault"
2. Add the Rampager unit to the list
3. Under Dedicated Transport the regular Drop Pod is not available

**Expected behavior**

Since the Rite of War has an "Or" clause, I should be able to select a regular Drop Pod as a Dedicated Transport for all units that may take a Legion Land Raider Proteus Carrier as Dedicated Transport.

**Screenshots**
![image](https://user-images.githubusercontent.com/3414406/235644512-73c5e4cd-3700-448c-9c9a-4ae83c35c374.png)

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version: 2.03.21.166

**Comment by Mayegelt** [comment]
Fixed by ShadowCore67 and will be in todays release.

**Comment by Mayegelt** [comment]
I'll have a looky. Someone else did the fixes, so I'll see what went wrong

**Comment by Mayegelt** [comment]
Looks like it was a "And child selections" tickbox wasn't ticked.
Will be fixed in next release.

**Comment by Mayegelt** [comment]
Fixed in v16.7.6 just released now.
