### ISSUE TITLE
Despoilers and World Eater Rampagers can select drop pod with illegal squad size or wargear respectively

### ISSUE THREAD

**Issue by Chaobaozi** [BSData/horus-heresy#2821]
**Describe the bug**
In the Drop Pod Assault Despoilers can still select a drop pod even when their squad is over 10 models. 

World Eater Rampagers can select drop pods when their squad is over 10 models or when they are equipped with the Legion Warhawk Jump pack.

**To Reproduce**
1. Select Drop Pod Assault Rite of War
2. Add a unit of Despoilers
3. Add models to the unit until it is more than 10
4. Drop Pod is still an option under Dedicated Transport

For Rampagers:
1. Under World Eaters
2. Select Drop Pod Assault Rite of War
3. Add a unit of Rampagers
4. Select Warhawk Jump pack 
OR
5. Add models to the unit until it is more than 10
6. Drop Pod is still an option under Dedicated Transport

**Expected behavior**
In either case: The Drop Pod should no longer be an option as Dedicated Transport

**Comment by Mayegelt** [comment]
Will be fixed on next release.

**Comment by Mayegelt** [comment]
Fixed in v16.7.6 just released now.
