### ISSUE TITLE
Ordinatus Ulator has too many selections of Volkite Culverin.

### ISSUE THREAD

**Issue by spectreofposadism** [BSData/horus-heresy#2822]
When selecting the Ordinatus Ulator for a Mechanicum army, the following errors are thrown simultaneously: 

Ordinatus Ulator has 2 too many selections of Volkite Culverin (Maximum 1)

Ordinatus Ulator has 1 too many selections of Volkite Culverin (Maximum 2)

No choice is given to select any more or fewer Volkite Culverins.

**Comment by Mayegelt** [comment]
Will be fixed next release. There was a tick in the shared box that was messing it up as there are 2 on sponsons, 1 on rear of the tank.

**Comment by Mayegelt** [comment]
Fixed in v16.7.6 just released now.
