### ISSUE TITLE
Primus Nullificator has too many CC options

### ISSUE THREAD

**Issue by Petitionerscity** [BSData/horus-heresy#2827]
**Describe the bug**
Hi Mayegelt, 

The primus nullificator shouldn't have any cc options - in the [Legacies doc](https://www.warhammer-community.com/wp-content/uploads/2022/09/RZRGS5ADYjwUb7Ry.pdf), it tells us he must replace their power weapon with an aether-shock maul. However, an aether-shock maul isn't a power weapon per the nullificator rules (it doesn't have a type), and thus a Primus-Nullificator has no way to replace the maul with a centurion's normal options for swapping their power weapon with another melee weapon.

Best,
PC

**Expected behavior**
A Primus Nullificator should only have a Aether-Shock Maul as their melee weapon, and no others.

**Screenshots**
https://i.postimg.cc/SQWsG9GX/Primus-Nullificator.png

https://i.postimg.cc/02PNXNtV/Aether-shock-maul.png.

![Aether-shock maul](https://github.com/BSData/horus-heresy/assets/133539150/e8738d6d-ef25-4981-be73-c3c2ef963f5b)
![Primus-Nullificator](https://github.com/BSData/horus-heresy/assets/133539150/8340fed0-f0f8-4966-99f5-a1c67b2be6a5)

**Comment by Mayegelt** [comment]
Will be fixed in next release. It was missing a min 1 if primaris null.

**Comment by Mayegelt** [comment]
Fixed in v16.7.6 just released now.

**Comment by Petitionerscity** [comment]
Thank you Mayegelt, that's fantastic!
