### ISSUE TITLE
Head of the Gorgon / Iron Father.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2828]
**File:** 2022 - Horus Heresy.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** In horus heresy 2.0 on the iron hands, while using the “head of the gorgon” rite of war, any iron father should be able to equip a cortex controller, however it is only available as a selection to the iron father in power armor (standard praetor), not the iron father in either terminator armor (cataphractii praetor, and tartaros praetor)

**Comment by Mayegelt** [comment]
Will be fixed in next release.

**Comment by Mayegelt** [comment]
Fixed in v16.7.6 just released now.
