### ISSUE TITLE
Apothecarian Detachment should allow more apothecaries 

### ISSUE THREAD

**Issue by PowerEncarnate** [BSData/horus-heresy#2829]
the datasheet entry starts you with 1 apothecary and you have the option to add up to 7 additional apothecaries but when you add the 7th extra apothecary BS tells me that I have one to many apothecaries

**Comment by Mayegelt** [comment]
Will be fixed next release. Was an issue of a 7 rather than an 8. I'm sure it used to work, so probably one of those things where BS data editor decided to make its own edit.

**Comment by Mayegelt** [comment]
Fixed in v16.7.6 just released now.
