### ISSUE TITLE
Cerastus Knight-Atrapos

### ISSUE THREAD

**Issue by Glaidr** [BSData/horus-heresy#283]
Debatable error. In rules says :

"The Mechanicum Knight-Atrapos may be used either as part of a Mechanicum Taghmata army as a Lords of War choice as normal, or as part of a Questoris Knight Crusade army as a 0-1 choice per 2,000 points in the army."

Link :https://www.forgeworld.co.uk/resources/fw_site/fw_pdfs/Horus_Heresy/Cerastus-Knight-Atrapos.pdf

as it says you can have "...0-1 choice per 2,000 points in the army." meaning you could take one, with an army size between 1-2000 points, 2 if army is between 2001 and 4000 (and so on...) . if it were must have 2000 points to take one, it would read something like "...0-1 choice per 2,000 points in the army, with a  minimum of 2000 points"

**Comment by Millicant** [comment]
I'm afraid I disagree.  It's 0-1 per 2000 points in the army.  To me that says that if your list is only 1500 points, you don't have that option.  Fortunately, as it is not hidden, you can still take it freely and merely have to look at an error.  

I will seek out more opinions.  If I'm in the minority - I'll come back and fix this.  Sound good?

**Comment by capitaladot** [comment]
I've double-checked that this wording is the same as the published text in book 6; it is the same muddled mess.

> The Mechanicum Knight-Atrapos may be used either as part of a
Mechanicum Taghmata army as a Lords of War choice as normal,
or as part o f a Questoris Knight Crusade army as a 0-1 choice per
2,000 points in the army

That said, this "2000 points in list, then you may add an Atrapos" interpretation is inconsistent with the interpretation of the other points-related LoW limitations (i.e., you need not take 2500 points, and then be allowed 25% as a Lord of War; you may take that Lord of War inclusive to the 2500 points, but it may only represent 625 of those points).

Extrapolating this "2000 points in list, then one Atrapos" exclusive of those 2000 points beyond the first increment starts to get quite odd... at 4000 points, to include two, need your list be 4870 points?

**Comment by Millicant** [comment]
That isn't really relevant since the list in question doesn't treat the Atrapos as a Lord of War.  

However, I received some varied opinions on this when I asked around - about half thought each way.  While I still disagree, I have to go with the least restrictive option, since that is in line with the goals set forth for this project.
