### ISSUE TITLE
SoH Reaver Attack and Aggressor squads missing wargear

### ISSUE THREAD

**Issue by AudwinFr** [BSData/horus-heresy#2831]
**Describe the bug**
Sons of Horus  Reaver Attack and Reaver Aggressor squads are missing Carsoran Power axes as options. Reference page 284 of Liber Hereticus.

**Comment by Mayegelt** [comment]
Had a look at this one and fixed it.
Also found that their special weapon allocation was wrong as it was not flagging an error correctly. It was allowing [1+ (+1 per 5 models in unit)]. Rather than [0 (+1 per 5 models in unit)]

**Comment by Mayegelt** [comment]
Fixed in latest release.
