### ISSUE TITLE
Hetaron guard - Dedicated Transports.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2833]
**File:** 2022 - Horus Heresy.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Hetaron guard for legio custodes can take a dedicated transport that is not a option in BattleScribe

**Comment by Mayegelt** [comment]
Thanks for the report. Will be fixed in next release.

Also noticed the max limit of 4 Aquillions for having a dedicated transport was not being followed, so did that at the same time.

**Comment by Mayegelt** [comment]
Fixed in latest release.
