### ISSUE TITLE
Terminator Indomitus Squad w/Heavy Weapon option's default weapon is Heavy Alchem Flamer

### ISSUE THREAD

**Issue by binaryspica** [BSData/horus-heresy#2834]
**Describe the bug**
As title says. Despite it is the exclusive equipment of the XIV legion, death guard, every other legion's Terminator Indomitus Squad with  Heavy Weapon option's default weapon is set to Heavy Alchem Flamer. It causes the error that it cannot have any sections, and the item is removed if you change it to the other heavy weapon options.

I have seen the error on the mobile version first, and then I found that the PC version has the same problem as well.

**To Reproduce**
1: Make any legiones astartes detachment, save for death guard.
2: Add a Terminator Indomitus Squad on it.
3: Add a 1x Indomitus w/Heavy Weapon (1 in 5).
4: Check its default weapon and you will see it's set to Heavy Alchem Flamer, despite the legion you chosen wasn't the XIV legion.

**Expected behavior**
Heavy Flamer should be the default weapon of the heavy weapon squad member.

**Device and data (please complete the following information):**
 - OS: Windows 10 / Android 13
 - BattleScribe version 2.03.21 / 2.03.25
 - Release version 16.7.6

**Comment by Mayegelt** [comment]
Strange error. Likely chance is when editing to add other weapon options, something went wrong. Will try to fix for next release

**Comment by Mayegelt** [comment]
Should be fixed next release

**Comment by Mayegelt** [comment]
Fixed in latest release.
