### ISSUE TITLE
No spreading corruption with Horus Ascended

### ISSUE THREAD

**Issue by LivingDynamode** [BSData/horus-heresy#2836]
Hi, Horus ascended has an ability,  "All models in a unit made up entirely of models with the Infantry, Cavalry or Dreadnought Unit Types inthesame Detachment as Horus Ascended may be given the Corrupted Unit Sub-type at a cost of +25 points per unit .", but while you'd expect this to add the dark channeling type function from Word Bearers to sons of horus, it doesn't show up in battlescribe yet

**Comment by LivingDynamode** [comment]
Appreciated!

**Comment by Mayegelt** [comment]
Well 3hrs of work later...
Should work on next release...

**Comment by Mayegelt** [comment]
Fixed in latest release.
