### ISSUE TITLE
SW- Great Frost Weapons for Retinue

### ISSUE THREAD

**Issue by Stubram** [BSData/horus-heresy#2841]
Space Wolves Retinue don’t count as Independent Characters so sadly can’t have Great Frost Weapons (though can have normal Frost Weapons).

**Comment by Mayegelt** [comment]
Are you saying they are lacking options, or have options they shouldn't have?

Sorry been working on Militia today and not sure which it is, and just logged out of the computer.

**Comment by Stubram** [comment]
Oh sorry bud.

Space Wolves Retinues/Command Squads SHOULDN’T have access to Great Frost Blades, but they currently do on BattleScribe.

Only SW Independent Characters can have Great Frost Blades


Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Mayegelt** [comment]
Strange, seems to be an issue for command squads taken by praetor, but not Centurions - Delegatus...

**Comment by Mayegelt** [comment]
Ok quick clarification before I fix...
You said in the first "Space Wolves Retinue don’t count as Independent Characters so sadly can’t have Great Frost Weapons (though can have normal Frost Weapons)."
I can't see a reference to say that they are allowed normal frost weapons. Both seem to have the same clause of must be SW and Independant char. Though understand it might be its hidden off somewhere else.

![image](https://github.com/BSData/horus-heresy/assets/20280410/bfb83d6d-92e8-4eec-a4a6-ab7feb6bbe7a)

**Comment by Mayegelt** [comment]
Live on [v16.9.0](https://github.com/BSData/horus-heresy/releases/tag/v16.9.0)
