### ISSUE TITLE
Militia Provenances Functioning incorrectly

### ISSUE THREAD

**Issue by harrisoncrazy** [BSData/horus-heresy#2843]
The Clan Levy and Industrial Stronghold provenances don't add their bonuses correctly it seems.

Clan Levy has the cavalry in the troops slot with the increase in LD, but BS still throws errors for not having enough compulsory slots (the Calvary become Compulsory troops) 

Industrial Stronghold seems to not add its benefits at all. I can't add additional Russes to the unit and errors are thrown about Heavy Support slots.

**Comment by Mayegelt** [comment]
Thanks for the input, and putting it in the right place :D
Looks like in the case of the Cavalry troops in Clan Levy I had added a modifier to limit the number to the max of the max number of compulsory troops, but not actually added the compulsory troops part...

Also noticed that Lasrifles were showing outside of "Armoury of Old Night" as I forgot to click to hide them, though did have the hidden = false function in place.

**Comment by Mayegelt** [comment]
Looks like I didn't create the link correctly and get it to show for the Leman Russ Squadron as well.

**Comment by Mayegelt** [comment]
Also had added the process to increase the max HS by 2 for Leman Russ Squadrons, but didn't actually add the category to the entry.

**Comment by Mayegelt** [comment]
Live on [v16.9.0](https://github.com/BSData/horus-heresy/releases/tag/v16.9.0)
