### ISSUE TITLE
Fortified Wall had wrong base cost

### ISSUE THREAD

**Issue by Posh-Tim** [BSData/horus-heresy#2844]
Attempting to buy a Fortified Wall fortification has a base cost of 255 with a single 'strong point' it should cost 55 per strong point.

**Comment by Mayegelt** [comment]
Should be fixed next release. No idea why their was a 200pts tax. It might have been a lazy copy / reskin which I didn't modify correctly.

**Comment by Posh-Tim** [comment]
Brilliant, thanks very much.
