### ISSUE TITLE
Militia Feral Warriors Chainaxes Points & Grenadier Options

### ISSUE THREAD

**Issue by Jonathan-Blazeby** [BSData/horus-heresy#2846]
Imperial Militia with the Feral Warriors Provenance of War are having their chainaxes pointed at 1pt across the board. Its 2pts when replacing a CCW, and 1pt when replacing a chainsword. I think one of the cavalry options is showing it as costing the same as one without.

Also, Grenadiers are missing shotguns as an option, and should have the militia Vexilla, not the militia Standard as an option.

**Comment by Mayegelt** [comment]
Should both be fixed next release.
For some reason I'd skipped over the 2pts for CCW to Chainaxe, and only read the 1pts bit. Though its a bit strange, as I don't think anyone starts with a chainsword to get the 1pts upgrade...

**Comment by Mayegelt** [comment]
Live on [v16.9.0](https://github.com/BSData/horus-heresy/releases/tag/v16.9.0)
