### ISSUE TITLE
Siege of Cthonia

### ISSUE THREAD

**Issue by Arkangelmark5** [BSData/horus-heresy#2847]
**Siege of Cthonia **

**Missing units from the Siege of Cthonia**

- [x] Infernus Abomination
- [x] Evander
- [x] Vheren
- [x] Evander
- [x] Legiones Decurion
- [x] Inductii

**Comment by Mayegelt** [comment]
Live on [v16.9.0](https://github.com/BSData/horus-heresy/releases/tag/v16.9.0)
