### ISSUE TITLE
Ogryn Chainaxe Costing

### ISSUE THREAD

**Issue by The4D6** [BSData/horus-heresy#2855]
Under the ogryn brute squad, the chainaxe cost is listed as a flat 6pts, whereas it should be 2pts per model to purchase them.

**Comment by The4D6** [comment]
Sorry, this should have "Bug - Cost" as a tag but I can't see how to add that

**Comment by The4D6** [comment]
I understand now what has happened, in that they cost 6pts because you're buying an extra CCW and then upgrading it, but then they should cost 7pts as it's 2pts to upgrade a CCW and 1pt to upgrade a chainsword

There does not appear to be an option to purchase chainaxes as an upgrade to the CCW they aready have, rather than buying a new CCW and upgrading it

**Comment by The4D6** [comment]
@Mayegelt do you want to close this and link the PR you did?

**Comment by Mayegelt** [comment]
Fixed in https://github.com/BSData/horus-heresy/commit/e658aba87788611abd842edf613cd074d2e61752

Will be available next release

**Comment by Mayegelt** [comment]
> @Mayegelt do you want to close this and link the PR you did?

Thanks. I'd forgot to link with the "done on (master,)..." Tag.
I tend to only close after live release, so people are less likely to report issues that are already resolved.

**Comment by Mayegelt** [comment]
Live on [v16.9.0](https://github.com/BSData/horus-heresy/releases/tag/v16.9.0)
