### ISSUE TITLE
Proteus Land Speeder's maximum squadron size is limited to 4

### ISSUE THREAD

**Issue by binaryspica** [BSData/horus-heresy#2859]
**Describe the bug**
As title says. Both Libers says their size is up to 5, because it says you can add up to 4 units while you have one by default when you add this(1+4=5, obviously). But for now Battlescribe says it's maximum is 4, not 5

**To Reproduce**
1. Make any Legiones Astartes faction detachment.
2. Add a Proteus Land Speeder Squadron.
3. Add 4 more Proteus Land Speeders on the same squadron.
4. Battlescribe says an error, that 'Proteus Land Speeder Squadron has 1 too many sections of Proteus Land Speeder (maximum 4)'.

**Expected behavior**
Five units in a single Proteus Land Speeder Squadron should be legal, as both Libers says.

**Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version v2.03.21
 - Release version 16.8.0

**Comment by Mayegelt** [comment]
Will be fixed on next release.

**Comment by Mayegelt** [comment]
Live on [v16.9.0](https://github.com/BSData/horus-heresy/releases/tag/v16.9.0)
