### ISSUE TITLE
Combi-Disintegrator is one of the option of Legion Sabre Strike Squadron's Pintle Mounted weapon option

### ISSUE THREAD

**Issue by binaryspica** [BSData/horus-heresy#2860]
**Describe the bug**
As title says.

**To Reproduce**
1. Add any Legiones Astartes faction.
2. Add a Sabre Strike Squadron.
3. Choose a Sabre on it.
4. See its Pintle-Mounted Weapon list and you will see **Magna Combi-Weapon - Disintegrator**.

**Expected behavior**
It must be removed from the option, because Combi-Weapon's description says only some specific units are able to choose this and Sabre is not among them.

**Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version v2.03.21
 - Release version 16.8.0

**Comment by Mayegelt** [comment]
Will be fixed on next release

**Comment by Mayegelt** [comment]
Live on [v16.9.0](https://github.com/BSData/horus-heresy/releases/tag/v16.9.0)
