### ISSUE TITLE
Some Thousand Sons units are not able to choose Æther-fire pistol instead when they can get its plasma variant

### ISSUE THREAD

**Issue by binaryspica** [BSData/horus-heresy#2861]
**Describe the bug**
For now these units are able to get a plasma pistol but cannot choose Æther-Fire pistol option instead in the XV legion, Thousand sons;

Command Squad(all models), Destroyer Assault Squad(1 in 5), Mortalis Destroyer Squad(1 in 5), Techmarine Covenant.

**To Reproduce**
1. Make a XV legion, Thousand Sons detachment.
2. Add either Command Squad, Destroyer Assault or Mortalis squad, or Techmarine Covenant.
3. Check their option for the plasma pistol.

**Expected behavior**
These models should have the option to choose Æther-fire pistol.

**Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version 2.03.21
 - Release version 16.8.0

**Additional context**

**Comment by Mayegelt** [comment]
Thanks for the report. Hopefully should have this patched for next release.

**Comment by Mayegelt** [comment]
Well be fixed soon. I plan on pushing a release today with any luck.

**Comment by Mayegelt** [comment]
Live on [v16.9.0](https://github.com/BSData/horus-heresy/releases/tag/v16.9.0)
