### ISSUE TITLE
Incorrect profile of Needle pistol

### ISSUE THREAD

**Issue by binaryspica** [BSData/horus-heresy#2863]
**Describe the bug**
Needle pistol is Range 12", Str 2, AP - and is Pistol 2, Poisoned (3+), Pinning. But for now, the profile of needle pistol is Range **24**, Str 2, AP -, and is **Heavy 4**, Poisoned (3+), Pinning.

I have check Primus Medicae and various source(Sisters of Silence and Militia with relic weapon options) and all of them are shows the same and incorrect profile as well.

**To Reproduce**
1. Make any detachment(too many - I think that most non-daemon detachment can access for this).
2. Add a unit with needle pistol option, or enable it if you need to unlock.
3. Check its profile.

**Expected behavior**
As 'Describe the bug' section above.

**Device and data (please complete the following information):**
 - OS: Windows 10
 - BattleScribe version 2.03.21
 - Release version 16.8.0

**Comment by Mayegelt** [comment]
Very strange. I fixed that big at one point. Might have reverted when I had to merge something.
Will be fixed next release

**Comment by Mayegelt** [comment]
On my one with todays update it looks like i am getting the right type, but wrong range.
Either way it will be fixed next release.
