### ISSUE TITLE
Davinite lodge priests not featured in HQ slot for militia and cults

### ISSUE THREAD

**Issue by sullywully95** [BSData/horus-heresy#2868]
![E6B3800B-FACF-46AF-A056-AA7754664254](https://github.com/BSData/horus-heresy/assets/121670993/ababc72c-57f5-4b6c-ba91-57432bc6500f)
![4C5909ED-D78C-4F16-8D6D-303D7E05FCDA](https://github.com/BSData/horus-heresy/assets/121670993/2239cf7e-dcfd-4369-ad80-337deabfa551)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - BattleScribe version [e.g. 2.03.45]
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by Mayegelt** [comment]
Was also missing from Mech, LA, Sisters and Custodes.
Fixed on master. Will be pushed out in next release.
