### ISSUE TITLE
HH2 - Night Lords Character Nakrid Thole, Warlord error

### ISSUE THREAD

**Issue by Skorpietto** [BSData/horus-heresy#2869]
the character Nakrid Thole of the Night Lords of the Legacies, is selectable as a warlord, but his trait is that of Kheron Ophion (Aberrant Bravery), instead a Night Lords or generic trait should be selectable.

**Comment by Mayegelt** [comment]
Will be fixed next release

**Comment by Mayegelt** [comment]
Release today [v16.9.3](https://github.com/BSData/horus-heresy/releases/tag/v16.9.3) fixes this
