### ISSUE TITLE
Preparing for Battlescribe 2.0

### ISSUE THREAD

**Issue by Millicant** [BSData/horus-heresy#287]
I'm going to be doing a bunch of work locally before I add a branch for development. This is because I'm doing some core restructuring of the gamesystem and catalogues.  

As of now - any new issues/fixes will have to be implemented twice: for release and for 1.16 development.  As a result, that means some minor fixes will be left until 1.16 release to prevent double-work.

**Comment by Millicant** [comment]
Alright, I've made a bunch of progress on the 2.0 catalogues/gamesystem.  It's going to get complicated, but it should be awesome.  

At this point - please do not make any changes/commits whatsoever.  I'm operating on slightly thin ice until I get a stable version that I can upload to a branch.  If any changes come through from outside sources, they might cause some problems.  

Once I do create the branch, I'm going to be seeking out Alpha testers from the community, as I'm sure there will be loads of issues.

**Comment by capitaladot** [comment]
Hanging back (as I have been since the 2.0 discussion). Is there anything that can be done to help?

**Comment by Millicant** [comment]
Thanks man.  

Not just yet, but I'm planning to re-write most of the entries once I finish the restructuring the core.  Ultimately, the whole Horus Heresy system is too spread out to expect users to track everything.  I want to consolidate so it's an easier source for building and using a list.  We'll lay out the "standard" for entries here before we dive in, but I think several people (including yourself) who have suggested a more 40k-style approach will be vindicated.  

I'm moving rules/profiles into the root slowly as a part of the basic process, but we'll have to do everything eventually.  Those two intertwined projects will need both of our attention and lots of time.  I'd like to ensure that all rules and profiles have the most recent book/page number listed as well.

**Comment by capitaladot** [comment]
I am super-excited about this. How is it going?

**Comment by Millicant** [comment]
It'a coming along nicely!  I've hit a few snags, just due to ongoing bugs in the alpha, but once those are resolved we should have a pretty good product on our hands.  I'm taking a few days off the project here - I just returned home from a deployment - but I'll jump back in shortly.

**Comment by Millicant** [comment]
I think the time has come to create a new repo for this project. The 40k guys did the same thing do it could be tested properly and I'd like to do the same. This will allow more testers and allow iOS testing. Who actually creates repo that fall under the Battlescribe umbrella?

**Comment by capitaladot** [comment]
It has got to be @amis92

**Comment by amis92** [comment]
Hey there, just gimme a moment :)

**Comment by amis92** [comment]
Here you go: https://github.com/BSData/horys-heresy-bs2prep

**Comment by amis92** [comment]
Here yo go: https://github.com/BSData/horus-heresy-bs2prep

**Comment by Millicant** [comment]
Great!  Thanks @amis92 I really appreciate that!
