### ISSUE TITLE
[Anon] Bug report: 2022 - LI - Sisters Of Silence.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2873]
**File:** 2022 - LI - Sisters Of Silence.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** For sisters of silence Firebrand Cadre (equipped with snare gun), Subjugator Cadre (equipped with snare cannon), and Expurgator Cadre (equipped with snare cannon) the Entangle (x) special rule is not displaying correctly.

**Comment by Mayegelt** [comment]
Fixed in todays release v16.9.4
