### ISSUE TITLE
Militia Thunderbolt - Heavy Krark Rockets have no profile

### ISSUE THREAD

**Issue by The4D6** [BSData/horus-heresy#2881]
**Describe the bug**
The heavy krark rockets have no profile on the Militia Thunderbolt

I am currently creating a fix for this, bug is for visibility

**Comment by The4D6** [comment]
Heavy frag rockets also have no profile

**Comment by Mayegelt** [comment]
> Heavy frag rockets also have no profile

I can see a profile for heavy frag

![Screenshot_2023-06-23-18-22-58-710_net battlescribe mobile rostereditor](https://github.com/BSData/horus-heresy/assets/20280410/df83f426-d8b8-4547-a056-060b6859ab07)

**Comment by The4D6** [comment]
I'm not sure what happened there, but it was blank for me. Reloaded the app and it was there.

**Comment by Mayegelt** [comment]
Merged.
If you want to release, then go for it
