### ISSUE TITLE
[Anon] Bug report: 2022 - LA - Word Bearers.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2883]
**File:** 2022 - LA - Word Bearers.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** When making a Word Bearers Mortalis Assault Force Organization Chart, the unit Mhara Gal Dreadnaught is not selectable in the Elite section.

The Mhara Gal Dreadnaught can be selected as normal when doing a Crusade Force Organization Chart.

**Comment by Mayegelt** [comment]
Please reread the ZM restrictions. No models with 8 or more wounds may be taken.
The restriction was raised from 7 or more to 8, which then allowed Leviathan, Thanatar (not paragon) and Samus. But Mhara Gal has W8
