### ISSUE TITLE
[BUG, World Eaters]: Red Hand Destroyer w/HeavyWeapons start with special weapons as well

### ISSUE THREAD

**Issue by TBigLyfe** [BSData/horus-heresy#2889]
When you select a Red Hand Destroyer Squad and attempt to add a ravager with a heavy weapon (missile launcher or thunder hammer), it counts as if they had also bought the chainsword weapon upgrade for free, making them 15 points cheaper.

In Battlescribe: ![image](https://github.com/BSData/horus-heresy/assets/81039164/2338f75b-6a9c-4617-ba46-c6a43e0bb368)
In the Exemplary PDF: ![image](https://github.com/BSData/horus-heresy/assets/81039164/73b342bd-1e73-4f93-aad2-71e5b4af3a57)

**Comment by nstephenh** [comment]
Should be fixed and added back in the missing falax blades.
Assuming regular chainaxes are a free upgrade replacing all chainswords?

**Comment by TBigLyfe** [comment]
> Should be fixed and added back in the missing falax blades. Assuming regular chainaxes are a free upgrade replacing all chainswords?

World Eaters can upgrade chainswords into chainaxes for free
