### ISSUE TITLE
Questoris Knight text typos

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#289]
**File:** (HH) Mechanicum - Questoris Knight.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** Spelling error again (didn't spot these ones when submitting previous one)

Oracle of Battle:
"Knights from the same detachment may add +1 to ttheir Reserves rolls."
'ttheir' = their

"Note that this is an exception to the noraml special"
'noraml' = normal

**Comment by Millicant** [comment]
Nice catches, thank you.  We'll get these added post 1.16 since they are non-critical.
