### ISSUE TITLE
HH v1 breachers do not have Rhino as DT option

### ISSUE THREAD

**Issue by Argel-Tal** [BSData/horus-heresy#2898]
**Describe the bug**
Legion breachers, when selected as Troops choices do not have the option for a Rhino DT

**To Reproduce**
1. Go to 'Troops'
2. Click on 'Legion Breachers'
3. Scroll down to 'Dedicated Transport'
4. See error - no Rhino

**Expected behavior**
35pt Rhino should appear, as seen for Support and Tactical squads.
This should also be replaced with a Drop Pod in Orbital Assault, and similar logic (as per other rhino replacements) in other ROWs

**Screenshots**
Unit menu
![Screenshot_20230722_083835](https://github.com/BSData/horus-heresy/assets/80669114/8480853c-249a-4e3d-be32-2b86e8288e19)
No Rhino:
![Screenshot_20230722_083840](https://github.com/BSData/horus-heresy/assets/80669114/1eda0d25-6abc-4cb4-a27c-67ec832f0532)
Tactical squad's rhino entry (should be there for Breachers in addition to other options)
![Screenshot_20230722_084521](https://github.com/BSData/horus-heresy/assets/80669114/e92d5369-24ec-442a-bd22-20742759859d)

**Device and data (please complete the following information):**
 - OS: [Android 13]
 - BattleScribe version [e.g. 2.03.27]
 - Release version [v16.9.5]

**Comment by Mayegelt** [comment]
Breachers do not get an option for Rhino as a dedicated transport in 1.0.
