### ISSUE TITLE
Combine copies of profiles into profile links

### ISSUE THREAD

**Issue by nstephenh** [BSData/horus-heresy#2907]
Currently there are a lot of copies of profiles. We can instead use one profile and the rest be profile links to the first instance of the profile. They don't even have to be a shared profile, it can be the profile of the target unit.

**Comment by Mayegelt** [comment]
I think in most cases this is done.
I know you can't just use the generic legionary profile as a shared one
though without a bunch of issues coming from modifiers.

**Comment by nstephenh** [comment]
Specifically I spotted this on Suzerians in Ultramarines, hopefully we've gotten the others taken care of.
