### ISSUE TITLE
Blood Angels Land Raider Proteus: missing hull mounted twin-linked Assault Cannon option.

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#291]
This is somewhat of a judgement call, but is probably an oversight (as it appears the other places twin-linked assault cannons can replace heavy flamers, i.e. the turret on the Fellblade, allow such replacement).

**Comment by Millicant** [comment]
Just an oversight on my part.  I'm going to add this to the short list of 'pre-1.16 fixes' and I'll knock it out today.
