### ISSUE TITLE
Iron Hands Morlock weapon choices are wrong

### ISSUE THREAD

**Issue by Idunnoguy** [BSData/horus-heresy#2913]
**Describe the bug**
All Morlocks are able to select volkite culverins whereas the rules state that only the augmentor (the sergeant) can take a culverin.

**Expected behavior**
The Volkite Culverin should only be selectable for the Morlock Augmentor

**Device and data (please complete the following information):**
 - OS: Android
 - App: Battlescribe 2.03.27
 - Data release version 17.0.0

**Comment by Mayegelt** [comment]
Will be fixed on next release
