### ISSUE TITLE
Castellax and Vorax do not have atomantic deflectors in their wargear displayed

### ISSUE THREAD

**Issue by Idunnoguy** [BSData/horus-heresy#2914]
**Describe the bug**
Castellax Automata and Vorax automata should have atomantic deflectors, but battlescribe does not display them in the view option

**To Reproduce**
1. Select either a unit of either Castellax or Vorax automata
2. Click on the view button
3. Scroll down to the unit descriptions of the Castellax and/or Vorax

**Expected behavior**
The unit descriptions should show the atomantic deflectors in the same way it is displayed for the unit descriptions for Domitars, Arlataxes, Vulturaxes, and Thanatars

**Screenshots**
![Screenshot_20230805-104627](https://github.com/BSData/horus-heresy/assets/55272139/7f702506-f6f5-4095-97d1-f47454643190)

**Device and data (please complete the following information):**
 - OS: Android
 - App version: Battlescribe v2.03.27
 - Data release version v17.0.0

**Comment by Mayegelt** [comment]
Will be fixed on next release
