### ISSUE TITLE
Iron Hands Venerable Ancient Contemptor Dreadnoughts have the incorrect option for graviton shredders

### ISSUE THREAD

**Issue by Idunnoguy** [BSData/horus-heresy#2915]
**Describe the bug**
Iron Hands Venerable Ancient Contemptor Dreadnoughts display the option for graviton shredders which they are unable to take due to dreadnoughts not being infantry

**Expected behavior**
Iron Hands Venerable Ancient Contemptor Dreadnoughts should not have the option to take a graviton shredder

**Device and data (please complete the following information):**
 - OS: android
 - App: Battlescribe v.2.03.27
 - Data release version: v17.0.0

**Comment by Mayegelt** [comment]
Will be fixed on next release
