### ISSUE TITLE
Augury Scanner not available for heavy weapons team when using Imperial Fists.

### ISSUE THREAD

**Issue by biochembri** [BSData/horus-heresy#2917]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - App being used to create lists [e.g. New Recruit, Bluescribe, Battlescribe]
 - App version
 - Data release version [e.g. v1.2.3]

**Additional context**

**Comment by Mayegelt** [comment]
Fake news, see screenshot.

![Screenshot_2023-08-07-18-44-40-162_net battlescribe mobile rostereditor](https://github.com/BSData/horus-heresy/assets/20280410/a2e2b49a-9cbc-4a74-b420-7fc3f98a4dfd)

**Comment by biochembri** [comment]
Mayegelt,

Sorry for the mistake, you are correct, it is under the add options section. Thank you for the quick and personal response. I try not to promote fake news, but I must be in collusion with Hillary now.

Brian Abela
(559)303-7182 (cell)






On Monday, August 7, 2023 at 10:47:59 AM PDT, Mayegelt ***@***.***> wrote: 







Fake news, see screenshot.
