### ISSUE TITLE
Whirlwind should not have Bombard Sub-Type.

### ISSUE THREAD

**Issue by nstephenh** [BSData/horus-heresy#2919]
**Describe the bug**
Whirlwind has bombard Sub-Type.
Doesn't in the legacies of age of darkness.

Creating this in case I don't remember to fix it.

**Comment by Mayegelt** [comment]
Might need to check and remove restrictions on the root selection for it that are trigging due to RoW or whatever as a few of them can't take bombard I think

**Comment by Mayegelt** [comment]
Will be fixed in next release

**Comment by Mayegelt** [comment]
Fixed in [v17.1.0](https://github.com/BSData/horus-heresy/releases/tag/v17.1.0)
