### ISSUE TITLE
Proposal: text of Rites of War.

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#292]
I would like to include the Rites of War text. Owning all published red books (and several black books; 3,4, and 6), I find hauling them to events to be a major pain, especially as Battle Scribe makes implementing every restriction a bit tricky.

As such, it is my intention to contribute text for each of these.

I will plan to do this after the current re-factoring is done to avoid merge trouble.

**Comment by Millicant** [comment]
Agreed. I've actually already begun this process. There is quite a bit of said text in my updated versions. Once I have a working edition, I'll create a branch so you can see and start inputting text.

**Comment by capitaladot** [comment]
Cool! I have the text copy-edited and ready to drop in.

**Comment by Millicant** [comment]
Badass, thanks!  Let me upload what I've been working on, then I'll give you a heads up so you can start pasting this stuff in.

**Comment by capitaladot** [comment]
No doubt you've seen the branch on the new project.

**Comment by capitaladot** [comment]
Released.
