### ISSUE TITLE
Armigers

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2921]
**File:** 2022 - Questoris Household.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** Arminger has vehicle key word, but in is not on the rulebook.

**Comment by Mayegelt** [comment]
Will be fixed in next release

**Comment by Mayegelt** [comment]
Fixed in [v17.1.0](https://github.com/BSData/horus-heresy/releases/tag/v17.1.0)
