### ISSUE TITLE
Cataphractii Chaplain WS6 vs  Cataphractii Hekaton Paladin WS5

### ISSUE THREAD

**Issue by The4D6** [BSData/horus-heresy#2922]
**Describe the bug**
The cataphractii chaplain was being buffed to WS6 instead of the Cataphractii Paladin of the Hekaton-whatsit for Dark Angels.

**To Reproduce**
Add a Cataphractii centurion
Make him a chaplain (Notice that his WS increases to 6)
Make him a paladin of the Hekaton-thingy (notice that his WS stays 5)

**Expected behavior**
The chaplain should still be WS5.

**Comment by The4D6** [comment]
This is fixed in PR [2923](https://github.com/BSData/horus-heresy/pull/2923)

**Comment by Mayegelt** [comment]
Fixed in [v17.1.0](https://github.com/BSData/horus-heresy/releases/tag/v17.1.0)
