### ISSUE TITLE
Word Bearers Right of War: Last of the Serrated Suns shows roster error lacking compulsory troops when Gal Vorbak are taken as troop choice.

### ISSUE THREAD

**Issue by biochembri** [BSData/horus-heresy#2925]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - App being used to create lists [e.g. New Recruit, Bluescribe, Battlescribe]
 - App version
 - Data release version [e.g. v1.2.3]

**Additional context**

**Comment by Mayegelt** [comment]
Will be fixed on next push

**Comment by Mayegelt** [comment]
Fixed in [v17.1.0](https://github.com/BSData/horus-heresy/releases/tag/v17.1.0)
