### ISSUE TITLE
Solar Aux; Carnodon Turret options

### ISSUE THREAD

**Issue by Morturg** [BSData/horus-heresy#2926]
the turret options for the Carnodon Strike tank should not show twin-linked for the Volkite Culverin

it's singular

(the other options are twin-linked)

**Comment by Mayegelt** [comment]
Will be fixed next push

**Comment by Mayegelt** [comment]
Fixed in [v17.1.0](https://github.com/BSData/horus-heresy/releases/tag/v17.1.0)
