### ISSUE TITLE
Solar Auxilia Velitaris vokite charger bug

### ISSUE THREAD

**Issue by Morturg** [BSData/horus-heresy#2928]
**Describe the bug**
erroneously saying that Veletarii must have a Volkite Charger

they _must_ not, the can have either Chargers, or Storm Axes
**To Reproduce**![image](https://github.com/BSData/horus-heresy/assets/25342188/7ab83e3c-332b-4360-ae92-826693690054)

LI - Solar Auxilia  v19, HH2 v73

**Comment by Mayegelt** [comment]
I can't see to reproduce this. Can you post the full list you have?
It might be one of the other sub options that is triggering this.

![image](https://github.com/BSData/horus-heresy/assets/20280410/269c4879-727b-4f2e-bbaa-b3247056e405)

**Comment by Morturg** [comment]
you are looking at the wrong unit...

**Comment by Morturg** [comment]
![image](https://github.com/BSData/horus-heresy/assets/25342188/c8475f6e-89e6-4480-86a9-3e21494e9dca)

you need to give the storm selctions storm-axes, to see the bug

**Comment by Mayegelt** [comment]
> you have the wrong unit selected there, but sure, I'll post the full list

Don't look at the highlighted unit. The one above in elites of the same velataris isn't it?

**Comment by Morturg** [comment]
should be, yeah, when I give them storm axes, is when the error message pops...

**Comment by Morturg** [comment]
so it does,! it also seems to cose 10pts more, even though I have mine with a vexilia and a blast pistol...
![image](https://github.com/BSData/horus-heresy/assets/25342188/101df9ff-6229-4caf-9bca-ecc67578e6ef)

**Comment by Morturg** [comment]
it may  be the ordering of removing ones with volkites and replacing with storm axes... 

if you gave the sergeant the upgraded armour, that will explain the difference in 10pts

**Comment by Mayegelt** [comment]
> it may be the ordering of removing ones with volkites and replacing with storm axes...
> 
> if you gave the sergeant the upgraded armour, that will explain the difference in 10pts
> 
> if i start a new elites slot, I can make a storm section with no errors, at get to 280

Might have been a previous version of them before a change of the way it was formatted.

Anyway is there still an issue, or all resolved?
