### ISSUE TITLE
Castellax-Achea

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2929]
**File:** 2022 - Horus Heresy.gstz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** Thousand Sons Elite unit Castellax-Achea Automata has a 2+ save, this should be 3+

**Comment by Mayegelt** [comment]
Will be fixed in next push

**Comment by Mayegelt** [comment]
Fixed in [v17.1.0](https://github.com/BSData/horus-heresy/releases/tag/v17.1.0)
