### ISSUE TITLE
Proposal: text of per-Legion Legiones Astartes.

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#293]
I would like to include the per Legion Legiones Astartes text. Owning all published red books (and several black books; 3,4, and 6), I find hauling them to events to be a major pain, especially as Battle Scribe makes implementing every restriction a bit tricky (e.g. Vehicle count vs. Infantry, etc).

As such, it is my intention to contribute text for each of these.

I will plan to do this after the current re-factoring is done to avoid merge trouble.

**Comment by Millicant** [comment]
Agreed.  I've actually already begun this process.  There is quite a bit of said text in my updated versions.  Once I have a working edition, I'll create a branch so you can see and start inputting text.

**Comment by capitaladot** [comment]
I have this text ready to go, as well.

**Comment by capitaladot** [comment]
Released.
