### ISSUE TITLE
Kytan Ravager and Greater Brass Scorpion unavailable as standard Lord of War choices

### ISSUE THREAD

**Issue by swarm332** [BSData/horus-heresy#2930]
**Describe the bug**
Kytan and Scorpion are currently available under a praevian, however outside of traitor mechanicum armies they should be available as standard lords of war choices in the lord of war detachment in a traitor army using normal lord of war selection rules

**To Reproduce**
1. Select any traitor army except traitor mechanicum
2. No option to select Lord of war demon engines

**Expected behavior**
Option to select kytan and Scorpion should be available

**Comment by Mayegelt** [comment]
This will be fixed next update. It looks like the Praevian had the options tied to it incorrectly, as they need to be selected separately to the praevian, despite being linked to him.
Additionally as a LoW choice for Kytan and Scorpion, they are available to all as LoW are their own detachments.

**Comment by Mayegelt** [comment]
Fixed in [v17.1.0](https://github.com/BSData/horus-heresy/releases/tag/v17.1.0)
