### ISSUE TITLE
Night Lords Transports Missing Preysight

### ISSUE THREAD

**Issue by The4D6** [BSData/horus-heresy#2931]
Night Lords vehicles purchased as dedicated transports don't have the option to purchase the Preysight upgrade when they should be able to for 15pts

**Comment by Mayegelt** [comment]
This one is a bit of an unknown for me....
I am unsure if as a dedicated transport for a unit (and thus part of the unit) they will get Preysite if the unit buys it. Or if they will need to buy it individually.

Comments welcome on how you believe it should be.

**Comment by The4D6** [comment]
Myu understanding of this (having consulted with some night lords players) is that you need to buy it separately for the transport, as the transport is a separate unit even though they use the same force org slot

**Comment by TheRavingRaven** [comment]
Hello, as per the rulebook although dedicated transports do not take up a force organisation slot thy are counted as separate units for all intents and purposes.

**Comment by The4D6** [comment]
Land Raider Proteus Carrier
Spartan
Damocles Command Rhino
Storm Eagle
Kharybdis

**Comment by Mayegelt** [comment]
> Other DDTs include:
> 
> Land Raider Proteus Carrier Spartan Damocles Command Rhino Storm Eagle Kharybdis Dreadclaw Termite

I think most of them are already working from what I can see.

**Comment by The4D6** [comment]
Did this get completed?

**Comment by Mayegelt** [comment]
As far as I know it was

**Comment by The4D6** [comment]
Checked through this yesterday, can't see any cases where it's not applied, happy to fix it if we encounter issues or bug reports.
