### ISSUE TITLE
Knights Errant in other armies.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2932]
**File:** 2022 - LI - Custodes.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** The Knights-Errant are not avalible for Custodes army.

**Comment by Mayegelt** [comment]
Will be fixed next release. It looked as though they were not being available to any of the non-legiones astartes armies

**Comment by Mayegelt** [comment]
Fixed in [v17.1.0](https://github.com/BSData/horus-heresy/releases/tag/v17.1.0)
