### ISSUE TITLE
 Master of Signals consul option missing for terminator Centurions

### ISSUE THREAD

**Issue by mezzode** [BSData/horus-heresy#2935]
**Describe the bug**
Master of Signals is a missing consul option for Cataphractii and Tartaros Centurions

**To Reproduce**
1. Add Cataphractii or Tartaros Centurion to roster
2. Look under Legiones Consularis options

**Expected behavior**
Master of Signals being present as an option since not restricted in rules

**Screenshots**

![image](https://github.com/BSData/horus-heresy/assets/6572225/27b8f115-580a-4b80-b68a-29ad1a02e9b6)

![image](https://github.com/BSData/horus-heresy/assets/6572225/5e8d6ff5-066d-4335-bc91-e257e4561dc7)

![image](https://github.com/BSData/horus-heresy/assets/6572225/cecd6ed1-587f-4af0-8a9d-311957ca35ff)

**Device and data (please complete the following information):**
 - OS: Windows
 - App: Battlescribe
 - App version: 2.03.21
 - Data release version: v74

**Comment by Mayegelt** [comment]
Please recheck your book.
Teeny centurions can't be MoS
