### ISSUE TITLE
Terminators and heavy weapons

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2939]
**File:** 2022 - LA - Sons of Horus.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** If I select a terminator with any heavy weapon, sends a message of error. It saiys it has "1 too many selections of heavy weapons. Max 1" . But I only selected 1 in an unit of 6 members and I can purchase 1 for every 5 members

**Comment by Mayegelt** [comment]
Need a bit more info on this one.

**Comment by Mayegelt** [comment]
This one has all 4 types of termy with a single heavy weapon in a squad and no errors


![Screenshot_2023-09-13-22-18-12-270_net battlescribe mobile rostereditor](https://github.com/BSData/horus-heresy/assets/20280410/f2a10560-318a-431a-bf06-c7ded830f420)
