### ISSUE TITLE
Iron Hands inductii phosphex bomb cost error

### ISSUE THREAD

**Issue by Idunnoguy** [BSData/horus-heresy#2946]
**Describe the bug**
Phoesphex bombs cost 10 points for Iron Hands Inductii, but are incorrectly displayed as being free.

**To Reproduce**
1. Select a Tactical Squad
2. Click on the Inductii box
3. Check Sergeant upgrades

**Expected behavior**
Phosphex bombs should cost 10 points.

**Device and data (please complete the following information):**
 - OS: Android
 - App being used to create lists: Battlescribe
 - App version: [2.03.27
 - Data release version [v17.2.3]

**Comment by Mayegelt** [comment]
will be fixed next release
