### ISSUE TITLE
Iron Father Autek Mor and Shadrak Meduson should fill compulsory HQ slot

### ISSUE THREAD

**Issue by Idunnoguy** [BSData/horus-heresy#2947]
**Describe the bug**
Battlescribe displays error when selecting either Autek Mor or Shadrak Meduson, stating that you "must have 1 more selections from Compulsory HQ", which Autek Mor and Shadrak Meduson both fufill.

**To Reproduce**
1) Select either Iron Father Autek Mor or Shadrak Meduson as your HQ. 
2) Check on the roster errors sections. 

**Expected behavior**
There should be no roster error.

**Device and data (please complete the following information):**
 - OS: Android
 - App being used to create lists: Battlescribe
 - App version: [2.03.27]
 - Data release version [v17.2.3]

**Comment by Mayegelt** [comment]
Will be fixed in next release. Coder must have missed adding the category.
They must clearly be really popular as no one has pointed it out since they were added :D
