### ISSUE TITLE
FAQ for Relics should appear, mark them "campaign only".

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#295]
Relics of the Dark Age of Technology Clarification (HH4 – page 222)
The rules for Relics of the Dark Age of Technology, included in the Campaign Rules section of The Horus Heresy Book Four – Conquest, are intended for use with and acquired as part of narrative campaigns by prior agreement of all involved parties. In casual games, players should seek the agreement of their opponent before including these powerful items of wargear in their armies and they should not be treated as being part of the
standard army list.

**Comment by Millicant** [comment]
Agreed, that's why the relics currently have to be selected with a checkbox THEN a list.  If you want to make it more explicit, that's fine too.  

Let's do this post-1.16, since it works correctly now.
