### ISSUE TITLE
Iron warriors; Legionary with Options cannot equip beyonet and shrapnel bolter

### ISSUE THREAD

**Issue by Smithm231** [BSData/horus-heresy#2952]
When attempting to equip Legionaries in troop options, can add a bayonet then update to shrapnel bolters, but this comes up with an error once this happens

**Comment by Mayegelt** [comment]
Unfortunately the wording doesn't allow bayonet on Shrapnel Bolters, Banestrike Bolters, Asphex Bolters or any other variation of bolter.
