### ISSUE TITLE
Sisters of Silence Chamber limitations not working

### ISSUE THREAD

**Issue by Idunnoguy** [BSData/horus-heresy#2958]
**Describe the bug**
When selecting any of the Sisters of Silence units that don't have Chamber of Vigilance, Battlescribe does not give an error message when it should be giving one

**To Reproduce**
1. Select any Sisters of Silence unit that does not have the Chamber of Vigilance
2. Ensure you don't have an HQ with the corresponding Chamber
3. See the lack of an error message

**Expected behavior**
There should be an error message stating that you need an _X_ Chamber HQ to run up to three units with that same chamber

**Device and data (please complete the following information):**
 - OS: Android
 - App being used to create lists Battlescribe
 - App version: 2.03.27
 - Data release version: v17.3.1

**Comment by Mayegelt** [comment]
Will be fixed next release. It seems a list was given as "Parent" instead of "Force"
