### ISSUE TITLE
Warlord traits not displaying special rules that they give to the HQ

### ISSUE THREAD

**Issue by Idunnoguy** [BSData/horus-heresy#2959]
**Describe the bug**
These warlord traits that give special rules do not give the HQs those special rules when viewed. This isn't a complete list, just some of the ones I've noticed. Iron Hands warlord traits From Hel's Heart, The Eye of Vigilance, and warlord trait of the named character Shadrak Meduson. White Scars warlord traits Heroes Never Die. Space Wolves warlord traits Crown Breaker, and warlord trait of the named character Hvarl Red-Blade. The warlord trait of Sisters of Silence named character Jenetia Krole. The Salamanders warlord trait The Weight of Duty. And the Raven Guard warlord trait The Hidden Hand. 

**To Reproduce**
1. Select a HQ with the warlord trait in question or one of the unique named HQs
2. View the rules for the HQ

**Expected behavior**
The special rules that the warlord traits give, should be visible within the rules for the HQ like the other special rules.

**Device and data (please complete the following information):**
 - OS: Android
 - App being used to create lists Battlescribe
 - App version: 2.03.27
 - Data release version: v17.3.1

**Comment by Mayegelt** [comment]
These will be fixed next release
