### ISSUE TITLE
Emperor's Children named character warlord traits aren't visible

### ISSUE THREAD

**Issue by Idunnoguy** [BSData/horus-heresy#2960]
**Describe the bug**
None of the Emperor's Children named characters have their warlord traits visible when viewed.

**To Reproduce**
1. Select any of the Emperor's Children named characters (Eidolon, Saul, or Lucius)
2. Select any of them to be your warlords
3. View the rules of said unit

**Expected behavior**
The warlord trait of those named characters should be displayed the same way as other warlord traits.

**Device and data (please complete the following information):**
- OS: Android
- App being used to create lists: Battlescribe
- App version: 2.03.27
- Data release version: v17.3.1

**Comment by Mayegelt** [comment]
It looks like they are being included when you make them the warlord as a hide/unhide rule, rather than warlord trait section

**Comment by Mayegelt** [comment]
Will be fixed next release
