### ISSUE TITLE
Death Guard: Creeping Death RoW

### ISSUE THREAD

**Issue by Morturg** [BSData/horus-heresy#2964]
Proteus Land Speeder showing as Troop selection for creeping death, it shouldnt (it didn't until a recentish update, I pull from the repo)

![image](https://github.com/BSData/horus-heresy/assets/25342188/04747821-7ade-4d29-9998-e2914f765f9f)

**Comment by Mayegelt** [comment]
Will be fixed next release. Looks like an OR instead of an AND was missed. It wasn't RoW related, but just on DG.
