### ISSUE TITLE
Firestorm Redoubt

### ISSUE THREAD

**Issue by Morturg** [BSData/horus-heresy#2965]
![image](https://github.com/BSData/horus-heresy/assets/25342188/ad4f9a87-4ccb-487f-b2e6-a8e1a13de83e)

has 2 lascannons on it's profile, when it should be two mounted Icarus lascannons 
![image](https://github.com/BSData/horus-heresy/assets/25342188/da060773-3c68-4371-ba08-eddf153c58c3)

pg 228 main rule book (lascannon plus skyfire)

**Comment by Morturg** [comment]
it also loses sunder

**Comment by Mayegelt** [comment]
Will be fixed in next release
