### ISSUE TITLE
Armoured Breakthrough: Blood Angels Legion Predator (Troops): should lack turret, pintel options.

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#297]
From "Rite of War: Armoured Breakthrough"

> Armour of the Line: Legion Predator Strike Armour Squadrons (**armed with Predator cannon turret and sponson weapons only**) must be taken as compulsory Troops choices in the detachment, and may be taken as additional Troops choices."

**Comment by Millicant** [comment]
Nice catch.  I've implemented this in the 1.16 update since it is much easier to do with the ancestor modifier.
