### ISSUE TITLE
Cannot add Ætos Dios under new Lord of War detachment

### ISSUE THREAD

**Issue by DanDev69** [BSData/horus-heresy#2971]
**Describe the bug**
I cannot add the Ætos Dios to my loyalist Imperial Fists army list, nor is it in the Lord of War detachment.

**To Reproduce**

1. Create an Imperial Fists army list
2. Ensure Exemplary battles are enabled
3. Ensure Legacy units are enabled
4. Add a Crusade Force org chart
5. Add a Lord of War Detachment
6. Set the Allegiance to "Loyalist" in the Crusade force org chart.
7. Add the Allegiance to the Lord of War Detatchment
8. Set it to "Loyalist"
9. Add "VII: Imperial Fists" to the Lord of War Detatchment
10. Add Rogal Dorn in the Primarch category in the Crusade Force org chart.

from here you can observe that the Ætos Dios is not available under the Lord of War Detatchment.

**Expected behavior**
the Ætos Dios should be available under the Lord of War Detatchment. the current edition of the Legacy Units from GW specifies that the Ætos Dios is a Lord of War, not as a dedicated transport for Rogal Dorn.

**Device and data (please complete the following information):**
 - OS: Android, iOS
 - Battlescribe v2.03.27.341
 - (HH V2) Horus Heresy (2022) v84

**Comment by Mayegelt** [comment]
Will be fixed soon. Needed to change a "Force" to "Roster"
