### ISSUE TITLE
White Scars Centurion and Praetor don't have their correct movement

### ISSUE THREAD

**Issue by Idunnoguy** [BSData/horus-heresy#2972]
**Describe the bug**
The non-terminator armored Centurions and Praetors in White Scars have movement 7" when they should have movement 8"

**To Reproduce**
1. Select either a Centurion or a Praetor
2. View the unit
3. See error in movement

**Expected behavior**
The movement should be 8", not 7"

**Device and data (please complete the following information):**
 - OS: Android
 - App being used to create lists: Battlescribe
 - App version: v2.03.27
 - Data release version v17.4.0

**Comment by Mayegelt** [comment]
Should be fixed soon. I think this was one of those strange logic issues that it needed to have the code put in the right order
