### ISSUE TITLE
White Scars Praevian Automata & Corrupted Engines do not get the benefits of the White Scars special rule

### ISSUE THREAD

**Issue by Idunnoguy** [BSData/horus-heresy#2973]
**Describe the bug**
The Automata and Corrupted Engines which a Praevian allows you to select do not get the movement benefits of the White Scars special rule, which they should get. 

**To Reproduce**
1. Select a Praevian in White Scars
2. Select any of the Automata or Corrupted Engines
3. View the unit rules for the unit selected in 2.

**Expected behavior**
Vorax should be movement 9", Castellax should be movement 8", Blood Slaughterers should be movement 10", and Decimators should be movement 8".

**Device and data (please complete the following information):**
  - OS: Android
 - App being used to create lists: Battlescribe
 - App version: v2.03.27
 - Data release version v17.4.0

**Comment by Mayegelt** [comment]
Will be fixed next release
