### ISSUE TITLE
Thallax taken within White Scars via a Forgelord do not get the benefit of the White Scars special rule

### ISSUE THREAD

**Issue by Idunnoguy** [BSData/horus-heresy#2974]
**Describe the bug**
Thallax Cohort taken by a White Scars Forgelord do not get the benefit of the White Scars special rule, which they should get. 

**To Reproduce**

1. Select a Forgelord in White Scars
2. Select a Thallax Cohort
3. View the unit rules for the Thallax Cohort

**Expected behavior**
Thallax Cohorts have a movement of 8".

**Device and data (please complete the following information):**
OS: Android
App being used to create lists: Battlescribe
App version: v2.03.27
Data release version v17.4.0

**Comment by Mayegelt** [comment]
Will be fixed next release
