### ISSUE TITLE
Legiones Hereticus Pheonix Terminator Bug.

### ISSUE THREAD

**Issue by TheRavingRaven** [BSData/horus-heresy#2982]
Phoenix Terminators are still available as a retinue despite pg 107 of exemplry battles stating under "The Phoenician's Hubris" stating that they lose the "Pheonix Retinue" special rule.

Retinue tag must be disabled when Legiones Hereticus option is selected

OS: Android
App: Battlescribe

**Comment by The4D6** [comment]
Resolved in 17.4.2
