### ISSUE TITLE
Raven Guard Independent Character Options

### ISSUE THREAD

**Issue by CygnustheSwan** [BSData/horus-heresy#2984]
For the Raven Guard Legion Astartes special rule regarding Independent Characters and Corvid Pattern Jump Pack, this option is missing for Kaedes Nex. Kaedes Nex falls into the Raven Guard Legion Astartes, Independent Character and infantry requirements.

The option is not available. The option is also not available to add the Cameleoline as it's there for other unit and model types where it should be, but for Kaedes Nex, you cannot edit or add anything.

**Describe the bug**

**To Reproduce**
When going into the Kaedes Nex HQ option for Raven Guard Crusade Force Organization Chart, there is no ability to add the Corvid Pattern Jump Pack or the Cameleoline option. There are no options for infravisor for that matter too. 

**Expected behavior**
I would expect these options and rules to be available in Battlescribe.
![Kaedes Nex Issue](https://github.com/BSData/horus-heresy/assets/149201204/72009fbb-df98-44ef-a630-f9490ea0a4c3)

**Screenshots**

**Device and data (please complete the following information):**
 - App being used to create lists [e.g. New Recruit, Bluescribe, Battlescribe]
 - App version
 - Data release version [e.g. v1.2.3]

**Additional context**

**Comment by Mayegelt** [comment]
Unfortunately special characters are not allowed to take any modifications to their wargear that aren't listed in their profile.

**Comment by The4D6** [comment]
Any model with the Unique subtybe cannot have their wargear altered outside of specific options on their profile (eg Lucius being able to take Sonic Shriekers). This includes Kaedes Nex.

The only "Named Characters" this doesn't apply to are Exodus and Alpharius, because they lack the Unique subtype

**Comment by CygnustheSwan** [comment]
Kaedes Nex also have the unique sub type.

**Comment by The4D6** [comment]
I'm not enturely sure what you're trying to argue here, this issue is cut and dry.

If the character has the Unique sub-type, like Kaedes Nex, they cannot take a corvid-pattern Jump Pack.

![image](https://github.com/BSData/horus-heresy/assets/4020636/2b2658d0-0043-40c7-ba47-e65e9f2c5c91)

**Comment by CygnustheSwan** [comment]
Thanks. Which page is this on?

**Comment by The4D6** [comment]
Liber Astartes/Hereticus P95
