### ISSUE TITLE
Raven Guard Troop Transport Selections

### ISSUE THREAD

**Issue by CygnustheSwan** [BSData/horus-heresy#2985]
**Describe the bug**
For the Raven Guard Troop transport options Storm Eagle Gun Ship (Angel's Wrath), in the book, you can take up to 22 on the transport. Page 62 AoD Data Sheet (transport capacity)
Troops do not fill a bulky slot, so should just count 1 for 1. 

**To Reproduce**
1. Go to troops (all troop options including inductii)
2. Click each troop selection
3. See the right side pane with troop options and transport options
4. It says cannot have Storm Eagle Gunship

**Expected behavior**
I would expect for the Angel's Wrath Rite of War for troops and other applicable units to be able to select the Storm Eagle Gunship and also it holds up to 22, not 10. 
![Storm Eagle Gunship Capacity](https://github.com/BSData/horus-heresy/assets/149201204/e373f2aa-d0df-4585-a18e-c930322a9ec5)

**Screenshots**

**Device and data (please complete the following information):**
 - App being used to create lists [e.g. New Recruit, Bluescribe, Battlescribe]
 - App version
 - Data release version [e.g. v1.2.3]

**Additional context**

**Comment by The4D6** [comment]
Seconding Maye here, if the unit is over 10, they are not eligible to take a rhino
