### ISSUE TITLE
Raven Guard Command Squad Selections

### ISSUE THREAD

**Issue by CygnustheSwan** [BSData/horus-heresy#2986]
**Describe the bug**
Command Squad options are only present with Corvus Corax. Command Squads should be nested under HQ options with the option of adding a retinue to a primarch. Command Squads are not required to be the retinue of a primarch, they can be HQs, which they are.

**To Reproduce**
1. Go to HQ options. Command Squad is not an option there.
2. Click down on the primarch option. The command squads are there, but not in HQ where they should be nested with an option to add retinue for a primarch.

**Expected behavior**
I would expect command squads and options to be in the HQ section of Battlescribe. I would expect an option for a retinue under the primarch  selection as well. 
![Command Squad Issue Raven Guard](https://github.com/BSData/horus-heresy/assets/149201204/603cf459-6584-46dd-be0a-9f696bcd865b)

**Screenshots**

**Device and data (please complete the following information):**
 - App being used to create lists [e.g. New Recruit, Bluescribe, Battlescribe]
 - App version
 - Data release version [e.g. v1.2.3]

**Additional context**

**Comment by Mayegelt** [comment]
To take a retinue squad you need to be a Master of the Legion. This means they can be taken by a Praetor or Delegatus consol.

**Comment by Mayegelt** [comment]
![IMG_20231108_163039](https://github.com/BSData/horus-heresy/assets/20280410/de4114e4-77fb-4120-8b0f-ae765fe9f0c2)
