### ISSUE TITLE
[Anon] Bug report: 2022 - Titan Legions.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#2987]
**File:** 2022 - Titan Legions.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Secutarii Peltasts should be equipped with the following selection: Kyropatris Field Generator	

So long as a unit contains at least five models with a Kyropatris field generator, all models in the unit may re-roll failed Armour Saves of 1. In addition, if the unit contains at least 10 models with Kyropatris field generators then all Shooting Attacks made against the unit suffer a modifier of -1 to the Strength of the attack (to a minimum of Strength 1).

**Comment by The4D6** [comment]
Still requires release

**Comment by The4D6** [comment]
Resolved in 17.4.2
