### ISSUE TITLE
Ruinstorm Daemons Aetheric Dominion Selections in Militia

### ISSUE THREAD

**Issue by The4D6** [BSData/horus-heresy#2988]
Ruinstorm Daemon Brutes can only select from the following options for Aetheric Dominion:
- Malevolent Artifice
- Heedless Slaughter
- Encroaching Ruin

Ruinstorm Daemon beasts, swarms, and lesser daemons only get the selection of "None (Use this to switch between if you change your Whole Army Dominion)"

**Comment by Mayegelt** [comment]
I can't seem to replicate this issue.
Remember if you select a dominion on any unit, that is the army wide dominion, so every Daemon unit needs to take the same one.

**Comment by The4D6** [comment]
This has been fixed in NewRecruit's next update, as it was their issue not ours. Closing now.

**Comment by The4D6** [comment]
This has been fixed in NewRecruit's next update, as it was their issue not ours. Closing now.
