### ISSUE TITLE
Ruinstorm Daemon Brutes Infernal Armaments selection can exceed unit size

### ISSUE THREAD

**Issue by The4D6** [BSData/horus-heresy#2989]
In the Imperialis Militia list, the number of Infernal Armaments can exceed the number of Ruinstorm Daemon Brutes in a unit

**Comment by Mayegelt** [comment]
Looks like it's a missing min/max 1. This will likely be replicated in LA

**Comment by The4D6** [comment]
Can confirm it's replicated in LA

**Comment by The4D6** [comment]
My next question is:

If brutes only have one weapons option, why is it a separate selection?

**Comment by Mayegelt** [comment]
Force of habit rather than including the profile and any rules on the model. Also future proofs for other options.

**Comment by The4D6** [comment]
I guess?

I feel it would be better to be corect now rather than banking on GW ever updating any of the EB/Legacies content

**Comment by Mayegelt** [comment]
Giving it a min/max of 1 will resolve the issue. It is the same as how things like boltguns or whatever are included in units that have no options

**Comment by The4D6** [comment]
As you wanted future proofing I've split the weapons out to give us the option to add others in the future (and present choices like in the lesser daemons), but this also resolves the issue of over-selection by just giving the weapon to the unit

**Comment by Mayegelt** [comment]
Sounds good to me

**Comment by Mayegelt** [comment]
It would be worth making the same change in ruinstorm file as well

**Comment by The4D6** [comment]
Changes made to the ruinstorm catalogue and pushed
