### ISSUE TITLE
Blood Angels - Day of Sorrows Fearless

### ISSUE THREAD

**Issue by Elorlas** [BSData/horus-heresy#2992]
**Describe the bug**
Blood Angels infantry units with the Day of Sorrows rite of war selected are supposed to get Stubborn when within 6" of an Objective. Currently it's they're listed as having this rule, but also have a rule where they gain fearless instead if they already have stubborn, which they should not have.

**To Reproduce**
1. Make a Blood Angels army list
2. Select Day of Sorrows Rite of War
3. Select any Infantry unit

**Expected behavior**
Should only get Stubborn within 6" of an objective.

![Fearless](https://github.com/BSData/horus-heresy/assets/111255419/0d95915b-3d6e-4fcb-9909-eb6cf64e97f3)

**Device and data (please complete the following information):**
 - OS: Windows
 - Battlescribe
 - 2.03.21
 - Data release version v17.4.1

**Comment by The4D6** [comment]
I believe the reason that this is displayed is because Infantry get Heart of the Legion when below half strength, which then grants them Stubborn when on or near an objective. I would thus assume that this rite would then convert that to Fearless.

**Comment by Elorlas** [comment]
That is the case. But nothing says giving stubborn to a unit with stubborn upgrades it to fearless.

It's a point in one of the Space Wolves Rites of War, but it's not in the standard rules for everyone else.

**Comment by The4D6** [comment]
Bloody Claw gives you Fearless if you already have stubborn (or another rule that lets you ignore Ld modifiers like Inexorable) when it's called.

If you had Stubborn from being on an objective at the time Bloody claw was called, I'd argue you get Fearless, in the same way that you would get it from this.

**Comment by The4D6** [comment]
Ok, I have misinterpreted how this Rite worked. You are correct in that they shouldn't get Fearless as it specifically gives them nothing if they have Fearless.

**Comment by The4D6** [comment]
Resolved in 17.4.2
