### ISSUE TITLE
Add Allegiance selection to allied detachment by default

### ISSUE THREAD

**Issue by The4D6** [BSData/horus-heresy#2994]
Having to manually add the allied detachment selection it annoying and it means that some options seem "hidden" if you don't know to add it.

I know that there is an error message raised that prompts you to add one, but it would be preferable if the system added it for you.

I am currently looking in to implementing this, issue has been raised for visibility and feature tracking.

**Comment by nstephenh** [comment]
Does it not get automatically added, at least in new recruit?

**Comment by Mayegelt** [comment]
I couldn't work out how to make it work when I initially played with it.

I worked out that you could probably turn it into a category that had a min/max of 0 but sets to 1 if primary catalogue is allied detachment.
The like with how the Mortalis Assault FoC catagory is added to the legion/army type.
Some rework might be required for restrictions.

**Comment by The4D6** [comment]
@nstephenh it seems to in NR but not in BS

**Comment by Mayegelt** [comment]
#3260
