### ISSUE TITLE
Militia Cargo-8 Transport upgrade options incorrect

### ISSUE THREAD

**Issue by Jonathan-Blazeby** [BSData/horus-heresy#2995]
**Describe the bug**
The Militia's Cargo-8 Hauler's upgrades are currently incorrect. The armoured container upgrade is listed at 20pts, rather than the 10pts from the army list pdf. This may be because the 2 extra heavy stubbers (each 5pts) you can take with it have been (accidentally) rolled in, but these are in fact optional: _"Additionally, a model with this upgrade may take up to two additional Pintle Mounted heavy
stubbers (these weapons may not be further upgraded)."_

**To Reproduce**
Make a Militia list
Add a Cargo-8 Hauler
Add the Armoured Container upgrade

**Expected behavior**
Armoured Container upgrade should be listed at (and cost) 10pts. And Heavy stubbers should be a variable numbered choice between 1 and 3 (max 3 if armoured container, max 1 if not).

**Device and data (please complete the following information):**
OS: Windows
Battlescribe
2.03.21
Data release version v17.4.1

**Comment by The4D6** [comment]
Resolved in 17.4.2
