### ISSUE TITLE
Sons of Horus Carsoran Power Weapons can't be taken by a few units.

### ISSUE THREAD

**Issue by chronocobra** [BSData/horus-heresy#2999]
Carsoran power axes & tabars cannot be taken by a few units including (the sergeant can take the weapons but any "squad member w/ options" that can take a power weapon should be able to take these instead):

- Destroyer Assault Squads
- Despoiler Squads
- Assault Squads

**Comment by The4D6** [comment]
Resolved in 17.4.2
