### ISSUE TITLE
Ruinstorm Daemons Allied Restrictions Not Working

### ISSUE THREAD

**Issue by The4D6** [BSData/horus-heresy#3002]
Apparently, you can select an allied detachment if you have primary Ruinstorm daemons

Secondly, you can select allies if your Primary is ruinstorm daemons

Neither of these should be allowed, if nothing it should at least raise an error.

**Comment by The4D6** [comment]
@Mayegelt I'm not 100% sure how to approach this.

My initial thought is to have a flagged "message" much like the Lords of War reminder that appears if you have any detachment that uses the daemons faction, and then drops a special rule in to the army USRs.

Ideally I want to solve this in such a way that makes it more obvious to the user than just a flagged error.

**Comment by Mayegelt** [comment]
I'm not sure if you have already resolved this or not. But when I attempted to make a Crusade list as Ruinstorm and take an allied solar force it does give an error. It's not a great one as it is saying you can't have the ruinstorm daemons entry and vice versa, and if removed it says you need it (which is how we have previously handled some of the RoW which require them.
![image](https://github.com/BSData/horus-heresy/assets/20280410/1a281c2b-6d01-49db-b8f1-d91d98da45df)

A potentially annoying way to do it would be to to set hidden to all the units if roster contains an allied detachment. That might be a solution.

**Comment by The4D6** [comment]
I believe that error is tied specifically to the Daemons of the Ruinstorm allegiance entry. I didn't put this in, what I had wanted to include was another entry in the same section that explicitly states the army/allied restrictions (similar to the Lords of War thing).

Basically a more overt warning.

**Comment by The4D6** [comment]
I'm going to close this issue as not planned. If someone raises a complaint about it then I may revisit it in the future.
