### ISSUE TITLE
What happened to Horus?

### ISSUE THREAD

**Issue by HorustheWarmaster** [BSData/horus-heresy#301]
I haven't tested the other primarchs, but I cannot find Horus as a selectable option under Lords of War, even after selecting Sons of Horus, and Allegiance:Traitor as my Legion.  I'm assuming this is an error as I've done everything exactly as I have done it in previous list builds

**Comment by Millicant** [comment]
Not sure why this is happening.  I still have Horus as a viable choice under the listed circumstances.  Please re-load your roster, perhaps create a new one, and let me know if this still pops up.

**Comment by HorustheWarmaster** [comment]
Thanks for the fast response and I apologize for the post because it was user error- When I was creating the list I wasnt doing so as an "Age of Darkness" list. Thanks for looking into it, and sort for wasting your time on it!!!

**Comment by HorustheWarmaster** [comment]
Sorry not sort!

**Comment by Millicant** [comment]
No worries!  Thanks for letting me know.  :)
