### ISSUE TITLE
Ruinstorm Daemons Hammer of Wrath

### ISSUE THREAD

**Issue by The4D6** [BSData/horus-heresy#3014]
Currently. for a number of units, the Hammer of Wrath rule that they gain from Infernal Tempest is applied incorrectly as Hammer of Wrath (X).

This is the case even when Infernal Tempest is selected as part of Ætheric Dominion (Whole Army).

I believe this could be fixed by abstracting the Ætheric Dominion rule to a single, high-level selection, rather than one you need to make on both an army and a per-unit basis.

I am currently investigating a fix for this, results can be seen in the PR #3015

**Comment by The4D6** [comment]
So further investigation in to this seems to suggest that it has issues displaying the correct version of the rule when you have multiple conditional name changes.

I believe the root cause of this is that the roster is struggling to detect whether or not the Infernal tempest is selected, either on a per-unit basis or as an army-wide selection.

I still believe that the best way to do this is to remove the per-unit dominion selection and to have it as a single army-wide choice, then make the various special rules conditionally visible based on that selection. This is what I will be working towards on the experimental branch going forwards.

**Comment by Mayegelt** [comment]
I think the issue of the Army Wide thing is you then need to import it to all forces that might contain daemons. As it would need selecting at that point.
It can probably be done easy enough. But might look messy for those without daemons

**Comment by The4D6** [comment]
Sorry, I might just be being stupid, but why do you need to import them all?

My apologies if I've explained this badly, by army-wide I mean at the force level, not the roster level.

**Comment by Mayegelt** [comment]
It can't be at the roster level as the LoW can ha w different ones.
But what I was saying is for instance if you take an army like Word Bearers with Lorgar or Ebebus or just have a Esoterist. Or things like having a Rogue Psyker in Militia lists, allows you to take a small number of daemons. Those daemons would then require the army wide thing.

**Comment by Mayegelt** [comment]
I'm not sure of the interaction in this as well as per the statement above as I haven't checked the wording.
But in theory (based on wording) you could take a unit of Bound Daemons from an Esoterist or Lorgar or whatever with 1 dominion, but then also take a unit of Daemons of the Ruinstorm with a different dominion from the same Esoterist or Lorgar or whatever.

**Comment by Mayegelt** [comment]
I think the hammer of wrath rule could be fixed by splitting it into 2 rule links. Both with their own hide condition. Rather than 1 that tries to cover both.

But it is still a mess and probably needs a rework.

**Comment by The4D6** [comment]
I tried this and it doesn't seem to work.

I have some time this evening though so I'll take another look and try to do it that way.

**Comment by Mayegelt** [comment]
Rewrote my comment above. That has worked in the past

**Comment by The4D6** [comment]
Will investigate this evening in that case

**Comment by The4D6** [comment]
This has now been updated on #3015 to work in the following way:

### If a unit does not have HoW naturally
- Under a single Hammer of Wrath rule, it checks to see if there are 1 or more selections of Infernal Tempest in the force (not roster), as you can only have one selection from dominion force wide and there is error handling to make sure the user doesn't select more than one.
- If so, it makes HoW(1) visible

### If a uni has HoW(n) naturally
- Under a single HoW entry, it sets the name to HoW(n) if there are 0 selections of Infernal Tempest in the force (not roster)
- If there are 1 or more selections of Infernal Tempest in the force, it sets the name to HoW(n+1)

It doesn't check the unit's Dominion nor the Army's one specifically, it just looks for any number of selections.

@Mayegelt does that seem like a reasonable solution to you?
