### ISSUE TITLE
Raptora Cadre do not have Voidsheen Cloaks in their wargear displayed

### ISSUE THREAD

**Issue by Idunnoguy** [BSData/horus-heresy#3016]
**Describe the bug**
Sisters of Silence Raptora Cadres should have Voidsheen Cloaks, but battlescribe does not display them in the view option

**To Reproduce**
1. Select a Raptora Cadre
2. Click on the view button
3. Scroll down to the unit descriptions of the Raptora Cadre

**Expected behavior**

**Screenshots**
The unit descriptions should show the Voidsheen Cloaks in the same way it is displayed for the unit description for an Oblivion Knight Cadre

**Device and data (please complete the following information):**
 - OS: Android
 - App being used to create lists: Battlescribe
 - App version: v2.03.27
 - Data release version v17.4.2

**Comment by The4D6** [comment]
Fixed in PR #3019 

Will be live with next release

**Comment by The4D6** [comment]
Released in 17.4.3
