### ISSUE TITLE
Warmonger adds Legiones Hereticus

### ISSUE THREAD

**Issue by TheFiremind77** [BSData/horus-heresy#3017]
**Describe the bug**
I added a Cataphractii Centurion to an Iron Hands list (v36). I gave the centurion the Legiones Consularis: Warmonger title. When checking the centurion unit itself to change its wargear, the "Legiones Hereticus (X)" tag was added as an input bar, as if it were wargear (in the same heading as armor type choice, melee weapon choice, etc). 

**To Reproduce**
Described above. Create an Iron Hands crusade force list, add a centurion, give it Warmonger, and check the centurion's details. For additional details in case they are needed, the list had no other detachments, no selected Rite of War, and was assigned the Loyalist alliance. 

**Expected behavior**
I didn't expect warmonger to attach Legiones Hereticus.

**Screenshots**
Attached below.

**Device and data (please complete the following information):**
 - OS: Android
 - App being used: Battlescribe
 - App version: 2.03.27
 - Data release version: HH V2 v87

![Screenshot_20231124_023223](https://github.com/BSData/horus-heresy/assets/151922930/ff3bd83c-4341-4e29-89bb-53e6d86c6c0a)
![Screenshot_20231124_023226](https://github.com/BSData/horus-heresy/assets/151922930/b12bdace-b248-411f-a55e-d65c947e7796)
![Screenshot_20231124_023237](https://github.com/BSData/horus-heresy/assets/151922930/7bb42251-130b-44c0-bcd6-9fc6ec635948)

**Comment by The4D6** [comment]
Fixed in PR #3018

**Comment by The4D6** [comment]
Released in 17.4.3
