### ISSUE TITLE
Solar Auxilia Companion option for Blast Pistol and Charnabal Weapon is misspelled

### ISSUE THREAD

**Issue by Idunnoguy** [BSData/horus-heresy#3022]
**Describe the bug**
The option for a SA Companion to replace their Lasrifle for a Blast Pistol and Charnabal Weapon has a misspelling. The option currently says "Blast Pilstol" not pistol.

**To Reproduce**
1. Select a Tactical Command Section
2. Select the "May exchange Lasrifle for:" option
3. See error

**Expected behavior**
The option should say, "Blast Pistol & Charnabal Weapon"

**Device and data (please complete the following information):**
 - OS: Android
 - App being used to create lists: Battlescribe
 - App version: v2.03.27
 - Data release version v17.4.2

**Comment by The4D6** [comment]
Fixed, will be included in latest release

**Comment by The4D6** [comment]
Released in 17.4.3
