### ISSUE TITLE
Space Wolves Terminator Speaker of the Dead - incorrect loadout

### ISSUE THREAD

**Issue by GPFallaize** [BSData/horus-heresy#3032]
Any Terminator speaker of the dead is limited to 1 melee and 1 ranged weapon per terminator consul rules.

with the latest HH 1.2 FAQ,  it specifically states that the Master Crafted Power maul can be exchanged for another weapon.

master Crafted Power Mail RAW is in addition to the existing melee weapon option

Fix
Allow Speaker of the dead terminator consul to have a 2nd melee weapon option (defaulting to Master Crafted Power Maul, and allowing the user to switch the MC Power mail for either a Frost blade (Sword/Claw/Axe) or a Great Frost blade for the normal points costs

**Comment by The4D6** [comment]
For clarity, thay aren't _limited_ to one melee weapon, the implementation is just incorrect
