### ISSUE TITLE
Varagyr Thegn unable to take GFB in (Ranged) offhand

### ISSUE THREAD

**Issue by GPFallaize** [BSData/horus-heresy#3033]
Missing option for Great frost blade in ranged hand option.

please add as current configuration limits loadouts in Battlescribe (e.g a Thunderhammer + Great Frost Blade cannot be chosen)

**Comment by The4D6** [comment]
Hi there,

As the ranged weapon swap specifically says axe, claw, or sword, I don't think it's the correct implementation to be able to exchange the combi-bolter for a great frost blade.

**Comment by GPFallaize** [comment]
HiThe Thegn rules say “ may replace their frost blade for a great frost blade”. It does not make a distinction of which.As the offhand combi bolter can be replaced with a Frost Blade.  RAW this applies too.On the BS entry therefore1 upgrade combi bolter to frost blade 5ptsSub menu for frost blade selection, claw, sword,axe (no cost) Great frost blade (10pts)Sent from my iPhoneOn 11 Dec 2023, at 11:36, The4D6 ***@***.***> wrote:﻿
Hi there,
As the ranged weapon swap specifically says axe, claw, or sword, I don't think it's the correct implementation to be able to exchange the combi-bolter for a great frost blade.

**Comment by The4D6** [comment]
I believe this issue to be ambiguous and would want to see it clarified in an FAQ before implementing it

**Comment by Mayegelt** [comment]
Just looking at this one myself. Transitive property counts. So yes the Thien could swap.
Equally a regular Varagyr could in theory swap it's combi to a frost axe, sword, claw to then further upgrade to a powerfist, chainfist or thinderhammer.

**Comment by GPFallaize** [comment]
I need to double check the wording in the index.Sent from my iPhoneOn 11 Dec 2023, at 12:20, Mayegelt ***@***.***> wrote:﻿
Just looking at this one myself. Transitive property counts. So yes the Thien could swap.
Equally a regular Varagyr could in theory swap it's combi to a frost axe, sword, claw to then further upgrade to a powerfist, chainfist or thinderhammer.
