### ISSUE TITLE
New Recruit Missing Force Weapons

### ISSUE THREAD

**Issue by FiovreGuillem** [BSData/horus-heresy#3039]
![Screenshot_2023-12-08-09-32-58-93_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/BSData/horus-heresy/assets/139741837/53060b57-4466-4f5c-b91a-9fe91ed55633)

![Screenshot_2023-12-08-09-31-50-50_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/BSData/horus-heresy/assets/139741837/4a96de5a-0e5e-4270-b21f-33a9d611688c)

![Screenshot_2023-12-08-09-32-05-44_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/BSData/horus-heresy/assets/139741837/79e3872e-d97e-417f-8153-362a22e39647)
In New Recruit specifically Librarians lack the option to equip force weapons.

**Comment by The4D6** [comment]
![image](https://github.com/BSData/horus-heresy/assets/4020636/d531b6cc-fbdd-4c55-a8d3-f7a206100224)

**Comment by FiovreGuillem** [comment]
Embarrassingly I asked on a heresy discord server for assistance and at least three independent people including myself could not see it xd
