### ISSUE TITLE
[Anon] Bug report: 2022 - LA - Imperial Fists.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3048]
**File:** 2022 - LA - Imperial Fists.catz

**BattleScribe version:** 3.27.34

**Platform:** Android

**Dropbox:** No

**Description:** When choosing Indominus terminators as a IF, it allows the selection of the teleport strike when it should only be on Cataphractii and tartaros.

**Comment by The4D6** [comment]
Fixed
