### ISSUE TITLE
Indomitus terminators Row, Some points and Nomus Rhy'Tan's command squad

### ISSUE THREAD

**Issue by Kardiwargaming** [BSData/horus-heresy#3052]
Legacies of the Darkness file vers 1.2 some notes of mine : 

Indomitus Terminators are now able to be used as Compulsory Line troops in Pride of the Legion RoW. The ability to click it in BS seems to be missing.

Lord Chaplain Nomus Rhy'Tan is not able to add a Command Squad in BS. He is considered a Master of the Legion so I assume he should be able to?

Cassian Dracos Reborn was dropped to 250p in the latest and was added some other magenta notifications in his page
 
There might be also multiple other points changes in vers 1.2. Legacies file. Not sure if they've been corrected yet. :)

**Comment by The4D6** [comment]
Hi there, 

Please could you update to the newest data (and make sure to check the box to delete existing data) and then see if these issues persist? Cassian and the indomitus terminators were updated in the 18.0.0 release (December FAQ).

As for Rhytan, we will look in to fixing that in time for the v18.1.0 release in January.

**Comment by The4D6** [comment]
Rhy'Tan retinue issue is now fixed and will be live on the 8th.

The other issues mentioned were all addressed in 18.0.0.

Please make sure to update your data in the meantime.

**Comment by Kardiwargaming** [comment]
Truly sorry, I thought I had the most up to date files!
