### ISSUE TITLE
Ancient Rylanor not updated to new profile. 

### ISSUE THREAD

**Issue by Posh-Tim** [BSData/horus-heresy#3056]
Ancient Rylanor (Emporers Children Loyalist Unique Elite choice) doesn't have updated cost and statline boost to make him playable. Not sure if there is any issue with any of the other legacies content.

**Comment by The4D6** [comment]
Hi there,

Rylanor was updated in v18,0

Please can you update your data files and make sure to select the "delete previous data" option
