### ISSUE TITLE
Misc HQs currently unavailable in daemons of the ruinstorm detachments

### ISSUE THREAD

**Issue by groppcw** [BSData/horus-heresy#3058]
The following characters should be available in Daemons of the Ruinstorm detachments:
* Infernus Abomination
* Davinite Lodge Priest
* Expeditionary Navigator

They aren't necessarily great choices, but they are cheap characters you can use to absorb challenges for sovereigns, and can be taken in any traitor (or any, for the navigator) detachment as a non-compulsory HQ. While Daemons of the Ruinstorm blocks optional detachments, it doesn't block units from other army lists taken in its own detachments.

Hopefully this is a simple fix, since they're already available in (basically) every other detachment type.

Thanks!

**Comment by The4D6** [comment]
Added for next release
