### ISSUE TITLE
Atrapos Ocular Augmetics, potential "1 per 2000" error.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#306]
**File:** (HH) Mechanicum - Questoris Knight.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** Receiving error for Knight atrapos having ocular augmetics.  It is a legal upgrade as per pdf found online. 

To recreate,  create a roster with questoris knights as force and questoris knight crusade as catalogue,  select atrapos for hq choice and recieve error: questoris knight crusade army (questoris knight crusade army) had too many upgrades from may be upgraded with: (maximum 0)

Also, should be allowed to take one per 2000 points. Receiving error again for having one under 2000 points.... Matter was felt with previously a few weeks ago.

**Comment by Millicant** [comment]
Ocular Augmetics fixed.  Silly error on my part.  

This "per 2000 points" thing is going to remain an issue for me.  But, as I stated before, I will cave to popular pressure.
