### ISSUE TITLE
World Eaters Red Hands Destroyers 

### ISSUE THREAD

**Issue by twizted86** [BSData/horus-heresy#3064]
The Ravager with Heavy Weapon option can not be changed individually. When selecting the Thunder Hammer or Missle Launcher option it changes it on the others. I think they should be able to each choose their own option.

**Comment by The4D6** [comment]
Please can you clarify what you mean by "it changes it on the others" ?

**Comment by twizted86** [comment]
You can take 3 different ravagers with heavy weapons. If you change the weapon on 1 it changes the weapon on the other 2 to the same option

**Comment by Mayegelt** [comment]
I think "collective" might be ticked when it shouldn't be. Or the item is
linked to a collective rather than individual version of that is the case.

**Comment by The4D6** [comment]
A potential fix for this has been pitched but is awaiting feedback. This will not make it in to today's release and will be hotfixed when done.

**Comment by The4D6** [comment]
Resolved in #3071
