### ISSUE TITLE
 EC Kakophoni character options 

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#3065]
Looks like there is an issue with EC Kakophoni. The sergeant can't take the phoenix weapon upgrades because of the way it's been coded.

**Comment by The4D6** [comment]
Fixed

**Comment by The4D6** [comment]
Will fix this weekend

**Comment by The4D6** [comment]
Further inspection reveals that Kakophoni can't take a surgical augment as they already have sonic shriekers

Does this still need fixing?

**Comment by Mayegelt** [comment]
Any character in an EC army can take one. This is in addition to any they
get buy default.

So for instance phoenix termy can take one for the whole unit. Then the
sergeant can take 1 for himself then if you really want you go extreme then
if you are playing 3rd company elite, then the unit could take another.

**Comment by The4D6** [comment]
Fixed in linked PR
