### ISSUE TITLE
Imperial Fists HQs Cannot Swap Guns for Shields

### ISSUE THREAD

**Issue by The4D6** [BSData/horus-heresy#3069]
I may be wrong here, so feel free to correct me if I am.

Both kinds of Imperial Fists terminator praetors have the option to exchange a combi-bolter for a vigil storm shield for 10pts.

They should not have this option.

**Comment by Mayegelt** [comment]
There is some interaction that kept reappearing that shouldn't.
I think it's to do with command squads. The order in which it was hidden or showing ruining it. And if it read it one way it worked as intended. Then it failed to work the other way.

**Comment by Mayegelt** [comment]
Personally i preferred opting command squads out of the Group Selection Entry Link. And making a unique one for them. As having them linked to the genetic one has caused various issues that keep re-emerging for no apparent reason when the file is saved again.

**Comment by nstephenh** [comment]
I prefer it being a shared SSE but I can understand wanting to keep some separate, or adding some entries on if it's just one unit that should get them.
