### ISSUE TITLE
Tech Priest Auxilia - Ephmera Incursus and Battlesmith values

### ISSUE THREAD

**Issue by groppcw** [BSData/horus-heresy#3073]
In mechanicum, the Magos Auxilia in a Tech Priest Auxilia is listed as being able to take Ephemera Incursus; they cannot. (Artificia Machina, Artificia Cybernetica, and Anima Malefica all appear to work correctly.)

Additionally, they are listed as having "Battlesmith (X)"; this value should be 6+ for tech priests and 5+ for magos auxilia.

**Comment by The4D6** [comment]
Fixed in PR
