### ISSUE TITLE
AP wrong on Decimator Siege Claw

### ISSUE THREAD

**Issue by Knight-of-Infinite-Resignation** [BSData/horus-heresy#3077]
**Describe the bug**
Decimator Siege Claw should be AP2 but is AP3 on Battlescribe

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - App being used to create lists [e.g. New Recruit, Bluescribe, Battlescribe]
 - App version
 - Data release version [e.g. v1.2.3]

**Additional context**

**Comment by The4D6** [comment]
Fixed, issue was a simple typo.
