### ISSUE TITLE
Blood Angels Compulsory HQ Requirement

### ISSUE THREAD

**Issue by DeKarbon** [BSData/horus-heresy#3078]
**Describe the bug**
When creating a Blood Angels army, only Dominion Zephon satisfies the compulsory HQ requirement.

**To Reproduce**
1. Create a new roster.
2. Select Blood Angels
3. Add any HQ unit other than Dominion Zephon

**Expected behavior**
That any HQ unit satisfies the compulsory HQ requirement.

**Screenshots**
![Screenshot_20240115_114355](https://github.com/BSData/horus-heresy/assets/10284443/a13bc5ad-9613-4571-af54-8fe1acb8401b)

![Screenshot_20240115_114408](https://github.com/BSData/horus-heresy/assets/10284443/0d0f16a1-e0ee-4df8-b225-ae03f6b5a124)

![Screenshot_20240115_114750](https://github.com/BSData/horus-heresy/assets/10284443/e71af203-f2f5-42ec-a71a-02819b915fe2)

**Device and data (please complete the following information):**
 - OS: Android 14
 - App being used: Battlescribe Mobile
 - App version: v2.03.27.341
 - Data release version: Horus Heresy v97, Blood Angels v41

**Comment by The4D6** [comment]
Hi there,

Day of Revelation requires compulsory HQs to have a Warhawk Jump Pack.

Zephon has one, none of the other HQs you have selected do. 

I have tested this with and can confirm there is no fault.
