### ISSUE TITLE
Allied Mechanicum detachments incorrectly require a warlord choice

### ISSUE THREAD

**Issue by pmplant** [BSData/horus-heresy#3079]
**Describe the bug**
When creating a list with an allied mechanicum detachment, the army builder will report that the allied detachment requires a warlord. This is incorrect, only the primary detachment should require a warlord.

**To Reproduce**
1. Create a list with a primary detachment of some Legiones Astartes and an allied detachment of Mechanicum.
2. Create a valid list with a warlord selected in your primary deatchment.
3. There will be an error asking you to select a warlord for the allied detachment.

Example list in NewRecruit: https://www.newrecruit.eu/app/list/URWqu

**Expected behavior**
There should be no error asking for a warlord selection in the allied detachment.

**Screenshots**
Screenshot from NewRecruit
https://imgur.com/a/90Pkpm3

**Device and data (please complete the following information):**
 - OS: Chrome
 - App being used to create lists: New Recruit
 - App version: v233
 - Data release version: Mechanicum rev. 35

**Additional context**
N/A

**Comment by Mayegelt** [comment]
Just tried it myself.
Please make sure the Archmagos you presumably took does not have the Archimandrite techno Arcana. That particular one is required to be the warlord if selected due to Bonds of Vassalage.
It may be a case that to avoid this the option.coukd be set to hidden if allied detachment is selected.

**Comment by pmplant** [comment]
Hi Mayegelt. I linked an example list that exhibits the problem in NewRecruit that should be importable (see bottom). In this list I do not use Archimandrite, I use Malagra, and it still asks me to include a warlord.

**Comment by The4D6** [comment]
I've seen a similar issue crop up with NR a couple of times.

I'll do some investigation this morning as I think this might be an issue with the roster builder rather than the data

**Comment by Mayegelt** [comment]
> Hi Mayegelt. I linked an example list that exhibits the problem in NewRecruit that should be importable (see bottom). In this list I do not use Archimandrite, I use Malagra, and it still asks me to include a warlord.

Unfortunately the screenshot only shows the RG section.

**Comment by pmplant** [comment]
@Mayegelt 
Example list in NewRecruit: https://www.newrecruit.eu/app/list/URWqu

**Comment by Mayegelt** [comment]
> @Mayegelt Example list in NewRecruit: https://www.newrecruit.eu/app/list/URWqu

Thanks 

Seems to be an issue in New Recruit rather than Battlescribe itself using the BS app.
I'm sure it's going to be a rework or something to make it work on there end. But will be done if it can.

**Comment by The4D6** [comment]
If this is a NewRecruit issue can we close this?

**Comment by Mayegelt** [comment]
> If this is a NewRecruit issue can we close this?

I'd say leave it open, but rename it as a NR issue. When they sort it out then close it. As otherwise we are more likely to get repeat bug reports.

Maybe make a new catagory tag of "NR bugs/issues".

**Comment by nstephenh** [comment]
This appears to have been fixed by NR.
