### ISSUE TITLE
Adding missing fortifications options to Horus heresy 1.0

### ISSUE THREAD

**Issue by Reptiliam** [BSData/horus-heresy#3086]
I was hoping someone could add the fortress of redemption and sky shield landing pad to Horus Heresy 1.0 fortification options. as there are many people who stick to the 1.0 ruleset and would really appreciate- also someone adding Ork fan made rules by the Australians that made the Necrons would be great.

**Comment by The4D6** [comment]
Hi there,

We are no longer working on the 1.0 data set as it is no longer the official current version of the game.

However, should someone wish to do the work, we will happily look at and review any pull request made.

**Comment by Reptiliam** [comment]
I would do it if I knew how - they could just copy and paste the 7th edition buildings there and put them in Horus Heresy 1.0
