### ISSUE TITLE
Adding the cities of death force organization charts to Horus Heresy 1.0

### ISSUE THREAD

**Issue by Reptiliam** [BSData/horus-heresy#3087]
Would be great if someone could add the force organization charts from the 4th black book that contain the cities of death force organization cards - similar to the strategic raid FoCs from that book which battlescribe has

![IMG_6226](https://github.com/BSData/horus-heresy/assets/157253962/0609534a-43f1-471f-b381-432b7b2263f2)

**Comment by The4D6** [comment]
Hi there,

We are no longer working on the 1.0 data set as it is no longer the official current version of the game.

However, should someone wish to do the work, we will happily look at and review any pull request made.
