### ISSUE TITLE
Knights in mechanicum taghmata list under war machine detachment are missing carapace weapon upgrade options as well as certain Knights are missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#309]
**File:** (HH) Mechanicum - Taghmata Omnissiah.catz

**BattleScribe version:** 1.15.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Knights in mechanicum taghmata list under war machine detachment are missing carapace weapon upgrade options as well as certain Knights are missing. See 30k faq.

**Comment by Millicant** [comment]
What knights are missing? And what carapace weapon upgrade options are missing? More details are better, it saves valuable time.
