### ISSUE TITLE
Logos Lectora is adding an additional HQ slot.

### ISSUE THREAD

**Issue by Komrad33** [BSData/horus-heresy#3097]
**Describe the bug**
When Logos Lectora is selected it adds an additional HQ slot to the force org chart

**To Reproduce**
Select Logos Lectora in an Ultramarines list
allows for 4 HQ slots. 

**Expected behavior**
Logos requires an Additional Compulsory HQ in addition to what is normally required that is either a MOS or Damocles Rhino, but nowhere does it grant an additional HQ slot like other ROW's EX: the Nightlord's Swift Blade ROW that modifies the Force Org Chart directly. 

It should only have 3 HQ slots available.

**Screenshots**
![image](https://github.com/BSData/horus-heresy/assets/123283918/11c5a6eb-8f7a-41b9-a1c5-d44539a47295)
![image](https://github.com/BSData/horus-heresy/assets/123283918/0d911dca-e78d-4484-bf49-a514c22f267d)
![image](https://github.com/BSData/horus-heresy/assets/123283918/88a0703d-89cd-479b-b5bb-eadc95d00856)

**Device and data (please complete the following information):**
Win 11, IOS, Mac OS
New recruit/Battlescribe latest versions

**Additional context**

**Comment by nstephenh** [comment]
I don't think I'm inclined to agree with you here. Looking at the text for the force organization chart, not the infographic, there are Compulsory HQ slots, and optional HQ slots. Adding a compulsory slot doesn't remove an optional slot. Willing to hear other opinions @The4D6 @Mayegelt .

The swift blade I don't think is a fair comparison since it just changes the max number of HQs, which I take to be changing the max of optional HQs.

**Comment by Mayegelt** [comment]
Logos lectota only requires an additional compulsory. That means that out of the 3 HQ slots you have. 2 must be filled with compulsory H! Units. Of which in this case 1 must be a Damocles or MoS.
There are no additional slots added.

**Comment by Mayegelt** [comment]
To expand on the point I made above. There are no force entries for any unit that are "compulsory HQ" or "optional HQ" they are just HQ.
Otherwise you would end up with a situation that unless a unit had the support squad rule. You would not be able to take it in any optional.slot, as it would be compulsory, and only only have 1 compulsory HQ and 2 compulsory troops slots in a regular FoC.

**Comment by nstephenh** [comment]
When you originally implemented it you went the other way with it. The thing that trips me up here is that it's "additional". You have by default 1 compulsory HQ and 2 additional. Panoptica says 3 as well. 
I don't know that I agree and I won't stop anyone else from changing it but I don't particularly want to change it.

**Comment by Mayegelt** [comment]
It may have been myself miss reading, or one of the other people doing it (I can't remember if I did UM).

**Comment by Mayegelt** [comment]
> When you originally implemented it you went the other way with it. The thing that trips me up here is that it's "additional". You have by default 1 compulsory HQ and 2 additional. Panoptica says 3 as well. I don't know that I agree and I won't stop anyone else from changing it but I don't particularly want to change it.

Also if you note that the RoW says"Additional" but the FoC says "Optional" they are different.
In essence as put above you get 3 HQ slots. But one is compulsory (this means both it is not optional, you have to take it, but also must be filled by a unit that is allowed to fill a compulsory FoC slot appropriate to the one needing to be filled.)
The other 2 optional ones you do not have to take, and can be filled by both units that can fill compulsory slots and those that say they can not.

**Comment by nstephenh** [comment]
To me the wording isn't that different from salamander's "additional non-compulsory HQ choice" which is just an extra optional slot. Not that what fills it must have support squad or anything like that. The wording is that its "take an additional compulsory" so I guess I can see that meaning "a slot becomes compulsory"
These are the only instances of any "additional" slots. unfortunately.

**Comment by Mayegelt** [comment]
"A Detachment using this Rite of War gains a single additional non-Compulsory HQ choice, which may only be used to select a Legion Centurion with the Chaplain Consul upgrade."

The 2 key parts of that is "gains" rather than "must take" and thay it comes under "Effects" rather than "Limitations".

**Comment by The4D6** [comment]
I'm with Maye on this one, and I've asked the various UM players I know

You don't gain an extra slot, but you're required to take 2/3 HQs

**Comment by Komrad33** [comment]
I appreciate y'all looking at this. 

I know it's a tough one, but after 4 games now of "Battle scribe says..." And being a UM player, I took a closer look at BS/NR and saw it. 

The wording, as with all GW products is very confusing and as a technical writer for a flight department stuff like that drives me nuts! I can't tell you how much I appreciate the hard work y'all put into these data files.

**Comment by Mayegelt** [comment]
I think the big one to look at regarding this is the Salamanders RoW which in the **Effects** has
"A Detachment using this Rite of War gains a single additional non-Compulsory HQ choice, which may only be used to select a Legion Centurion with the Chaplain Consul upgrade."
Then under **Limitations** has
"A Detachment using this Rite of War must include at least one Legion Centurion with the Chaplain Consul upgrade."

![image](https://github.com/BSData/horus-heresy/assets/20280410/9ad4ad72-846d-46db-8e9b-681a8f33c959)

This is giving the additional Non-Comp HQ but then making it Comp by requiring it.
While the UM one only has it in the Limitations of  requiring an additional Comp HQ which has to be a MoS or Damocles.

**Comment by Mayegelt** [comment]
Will be fixed in #3302
The wording explains its an additional Comp HQ, not an additional HQ. This is so that if you take Guilliman you would still need to take a MoS/Damo and another comp HQ to have a legal army, which without them would be your Delegatus/Preator/Special Char + a MoS/Damo as 2 of the 3 choices.
