### ISSUE TITLE
Solar Auxilla or Imperialis Militia minimum + Mech allied detach

### ISSUE THREAD

**Issue by giloushaker** [BSData/horus-heresy#3099]
**Describe the bug**
The `Solar Auxilla or Imperialis Militia` category is only added on the `Imperialis Militia` entry if there is `Templar Assault (IF)`,
which (allegedly) is not required for a Mech allied detach

**To Reproduce**
1. Go to (https://www.newrecruit.eu/app/list/zWcuM)
2. Scroll and and click "Import List"
3. See error in the roster

**Expected behavior**
No Error

**Device and data:**
 App being used to create lists: New Recruit

**Additional context**
https://discord.com/channels/736936369670193332/1202756964325793822/1202765438446997564

**Comment by The4D6** [comment]
This is an issue with NewRecruit, not with our data set, so it is being handled by them

**Comment by giloushaker** [comment]
The warlord one is NewRecruit specific. i fail to see how this one is an issue with NewRecruit.

**Comment by nstephenh** [comment]
@The4D6 I'm reopening this

**Comment by The4D6** [comment]
@nstephenh @Mayegelt 

Please can you guys try to repro this issue in BattleScribe as I cannot

**Comment by giloushaker** [comment]
Seems its just BattleScribe not showing that error, even though it should.
