### ISSUE TITLE
Arioch power claw - warlord titan

### ISSUE THREAD

**Issue by Hasfodel** [BSData/horus-heresy#311]
New for the warlord Titan :
Possibility of adding a Vulcan Mega Bolter to the wrist of a Arioch Power Claw for 75pts
Can you add it to all the catalogues the Titan appear

**Comment by Hasfodel** [comment]
And add the full rules on dah weapn not only choice to take it ;)

**Comment by Millicant** [comment]
This is a tough one.  It's not a big update, but it requires me to access every single catalogue to update this.  And, seeing as how there can't be more than a handful of people that own Warlord Titans, have the Vulcan Mega Bolter on an Arioch Power Claw, play Horus Heresy, AND use these catalogues... This is probably going to get slid into the post-BS update.  It will be extraordinarily easy there and I can focus a bit more on getting everything transferred over.
