### ISSUE TITLE
Autek Mor has wrong warlord trait

### ISSUE THREAD

**Issue by Idunnoguy** [BSData/horus-heresy#3117]
**Describe the bug**
Autek Mor has the Tyrant's Wrath warlord trait when he should have Bloody-Handed. However the rules for Autek are confusingly written where his special rules note Tyrant's Wrath, but in the little box that explains his special rules it says that he uses Bloody-Handed

**To Reproduce**
1. Select Autek More
2. Make him your warlord
3. View Autek Mor

**Expected behavior**
Autek Mor should have the option to use Bloody-Handed as his warlord trait. Maybe make a little box that let's you swap between Bloody-Handed and Tyrant's Wrath depending on how the players decides to rule this weirdly written profile

**Device and data (please complete the following information):**
 - OS: Android
 - App being used to create lists: Battlescribe
 - App version: v2.03.27
 - Data release version v18.2.0

**Comment by nstephenh** [comment]
I think having both is reasonable here, as he doesnt have the special rule in his text box because it's not in his special rules list. It's unclear which thing the developers meant to update so until we get a FAQ, not sure if we can swing either way on this.

**Comment by Mayegelt** [comment]
If looks as though in legacies v1.0 and v1.1 he had his own unique warlord trait (Tyrant's Wrath). However they changed (but didn't highlight that they had) his warlord trait to be bloody handed, and the rule Tyrants Wrath no longer exists in any current document.
V1.1
![Screenshot_2024-02-13-18-52-37-988_com adobe reader](https://github.com/BSData/horus-heresy/assets/20280410/cda27dcf-54dd-4921-890c-2f0e04b72e2a)

V1.2
![Screenshot_2024-02-13-18-52-49-045_com adobe reader](https://github.com/BSData/horus-heresy/assets/20280410/aa1ef5e6-fa88-4241-8924-5dd12b2ba8dc)

**Comment by Mayegelt** [comment]
> So we change to Bloody Handed then?

Yep
