### ISSUE TITLE
Legiones Hereticus Emperor's Children rite of war Children of the Maraviglia validation issue

### ISSUE THREAD

**Issue by edvinullman** [BSData/horus-heresy#3119]
**Describe the bug**
The Children of the Maraviglia rite of war requires an allied detachment of either Solar Auxilia or Imperialis Militia of at least 4 units. This fails to validate.

**To Reproduce**
Create a list with a Legiones Hereticus Emperor's Children Crusade force.
Apply the Children of the Maraviglia rite of war
Add an Allied Detachement force of either Solar Auxilia or Imperialis Militia, which satisfies the criteria of at least 4 units strong.
See validation error. 

**Expected behavior**
The list should validate.

**Screenshots**
<img width="837" alt="image" src="https://github.com/BSData/horus-heresy/assets/6905723/6ef81b9e-0b2c-412d-b734-7e697ef66f13">

**Device and data (please complete the following information):**
 - OS: MacOS Safari
 - App being used to create lists: New Recruit
 - App version v235

**Comment by Mayegelt** [comment]
Additional point for LH EC. They seem to not be able to take the Inductii despoilers. I believe they should be able to do so.

**Comment by edvinullman** [comment]
I'm not 100% sure they are, RAW seems to require a Legiones Astartes(X) (page 225, Siege of Cthonia), which get's replaced with Legiones Hereticus(X) (page 106 Exemplary Battles vol 1)
This might be something which will be FAQed away, but as it stands right now I don't think Inductii can be taken by LH EC

**Comment by The4D6** [comment]
![image](https://github.com/BSData/horus-heresy/assets/4020636/c6c4dce8-77a7-48ac-839f-fa23562924fd)

LH armies can take Inductii as per the Exemplary Battles book FAQ

**Comment by The4D6** [comment]
@nstephenh did we ever get to the bottom of whether this was actually a BS vs NR error that we actually need to fix?

**Comment by nstephenh** [comment]
NR made some changes to the force modifiers yesterday, I'll try and validate this.

**Comment by edvinullman** [comment]
@The4D6 Good to know! Thanks!

**Comment by nstephenh** [comment]
It looks like this rite of war is coded a couple of ways, there's a checkbox "children of the maraviglia allies restriction" on each unit, which looks like it's working, and a half-coded second condition that's using the same logic as Liberation Force, but it doesn't apply the condition "Solar Auxillia or Imperialis Militia", which was only applied in a templar assault for some reason.
