### ISSUE TITLE
Master of armor has decurion selection

### ISSUE THREAD

**Issue by nstephenh** [BSData/horus-heresy#3124]
Need to filter it to be "if ancestor is not master of armor"

**Comment by The4D6** [comment]
Are we sure that you can't add a Decurion to a master of armour?

They are a Predator or Sicaran squadron selected as an HQ choice so I don't see why they shouldn't be allowed to take one

**Comment by The4D6** [comment]
Unless there's something in the Decurion entry that specifically  forbids it

**Comment by Mayegelt** [comment]
Decurion and MoA can be in the same tank

**Comment by nstephenh** [comment]
Oh shoot you are right. I was looking at the list of 4 models, but the master of armor is still a sicaran or a predator model, it just has the master of the legion special rule and a warlord trait.
