### ISSUE TITLE
[Anon] Bug report: 2022 - LA - Imperial Fists.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3127]
**File:** 2022 - LA - Imperial Fists.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** Imperial Fist Command Squad Terminator's Storm Shields have been removed from Battlescribe.

**Comment by nstephenh** [comment]
Context: https://discord.com/channels/736936369670193332/1208196810556964955

**Comment by realsnice** [comment]
Additionally along side the shield not being selectable there is a related issue that appears with this unit when the regular PDF is generated. The tartaros command squad reads as having every ranged weapon option selected. [
[War Hounds (1).pdf](https://github.com/BSData/horus-heresy/files/14317255/War.Hounds.1.pdf)
![image](https://github.com/BSData/horus-heresy/assets/160292715/bfb76bfd-d7d5-4566-a456-16195d72badf)
only a combi bolter is selected in this list.

https://www.newrecruit.eu/app/list/ZsYrJ

**Comment by The4D6** [comment]
![image](https://github.com/BSData/horus-heresy/assets/4020636/c72fdcbd-28b8-48b9-8426-a8b244f7bf29)

![image](https://github.com/BSData/horus-heresy/assets/4020636/f469413f-069a-4b34-9263-e86fcc6bc67d)

They both still appear to be able to be selected

**Comment by The4D6** [comment]
Oh no wait I understand the issue, sorry, not been awake long

My apologies then, this one is on me as previously the praetors had the cheap option to replace a ranged weapon with a shield like a command squad does

I forgot that the ancestor of the command squad is the unit it's attached to

Needs changing from the praetor unit to the specific entry that is the praetor

Will fix when I'm home this afternoon

**Comment by realsnice** [comment]
Thanks for taking this up!

**Comment by nstephenh** [comment]
Sounds like we fixed this but can someone confirm?

**Comment by Mayegelt** [comment]
This seemed to have been fixed
