### ISSUE TITLE
Firewing Enigmatus Cabal Points

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3130]
**File:** 2022 - LA - Dark Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Firewing Enigmatus Cabal is undercosted. Should be 150 points, it’s 100 currently.

**Comment by nstephenh** [comment]
User needed to update their data. This was changed in 2f3f83222bce9572b4db0a5bce87a6b1522427b9.
