### ISSUE TITLE
HHV1

### ISSUE THREAD

**Issue by LachrimallusExterminator** [BSData/horus-heresy#3131]
Is there a page for Horus Heresy 1 bug fixes? I understand it would be low priority, but there’s a Mournival unit I was hoping to have added. If it can’t happen, then I’ll do related lists in Excel etc.

![IMG_1276](https://github.com/BSData/horus-heresy/assets/84422145/dbdbe0d7-4f63-4c3a-a211-3153adb518e8)

Thanks

**Comment by The4D6** [comment]
This repository is for the HH2.0 dataset.

If you wish to raise an issue with HH1.0, please raise it here: https://github.com/BSData/horus-heresy-1e/issues
