### ISSUE TITLE
Questoris Household: Putrid Corruption loads incorrect rule for Knights

### ISSUE THREAD

**Issue by Heatedpete** [BSData/horus-heresy#3140]
**Describe the bug**
For Traitor-aligned Knights using Dark Blessings upgrades from the Battle of Felweather Keep Exemplary Battles document, the Putrid Corruption upgrade loads the incorrect special rule for the Knight unit.
As opposed to loading text for the Putrid Corruption upgrade from page 8 of Felweather Keep, Putrid Corruption instead loads the Putrid Corruption Aetheric Dominion rule from page 3 of the Daemons of the Ruinstorm army list
This has been observed on the Knight Atrapos, Knight Styrix, and the Knight Questoris unit entries.

**To Reproduce**
1. Create a Mechanicum Army List with the Questoris Household force organisation chart
2. Set allegiance to Traitor
3. Create a Knight unit from within the Lords of War section of the roster creator (tested w/ Atrapos, Styrix and Questoris variants) and apply the Putrid Corruption option from the Dark Blessings list
4. View the army list entry for the Knight unit

**Expected behavior**
Knight should have the Putrid Corruption entry (-2 Movement + Unrelenting special rule) loaded from p8 of the Battle of Felweather Keep Exemplary Battles pdf

**Screenshots**
[Screenshot for Knight Atrapos linked from Discord](https://cdn.discordapp.com/attachments/385125950204936193/1212159764872568932/Screenshot_20240227-221001.png?ex=65f0d2c0&is=65de5dc0&hm=8e7a975cfacfb4281054ae1fb79f4b1a3f1b15a7b2730a191ecd8056f133cddc&) (using link as it's far bigger than the post to capture both unit name and rule error)

**Device and data (please complete the following information):**
 - OS: Android
 - App being used to create lists: Battlescribe
 - App version: v2.03.27.341
 - Data release version: Horus Heresy v18.2.0

**Additional context**
N/A

**Comment by The4D6** [comment]
@nstephenh this also seems to be the case for the Formless Distortion chaos knight buff/boon/thing

I suspect this came out of the duplicate remover script

**Comment by The4D6** [comment]
![image](https://github.com/BSData/horus-heresy/assets/4020636/ae4bb2c5-8780-48ad-9170-2d8e213ba448)
Looks to have the wrong text
