### ISSUE TITLE
REward of Treachery Dawn Breaker Cohort

### ISSUE THREAD

**Issue by BluFalc11** [BSData/horus-heresy#3141]
When I select "Dawn Breaker Cohort" from the Blood angels for a rewards of treachery option in an alpha legion army they retain the Legion Astrates Alpha Legion rule as well as the abillity to take weapons of perdition in addition to the Alpha legion armory. They should become Alpha Legion with Access to the Alpha Legion armory only

**Comment by Mayegelt** [comment]
Because it's listed in the unit entry it overrides various legion only restrictions.
The same goes with units like palatine blades taking augments.

![IMG_20240229_114527](https://github.com/BSData/horus-heresy/assets/20280410/246874cd-daf7-415a-a526-7fa3516b8b74)
