### ISSUE TITLE
Kratos Pintle Weapons - Wrong Combi-Weapons

### ISSUE THREAD

**Issue by The4D6** [BSData/horus-heresy#3146]
![image](https://github.com/BSData/horus-heresy/assets/4020636/499a16fb-4cc3-4798-b970-8ab4c376c37d)
 A kratos tank describes a combi-grenade launcher as magna when it should be minor, and also it is spelled wrong.

**Comment by The4D6** [comment]
![image](https://github.com/BSData/horus-heresy/assets/4020636/1faaeac0-b675-43a1-af9c-cc3fcedcdf51)
Actually, multiple of the combi weapons are wrong here

**Comment by nstephenh** [comment]
I looked to see if we could make all pintle-mounted weapons a shared selection entry but it looks like the decurion makes that logic at least a little bit more complex than I was willing to do this morning.
