### ISSUE TITLE
Battle for Beta Garmon Content

### ISSUE THREAD

**Issue by nstephenh** [BSData/horus-heresy#3147]
- [X] New force/cat: Blackshields - #3173
- [x] New force/cat: Shattered legions
- [x] New Space Marine Units
- - [x] Horus Aximand - Sons of Horus - #3176
- - [x] Tybalt Marr - Sons of Horus
- - [x] Hibou Khan - LA Library, import into white scars and shattered legions
- - [x] Shadrak Meduson - LA Library, import into iron hands and shattered legions (an existing character, needs to be updated. see issue #3272)
- - [x] Endryd Haar - Blackshields 
- - [x] Legion Optae - LA, Everybody can take!
- - [x] Legion Company Command Squad - LA, Everybody can take!
- - [x]  Legion Overseer consul - LA, not a new unit per say, but you get the idea.  (#3258)
- [X] New Solar Auxilia Units - #3176
- [x] Solar Auxilia -> legions auxilia rules
- [x] New Solar Auxilia Cohort (Reconnaissance Pattern Cohorts)

For Shattered Legions, I think we're fairly agreed that we won't be changing all units to allow you to select which models are which legion. This would be extremely difficult on units that are collective entries. 
We'll probably start with just giving a selection for the army and then add a selection to characters (for wargear?) and then consider adding a selection for models that aren't collective.

**Comment by The4D6** [comment]
Blackshields PR -> #3173
