### ISSUE TITLE
Iron Warriors in the Moritat error

### ISSUE THREAD

**Issue by DanD84** [BSData/horus-heresy#3148]
Iron warriors dice Moritat can't not equip 2 shrapnel pistols with out there saying there is an error

**Comment by nstephenh** [comment]
This seems specific to new recruit, I'll talk to the devs.

**Comment by nstephenh** [comment]
I'm also not entirely sure if you can take 2 shrapnel bolters without paying 2 points or 4 points. I'll ask around.
Any model with the Legiones Astartes (Iron Warriors) and Independent Character special rules may exchange **a** bolt
pistol for **a** shrapnel pistol or a bolter for a shrapnel bolter for no additional points cost.

Any unit composed entirely of models with the Legiones Astartes (Iron Warriors) special rule may upgrade all bolt pistols
in the unit to shrapnel pistols, and/or all bolters for shrapnel bolters and/or all heavy bolters for shrapnel cannon for a
cost of +2 points per weapon.

**Comment by The4D6** [comment]
![image](https://github.com/BSData/horus-heresy/assets/4020636/7f4aace7-db63-4df0-8080-29c70c4e4a9c)
I can't seem to see what the issue is, you can select the shrapnel pistols for a moritat

**Comment by The4D6** [comment]
> I'm also not entirely sure if you can take 2 shrapnel bolters without paying 2 points or 4 points. I'll ask around. Any model with the Legiones Astartes (Iron Warriors) and Independent Character special rules may exchange **a** bolt pistol for **a** shrapnel pistol or a bolter for a shrapnel bolter for no additional points cost.
> 
> Any unit composed entirely of models with the Legiones Astartes (Iron Warriors) special rule may upgrade all bolt pistols in the unit to shrapnel pistols, and/or all bolters for shrapnel bolters and/or all heavy bolters for shrapnel cannon for a cost of +2 points per weapon.

You can't take two bolters on a moritat I don't think as you have to pay 2pts for the first one and there's not an option to buy a second

**Comment by DanD84** [comment]
It's not the bolters it's the pistols you can select them for sure but you end up with the error for an invaded selection
![Screenshot_20240324_143656_net battlescribe mobile rostereditor](https://github.com/BSData/horus-heresy/assets/105502634/bbb6699c-5403-4ebd-bb2a-af6d089430ac)

**Comment by Mayegelt** [comment]
It needs the limit of max 1 in parent to be made max 2 I think just for that case. I don't think there are others that get the 2 options for a bolt pistol or trade for X. While the moritat gets the "2nd bolt pistol" option.

**Comment by nstephenh** [comment]
> You can't take two bolters on a moritat I don't think as you have to pay 2pts for the first one and there's not an option to buy a second
@The4D6 

Sorry I meant bolt pistols. 



> It needs the limit of max 1 in parent to be made max 2 I think just for that case. I don't think there are others that get the 2 options for a bolt pistol or trade for X. While the moritat gets the "2nd bolt pistol" option.

@Mayegelt  But why is max 1 in parent applying to the second selection entry group? And if we make it max 2 in parent then you'd be able to select 2 in that seg and 1 other pistol in the 1.5 selection entry group.

Also I'm not seeing this issue on battlescribe destkop, but from the screenshots clearly it's happening in battlescribe mobile.

**Comment by nstephenh** [comment]
Not new recruit specific, turns out the shared box was just checked, unchecking it fixed the issue, and it didn't hot reload for me.

**Comment by DanD84** [comment]
So is this fixed now? Nothing has changed on the app? I've updated the file too. Is there a delay? Also if it is fixed thank you so much this has been bugging me for like months hahaha

**Comment by Mayegelt** [comment]
> So is this fixed now? Nothing has changed on the app? I've updated the file too. Is there a delay? Also if it is fixed thank you so much this has been bugging me for like months hahaha

You need to wait until after the next release

**Comment by DanD84** [comment]
Awesome thank you guys so much :)
