### ISSUE TITLE
Sabre tank pintle weapons

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#3149]
Seems like there is an issue when selecting pintle weapons on a sabre squad.
If you select one for 1 of them it makes all of them take it. You should be able to pick individually.

**Comment by nstephenh** [comment]
Are you having this issue in new recruit or in battlescribe? I'm not having this issue in either.
There is however an issue if if you give one a shrapnel, it hides the heavy bolter for everyone.

**Comment by Mayegelt** [comment]
It was on BS on mobile. Didn't try desktop.

The sharpnel one is as it should be as that is a unit wide upgrade.

**Comment by Mayegelt** [comment]
Side note. Works fine on multiple Land raider carriers taken as HS slot. Just seemed to be with Sabres

**Comment by Mayegelt** [comment]
Was an issue of the links being to Collectives, rather than individual weapons. This is resolved in my latest pull request (if it goes through).
