### ISSUE TITLE
Night Lords Tartaros Praetor Wargear

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3151]
**File:** 2022 - LA - Night Lords.catz

**BattleScribe version:** 2.03.21

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Tartaros Praetor can't take the chainglaive or Headman's Axe when they are allowed to

**Comment by Mayegelt** [comment]
This seems to have been fixed already
