### ISSUE TITLE
Imperial Fists Assault Sergeants can't take solarites instead of bolt pistols

### ISSUE THREAD

**Issue by The4D6** [BSData/horus-heresy#3162]
An imperial fist assault squad sergeant can swap his chainsword for a solarite power gauntlet, but he can only swap his bolt pistol for a power fist.

He should be able to swap his bolt pistol for a gauntlet as an alternative.

**Comment by Mayegelt** [comment]
Fixed in #3302
Also added the option to Nullificators & Sergeant.
