### ISSUE TITLE
Solar pattern Cohort Cortex controllers

### ISSUE THREAD

**Issue by MaelRH** [BSData/horus-heresy#3169]
Solar pattern Cohort is incorrectly giving the option for the Legate Marshal, Auxilia Captain, and Auxilia Marshal to take Cortex Controllers. 

Once you select the Solar pattern Cohort on the Legate Marshal the option appears. 

This should not be the case as only the Iron pattern Cohort gives the option.

**Comment by Squiggzz** [comment]
I've noticed that the Cortex Controller is not showing as an option for the Iron Pattern Cohort Legate Marshal. Maybe this is related, or maybe not, I don't know, but anyway, I wanted to add that detail here.
