### ISSUE TITLE
Solar Auxilia allied detachment armoured fist cohort HQ issue 

### ISSUE THREAD

**Issue by Petitionerscity** [BSData/horus-heresy#3177]
**Describe the bug**

Hi folks, I noticed an error with an allied detachment of solar Auxilia which chooses the armoured fist cohort doctrine. While a primary detachment does require a single command tanks, this is not required for an allied detachment (or even an option) - instead it should still pick a legate marshall as its sole compulsory HQ.

![Screenshot_20240414-112640~2](https://github.com/BSData/horus-heresy/assets/133539150/69d4e682-f379-4940-b997-6924e9dea031)

As you can see this second point only applies "In a primary detachment using this cohort doctrine", not in an allied detachment. Instead the cohort would still need a legate marshall to obtain this.

However currently one is told of an error if a command tank isn't chosen in allied detachment using this doctrine. Eg:

![Screenshot_20240414-112918](https://github.com/BSData/horus-heresy/assets/133539150/f565b265-3dba-414a-8840-64103a2abfec)

**Expected behavior**
A command tank should not be a mandatory HQ for (or even available to) an allied detachment with the armoured fist cohort doctrine.

**Comment by nstephenh** [comment]
@Mayegelt Relevant to our recent discussions about where the entry for cohort doctrines are, though I think this should be relatively easy to fix.

**Comment by Mayegelt** [comment]
Fixed in https://github.com/BSData/horus-heresy/pull/3302

**Comment by Petitionerscity** [comment]
Thank you!
