### ISSUE TITLE
Solar Aux Armoured Tercio allows too many selections

### ISSUE THREAD

**Issue by The4D6** [BSData/horus-heresy#3179]
As per p136 of Liber Imperium, you can only have 3 units in an armoured tercio. The command tank counts as one of these. We currently allow for 3 tank squadron _and_ a command tank, when we shouldn't.
![image](https://github.com/BSData/horus-heresy/assets/4020636/60ced5b1-3c40-463d-a3d4-e52726320a21)

**Comment by CanapeLit** [comment]
I did little researches and there is it : 

Same thing in Infantry tercio and the command squad. 
Same for velataris with command squad AND Storm section.
Same in artillery tercio.
Same in armoured support tercio.
