### ISSUE TITLE
Tactical Support Squads unable to take Graviton Guns when identified as Iron Hands (they should be able to).

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#318]
**File:** (HH) Crusade Army List.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** Yes

**Description:** Tactical Support Squads unable to take Graviton Guns when identified as Iron Hands (they should be able to).

**Comment by capitaladot** [comment]
This works as specified in the Head of the Gorgon Rite of War, but is not a more general Legiones Astartes (Iron Hands) allowance.
