### ISSUE TITLE
Paragon of Metal

### ISSUE THREAD

**Issue by Morturg** [BSData/horus-heresy#3186]
Paragon of metal for mechanicum is supposed to remove the cybernetica typr

It does not

**Comment by nstephenh** [comment]
Two ways I can think of fixing this.
Theoretically we could add something in the category to check for paragon on the parent and remove the rule/hide the category? That'd be less work overall, if it works.
The other fix is to add a modifier to every model with paragon of metal to remove the type, or if that causes issues add the type if not paragon of metal.

**Comment by Mayegelt** [comment]
Fixed in https://github.com/BSData/horus-heresy/pull/3302
