### ISSUE TITLE
SoH Black Reaving RoW requires mandatory HQ of Centurion with Master of Signal upgrade

### ISSUE THREAD

**Issue by vkurchenko** [BSData/horus-heresy#3187]
**Description
Sons of Horus Black Reaving Rite of War requires mandatory HQ of Centurion with Master of Signal upgrade. Now I can create roster w/o this limitation being reported as an error.

**To Reproduce**
Create roster for Sons of Horus
Select Loyalist allegiance
Select The Black Reaving (SoH) Rite of War
Complete all other requirements but not HQ Centurion with Master of Signal
No error is reported

**Expected behavior**
Error should indicate that HQ Centurion with Master of Signal should be present for given RoW

**Screenshots**
<img width="778" alt="Screenshot 2024-05-08 at 20 12 39" src="https://github.com/BSData/horus-heresy/assets/35027228/3ff1e536-2fb7-4d9f-b020-7e898797cbe9">

**Device and data (please complete the following information):**
 - OS: MacOS
 - Battlescribe
 - 2.03.21
 - Data release version v102

**Comment by nstephenh** [comment]
@The4D6 you didn't fix this did you?

**Comment by Mayegelt** [comment]
This seemed to have been fixed
