### ISSUE TITLE
Incorrect Weapon Option for the Solar Auxilia Leman Russ Assault Squadron

### ISSUE THREAD

**Issue by Saadat-Shah** [BSData/horus-heresy#3190]
**Describe the bug**
Solar Auxilia Leman Russ **Assault** Squadron can swap it's turret mounted demolished cannon for a "Turret Mounted Executioner plasma _**cannon**_" but the wargear options listed on the roster is for a "Turret Mounted Executioner plasma **_destroyer_**". 

**To Reproduce**
1. Create a roster for Solar Auxilia
2. Add an armored Tercio 
3. Add a Leman Russ **Assault** Squadron
4. Select the Leman Russ Assault Squadron and go to "All models may exchange their Turret Demolisher Battlecannon for one of the following"
5. Select "Executioner Plasma Destroyer"
![image](https://github.com/BSData/horus-heresy/assets/104098648/6186a791-bc1b-47a2-9215-fa0be9375e58)

**Expected behavior**
It should be a "Executioner Plasma **Cannon**"
![image](https://github.com/BSData/horus-heresy/assets/104098648/11feef22-97b9-450f-971d-29aba3ceb9ec)
and not an "Executioner Plasma **Destroyer**"

**Screenshots**
Because games workshop hates the solar auxilia, there is a profile difference between a "Executioner Plasma **Cannon**" (The **correct** profile):
![image](https://github.com/BSData/horus-heresy/assets/104098648/5ea11872-f5e4-4da6-8ae2-bee183b437cb)
And the "Executioner Plasma **Cannon**" (**Incorrect** profile that is available for selection):
![image](https://github.com/BSData/horus-heresy/assets/104098648/772c04c8-f330-4202-bb7b-3c8d0892ec0f)

The Executioner Plasma **Cannon** has a 48" range, while the Executioner Plasma **Destroyer** has a 60" range. The roster has the following profile for reference:
![image](https://github.com/BSData/horus-heresy/assets/104098648/f26aba58-3ffb-414e-90c8-891fae06d6e8)

**Device and data (please complete the following information):**
 - OS:  Window's 11
 - Battlescribe
 - 2.03.21
 - Release version v18.4.0

**Comment by nstephenh** [comment]
This has now been fixed for Militia and Solar aux, thanks!
