### ISSUE TITLE
[Anon] Bug report: 2022 - Questoris Household.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3202]
**File:** 2022 - Questoris Household.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** Yes

**Description:** When creating a knight army I am only getting the option to add troop choices and armigers. There are no other knight options appearing along with hq or support choices.

**Comment by nstephenh** [comment]
User likely selected crusade and not questoris force organization chart.
