### ISSUE TITLE
In disgrace all are equal - +1 characteristic

### ISSUE THREAD

**Issue by Petitionerscity** [BSData/horus-heresy#3211]
**Describe the bug**

Hi all, thank you for the blackshields addition which is fab. First error I noticed is for the "in disgrace all are equal", which has that +1 to one of several characteristics. In new recruit it forces you to pick one t apply to all characters:

![Screenshot_20240528-195403](https://github.com/BSData/horus-heresy/assets/133539150/66cbffc0-7e86-4088-b1be-50695efed0d3)

However, according to rule each character should be able to pick it individually what that +1 is:

![Screenshot_20240528-195407](https://github.com/BSData/horus-heresy/assets/133539150/bb6a6f18-393c-4384-9336-71efef382ea1)

I hope this is possible to fix - thank you!

**Comment by The4D6** [comment]
Hi there,

Every character in the force should have their own selection available within their own selection
![image](https://github.com/BSData/horus-heresy/assets/4020636/c6c4bc04-2973-403c-b564-d71e7e6f1c40)
The top level one under the oath selection should be hidden, I'll get on that

**Comment by Petitionerscity** [comment]
Thank you!
