### ISSUE TITLE
White Scars Rite of war not applying rules

### ISSUE THREAD

**Issue by WilliamPitt** [BSData/horus-heresy#3215]
**Describe the bug**

When i add the Sagyan Mazan Rite of war it previously added the rules to all Infantry. It is currently not adding the Kharash or Feel no pain rule.  The Kharash and Feel no pain rule is also incorrectly turning up on Unique characters.

**To Reproduce**

Go to New Recruit
Add a new white scars list
Add the Rite of war The Sagyan Mazan (WS)
Add Qin Xa
Add a Tactical Squad
Note that Qin Xa has Kharash and Feel no pain (5+)
Note that the Tactical squad doesn't have Kharash and the Fell no pain (5+) 

**Expected behavior**
Infantry should have the Kharash rule and Fell no pain (5+) rule added to their profile when the Sagyan mazan rite of war is selected. Unique characters should not have these rules applied.

**Comment by nstephenh** [comment]
Hopefully this was fixed by https://github.com/BSData/horus-heresy/pull/3214

**Comment by WilliamPitt** [comment]
Unfortunately still not working

**Comment by Mayegelt** [comment]
> Unfortunately still not working

Is this on NR or BS?
As it is working fine for me on BS, and I think someone else checked on NR.

**Comment by WilliamPitt** [comment]
This is on New Recruit

**Comment by Mayegelt** [comment]
Very odd. It works for a Praetor, But for other units it seems to not work despite the rule being under the "infantry unit type" category. It's defo an issue with NR rather than the data though as on BS its working fine.

![image](https://github.com/BSData/horus-heresy/assets/20280410/d6529553-69df-44e0-ad82-01e4f1299616)

**Comment by giloushaker** [comment]
Fixed on new recruit
