### ISSUE TITLE
[Anon] Rapier pattery points

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3221]
**File:** 2022 - LA - Space Wolves.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** Rapier Batteries have an overcoated Laser Destroyer upgrade (75. Should be 25/each)

**Comment by nstephenh** [comment]
Related or duplicate of https://github.com/BSData/horus-heresy/issues/3213 ?

**Comment by The4D6** [comment]
Duplicate of 3213
