### ISSUE TITLE
[Anon] Company command squad stats are messed up

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3222]
**File:** 2022 - LA - Space Wolves.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** Stat lines on the Company Command Squad are mixed up. (Move, I. A)

**Comment by nstephenh** [comment]
> This is correcting an earlier bug report. (I should make an account!)
> 
> The unit stats bug on the company command squad is actually just on the Legion Optea.
> 
> Seems like the Optae doesn't have a "unit type" that stat is missing on the stat line.
> The command squad do have a unit type, so it puts that (infantry) into the "M" Column, which is why the other stats all appear mixed up.
> 
> So I think the issue is with the Optae unit type.

Looking at nr-editor, the stats are right, but nr-builder is definitely interpreting them incorrectly. Not sure why it's broken. Following up with the nr devs.

**Comment by nstephenh** [comment]
I thought I had fixed this but I guess this commit never got merged. It should be fixed as soon as anyone runs the script to fix profile ordering, which I've done in the #3259 PR
