### ISSUE TITLE
Adding Fulgrim

### ISSUE THREAD

**Issue by thestudent911** [BSData/horus-heresy#323]
I have spent a long time trying to add Fulgrim. I have added the Emperor's Children, but he still doesn't appear. What do I need to do to add him to my list?

**Comment by Millicant** [comment]
Make sure you are using a Traitor allegiance and the Emperor's Children legion.

**Comment by thestudent911** [comment]
So I did that and it still doesn't show. But what I did notice that on the new app that you guys are developing (much better btw, just thought I'd tell you guys that), Fulgrim does appear there. I can add him that way, just not on the older one.

**Comment by Millicant** [comment]
Not sure what else to tell you.  Please mess around with it and see what you can do.
