### ISSUE TITLE
Horus Aximand both in AL data and allowed for Loyalist SoH

### ISSUE THREAD

**Issue by Jonathan-Blazeby** [BSData/horus-heresy#3235]
**Describe the bug**
Horus Aximand both in AL data and allowed for Loyalist SoH
![image](https://github.com/BSData/horus-heresy/assets/71888333/2f3c4973-0a2a-4a79-b219-d4961f7509e9)
![image](https://github.com/BSData/horus-heresy/assets/71888333/3cfd1d22-8e00-49c9-8943-1578dd0baa1c)

**To Reproduce**
1. Go to LA -XX: Alpha Legion new Crusade FOC
2. See Horus Aximand in HQ section

1. Go to LA -XVI: Sons of Horus new Crusade FOC
2. Set Allegiance to Loyalist
3. See Horus Aximand in HQ section

**Expected behavior**
Horus Aximand should only be available to Traitor Sons of Horus

**Screenshots**

**Device and data (please complete the following information):**
 - OS: PC Windows 10
 - App being used to create lists: Battlescribe
 - App version: 2.03.21
 - Data release version v19.0.3

**Additional context**

**Comment by The4D6** [comment]
Same issue as #3234, import flag improperly set
