### ISSUE TITLE
Unable to select Company Standard for Company Command squad - Horus Heresy - Battlescribe

### ISSUE THREAD

**Issue by Kingslayer679** [BSData/horus-heresy#3239]
**Describe the bug**
Under the options to select for each veteran present in the company command squad, I notice that it does not contain the option to equip one of them with a Company Standard as an option, which in the Beta Garmon book is listed as a 20 point upgrade for one of the models within the Company command squad.

**To Reproduce**
I don't know what to put under this section, I do apologise

**Expected behavior**
Expected an option similar to the despoiler and tactical squad option for taking a vexilia or vox, a section which says "One in the unit may take" and the ability to select the Company standard for 20 points, or legion vexilla for 10 points as stated in the beta garmon book for options.

**Screenshots**
![image](https://github.com/BSData/horus-heresy/assets/171704889/5806df10-b02f-4ddf-9654-d05b25180006)

**Device and data (please complete the following information):**
 - OS: iOS 17.5.1
 - Battlescribe
 - Version 2.03.15

**Additional context**
None.

**Comment by nstephenh** [comment]
Fixed in 371770f3c13627b26e479a894cbb03cf6b1ef91c

**Comment by nstephenh** [comment]
Though I think I forgot the nuncio-vox and augury scanner as well: 
#3283
