### ISSUE TITLE
Blood Angels Legion Veteran Tactical Squads are unable to take a Hand Flamer in place of a Volkite Serpenta

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#324]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 1.15.08

**Platform:** Android

**Dropbox:** No

**Description:** Blood Angels Legion Veteran Tactical Squads are unable to take a Hand Flamer in place of a Volkite Serpenta: As per the Legiones Astartes rules for Blood Angels, any Legiones Astartes (Blood Angels) model with access to a Volkite Serpenta should be able to take a Hand Flamer instead.

**Comment by capitaladot** [comment]
,.. for 15 points.
