### ISSUE TITLE
Questoris Household Detachment - Knights should not be abe to take generic/mechanicum warlord traits

### ISSUE THREAD

**Issue by BoaPi** [BSData/horus-heresy#3242]
**Describe the bug**
Currently it is possible for selected knights that are also a warlord, to select from the generic or mechanicum warlord traits. This should not be possible.

As stated in the core rules, only HQ choices that are also a warlord, should be able to select warlord traits. 

Only the knight with the seneschal rank, should be able to select the questoris household specifc warlord trait "Master of the household"

**To Reproduce**
1. please see [this](https://www.newrecruit.eu/app/list/EWFEs) list

**Expected behavior**
* knights which are warlord, but does not have the seneschal rank, should not be able to select generic or mechanicum warlord traits

**Screenshots**
![image](https://github.com/BSData/horus-heresy/assets/27858462/06bc270e-82ef-4695-8076-3fa15acbbbad)

**Device and data (please complete the following information):**
 - OS: iOS
 - New Recruit
 - Version v258.18

**Additional context**
none

**Comment by Petitionerscity** [comment]
Surely the issue here is that knights with ranks gain the character sub-type, and so could gain a normal Warlord trait?

**Comment by BoaPi** [comment]
@Mayegelt exactly this. The only seneschal rank allows a warlord trait.

**Comment by Petitionerscity** [comment]
My bad, and thanks for making clear :)

I wonder if it's helpful to add that info as a pop up on warlord selection for a non-hq choice?

**Comment by BoaPi** [comment]
that sounds like a great idea!

**Comment by nstephenh** [comment]
Not sure if we can do a pop-up, we could either change the name or add a rule, but that's about it. 

I've made a fix, but there might be other versions of this that are funky, namely titans all have "warlord" and there's some weird restrictions on some of the existing knight warlord choices.
