### ISSUE TITLE
[Anon] Bug report: 2022 - LA - Alpha Legion.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3243]
**File:** 2022 - LA - Alpha Legion.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** v2.03.27.341 Pts incorrect for Rapier Battery upgrades. Way too high.

**Comment by The4D6** [comment]
Duplicate of #3213
