### ISSUE TITLE
Blackshields still show rite of war/redo imports in general

### ISSUE THREAD

**Issue by nstephenh** [BSData/horus-heresy#3247]
I meant to fix this by changing how catalogue imports work but I apparently did not. 
Need to untick "import" on rite of war and/or change the import  on blackshields to not import root selection entries from LA.cat.

**Comment by Mayegelt** [comment]
Moved the RoW to each legion in its own rite. This seems to have fixed the issue without causing probs for old rosters.

**Comment by nstephenh** [comment]
I'll close this for now, we could mess around with imports more but I don't want to at this poin.
