### ISSUE TITLE
Legion Rapier Quad Launcher increases shell option costs with crew members

### ISSUE THREAD

**Issue by TheGodOfCakes** [BSData/horus-heresy#3249]
The cost for the Quad Launcher Shell Options increases for each crew member in the unit. It should only be x points per Quad Launcher.

https://i.gyazo.com/6e8ea784b00f92930a9dde8e493a1b25.png
https://i.gyazo.com/f4b8c88356415351bcf9bc883d4378bb.png
https://i.gyazo.com/42a71373d226d4863f9df9be427bdf31.png

**Comment by nstephenh** [comment]
This is a duplicate or extension of #3213
I thought we fixed it in https://github.com/BSData/horus-heresy/releases/tag/v19.0.4 , but it looks like it isn't working. Maybe we only changed the quad launcher itself and not the shells.

**Comment by Mayegelt** [comment]
Is this going to be something like the crew weren't counted as models before and the modifier might be counting models or something.

**Comment by nstephenh** [comment]
> Is this going to be something like the crew weren't counted as models before and the modifier might be counting models or something.

Yes it was exactly that I believe. It's fixed, we can just count the number of rapiers.
