### ISSUE TITLE
Beserker upgrade 

### ISSUE THREAD

**Issue by Dwango1** [BSData/horus-heresy#3250]
The above upgrade is missing from the world eaters character screen.

**Comment by nstephenh** [comment]
Berzerker is set to be programmed as hidden by default, but we were treating it as not hidden because the link doesn't. I've inverted the logic for centurion and will look to see if we messed up on any other units. I know praetor it worked fine.

**Comment by nstephenh** [comment]
Re-opening as it is apparently a problem on centurions as well, don't know how I missed it.

**Comment by nstephenh** [comment]
Ok, it's working fine in new recruit, it's a battlescribe only problem. Moving it to the other issue for tracking battlescribe issue.
