### ISSUE TITLE
Blackshields: Panoply shows Consularis upgrades.

### ISSUE THREAD

**Issue by UltraWeebMaster** [BSData/horus-heresy#3254]
Panoply of Old (Emperor’s Children) wrongfully adds the following feature to the army list:

```
Legion Consularis: Phoenix Warden: A Legion Tartaros Centurion with the Legiones Astartes (Emperor's Children) special rule may be upgraded to a Phoenix Warden.

• The Phoenix Warden gains the Skill Unmatched and Living Icons Special Rules.

• The Phoenix Warden gains a Phoenix Pattern Power Weapon of any kind and a Iron Halo at no additional points cost.
```

**Comment by The4D6** [comment]
![image](https://github.com/user-attachments/assets/06ead4b0-9d3c-4d4b-889c-840b9afe2a93)
![image](https://github.com/user-attachments/assets/2bac6054-ffb5-416f-a984-1080c205f5e3)
I don't think this is an issue, or it has been fixed previously

If you can provide more info I'm happy to re-open it, but until then I'm going to close it as completed
