### ISSUE TITLE
Blackshields: Sergeants should count as characters for Panoply: EC

### ISSUE THREAD

**Issue by UltraWeebMaster** [BSData/horus-heresy#3255]
Blackshield Sergeants (Tactical, Despoiler, Assault, etc) count as characters and Legiones Astartes units, but do not receive an option for surgical enchancements under the Panoply of Old (Emperor’s Children) Oath of Vengeance and Wrath :c

**Comment by The4D6** [comment]
I believe this was fixed as part of #3311

If I'm wrong, feel free to re-open it and I'll address it again
