### ISSUE TITLE
Ætheric Dominion has mandatory selections

### ISSUE THREAD

**Issue by Docbungle** [BSData/horus-heresy#3257]
**Describe the bug**
Ætheric Dominion in rainstorm daemons throws a list warning if specific ones not selected. Selecting multiples gives correct response though.

See warning given below;

Ætheric Dominion (Whole Army) requires 1 selections more of Encroaching Ruin
 Ætheric Dominion (Whole Army) requires 1 selections more of Heedless Slaughter
 Ætheric Dominion (Whole Army) requires 1 selections more of Malevolent Artifice

**Expected behavior**

**Device and data (please complete the following information):**
 - OS: androis
 - New Recruit

**Comment by The4D6** [comment]
@Mayegelt I've looked in to this and I can't quite work out how to fix it, you did daemons originally, any ideas?

**Comment by The4D6** [comment]
Fixed in #3323
