### ISSUE TITLE
Praetor Rampage (2)

### ISSUE THREAD

**Issue by Jedirev** [BSData/horus-heresy#3261]
**Describe the bug**
Legion Praetors of any legion appear to have picked up Rampage (2). (Cataphractii and Tarts don't have the issue.)

**To Reproduce**
Create a new list
Add a Legion Praetor
View the list

**Expected behavior**
Legion Praetors shouldn't have Rampage.

**Device and data (please complete the following information):**
 - OS: Android
 - App: Battlescribe
 - App version: 2.03.27
 - Data release version: 19.0.4

**Comment by nstephenh** [comment]
This looks configured in the data properly, and new recruit is handling it fine, but battlescribe is not respecting the hidden flag. 
![image](https://github.com/BSData/horus-heresy/assets/3454308/a326ef31-122d-40a3-8d0f-6bfa97bde4b0)

For now, I'd recommend not using battlescribe and switching to new recruit.

**Comment by Mayegelt** [comment]
BS hates Hidden is false on linked rules that the rule that it is linked to is not hidden.

**Comment by nstephenh** [comment]
To fix this we should just invert all the logic so it's shown by default and we hide it. Very annoying.

**Comment by Mayegelt** [comment]
Just required the logic reversal on the Praetor option
Will be fixed in https://github.com/BSData/horus-heresy/pull/3302
