### ISSUE TITLE
Move "allied detachment" to the top of the force where we put other administrative stuff.

### ISSUE THREAD

**Issue by nstephenh** [BSData/horus-heresy#3263]
Allied detachment being at the bottom of the detachment can create some minor confusion: 
The people looking at this then thought the questoris household was the allied detachment. 
![image](https://github.com/BSData/horus-heresy/assets/3454308/78a5c550-5773-4e13-a955-81ddd2de79a9)

**Comment by Mayegelt** [comment]
This should no longer be the case from the push of #3260 as there is no longer an allied detachment SE. It's loaded in like ZM FoC as a category.
