### ISSUE TITLE
Panoply of old World Eaters Weapons

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3268]
**File:** 2022 - BG - Blackshields.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** When selecting the oath "Panoply of old (X)" and using World Eaters XII: World Eaters, their options for weapons don't appear anywhere. Other factions items appear just fine.

**Comment by nstephenh** [comment]
I am seeing them in new recruit, at least for the despoiler squad. And in battlescribe with a regression test on desktop.  Maybe battlescribe mobile only?

**Comment by Mayegelt** [comment]
Checked this on mobile. I can't see the issue.
