### ISSUE TITLE
Shadrak Meduson new profile

### ISSUE THREAD

**Issue by FlipmodeSH** [BSData/horus-heresy#3272]
**Describe the bug**
Shadrak Meduson is 135 and has his legacy PDF warlord trait and war gear.

**To Reproduce**
Iron Hands HQ option.

**Expected behavior**
New profile 175 points, reworded warlord trait and different equipment. From Battle for Beta Garmon supplement.

**Device and data (please complete the following information):**
 - OS: Android
 - App being used to create lists Battlescribe
 - App version 2.03.27
 - Data release version [e.g. v1.2.3]

**Additional context**

**Comment by nstephenh** [comment]
It hasn't been added as part of the battle for beta garmon content, I forgot the old version was still in there.

**Comment by nstephenh** [comment]
Done.
