### ISSUE TITLE
Endryd Haar Retinue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3279]
**File:** 2022 - BG - Blackshields.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Endryd haar is not able to take retinue on battlescribe. And the comoany command doesnt have the standart option

**Comment by nstephenh** [comment]
Standard was fixed. Still need to fix retinue

**Comment by Mayegelt** [comment]
Also noticed he doesn't have stats. Will be checking for other errors then Will be fixed in https://github.com/BSData/horus-heresy/pull/3302
