### ISSUE TITLE
'Hammer of Olympia' Rite of War Heavy Support Slot

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#328]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 1.15.08

**Platform:** Android

**Dropbox:** No

**Description:** When selecting the Iron Warriors Legion in an army list, using the 'Hammer of Olympia' Rite of War, you are supposed to be able to take an additional Heavy Support unit, bringing the total count of allowed squads to 4, instead of 3. However, even with this Rite of War selected, I still get an error if I select more than 3 Heavy choices.

**Comment by cowomo404** [comment]
This is a known issue. Not currently possible with the current version of  battlscribe. Maybe fixed/possible when 2.0 is fully released. For now just ignore the error.
