### ISSUE TITLE
Delegatus missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3280]
**File:** 2022 - Horus Heresy.gstz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** Delegatus still missing from HQ Options. Command Squad can be selected as Honour Guard for Centurion, even though they can only accompany a Delegatus or Praetor. Rosters that previously contained a delegatus now contain a blank centurion

**Comment by nstephenh** [comment]
Not sure what's up with delegatus but I assume the user is seeing the company command squad instead of the command squad.

**Comment by Mayegelt** [comment]
I assume they have taken a praetor in force

**Comment by nstephenh** [comment]
Closing this as not fixing/user error. Delegatus appears for me just fine, maybe we didn't have the rule enforced before and it's enforced now which is breaking their list. If the user contacts us in a way to elaborate, we can re-open.
