### ISSUE TITLE
Durak Rask Retinue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3284]
**File:** 2022 - LA - Death Guard.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** Marshal Durak Rask has master of the legion but can't be given a retinue in the app.

**Comment by Mayegelt** [comment]
Will be fixed in https://github.com/BSData/horus-heresy/pull/3302
