### ISSUE TITLE
Thanatar missing in Zone Mortalis.

### ISSUE THREAD

**Issue by nstephenh** [BSData/horus-heresy#3287]
OnlyChins — 06/26/2024 2:26 AM
When trying to make a Myrmidax warlord list for Mechanicum in ZM, the Thanatar is omitted in HQ, even though it only has 7 wounds.

Gothjuice — 07/01/2024 12:19 AM
Second this, it is also prevented as a Heavy Support option for Mech in ZM

Discussion in discord: https://discord.com/channels/736936369670193332/1255423947185324134

**Comment by Mayegelt** [comment]
Will be fixed in https://github.com/BSData/horus-heresy/pull/3302
