### ISSUE TITLE
Heedless Slaughter and Malevolent Artifice bug

### ISSUE THREAD

**Issue by nstephenh** [BSData/horus-heresy#3288]
OnlyChins — 06/26/2024 2:25 AM
For certain corrupted engines and daemons these choices for special rules are asking for more and less choices of themselves simultaneously, and interfering with the choices of others in the army. Perhaps due to a mixup between special rules chosen for units and aetheric dominions for army wide rules for daemons.

In Discord: https://discord.com/channels/736936369670193332/1255423554867036210

**Comment by Mayegelt** [comment]
Not sure how to fix this one yet...

**Comment by Mayegelt** [comment]
Ahh accy I see the issue here.
Basically its asking for both a + and - as you can only have 1 dominion in any force. As such if they are taking something like a Decimator and a Blood Slaughterer then there is a conflict that you can't have both.

**Comment by m455954** [comment]
As far as I can see the restriction to only have one aetheric dominion only applies to a Demons army, can't see anything that prevents both a Decimator and a Blood Slaughterer being in the same army list

**Comment by The4D6** [comment]
![image](https://github.com/user-attachments/assets/0b10ac23-5fbb-4064-affb-360192a6a160)
This is from the Tredecimmia PDF

The restriction is not on Daemons, the restriction comes from the Aetheric Dominion special rule itself

**Comment by m455954** [comment]
Ah - missed that - thanks

**Comment by The4D6** [comment]
@Mayegelt I'm reading this as a non-issue in that case? As you cannot have both, things are working as designed?

**Comment by Mayegelt** [comment]
> @Mayegelt I'm reading this as a non-issue in that case? As you cannot have both, things are working as designed?

Sounds good to me
