### ISSUE TITLE
Death Guard Vet Sgt Alchem Flamer

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3289]
**File:** 2022 - LA - Death Guard.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** Veteran Sgt doesn't have Alchem Flamer minor combi weapon option

**Comment by Mayegelt** [comment]
Will be fixed in https://github.com/BSData/horus-heresy/pull/3302
