### ISSUE TITLE
Word Bearers - Samus and Cor'bax Utterblight Missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#329]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** Yes

**Description:** When selecting Word Bearers as a Legion - Legion Astartes selection, the demons Samus and Cor'bax Utterblight should be available as Lords of War choices but are not showing up.

**Comment by Millicant** [comment]
They are a part of the Codex:Chaos Daemons, not LA:CAL.

**Comment by capitaladot** [comment]
According to the FW PDF (and I could find no other reference in black or red books), they are part of both, so I added profiles, special rules, and copied them across.
