### ISSUE TITLE
(Space Wolves) Retinue option missing

### ISSUE THREAD

**Issue by WetworkSicknote** [BSData/horus-heresy#3291]
A Speaker of the Dead and Caster of Runes (two SW-specific Consuls) have the option to take a unit of Deathsworn (SW-specific unit) as a Retinue option. 

This option is present for the artificer armoured consul but not for the Tartaros or Cataphractii ones. The wording of the option on the Deathsworn unit entry is 'model with the Speaker/Caster upgrade' (i.e. not specific to any armour type) 

Have experienced this through New Recruit via Chrome on an Android phone (so I assume it's the live data but I couldn't find a reference number, sorry)

**Comment by Mayegelt** [comment]
Will be fixed in https://github.com/BSData/horus-heresy/pull/3302

**Comment by WetworkSicknote** [comment]
Thank you so much!
