### ISSUE TITLE
Phalanx Warden squad can not equip Solarite Power Gauntlet 

### ISSUE THREAD

**Issue by Kubolakuba** [BSData/horus-heresy#3292]
**Describe the bug**
Hello, I gound an issue in the HHfiles. 
the issue is that a Phalanx Warden squad can not equip Solarite Power Gauntlet in their special weapon guys, although according to rules it shuld be able to
it is stated in the Solarite Power Gauntlet rules, that you can exchange any power fist for solarite for +5 pts, and any Thunder Hammer for solarite for free

**To Reproduce**
1. Add Pahlanx Warden squad to your force
2. Add marines 2/options
3. Marines with options cant sellect a solarite power fist, even though solarite rulles allow you to change any thunder hammer for free

**Expected behavior**
Posibbility to chose Solarite Power Gautnlet by Phalanx Wardens w/options for points cost equal to thunder hammer

**Screenshots**
![2024-07-22 10_00_34-Base - New Recruit](https://github.com/user-attachments/assets/eb8bf6c6-147d-4081-b971-b94cadcd875b)
![2024-07-22 10_34_16-Roster Editor 2 03 21 - New Roster (Horus Heresy (2022) v111)](https://github.com/user-attachments/assets/0e6ea481-7abd-40c5-bb25-2183f294c7f4)

**Device and data (please complete the following information):**
 - OS: Windows
 - New Recruit, Battlescribe
 - Web version New Recruit, Newest Battlescribe
- Data Version 19.0.8

**Additional context**

**Comment by Mayegelt** [comment]
Will be fixed in https://github.com/BSData/horus-heresy/pull/3302 This was likely an oversight due to rules interactions.
