### ISSUE TITLE
Culexus lacks the Anathema subtype in the Categories section

### ISSUE THREAD

**Issue by Covacslong** [BSData/horus-heresy#3293]
The Culexus assassin has Anathema in its Liber Imperium entry and in the Unit Type section of the sheet, but not in the Categories section.  As a result the Anathema rule does not display, which may cause some confusion as to whether it has it or not. 
![image](https://github.com/user-attachments/assets/751c0689-d1eb-4608-aa00-4cfa986621ba)

**Comment by Mayegelt** [comment]
Will be fixed in https://github.com/BSData/horus-heresy/pull/3302
Had to move the category from the SoS lib to GST
