### ISSUE TITLE
[Anon] Bug report: 2022 - LA - Word Bearers.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3294]
**File:** 2022 - LA - Word Bearers.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** Yes

**Description:** I can't seem to get the Terminators to switch to different power weapons.  All they will let thme have is power swords.  The rules state you can have different power weapons.  I was going to build with mauls and then make them tainted.

Thank you

**Comment by Mayegelt** [comment]
There is a sub option located below the power weapon
