### ISSUE TITLE
Clade Callidus Assassin Phase Sword stats missing

### ISSUE THREAD

**Issue by m455954** [BSData/horus-heresy#3295]
The Clade Callidus Assassin can be taken as an HQ in any loyalist force.

The Phase Sword that they come equipped with does not show any stats at all in Battlescribe

It should be Range - Str 3 AP1 Melee, Rending (5+), Phase Shift

The Phase Shift and Rending (5+) special rules are being shown in Battlescribe already, but the stats aren't showing in the Weapon entry for the unit.

**Comment by Mayegelt** [comment]
Will be fixed in https://github.com/BSData/horus-heresy/pull/3302
