### ISSUE TITLE
Firedrakes have incorrect DT options

### ISSUE THREAD

**Issue by sammy1512** [BSData/horus-heresy#3296]
**Describe the bug**
Salamanders Firedrake Terminators are able to select Dreadclaw Drop Pods as dedicated transports by default (i.e. no rite of war, etc.). Their rules in Liber Astartes (of 318) don’t list this as an option. 

**To Reproduce**
1. Create a new Salamanders army list 
2. Add Firedrakes to army list 
3. Select dedicate transport
4. See erroneous drop pod

**Expected behavior**
Dreadclaw drop pod shouldn’t be an option by default. 

**Device and data (please complete the following information):**
 - OS: iOS
 - App being used to create lists: repeatable on New Recruit and Battlescribe
 - Data release version v19.0.8

**Comment by Mayegelt** [comment]
Will be fixed in https://github.com/BSData/horus-heresy/pull/3302
