### ISSUE TITLE
Thanatar Siege automata not Available in Zone mortals force organisation

### ISSUE THREAD

**Issue by bobmylan** [BSData/horus-heresy#3297]
**Describe the bug**
Tha Thanatar Heavy choice is not available in the unit selection panel
**To Reproduce**
1. Make a 1000+ pts list
2. Can't add the Thanatar Unit
3. See error

**Expected behavior**
As described in the Zone mortals rules in the Cthonia book, battle automata can be included if they have less than 8 wounds, and the Thanatar has 7
**Screenshots**
<img width="903" alt="image" src="https://github.com/user-attachments/assets/46d133cb-816a-46be-a336-2dd52898e15a">

**Device and data (please complete the following information):**
 - OS: MacOs 15
 - App being used to create lists New Recruit, Battlescribe (same bug)
 - App version : last
 - Data release version [e.g. v1.2.3] : version 19.0.8

**Comment by Petitionerscity** [comment]
It also seems strange the macrocarid is allowed too?

**Comment by Mayegelt** [comment]
Will be fixed in https://github.com/BSData/horus-heresy/pull/3302
