### ISSUE TITLE
Incorrect Consul choices re:Alpha Legion: Consul Option: Saboteur  incorrectly allowed for terminator armour

### ISSUE THREAD

**Issue by Morturg** [BSData/horus-heresy#3298]
the Saboteur consul upgrade is only for Legion Centurion

NOT legion cataphractii centurion, nor legion tartarus centurion

these should not be valid for the saboteur upgrade

simililarly 

Castellan (IF)  is only for power armour

and
the new Overseer are also Power armour locked

**Comment by Morturg** [comment]
same for praevin too

**Comment by Mayegelt** [comment]
Will be fixed in https://github.com/BSData/horus-heresy/pull/3302
