### ISSUE TITLE
Blackshields Panoply: Iron father shows on tartaros, but not on cataphractii

### ISSUE THREAD

**Issue by nstephenh** [BSData/horus-heresy#3299]
As it's in the wargear section, it should show on both.

https://discord.com/channels/832649952043204659/864924897679769600/1268289817096228968

**Comment by Mayegelt** [comment]
Seemed like Tartaros was edited to have an additional hidden false, but regular cata and praetor didn't
Will be fixed in https://github.com/BSData/horus-heresy/pull/3302
