### ISSUE TITLE
Nullificators need checking for Legion options.

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#3303]
It seems like Nullificators were missing Solarite Gauntlets from their weapon options. I think there are probably other legion options that might be lacking, so probably need to be looked at.

**Comment by The4D6** [comment]
![image](https://github.com/user-attachments/assets/a4225065-87a7-463b-b652-f8ab9b9e4627)
Most appear to be there

**Comment by Mayegelt** [comment]
@The4D6 I assume most should be there, I just wanted to make sure nothing had been left out accidently, as it was clear a couple had been. So thought best to seek a 2nd person to check it over.
I had put "Were missing" for the solarite gauntlets, as i fixed them prior to posting the issue, as someone had let me know the issue, and I had included it in a push. I just forgot to tag this one into it.
