### ISSUE TITLE
Legion specific bolters shoudl be incompatible with bayonets.

### ISSUE THREAD

**Issue by nstephenh** [BSData/horus-heresy#3304]
Thousand sons asphyx and iron warriors shrapnel bolters are incompatible with bayonets per the FAQ.

Sounds like we left it in the normal tactical marine but removed it from the sgt and the "tactical marine with options".

Reported by ghosthowl in the new recruit discord.

**Comment by Mayegelt** [comment]
Looks like a small bit of missing code to put the hide if 0 for bolters.
Will be fixed in https://github.com/BSData/horus-heresy/pull/3302
