### ISSUE TITLE
World Eater Red Hand Destroyers

### ISSUE THREAD

**Issue by twizted86** [BSData/horus-heresy#3307]
Red Hand Destroyers lost the ability to add a Missle Launcher or Thunder Hammer for every 5 models in New Recruit.

**Comment by The4D6** [comment]
![image](https://github.com/user-attachments/assets/2b2666fc-9c6d-4492-8b79-59af673f5eed)
This does not appear to be an issue

If you can update with more info then we can look at it but closing for now
