### ISSUE TITLE
Drop pod Augmetic Transport rule non Black shield factions

### ISSUE THREAD

**Issue by FirestormSquadronfirecast** [BSData/horus-heresy#3313]
**Describe the bug**
All drop pods now showing as having the Augmetic Transport Bay rule

**To Reproduce**
go to a drop pod dedicated transport for any unit that has it available (Night Lords terror squad for example)
scroll over the entry and see it has the above mentioned special rule
Drop Pod [35Pts]
Selections: Drop Pod, Pintle Mounted Twin-linked Bolter
Categories: Legiones Astartes, Transport Sub-type, Vehicle Unit:, Vehicle:
Rules: Augmetic Transport Bay, Deep Strike, Impact-reactive Doors, Inertial Guidance System, Infantry Transport, Orbital Assault Vehicle, Twin-linked

**Expected behavior**
The rule should only be applied to factions that have the Flesh Is Weak (Oath of Vengeance and Wrath) selected
should not apply to factions without this rule

Drop Pod [35Pts]
Selections: Drop Pod, Pintle Mounted Twin-linked Bolter
Categories: Legiones Astartes, Transport Sub-type, Vehicle Unit:, Vehicle:
Rules:  Deep Strike, Impact-reactive Doors, Inertial Guidance System, Infantry Transport, Orbital Assault Vehicle, Twin-linked

**Screenshots**

**Device and data (please complete the following information):**
 - OS: [windows 11)
 - App being used to create lists Battlescribe
 - App version 2.03.21
 - Data version horus heresy (2022) v112

**Additional context**
Could cause confusion where people try to say the unit it has been bought for cannot embark due to not having the automata keyword.

Thank you for the work you all do.

**Comment by The4D6** [comment]
Hi there,

I can't seem to see this in NR:
![image](https://github.com/user-attachments/assets/0bd61d00-ed6d-453c-9cf8-450b52a573e2)
![image](https://github.com/user-attachments/assets/e2fe2d77-528c-49a9-8ba4-daed2608aa60)

Can you provide some screenshots or further details on what's going on here?

And are you using BattleScribe?

**Comment by The4D6** [comment]
Ah, I've managed to repro it with a data update
![image](https://github.com/user-attachments/assets/a0dfbaa4-e88c-4120-8702-83f23a9e60bd)

I believe this is an issue unique to BattleScribe, it'll get looked in to but it's low priority

In the meantime, we recommend switching to use [NewRecruit](https://www.newrecruit.eu/)

**Comment by Mayegelt** [comment]
Just edited all the entries to reverse the logic to fix it.
BS doesn't like a rule that isn't hidden, but the rule link being hidden with a modifier to unhide it.
These should be left as not hidden and the hide modifier added to the entry.
