### ISSUE TITLE
Bug with Archimandrite Arch-Magos, Mechanicum allied detachment and LOW

### ISSUE THREAD

**Issue by m455954** [BSData/horus-heresy#3315]
**Describe the bug**
A Mechanicum Arch-Magos Prime that selects the Archimandrite High Techno-arcana allows a Mechanicum Allied Detachment to be taken as long as the Arch-magos in the allied detachment selects a different high techno-arcana.

This works fine, but if you then add a Mechanicum Lord of War detachment (which is also allowed) an error is raised stating" Roster has 1 selections too many of Mechanicum (max 2)"

**To Reproduce**
Create a roster with 1 Mechanicum Crusade Force Org, 1 Mechanicum Lord of War, and one Mechanicum Allied Detachment
Add an Arch-Magos Prime to the crusade force org, select the Archimandrite High Techno-arcana, make the unit the warlord and select any warlord trait
Add 2 compulsory troops to the crusade force org (e.g. tech thralls)
Add an Arch-magos Prime to the allied detachment, select any other high techno arcana (e.g. Cybernetica)
Add a single compulsory troop to the allied detachment
Add a Lord of War to the lord of war detachment

This is a valid army, but the roster will complain that " Roster has 1 selections too many of Mechanicum (max 2)"

**Expected behavior**
There should be no warnings raised

**Device and data (please complete the following information):**
 - OS: Browser
 - App being used to create lists New Recruit
 - App version v262.48
 - Data release version v19.0.9

**Comment by The4D6** [comment]
Fixed in #3323
