### ISSUE TITLE
Questoris Knight Crusader

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#332]
This will be a bit of an odd one.
Crusaders have Gatling Cannon and Thermal Cannon to start.
In 40K the Knight Crusader can swap its Thermal Cannon for the Battle Cannon (but must keep the Gatling). And a starting price of 425pts
It seems from the Crusader Imperialis (Redbook) it can swap its Gatling Cannon for a Battle Cannon (but must keep the Thermal). And has a starting cost of **435**pts (10pts more)

Now this might be a misprint, but they have not said it (though I have just asked and will likely ask at Forgeworld Openday next Sunday)
But due to the continually updated FAQ (last update June 2016)

> Additional Knight Types
> The following additional Knight Types: Knight Warden, Knight Gallant and Knight Crusader from Codex: Imperial Knights are also available in the army list in the same manner as the Questoris Knight Errant and Paladin as Questoris variants. These variants gain the Household Rank special rule in addition to those already in their profile, and are able to take the following additional upgrades:
> Bio-corrosive rounds for their heavy stubbers ... +5 points
> Occular augmetics... +10 points

It seems like we need 2 entries for Knight Crusader, 1 as the Questoris Knight Crusader (with the option to change the Gatling for a Battle but costs 10pts more) and one for Knight Crusader (with the option of swapping the Thermal for a Battle).
Or maybe just merge the 2 and give it a clicky option to choose which pair of weapons it wants, Thermal/Gatling (Both books but costs more in redbook), Thermal/Battle (Crusade Imperialis only and +10pts more), Battle/Gatling (40K Knight Codex only)

**Comment by Millicant** [comment]
Let us know if there's any feedback from the Open Day, but expect that the book (Released after the FAQ) will take precedence and we won't be adding 40k knight codex entries that are duplicates.

**Comment by Mayegelt** [comment]
Got the feedback from Mr Alan Bligh. He said with the current wording due the the FAQ that was released after Crusade Imperialis (though the question was asked before), you could use either variant. He said it may have been a mistake on print, but as the Renegade Knights can have the option in 40K of either variant, that it is just a relic of the Heresy :)

**Comment by capitaladot** [comment]
Yeah... just going to implement the Heresy option until a written FAQ comes out. IMHO, open-day chats and emails to FW customer service are too inconsistent (and too hard for everyone to access) to be authoritative.
