### ISSUE TITLE
Unable to assign weapons on individual basis

### ISSUE THREAD

**Issue by Srlojohn** [BSData/horus-heresy#3320]
I'm unsure if this is a bug or a feature, but on many units such as veterans or tactical squads, i'm unable to select wargear on an individual basis. I.e. If I have a standard veteran squad, I cannot say, give one man a Power Sword, One a Chainsword, one a Lighting claw, etc instead it requires them to all be unified. 

Note, I am on New Recruit, so it may have something to do with them.

**Comment by The4D6** [comment]
This is definitely doable on new recruit, you just need to add another instance of Veteran to the unit

![image](https://github.com/user-attachments/assets/252757ed-1c83-4eca-ba99-c19ce06cd844)

Alternatively this arrow button splits the unit down
