### ISSUE TITLE
Martian Civil War Campaign Book content

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#3326]
All the new campaign book stuff to add
 
- [x] Dark Scions of the Questoris (Check for changes, initially reported as none)

- [x] Automata Malefica
    - [x] Scions Of The Dark Forges (Warlord Traits)
    - [x] The Corrupted Engine Unit Sub-type (No change)
    - [x] Malefic Aegis (X) (No change)
    - [x] The Ætheric Dominion (X) Special Rule (No longer restricts usage for corrupted engines to 1 type)
    - [x] Corrupted Engines (Brass Scorp has a change)
      - [x] Brass Scorpion now has a * about attacks included in profile

- [x]  Techno-Heresies of the Dark Age
    - [x] Malefikite
       - [x] Cybertheurgic Arcana: Machina Malefica
       - [x] Ruinous Cybernetica (including giving the option to any unit of Cybernetica (Arlatax, Castellax, Domitar, Vorax, Vultarax)
    - [x] Nekrotek
       - [x] Cybertheurgic Arcana: Ephemera Nekrotek
    - [x] Malamina
    - [x] Æthertek
       - [x] Cybertheurgic Arcana: Anima Malefica (now just for Æthertek)

- [x] Aster Crohne
- [x] Kaedes Nex
- [x] Camba Diaz
- [x] Krios Squadron new weapon option - Krios Irradiator

### Minor Blackshields Update:
- [x] Cassian Dracos
- [x] Xiaphas Jurr
- [x] Narik Dreygur

**Comment by Mayegelt** [comment]
#3327 has the 3 characters and the new weapon so far. Will try to get more done later.

**Comment by m455954** [comment]
The Ætheric Dominion (X) Special Rule differs from the one in Ruinstorm Demons - The final paragraph preventing units with different versions of the Ætheric Dominion (X) Special Rule being in the same detachment is removed. The only proscription is that you cannot have a unit with one version of the rule join a unit with a different version of the rule. It is now legal to run a Blood Slaughterer with Ætheric Dominion (Heedless Slaughter) in the same detachment as a Chaos Decimator with Ætheric Dominion (Malevolent Artifice)

**Comment by Mayegelt** [comment]
> The Greater Brass Scorpion has been slightly nerfed - the two Hellcrusher Claws now have a new asterisk note stating "The additional attack for two Melee weapons is included in the Greater Brass Scorpion's profile"

I'm kinda of in agreement. But also feel like they have just slimmed down the blar blar at the top. So I'm a bit unsure and myself and the other 2 core data updaters had a discussion and thing it might need an FAQ to clarify. So I might put in an ambiguity button.

**Comment by Mayegelt** [comment]
> The Greater Brass Scorpion has been slightly nerfed - the two Hellcrusher Claws now have a new asterisk note stating "The additional attack for two Melee weapons is included in the Greater Brass Scorpion's profile"

Thanks for checking. I will remember when I make the update

**Comment by m455954** [comment]
> > The Ætheric Dominion (X) Special Rule differs from the one in Ruinstorm Demons - The final paragraph preventing units with different versions of the Ætheric Dominion (X) Special Rule being in the same detachment is removed. The only proscription is that you cannot have a unit with one version of the rule join a unit with a different version of the rule. It is now legal to run a Blood Slaughterer with Ætheric Dominion (Heedless Slaughter) in the same detachment as a Chaos Decimator with Ætheric Dominion (Malevolent Artifice)
> 
> I'm kinda of in agreement. But also feel like they have just slimmed down the blar blar at the top. So I'm a bit unsure and myself and the other 2 core data updaters had a discussion and thing it might need an FAQ to clarify. So I might put in an ambiguity button.

I think that the removal of that paragraph must be on purpose, otherwise an Æthertek army can only take a limited subset of the corrupted demon engines in the book, and I think that if that was the intention they would have a) left that paragraph in, or b) made it much more obvious with a specific call-out to that fact.

**Comment by m455954** [comment]
Also, I just checked and that paragraph does NOT exist in the Exemplary Battles: The Depths of Tridecimmia
![image](https://github.com/user-attachments/assets/948e8889-50bc-481a-b1ca-22586bd058f2)

**Comment by Mayegelt** [comment]
@The4D6 @nstephenh

**Comment by The4D6** [comment]
I literally had the tredecimma tab open from yesterday and they appear to have updated the new one _today_

I would say allow it for corrupted engines, but not for Daemons (as they have not changed that one)

**Comment by The4D6** [comment]
The rule is no longer in Tredecimma _at all_ as none of the engines content is there anymore

Daemons still isn't updated

**Comment by Mayegelt** [comment]
> The rule is no longer in Tredecimma _at all_ as none of the engines content is there anymore
> 
> Daemons still isn't updated

That also means they have removed the cyberthergy which was in there, as such under the new book it seems to be limited to just a prime with a particular techno arcana

**Comment by The4D6** [comment]
## More content that needs adding in this PR (as it's part of the wider MCW update):

### Cassian Dracos and Xiaphas Jurr gained this rule
![image](https://github.com/user-attachments/assets/aa38d8e1-4f09-4fef-babf-edf2b62f60c8)

### Their warlord traits were updated as follows:
![image](https://github.com/user-attachments/assets/2238b184-9e56-4ce6-9a76-33955fb89c87)
![image](https://github.com/user-attachments/assets/3f48ce72-eddd-468d-9a7b-acd18cf7fb87)

### Narik Dreygur gained this (ever so slightly different) rule:
![image](https://github.com/user-attachments/assets/7f53ff62-7fc1-44b7-89e1-b3e8691f26b5)

**Comment by The4D6** [comment]
Cassian dracos also lost IWND(5+) and gained Battlesmith 4+ instead
![image](https://github.com/user-attachments/assets/f803f04d-5017-49a1-beb2-732f47c75e43)

**Comment by Mayegelt** [comment]
Everything should be in pull #3327
