### ISSUE TITLE
[Anon] LA -   III: Emperor's Children: Add to favourite and and miniature buttons move up to block options instead of remaining at the bottom of the list

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3328]
**Problem:**
Add to favourite and and miniature buttons move up to block options instead of remaining at the bottom of the list

**Expected:**
They normally don't move

**List:** https://www.newrecruit.eu/app/list/reDYP

**Comment by Mayegelt** [comment]
This has been posted on the New Recruit discord as well.
https://discord.com/channels/736936369670193332/1285239346810720388
This is a bug with that program rather than our data side. So I will close it here. Hopefully they will fix soon.
