### ISSUE TITLE
GUI issue

### ISSUE THREAD

**Issue by dreadwingprotocol** [BSData/horus-heresy#3329]
**Describe the bug**
On the App when you open up a unit profile the add to favourites and add to miniature headers are overlayed over entries. I've been able to repeat it on Space Wolves, Mechanicum and Dark Angels on multiple different units.

**To Reproduce**
1. Create a new list for a faction
2. Click on the '+' to add a new unit
3. Open up that unit profile and it appears.
![Uploading Screenshot_20240917-063930.png…]()

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - App being used to create lists [e.g. New Recruit, Bluescribe, Battlescribe]
 - App version
 - Data release version [e.g. v1.2.3]

**Additional context**

**Comment by Mayegelt** [comment]
This seems to be a known issue in New Recruit. Hopefully should be fixed soon.
If this is being an issue on Battlescribe it will not be fixed as the dev abandoned it a long time ago
