### ISSUE TITLE
[Bug] EC Inductii and hereticus bug survived last bug fix

### ISSUE THREAD

**Issue by NotSuperKong** [BSData/horus-heresy#3333]
**Describe the bug**
The EC despoiler Inductii are still not selectable in hereticus, I know it survived as all the other bugs reported as fixed in the last patch have been successfully dealt with so this bug seems resilient

**To Reproduce**
1. Go to Emperor’s Children Legiones
2. Click on Despoiler
3. Enable Inductii
4. Switch to Hereticus
5. See error

**Expected behavior**
The red error message saying “Despoiler Inductii can not be selected while hidden” should not be showing up

**Screenshots**

**Device and data (please complete the following information):**
 - OS: iOS: 17.6.1
 - App being used to create lists: New Recruit
 - App version: v263.16
 - Data release version: 19.0.11

**Additional context**
It survived the last patch but this is nothing game breaking and you can make a work around by picking Legiones, then selecting Inductii, then back to hereticus. There is an error but you can see the rules that way so this bug is not going to stop that many users from using Inductii it’s just a little annoying. Thank you for all your hard work.
![IMG_2072](https://github.com/user-attachments/assets/4784667c-07b1-4a69-b256-24076218c22d)
![IMG_2073](https://github.com/user-attachments/assets/9d3d2ba9-fb8f-4ea6-89ae-8f1ed6498853)

**Comment by Mayegelt** [comment]
I'll squish that one tomorrow/ today if I'm well

**Comment by NotSuperKong** [comment]
Thank you, the entire team does such great work and I wish you all luck
