### ISSUE TITLE
[Anon] LA -   I: Dark Angels: No Elites, Fast Attack or Heavy Support menu's to choose units from

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3334]
**Problem:**
No Elites, Fast Attack or Heavy Support menu's to choose units from

**Expected:**
Those menu's to be present

 **Additional Info:**
New Recruit Horus Heresy 2022, Liber Astartes, Dark Angels 

**List:** https://www.newrecruit.eu/app/list/iPMja

**Comment by Felipe-Rafael-Rosa** [comment]
try this
https://bit.ly/4evXrQ6
I put the necessary dlls in the archive

**Comment by Mayegelt** [comment]
Press the + sign in the bottom left
