### ISSUE TITLE
[Anon] LA -   IV: Iron Warriors: Under "Master of Automata" it says on line 1 and 2 "one of more" it should be "one or more"

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3337]
**Problem:**
Under "Master of Automata" it says on line 1 and 2 "one of more" it should be "one or more"

**Expected:**
Change to "one or more"

**List:** https://www.newrecruit.eu/app/list/wPAnq

**Comment by Mayegelt** [comment]
Will be fixed next release.
We did a big typo fix, but as that wasn't an incorrect spelling, just an incorrect word, it didn't pick it up.
