### ISSUE TITLE
[Anon] LA -   III: Emperor's Children: Legacies/Exemplary locked to primary detachment.

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3338]
**Problem:**
Legacies/Exemplary locked to primary detachment.

**Expected:**
You should be able to make a list for an allied detachment with all the units, not just the ones from the main books.

 **Additional Info:**

**List:** https://www.newrecruit.eu/app/list/UchaN

**Comment by Mayegelt** [comment]
It applies to all forces around it.
You can't have an allied detachment without a regular detachment. So this should be a non issue.
