### ISSUE TITLE
[Anon] LA -  X: Iron Hands: The Iron Hands RoW Company of Bitter Iron allows special rule Bitter Duty to be given to independent characters, however, NR does not allow unique characters to be given such special rule. 

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3342]
**Problem:**
The Iron Hands RoW Company of Bitter Iron allows special rule Bitter Duty to be given to independent characters, however, NR does not allow unique characters to be given such special rule. 

**Expected:**
Unique characters can be given Bitter Duty special rule when Iron Hands RoW Company of Bitter Iron is selected

**Comment by The4D6** [comment]
Company of Bitter Iron allows _Independent Characters_ to be given Bitter Duty

Characters with the Unique unit sub-type cannot be given any upgrades not found on their datasheet
