### ISSUE TITLE
[Anon] Imperialis Militia: Levy squad miscounts leader weapon choice as a unit member.

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3343]
**Problem:**
Levy squad miscounts leader weapon choice as a unit member.

**Expected:**

 **Additional Info:**
There is also no default for the leader weapon

**List:** https://www.newrecruit.eu/app/list/rSYwd

**Comment by Mayegelt** [comment]
Will be fixed in next release
