### ISSUE TITLE
[Anon] Bug report: 2022 - BG - Blackshields.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3345]
**File:** 2022 - BG - Blackshields.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** For blackshields Xiaphas Jurr's warlord trait "Beacon of Hope" isn't working correctly.
It states that "if Xiaphas Jurr is selected as the army’s Warlord in a Blackshields Detachment, you can include Salamanders Adherents Squads as part of that Detachment. If you do so, replace  their Legiones Astartes (Salamanders) special rule with the Legiones Astartes (Blackshields) special rule and remove their Support Squad special rule."

You can add Adherants correctly but they don't loose the Support squad rule. This is incorrect and stops them from being selected as compulsory troops in the intended way.

**Comment by The4D6** [comment]
There are no compulsory troops slots in a Pride is our Armour detachment, so I'm not sure what the issue is here.

Also, I was under the impression we had decided not to implement the ability to add Adherents due to conflicts with the oaths

**Comment by Mayegelt** [comment]
Bad rule checking from HH team means that the bonus can't be applied. Going to close.
