### ISSUE TITLE
[Anon] BG - Blackshields: when using the blackshield rules under the zone mortalis detachment, the pride is our armor detachment rule states that no troops are necessary, but having no troops give you the red exclamation point, also the extra 2 elite slots are not given, this is only under mortalis and not regular 30k

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3347]
**Problem:**
when using the blackshield rules under the zone mortalis detachment, the pride is our armor detachment rule states that no troops are necessary, but having no troops give you the red exclamation point, also the extra 2 elite slots are not given, this is only under mortalis and not regular 30k

**Expected:**
the pride is our armor rule should function as stated, the upgrade to veterans is given its just that none of the other things are given alongside it

**List:** https://www.newrecruit.eu/app/list/LwgxQ

**Comment by Mayegelt** [comment]
Probably was only applied to Crusade and maybe Ally, but not ZM. Can be fixed easily at some point.

**Comment by Mayegelt** [comment]
Will be fixed in the next release
