### ISSUE TITLE
Typo Mechanicum Warlord Trait Scion of Retlaxi

### ISSUE THREAD

**Issue by m455954** [BSData/horus-heresy#3350]
**Describe the bug**
The current description for the Scion of Retlaxi warlord trait in the Mechanicum faction states

" resolve a Strength 5+D3, AP 5 Hit against every model, friendly or enemy, within 3+D**;**" of the model or the Vehicle's Hull."

This should state 

" resolve a Strength 5+D3, AP 5 Hit against every model, friendly or enemy, within 3+D**3**" of the model or the Vehicle's Hull.

**To Reproduce**
Create a Mechanicum list and add an Archmagos or Magos Dominus
Click the Warlord option
From the Scions of the Dark Forges list of Warlord traits select Scion of Reltaxi
Look at the description of the warlord trait

**Expected behavior**
The semi colon in the distance calculation in the existing description should be replaced with the numeral 3

**Screenshots**
![image](https://github.com/user-attachments/assets/74877c77-f429-47c8-b384-d794313ab419)

**Device and data (please complete the following information):**
 - OS: Any
 - Any [e.g. New Recruit, Bluescribe, Battlescribe]
 - Any
 - 19.1.0

**Additional context**
None

**Comment by Mayegelt** [comment]
will be fixed in next release
