### ISSUE TITLE
[Anon] LA -   IV: Iron Warriors: Veteran Squad not having regular bolter and bayonet as weapon options

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3352]
**Problem:**
Veteran Squad not having regular bolter and bayonet as weapon options

**Expected:**
Veteran Squad  having regular bolter and bayonet as weapon options

**List:** https://www.newrecruit.eu/app/list/mJTQA

**Comment by Mayegelt** [comment]
I can't see to replicate 

![Screenshot_2024-10-02-10-59-46-570_com android chrome](https://github.com/user-attachments/assets/60b258c0-c11e-43f6-ace5-b9222faa173b)
![Screenshot_2024-10-02-11-00-09-572_com android chrome](https://github.com/user-attachments/assets/f03a6425-a753-4d82-83ce-171e4eb1ff4c)

**Comment by Mayegelt** [comment]
I'll recheck the links again. I might have found a way to replicate.

**Comment by Mayegelt** [comment]
Found the issue, it seemed to be a modifier which was checking in force, rather than in unit.
Will be fixed in next release.
