### ISSUE TITLE
[Anon] LA -  X: Iron Hands: Does not allow legion chosen to be kitted out with options

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3356]
**Problem:**
Does not allow legion chosen to be kitted out with options

**Expected:**
1x chosen with lighting claw 1x chosen with boarding shield and plasma pistol etc

 **Additional Info:**
Liber Astartes

**List:** https://www.newrecruit.eu/app/list/3UCUo
**Unit:** Command Squad, id: 92a3-5f51-0863-b6f8

**Comment by Mayegelt** [comment]
This seems to be an issue that the user doesn't understand the interface. By default it makes collections of the same model. There is a button there to split into different variations of the same model.
