### ISSUE TITLE
[Anon] (HH V1) Imperialis Militia and Cults Army List: When going through Praetor, legion upgrades. You can't select the other gun weapon without the program saying there's an error and saying you must select one while the ratio says 0/0. I'm trying to use the night lord specific trataros praetor. Plus im pretty sure he wields a volkie serpentina

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3359]
**Problem:**
When going through Praetor, legion upgrades. You can't select the other gun weapon without the program saying there's an error and saying you must select one while the ratio says 0/0. I'm trying to use the night lord specific trataros praetor. Plus im pretty sure he wields a volkie serpentina

**Expected:**
I would assume this needs to be a 0/1 ratio to fix the programs wants

**List:** https://www.newrecruit.eu/app/list/LuGri

**Comment by The4D6** [comment]
We no longer fix 1.0 bugs
