### ISSUE TITLE
[Anon] LA -  X: Iron Hands: Cannot select Gorgon Terminator Armour on Centurion Cataphractii for The Iron Hands

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3360]
**Problem:**
Cannot select Gorgon Terminator Armour on Centurion Cataphractii for The Iron Hands

**Expected:**
Should be able to upgrade any centurion or praetor with the Legiones Astartes (Iron Hands) special rule in Cataphractii armour to a Gorgon Terminator armour

**List:** https://www.newrecruit.eu/app/list/J7jTt

**Comment by Mayegelt** [comment]
Will be fixed momentarly. I put an "And" rather than "Or" in one of the 300 of so changes needed for Shattered Legions and didn't notice that one.
