### ISSUE TITLE
[Anon] LA -   III: Emperor's Children: In Horus Heresy play mode, the Pathfinder Centurion is labeled as having a 2+ Save (as if he had Artificer Armour). 

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3366]
**Problem:**
In Horus Heresy play mode, the Pathfinder Centurion is labeled as having a 2+ Save (as if he had Artificer Armour). 

**Expected:**
He should have a 4+ save for his Scout Armour. The value is correct in the list editing mode.

**List:** https://www.newrecruit.eu/app/list/mfnTj

**Comment by Mayegelt** [comment]
Will be fixed in next release
