### ISSUE TITLE
[Anon] (HH V1) Legiones Astartes: Age of Darkness Army List: Cataphractii praetor for HH reports an error when equipped with a combi bolter as well as when not equipped with one, citing either having one too many or one too few selections respecitvely.

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3370]
**Problem:**
Cataphractii praetor for HH reports an error when equipped with a combi bolter as well as when not equipped with one, citing either having one too many or one too few selections respecitvely.

**Expected:**
Equipping 1 combi bolter should give no error.

**List:** https://www.newrecruit.eu/app/list/RxNTH

**Comment by Mayegelt** [comment]
Unfortunately we no longer support HH1.0
