### ISSUE TITLE
[Anon] LA -  XVIII: Salamanders: error message 

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3371]
**Problem:**
error message 

**Expected:**
no error message

 **Additional Info:**
 1. Crusade Force Organisation Chart requires 1 selections more of Allegiance (min 2)
Allegiance: requires 1 selections more of XVIII: Salamanders
Rite of War: The Covenant Of Fire (SAL) cannot be selected while hidden
Centurion, Cataphractii: Master-craft one weapon cannot be selected while hidden
Centurion, Cataphractii: Dragonscale Shield cannot be selected while hidden
Praetor, Cataphractii: Dragonscale Shield cannot be selected while hidden
Praetor, Cataphractii: Twin-linked Heavy Dragon's Breath Flamer cannot be selected while hidden
Praetor, Cataphractii: Dragon's Breath Heavy Flamer cannot be selected while hidden
Praetor, Cataphractii: XVIII: Salamanders cannot be selected while hidden
Firedrake Terminator Squad: Master-craft one weapon cannot be selected while hidden
Firedrake Terminator Squad: Twin-linked Heavy Dragon's Breath Flamer cannot be selected while hidden
Adherents Squad: Dragon's Breath Heavy Flamer cannot be selected while hidden
Tactical Squad: Master-craft one weapon cannot be selected while hidden
Tactical Squad: Dragon's Breath Heavy Flamer cannot be selected while hidden
Tactical Squad: Master-craft one weapon cannot be selected while hidden
Tactical Squad: Dragon's Breath Heavy Flamer cannot be selected while hidden
Tactical Squad: Master-craft one weapon cannot be selected while hidden
Tactical Squad: Dragon's Breath Heavy Flamer cannot be selected while hidden
Tactical Support Squad: Dragon's Breath Flamer cannot be selected while hidden
Tactical Support Squad: Dragon's Breath Heavy Flamer cannot be selected while hidden
Heavy Support Squad: Dragon's Breath Heavy Flamer cannot be selected while hidden
Heavy Support Squad: Dragon's Breath Heavy Flamer cannot be selected while hidden
Kratos Squadron: 2x Dragon's Breath Heavy Flamer cannot be selected while hidden
Kratos Squadron: Hull (Front, Right/Left) Mounted Heavy Dragon's Breath Flamers cannot be selected while hidden
Kratos Squadron: Pintle Mounted Dragon's Breath Heavy Flamer cannot be selected while hidden

**List:** https://www.newrecruit.eu/app/list/Vyb60

**Comment by Mayegelt** [comment]
User had removed the Salamanders allegiance. On restoring it, the list functioned as expected.
