### ISSUE TITLE
Flag and or Note feature

### ISSUE THREAD

**Issue by jacksbox** [BSData/horus-heresy#3374]
I would like a feature where I can flag units in my army list (maybe with different colors).
I would like to use this to plan ahead which units start in reserve, strategic reserve, maybe which unit is in which transport etc.

For this also a note feature for the armylist and the individual units would be a nice addition.

**Comment by The4D6** [comment]
This is not an enhancement we can make, as we only work with the data set rather than the application itself. (The application has long since been abandoned by its developer)

You would be better off making this request to the NewRecruit developers, as they might be able to do something about it.
