### ISSUE TITLE
The Angel's Tears

### ISSUE THREAD

**Issue by Toreador13** [BSData/horus-heresy#3375]
The Angel's tears weapon options are not able to be fulfilled. Any model may exchange one of it's volkite serpenta, but right now it's all or nothing. 
![image](https://github.com/user-attachments/assets/239eab7f-1751-46dd-aa91-68f0da5ce5de)

![image](https://github.com/user-attachments/assets/3f5926e1-f273-4f27-b1b6-6a9b9eb9c241)
![image](https://github.com/user-attachments/assets/21146b07-52f0-44b9-98f5-a43d22b87d8b)
Each model should be able to exchange it's volkite for any other weapon option.

**Comment by Mayegelt** [comment]
You need to click the "Split off" button. NR naturally groups things together by default. So you split off to get multiple versions of the same model.


![image](https://github.com/user-attachments/assets/f5ecbffe-c159-4038-87d0-aa2e1c674249)

![image](https://github.com/user-attachments/assets/a6a9870f-86ea-456e-af4f-9f0e74899cc3)

**Comment by Mayegelt** [comment]
I'll leave this open just in case there is an issue which isn't as I think you are describing. But if it is this then please close the issue.

**Comment by Toreador13** [comment]
Nope, that explains it. Didn't even know that was a thing in NR!
