### ISSUE TITLE
[Anon] LA -   IV: Iron Warriors: Cannot take off breachers

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3377]
**Problem:**
Cannot take off breachers

**Expected:**
Able to reduce breachers down from 9

**List:** https://www.newrecruit.eu/app/list/Vzd1V
**Unit:** Breacher Squad, id: be21-9e50-1c3c-5076

**Comment by Mayegelt** [comment]
No idea why you can't I just imported your list and could.
Remember the min squad size is 10 (1 sergeant, 9 normal ones / ones with options).
