### ISSUE TITLE
[Anon] LA -  XV: Thousand Sons: Thousand sons praetor can't select achean force weapons 

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3378]
**Problem:**
Thousand sons praetor can't select achean force weapons 

**Expected:**
Being able to select achean weapons on characters

 **Additional Info:**
Thousand sons horus heresy 2022

**List:** https://www.newrecruit.eu/app/list/5m8Ro
**Unit:** Praetor, id: 19dd-ef2a-c108-1bf6

**Comment by Mayegelt** [comment]
From the Hereticus

"Any modelwith both the Legiones Astartes (Thousand Sons) special rule and the Character Unit Sub-type may exchange a power weaponfor any one Achea pattern force weapon for no additional points cost (a model with the Independent Character special rule may not select this option):"

It's really dumb...
