### ISSUE TITLE
[Anon] Mechanicum: Castellax options are for the whole unit, not any one

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3380]
**Problem:**
Castellax options are for the whole unit, not any one

**Expected:**
Castellax weapons should be 'any Castellax may...' if there's more than one

 **Additional Info:**
Liber Mechanicum. Apologies if this is the wrong way to report this!

**List:** https://www.newrecruit.eu/app/list/VrkQ6
**Unit:** Castellax Battle-Automata Maniple[2], id: 3c04-f537-6cf1-65bc

**Comment by Mayegelt** [comment]
You need to use the "Split off" option like this. NR naturally groups things together by default. So you split off to get multiple versions of the same model.

![image](https://github.com/user-attachments/assets/678a0afa-18be-4193-990f-396313c6cb03)
