### ISSUE TITLE
[Anon] LA - XIX: Raven Guard: Kaedes Nex has moved to hidden for an unknown reason

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3381]
**Problem:**
Kaedes Nex has moved to hidden for an unknown reason

**Expected:**
His status is Hidden:false rather than hidden: true

**List:** https://www.newrecruit.eu/app/list/yowrO

**Comment by Mayegelt** [comment]
Will be fixed next release
