### ISSUE TITLE
[Anon] LA -  X: Iron Hands: The iron hands gorgon terminators don't have power axes in their profile. The heavy weapons also don't say (1 in 3) like other units.

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3382]
**Problem:**
The iron hands gorgon terminators don't have power axes in their profile. The heavy weapons also don't say (1 in 3) like other units.

**Expected:**
They come with power axes as standard.

**Comment by Mayegelt** [comment]
Looks like the min selection wasn't set for the melee options. The 1 in 3 was being applied. It just wasn't written.
Will be fixed next release.
