### ISSUE TITLE
Mantle of the Elder Drake not available on Cata Praetor

### ISSUE THREAD

**Issue by Mr-Fishlegs** [BSData/horus-heresy#3386]
For Salamanders lists, cata praetors in already created lists are now showing up with an error saying “Legion Cataphractii Praetor cannot have any selections of Mantle of the Elder Drake (hidden)”

Cannot be selected in new lists either. 

![IMG_3066](https://github.com/user-attachments/assets/43f97ebd-86d8-4d22-b811-948b4b6b54c1)

BattleScribe version 2.03.15

Cheers

**Comment by Mayegelt** [comment]
I'll have a look when I get home. It's probably a reversal of logic needed
