### ISSUE TITLE
[Anon] LA -   VIII: Night Lords: Error reported for having too many Troop Type units (claims 7/6 slots are filled) only 4 Troop units are present

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3387]
**Problem:**
Error reported for having too many Troop Type units (claims 7/6 slots are filled) only 4 Troop units are present

**Expected:**
Correctly reflect the amount of Troop units in the list

**List:** https://www.newrecruit.eu/app/list/fsgLn

**Comment by Mayegelt** [comment]
Looks like Terror Squads as Troops are counting as 4 troops...
