### ISSUE TITLE
Mechanicum Malamina Techno Arcana and Arlatax Arc Scourge issue

### ISSUE THREAD

**Issue by m455954** [BSData/horus-heresy#3389]
**Describe the bug**
For a traitor alliegence Mechanicum force, the Malamina Proscribed Techno Arcana gives any unit with power blade arrays the ability to swap them out for abomination blades.

The Arlatax unit in Fast Attack comes with two power blade arrays with in-built light autocannons. The unit allows you to swap out one or both for an Arc Scourge.

If you use the number spinner controls to chose one or more Arc Scourges then the weapon stats appear on the army listing, however if you use the new checkbox to select One Abomination Blade and 1 Arc Scourge, then the Arc Scourge is not added, only the Abomination blade (the points are correct but the Arc Scourge is not added)

**To Reproduce**
1 Create a new Mechanicum army list using the Crusader Force Organization
2 Add an Archmagos Prime or Archmagos Prime on Abayant from the HQ slot
3 Select the Malamina Proscribed Techno Arcana for the Archmagos
4 Add an Arlatax Battle-Automata Maniple from the Fast Support slot
5 Select the Arlatax
6 Change the number of Power Blade Arrays with In-Built Light Autocannon to zero
7 Click the checkbox for One Abomination Blade & 1 Arc Scourge
8 Check the unit listing - there is no Arc Scourge listed

**Expected behavior**
The Arc Scourge weapon stats should be included on the unit listing

**Screenshots**
![image](https://github.com/user-attachments/assets/246e5d53-6507-485b-9918-40cc65141488)

**Device and data (please complete the following information):**
 - OS: PC
 - App being used to create lists : Battlescribe
 - App version 2.03.21
 - Data release version 19.2.3

**Additional context**

**Comment by Mayegelt** [comment]
Reworked the entry to add the new options again. This should work better. Though it might be better to try to do a Left Hand / Right Hand option.
Will be fixed later today.
