### ISSUE TITLE
[Anon] LA -   VI: Space Wolves: Wrong transport -- Land Raider Spartan -- listed for Varagyr Wolf Guard Terminators

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3391]
**Problem:**
Wrong transport -- Land Raider Spartan -- listed for Varagyr Wolf Guard Terminators

**Expected:**
should have Land Raider Proteus Carrier 

 **Additional Info:**
Liber Astartes book page 210

**List:** https://www.newrecruit.eu/app/list/7eafR

**Comment by Mayegelt** [comment]
Varagyr are allowed a Land Raider if they have less than 6 models in the unit. They are allowed a spartan if they have any number of models.

![image](https://github.com/user-attachments/assets/163dc0d7-5e24-4c80-bfa8-48c2bff199d5)
