### ISSUE TITLE
[Anon] (HH V1) Solar Auxilia: The Auxilia Infantry Tercio is not up to date with new book

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3392]
**Problem:**
The Auxilia Infantry Tercio is not up to date with new book

**Expected:**
to see info from the the right book

 **Additional Info:**
Liber Imperium

**List:** https://www.newrecruit.eu/app/list/ukp11

**Comment by Mayegelt** [comment]
Thus report was generated for the old version.of heresy
