### ISSUE TITLE
[Anon] LI - Solar Auxilia: Hermes Veltaris Squadron is missing. The Reconnaissance Pattern Cohort data says "NOTE The 2nd bullet point about Veletaris Assault Squadrons getting Outflank is not implemented as no unit exists with that name, so it is unclear which unit it should go on." The Beta-Garmon book has an error here: the bullet says VAS but the only other Sentinel squadron is the Hermes Veltarii Squadron. That squadron is not present in the list. 

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3393]
**Problem:**
Hermes Veltaris Squadron is missing. The Reconnaissance Pattern Cohort data says "NOTE The 2nd bullet point about Veletaris Assault Squadrons getting Outflank is not implemented as no unit exists with that name, so it is unclear which unit it should go on." The Beta-Garmon book has an error here: the bullet says VAS but the only other Sentinel squadron is the Hermes Veltarii Squadron. That squadron is not present in the list. 

**Expected:**
Hermes Veletarii Sentinel can be added to the list. 

 **Additional Info:**
The Battle for Beta-Garmon page 181. 

**List:** https://www.newrecruit.eu/app/list/BsfOF

**Comment by Mayegelt** [comment]
It's all there..the Hermes Veletaris Squadron is part of the Veletaris Tercio
https://www.newrecruit.eu/app/list/4kDli
