### ISSUE TITLE
[Anon] LA -   III: Emperor's Children: Praetor/Master of the Legion

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3394]
**Problem:**
Praetor/Master of the Legion

**Expected:**
I should be able to take one Praetor every 1k points.

 **Additional Info:**
https://www.newrecruit.eu/wiki/horus-heresy/horus-heresy-(2022)/rules/master-of-the-legion

**List:** https://www.newrecruit.eu/app/list/8TrWy

**Comment by Mayegelt** [comment]
There was no issue taking a praetor with this list.
However with MOTL it is per 1000pts in army. As such if you are playing a 2k game and only have 1999 or less PTS as written you can not have 2 MotL.
