### ISSUE TITLE
Abaddon has the Wrong Bolter

### ISSUE THREAD

**Issue by FishQueen1702** [BSData/horus-heresy#3397]
Abaddon is supposed to have a Banestrike Combi-Bolter, but you guys have him just having a normal one.

![image](https://github.com/user-attachments/assets/6fe70c84-eb78-4d5b-bf40-0acfb19c4b74)
![image](https://github.com/user-attachments/assets/5a042020-af9b-4025-866c-c5d29cbac195)

**Comment by Mayegelt** [comment]
Will be fixed later today.
