### ISSUE TITLE
[Anon] LA -  XVI: Sons of Horus: Terminators can only select one melee weapon for the squad

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3398]
**Problem:**
Terminators can only select one melee weapon for the squad

**Expected:**
Each Terminator can select their choice of single lightning claw, power fist, or chainfist

 **Additional Info:**
Liber Astartes/Hereticus

**List:** https://www.newrecruit.eu/app/list/fzAkE
**Unit:** Terminator Cataphractii Squad, id: b113-e149-4c1b-ad2b

**Comment by The4D6** [comment]
Models can be split out to equip differently
