### ISSUE TITLE
[Anon] LA -  XVI: Sons of Horus: Tank squadrons all have to take the same wargear. 

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3400]
**Problem:**
Tank squadrons all have to take the same wargear. 

**Expected:**
Tank squadrons can take individual options. 

 **Additional Info:**
All Liber books with tank squadrons, this is true for Solar Auxilia and Astartes. 

**List:** https://www.newrecruit.eu/app/list/SZVtg
**Unit:** Scorpius Squadon, id: e3ef-ce1f-d480-fc6b

**Comment by Mayegelt** [comment]
You need to use the split option
