### ISSUE TITLE
[Anon] LA -  XVI: Sons of Horus: Contemptor Dreadnoughts can only take one loadout per talon. 

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3401]
**Problem:**
Contemptor Dreadnoughts can only take one loadout per talon. 

**Expected:**
Contemptor Dreadnought talons can mix and match weapon loadouts. 

 **Additional Info:**
Liber Astartes/Hereticus

**List:** https://www.newrecruit.eu/app/list/7PFwZ
**Unit:** Contemptor Dreadnought Talon, id: 240d-8914-458c-8982

**Comment by Mayegelt** [comment]
You need to use the split option
