### ISSUE TITLE
[Anon] LA -  XVI: Sons of Horus: Cataphractii cannot mix and match melee weapons, you can pick for heavy weapons and regular models

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3402]
**Problem:**
Cataphractii cannot mix and match melee weapons, you can pick for heavy weapons and regular models

**Expected:**
You should be able to take mixed melee weapons with regular Terminators, eg 4× power fist, 3× chainfist, 3× lightning claw

**List:** https://www.newrecruit.eu/app/list/2H4hT
**Unit:** Terminator Cataphractii Squad[1], id: b113-e149-4c1b-ad2b

**Comment by hardworlder** [comment]
Should clarify this is on new recruit.

**Comment by hardworlder** [comment]
I should also clarify I'm an idiot. Disregard.
