### ISSUE TITLE
[Anon] LA -   III: Emperor's Children: Rite of War (traitor) wrong

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3406]
**Problem:**
Rite of War (traitor) wrong

**Expected:**
Traitor allegiance for Emperors children should allow for the 3rd company elite rite of war, but this is only an option with loyalist allegiance

**List:** https://www.newrecruit.eu/app/list/OBUPr

**Comment by Mayegelt** [comment]
It does...

https://www.newrecruit.eu/app/list/VbUOC
