### ISSUE TITLE
[Anon] LA -  XIV: Death Guard: Veterans in Company Command Squad cannot take banners

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3407]
**Problem:**
Veterans in Company Command Squad cannot take banners

**Expected:**
New choice in Company Command Squad: Veteran w/banner OR Veteran w/Options

 **Additional Info:**
Previous version did not have this issue. Original source: Battle for Beta-Garmon

**List:** https://www.newrecruit.eu/app/list/BKfET

**Comment by Mayegelt** [comment]
Sorry about that. for some reason it didn't copy over when reformatting it.
Will be fixed in a sec.
