### ISSUE TITLE
[Anon] LA - XX: Alpha Legion: List says list has too many master of legion units, despite point limits allowing the unit

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3409]
**Problem:**
List says list has too many master of legion units, despite point limits allowing the unit

**Expected:**
One master of the Legion is allowed once per 1000 points, so the 3000 point list should allow up to three selections of said unit type

 **Additional Info:**
Liber Astartes/Hereticus, Page 19, Master of the Legion info box

**List:** https://www.newrecruit.eu/app/list/eM4Ba

**Comment by The4D6** [comment]
The list posted is less than 1000pts, so the error will display. nothing is wrong here.
