### ISSUE TITLE
[Anon] LI - Solar Auxilia: Missing unit for the Solar Auxilia


### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3411]
**Problem:**
Missing unit for the Solar Auxilia

**Expected:**
Veletaris Sentinel

 **Additional Info:**
The Veletaris Sentinel option for the Solar Auxilia is not present

**Comment by The4D6** [comment]
I believe the veletaris sentinel can only be taken as part of a veletaris tercio, so is not available to purchase standalone.
