### ISSUE TITLE
[Anon] LA -   VII: Imperial Fists: Evander Garrius marked as Legacy Unit

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3412]
**Problem:**
Evander Garrius marked as Legacy Unit

**Expected:**
Should he not be an exemplary unit? he got rules in one of those books did he not?

**List:** https://www.newrecruit.eu/app/list/bygtF

**Comment by The4D6** [comment]
I can't see this happening in the list builder, so closing.

If raised again, will get fixed.
