### ISSUE TITLE
[Anon] LI - Sisters of Silence: The Snaregun option is not available at this moment

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3415]
**Problem:**
The Snaregun option is not available at this moment

**Expected:**
I would like to see the snare gun to be added

 **Additional Info:**
Snare gun is available for 1 per 5 models for free

**List:** https://www.newrecruit.eu/app/list/0lrCg
**Unit:** Prosecutor Cadre, id: b4c2-8102-8847-b9fc

**Comment by The4D6** [comment]
You exchange the bolter for a snare gun, and as you have no bolters in the unit, the option isn't visible
