### ISSUE TITLE
[Anon] LA -  XVI: Sons of Horus: can’t change individual justaerin wargear 

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3416]
**Problem:**
can’t change individual justaerin wargear 

**Expected:**
to be able to change individual wargear, instead lightning claw and grenade harness is repeated 

**List:** https://www.newrecruit.eu/app/list/p8gfM
**Unit:** Justaerin Terminator Squad, id: c121-2d4a-e85e-14c7

**Comment by The4D6** [comment]
@Mayegelt Closing this as the same loadout issue were people don't know how to split models
