### ISSUE TITLE
[Anon] LA -   VII: Imperial Fists: Additional attack is being added to the dreadnaught profile (as system is seeing 2 melee weapons on the profile, through it 2 dreadnaughts with one weapon each)

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3417]
**Problem:**
Additional attack is being added to the dreadnaught profile (as system is seeing 2 melee weapons on the profile, through it 2 dreadnaughts with one weapon each)

**Expected:**
Additional attack shouldn't be added as each dreadnaught only has 1 melee weapon.

**List:** https://www.newrecruit.eu/app/list/7KEd7
**Unit:** Contemptor Dreadnought Talon, id: 52a6-f923-f1a7-f203

**Comment by The4D6** [comment]
Same issue as #3420
