### ISSUE TITLE
[Anon] LI - Solar Auxilia: If you add a command or vanguard section you get errors if you have more than 1 storm section

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3418]
**Problem:**
If you add a command or vanguard section you get errors if you have more than 1 storm section

**Expected:**
Should be upto 3 storm sections no matter about command or vanguard selection

**List:** https://www.newrecruit.eu/app/list/hzVeC
**Unit:** Veletaris Tercio, id: 5be2-1846-2870-ba0b

**Comment by The4D6** [comment]
Each Auxilia Veletaris Tercio is a single Elites choice, using up a single Elites slot on the Force Organisation chart. Each Auxilia Veletaris Tercio is composed of a number of separate units – the exact number of units in the Tercio is shown on the Auxilia Veletaris Tercio Organisation chart (shown below). **_An Auxilia Veletaris Tercio may not include more than three units._**
