### ISSUE TITLE
[Anon] LA -  XVII: Word Bearers: They are missing their weapon

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3421]
**Problem:**
They are missing their weapon

**Expected:**
Adding their weapon would be good (infernal armaments)

**List:** https://www.newrecruit.eu/app/list/2ERFD
**Unit:** Bound Daemon Brutes (Esoterist)[1], id: 2330-f3a4-f359-c3b4

**Comment by Dalethmann** [comment]
Oddly enough Ruinstorm Daemon Brutes and Bound Daemon Brutes have different profiles and weapons (go figure, probably a good candidate for an FAQ Errata for consistency but for now we suffer in confusion. Just as planned). They cannot be equipped with Infernal armaments but are missing their Brute armaments and their Hammer of Wrath (1) special rule.
Additional Info:
Horus Heresy: The Burning of Ohmn-Mat page 11
Horus Heresy: Daemons of Ruinstorm 9
