### ISSUE TITLE
[Anon] LA - XIX: Raven Guard: contemptor talon with more than one each contemptor has to have same weapons

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3423]
**Problem:**
contemptor talon with more than one each contemptor has to have same weapons

**Expected:**
expected contemptors to have different weapon load outs

 **Additional Info:**
libera astartes contemptor does not say all contemptors in a talon have to have same weapon load out

**List:** https://www.newrecruit.eu/app/list/N0vot
**Unit:** Contemptor Dreadnought Talon, id: 31cb-0e8f-9c63-a9f6

**Comment by The4D6** [comment]
@Mayegelt I think this is the same "issue" we were seeing before with the terminators
