### ISSUE TITLE
[Anon] LA -   III: Emperor's Children: Pride of the legion indomitus terminators not counting for compulsory troops count

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3427]
**Problem:**
Pride of the legion indomitus terminators not counting for compulsory troops count

**Expected:**
Indomintus terminators seem to not count for number of units selected pride of the legion compulsory troops when it comes to error checking.

 **Additional Info:**
list should not have any errors, but says i need one more compulsory troop, but on the right hand side when selected indomintus terminator squad say it's 2/2. If i add another cataphractii terminator unit and also select it to be compulsory troop i get the expected error that there are too many compulsory troops selected (as expected). Kinda a niche problem I know 

**List:** https://www.newrecruit.eu/app/list/F4ipq

**Comment by nstephenh** [comment]
Indomitus terminators have support squad.
