### ISSUE TITLE
Garro

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#3431]
It seems that between legacy doc v1.1 and v1.2 they changed his swords special rules.
It used to include reach 1 in the "edge of truth" rule. But now has Dualists edge (1) on the sword.
The DE rule had been added, but the Reach rule hadn't been removed from the Edge of Truth description.

**Comment by The4D6** [comment]
1.2 is no longer the latest version, legacies is on 1.3 now and the rule has been removed

![image](https://github.com/user-attachments/assets/2bbe0426-34eb-481f-9bc9-35e30795a640)

**Comment by The4D6** [comment]
Link to latest, closing this as I don't think it's an issue

https://assets.warhammer-community.com/dave-s-downloads-25-09/horusheresy_legaciesoftheageofdarkness_legionesastartes_eng_24.09.23.pdf

**Comment by Mayegelt** [comment]
The description on BS is still showing it as part of the rule
![Screenshot_2024-11-22-09-16-46-519_net battlescribe mobile rostereditor](https://github.com/user-attachments/assets/01c842b4-8418-4137-9997-2e9f57c9a001)

**Comment by The4D6** [comment]
Ahhhh my misunderstanding
