### ISSUE TITLE
[Anon] LA -   I: Dark Angels: In deathwing companion detachement, all companions lost their bolter options, if I choose 1 companion to replace its bolter for another option. It seems that, if I change 1 thing the whole unit will recieve the same modification.

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3433]
**Problem:**
In deathwing companion detachement, all companions lost their bolter options, if I choose 1 companion to replace its bolter for another option. It seems that, if I change 1 thing the whole unit will recieve the same modification.

**Expected:**
The book says the unit come with the following:
- calibanite warblade
- Bolter
- bolt pistol, etc.
Options section:
Any model in the unit may exchange its bolter for one of the following:
- magna combi-weapon
- minor combi-weapon
- plasma pistol
- cytheron pattern aegis

This means that the correct behaviour is that, if I change only 1 copmpanions bolter to a different thing, the rest of the companions keep their bolters, until I change theirs too.

 **Additional Info:**
Liber Astartes - Loyalist Legions - Deathwing Companion Detachement page - page nr. 164

**List:** https://www.newrecruit.eu/app/list/sbW8c

**Comment by The4D6** [comment]
This appears to be user error from not understanding how to split a unit up

**Comment by pi1ci** [comment]
> This appears to be user error from not understanding how to split a unit up

you are right, I never tried that before. Sorry for the report.
