### ISSUE TITLE
[Anon] LA -   VII: Imperial Fists: Master of the legion bug (max 0)

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3435]
**Problem:**
Master of the legion bug (max 0)

**Expected:**
I would like to put primach in my list

 **Additional Info:**
It won’t let me put the primach in my list because of master of the legion 1 max 0

**List:** https://www.newrecruit.eu/app/list/zwkNU
**Unit:** Rogal Dorn, id: 6de5-a6a9-bf25-76c8

**Comment by Mayegelt** [comment]
Force didn't have enough points spent
