### ISSUE TITLE
[Anon] Mechanicum: Castalax battle automata within the same unit are forced to take the same main weapon

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3436]
**Problem:**
Castalax battle automata within the same unit are forced to take the same main weapon

**Expected:**
Castalax battle automata within the same unit can each have different main and melee weapons

 **Additional Info:**
Liber Mechanicum. Page 37. The rules referring to wargear options for melee and ranged weapons state “any castalax” rather then “all castalax”

**List:** https://www.newrecruit.eu/app/list/meiKe
**Unit:** Castellax Battle-Automata Maniple, id: 3c04-f537-6cf1-65bc

**Comment by The4D6** [comment]
This is not a bug, you need to split the units apart with this button
![image](https://github.com/user-attachments/assets/596fb932-a724-4466-a367-5d246ff10241)
