### ISSUE TITLE
[Anon] BG - Blackshields: Oath of Vengeance "In Disgrace All Are Equal" is selected but HQ choices are available and required.

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3437]
**Problem:**
Oath of Vengeance "In Disgrace All Are Equal" is selected but HQ choices are available and required.

**Expected:**
HQ options should not be required or allowed if this oath of vengeance and wrath is selected.

**List:** https://www.newrecruit.eu/app/list/LB4ac

**Comment by The4D6** [comment]
Duplicate of #3443
