### ISSUE TITLE
[Anon] Questoris Household: Provenances of war are missing entry's for 12 & 13 debased rabble and tainted flesh

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3438]
**Problem:**
Provenances of war are missing entry's for 12 & 13 debased rabble and tainted flesh

**Expected:**
The Provenances of war debased rabble and tainted flesh to be added 

 **Additional Info:**
https://assets.warhammer-community.com/horusheresy_legaciesoftheageofdarkness_imperialismilitia_eng_24.09-tyq53ht49b.pdf

**List:** https://www.newrecruit.eu/app/list/7fFkj
**Unit:** Provenances of War, id: 37de-ba3c-f798-5bcb

**Comment by The4D6** [comment]
The provenances you are asking for are only available to a Traitor detachment. You have selected aa Loyalist allegiance for the militia detachment.
