### ISSUE TITLE
[Anon] LA -   VII: Imperial Fists: Master of the legion bug 

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3439]
**Problem:**
Master of the legion bug 

**Expected:**
I wanted to build a army list with some of my favourite models but it said that I have to many master of the legion 

**List:** https://www.newrecruit.eu/app/list/9V1Nx
**Unit:** Praetor, id: 66e7-ee64-2389-9645

**Comment by The4D6** [comment]
This is not a bug, you can only play one Master of the Legion model per 1000pts, and you have 2 at 1940pts (praetor and Dorn).

You either need to bring the list up to 2000pts or drop a master of the legion
