### ISSUE TITLE
[Anon] LA -  X: Iron Hands: Sky-Hunter Squadron displays Heavy Bolter in its profile when all have been replaced with multi-meltas

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3441]
**Problem:**
Sky-Hunter Squadron displays Heavy Bolter in its profile when all have been replaced with multi-meltas

**Expected:**
Only the multi-meltas should be displayed as the jetbike weapon options, heavy bolter should not be listed

**List:** https://www.newrecruit.eu/app/list/ZuJ0E

**Comment by The4D6** [comment]
This is because the jetbike is a wargear item and comes with a heavy bolter by default. 

The hiding logic for this is not supported by BattleScribe, only NewRecruit.
