### ISSUE TITLE
[Anon] Mechanicum: no option to change the leman russ command tank's battle cannon

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3446]
**Problem:**
no option to change the leman russ command tank's battle cannon

**Expected:**

**List:** https://www.newrecruit.eu/app/list/mLDY8
**Unit:** Armoured Tercio, id: 0ff6-56d1-caf7-893f

**Comment by The4D6** [comment]
This is by design in the books
