### ISSUE TITLE
[Anon] LA -  XVII: Word Bearers: Incorrect weapon options for Procurator

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3457]
**Problem:**
Incorrect weapon options for Procurator

**Expected:**
Any Procurator may exchange their chainsword for a: Heavy chainsword, Power weapon.
Power fist is not included as a weapon upgrade for the Procurator. This option is exclusive to the Procurants only.
(Random/ Optimization Note): Why are options for Procurant w/Options all listed separately for every combination instead of having a single click drop down menu for the Bolt Pistol and Chainsword such as one found in Despoiler Squad: Despoiler w/Options? 

 **Additional Info:**
Horus Heresy: The Scouring of Gilden’s Star page 8

**List:** https://www.newrecruit.eu/app/list/AyeBy
**Unit:** Procurators, id: f98a-c47f-c564-7cfc

**Comment by The4D6** [comment]
The procurants are in buckets because it makes the list output nicer
