### ISSUE TITLE
Word Bearers Mhara Gal Dreadnought STILL has Blind

### ISSUE THREAD

**Issue by m455954** [BSData/horus-heresy#3461]
The fix that went into 19.3.0 (#3434 in fix bundle #3448) seems to have regressed in 19.4.0 as the unit still has Blind

**Comment by m455954** [comment]
![image](https://github.com/user-attachments/assets/fb70fa4e-649c-4ced-8538-775d2f9f2892)

**Comment by The4D6** [comment]
Found it, was on the regular boltspitter
