### ISSUE TITLE
[Anon] LI - Solar Auxilia: Veletaris Tercio has Hermes Veletaris Squadron listed as an option instead of the Veletaris Vanguard Section. 

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3472]
**Problem:**
Veletaris Tercio has Hermes Veletaris Squadron listed as an option instead of the Veletaris Vanguard Section. 

**Expected:**
Remove Hermes Squadron and replace it with Veletaris Vanguard section. 

 **Additional Info:**
Source is Liber Imperium page 80 to 83. 

**List:** https://www.newrecruit.eu/app/list/1fAEM

**Comment by The4D6** [comment]
I'm not convinced this is actually an issue, and I don't really understand what this report means as I cannot see anything wrong
