### ISSUE TITLE
[Anon] LA -   III: Emperor's Children: Unable to take a Rite of War despite having the required unit/upgrade. 

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3473]
**Problem:**
Unable to take a Rite of War despite having the required unit/upgrade. 

**Expected:**
You can take the Maru Skara with a Pheonix Warden Consul. 

**List:** https://www.newrecruit.eu/app/list/ek346

**Comment by The4D6** [comment]
You still need a model with Master of the Legion, which you don't have
