### ISSUE TITLE
[Anon] LA -   IV: Iron Warriors: Unable to equip dreadnoughts in talon differently.

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3474]
**Problem:**
Unable to equip dreadnoughts in talon differently.

**Expected:**
Ability to customize each dreadnought.

 **Additional Info:**
Liber Astartes/Hereticus

**List:** https://www.newrecruit.eu/app/list/ONYDW
**Unit:** Contemptor Dreadnought Talon, id: d1bf-1149-3a68-e317

**Comment by The4D6** [comment]
Multi-select issue, need to split models apart in units
