### ISSUE TITLE
Toggle mixed tercios

### ISSUE THREAD

**Issue by Hamemer** [BSData/horus-heresy#3477]
Currently the app hides the other entries when a tercio is taken (for example support armoured tercio for thunderer or tank destroyers), however some people allow mixed entries in the same tercio, please unhide them or give an option to toggle, for opponents to agree between themselves.

**Comment by The4D6** [comment]
Hi there,

Unfortunately if a selection is not supported by the official rules, it's not something we will look to include in the data set.

Some people take the word of BattleScribe/NR as gospel, and so if we begin to include things that aren't actually allowed, people unfortunately will take it in games assuming it's fair to use.

**Comment by Hamemer** [comment]
Thats honestly a word of contention. P.100 for example

[..]the exact number of units in the Tercio is shown on the Auxilia Artillery Tercio organisation chart (shown below). An Auxilia Artillery Tercio may not include more than three units.[..]

You are technically already mixing the tercio with the command tercio included anyway.

**Comment by The4D6** [comment]
Some tercios (such as theVeletarii) can be mixed.
Some cannot as they say "1-3 of _*either*_ <X unit> or <Y unit>"

> You are technically already mixing the tercio with the command section included anyway. There are no rules from the command section to override a mono entry tercio.

I'm not saying a Tercio cannot mix units _at all_, I'm saying you have to abide by wha tit says underneath the tercio description. Nearly all of them say:
- 0-1 of <Command ssection variant>
- 1-3 of <Whatever other unit>

In the case of the armoured support tercio, the unit allowed are no more than 3 total of the following:
- 0-1 Armoured Command Section
- 1-3 of _either_ Thunderer/Destroyer squadrons or Trojans

Valid configurations of the above include:
- 1 single Trojan
- A single squadron of thunderers and a command tank
- Three squadronss of destroyers
etc etc

It does not mean you can take:
- A command tank, a trojan, and a destroyer squadron

Now I agree with you that this is a contentious topic and the use of written English here is not fantastic. However, until it's cleared up by an FAQ, we're sticking with what appears to be the consensus
