### ISSUE TITLE
[Anon] LA -  X: Iron Hands: The seeker sergeant should be able to swap chain sword for power fist

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3478]
**Problem:**
The seeker sergeant should be able to swap chain sword for power fist

**Expected:**
When I select power fist I should be able to keep the kraken bolger

 **Additional Info:**
The power fist selection automatically deselects the kraken bolter

**Comment by The4D6** [comment]
This is intended behaviour, if you read the entry:
- You swap the kraken bolter for a chainsword
- You swap the kraken bolter _or_ a chainsword for a power fist
