### ISSUE TITLE
[Anon] LA -   VIII: Night Lords: The legion delegatus special rule allowing a rite of war in detachments under 1k points is missing and is marked in error.

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3479]
**Problem:**
The legion delegatus special rule allowing a rite of war in detachments under 1k points is missing and is marked in error.

**Expected:**

**List:** https://www.newrecruit.eu/app/list/8O02v
**Unit:** Centurion, id: c59f-e5d9-186b-a729

**Comment by The4D6** [comment]
The error in this list is not that you cannot take a delegatus in an allied detachment, but that your list has two models with master of the legion and doesn't total 2000pts.

As per Master of the Legion, you can only have one per 1000pts
