### ISSUE TITLE
[Anon] LA -   VII: Imperial Fists: Cannot access the compulsory units 

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3480]
**Problem:**
Cannot access the compulsory units 

**Expected:**
Open up and give me a list of compulsory units 

**List:** https://www.newrecruit.eu/app/list/EDuBL

**Comment by The4D6** [comment]
The issue here is that your rite of war requires you to take Phalanx Warders as comp troops and you haven't selected them
