### ISSUE TITLE
[Anon] LA -  XVII: Word Bearers: Word Bearers don't have legion specific units listed as options other than Ashen Circle

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3482]
**Problem:**
Word Bearers don't have legion specific units listed as options other than Ashen Circle

**Expected:**
Can you please add them? 

**List:** https://www.newrecruit.eu/app/list/jYcUg

**Comment by The4D6** [comment]
You have your allegiance set to loyalist, to see the others it needs to be Traitor
