### ISSUE TITLE
[Anon] LA -   I: Dark Angels: Herald upgrade is charging 2pts for standard when it should be a free upgrade

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3483]
**Problem:**
Herald upgrade is charging 2pts for standard when it should be a free upgrade

**Expected:**
Legion standards should be free upgrade but it has a points cost

**List:** https://www.newrecruit.eu/app/list/hwwts
**Unit:** Centurion[1], id: d5b2-f823-d621-330f

**Comment by The4D6** [comment]
You are looking under the submenu which includes the option to buy a bolter and exchange that for the standard

If you look under bolt pistol/chainsword options there is a free swap from a bolt pistol to the standard
