### ISSUE TITLE
[Anon] LA -   IV: Iron Warriors: Land raider transport capacity is 12 but i can only select it with 5 teminator instead of 6

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/horus-heresy#3486]
**Problem:**
Land raider transport capacity is 12 but i can only select it with 5 teminator instead of 6

**Expected:**
to be able to pick a land raider for 6 terminators 

**List:** https://www.newrecruit.eu/app/list/yRzpL

**Comment by The4D6** [comment]
This is as intended

The data sheet only allows an LR transport at 5 models
