### ISSUE TITLE
Port Additional Lords of War from 40k Files

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#356]
So, this will be ugly, due to a long-ago fork in the Vehicle Profile.

Here's the relevant text:
Using additional Super-heavy & Orbital Strike Wing Flyer Units
The vast milieu of battle during the Horus Heresy and the armies of the Great Crusade were staggeringly diverse, with only the most common or singular currently dealt with by Forge World’s Horus Heresy supplements. In order to represent this diversity when it comes to Super-heavy vehicles and Flyers, this section presents a list of additional models which may be used. In many cases, the Imperium of the Great Crusade sees the origin of some of these designs, while in others they can simply be used to stand in for one of the many less-widespread war machine types and unique patterns employed by a vast Imperial armed force, far less regimented and standardised than its 41st Millennium counterpart. Where general options are listed but not found on the vehicle’s profile or within this book, or refer explicitly to the 41st Millennium (i.e., Commissar tanks), ignore those options:

- [x] Baneblade, 
- [x] Banehammer, 
- [x] Stormlord, 
- [x] Shadowsword, 
- [x] Stormsword
- [x] Macharius 

and variants (representing indigenous war machines)
- [x] Macharius Vulcan
- [x] Macharious Vanquiser
- [x] Crassus 
and variants (representing indigenous war machines)
- [x] PRAETOR ARMOURED ASSAULT LAUNCHER

- [x] Marauder Bomber,
- [x] Marauder Destroyer,
- [x] Thunderbolt Heavy Fighter,
- [x] Crusade Avenger Strike Fighter (see Mechanicum Taghmata army list)
- [x] Minotaur (see Taghmata Omnissiah army list)

_When used in conjunction with this army list, these vehicles may be further modified by the following upgrades:_

**Space Marine Crew (Super-heavy Tanks only):+15 points**
- [x] Baneblade, 
- [x] Banehammer, 
- [x] Stormlord, 
- [x] Shadowsword, 
- [x] Stormsword
- [x] Macharius

**This should included a BS +1 modifier for the Super-heavy in question.**
 and variants (representing indigenous war machines)
- [x] Macharius Vulcan
- [x] Macharius Vanquiser

- [x] Crassus 

and variants (representing indigenous war machines)
- [x] PRAETOR ARMOURED ASSAULT LAUNCHER

**Battle Servitor Control (Flyers only):+15 points. If taken as an option for a Sub-orbital Strike Wing, then all the Flyers in the wing must be so upgraded**
- [x] Marauder Bomber, 
- [x] Marauder Destroyer, 
- [x] Thunderbolt Heavy Fighter, 
- [x] Crusade Avenger Strike Fighter

**Comment by capitaladot** [comment]
Here's the relevant text:
Using additional Super-heavy & Orbital Strike Wing Flyer Units
The vast milieu of battle during the Horus Heresy and the armies of the Great Crusade were staggeringly diverse, with only the most common or singular currently dealt with by Forge World’s Horus Heresy supplements. In order to represent this diversity when it comes to Super-heavy vehicles and Flyers, this section presents a list of additional models which may be used. In many cases, the Imperium of the Great Crusade sees the origin of some of these designs, while in others they can simply be used to stand in for one of the many less-widespread war machine types and unique patterns employed by a vast Imperial armed force, far less regimented and standardised than its 41st Millennium counterpart. Where general options are listed but not found on the vehicle’s profile or within this book, or refer explicitly to the 41st Millennium (i.e., Commissar tanks), ignore those options:
- [ ] Baneblade, 
- [ ] Banehammer, 
- [ ] Stormlord, 
- [ ] Shadowsword, 
- [ ] Stormsword
- [ ] Macharius and variants (representing indigenous war machines)
- [ ] Macharius Vulcan
- [ ] Macharious Vanquiser
- [ ] Crassus and variants (representing indigenous war machines)
- [ ] PRAETOR ARMOURED ASSAULT LAUNCHER
- [ ] Marauder Bomber, 
- [ ] Marauder Destroyer, 
- [ ] Thunderbolt Heavy Fighter, 
- [ ] Crusade Avenger Strike Fighter (see Mechanicum Taghmata army list)
- [ ] Minotaur (see Taghmata Omnissiah army list)
When used in conjunction with this army list, these vehicles may be further modified by the following upgrades:
Space Marine Crew (Super-heavy Tanks only):+15 points
- [ ] Baneblade, 
- [ ] Banehammer, 
- [ ] Stormlord, 
- [ ] Shadowsword, 
- [ ] Stormsword
- [ ] Macharius and variants (representing indigenous war machines)
- [ ] Macharius Vulcan
- [ ] Macharious Vanquiser
- [ ] Crassus and variants (representing indigenous war machines)
- [ ] PRAETOR ARMOURED ASSAULT LAUNCHER
Battle Servitor Control (Flyers only):+15 points. If taken as an option for a Sub-orbital Strike Wing, then all the Flyers in the wing must be so upgraded
- [ ] Marauder Bomber, 
- [ ] Marauder Destroyer, 
- [ ] Thunderbolt Heavy Fighter, 
- [ ] Crusade Avenger Strike Fighteri

**Comment by Millicant** [comment]
I think this should get rolled into 2.0a, otherwise we'll just be doing
this over again in a few months.

**Comment by capitaladot** [comment]
Sounds good... 'cause I've tried doing some of this in the past and really don't want to, again, unless someone like @amis92 has a script laying around to convert profiles so they'll work (like the 40k guys did with the flyers).

**Comment by capitaladot** [comment]
So, @Mayegelt stepped up to the plate on this.

**Comment by Mayegelt** [comment]
:) Made an update. Not added a lot, but fixed a few bits that I had added.

**Comment by Mayegelt** [comment]
More updates done. Left as a pull request on my fork.
Should be good. Just fixed a couple of errors on the current stuff like some of them not having War Machine Detachment rules. Also 2 of them were not in a sub entry, so couldn't be bought as a 1-2 as a single LoW.
So should be able to tick all the rest of the boxes and close this one down i think.
