### ISSUE TITLE
v130 Chainglaives issue on Centurion + Chaplins

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#379]
Latest downloaded version (v130) Nightlord Nostroman Chainglaive for Centurions that replace the chainsword are showing as 10pts and should be 15pts when in power armour & for a Chaplin should should be 0pts.

**Comment by capitaladot** [comment]
Is this from the book or something someone's cousin at Forge World heard Alan Bligh say on the way to the loo? ;)

If the former, can I get a book and page number to look it up?

**Comment by Mayegelt** [comment]
I asked Alan Bligh at FW Open day as i asked "Is the power weapon that the Chaplin gets as an upgrade for the purpose of Nightlords chainglaives, in the same way as it does if you buy Terminator Armour as an upgrade to your character."
Quotey rules 

> "Any character or Independent Character with the Legiones Astartes (Night Lords) special rule eligible to take a power weapon as part of their options, may instead take a Nostraman Chainglaive for the same listed cost." 

Upgrading to a Consul Chaplin is an option that grants a power weapon
Wargear
Crozius Arcanum – power weapon (type as shown on model).

He looked at my phone with the wording on it and agreed it was an upgrade.

**Comment by capitaladot** [comment]
Oh, right-on... so, a Nostraman Chainglaive Crozius? Wacky.

**Comment by Mayegelt** [comment]
Yes :)

**Comment by capitaladot** [comment]
Fixed.. and also the powerfist for bolt pistol on Primus Medicae (the power fist for chainsword was already in there).

**Comment by Mayegelt** [comment]
@capitaladot seems you have put the reduced cost for if they swap their bolt pistol for the glaive, not the combat weapon. I would assume the power weapon would be the replacement for the combat blade/chainsword rather than the bolt pistol.
