### ISSUE TITLE
V130 War Machine Detachment

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#381]
Can only take 1 Knight / Cerb / Typhon, no option to take the second one.

**Comment by capitaladot** [comment]
Fixed. Had to add another layer in the menu to allow proper "single choice, duplicated" behavior.

**Comment by Mayegelt** [comment]
@capitaladot is this in V130 or is it a later one. As some of the V130 issues i put up seemed to be added in V130 now, but weren't when submitted. But this one does not seem to be working still.
It seems that they are no longer grouped under "War Machine Detachment" in the book (only under the rules saying about how one works). So each could just be added as its own entity in the same way as the Malcador shifted to be its own.

**Comment by capitaladot** [comment]
Now on version 138.

**Comment by Mayegelt** [comment]
Wow! also seen that Typhon and Cerb, the Hunter killer missiles are still at 10pts rather than the new 5pts. But you may have fixed that one :)

**Comment by capitaladot** [comment]
HKs for War Machines now fixed in 139.
