### ISSUE TITLE
Questoris Crusader weapon option (V130) AoD Legion, Also Questoris List

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#386]
Still working with V130 for as http://battlescribedata.appspot.com/#/repo/horus-heresy hasn't updated and can't seem to make the other file work. For Age of Darkness Legions. But also not on the Questoris Knights one.

Questoris Knight Crusaders can replace the Gatling Cannon with with either Questoris Battle Cannon with Heavy Stubber OR Rapid Fire Battle Cannon with Heavy Stubber. Currently it only has the option for a Rapid Fire Battle Cannon with Heavy Stubber.

~~Also in
case not seen on that closed issue, the Hunter Killer missiles on Typhon and Cerb are still showing as 10pts when they should be 5pts.
Also the Chaplin still has an issue. The power sword is set to 0pts when not a Chaplin and the Glaive is showing as being for 0pts in exchange for the bolt pistol, rather than the melee weapon arm.~~
Fixed.

As said before, keep up the good work, we all appreciate you for it :)

**Comment by capitaladot** [comment]
What book or FAQ is this new option defined in?

**Comment by Mayegelt** [comment]
HH -CRUSADE IMPERIALIS - ARMY LIST pg112

**Comment by Mayegelt** [comment]
Also the "may exchange Avenger Gatling cannon for" needs Default Selection changed to Avenger Gatling Cannon

**Comment by Mayegelt** [comment]
https://drive.google.com/open?id=0B2WSzVPkudYKWFBmek9IV0lBZUU

That is the link to my version of the file stored on my googledrive with the update for both the Chaplin and Malcador, Added the Questoris Battle Cannon to the Crusader (including remembering to make sure it has the melta upgrade for it if wanted).

**Comment by capitaladot** [comment]
Fixed.
