### ISSUE TITLE
Malcador sponsors

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#387]
Sorry me again with a Malcador one...

"May upgrade both sponson weapons to a pair of:" needs to have a min of 1 rather than 0 as it comes with Heavy Bolters. It is set as the "default" option but without the min 1 choice it doesn't auto select it.

**Comment by Mayegelt** [comment]
https://drive.google.com/open?id=0B2WSzVPkudYKWFBmek9IV0lBZUU

That is the link to my version of the file stored on my googledrive with the update for both the Chaplin and Malcador, Added the Questoris Battle Cannon to the Crusader (including remembering to make sure it has the melta upgrade for it if wanted).

**Comment by capitaladot** [comment]
Fixed.
