### ISSUE TITLE
Chaplins again... sorry...

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#388]
I have modified it to work well.

See picy below, though here is the basic

![image](https://cloud.githubusercontent.com/assets/20280410/17052769/c36a1822-4ff6-11e6-9c33-1a1a1caec4b9.png)

I made a new entry for Nostaman Chainglaives for both the replace bolt pistol and replace chainsword sections of the centurion.
Inside that i put copy/pasted the shared entry for chainglaives.
Then Set Points to 0 condition
(And)
If chaplins equals 1
If weapons has equal to 0 for the chainglaive and power weapon from the other entry (aka pistol side from the chainsword side and chainsword side from the pistol one) 

Also adding a simalar structure to the power weapons entries that already exist.

So this means if you select a power weapon for the chainsword replacement, it makes the power weapon and chainglaive cost 15pts if you would replace them for the bolt pistol side, and vice versa. I know it would be uncommon, but i can see some wishing to use a chainglaive and a power axe for the AP2 garenteed sometimes, or maul for the additional strength and concussion.

**Comment by Mayegelt** [comment]
https://drive.google.com/open?id=0B2WSzVPkudYKWFBmek9IV0lBZUU

That is the link to my version of the file stored on my googledrive with the update for both the Chaplin and Malcador, Added the Questoris Battle Cannon to the Crusader (including remembering to make sure it has the melta upgrade for it if wanted).

**Comment by capitaladot** [comment]
I redid this whole section last night, combining the two lists of choices into one to get the math right.
