### ISSUE TITLE
Death from the skies

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#389]
https://www.forgeworld.co.uk/resources/fw_site/fw_pdfs/Warhammer_40000/Death-from-the-Skies.pdf

New update today to add the Death from the skies profiles...
Sounds like a lot of work adding Role, Pursuit, Agility to a dozen things.

**Comment by capitaladot** [comment]
As much as I might like it to be, this is only for 40k, not the HH.

**Comment by thebiggeordiegeek** [comment]
Can I suggest this be looked at again as Death from the Skies is being used at the Throne of Skulls so it looks like it's part of the game.

https://www.facebook.com/events/904082969690050/permalink/987849937980019/

**Comment by capitaladot** [comment]
Okay, okay... I just know the grognards in my local meta are unlikely to allow it, and it will be a big effort to implement.
@thebiggeordiegeek, care to give it a shot? I'll merge your pull request.

**Comment by thebiggeordiegeek** [comment]
I wish I could, but I am afraid the skills for the work is beyond my capability, sorry.

**Comment by Millicant** [comment]
Don't think this is going to happen. No precedent for including a 40k supplement into the 30k catalogues. 

On top of that, the workload is too much. We are already trying to split between two versions simultaneously for 2.0a. 

If you want to use it, go ahead. It just won't be viable with Batttlescribe.

**Comment by capitaladot** [comment]
So, @Mayegelt was kind enough to enter all of this (albeit in the "Type" Characteristic of Vehicles, but including all the rules), so I made a proper Flyer Profile Type did some regexp to parse these out into new Flyer profiles, even if just for the Throne of Skulls guys to use at that event.

**Comment by Millicant** [comment]
Ugh this is such a pain.  

There is little consensus on how this interacts with 30k.  Technically it "Replaces the flyer rules" so we should be using it, right?  Forgeworld also released their flyers update so we have the profile data, albeit all "40k" versions.  

So really, our inputs to this seem to be limited to adding the new profile data.  Basically just adding Pursuit/Agility numbers to the flyer profiles, yes?  No rules should be added anywhere since they are all 40k specific.  

Am I on-track here?

**Comment by Mayegelt** [comment]
I think as 30K is a supplement to 40K it will probably be like W40K Stronghold Assault (also a supplement) is usable for the rules for fortifications.
Much like in 40k you can use Death from the Skies, Escalation, Stronghold Assault & Imperial Armour books all in 40K, as they are all supplements, none of them restricting the use of any of the others.
