### ISSUE TITLE
Nightlord Chaplins again again... sorry... again...

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#391]
Nightlord Chaplins taking both a Glaive and Power Weapon end up getting the first one for free, but if they select the second one they pay 15pts for each of them (so 30pts total) rather than what you have with 2 power weapons being 7.5pts (15pts for the pair) if you buy 2.

**Comment by capitaladot** [comment]
Nope, this is right; first power weapon for free, second for 15 points.

**Comment by Mayegelt** [comment]
@capitaladot  Yeah, but if you select 1 power weapon and 1 glaive, It charges you 15pts for the power weapon AND 15pts for the glaive
![image](https://cloud.githubusercontent.com/assets/20280410/17069066/74c42c20-504c-11e6-83fd-596ed2378042.png)

**Comment by Mayegelt** [comment]
![image](https://cloud.githubusercontent.com/assets/20280410/17069602/7104305a-504f-11e6-9837-2b02c3247d55.png)

Fix. Just need an Or under the And

![image](https://cloud.githubusercontent.com/assets/20280410/17069618/9560e09c-504f-11e6-85af-99b466b81eb3.png)

![image](https://cloud.githubusercontent.com/assets/20280410/17069747/2bd5cd30-5050-11e6-935a-20bcd7587121.png)

![image](https://cloud.githubusercontent.com/assets/20280410/17069801/7261e4f0-5050-11e6-8d72-5f68be2edc8f.png)

![image](https://cloud.githubusercontent.com/assets/20280410/17069695/e19afd08-504f-11e6-845e-c40799bb6661.png)

**Comment by capitaladot** [comment]
Fixed, hopefully right this time (shows 7.5 points, when taking two power weapons or power weapon and chainglaive as Chaplain, but points total is right, which is I think more important than it looking perfect).
