### ISSUE TITLE
V145 Questoris Knights in AoD Legions

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#392]
Need to Error that you can once again only take 1 Knight. Need Max Selections increased to 2 again. The rest are fine in War Machine Detachment.

**Comment by capitaladot** [comment]
Fixed. Moved out of War Machine detachment. Tested this before, seemed to work... must have been late.

**Comment by capitaladot** [comment]
Ugh... I swore this tested fine!

**Comment by capitaladot** [comment]
Okay, fixed for real this time.
