### ISSUE TITLE
Covenant of Fire rite creating invalid error

### ISSUE THREAD

**Issue by gungagreg** [BSData/horus-heresy#396]
When adding covenant of fire as a rite to a 30k Salamander list, I am getting a recurring error when the rite is chosen.

 The error states "Legiones Astartes: Age of Darkness Army List (Age of Darkness) has 3 too many selections from May be upgraded to one of these Consul roles: (maximum-3)..."

I start with a valid AoD list...loyalist Salamander...Preator and two tactical squads.  As soon as I assign the Praetor the Covenant ROW the error pops.  Pops even if starting with just the Praetor.  Reference to consul indicates some error linking the rite to consul positions.

**Comment by capitaladot** [comment]
Thanks for the report; certainly a bug with Covenant of Fire and its Consul restrictions.

**Comment by capitaladot** [comment]
Covenant of Fire or Awakening of Fire?

**Comment by capitaladot** [comment]
I think this got clobbered in a merge. Fixed.
