### ISSUE TITLE
Not all consuls should have the support officer rule

### ISSUE THREAD

**Issue by cowomo404** [BSData/horus-heresy#408]
The new rules for *some* consuls not being able to be used at  compulsory HQ choices is listed on page 19 of the new red book, but this rule does not apply to ALL upgraded centurions.

The consul types impacted have the special rule "support officer" listed in their special rules. Page 19 serves only to outline what the rule means. It appears all of the consuls in the data have this rule applied erroneously.

Consuls which should have the support officer rules:
- Librarian
- Master of signals
- Primus medicae
- Praevian
- Herald

Consul which **should NOT** have the support officer special rules:
- Champion
- Forge lord
- Siege breaker
- Chaplain
- Vigilator
- Moritat** but may not be compulsory HQ
- Delegatus
- Diabolist

**Comment by capitaladot** [comment]
I will take a look and sort this out. I may have deferred over-much to some of the summaries (e.g. Garro).

**Comment by cowomo404** [comment]
No problem, I'm not sure the support office rule is being enforced currently any way. I will double check in a bit. If this needs to be held over until BS 2.0 that works too. 

** Is there a way to segment issues that are known but will not be fixed until the new version is released? Or how is that being managed by the team?

**Comment by capitaladot** [comment]
I fixed who gets SuppOff and released it last night. 
The best bet is to copy paste your issue into the other project if feedback indicates it is can't be implemented in 1.x.

**Comment by cowomo404** [comment]
Roger Roger.

I double checked and it looks like the consuls are correct **except** the Delegatus which shows as having support officer but should not per the book.

**Comment by capitaladot** [comment]
Fixed that last; will release tonight.
