### ISSUE TITLE
Legion astartes (Word Bearer) primary detachment is subject to charismatic leadership rule

### ISSUE THREAD

**Issue by cowomo404** [BSData/horus-heresy#409]
Page 92 of AoDL red book 
Any primary detachment forced chosen from the word bearers legion **must** take a second  compulsory HQ choice in the fourth organization chart (where a second choice is allowed). 
This choice **must** always be either a centurian or a chaplain consul.

**Comment by capitaladot** [comment]
I'm not sure this can really be enforced in BattleScribe 1.,x as the logic engine is a bit limited. This might be a better issue for the 2.x project. 
https://github.com/BSData/horus-heresy-bs2prep
I think the best I can do is require a Centurion or Chaplain if Word Bearers is selected.

**Comment by cowomo404** [comment]
Requiring a Centurion or Chaplain is probably okay for now. (technically it could allow an invalid army list) but holding this until BS2.0 seems to make sense. - Maybe stick this in the known issue hold for BS2.0 bucket.

**Comment by capitaladot** [comment]
Released WB req for Chaplain/Centurion last night.
