### ISSUE TITLE
 new cortex controller rules of for each controller you get 0-1 choice of thallax castellax and now vorax

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#412]
**File:** (HH) Legiones Astartes - Age of Darkness Army List.catz

**BattleScribe version:** 1.15.08

**Platform:** Android

**Dropbox:** No

**Description:** The new cortex controller rules of for each controller you get 0-1 choice of thallax castellax and now vorax

**Comment by capitaladot** [comment]
"A **single unit** of either Castellax or Vorax class Battle-automata must be selected as part of the Legion Praevian unit (note that Battle-automata units selected in this fashion may not take the Paragon of Metal upgrade). This unit does not use up an additional Force Organisation choice and the Legion Praevian must be included as part of the unit even if it includes **models** of the Monstrous Creature type (while it is part of a unit of Monstrous Creature**s**,"
