### ISSUE TITLE
points cost for the Land Raider Proteus dedicated transport option, which is available to survivors of the dark age, needs to be adjusted to be in line with the new crusade army list.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#413]
**File:** (HH) Imperialis Militia and Cults Army List.catz

**BattleScribe version:** 1.15.08

**Platform:** Android

**Dropbox:** No

**Description:** The points cost for the Land Raider Proteus dedicated transport option, which is available to survivors of the dark age, needs to be adjusted to be in line with the new crusade army list.

**Comment by capitaladot** [comment]
Sorry, it actually looks like that option was deleted.

"Survivors of the Dark Age.....+75 points
The force has its origins on a world which survived with many of the wonders of the Dark Age of Technology intact, and its forces are equipped with weapons and equipment which are potent, if idiosyncratic, in origin.
All eligible units and models receive an increase of +1 to their basic Armour save (5+ becoming 4+ and so on) to a maximum of 3+. However, the detachment’s compulsory Troops choices must be filled by Grenadier squads, and in addition Inducted Levy squads in an army with this Provenance gain the Support Squad special rule and this Provenance itself may not be used in conjunction with the Cult Horde or Tainted Flesh Provenances"

**Comment by capitaladot** [comment]
Implemented, will release tonight.
