### ISSUE TITLE
iPhone issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#422]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 1.10.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Hello, I'm using the Free version of Battlescribe, just updated To 1.10.15.
Immediatly after I've downloaded the Horus Heresy compilation of files.
Now, when adding "Legiones Astartes" and selecting "salamanders" ( or any other) it begins to load, then remains loading searching for something, unable To load, neither to exit. I've to close it after pressing "home button" in the iPhone.

**Comment by capitaladot** [comment]
Can anyone verify this on an iOS device?

**Comment by capitaladot** [comment]
@Jonskichov iOS bug.
