### ISSUE TITLE
No option available for World Eaters to be equipped with chain axes in either the free bolters to CCW upgrade, or the points based upgrade.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#423]
**File:** (HH) Legiones Astartes - Age of Darkness Army List.catz

**BattleScribe version:** 1.15.08

**Platform:** Android

**Dropbox:** No

**Description:** No option available for World Eaters to be equipped with chain axes in either the free bolters to CCW upgrade, or the points based upgrade.

**Comment by capitaladot** [comment]
Added.
