### ISSUE TITLE
Ordo Reductor list appears incomplete

### ISSUE THREAD

**Issue by cowomo404** [BSData/horus-heresy#424]
It appears the Ordo Reductor list in the HH:MTAL red book is incomplete in the battle scribe files.

The Ordo Reductor should have access to the full list of tagmata army list with a few additional units and some restrictions:

Additional [unique] units:

- **HQ - Magos Reductor** (this seems to be an add-on to the magos dominus, but this is not technically correct. The dominus has lower points cost and stats than the magos Reductor, with the arch magos being higher still. Dominus is 75pt, while the magos reductor starts at 125pts with the arch magos Reductor being +35... For example) HH:MTAL pg.82 
- **HS - Ordo Reductor artillery tank battery**  completely missing HH:MTAL pg.84
- **HS - Ordo Reductor Minotaur battery**  completely missing HH:MTAL pg.85

Restrictions: HH:MTAL pg.80

- Compulsory HQ choice must be a Magos Reductor,  Archmagos Reductor, or Calleb 
- Compulsory troop choices must be Thallax Cohorts
- The force may not contain more automata than half the total number of units in the detachment
-  The force is built off of the matrix of ruin army force organization chart  rather than the standard force org. HH:MTAL Pg.81 (update: I found the matrix of ruin force org)

 Otherwise all the other units are available,  including the Lord of war choices.

 Did I miss something with how this was implemented?

**Comment by capitaladot** [comment]
Select Reductor under Legion.
