### ISSUE TITLE
Deathstorm drop pod missing from heavy support units

### ISSUE THREAD

**Issue by cowomo404** [BSData/horus-heresy#425]
When taking the orbital assault rite of war the death storm drop pod do not show up in the heavy support unit list. 
The orbital assault RoW states that deathwind _may_ be taken as a fast attack option, but it shouldn't preclude it from being taken as a heavy support choice.

HH:LAAoDAL pg.98

I believe this should be handled in the same way reaver squads are handle when the black reading RoW is taken; they show up as both troops and fast attack options.

**Comment by capitaladot** [comment]
Fair enough!

**Comment by capitaladot** [comment]
Releasing.
