### ISSUE TITLE
Cant Choose Force Type

### ISSUE THREAD

**Issue by Tomakokamikaze** [BSData/horus-heresy#430]
Hi
Im kind of new here, so please forgive me if Im doing something wrong.
For the last month or so I cant open any of my old lists or create new ones. My devices are not so new so it might be that the app was updated and I csnt get the new version.
Either way I cant open it in my Iphone 4 or Motorolla XOOM
Please help me.

**Comment by capitaladot** [comment]
Delete all data (this does not delete rosters) and try again. Which platform are you on?

**Comment by Tomakokamikaze** [comment]
Motorolla MZ605 (not XOOM sorry)
Already did that, even deleted the app and still no good
Lists from other depositories are working fine though.
:-(

**Comment by capitaladot** [comment]
There is a known bug in iOS.
What happens on the Motorola? Exactly the same thing?

**Comment by Tomakokamikaze** [comment]
On the Iphone 4 it crashes every time I try to open a list or create a new one
On the Motorolla I select the game sistem and the force, but it doesnt enable me to choose a Roster and says I must choose a force and a Roster

**Comment by capitaladot** [comment]
Which app version do you have on each?

**Comment by Tomakokamikaze** [comment]
1.15.08 Motorolla
1.15.10 on Iphone 4

**Comment by capitaladot** [comment]
Those versions are current.

**Comment by Tomakokamikaze** [comment]
I have a test rigjt now
Should be back in an hour or two
Just in case you have more questions

**Comment by capitaladot** [comment]
I don't have any devices as old as either of those to test with (and no iOS devices, period), so you may need to learn a bit about git and go back through the releases to find one that works. If we can figure out what makes it not work for you (others have likewise reported issues with iOS regarding math and performance), I can rework whatever change is causing you trouble.

**Comment by Tomakokamikaze** [comment]
I still havent figured out how to download the .bsi file from gitub. Can anyone help me?

**Comment by capitaladot** [comment]
You can't, as it doesn't exist. You have to download the game system and
individual roster files.

**Comment by Tomakokamikaze** [comment]
I downloaded a version from when it worked and now it still doesnt work.
My uneducated guess is that he is not selecting the Parent Force, neither is the app alowing me to do it.

**Comment by capitaladot** [comment]
Hmm... sounds like your data is broken or something. You may need to go in with a file browser and delete files.

**Comment by capitaladot** [comment]
Doesn't enable you to choose a Roster? Roster is just a name your specify for your list.

**Comment by Tomakokamikaze** [comment]
Sorry
i meant Force Type not Roster
And I have already deleted everything and tried again, with no succes

**Comment by Tomakokamikaze** [comment]
![img_3112](https://cloud.githubusercontent.com/assets/21247755/18029146/73d8e46e-6c66-11e6-9970-65560cc08212.JPG)

my device doesnt print screen so here is a Photo

**Comment by capitaladot** [comment]
That is quite weird, indeed. Are you using Dropbox?

**Comment by Tomakokamikaze** [comment]
No
I either use the uploaded file or the omes I downloaded from github (previous versions). Either way none of them work. I dont know how but I believe its something to do with the latest app updates.

**Comment by Tomakokamikaze** [comment]
Ok, first of all, Im sorry I wasted your time, you guys do amazing work and Im just a noob.
I found out there was a delete all data function wich made both my Ios and android apps return to normal.
so, sorry I bothered you guys. and keep up the good work

**Comment by capitaladot** [comment]
No worries.
