### ISSUE TITLE
Corrupted data.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#432]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 1.15.08

**Platform:** Android

**Dropbox:** No

**Description:** Hello there dear support team.problem is that i cant create a new roster using horus heresy gstz. It says that i have to choose both, force and catalogue but i can choose only the catalogue, but the.forces drop down menu doesnt work and i cannot.create therefor a new.roster. maybe im using it.wrong but  dont think so.

**Comment by capitaladot** [comment]
"Delete All Data" and try again.

**Comment by capitaladot** [comment]
Was leaving this open because it seems to be happening repeatedly.

**Comment by Millicant** [comment]
Ah, gotcha.  Wonder why?

**Comment by capitaladot** [comment]
No good explanation... I haven't mis-released a borked file in quite a
while.

**Comment by Millicant** [comment]
No, I don't think that's the cause.  Good idea to keep an eye on it - might be hard to pin down though.

**Comment by Millicant** [comment]
Think we can close this now - I'm sure there's plenty of other new t hings to keep up with...
