### ISSUE TITLE
Legion Delegatus Consul forbids Lord of War

### ISSUE THREAD

**Issue by VanNostrand** [BSData/horus-heresy#435]
According to the 2016 Legiones Astartes Redbook page 23, the Delegatus has two restrictions: a Praetor or Lord of War may not be taken in a Primary Detachment. At least the LOW restriction is not checked as I was able to add a LOW to the Detachment lead by a Delegatus.

**Comment by capitaladot** [comment]
I would like to enforce this but BattleScribe 1.x lacks the ability to enforce restrictions related to slots and reactively put in place validation errors.
I think the best I can do is include the rules text under Delegatus for the user to self-enforce.

**Comment by Millicant** [comment]
Can be done now with 2.0.  I may have already done it, I can't recall.  Either way, it'll be done eventually.

**Comment by alphalas** [comment]
rolled into #844
