### ISSUE TITLE
Options without rules

### ISSUE THREAD

**Issue by VanNostrand** [BSData/horus-heresy#437]
Some options/weapons/upgrades have no description, mostly from 40k core rules
- [ ] Artificer Armour - A. confers a 2+ Armour save [LAAoDAL p131]
- [ ] Power Armour - P. provides a 3+ Armour save [LAAoDAL p133]
- [ ] Heavy Bolter - Range 36", S5 AP4, Heavy 3 [7th edition core rules p176]
- [ ] Heavy Flamer - Range Template, S5 AP4, Assault 1 [7th edition core rules p176]
- [ ] Melta Gun - Range 12", S8 AP1, Assault1, Melta [7th edition core rules p177]
- [ ] Plasma Gun - Range 24", S7 AP2, Rapid Fire, Gets Hot [7th edition core rules p177]
- [ ] Hunter Killer Missile - Range infinite S8 AP3 Type Heavy 1, One Use Only [7ed core rules p98]
- [ ] Extra Armour - Vehicles equipped with E. count Crew Stunned results from the Vehicle Damage table as Crew Shaken results instead. [7ed core rules p98]

also:
- [ ] Plasma Pistol
- [ ] Lightning Claw / Pair of Lightning Claws
- [ ] Power Fist
- [ ] Power Weapon
- [ ] Combi Weapon
- [ ] Thunder Hammer
- [ ] Chainfist
- [ ] Power Sword
- [ ] Multi Melta

**Comment by capitaladot** [comment]
Thanks for documenting these. There are tons of entries where the default entry (even when it is HH specific) does not have a profile (or any special rules) listed, so please continue to add to this list.

**Comment by capitaladot** [comment]
It would also be great to compile a list of where these things are missing, as many of these are not using "shared" entries, but instead have copy-paste style duplication of entries throughout the file.

**Comment by capitaladot** [comment]
@VanNostrand if you submit pull requests fixing these, I will merge them.

**Comment by Millicant** [comment]
Most of these have been implemented in 2.0 already, so that's a relief.  We might just wait for that release rather than trying to backfill all these, as it is a pretty massive undertaking.

**Comment by capitaladot** [comment]
Sounds good.
