### ISSUE TITLE
Emperor's Children Palantine Blades should have bolt pistols.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#438]
**File:** (HH) Legiones Astartes - Age of Darkness Army List.catz

**BattleScribe version:** 1.15.10

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Emperor's Children Palantine Blades should have bolt pistols.

**Comment by Millicant** [comment]
Will be added as each unit is re-written for standardized wargear.  ie we'll get to it but probably not soon.  :(
