### ISSUE TITLE
Ireton MaSade, the special character is still a Lord Marshal so should be able to take Household Retinue squads

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#439]
**File:** (HH) Solar Auxilia - Crusade Army List.catz

**BattleScribe version:** 1.15.08

**Platform:** Android

**Dropbox:** No

**Description:** Ireton MaSade, the special character is still a Lord Marshal so should be able to take Household Retinue squads. The current build forbids him from doing this. Thanks

**Comment by capitaladot** [comment]
Fixed.
