### ISSUE TITLE
Night lords terror assault requirements

### ISSUE THREAD

**Issue by Death1942** [BSData/horus-heresy#441]
Currently when selecting the terror assault right of war for night lords it isn't checking for the extra compulsory troop choice and letting you save lists with only 2 choices.   This needs to be 3 for normal force orgs and adjusted for other force orgs to be the required number + 1.

**Comment by capitaladot** [comment]
Sorry, can't be implemented in BS1.

**Comment by Death1942** [comment]
Really?   It had it before but maybe I am thinking of a different battlescribe 30k file.

**Comment by capitaladot** [comment]
The concept of compulsory Troop choices doesn't really work with how these files are made... basically, they would need to have separate FoC categories for Compulsory Troops and Support troops, and somehow combine the numbers to equal 2-6. BS1 can't do that.
