### ISSUE TITLE
Legion Praetor "...has 1 too many selections of Master of the Legion (maximum 0)..."

### ISSUE THREAD

**Issue by gungagreg** [BSData/horus-heresy#444]
iOS BattleScribe Pro - October 8th update of Horus Heresy file
Force Org:  Age of Darknes
When I select a Praetor for a 1000 or greater point list, I get the following error:  "...has 1 too many selections of Master of the Legion (Maximum 0)...". 

The data file apparently has a setting where you cannot have any master of the legion?  Selecting Loyalist or Traitor or any specific legion does not modify this.

Thanks!
Greg

**Comment by capitaladot** [comment]
Hi Greg! This is **also** a bug in the iOS version of the app that does not impact the other platforms. I would not expect to see it fixed until @Jonskichov brings 2.x to general availability.
