### ISSUE TITLE
Repost of #396 "Covenant of Fire creating invalid error" due to error reoccurance

### ISSUE THREAD

**Issue by gungagreg** [BSData/horus-heresy#445]
Reposting this from July 25 as the issue still remains:

When adding covenant of fire as a rite to a 30k Salamander list, I am getting a recurring error when the rite is chosen.

The error states "Legiones Astartes: Age of Darkness Army List (Age of Darkness) has 3 too many selections from May be upgraded to one of these Consul roles: (maximum-3)..."

I start with a valid AoD list...loyalist Salamander...Preator and two tactical squads. As soon as I assign the Praetor the Covenant ROW the error pops. Pops even if starting with just the Praetor. Reference to consul indicates some error linking the rite to consul positions.

Thanks!
Greg

**Comment by capitaladot** [comment]
Hi Greg! This is a bug in the iOS version of the app that does not impact the other platforms. I would not expect to see it fixed until @Jonskichov brings 2.x to general availability.

**Comment by gungagreg** [comment]
Got it, thanks!
