### ISSUE TITLE
Incompatible with BS2.01. Timeline?

### ISSUE THREAD

**Issue by Glaidr** [BSData/horus-heresy#448]
Soo... Battle Scribe 2.0 is out. Have updated on phone and windows 10 pc. 

Obviously people will be working to update for new client. Just wondering about time line?

Tried to open new roster for SM legiones Astartes and got these:

Message:
There were some problems with your data files. If you continue, this may lead to crashes or other strange behaviour.

> Legiones Astartes: Age of Darkness Army List:839b6f2a-4041-398b-fc2d-dc6a31d5f75e:net.battlescribe.model.data.Catalogue@1691f2e0: The catalogue data file is invalid:
> net.battlescribe.model.data.Condition@5bdd9933: Condition must have a child that exists in it's scope
> net.battlescribe.model.data.Condition@14fe3c3b: Condition must have a child that exists in it's scope
> net.battlescribe.model.data.Condition@58dc1dd9: Condition must have a scope that exists
> net.battlescribe.model.data.Repeat@1ab03e4e: Repeat must have a child that exists in it's scope
> net.battlescribe.model.data.Condition@2eebf130: Condition must have a scope that exists
> net.battlescribe.model.data.Condition@537d2df7: Condition must have a child that exists in it's scope
> net.battlescribe.model.data.Condition@635a4693: Condition must have a scope that exists
> net.battlescribe.model.data.Condition@1febd4fd: Condition must have a scope that exists
> net.battlescribe.model.data.Condition@10a47b3a: Condition must have a scope that exists
> net.battlescribe.model.data.Condition@3c99f40d: Condition must have a scope that exists
> net.battlescribe.model.data.Condition@d4653d3: Condition must have a scope that exists
> net.battlescribe.model.data.Condition@4c4b22ba: Condition must have a scope that exists
> net.battlescribe.model.data.Condition@7f05fda2: Condition must have a scope that exists
> net.battlescribe.model.data.Condition@c4f57d3: Condition must have a scope that exists
> net.battlescribe.model.data.Condition@581351c8: Condition must have a scope that exists
> net.battlescribe.model.data.Condition@3a14840e: Condition must have a scope that exists
> net.battlescribe.model.data.Condition@1070627d: Condition must have a scope that exists
> net.battlescribe.model.data.Condition@18d54f4b: Condition must have a scope that exists
> net.battlescribe.model.data.Condition@5a0ac088: Condition must have a scope that exists
> net.battlescribe.model.data.Condition@43b0e8ea: Condition must have a scope that exists
> net.battlescribe.model.data.Condition@54170c0c: Condition must have a scope that exists
> net.battlescribe.model.data.Condition@3349b8d2: Condition must have a scope that exists
> net.battlescribe.model.data.Condition@6b7fafe2: Condition must have a scope that exists
> net.battlescribe.model.data.Condition@2f4cfddf: Condition must have a scope that exists

Hope this helps working the bugs out!

**Comment by Millicant** [comment]
Old database is incompatible. New files have been created, but they have their own issues. 

I'll be releasing the 2.0 files into the mainstream Horus Heresy Repo this week.

**Comment by teun135** [comment]
Your work on these files is appreciated! Can't wait for the new ones, hopefully they aren't too much more difficult to work on in the new structure.

**Comment by Millicant** [comment]
Working on this today, should be attempting to release it.  Might be a mess...

**Comment by Millicant** [comment]
Released
