### ISSUE TITLE
Lords of War?

### ISSUE THREAD

**Issue by HorustheWarmaster** [BSData/horus-heresy#456]
Not sure if I'm missing something or not. For whatever reason, when I'm making a list there doesn't seem to be an option to add a Lord of War. Bug or user error?

**Comment by thebiggeordiegeek** [comment]
You need to add a Lord of War detachment under the Force Organisation category.

Not the clearest way of doing things but the guys are working to make it easier for us.

**Comment by zopha** [comment]
A bit old now but Lords of War are added in a separate detachment.

1. Add in a second force
2. Add the Force Org selection to that second force
3. Touch it for options
4. Touch the Force Org Chart selection (the text, not the radio button!)
5. Change to Lord of War
6. Go back to the main roster
7. Add in your Lord of War
