### ISSUE TITLE
Legion Specific Gear for HQ Bodyguards

### ISSUE THREAD

**Issue by Tomakokamikaze** [BSData/horus-heresy#457]
Good evening all, I play Alpha Legion wich lets me give banestrike ammo, venom spheres to my squads and power daggers to my characters, I was just wondering if the HQ bodyguards shouldnt be able to take some or all of these.

**Comment by capitaladot** [comment]
Sorry, they're Chosen Warriors, not Characters.

**Comment by Tomakokamikaze** [comment]
So no power daggers, but banestrike ammo I can?

**Comment by Tomakokamikaze** [comment]
I was wrong, sorry, its not everyone who can have banestrike boltshells and venom spheres.
