### ISSUE TITLE
Pull issues from HH2a repo

### ISSUE THREAD

**Issue by Millicant** [BSData/horus-heresy#458]
I need to go through and pull all the issues from the https://github.com/BSData/horus-heresy-bs2prep repo over here...

*Sigh*

**Comment by capitaladot** [comment]
https://github.com/IQAndreas/github-issues-import

**Comment by capitaladot** [comment]
Better yet: https://github-issue-mover.appspot.com/

**Comment by capitaladot** [comment]
@Millicant made attempt; please double check and close.

**Comment by Millicant** [comment]
Mostly - a few missed ones.  We can snag those separately later.

**Comment by zopha** [comment]
HH2a repo is not longer available (at least from what I can see) so this looks complete.
