### ISSUE TITLE
(Bug) HH making Battlescribe (mobile) crash

### ISSUE THREAD

**Issue by Hasfodel** [BSData/horus-heresy#461]
Every Time I try to open or create a HH roster, *bam*, crash ! (Of battlescribe)
For when I create it it crashes when I push the "add force" button
I'ts the same on iPad an iPhone (pro version)
Battlescribe and the data are up to date

**Comment by capitaladot** [comment]
1.x? 2.x? This (old) repo? New repo?

**Comment by Hasfodel** [comment]
Oups sorry,
I havre both apps, new repo on both, planting both, on both devices :((((

**Comment by Hasfodel** [comment]
2.00.03 and 1.15.10
