### ISSUE TITLE
One Bodyguard entry for Master of the Legion to rule them all.

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#464]
_From @capitaladot on July 30, 2016 20:24_

There are 3+ divergent copies in the 1.x branch. These should be paired down into one.

_Copied from original issue: BSData/horus-heresy-bs2prep#36_

**Comment by capitaladot** [comment]
Dupe

**Comment by Millicant** [comment]
Completely agreed.  The nice thing is - with the addition of some of the 2.0 tools (I'm looking at Ancestor) we should be able to make this even more easy to manipulate.
