### ISSUE TITLE
Lord of War Alpharius and choosing Coils of the Hydra for Rite of War in his detachment doesn't allow Rewards of Treason units to be used in the main detachment

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#466]
_From @BSDataAnon on July 24, 2016 1:7_

**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.00

**Platform:** Windows

**Dropbox:** No

**Description:** Adding Lord of War Alpharius and choosing Coils of the Hydra for Rite of War in his detachment doesn't allow Rewards of Treason units to be used in the main detachment. A validation error appears since the Rite of War doesn't cross detachments and a Rite of War cannot be chosen for the main detachment when there is no Master of Legion present to allow the RoT units. Choosing things in different order will always end with a validation error of either "Legion cannot have any selections of Rite of War" or "Elites cannot have any selections of Rewards of Treason".

_Copied from original issue: BSData/horus-heresy-bs2prep#34_

**Comment by capitaladot** [comment]
_From @Millicant on October 10, 2016 17:43_

This may be symptomatic of a larger problem.  By separating out the Lords of War into a separate Detachment, I may have inadvertently made Rites of War inaccessible by Primarchs.  Ugh, that's definitely a problem.  I'll see about a workaround, I really don't want to undo all that.

**Comment by zopha** [comment]
The issue with rites should be fixed in pull request #674 by changing the rites of war condition to Roster instead of Force. Not a great solution as it will appear if anyone takes an allied detachment that has an Astarte Master of the Legion but it will work well enough for now.

**Comment by alphalas** [comment]
rolled into #863
