### ISSUE TITLE
ROW: Day of Revelation

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#472]
_From @Millicant on July 23, 2016 5:11_

Compulsory HQ and Troops must have Jump Packs... (YIKES)
Compulsory Fast Attack must have Flyer or Deep Strike rule
No Lords of War other than Flyers or Primarch Sanguinius

_Copied from original issue: BSData/horus-heresy-bs2prep#28_

**Comment by alphalas** [comment]
rolled into #863
