### ISSUE TITLE
ROW: The Awakening Fire

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#475]
_From @Millicant on July 23, 2016 4:24_

Only one each:
- Jump Infantry
- Jet Bikes
- Skimmers
- Flyers

_Copied from original issue: BSData/horus-heresy-bs2prep#25_

**Comment by zopha** [comment]
Also currently available for any legion to take. Will get to it when the CAL file is freed up.

**Comment by zopha** [comment]
Hidden from other legions now.

**Comment by alphalas** [comment]
rolled into #863

**Comment by capitaladot** [comment]
Were the restrictions implemented or only the Legion filter?
