### ISSUE TITLE
Fury of the Ancients - Dreadnought talon multi-error

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#483]
_From @Millicant on July 16, 2016 23:41_

_Copied from original issue: BSData/horus-heresy-bs2prep#15_

**Comment by zopha** [comment]
The errors. Might be solved by using the Shared checkbox on a contraint but needs testing to figure it out.

![2017-02-16 07_10_16-roster editor v2 00 11 - new roster warhammer 30 000 - the horus heresy v57](https://cloud.githubusercontent.com/assets/1666415/23011124/02be98e4-f417-11e6-8bf6-915d8b9714d7.png)

**Comment by zopha** [comment]
Fixed in commit 9c0385a5b7b51a51029f0e6a710237e74fd8643b and will be in a future release.
