### ISSUE TITLE
Head of the Gorgon - 1 consul / Forge Lord

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#489]
_From @Millicant on July 16, 2016 23:39_

_Copied from original issue: BSData/horus-heresy-bs2prep#9_

**Comment by capitaladot** [comment]
Implemented this in the 1.0 project; set total allowed as 3 and decremented by 2, then incremented by 1 when one of the allowed Consul types.

**Comment by alphalas** [comment]
rolled into #863
