### ISSUE TITLE
Stone Gauntlet - 1 Consul / Legion Champion

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#490]
_From @Millicant on July 16, 2016 23:38_

Only one allowed unless Legion Champion.  Not implemented. 

_Copied from original issue: BSData/horus-heresy-bs2prep#8_

**Comment by capitaladot** [comment]
Implemented this in the 1.0 project; set total allowed as 3 and decremented by 2, then incremented by 1 when one of the allowed Consul types.

**Comment by capitaladot** [comment]
_From @Millicant on July 20, 2016 17:56_

Nice idea.  I've been struggling with that for 2.0a.  I will try the same
thing and see if it works there.

**Comment by alphalas** [comment]
rolled into #863
