### ISSUE TITLE
Steal Codex: Chaos Daemons from the 40k repo

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#493]
_From @Millicant on July 16, 2016 3:38_

I kid, I kid.

But seriously, no need to reinvent the wheel here.  Once that codex is 2.0 compliant, we'll just have to snag a copy and transfer all the nonsense over.  It's going to be a royal pain in the butt.  

_Copied from original issue: BSData/horus-heresy-bs2prep#4_

**Comment by capitaladot** [comment]
- [ ] Backport Samus
- [ ] Backport Cor'bax Utterblight

**Comment by capitaladot** [comment]
The above are done in 1.x and can be imported then copy pasted.

**Comment by capitaladot** [comment]
_From @Millicant on July 31, 2016 3:43_

Understood.  I'm going to wait a bit until I iron out all the Force Organization stuff, that way it prevents double work.  Thanks for doing it for 1.15!

**Comment by cowomo404** [comment]
Looking for this allied list for the word bearers right of war.
Seemed the 40k  daemons list is working in 2.0, ready for copying over?

**Comment by zopha** [comment]
Yeap, the Daemons file is ready to be copied over, it won't be a straight copy though. Once the file is added in everything that links to the 40k GST needs to updated so it uses the 30k GST instead. The 30k one doesn't have all the rules from the BRB so they'll have to be added in.
It'll also have to be updated to use the 30k force org. I'm not sure if it has formations in it either! They'll have to be disabled if they're 40k only.

**Comment by zopha** [comment]
@cowomo404 can you give the files from https://github.com/BSData/horus-heresy/tree/Daemons a go and see how they are for Daemons? It's an old file and needs to be updated with current daemon codex content but it's working with the new 30k files.

**Comment by cowomo404** [comment]
So I think I was able to add allied units without significant issue. I will have to do some validation on if the selections are accurate but it seemed so at a quick glance.

I did have an issue with too many selections of Master of the Legion (maximum 0) similar to a previous issues #429 , but I don't think it's related to adding the Chaos codex data file or selecting allies.  quick snap of my results on desktop

![screen shot 2017-03-06 at 20 52 31](https://cloud.githubusercontent.com/assets/13860904/23639730/e3e05f92-02ae-11e7-8d57-086443413a23.jpg)

**Comment by capitaladot** [comment]
Nice!

**Comment by alphalas** [comment]
The MoL error happens when you're below 1kpts

**Comment by cowomo404** [comment]
@alphalas ah yes, good catch - duh - 

![screen shot 2017-03-06 at 20 57 56](https://cloud.githubusercontent.com/assets/13860904/23639871/974197ae-02af-11e7-85ee-a10eb6cc2174.jpg)

**Comment by zopha** [comment]
@cowomo404 an updated daemons file is in the master set now. Should be all the daemon stuff. @alphalas has taken the 40k for and made it Heresy friendly.
