### ISSUE TITLE
Age of Darkness FoC missing 4th Elite Slot, Lord of War slot.

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#494]
_From @capitaladot on July 10, 2016 18:14_

I don't want to make things crazy by implementing structural changes, so I thought I'd file this here.

_Copied from original issue: BSData/horus-heresy-bs2prep#3_

**Comment by capitaladot** [comment]
_From @Millicant on July 16, 2016 6:20_

Okay, thanks!

Lords of War aren't in the regular AoD Force Org - they are in an extra Lords of War force org.  The elites I will fix though.

**Comment by zopha** [comment]
Looks like this has been fixed. If I try to add 5 elites Battlescribe returns a validation error stating I cannot have more than 4 in a Legion Astarte list.
