### ISSUE TITLE
Laundry list of problems.

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#498]
![image](https://cloud.githubusercontent.com/assets/1619329/20075314/bb81021e-a501-11e6-9a09-b82e3b5a8e01.png)

**Comment by capitaladot** [comment]
This was forwarded to me through my local games club from one of the UK pod casts. I'm guessing 2.0 in any respect isn't ready for prime time? I haven't tested in quite a while, so honestly, I'm ignorant of the current status.

**Comment by Millicant** [comment]
Yikes, its a bit melodramatic.  

That being said, yes the Primarch thing is a legitimate issue - only for Primarchs though.  Rites of War are totally available, just in a new location.   The rest are out of our control, 2.0 is in a bit of a state.  Not much we can do about it.
