### ISSUE TITLE
Separate database for Battlescribe 1 and 2

### ISSUE THREAD

**Issue by Tomakokamikaze** [BSData/horus-heresy#499]
My devices are too old to run battlescribe 2.0 (except for PC).
I was wondering if they will have different databases or if I will just have to download an older version of it and never update it. Or if the two will be compatible. Either way my BS1 is unnusable right now.

**Comment by capitaladot** [comment]
@Millicant overwrote the old files yesterday. If you have them already somewhere, I would suggest holding on to them until some of the show-stoppers are worked out.

**Comment by Millicant** [comment]
Well, I might post the old files in a dropbox folder or something so people can access them.   That being said, they are no longer supported.

**Comment by amis92** [comment]
@Tomakokamikaze 

I've took the liberty and created the `.bsr` for 1.15 and also added notice for future users in README, look here: https://github.com/BSData/horus-heresy/blob/master/README.md#important

**Comment by f1r3warr10r** [comment]
Someone please add the older files for astra militarum until we mobile (kindle) users can upgrade to the new version. Oh, and please tell us where we can find it. Please????

**Comment by f1r3warr10r** [comment]
Does anyone with a kindle fire know where we can get either free or pro? It's really not cool that we can't get it and are having such problems using the old version!

**Comment by amis92** [comment]
@f1r3warr10r if there were any AM files for Horus Heresy, please check out the link I've provided in my comment directly above yours. Other than that, we can't help you.
