### ISSUE TITLE
[Unit missing]  Legion Jetbikes Sky-Slayer Squadron

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#500]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.06

**Platform:** Android

**Dropbox:** No

**Description:** In the legion army list v200, the Legion Jetbikes Sky-Slayer Squadron has dissapeared from the heavy support

**Comment by Millicant** [comment]
Yup, needs to get added!

**Comment by zopha** [comment]
Added in latest release. May need some more work but the unit is available now.
