### ISSUE TITLE
Apothecaries missing option for jump pack

### ISSUE THREAD

**Issue by HorustheWarmaster** [BSData/horus-heresy#503]
First- great work on this guys. This morning's latest version crunched a lot of bugs. 

As the title states, apothecaries are missing the option for jump packs.

**Comment by DonMorr** [comment]
Can you please double check this? Testing with the latest version, I can see that jump packs are there as an option.

**Comment by zopha** [comment]
I had a look this morning and the option for a jump pack is there now.
