### ISSUE TITLE
Lords of war and rows in age of darkness missing

### ISSUE THREAD

**Issue by MrRta1910** [BSData/horus-heresy#522]
Lordsof War and Rites of War are missing in the Legionnes Astartes list building.

**Comment by MrRta1910** [comment]
I'm using android

**Comment by Jesse1220** [comment]
Lord of War are currently unavailable. Rites of War are now under Legion
selection, when a model with the Master of the Legion is selected for the
army.

**Comment by Millicant** [comment]
Lords of War ARE available.  Need to use a new Detachment.
