### ISSUE TITLE
Dealing with the "Or" condition

### ISSUE THREAD

**Issue by Millicant** [BSData/horus-heresy#527]
@capitaladot and @amis92 and @cartag I'm hoping for your inputs here, as the local experts and experienced users.  

Quite a few Rites of War state that compulsory troops (or some other condition) may be met by unit X OR unit Y.  e.g. Primarch's Chosen compulsory troops must be either Veteran Tactical Squads OR Legion Terminators.

Up until now, I've been trying to use a shared entry as a "marker" and then require the marker entry a certain number of times.  This is ugly, however, since between Terminators and Tactical squads it gets hard to find a name that both identifies the requirement and doesn't sound stupid when it isn't applicable.  Furthermore, as there are many competing Rites of War, units like Terminators and Vet Tactical squads will end up with multiple dummy "marker" entries which adds clutter and confusion. 

(Another example - All the various types of Dreadnoughts have a shared entry entitled "Dreadnought Talon" in order to capture the Fury of the Ancients Rite of War.)

So, my new idea is this: When a Rite of War has a compulsory requirement with multiple options, it becomes it's own new entry with links to the options.  For example, Primarch's Chosen Rite of War would make visible a new "Compulsory Troops" entry (title TBD) which would have links to the Veteran Tactial Squad and Legion Terminators.  On top of that - the regular entries would likely have to be hidden as well.  

It's not as pretty as I would like, but I nicely solves the issue.  I'm looking for ideas on how else to solve this riddle, since it comes up quite a few times.  Pretty please? Any thoughts or suggestions?

Thanks guys!

**Comment by cartag** [comment]
If you set a separate group (Troops/Elites/Heavy Support/etc) for Compulsory Troops (CT) that has hidden links to entries (Check 40k CSM file for links to shared entries for both Elite and Troop choices for Khorne Berzerkers for example).

You can set one as Troop, one as CT, and have the CT hidden, with an unhide modifier if Rites XYZ are present. Set the T one up as visible always. This is gonna be way easier for me to just show... 

Under Force Entries
![image](https://cloud.githubusercontent.com/assets/4388344/20334735/d25f4684-ab79-11e6-8643-ccb5a36ae86c.png)

**Comment by cartag** [comment]
![image](https://cloud.githubusercontent.com/assets/4388344/20334771/231f01fe-ab7a-11e6-8a18-ed664cc723b3.png)

![image](https://cloud.githubusercontent.com/assets/4388344/20334781/3733d0fc-ab7a-11e6-803f-2afdf297facb.png)
