### ISSUE TITLE
Lords of War addition

### ISSUE THREAD

**Issue by Millicant** [BSData/horus-heresy#528]
So, this will be ugly, due to a long-ago fork in the Vehicle Profile.

**Like the Alternate Force Orgs and Relics, these should all be marked "(Optional)".**

Here's the relevant text:
Using additional Super-heavy & Orbital Strike Wing Flyer Units
The vast milieu of battle during the Horus Heresy and the armies of the Great Crusade were staggeringly diverse, with only the most common or singular currently dealt with by Forge World’s Horus Heresy supplements. In order to represent this diversity when it comes to Super-heavy vehicles and Flyers, this section presents a list of additional models which may be used. In many cases, the Imperium of the Great Crusade sees the origin of some of these designs, while in others they can simply be used to stand in for one of the many less-widespread war machine types and unique patterns employed by a vast Imperial armed force, far less regimented and standardised than its 41st Millennium counterpart. Where general options are listed but not found on the vehicle’s profile or within this book, or refer explicitly to the 41st Millennium (i.e., Commissar tanks), ignore those options:
- [x] Baneblade, 
- [x] Banehammer, 
- [x] Stormlord, 
- [x] Shadowsword, 
- [x] Stormsword
- [x] Macharius and variants (representing indigenous war machines)
- [x] Macharius Vulcan
- [x] Macharious Vanquiser
- [x] Crassus and variants (representing indigenous war machines)
- [x] PRAETOR ARMOURED ASSAULT LAUNCHER
- [x] Marauder Bomber, 
- [x] Marauder Destroyer, 
- [x] Thunderbolt Heavy Fighter, 
- [ ] Crusade Avenger Strike Fighter (see Mechanicum Taghmata army list)
- [x] Minotaur (see Taghmata Omnissiah army list)

_When used in conjunction with this army list, these vehicles may be further modified by the following upgrades:_

**Space Marine Crew (Super-heavy Tanks only):+15 points**
- [x] Baneblade, 
- [x] Banehammer, 
- [x] Stormlord, 
- [x] Shadowsword, 
- [x] Stormsword
- [x] Macharius
  and variants (representing indigenous war machines)
- [x] Macharius Vulcan
- [x] Macharious Vanquiser
- [x] Crassus 
  and variants (representing indigenous war machines)
- [x] PRAETOR ARMOURED ASSAULT LAUNCHER

**Battle Servitor Control (Flyers only):+15 points. If taken as an option for a Sub-orbital Strike Wing, then all the Flyers in the wing must be so upgraded**
- [x] Marauder Bomber, 
- [x] Marauder Destroyer, 
- [x] Thunderbolt Heavy Fighter, 
- [x] Crusade Avenger Strike Fighter

**Comment by capitaladot** [comment]
Is it practical to reimport the 1.x file and copy pasta these?

**Comment by alphalas** [comment]
If all these lords of war in the 1.x version, sure. Copy paste them to CAL, just hold off on that until I'm done AoDC please

**Comment by zopha** [comment]
What the best source book for them? We'd just need to make sure they still have the right loadouts and costs.

**Comment by capitaladot** [comment]
They were in all kinds of different source books. It was a big project, and the lack of effort to pull them in before the 2.x release was pretty infuriating. Anyway, they're back, though perhaps not quite as cleanly.
