### ISSUE TITLE
Steal Fortifications codex from 40k repo

### ISSUE THREAD

**Issue by Millicant** [BSData/horus-heresy#529]
Same as C:CD

**Comment by smokescreentk421** [comment]
I know very little about coding and haven't really messed about with the data files in BattleScribe. But I see that Fortifications is missing a lot of information. The information is mostly in the Stronghold Assault book but I am guessing this should be replaced with the new Planetary Onslaught book that is being released tomorrow.

I can get the book and input the data but don't want to step on any toes - and I also want to make sure I'm doing it correctly. What's the procedure for this...?

**Comment by zopha** [comment]
Most of the fortifications are in place in the GST now, Selection Entries need to be set up for them to appear for users but we'll need to check restrictions and optimise them before making them available.
