### ISSUE TITLE
Improve legion veteran additional wargear section

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#532]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.10

**Platform:** Android

**Dropbox:** No

**Description:** The power weapon part in the legion veteran additional wargear section is a bit unpractical to use. While is nice to state which power weapon is given individually, it would save a lot of space if it was a menu like the one for the bolter replacement, with a list of power weapons variants and the quantity for each.

**Comment by thebiggeordiegeek** [comment]
I would also raise this an issue with Ultramarine Breachers who can take Power Swords, it makes the output look a little messy.

But that said considering the other issues at the moment, it's one that can happily wait a good while.

**Comment by Millicant** [comment]
Interesting.  Yeah, I'll have to consider that.  The main reason for the this change was to drive the ability to swap in the various legion-specific swaps/upgrades, but perhaps that's not a great solution.  I'll re-evaluate.

**Comment by capitaladot** [comment]
Collective checkbook?

**Comment by alphalas** [comment]
Would possibly work, but if a user wants to mix and match power weapon types, that won't work
