### ISSUE TITLE
Completely broken

### ISSUE THREAD

**Issue by bryankia** [BSData/horus-heresy#533]
I am on iOS most recent version
I am on 2.00.07 of battle scribe
Version 41 of the file 

I don't know how to reach the data file creator who I am so greatfull to but what I have is a pile of poo.  

Below are a couple images that show my frustration.  Which army of darkness file should I select... hint they are all broken.  The other image shows the list of errors I get before I have added anything to my army.

I have deleated all the data and removed all the repositorys and addeded them many times.

I have no idea how to create or edit the data file.  I would love to help in some way.  Please advise.

![img_0050](https://cloud.githubusercontent.com/assets/23393151/20411996/bdfc602a-ace9-11e6-96b0-1562483dd689.PNG)
![img_0051](https://cloud.githubusercontent.com/assets/23393151/20411997/be314c72-ace9-11e6-94a5-ce200e0ad0ec.PNG)

**Comment by thebiggeordiegeek** [comment]
Many of the issues you are describing have noting to do with the database here, you should raise these with the developer of BattleScribe and close this issue.

**Comment by bryankia** [comment]
I went back and edited the post.  The paragraph of frustration has been removed but the rest should directly relate to the data file.  

I would appreciate any help anyone can give.  Are the things I am seeing limited to me?

**Comment by capitaladot** [comment]
On Thu, Nov 17, 2016 at 7:04 PM, bryankia <notifications@github.com> wrote:

> I went back and edited the post. The paragraph of frustration has been
> removed but the rest should directly relate to the data file.
>
> I would appreciate any help anyone can give. Are the things I am seeing
> limited to me?
>

@thebiggeordiegeek are there Uservoice issues open about these? 2.x seems
like one big regression, spare the subscription/monetization "features".

**Comment by bryankia** [comment]
This error is happening on my iPad but not my phone. I will try again to delete the data files and clear this up. I will close it
