### ISSUE TITLE
Standard Terminator Armour missing from vaious selections

### ISSUE THREAD

**Issue by DonMorr** [BSData/horus-heresy#540]
Standard Terminator Armour is missing from the following selections:
- Legion Praetor
- Legion Terminator Command Squad
- Legion Centurion
- Legion Terminator Squad

**Comment by Millicant** [comment]
@DonMorr when you say "standard" terminator armour, what are you referring to?  As in not Tartaros or Cataphractii?  That's not technically an option right now.

**Comment by capitaladot** [comment]
That is incorrect. Indomitus ("standard") is still an option.

**Comment by zopha** [comment]
It's in the most recent red book as an option for those units.

Listed as Terminator armour/Tartaros Terminator/Cataphractii Terminator armour 

Pretty sure it was outlined in the FAQ from Jan when they separated out Tartaros and give it sweeping advance.

**Comment by Millicant** [comment]
I'm familiar with the entry, I just never read it as 3 unique options.  However, I will concede that some people may be using 40k/Indomitus Terminator armour and want that option.  

If it is going to be implemented - it NEEDS to be a root entry.  No adding it to the unit entry itself.  That's the direction the other Terminator armours will be going as well, no need to re-do work for it.

**Comment by capitaladot** [comment]
Solidly agreed on a root entry, not per unit.

**Comment by DonMorr** [comment]
In the pull request, I added a "Terminator Armour" shared profile (Wargear Item) in the same section as Tartaros & Cataphractii Terminator Armour. I then added this new profile to the Legion Terminator Squad (same as the Tartaros & Cataphractii).

Sounds like you want to move away from this approach. Can you describe the new approach you want, the one using the "root entry"?
