### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by DonMorr** [BSData/horus-heresy#548]
Hi There,
I would like to join the repo so I can help improve the horus heresy data files. I already have one pull request waiting.
Cheers,
Donal

Mentioning @amis92  as I had originally put in the join request in the wrong location: https://github.com/BSData/bsdata/issues/125#issuecomment-261795184

**Comment by amis92** [comment]
@Millicant @capitaladot you guys are actual bosses here, so go on and decide - should I invite @DonMorr? A quick look at the profile tells me he's a programmer and knows git so that'd be beneficial I guess :)

**Comment by capitaladot** [comment]
+1

**Comment by amis92** [comment]
I'm gonna wait for @Millicant, he's been quiet recently, and also promised to give a sign when to close HHbs2prep repo. He might be working on something possibly, and never liked conflicts when uploading.

**Comment by Millicant** [comment]
Hey @DonMorr sounds good - welcome to the Horus Heresy repo!  Please heed #459 as you start making improvements.  As @amis92 mentioned I get antsy about conflicts.  Please be very careful when making changes - this repo is in a delicate balance now with the new improvements for 2.0.

**Comment by amis92** [comment]
Invited, closing.

**Comment by DonMorr** [comment]
Thanks for letting me join the team! Would you prefer me to create pull requests for my initial few changes, that way you can do quick reviews before I push to master? Otherwise I could commit the small changes to master myself (weapon stats, etc), and any changes I am unsure of, create a pull request for review.
I've read #459, is there a general guide on the structure of the BS data files?
