### ISSUE TITLE
Mechanicum issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#553]
The thagmatta army list has no way of selecting the matrix of ruin force organization for the ordo reductor

Also there is no support for the Legio Cybernetica 
* [x] (compulsory units, 
* [x] initiative buff, 
* [x] cortex buff, 
* [x] victory conditions) 
yet.

![screen](https://cloud.githubusercontent.com/assets/20644972/24399134/6f740c00-13b4-11e7-8462-fc9c77a6b30d.jpg)

**Comment by thebiggeordiegeek** [comment]
Done extensive playing around and you are correct I can't figure it out

**Comment by capitaladot** [comment]
Needs reimplemented.

**Comment by Millicant** [comment]
Indeed.  I have not written this in yet after the 2.0 update.

**Comment by zopha** [comment]
Have the force org for this setup in the Taghmata branch. More work to be done to add restrictions and rules in to it.

**Comment by zopha** [comment]
The newest version of battlescribe has added features that will allow us to implement the restrictions for this.

Some groundwork needs to be done on the current file but this will be implemented.
