### ISSUE TITLE
Librarian mastery level

### ISSUE THREAD

**Issue by bryankia** [BSData/horus-heresy#557]
How do I add a mastery level to my librarian.  

All is not dust yet!

**Comment by zopha** [comment]
The option is missing for the moment. Should be covered in issue #518 I'll get to it once I do the rest of the standard force org slots from the Army list book and if I managed to do a decent job on them (and the others let me tackle something more complicated) :shipit:

**Comment by zopha** [comment]
Fixed in latest release.
