### ISSUE TITLE
 Astarte Fast Attack changes

### ISSUE THREAD

**Issue by zopha** [BSData/horus-heresy#562]
I talked to capitoldot on gitter and I'm posting this so it can be made into a punch down list for updates. I'm not very familiar with BS datafile creation or github so doing what I can to help. I have about an hour a day on my commute, if you want someone to concentrate on an area or do some QA on a list let me know! I'll do what I can to help.

----

**Points update/change**

LEGION LAND SPEEDER SQUADRON - LA:AODAL P.56
- [x] - Hunter killer missile - Change to 5 points

LEGION STORM EAGLE ASSAULT GUNSHIP - LA:AODAL P.57
- [x]  Extra Armour - Change to 5 points

----
**Rules/Equipment updates**

LEGION SEEKER SQUAD

- [x] Strike leader missing lighting claw option LA:AODAL P.48
- [x] Precision Shot missing from Special Rules LA:AODAL P.48
- [x] Scorpius bolt shells LA:AODAL P.128
  - [x] Change AP to 2 
  - [x] Remove Rending 
  - [x] Change Strength to 5
----

PRIMARIS-LIGHTNING STRIKE FIGHTER - Unit correct - LA:AODAL P.52

- [x]          - Electromagnetic storm charge - Change from Heavy 1 to Bomb 1. LA:AODAL P. 53
- [x]           - Phosphex bomb cluster - Change from Heavy 2 to Bomb 2. Remove Bomb Cluster. LA:AODAL P. 53
----

LEGION TARANTULA SENTRY GUN BATTERY - LA:AODAL P.54   
- [x]  - Forward Deployment - No cost in the book, no option to add it.
- [x]           - Add special rules - Automated Artillery, Deployment (Gives Foward Deployment for free (Scout), Targeting (LA:AODAL P. 54) **Double check this please!**
----

XIPHON PATTERN INTERCEPTOR- LA:AODALP.58

- [x]           - Unit entry has Special Rules duplicated from the weapon entry (Cluster Warhead, Terminal Tracking)
----

LEGION JAVELIN ATTACK SPEEDER SQUADRON - LA:AODAL P.59

- [x]           - Add Strafing Run special rule
- [x]           - Add Grav-backwash special rule
----

**Update reference pages only**

LEGION OUTRIDER SQUAD
- [x]           - All correct - LA:AODAL P. 49

LEGION ATTACK BIKE SQUADRON
- [x]           - All correct - LA:AODAL P. 50

LEGION JETBIKE SKY HUNTER SQUADRON
- [x]           - All correct - LA:AODAL P. 51

ANVILLUS PATTERN DREADCLAW DROP POD
- [x]           - All correct LA:AODAL P.55
----

[edit]Scorpius update. Updated formating[/edit]

**Comment by DonMorr** [comment]
@zopha I'm happy to start working through this list. Will create a branch and start work, unless there are any objections?

**Comment by capitaladot** [comment]
+1
Worth looking at the pre-2.x version and copypasting; should save you time.

**Comment by zopha** [comment]
+1 @DonMorr Go for it.

I think the Hunter Killer and Extra Armour stuff should be a root/shared/linked option so all the entries work off the same entry, if they ever change the points value again it'll be easier and new vehicles should be a matter of some stat/rule data entry and just linking to the existing profiles/objects. I fiddled around with pintle mount stuff and it looks like it can be done with weapon groups as well. That will be handy if the Wolves/1ksons have any unique options or new vehicles.

Should have already been done in the 1.x files, we just need to do some data-archology on it :D

**Comment by Millicant** [comment]
@DonMorr please go ahead and work on this.  Ultimately this is going to entail a lot of foundation work to set the stage for further root-level entries.  Please ensure you're following the structure set forth and making improvements as you go!  This will help me out in the long run.  

ALSO - everybody see #561 as this is DEFINITELY going to affect LA:AODAL.  This is arguably one of the most complex catalogues and any performance improvements are going to pay big dividends. 

As always, branch and merge to avoid conflicts.
