### ISSUE TITLE
Legion Malcador is not showing up as an entry for Heavy Support. Note it is not a Lord of War.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#565]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.00.05

**Platform:** Windows

**Dropbox:** Yes

**Description:** Legion Malcador is not showing up as an entry for Heavy Support.  Note it is not a Lord of War.

**Comment by zopha** [comment]
I have this in the #568 to do list. I'll get it added once the other updates are working and merged. Options and standard wargear for this unit will depend on those changes so it's going to be done last.
