### ISSUE TITLE
Artillery Tank Squadron selections do not show secondary weapons in the report views.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#573]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.08

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Artillery Tank Squadron selections do not show secondary weapons in the report views. These should show "heavy bolters" for a Medusa tank, for example.

**Comment by zopha** [comment]
Should be covered in the #568 issue/check list.
