### ISSUE TITLE
Deathstorm drop pod missing from heavy support with orbital assault RoW

### ISSUE THREAD

**Issue by cowomo404** [BSData/horus-heresy#575]
This issue has resurfaced with the release of Battle scribe 2.0+

When taking the orbital assault rite of war the Deathstorm drop pod does not show up in the heavy support unit list.
The orbital assault RoW states; "Deathstorm Drop Pods _may_ be selected as Fast Attack choices” This means it should not be precluded it from being taken as a heavy support choice.

HH:LAAoDAL pg.98

I believe this should be handled in the same way reaver squads are handle when the black reaving RoW is taken; they show up as both troops and fast attack options.

EDIT - upon further inspection it appears that the above behavior is erroneously applied to the Pride of the Legion RoW. using Pride of the Legion Deathstorm Drop Pods show up in the fast attack AND Heavy Support slots. Using this RoW Deathstorm Drop Pods should ONLY show up as a Heavy Support.

The behavior for Deathstorm currently implemented in Pride of the legion should be swapped for the behavior in Orbital Assault.

**Comment by zopha** [comment]
Should be able to sort this when I get to the rites of war section of the army list or if someone else fixes it before that happens.

**Comment by cowomo404** [comment]
@zopha do you mean the content from the red book?
I have the content and I'm happy to help but would need guidance for format, etc...

**Comment by zopha** [comment]
@cowomo404 Yeap, the red book. I'm new here so can't really advise on format, content, etc for the data files. I have some stuff that needs to be looked at before it gets merged, if I can get a few updates done I'll hopefully get the hang of it.

Doing some QA might be handy though, picking a RoW, unit or Force Org slot, running through it on BS and making a task list on what's missing or needs to be corrected and posting it as an issue. I've gone through Heavy support, fast attack and dedicated transports so far and there's plenty more to do.

**Comment by zopha** [comment]
Looks like the heavy support entry was incorrectly set to Orbital Assualt. This should be fixed in the next release. I think it should have been set to Stone Gauntlet as that Rite excludes all deep strike units so this has been fixed for both rites. I had a look at Pride of the Legion and I can't see the the Deathstorm available in Fast Attack.

I'll make a note to check again after the release goes out.

**Comment by cowomo404** [comment]
@zopha sounds like it's fix - it should not show up for pride of the legion RoW - I will test and confirm.

**Comment by cowomo404** [comment]
so @zopha this issue seems to persist for me, do I need to manually create a data file to load - rather than the update posted on the web?

**Comment by zopha** [comment]
Argh, my last comment didn't post :/

Thee one posted on the web is the most current one, there shouldn't be any difference between it and what you have and what I have on my phone.

Are you using desktop or mobile? And, sorry have to ask, have you deleted your catalogue files and made battlescribe download them again?

When creating a roster you should have "Horus Heresy v44" and then "Age of Darkness Army List v205" If they're not set to those versions then you may need to manually delete the files and get BS to download them again.

 
If you've done that then the next thing to try checking the data file yourself. If you open the legion file with the data editor on desktop. Expand the second last set of entries "selection entries" and scroll down until you see a chain link icon for the entries. Scroll down to the D's and you'll see thre entries for the deathstorm. If you select the last one you should see what force slot the entry the entry belongs to, so you can see which is the fast attack entry

![2017-01-09 19_20_18-data editor 2 00 09 - legiones astartes_ age of darkness army list](https://cloud.githubusercontent.com/assets/1666415/21780654/561b3a5a-d6a4-11e6-87c4-68c7fca33cfa.png)

Expand the entry and the one under it and you;ll see the restriction that keeps it hidden, it should be set to Orbital Assault. Select it and you'll see the following on the right.

![2017-01-09 19_30_11-data editor 2 00 09 - legiones astartes_ age of darkness army list](https://cloud.githubusercontent.com/assets/1666415/21780655/561dc4be-d6a4-11e6-9f67-43ed3eccaf47.png)

Just make sure the Enter ID is the same as the one I have. If you only have two deathstorm entries (the on that hides it when stone gauntlet is selected) then BS hasn't updated the file properly. Try manually deletion and download again.

**Comment by cowomo404** [comment]
I used both desktop and mobile depending on where I am. When I get a sec I'll do another check and take screen shots if it's the same as I saw yesterday.

**Comment by zopha** [comment]
@cowomo404 any luck?

I've put out another release today but didn't make any changes to the Deathstorm or Obital RoW. If it's still not working perhaps try a clear out again? Full instructions are available here: https://battlescribe.net/?faq=refreshData

**Comment by cowomo404** [comment]
This works correctly in the current version - Death storm available as Fast attack and Heavy Support 
![screen shot 2017-01-24 at 18 31 57](https://cloud.githubusercontent.com/assets/13860904/22272995/6a75c112-e263-11e6-9a02-3affa2b3bbac.jpg)
