### ISSUE TITLE
Erroneous Lord of War error message (???)

### ISSUE THREAD

**Issue by cowomo404** [BSData/horus-heresy#576]
not sure if this is a data file issue or app issue (please advise)

When building a 5000pt force I receive an alert that I have spent too much on Lord of War choices - saying 3750 (maximum of 1250) the math is correct based on the size force being built - but the list only has 2960 pts selected so far.. not sure how it's calculating the pts spent.

Screen shot attached (ignore message #2 - submitted as separate issue
![screen shot 2016-12-02 at 01 48 06](https://cloud.githubusercontent.com/assets/13860904/20826561/674fe30c-b831-11e6-8e49-620eeb25ae1b.jpg)

**Comment by zopha** [comment]
I haven't been able to get someone to test it but it looks like an app issue so far. If you could test that would be great @cowomo404 !

I've done a fresh install and I'm not seeing this error.

Check the version of BS you're using (My one is v2.00.05.60)

Clear out your catalogue data. Browse to the data location that listed in Managed Data in BS. Go in to the data folder and then the "Warhammer 30,000 - The Horus Heresy" folder and delete the .gst and .cat files. Then back to BS and get it to "Update Data" to pull in files again.

**Comment by mugginns** [comment]
I am also seeing this on android and Windows platforms. Reinstalled and cleaned everything out.

**Comment by zopha** [comment]
Thanks @mugginns! Can you check the version of BS you're running on Windows for me, please?

**Comment by cowomo404** [comment]
I am also still seeing this with 0 points spent BS v2.00.05.60 on MacOS
![screen shot 2016-12-15 at 10 02 58 am](https://cloud.githubusercontent.com/assets/13860904/21231382/b2a65d82-c2ad-11e6-9b24-c845354a2e74.jpg)

**Comment by zopha** [comment]
Thanks for the screenshot @cowomo404 I realise my mistake now, I was creating lists with no points limit so the error wasn't kicking in. I'm not sure why this error is happening, I'm not familiar with how that, lords of war restriction, works but I'll see what I can find out a little later.

**Comment by zopha** [comment]
@cowomo404 @mugginns 

Battlescribe v2.00.06.61 desktop and v2.00.14 android has been released. I've tested this issue on it and I'm not seeing that error any more. Can you update and check as well please?

Change log includes

"Fixed incorrect roster errors for restrictions based on roster points limit" so it looks like this was a BS app bug that Jon has fixed.

**Comment by cowomo404** [comment]
I updated my desktop version to v2.00.08.63 (MacOS) and tested - it appears that it is correctly calculating the lord of war slot now. 

I also validated on iOS v 2.00.12

I tested both under point and over point allowance expected warning messages were displayed.
From my POV this it good/closed. Thank you.
