### ISSUE TITLE
Blackshields should have Knights Errant as a HQ choice

### ISSUE THREAD

**Issue by Hasfodel** [BSData/horus-heresy#577]
Knight errants should appear as possible HQ choice for loyalist blackshields

**Comment by Hasfodel** [comment]
++

**Comment by zopha** [comment]
Probably best to add to the main GST file as they can be used in multiple loyalist armies.

I'm working on the base Astarte units at the moment and maybe @Millicant would want to work on this one. Once I'm finished with the Army list red book I can look at this if needed.
