### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by zopha** [BSData/horus-heresy#581]
Hi! I'd like to join the group and contribute towards building the datasets needed for this great game. 

I'd like to concentrate on getting everything up to date with the last Astarte army red book and help move required items over to root/shared entries, points updates and adding descriptions. I've submitted a couple of issues so I was going to work on the simple stuff, I've made a branch to deal with the pintle mounts here -> https://github.com/zopha/horus-heresy/tree/Pintle-Mount-Updates and copied most of the stuff from the older 6.9.3 release. I'd like to work on getting the standard vehicle upgrades into a shared profile and once that's all in place re-adding the Malcador and other units that are missing from the current release.

I don't have much git experience yet, I got the basics figured out in the last week and a half and I'm willing to learn if your willing to let me contribute. If anyone wants to review my pintle-mount changes and comment (good or bad, both accepted!) I can correct any mistakes and submit a pull request for it.

Zopha

**Comment by capitaladot** [comment]
+1

**Comment by DonMorr** [comment]
+1

**Comment by amis92** [comment]
Hello, @zopha. Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Also join our team in Gitter chat room (GitHub login): [![Join the chat at https://gitter.im/BSData/horus-heresy](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/BSData/horus-heresy?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

Cheers!

PS @zopha at first you may want to stay with just pull requests so guys can get comfortable with you and vice versa.
