### ISSUE TITLE
[LoW] No option/Exceeded LoW points allowance

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#583]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** No lord of war option, says I've exceeded lord of war by 1875 in a 2500 list

**Comment by coxiewoo321** [comment]
I've got the same problem and no one seems to care at all, it's really irritating me

**Comment by zopha** [comment]
@coxiewoo321 I'd take a stab at a fix but I've no idea how it works at the moment.

Can you try deleting your data and re-download it to see if that fixes the exceeded limit when no Lords of War are chosen? BS can hold on to old data and sometimes needs a clear out. I have a new install of BS on my phone, in the last two days, and I'm not getting that warning.

As for adding a Lord of War, 

1. Add a new Force Org in at the bottom
2. Touch it for options
3. Touch the Force Org Chart selection (the text, not the radio button!)
4. Change to Lord of War
5. Go back to the main roster
6. Add in your Lord of War
7. Remove the Lord of War Force Org entry you just added

This isn't a great method and is a very roundabout way of adding one but it will allow you to do it. You're left with one warning at the end about "cannot have any selections of Lords of War (hidden)"

I can't do much more at the moment, I have some heavy support fixes waiting for review, if they get passed and I get more experience with BS I can try to fix it, hopefully, one of the other contributors will look at it before then.

Going to reference the following issues that are the same or similar

#576 #584 #567 #494 #497 #456

**Comment by zopha** [comment]
This was a bug with Battlescribe and has been fixed in the latest updates. If you are experiening this issue please update battlescribe.
