### ISSUE TITLE
Knights errant - Valid options for Custodes army?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#590]
**File:** (HH) Custodes - Allied Detachment.catz

**BattleScribe version:** 2.00.13

**Platform:** Android

**Dropbox:** No

**Description:** Sentinel guard squads are also troop I thought and can we also get nathienil and tylos e.g. the knights errant added to the file

**Comment by zopha** [comment]
Sentinel guard are elite according to the FW PDF.

I don't know the knight errant rules well enough for the second request and how they'd work with the get-you-by custodes rules.
