### ISSUE TITLE
[LoW]Add Questoris Knight as LoW choice to Legion lists

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#592]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.05

**Platform:** Windows

**Dropbox:** No

**Description:** There is missing a weapon for the Deredero Patteren Dreadnought. The weapon missing is the Arachnus Lascannon Battery described in the new updated age of darkness army list book.
Also i can't seem to add a questoris knight styrix as a Lord of war choice to my legion list.

**Comment by zopha** [comment]
The Deredero weapon addition will be covered with Heavy Support fix/updates in #568.

As for the Sytyrix, I haven't looked at lords of war or knights yet so I'm not sure how/if that is setup yet.

**Comment by capitaladot** [comment]
#818

**Comment by zopha** [comment]
The Styrix is available in the War Machine Detachment as described in the Age of Darkness Legions red book. This will be in the next release or you can grab the files from the master branch here - https://github.com/BSData/horus-heresy/archive/master.zip If you need instructions on how to replace the files on desktop or android let me know and I can post them.
