### ISSUE TITLE
LoW / Rites of War not selectable/easily found

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#594]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.00.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** 1)There is no Lord of War choise in Legiones Astartes Crusade Army list
2) Cant choose rite of war in praetor options
3) there is no master of the legion choise in delegatus options

**Comment by OzaS** [comment]
1) LoW should be chosen as Force Organization
It's not really easy to understand why, but it is so
2) Right of war can be chosen at legion options
3)strange, maybe bug

**Comment by zopha** [comment]
1) This is something that may need to be reimplemented as it's quite cumbersome to select now.

3) Rite of Command and Master of the Legion are missing from the Delegatus in the overview. The rules are still present in the overview and the Rite of War still works (including the Delegatus-only rite) by going through the Legion Options. This means the only things missing are some text on the overview and a command squad option for the Delegatus.

**Comment by Ronctron** [comment]
I am not seeing LOW as a force organization choice.  I am only seeing:
Legiones Astartes: Age of Darkness Army List v202
and then force org choice is only "The Age of Darkness"

Where is the LOW selection?

**Comment by zopha** [comment]
@Ronctron The force organisation selection has been moved from the list initial list creation to the Force Org section. Just create the list with the options you have and then 

1. Add a new Force Org in at the bottom
2. Touch it for options
3. Touch the Force Org Chart selection (the text, not the radio button!)
4. Change to Lord of War
5. Go back to the main roster
6. Add in your Lord of War

**Comment by zopha** [comment]
Looking at this a bit more and it looks like the detachment choices should be check boxes rather than radio buttons, ticking one would enable the optional LoW/Fortification/Ally slot but we currently have this instead

![2017-01-03 13_53_24-roster editor v2 00 09 - new roster warhammer 30 000 - the horus heresy v43](https://cloud.githubusercontent.com/assets/1666415/21610069/ddc3d7dc-d1bd-11e6-958d-000906cfc39a.png)

There's a lot of dependencies in that section so I'm not going to touch it unless I have it 100% figured out.

**Comment by zopha** [comment]
I've been thinking this one through and the Fall of Cadia supplement for 40k has given me some idea's. The current method makes sense if you look at how they have to implement new cross-codex formations. Troops can come from a mix of 5 or 6 codex, a real problem to implement if they're all separate codexes. Right now w

1. Scrap the current method and place each LoW in the catalogues that may take them. This will be a pain to keep updated but more seamless to the enduser.

2. Enable the LoW slot again and units for the respective armies (Primarchs for legions, etc) but leave in the LoW detachment so another army can be added just for their LoW. Like adding Questoris knights. This one could work like the current system, you add a force org in and set the army and you'll have LoW options available to your army. It would take a bit of work to make it work.

3. Make the current system work. LoW are only added to a roster via a detachment. Validation can be made to work, just a matter of getting it right and advising end users.

I don't think the detachment method of adding units is going to go away. The talons of the Emperor and the Space Wolves seem like good candidates to have units that fill different Force slots (troops, heavy support, etc) for other armies. Also could be a good way to get the Word Bearer/Militia rite that combines both to work properly.

@capitaladot @Toreador13 @thebiggeordiegeek (or anyone else) do you have any suggestions or ideas on this?

**Comment by cowomo404** [comment]
I'm able to find LoW options - but Rights of War are gone -  they show up in the desktop version still fine - but a buddy of mine was telling me he could not figure out how to add a RoW - I cannot either.

Should I create a separate issue for RoW vs LoW?
