### ISSUE TITLE
[Astarte - EC]Phoenix Terminator squad missing the Phoenix champion as part of their entry

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#596]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.00.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Noticed a couple things:

1) Orbital assault RoW allows talons of dreadnoughts to all take dreadnought drop pods; however, if you have RoW selected and multiple dreadnoughts in a talon the dreadnought drop pods option disappears from their dedicated transport options.
2) Legion praetor tribune HQ option appears to be missing.
3) Phoenix Terminator squad for Emperors Children are missing the Phoenix champion as part of their entry. Currently can only produce a 9 man unit without champion. Odd thing is that if you "view" your list it suddenly shows up just not in the roster section when building the list.

**Comment by zopha** [comment]
Thanks for submitting this issue! 2 is known, the other two will need to be implemented or fixed.

1. Needs to be implemented. Also, Deathstorm drop pods are missing from this RoW as mentioned here - #575
2. Praetor Tribune missing was reported in #507
3. Need to replicate this and see where the error is. Must be something set to hidden when it shouldn't be.
