### ISSUE TITLE
Astarte Elites changes

### ISSUE THREAD

**Issue by zopha** [BSData/horus-heresy#597]
Here's my QA of the Elites section.

----
- [x] LEGION VETERAN TACTICAL SQUAD LA:AODAL P.28
	- [x] Veteran Tactics:
    	- [x] Weaponmasters extra rules not showing
    	- [x] Xenobane extra rules not showing
    	- [ ] Add option to display all rules for those who want to choose right before a game?
	- [x] Squad Weapons
    	- [x] Single Lighting Claw option missing
	- [x] Sergeant
     	- [x] Artificer Armour does not change save to +2
	- [x] Rhino - Link to Dedicated transport entry

----

- [x] LEGION DESTROYER SQUAD LA:AODAL P.29
	- [x] Profile
    	- [x] No indication of dual bolt pistols
     	- [x] No indication of chainsword/combat blade
    	- [x] No indication of frag/krak grenades
     	- [x] Counter Attack missing profile
	- [x] Weapons
     	- [x] Hand Flamer missing Profile
     	- [x] Plasma pistol missing profile
     	- [x] Power weapon pofile?
     	- [x] Power Fist missing profile
     	- [x] Thunder Hammer missing profile
     	- [x] Lighting claw missing profile
	- [x] Transports
     	- [x] Proteus - Link to standard entry
     	- [x] Rhino - Link to Dedicated transport entry

----

- [x] LEGION TERMINATOR SQUAD LA:AODAL P.30
	- [x] Heavy Flamer missing profile
	- [x] Gets Hot! missing profile
	- [x] Heavy 2 missing profile
	- [x] Twin-linked missing profile
	- [x] No options to choose combi-weapon loadout (Is that really needed?)
	- [x] Chainfist missing profile
	- [x] Pair of lighting claws missing profile
	- [x] No option for standard Terminator armour
	- [x] Transports
     	- [x] Link Dedicated transports to standard entry

----

- [x] TECHMARINE COVENANT LA:AODAL P.31
	- [x] No indicaition of servo arm
	- [x] No indication of power axe
	- [x] No indication of bolt pistol
	- [x] Master-crafted bolter missing profile
	- [x] Plasma pistol missing profile
	- [x] Melta bombs missing profile
	- [x] No indication of artificer armour
	- [x] Servo-automa
     	- [x] Not counting automa exchange for different weapons (maximum 0)
     	- [x] Reduce Rotorcannon to 5 points
     	- [x] Flamer missing profile
     	- [x] add Heavy Bolter
     	- [x] add Multi-melta
     	- [x] add Missile-launcher (frag & krak)
     	- [x] add option to add rad (when rad grenades are selected) +10 points
     	- [x] No indication of Automa weapons
     	- [x] No indication of chainsword on automa

----

- [x] APOTHECARION DETACHMENT LA:AODAL P.32
	- [x] No feel no pain roll
	- [ ] ~~Simplify bike rules~~ -GST mod needed.
----

- [x] LEGION DREADNOUGHT TALON LA:AODAL P.33
	- [x] Weapons
     	- [x] No indication of DCC
     	- [x] No indication of TL Heavy bolter
     	- [x] Multimelta missing profile
     	- [x] TL Autocannon missing profile
     	- [x] TL missile launcher missing profile
     	- [x] Plasma cannon missing profile
     	- [x] Flamestorm cannon missing profile
     	- [x] TL lascannon missing profile
     	- [x] Havoc launcher profile missing
     	- [x] Frag Assualt launcher missing
     	- [x] Chainfist missing profile
     	- [x] Siege Wrecker
        	  - [ ] Missing Concussive profile
        	  - [ ] Missing Specialist weapon profile
        	  - [ ] No indication of TL bolter or profile
     	- [x] Inbuilt Weapons    
        	  - [ ] Not counting TL-bolter when using "replace any inbuilt TL-bolter with"
        	  - [ ] No inbuilt heavy flamer profile
        	  - [ ] No inbuilt melta gun profile
	- [x] Standard Wargear
    	- [x] Searchlight
     	- [x] Smoke launcher
     	- [x] Change Extra Armour to shared profile
     	- [x] Change Armoured Ceramite to shared profile
     	- [x] Hunter killers limited to 1 (should be 2)
	- [x] Profile Changes
     	- [x] Extra DCC does not add extra attack
     	- [x] BS 4 (currently 5)
     	- [x] Check attacks in FAQ
----

- [x] CONTEMPTOR DREADNOUGHT TALON LA:AODAL P.34
	- [x] Standard Wargear
     	- [x] Searchlight
     	- [x] Smoke launcher
     	- [x] No indication of DCC
     	- [x] No indication of TL Heavy bolter
     	- [x]      Add extra armour shared profile
	- [x] Profile Changes
     	- [x] Fleet rule missing
	- [x] Link Drop pod to standard entry
	- [x] Weapons
     	- [x] Reduce TL autocannon by 5 pts (and profile)
     	- [x] TL volkite missing TL rule
     	- [x] TL lascannon missing profile
     	- [x] Inbuilt Weapons    
        	  - [ ] Not counting TL-bolter when using "replace any inbuilt TL-bolter with"
        	  - [ ] No inbuilt heavy flamer profile
        	  - [ ] No inbuilt melta gun profile
----

- [x] LEGION RAPIER WEAPONS BATTERY LA:AODAL P.35
	- [x] Profile
     	- [x] Missing Extremely Bulky profile
     	- [x] No indication of default weapon (quad heavy bolter) or profile
	- [x] Marines
     	- [x] No indication of bolt pistol
     	- [x] No indication of frag and krak
     	- [x] No indication of PA
     	- [x] 2 crew per battery
	- [x] Weapons
     	- [x] missing haywire profile for Graviton
     	- [x] No costs for mortor ammo
     	- [x] No selection for mortor ammo
----

- [x] LEGION MORTIS DREADNOUGHT LA:AODAL P.36
	- [x] Standard Wargear
     	- [x] No indication of default 2 TL heavy bolters
     	- [x] Add Smoke launchers
     	- [x] Add searchlight
     	- [x] Extra Armour is a 0 - 2 option rather than a tick box
	- [x] Hunterkiller 0 - 2 works, copy this for the other dreads
	- [x] Weapons
     	- [x] Add Havok Launcher profile
----

- [x] CONTEMPTOR-MORTIS DREADNOUGHT LA:AODAL P.37
	- [x] Standard Wargear
     	- [x] No indication of default 2 TL heavy bolters
     	- [x] Add Smoke launchers
     	- [x] Add searchlight
     	- [x] Extra Armour is a 0 - 2 option rather than a tick box
	- [x] Weapons
     	- [x] Add Havok Launcher profile
----

- [x] CONTEMPTOR-CORTUS CLASS DREADNOUGHT TALON LA:AODAL P.38
	- [x] Profile/Standard Wargear
     	- [x] Add fleet profile
     	- [x] Add Move through cover profile
     	- [x] Add Smoke launchers
     	- [x] Add searchlight
     	- [x] No indication of default loadout (DCCW and TL heavy bolter)
     	- [x] Update Extra armour to shared profile (set at 10 pts when it should be 5)
	- [x] Rest of the entries to mirror this standard Contemptor class
----

**Comment by capitaladot** [comment]
This is great work, Is someone tackling this one?

**Comment by alphalas** [comment]
Probably could easily be fixed by @Kohato

**Comment by zopha** [comment]
I was distracted by getting the GST updated and after the other legion reviews I didn't have the concentration needed to tackle the terminator entry. I did work through some of the dreads though. I'll review this and see what I've actually done.
