### ISSUE TITLE
[LoW]Points allocation error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#599]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.13

**Platform:** Android

**Dropbox:** No

**Description:** When I start a new roster, bevors I make any selections or choose an organisation plan, I get an error saying that I spent the entire points budget in LoW units. I.e. in a 3000 pts roster, the message says: Roster x has spent 2250 points too much on Lords of War (750pts / 25% of points limit). This is before I choose a single unit for the roster and it keeps showing up, even when the roster is finished and I spent the entire budget on non-LoW units. The same error occurs with the Questoris Knights Army list.

**Comment by zopha** [comment]
I've done a fresh install and I'm not seeing this error.

Can you clear out your catalogue data and see if that helps? You can delete data from the menu in Manage Data. Take a look at this: https://battlescribe.net/?faq=refreshData

**Comment by zopha** [comment]
This was a bug with Battlescribe and has been fixed in the latest updates. If you are experiening this issue please update battlescribe.
