### ISSUE TITLE
Seeker ammo update

### ISSUE THREAD

**Issue by Hasfodel** [BSData/horus-heresy#601]
Scorpius bolts are now 254" s5 ap2 heavy1, shred

**Comment by zopha** [comment]
Thanks! I've updated #562 with the new Strength, must have missed that when I went through the list. @DonMorr is working on that issue so we're aware of it and will get it updated/changed.

----
I'll close this off as a duplicate. If there are any more updates for FA units can you put them in the #562 issue, please?
