### ISSUE TITLE
Update Legion Breacher Siege squad points value to latest Red Book/FAQ

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#607]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.00.05

**Platform:** Windows

**Dropbox:** Yes

**Description:** Legion Malcador Tank is no longer a Lord of War as of the most recent rulebooks, and is also 275 points base, not 300. Flare shields are 45 points, not 25. Legion Breacher Siege squads are 200 points base, not 210. Also it would be nice if the 40K fortifications (including fortification networks) would be included in the Fortification detachment section.

**Comment by zopha** [comment]
Legion Malcador Tank will be added/updated in #568 

Flare Shields will be updated in #568 with the Spartan entry

Yeap, Breachers will need to be updated. Changed the title in this issue to refect that.

Fortifications will be covered in #529 Not sure of the scope of work required on that but it'll take a bit of time to implement and test.
