### ISSUE TITLE
Mechanicum Taghmata army list - Update Lord of War and superheavy units

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#608]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.00.05

**Platform:** Mac

**Dropbox:** No

**Description:** The Lord of War slots e.g. for Mechanicum Taghmata Army List are missing. You can't even choose a knight or the Ordinatus stuff. And 2nd: Can you please add the Vultarax Drones?! Thanks a lot! :)

**Comment by zopha** [comment]
The Vultarax will be covered in #523

Have to look at the Mechanicum Taghmata Army list to see what's missing but a good few lord of war need to be added/updated.

**Comment by zopha** [comment]
Ordinatus are in and visible now under the LoW slot. Knights are available in the War Machine detachment. LoW knights are due for an update and we'll get them done for all relevant armies.

![2017-02-17 10_56_09-roster editor v2 00 11 - new roster warhammer 30 000 - the horus heresy v58](https://cloud.githubusercontent.com/assets/1666415/23063136/d9de9d30-f500-11e6-9d1c-ceeae6e46771.png)
