### ISSUE TITLE
Rhino Pintle weapon prices are off

### ISSUE THREAD

**Issue by cowomo404** [BSData/horus-heresy#620]
I saw a previous issue listed which said it was fixed but it does not seems to be the case in the Battle scribe 2.
All prices list are per LAAoDAL pg. 45.

Combi-weapon should be 5 points
Havoc launcher is correct at 15 points
Heavy bolter should be 10 points
Heavy flamer should be 10 points
Twin-linked bolter is correct at 5 points

Missing multi-melta at 15 points

Battlescribe 2.00.10 on iOS

**Comment by zopha** [comment]
Looks like the issue has been fixed but the edited files have not been released, so it'll be in the next release.

There's an issue with the pintle mounts across nearly all units. Thankfully they seem to be a standard set of pintle mounts for Astarte vehicles so I've added a group to #568 that will make updating them easier in the future.

**Comment by cowomo404** [comment]
Awesome, thanks. Separate but related issue... is the team moving to a regular release schedule (or are y'all already on a regular schedule)?

**Comment by zopha** [comment]
@cowomo404 I have no idea. I came in just as @capitaladot was moving city (and has no internet atm) and I haven't seen anything from @Millicant for over a month. I'm not sure if there's anyone else working on the repo atm, just those two.
