### ISSUE TITLE
Dark Angels - Vets missing Molecular acid rounds (heavy bolter) and Stasis rounds (missile launcher)

### ISSUE THREAD

**Issue by zopha** [BSData/horus-heresy#623]
- [x] Dark Angel Veteran Tacticals are missing the option to take Heavy bolters with molecular acid rounds 
- [x] Dark Angel Veteran Tacticals are missingr missile launchers with stasis rounds.
- [x] Dark Angel Dreadnoughts (all types) should have Molecular Acid Rounds option for all Heavy Bolters
- [x] Dark Angel Jetbikes should have the Molecular Acid Rounds option for all Heavy Bolters
- [x] Dark Angel Rapier Quad Heavy Bolters should have the option for Molecular Acid Rounds
- [x] Ironwing Protocol Assault Weapons should have the rule  +1 to wound roll within 12".

Source: http://www.bolterandchainsword.com/topic/326330-30k-battlecribe-repository/?p=4561204

**Comment by Ammobunkerdean** [comment]
also need Molecular acid rounds added to Predator sponsons, Deredeo dreads and probably every land raider and Sicaran that can select heavy bolters.  
Contemptor and Legion Heavy support squads work...

**Comment by capitaladot** [comment]
@ammobunkerdean: please reread book 6. Only models with Legiones Astartes (and Dreadnoughts) can take the special issue ammunition.
