### ISSUE TITLE
Proteus missing hull mounted twin linked 

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#626]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.12

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Still unable to select Hull Mounted Twin Linked Lascannon on a Land Raider Proteus.

My original submission / query has been closed.

**Comment by zopha** [comment]
Was it #525 ? The issue was fixed but a release hasn't been pushed out yet.

**Comment by zopha** [comment]
The hull-mounted lascannon is available now after the last release.
