### ISSUE TITLE
Damocles command rhino missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#628]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.12

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Damocles command rhino no longer appears to be an option no matter what I do or what legion I select.

**Comment by zopha** [comment]
Pretty sure the Damocles is in the data files, could be hidden or something is missing but it will have to be checked and looked in to.

**Comment by zopha** [comment]
The Damocles is present on unlimited lists or lists over 1k points. If it's
missing from yours please refresh your data.

Screenshot attached for reference, a 1k list with imperial fists selected.

**Comment by zopha** [comment]
Okay, email ignores attachments so here's the screenshot.

![screenshot_20170103-081548](https://cloud.githubusercontent.com/assets/1666415/21603938/6706d330-d198-11e6-9088-6284f01f9562.png)
