### ISSUE TITLE
 Legion Praetor Tribune missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#629]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.00.06

**Platform:** Windows

**Dropbox:** Yes

**Description:** Forge World's Legion Praetor Tribune model (sold in GW stores a few months ago) isn't supported in the data files (it's not quite a standard Praetor):
180 points. Has the same profile as a standard Praetor,
Wargear: Master-crafted paragon blade, Iron halo, Digital lasers, Tartaros pattern Terminator Armour
Special Rules: Legiones Astartes, Master of the Legion, Independent Character, Exemplary Tribune (This profile represents a common pattern of deployment for the many lesser Praetors that existed during the glory days of the Space Marine Legions. A Legion Praetor Tribune may be included as an HQ choice in a Space Marine Legion army selected from the Legiones Astartes - Age of Darkness Army list, but may not be given any other options or wargear. It uses the same additional Legion rules as the other units of the detachment it is included in, as per the Legiones Astartes special rule.)

**Comment by zopha** [comment]
Will be fixed when #614 is merged.

**Comment by zopha** [comment]
Forgot to add a tag to close this on merge but the Tribune is added now. The next release is queued up and will be available shortly (a few hours)
