### ISSUE TITLE
Add Indomitus Terminator armour option for Terminators and characters

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#630]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.08

**Platform:** Windows

**Dropbox:** Yes

**Description:** The various characters have the options to take Tartaros- or Cataphractii-pattern Terminator armour, but also "ordinary" Terminator Armour; something not reflected in the data file. A pedantic note perhaps, but for those of us trying to remain WYSIWYG, it'd be appreciated. :)

**Comment by zopha** [comment]
@DonMorr added this for some. Not sure if it's for them all or just the Terminator squad. Will look at this a little later if no one else gets to it.

**Comment by Morturg** [comment]
So this wasn't implemented, or doesn't seem to be working in my download

**Comment by zopha** [comment]
Hello!

Not yet, I've been working through the standard entries (and fixing any mistakes I've made) Part of the way through Elites at the moment and HQ will be next. Each unit has a separate entry for Terminator armour and I was going to create a single selection group with all three types that can be selected.

**Comment by zopha** [comment]
#540 covers adding Terminator armour. The Terminator squad and command squad are done and will be in the next release. I'll work on the two HQ units. I'll close this one off for now as it's a duplicate.
