### ISSUE TITLE
Questoris Knight list

### ISSUE THREAD

**Issue by fedratsailor** [BSData/horus-heresy#635]
taking the atrapos brings up an error stating 0 can be taken.  Also Knights have their own force org.

**Comment by zopha** [comment]
Should be able to fix the Atropos fairly easily. I'll look at it during the week for the next release.

I haven't touched the knight stuff yet so not sure what needs to be done for a separate force org for them.

**Comment by fedratsailor** [comment]
here ya go on the Force org, should be a simple fix.  saw someone else mention adding the Porphyrion.


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by zopha** [comment]
I mentioned that new knight in #613 to track it. As there's issues with the
LoW slot at the moment the new knight probably won't get added until that's
fixed.

Screenshot of the Atropos error attached for reference.

I'm not very familiar with force orgs yet so that may take a few weeks to
figure out and implement.

**Comment by zopha** [comment]
I should never have said this would be simple. Tried editing the Questoris knight list and

>net.battlescribe.a.c.f: File was corrupted and has been deleted:

This will take longer than I thought to fix, the file may need a manual review to find the issue but I've removed the Atropos and the error has stopped, I'll try re-adding it and see if it fixes it or brings back the error.

**Comment by zopha** [comment]
I have the Atrapos limit fixed now. The limit of 0 will lift when you have 2000 (including the Atrapos) actually in a list. If you add the Atrapos first you'll get the validation error until you have added at least 2000 points in the list. You should be able to add a second at 4000 points as well.

You'll see the update in the next release which, depending on my schedule, will be between now and the end of the week.

I've made some general updates to the Questoris list as well but still need to work on the Questoris force org.

**Comment by fedratsailor** [comment]
you rock, thanks for taking a look at it.


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by zopha** [comment]
I ran through the Force Org for Questoris knights and most limitations are too high so I've adjusted them to match the Questoris knight force org. These changes will be in the next release.
