### ISSUE TITLE
Bug fixes (items I missed mainly) for the 7.1.1 release

### ISSUE THREAD

**Issue by zopha** [BSData/horus-heresy#637]
Minor bug fixes (items I missed mainly) for the latest release 

- [x] Predator missing Plasma Executioner turret (reported by @cowomo404 in #636 #638 )
- [x] Correction: Preator heavy conversion Beamer has no cost, should be 35. #638 
- [x] Sicaran battle tank missing optional pintle-mount
- [x] Phosphex Grenades have no cost (should be 10 each)
- [x] Update Heavy support squad weapons to show profiles
- [x] Legion Heavy support squad- You appear to be charged for the sergeants upgraded weapon, even if he swaps his flamer out for something else.
- [x] Machine Spirit has no cost for Vindicators and Predator tanks.

**Comment by MountyChris** [comment]
Cheers for the update.
Couple of bits still off. 
Predator sponsons don't appear to be working for me now. 
Land speeder Hunker Killer Missiles should be 5pts not 10. 
Legion support squad- You appear to be charged for the sergeants upgraded weapon, even if he swaps his flamer out for something else. (At least, that's my understanding of how it should work)
Cheers

**Comment by zopha** [comment]
@MountyChris Thanks!
I have a look at the support squad sergeant stuff a little later, didn't realise that. Thanks!

The last update just dealt with Heavy Support updates as there were quite a few changes to be made in that section. We'll get the FA units updated next and then on to Elites and Troops.

Can you get a screenshot of the sponson option or what's happening with it? Or try doing a delete and refresh of your data files and see if that helps. You can delete data from the menu in Manage Data, info on doing that is avaiable here : https://battlescribe.net/?faq=refreshData

**Comment by MountyChris** [comment]
Deleting and redownloading the data file fixed the predator issue. Cheers! 

Is anyone looking into making the roster compatible with 40k fortifications?

**Comment by zopha** [comment]
There is an issue open for it #529 not sure if anyone is working on it, there hasn't been much activity around here for the last while so it's just me at the moment.

Fortifications from 40k shouldn't be too difficult, they've integrated them into their main catalogue file. I'm not sure that would be a good idea for the heresy files though. The main catalogue file is handy for a few things but adding them all in would be a large increase on an already large file. If there are one or two fortifications that are in high demand I can look at adding them into the current system but it's not something I'm planning on fixing anytime soon. They might work best for the heresy files if they're in a separate file so they only get loaded if they're wanted.

Also, the heavy support update is basically my first update, I've learnt a good bit from it and I want to get the basic Astarte units updated before tackling the complicated and extremely complicated stuff, along with that, quite a few units could be optimised to use new BS2 features to reduce the size of the catalogues.

**Comment by Toreador13** [comment]
@zopha Did you do updates on the Taghmata list? I have made fixes and updates to the file for basic weapons and added the Vultarax. I didn't see the version number change. 

I have requested to be on the change team, but with @Millicant AWOL for the last month not sure that can happen.

**Comment by zopha** [comment]
@Toreador13 I only made two small changes and added an entry for the Vultarax. I've only looked at the Taghmata catalogue for simple bug fixes so far, nothing more. Did your changes get added a while ago? 

Did you raise the join request in this repo or through PM? I'm sure any help with that army would be welcome here.

**Comment by Toreador13** [comment]
The join request is through the team feature on Github. 

I have the file, but am unable to do much with it since I don't have permission. Was waiting to see if Milicant was going to show again after Christmas. I was going to submit it today, but then saw your update. I started going through the file adding basic wargear and weapons to the file. I can look at merging what you did and what I have done together tonight.

**Comment by zopha** [comment]
I didn't do much so if your file has more fixes and updates in it along
with the Vultarax we could potentially replace the one I updated. I just
wasn't aware anyone was working on it. We just need to make sure the
catalogue version number is higher than the current one, if we can replace
it.

I wasn't aware of the team function, most of the time I've seen people
submitting issues with [Join Request] as the title. If your current request
is pending for awhile maybe try that instead and we can work something out.

**Comment by Toreador13** [comment]
I have done quite a bit to the units in the file, so it might be easier. I will have to do a compare and see. 

Are either of you able to add me? It's pending there, but I am not sure if Milicant is the only one that gets that notification.

**Comment by HorustheWarmaster** [comment]
I figure I'll leave this here since it deals with things missing- there's a box to select the sponsons for the Sicaran, however the only choice available is "None" preventing you from selecting the lascannons.

**Comment by HorustheWarmaster** [comment]
Sorry, didn't see it was updated on the third- I apologize. It works correctly

**Comment by zopha** [comment]
@Toreador13 I can't see anything in particular, it just may not be visible to me. @amis92 are you able to see @Toreador13 's team join request? Or am I just not looking in the right place?

No worries @HorustheWarmaster thanks for submitting an issue for it!

**Comment by zopha** [comment]
I missed the "and all child selections" on the Heavy Support team so the query didn't trigger when the Seargent dropped his and took a Nuncio vox.  I'll fix that and it should be sorted in the next general release.

**Comment by amis92** [comment]
@Toreador13 yeah I wasn't notified, I'm org admin and it seems only team maintainers are notified. Already approved.
