### ISSUE TITLE
Taghmata updates

### ISSUE THREAD

**Issue by zopha** [BSData/horus-heresy#640]
I just realised the updated Taghmata file you've been working on is uploaded now.

Do you have a basic or short list of the changes you've made? It would be good to review them before a release goes out and to make sure it doesn't break anything :) or catch some small stuff if you missed it (like I did with some of the astarte heavy support options)

Are you in a position to do future updates or bug fixes for this catalogue? If so we can assign issues to you so you get to look over them first so I don't go making changes while you're working on something again :smile: 

If this is a one-time update from you then no worries, thanks for contributing!

**Comment by Toreador13** [comment]
Not much of a list. It was what I was doing way over a month ago, and primarily was adding basic weapon entries for most of the units. Very few of the standard weapon loadouts on units were represented or had a profile so it was rather hard to tell what units had what wargear and weapons. I need to go back through and clean up shared entities. You can assign me any of the Taghmata bugs, I can take "ownership" of the file. There might be a few things people have to clean up on old rosters with the groupings of weapons on some units, but it should be rather small. I have been using this file for games for the last 2 months or so with my Taghmata.

**Comment by zopha** [comment]
The file has been released now. It'll need a clean up at some stage but nothing urgent, I can see some selection entries for Drop Pods and bolters that aren't used for anything, perhaps relics from its initial creation.
