### ISSUE TITLE
Where to find - Rite of war

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#642]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** My issue has to do with selecting a "rite of war"
In the older editions you could just click on the master of the legion button and select your perfered rite of war but since the update we can not longer click on that button. So I ask you to either add rites of war or explain where they can be found. 
Thanks.

**Comment by zopha** [comment]
Sorry, I thought I replied to this.

Rite of War has moved from the unit entry.

Add in your master of the legion and then scroll down to the Legion section and hit the + you'll have a Rite of War entry there now.

**Comment by zopha** [comment]
I'm going to close this off as it's been answered for a few days. A No Force Org slot has been added to the GST with instructions on these two topics so everyone should have access to the info now.

Should have a fix to enable a Primarch to trigger the Rite selection fairly soon.
