### ISSUE TITLE
Can't select LoW option without an errors

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#647]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.22

**Platform:** Android

**Dropbox:** No

**Description:** Can't select low option without an error occurring.  To select one I have to add an additional force org select low det add what I want then remove the force org to get me back to creating the army.

**Comment by zopha** [comment]
To add a LoW in without errors add a second force when creating the list, in that second force you can change it's force org to LoW. This will change the force org structure in that force to allow for one LoW and you can build your list in the other force.

We're looking in the current stucture and are using #594 to keep track of it.

**Comment by zopha** [comment]
I'm going to close this off as it's been answered for a few days. A No Force Org slot has been added to the GST with instructions on these two topics so everyone should have access to the info now.
