### ISSUE TITLE
New LoW units missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#648]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.22

**Platform:** Android

**Dropbox:** No

**Description:** Latest variants of low ie marauders macharius etc not showing up

**Comment by zopha** [comment]
We have a lot of work to do to get basic units updated, something I'm working on at the moment. The missing LoW's are being covered in #528 and will get added, it will just take a bit of time to get everything else sorted out.

**Comment by zopha** [comment]
I'm going to close this one off as we have an existing issue for it and the missing units will be added once we get to reviewing LoW entries.
