### ISSUE TITLE
Unable to select a Rite of War or Lord of war

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#650]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Unable to select a Rite of War for master of the legion. Also unable to add Lord of War options in same roster as a force organization (requiring a separate detachment dedicated solely to the lord of War)

**Comment by MrRta1910** [comment]
Once u have a unit with master of the legion go to legion choice and there will be rite of war choice

**Comment by zopha** [comment]
The separate detachment for a LoW is the current implemented method of adding a LoW. I'm hoping to get this reviewed but it will take some time to look at.

As for Rite of War, MrRta1910 has it. It's moved from the unit entry to the legion section.

Add in your master of the legion and then scroll down to the Legion section and hit the + you'll have a Rite of War entry there now.

We have an issue logged for both of these in #594 and will update that ticket with any developments or changes.

**Comment by zopha** [comment]
I'm going to close this off as it's been answered for a few days. A No Force Org slot has been added to the GST with instructions on these two topics so everyone should have access to the info now.

Should have a fix to enable a Primarch to trigger the Rite selection fairly soon.
