### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by thebiggeordiegeek** [BSData/horus-heresy#653]
Hey dudes

Just getting to grips with GirHub, and with the catalogues, but figure it's time to join the team properly.

**Comment by capitaladot** [comment]
The more the merrier. +1

**Comment by capitaladot** [comment]
@amis92

**Comment by zopha** [comment]
Awesome! +1

Are you interested in working on any particular armies?

If you have any questions about how the catalogue is set up, how to do something in BS, want to talk or get stuck on something there's a github chat site called gitter https://gitter.im/BSData/horus-heresy 

The 40k channel is quite helpful as well, they're quite active in that channel and will try to help.

The last things I'd say are 
If you're working on something let us know so we don't duplicate it and work over each other, also let us know if you're working on a catalogue as this can help to avoid merge conflicts. 
Try to stick to branches for any changes, either on the main code or if your going to work from a fork. 
Merging XML can be tricky and the auto merge on github will throw up merge conflicts even with small changes. Like if I pop in and make some changes to the Legion catalog and you've spent the last 5 hours working on something and set up a pull request, the auto merge will throw up errors.

@capitaladot Has experience manually fixing merge errors and I don't have any at all. Let's try to avoid them if we can. Depending on the scale of them they can be tricky and time intensive to resolve.

**Comment by thebiggeordiegeek** [comment]
Will just stick to little things as I start to learn a bit more about the catalogue, but have an interest in testing issues out when they arise and trying to deal with easily answered questions/simple fixes.

**Comment by amis92** [comment]
Hello, @thebiggeordiegeek. Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Cheers!
