### ISSUE TITLE
Legion support squad cost error

### ISSUE THREAD

**Issue by Vexxnoir** [BSData/horus-heresy#654]
When upgrading the framers it looks to be calculating it wrong. Charging 90 instead of 75 for the base 5 people for meltaguns or plasmaguns

**Comment by zopha** [comment]
I put an extra increment in for some reason. Removing it will resolve this.

![Uploading 2017-01-16 09_42_54-Data Editor 2.00.10 - Legiones Astartes_ Age of Darkness Army List.png…]()
