### ISSUE TITLE
Sky slayer weapon

### ISSUE THREAD

**Issue by Hasfodel** [BSData/horus-heresy#658]
Please check the point cost of the heavy weaps for the sky slayers,( I'm not Sure but the plasma and volkite may be over costed)

**Comment by zopha** [comment]
Looks okay for me with the legion army list red book.

Plasma is 45 for the base squad (3 x 15)
Volkite is 30 for the base squad (3 x 10)

Is that's what you're seeing?

**Comment by thebiggeordiegeek** [comment]
The unit entry requires that the entire unit upgrade their weapons, costs listed in the data file are therefore correct so I shall close this issue.

**Comment by Hasfodel** [comment]
I don't have the book so I thought that it would be same point cost for the weapons as the skyhunters (so free volkite and 5pts plasma, as the multimelta are already included and are usually at 10pts)

**Comment by Hasfodel** [comment]
Wasn't shire btw ^^

**Comment by zopha** [comment]
@Hasfodel I think the extra cost is because you can have more of them and you don't have to pay for 2 standard bikes to get access to a heavy weapon. Although this is FW! Could be for any reason :)
