### ISSUE TITLE
Hammer of Olympia - All vehicles and walkers get Extra Armour for free

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#659]
- [ ] The Iron Warriors Rite of War: Hammer of Olympia gives all Vehicles and Walkers Extra Armour for free. Rule is called: Shattered in Steel.
- [ ] Ironwing Protocol gives a rule called Dust of a Thousand Worlds to Tanks, allowing them to ignore the first failed Dangerous Terrain roll.

**Comment by zopha** [comment]
Might be able to do this by putting a modifier in the main Extra Armour entry. Needs to be tested though.

The only thing to note is it only applies to vehicles with the Tank and Walker types.

**Comment by capitaladot** [comment]
I had zero'd out the cost and set minimum to 1 in the 1.x files.
The same thing needs to be done for The Dust of a Thousand Worlds for Dark
Angels Ironwing Tanks.

**Comment by zopha** [comment]
I keep forgetting about those files :/ and here it is

![2017-01-16 20_59_23-data editor 2 00 10 - legiones astartes_ age of darkness army list](https://cloud.githubusercontent.com/assets/1666415/21998805/d27608fc-dc2e-11e6-986f-24e32d26831a.png)

Did you have to do anything to separate out the flyers that can take extra armour or were they all separate entries?

**Comment by capitaladot** [comment]
I had probably refactored it out to a shared entry. I did a lot of that sort of cleanup in the 1.x that was clobbered with the 2.x file.

**Comment by alphalas** [comment]
rolled into #863
