### ISSUE TITLE
Apothecary missing bike and jump pack options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#660]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.00.10

**Platform:** Windows

**Dropbox:** No

**Description:** Legion Astartes, Age of Darkness Army list, Elites, Apothecarium Detachment, no access to Jump pack or space marine bike with twin-linked bolters, which they do in my red book, Legion Astartes, Age of Darkness Army List, page 32.

**Comment by zopha** [comment]
Can you update your catalogue files please.

Jump packs and bikes are available under additional wargear for each individual Apoticary.

Screenshot of an Apoticary with a bike http://i.imgur.com/s4xsiHP.png
