### ISSUE TITLE
Demon LoW additions for WB - Cor’bax Utterblight and Samus

### ISSUE THREAD

**Issue by zopha** [BSData/horus-heresy#663]
Just logging to keep track, these can be used in the Demon codex but that will be a large implementation so they can be added to the Legion file for Word Bearers until Demons get added.

Cor’bax Utterblight and Samus can be chosen as a LoW for the Word Bearers legion.

Rules available as PDF on FW site.

**Comment by capitaladot** [comment]
These are in the old file.

**Comment by zopha** [comment]
Have they been added in another issue/commit?
