### ISSUE TITLE
Legion Falchion Super-Heavy Tank Destroyer - Missing upgrade

### ISSUE THREAD

**Issue by Piratos89** [BSData/horus-heresy#664]
Greetings

I just noticed a little bug while playing around in Battlescribe. The Legion Falchion Super-Heavy Tank Destroyer, which is a LoW choice in the Legion Astartes list, is missing the Neutron Wave Capacitor upgrade (AODAL:84).

Anyway, you guys are doing a great job and its really nothing major, just thought I'd let you know :)

**Comment by capitaladot** [comment]
This was in the 1.x file so can be copy pasted?
