### ISSUE TITLE
Solar Aux - Valdor Tank Hunter sponson options need to be updated

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#667]
**File:** (HH) Solar Auxilia - Crusade Army List.catz

**BattleScribe version:** 2.00.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Auxilia Valdor Tank Hunter.  
The vehicle only has a single side sponson, so only 1 weapon to be upgraded 
* Multilaser = Free
* Heavy Flamer = Free
* Lascannon = +10 points (currently shows 2 at +20 points)

**Comment by Steelmaelstorm** [comment]
HH4: Conquest page 282

Or

HH: Crusade Imperials Army List page 50
