### ISSUE TITLE
Legion command squad - Incorrect cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#670]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.10

**Platform:** Windows

**Dropbox:** Yes

**Description:** Legion Command Squad from Legion Praetor costs 100pts in base version.
In LA:AODAL it is listed for 75pts.
Also adding a Chosen to it costs 20pts, in LA:AODAL only 15

Thank you for your awesome work!

BR
Oliver

**Comment by zopha** [comment]
Thanks for submitting the issue.

Fixed in #662 , the Centurion and Praetor still had a unique entry for the command squad so it's been changed to the shared one. It just needs a release for the fix to go out to everyone, shouldn't be much longer.
