### ISSUE TITLE
Army of Dark Compliance - Not working

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#671]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Army of dark compliance not working correctly. I select the option and nothing happens.

**Comment by zopha** [comment]
Yes, this rite needs to be reimplemented - #473 is setup to deal with this.

It's not an easy one as selections for force org slots can come from cults and miliitia and still be the same force org. We're updting the standard Astarte units first so all the base units are correct, once that's complete we'll be moving on to each legion and their rites of war. This one will take some time to implement on it's own but the 40k catalogues are doing something similar for FoC so we'll be able to copy their methods.
