### ISSUE TITLE
Bug Report - Legion Attack Bike Squad

### ISSUE THREAD

**Issue by axs041** [BSData/horus-heresy#673]
Option for Melta Bombs missing since last update.

Option for Armour types available for some reason (although no selections are available in the armour submenu).

**Comment by zopha** [comment]
The armour type selections are for a Pariah power armour replacement when available so it shows up as if it had options. It needs a bit of work done when we get to Blackshields/Shattered Legions but it does the job for now.

Melta bombs re-added, the fix will be in the next update.

**Comment by zopha** [comment]
This was fixed in #674. I missed the # on the commit so it didn't auto-close this issue.
