### ISSUE TITLE
Chaplin - No Crozius Arcanum power weapon profile, Diabolist should not have access to a jump pack

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#676]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.10

**Platform:** Windows

**Dropbox:** No

**Description:** The Chaplain Consul selection should add a Crozius Arcanum power weapon to the wargear, but it does not.
A Diabolist Consul for Word Bearers cannot take a jump pack, but the option is still present.

**Comment by zopha** [comment]
Diabolist access to jump pack is correct according to the Legion army red book.

The consul HQ entry needs an overhaul, setting up a new weapon (power armour and terminator armour) for the Chaplin right now would cause more difficulty when we make changes so I'm not going to add the crozius at the moment.
