### ISSUE TITLE
ROW: Horror Cult

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#677]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.23

**Platform:** Android

**Dropbox:** No

**Description:** Good morning. The Horror Cult Rite of War is still not available for Traitor Night Lord selections.

**Comment by zopha** [comment]
- [ ] Night Raptors can be taken as Troops
- [ ] Any Squad may take Trophies of Judgement
- [ ] Any infantry squad may take a Kharybdis Assault claw as dedicated transport
- [ ] No fortifications
- [ ] Traitor
- [ ] Rule: Must declare a charge if there's a unit in range they can harm.

**Comment by zopha** [comment]
Rites are usually complicated things so they can require a good bit of work to implement. This was raised in #634 and is on the list of things to look at but I haven't gotten to it yet. It will be done but may take some time.

**Comment by zopha** [comment]
Most of this is in, it was just set to Loyalist only.. Need to restrict fortifications but none are in at the moment so that's working right now.

**Comment by capitaladot** [comment]
@zopha good to close?

**Comment by alphalas** [comment]
Unless you implemented the fort limits that still needs to be done

**Comment by alphalas** [comment]
We could probably just make 2 new bugreps, one for LoW restrictions in rites, one for Fort restrictions in rites - we might close six others that way

**Comment by capitaladot** [comment]
I think that may make sense; I imagine there are quite a few to check.

**Comment by alphalas** [comment]
rolled into #863
