### ISSUE TITLE
Preator/Delegatus Legion command squads have lost their option to upgrade with Jump Packs, Jetbikes or Bikes 

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#679]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.23

**Platform:** Android

**Dropbox:** Yes

**Description:** Legion command squads have lost their option to upgrade with Jump Packs, Jetbikes or Bikes when the Preator is upgraded with those options. This was working in v207, and not in v208.

**Comment by XionXxen** [comment]
Hi, never used git hub bug reporting before. How do I know what released version the fix is included in? It doesn't work still in v209.
