### ISSUE TITLE
Seeker squads can only add one combi-weapon

### ISSUE THREAD

**Issue by zopha** [BSData/horus-heresy#682]
Seeker squad combi weapon selections only have a tick box. No options for more.

**Comment by Morturg** [comment]
are you guys, or rather just zopha now using a chat client to discuss stuff?

**Comment by zopha** [comment]
@Morturg I tend to talk to myself a bit on the gitter channel, that's about the extent of chat at the moment.

https://gitter.im/BSData/horus-heresy Drop in! :)

Otherwise I'm finding issues reported on battlescribe threads (and talking to people a bit) that are

http://heresy30k.invisionzone.com/index.php?/topic/6919-battlescribe-catalogues-horus-heresy-list-building/page-10
http://www.bolterandchainsword.com/topic/326330-30k-battlecribe-repository/page-40
