### ISSUE TITLE
RoW - Armoured Breakthrough 

### ISSUE THREAD

**Issue by zopha** [BSData/horus-heresy#683]
- [x] Unable to select Sicaran or Predator as Master of Armor selection 
- [x] Master of Armour granted company command vehicle for 0 points 
- [x] Master of Armour granted BS5
- [x] Predator troop choices need to be restricted so they can only take a predator cannon
- [x] Predator troop choices need to be restricted so they cannot only add sponson weapons, not pintle, hunter killer, etc
~~- [ ] No forts or immobile units~~Impossible
~~- [ ] Must not have more skimmers or flyer than it has tanks~~ Impossible

**Comment by capitaladot** [comment]
@zopha updated the checklist a bit.

**Comment by zopha** [comment]
Thanks! Should be able to set up Master of Armor from the v6 files fairly easily but it might have to wait for the other to finish Space Wolf additions to avoid merge conflicts.
