### ISSUE TITLE
Re: Bug Report - Legion Attack Bike Squad

### ISSUE THREAD

**Issue by axs041** [BSData/horus-heresy#685]
Thanks for re-adding Melta Bombs to the unit, one small error remains on the cost. The cost now seems to be 5 + 5per model totalling 30 for a 5 man squad. Double checked it should just be 5pts each.

Thanks for Malcador Demo Cannon and Schrapnel Bolts too.

**Comment by zopha** [comment]
Thanks for the bug reports. This will be fixed in the next release, should be fairly soon.
