### ISSUE TITLE
Militia missing fortifications

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#690]
**File:** (HH) Imperialis Militia and Cults Army List.catz

**BattleScribe version:** 2.00.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The militia list doesn't seem to be able to add in fortifications, such as the Aegis Defense Line. I've added another detachment and then used the option to turn it into a fortification detachment, but no fortifications are there to select.

**Comment by zopha** [comment]
Work is being carried out to setup fortifications for all armies. I'll be using #529 to keep track of it so I'll close this one off for now and update that call as I make progress.
