### ISSUE TITLE
Legion Seeker Squad Combi Weapon

### ISSUE THREAD

**Issue by thebiggeordiegeek** [BSData/horus-heresy#691]
Members of a Legion Seeker Swuad can replace their bolters with a Combi Weapon for 10pts each, currently only 1 can replace their weapon for 5 points.

**Comment by zopha** [comment]
Can you delete/refresh your data and see if that fixes it? That fix should have been in the last release from #682

**Comment by thebiggeordiegeek** [comment]
Yeah that fixed it, sorry.
