### ISSUE TITLE
join request

### ISSUE THREAD

**Issue by alphalas** [BSData/horus-heresy#696]
yup i finally decided i didn't have enough of a lack of free time lol

**Comment by zopha** [comment]
Yay! More :D 

Are you interested in working on any particular armies?

Any tips/suggestions on how to get the catalogues in shape are appreciated :)

**Comment by alphalas** [comment]
i was thinking cults and astartes - my primaries are BA and the army :P

**Comment by capitaladot** [comment]
+1

**Comment by amis92** [comment]
@capitaladot on the occasion, please accept my congratulations, you've been promoted as a team maintainer :D Less work for me, hehe ;)
