### ISSUE TITLE
LoWs Missing - CAL

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#699]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.24

**Platform:** Android

**Dropbox:** No

**Description:** cannot add any of the baneblade variants from the low as they are not there

**Comment by alphalas** [comment]
first half was dupe of #483

**Comment by alphalas** [comment]
second half dupe of #528
