### ISSUE TITLE
Horus cannot take Veteran squads a troops when used as a LoW

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#701]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.00.24

**Platform:** Android

**Dropbox:** No

**Description:** Horus allows veteran squads to be taken as troops in a force where he is the warlord.

however, the option does not become available when he is chosen as a lord of war.

**Comment by zopha** [comment]
This will be fixed in the next release due to the major force org update implemented by Alphalas. No other modifications needed.
