### ISSUE TITLE
Profiles not showing

### ISSUE THREAD

**Issue by MrRta1910** [BSData/horus-heresy#702]
The profiles are not showing up 
![screenshot_2017-02-05-11-20-15](https://cloud.githubusercontent.com/assets/7269431/22622695/084b48fe-eb96-11e6-97bb-e74a2670b213.png)

**Comment by zopha** [comment]
This is going to be a battlescribe bug. Can you check if low memory mode is enabled? 

It's at the bottom of the options list

*[Imgur](http://i.imgur.com/1QtyMCRm.png)

**Comment by MrRta1910** [comment]
It is already off should I report it to battle scribe

**Comment by zopha** [comment]
@MrRta1910 sorry, I was mesmerised by the weekender releases.

You could try clearing out your data files and refreshing. You can delete data from the menu in Manage Data. Take a look at this: https://battlescribe.net/?faq=refreshData

I haven't come across this bug much so I'm not sure what else you can try to fix it :(

**Comment by MrRta1910** [comment]
You can close the file zopha
