### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by kabuumu** [BSData/horus-heresy#704]
I'd like to work on the SW stuff.

**Comment by zopha** [comment]
Talked to kabuumu on gitter about this

:+1:

**Comment by capitaladot** [comment]
+1

**Comment by amis92** [comment]
Hello, @kabuumu. Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Also join our team in Gitter chat room (GitHub login): [![Join the chat at https://gitter.im/BSData/horus-heresy](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/BSData/horus-heresy?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

Cheers!
