### ISSUE TITLE
Legion Sicaran - Remove Assault cannon option

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#705]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** For the Blood Angel legion as per book 6, any "heavy flamer" can be exchanged for a Iliastus pattern assault cannon. The following options need to be changed, side sponsons for Sicaran battle tank variants as of right now have the option for the Iliastus pattern assault cannons and they should not as they are not allowed heavy flames. Contemptors only have the option to take 1 Iliastus pattern assault cannon but since it can take 2 heavy flamers it should be able to take 2.
Thanks and I hope this gets resolved quick.

**Comment by zopha** [comment]
The Contemptor issue should be fixed. Please clear your data files and get battlescribe to pull in refreshed ones. Instructions for this are available here: https://battlescribe.net/?faq=refreshData

The Sicaran will be updated in one of the next releases.

We're getting most of the generic options sorted out first and will be doing a legion by legion review later, if there are any specific units with issues just reply to this issue (or create a new one) to highlight them and we can make the changes.

**Comment by alphalas** [comment]
Sicarans can take HF - but only in salamanders ;)
