### ISSUE TITLE
New Legion/Addition - Thousand Sons

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#729]
LA - Thousand Sons:
Warlord must be ML1+ Psyker and highest LD score
- [x] added
All psykic disciplines, save malefic
- [x] added
Any HQ may be upgraded to ML1 for 20pts, may exchange a power weapon with force weapon
- [x] added
- [x] Constraints Implemented
Cult Arcana - add table options to units with rule
- [x] added
- [x] Constraints Implemented
Compulsory troops must use same cult as warlord/compulsory HQ
- [x] added

- [x] Add text regarding psykic disciplines and cult and manifesting on 3+
- [x] Add text for signs and portents
- [x] Sekmet 
- [x] Ammitara
- [x] Khenetai
- [x] Ahzek Ahriman
- [x] Amon
- [x] Magnus
- [x] Osiron - any contemptor upgrade 50pts; PP ML1 (tele's, Pyro, Div); Adamantium Will; starts with Dread Force Blade w/ combi w/ asphyx
- [x] Castellax-Achea
- [x] Praetor- must purchase 1-3 ML for 25pts - upgrade PW to FW for 5pt
- [x] Vet Tac/Terminators- upgraded to BoP ML1 for 25pts
- [x] Arcane litanies

Aether-fire cannon
- [x] added
- [x] Constraints Implemented

Asphyx shells; ICs 10pts, combi/pistol/boltgun; Term/Vets 20pts; Rotor cannon Support squads 25pts
- [x] added
- [x] Constraints Implemented

RITES:

Axis of dissolution: add text; troops must be max size, no more tanks or flyers then infantry units
- [x] added
- [x] Constraints Implemented

Guard of Crimson King: add text; sekhmet become compulsory, Magnus may be HQ; warlord must be Ahriman, Magnus, or ML3 Praetor; no more vehicles then LA; no forts or allied
- [x] added
- [x] Constraints Implemented

**Comment by alphalas** [comment]
They're on the list - if someone doesn't get to it before I do I'll put them in after I'm done talons

**Comment by capitaladot** [comment]
@alphalas planning to put your hit list in here?

**Comment by alphalas** [comment]
I will yes - patience ;p
