### ISSUE TITLE
Rite of War available for Allies

### ISSUE THREAD

**Issue by zopha** [BSData/horus-heresy#740]
Using Rites of War with allies. Rites of war are applied to all detachments regardless of which selected them, and it only recognizes a limit of 1 in use despite the ability to run RoW on allies using a praetor with sufficient points.

**Comment by zopha** [comment]
Have to cover this in a rite of war review as it's quite broad in scope.

**Comment by alphalas** [comment]
AFAIK, rites only apply per detachment, so a allied detachment can take a completely separate Rite due to having to be a different Legion.

**Comment by alphalas** [comment]
![img_0394](https://cloud.githubusercontent.com/assets/15703066/23332409/2e352b1e-fb47-11e6-8f2e-e5d1422dcac6.PNG)
As I was saying, Rites do not apply to allied detachments, Also, Allied detachments can have their own rite - as long as your army is 2k points or more.
