### ISSUE TITLE
Compulsory Battlefield Role Unit requirement implementation.

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#751]
This applied to many of the Consul types, as well as special characters like Kades Nex (and probably others in Legions I am less familiar with).

**Comment by alphalas** [comment]
![image](https://cloud.githubusercontent.com/assets/15703066/23099092/e154f848-f62c-11e6-8f2b-203bb32f8de3.png)
![image](https://cloud.githubusercontent.com/assets/15703066/23099100/ed4a3d0c-f62c-11e6-9acf-4011db7eb8b9.png)
offered as options to solution.

**Comment by capitaladot** [comment]
Love it.

**Comment by alphalas** [comment]
what's nice is this *SHOULD* work for troops too - so simplify Support squads.

**Comment by alphalas** [comment]
Just in case anyone is following this thread, the next update of BS *should* make implementing parts of this much easier.

**Comment by zopha** [comment]
What's being added?

**Comment by capitaladot** [comment]
This has been started. Many sub-categories have been added, including Compulsory Troops and Compulsory HQs, and math to require these in the Age of Darkness FoC for Legiones Astartes. These will need to be implemented where relevant for Mechanicum and Solar Auxilla.

**Comment by capitaladot** [comment]
Implementing it will involve copying and pasting the FoCs from LA to the other files.

**Comment by capitaladot** [comment]
This is implemented.
