### ISSUE TITLE
Talons QA

### ISSUE THREAD

**Issue by Kohato** [BSData/horus-heresy#756]
- [x] No Upgrade to Tribune for the Shield captain - _detachment needs to be 2000pts+_
- [x] Excruciatus Cadre - Silent Judge - 10 point cost on the power weapon, brings the squad cost up to 110
- [x] Fanatic Discipline rule is incomplete (Ends with In addition, )
- [x] Valdor - Weapon is a Guardian Spear but is called The Apollonian Spear, the profile is the same as a Paragon Spear.
- [x] Shield Captain - Paragon spear shows guardian blade profile
Contemptor-Achillius
- [x] Missing - Extra Armour, Smoke Launcher, Searchlight, Refactor Field, Fleet, Move through Cover, Counter-attack
No book references for 
- [x] Assault Needler
- [x] Needle Pistol
- [x] Psyk-out Grenades
- [x] Arae-Shrikes
White dwarf reference
- [x] Guardian Spear
- [x] Inviolable Psyche
- [x] Hail of Fire
- [x] Praesidium shield
- [x] Hetaeron Guard - Master-crafted power sword should be master-crafted power weapon.
- [x] Custodian Guard - Master-crafted power sword should be master-crafted power weapon.
- [x] Oblivion Knights - Power axe should cost 5pts each.
- [x] Agamatus Jetbikes - Power lance should be free.
- [x] Seeker Cadre - Default unit should cost 85pts.
- [x] Seeker Cadre - Should be able to take Kharon Pattern Acquisitor as dedicated transport.

**Comment by Kohato** [comment]
@alphalas I can't assign you as i'm not part of this repo it seems.

**Comment by zopha** [comment]
Testing on android tablet with v62 of the file.

Coronus Grav-carrier appearing in uncategorised (but not on the desktop client)
Kharon Pattern Acquisitor appearing in uncategorised (but not on the desktop client)
No Upgrade to Tribune for the Shield captain
Excruciatus Cadre - The option to add more Questora is available but the squad is already at max.
Compression Tanks - no text for rule
Psykic Anathema - no text for rule
Ex Oblivio - no text for rule

**Comment by GenWilhelm** [comment]
- [ ] Shield Captian - Archaetech pistol should cost 20pts.
- [ ] Shield Captian - Paesidium shield should cost 20pts.
- [ ] Shield Captian - Tribune upgrade should be limited to 1 in roster.
- [ ] Excruciatus Cadre - Questora power weapon should cost 10pts. (Currently being double charged?)
- [ ] Excruciatus Cadre - Adrathic destructor should cost 15pts.
- [ ] Hetaeron Guard - Master-crafted power sword should be master-crafted power weapon.
- [ ] Custodian Guard - Master-crafted power sword should be master-crafted power weapon.
- [ ] Oblivion Knights - Power axe should cost 5pts each.
- [ ] Oblivion Knights - Should be able to take Kharon Pattern Acquisitor as dedicated transport.
- [ ] Sentinel Guard - Should cost 65pts each.
- [ ] Prosecutors - Special equipment should cost 10pts each.
- [ ] Prosecutors - Should be able to take Kharon Pattern Acquisitor as dedicated transport.
- [ ] Vigilators - Breaching charge should cost 10pts.
- [ ] Vigilators - Should be able to take Kharon Pattern Acquisitor as dedicated transport.
- [ ] Coronus Grav-Carrier - Should be able to take armoured ceramite.
- [ ] Kharon Pattern Acquisitor - Should be able to take armoured ceramite.
- [ ] Agamatus Jetbikes - Power lance should be free.
- [ ] Seeker Cadre - Default unit should cost 85pts.
- [ ] Seeker Cadre - Seeker with breaching charge should cost 20pts total.
- [ ] Seeker Cadre - Should be able to take Kharon Pattern Acquisitor as dedicated transport.
