### ISSUE TITLE
Aether rune armour for SQ and Frost blade options for HQ's

### ISSUE THREAD

**Issue by zopha** [BSData/horus-heresy#764]
For the Wolves, only Priests are showing Aether rune armor, and no HQs have the frost blade/greater frost blade options

From http://www.bolterandchainsword.com/topic/326330-30k-battlecribe-repository/?p=4660495

**Comment by zopha** [comment]
It looks like only the Preator gets options for the Aether rune armour.

The frost options are for IC's that can take power weapons so might take a bit more work to implement.

**Comment by alphalas** [comment]
rolled into #844
