### ISSUE TITLE
Mechanicum Taghmata v37 Matrix of Ruin no force org.

### ISSUE THREAD

**Issue by ThomasBroom** [BSData/horus-heresy#767]
In the Matrix of Ruin force for Taghmata v37 all units are listed under "uncatagorized" rather than splot by force org slot.

**Comment by zopha** [comment]
That will be fixed shortly whenever appspot picks up this release, hopefully within the next few hours.

https://github.com/BSData/horus-heresy/releases/tag/v8.2.3

More work needs to be done for the restrictions to work in BS but you should be able to us it as it is, just have to follow the restrictions manually until I get the rest implemented.

**Comment by zopha** [comment]
Forgot to say I'll be tracking the progress in #553 so I'm going to close this issue.

Next step is to make a check list of what's required for the Reductor and then work my way through it.
