### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by Kohato** [BSData/horus-heresy#769]
@alphalas told me to. Blame him for this. Let me in. It's cold and heretical out here.

**Comment by capitaladot** [comment]
+1

**Comment by zopha** [comment]
Done. Welcome to Heresy land, Forgeworld rules as far as the eye can see.

**Comment by capitaladot** [comment]
Repo owner has to handle these.

**Comment by Kohato** [comment]
O.o. Zopha definately added me - I can upload to master now.

**Comment by alphalas** [comment]
Really? Cool

**Comment by capitaladot** [comment]
Oh! That is new.

**Comment by amis92** [comment]
Yeah, I've promoted him to Team Maintainer, he can now add current organization members to HH team - as far as this request goes, Kohato was already org member so all is good. :)
