### ISSUE TITLE
Legiones Astartes: Crusaders || Standard Weaponry on units

### ISSUE THREAD

**Issue by Kangodo** [BSData/horus-heresy#77]
Hello, thank you for all your work.
As a 40k author I have something of a suggestion.

Let's take Legion Tactical Support Squad as example.
They have an entry-group that allows them to exchange Flamers for several weapons.
But there is no entry or profile for the Flamers.
Wouldn't it be better to change the entry-group to a min/max of 1/1, add a Flamer-entry (with profile) and set that as standard selection?

Same for the Legion Tactical Squad, I would make a min/max of 1/1 with the following entries:
>Bolters
>Chainsword/Combat Blade
>Bolters and Chainsword/Combat Blade

Or the Mortis Dreadnought, which can exchange TL heavy Bolters which he technically doesn't have according to BattleScribe ;)

I also noticed that Legion II is missing! (Sorry, couldn't resist)

**Comment by Millicant** [comment]
Hey Kangodo,

Thanks for the input!  I actually chose this method rather specifically, to diverge a little bit from my past 40k catalogues where I worked very hard to do exactly what you describe.  I understand your reasoning - the units show up in the roster with all their wargear under the unit profile, yielding a slightly more "complete" roster list output.  

However, with the Horus Heresy catalogues I chose to write it as close as possible to the entries in the respective books, while still accounting for usability.  In some places, especially the parts I wrote at the very beginning (I'm looking at you Tactical squad), this produces some strangely worded options.  

Now that they are finished, I may end up going back and adjusting some of the entries as you describe.  I'll have to think on it, but more importantly, explore all the units that would be affected.  I'm not sure yet, as this would open a rather large drum of worms that I'm necessarily willing to take on.  

Sorry about the II Legion, but something tells me they won't be getting any rules... ;)
