### ISSUE TITLE
Legiones Astartes: Legion Command Squad: Bolter exchange

### ISSUE THREAD

**Issue by battlebrother** [BSData/horus-heresy#78]
Hi good folks:
Just got my hopes up that my LCS could take combi-weapons after seeing the option in Battlescribe, however on checking LA:CAL the option should be for combi-bolters instead.
The option and points cost are correct (10 for a combi-bolter to replace a bolter? I think not!), it's just the name that needs amending from combi-weapon to combi-bolter.
Thanks! Chris

**Comment by Millicant** [comment]
Nice catch.  Thanks for sharing!
