### ISSUE TITLE
Book 7 - Space Wolves

### ISSUE THREAD

**Issue by zopha** [BSData/horus-heresy#787]
Just want to keep track of what's done and what's left to be done with these guys 
----
- [ ] Legion restrictions
  - [ ]   Compulsory HQ from Praetor (Wolf Lord) or Centurion (Claw Leader) only
  - [ ]   1 Compulsory HQ per 1,000 points
  - [x]   No Access to Chaplin, Librarian or Primus Medicae
  - [ ]   Compulsory Troops - Grey Slayers only
----
- [ ] Rites of War
  - [ ] The Pale Hunters
    - [ ] All infantry units except for those in Terminator armour gain Hit & Run (with 1D6 modified to 3D6)
    - [ ] limited to 1 Heavy Support choice 
    - [ ] No Artillery
    - [ ] No Drop Pods
    - [ ] No Fortifications

  - [ ] The Bloodied Claws
    - [ ] Grey Slayers and Assault Squads gain Furious Assualt
    - [ ] No Immobile units
    - [ ] No Slow and Purposeful units
    - [ ] No Allied Space marines
----
- [ ] Legion Units
  - [ ] Priest of Fenris
    - [x] Needs Frost weapon options (Any IC can swap their power weapon for one with extra costs)
    - [x] Speaker of the Dead
    - [x] Caster of Runes
  - [x] Grey Slayers
    - [x] Grey slayers don't count the huscarl in the model count for the restricted items. If a squad of 20 take 4 power fists they get a validation error.
    - [x] Grey Slayer Huscarl has a validation error when selecting a close combat weapon. "Huscarl cannot have any selections of Exchange close combat weapon for: (hidden)
  - [x] The Deathsworn
  - [x] Varagyr Terminators
  - [x] Geigor Fell-hand
    - [x] Update profile to show 5++ from Refractor Field
  - [x] Hvarl Red-blade
    - [x] Update profile to show 4++ from Iron Halo
  - [x] Priest of Iron
    - [x] May take Aether or Artificer armour
    - [ ] Forge Lord may take Cyberwolves
    - [ ] Praevian may give Automata Counter-Attack for x points
  - [x] Leman Russ
  - [x] Wolf-kin of Russ
----
- [x] Legion Wargear/Misc	
  - [ ] Fenrisian Wolf - up to 2 for any Praetor/Centurion not equipped with a jump pack	
  - [x] Frost Blades	Any IC with a power weapon may exchange it for a frost weapon for x points
    - [x] Frost Blade
    - [x] Frost Axe
    - [x] Frost Claw
    - [x] Great Frost Blade
  - [x] Aether Rune Armour - Any Praetor/Priest of Fenris may exchange Artificer armour for x points

**Comment by capitaladot** [comment]
I looked into "No Fortifications" and see no way to implement that without a huge refactor of the whole game system.

**Comment by alphalas** [comment]
That's actually easy.  Remove all the links in the GST, then just add the links to fortifications in each cat, and then constrain them there

**Comment by meatlaser** [comment]
Wolf priests need a terminator option as well

**Comment by alphalas** [comment]
bumping to top
