### ISSUE TITLE
Terminator Command Squad 

### ISSUE THREAD

**Issue by HydraulicGold2** [BSData/horus-heresy#791]
Terminator Command Squad appears as same cost as regular command Squad, when it should be 15pts per model extra over the cost of a regular Command Squad. So base Squad should be 120pts, not 75. 

At least it was mispriced from the bubble list under the Primarch Perturabo's entry

**Comment by HydraulicGold2** [comment]
This is for Android devices if that makes any difference

**Comment by capitaladot** [comment]
There are sadly many copies of this.

**Comment by alphalas** [comment]
They should however all be linked to the same unit so it should only require fixing one unit

**Comment by capitaladot** [comment]
Have they been consolidated? I hope so, but there were previously many
copies.

**Comment by alphalas** [comment]
I believe so that was one of the things that @zopha and I were working on

**Comment by capitaladot** [comment]
Sweet!

**Comment by zopha** [comment]
Yeah, they've mostly been migrated over to a shared entry. A bit more work and I think they could all be one shared group.

Looks like this is on the Shared entry so it's going to be wrong for most of the others.

**Comment by capitaladot** [comment]
Closing this per @zopha's commit.

**Comment by zopha** [comment]
Reopening as this commit was waiting for a review with the Praetor changes and had merge conflicts from the AoDC fixes that got in before this was merged.
