### ISSUE TITLE
Perturabo Breaks Tactical Squads 

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#792]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.00.26

**Platform:** Android

**Dropbox:** No

**Description:** Pride of the Legion RoW sets max value of Tactical Squads to 0, when you can still field them, as long as you fill Compulsory slots with Terminators or Veteran Tacticals

**Comment by HydraulicGold2** [comment]
Correction to this. Adding the Primarch Perturabo to a list is the source of the limit on Tacticals, not the RoW

**Comment by zopha** [comment]
@HydraulicGold2 Can you post a screenshot if you can get one? I've been trying to replicate this and the error I'm seeing is that compulsory troop selection/validation isn't being enforced.

**Comment by HydraulicGold2** [comment]
I have included 3 Screenshots. 1 of the error message, 1 that shows
Perturabo still in the list with the error notice, and 1 that shows the
error message is gone, with the only change being Perturabo's entry is gone

**Comment by HydraulicGold2** [comment]
Or at least I tried to...

**Comment by zopha** [comment]
Try sticking them on http://imgur.com/ and pasting the link for each one or the album they're in.

**Comment by HydraulicGold2** [comment]
http://imgur.com/a/0a5Dq

**Comment by zopha** [comment]
Ah, first thing to do is update your files. The legion file is up to v252 now. Appspot is still having some issuese so if the auto update doesn't work you can download the file from here https://github.com/BSData/horus-heresy/archive/master.zip

That zip will always have the most up to date files. Just browse to your battle scribe data folder, delete the contents of the 30k folder ( make a backup first!) And then copy the contents of the zip file in to that folder.

**Comment by HydraulicGold2** [comment]
Tried that. Still says v251

**Comment by zopha** [comment]
Sorry, this head cold must be affecting my concentration. I pushed a release last night with LA v252, can you update to that and see if it resolves this for you. I haven't seen able to replicated the validation error with 252.

**Comment by HydraulicGold2** [comment]
So I further narrowed it down to only if Perturabo has the After Istvaan 35pt upgrade

**Comment by zopha** [comment]
Ah, I see that error now. Thanks for finding it!

![2017-03-06 18_59_16-data editor 2 00 14 - legiones astartes_ age of darkness army list](https://cloud.githubusercontent.com/assets/1666415/23625318/a8bb912e-02a0-11e7-92ce-d200e9a9889c.png)

These are the constraints on the tactical squad causing the issue. I've no idea why they're pointing at his After Istvaan rule.
