### ISSUE TITLE
Shared Entries for Armour Should Modify Profiles 

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#795]
Armour and Invuln Saves should be set by wargear.
- [ ] Cataphractii Terminator Armor
- [ ] Tartaros Terminator Armor
- [ ] (Generic/Indomitus/unspecified) Terminator Armor
- [ ] Artificer Armor  
- [ ] Refractor Field
- [ ] Iron Halo
- [ ] Combat Shield
- [ ] Boarding Shield
- [ ] ... that wargear item IH and Mech can take that boosts invuln by 1

**Comment by alphalas** [comment]
Agreed -  that's a lot of things that need modified though.

**Comment by zopha** [comment]
Quite a few things, this would be easier to track on a per unit basis.

**Comment by capitaladot** [comment]
@zopha As this is really only relevant for Character upgrades (spare Terminator squads that don't specify armor type), could not just the shared entry modify the parent profile?

**Comment by capitaladot** [comment]
Further, these modifiers could be copy-pasta'd in with a text editor to avoid tons of typing.

**Comment by alphalas** [comment]
there is no actual Invuln stat to be modified. otherwise, Cents now have 4+ and 2+ modifiers.
