### ISSUE TITLE
RoW: Zone Mortalis Assualt Force

### ISSUE THREAD

**Issue by zopha** [BSData/horus-heresy#798]
They should only have it in ZM and if the ZM Assault Force rite of war is selected.

Reported by @Morturg in gitter

[edit]May as well turn this into a RoW implementation issue and get it setup.

- [x] Restrict ZM Assault Force Rite to only appear when a ZM Force Org is selected
- [ ] Restrict Teleport Assualt to only appear when ZM Assualt Force Rite is selected

- [ ] Units limited to 15 marines at most. List goes here -

**Comment by capitaladot** [comment]
We no longer have Force Orgs, right?

**Comment by alphalas** [comment]
We still do, it's just a separate detachment now.

**Comment by zopha** [comment]
There may be some extra requirements for this rite, I haven't been able to go back and review it. The limit on squad size seems easy enought but I was going to leave this until after unit optimisation.

**Comment by cowomo404** [comment]
Just a note. You **can** use the Zone Mortalis Right of War while using a force org chart other than Zone Mortalis - Attacker, Defender or Combatant' though, some benefits/limitations may not apply (e.g. Interlocking Defence).
_Zone Mortalis_ Right of War **is** available for Age of Darkness games. (per LA:AODAL) 

![screen shot 2017-04-01 at 05 12 08](https://cloud.githubusercontent.com/assets/13860904/24577896/3a0fc10e-169c-11e7-9f57-498838580a1d.jpg)

**Comment by alphalas** [comment]
rolled into #863
