### ISSUE TITLE
Legion Tactical Sergeant missing weapon options

### ISSUE THREAD

**Issue by zopha** [BSData/horus-heresy#806]
Legion tactical Sgt can only exchange their bolter for other weapon options. The AoDAL book has the entry as "Sgt may exchange their bolter AND/OR their chainsword for one of the following:" 

http://www.bolterandchainsword.com/topic/326330-30k-battlecribe-repository/?p=4667889

**Comment by kabuumu** [comment]
I think this is already fixed. Just tested it and it's worked fine. You have to have a chainsword to be bale to swap it though.

**Comment by capitaladot** [comment]
Good to close, @kabuumu ?

**Comment by zopha** [comment]
Yeap, it's there. I just didn't look enough.
