### ISSUE TITLE
Add Codex Daemons

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#809]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.00.26

**Platform:** Android

**Dropbox:** Yes

**Description:** Greetings,

Just a request to add in Deamon information for the Horus Heresy as they can be taken as allies with Word Bearers.

**Comment by zopha** [comment]
If you have time please review the daemon catalogue under

https://github.com/BSData/horus-heresy/tree/Daemons

and let us know if it's working and if the entries are accurate. It's an old catalogue but no one has had time to check it out to review it. We also have this logged under #493

**Comment by zopha** [comment]
Closing this off as it's a duplicate. If we can get some reviewers on to the Daemons branch we can verify it's working.
