### ISSUE TITLE
Profile updates

### ISSUE THREAD

**Issue by Tomakokamikaze** [BSData/horus-heresy#829]
- [x] Sicaran Battle tank accelerator autocannon is Twin-Linked.

- [x] Legion Tactical Support Squad has a bug = after chosing to take aditiional chainblades it says you must choose a replacement for it on your sargeant.

**Comment by Tomakokamikaze** [comment]
wish i could do the alterations myself, if someone could show me how I would be willing to try.

**Comment by alphalas** [comment]
Actually, a lot of these issues are going to go away as soon as @kohato finishes doing a complete rewrite of the CAL

**Comment by zopha** [comment]
Fixed/update
>First, the Sicaran Battle tank doesn't inform his accelerator autocannon is Twin-Linked.
The profile in the books doesn't say it has twin-linked.

>Legion Reconnaissance Squad are missing the profiles for sniper rifles and other weapons
Updated now but the Sergeant needs more work.

>Dynat is missing his hammerhead strike rule
Added now and updated his entry with missing wargear.

>Sabotour is missing his camelioline. also his Lone Killer rule is different from the one that Exodus uses.
Added Camelioline and updated the Lone Killer rule for the Sabotour.

>Also Venon Spheres are missing for Alpharius and Headhunter Killteams
Added
------
Comments
>The Rewards of Treason also need to be updated, both its units and their gear and adding of the thousand sons and Vyka Fenrica units.
That's covers quite a few units, does rewards of Treason work on any units at the moment? It would be best to do a seperate review for this Rite of war. That's really the case for most rites as they can impact a large number of units..

>Legion Tactical Support Squad has a bug = after choosing to take additional chainblades it says you must choose a replacement for it on your sergeant.
Haven't looked at this yet. 

>Contemptor Cortus (and probably other contemptors) missing the profile for chainfist and dread ccw.
Covered in #597, it'll be worked on.

>As for the Alpha Legion all its characters and special units need to be updated to display their weapons and gear. I can go into further detail if necessary.
They'll be mostly done for the next release.

**Comment by Tomakokamikaze** [comment]
> The profile in the books doesn't say it has twin-linked.

it says it is twin linked in the tank profile (not in the weapon profile)
![sicaran](https://cloud.githubusercontent.com/assets/21247755/24145670/fb719f3c-0e10-11e7-8869-771ed75105ab.jpg)

**Comment by Tomakokamikaze** [comment]
and I hate to bring this up here, but shouldnt named characters be able to take legion wargear? like venom spheres, power daggers and banestrike ammunition?

**Comment by alphalas** [comment]
That is a discussion for Gitter- join us there

**Comment by capitaladot** [comment]
Missing rules are bugs.

**Comment by capitaladot** [comment]
@Tomakokamikaze yes, as there is no rule in 7th edition (nor since like 4th) disallowing named characters from taking options that are provided to all Legiones Astartes in a Legion or all Characters or all Independent Characters with Legiones Astartes within a Legion.

**Comment by capitaladot** [comment]
@Tomakokamikaze a twin-linked version of a weapon is a variation on the same weapon, only in number. following the twin-linked rule. It is indeed the same weapon; entries listing profiles for twin or quad-linked weapons with different profiles are situational changes to a given weapon and overrides of how a given weapon performs in that configuration, not discrete weapons. 
All of this boils down to any option allowing a replacement of a type of weapon with another type (e.g. Blood Angels assault cannons) applying to twin and quad linked variations, except where specifically prohibited.
