### ISSUE TITLE
Reaver Titan - points cost wrong

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#833]
**File:** (HH) Mechanicum - Taghmata Army List.catz

**BattleScribe version:** 2.00.29

**Platform:** Android

**Dropbox:** No

**Description:** Reaver Battle Titan should cost 1475 not 1450, as per Mechanicum Taghmata Red Book

**Comment by HydraulicGold2** [comment]
Seems to be the same for the Crusade Army List version
