### ISSUE TITLE
Priest of Fenris missing Terminator Armour

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#834]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.00.29

**Platform:** Android

**Dropbox:** Yes

**Description:** -Wolf Priests missing Terminator Armor options 

-Moritat missing second bolt gun swap option (They get another bolt gun in their gear so can switch out both to other guns + that means then can also have a melee weapon as well)

**Comment by zopha** [comment]
Needs more than just the armour entry added as the armour enables access to the weapon list for a terminator-equiped centurion.

**Comment by alphalas** [comment]
rolled int #844
