### ISSUE TITLE
Breacher Siege Squad - Points cost wrong

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#835]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.15

**Platform:** Windows

**Dropbox:** No

**Description:** Legion Breacher Siege Squad costs 190pts
Should cost 200pts

**Comment by IronMaster87** [comment]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.15

**Platform:** Windows

**Dropbox:** No

**Description:** Techmarine Servitors; option for missile launchers and rad missiles missing.
