### ISSUE TITLE
Centurion/Praetor Multi-Bug list

### ISSUE THREAD

**Issue by gungagreg** [BSData/horus-heresy#844]
- [x] Forge Lord - Bug with PA/AA option (AA still costs 10pts) - fixed in #887
- [x] Moritat - second pistol still bugged - fixed in #887
- [x] Diabolist needs gone over
- [x] Legion Champion (Covenant of Fire bug?)
- [x] Delegatus (no LoW allowed restriction)
- [x] Decapitation Strike - One Consul
- [ ] Check Primus Medicae and Vigilator for illegal options... 
    - [x] Lightning Claw(s)
        - [x] Raven's Talons
    - [x] Power fist
      - [x] Phoenix Spear (also typo)
      - [x] Power Scythe
        - [x] Potentially out of date profile... special rule changed in Age of Darkness: Legions
   ~~White Scars spear thing? (available for power fist eligible, or power weapon eligible?)~~
  - [x] Thunder hammer
  - [x] Boarding shield
- [ ] Check Forgelord for illegal options

**Comment by alphalas** [comment]
edited to remove SW options from list since they're listed in #787

**Comment by capitaladot** [comment]
Chameoline is also bugged on Raven Guard Centurions.

**Comment by capitaladot** [comment]
Two profiles show for Centurions, so the hiding condition is broken on the base Centurion profile.
