### ISSUE TITLE
Mechanicum: Taghmata Army List Cybernetica issue

### ISSUE THREAD

**Issue by orvCiklum** [BSData/horus-heresy#853]
Hello!
Here is the screenshot shows the restricts for building cybernetica roster and i believe they should be checked
![screen](https://cloud.githubusercontent.com/assets/20644972/24399134/6f740c00-13b4-11e7-8462-fc9c77a6b30d.jpg)

And it seems if you create Age of Darkness Taghmata Army List with **Legio: Cybernetica** option it seems army is creating as Onslaught detachment because it uses 1hq+1tropps+1heavy_support schema

**Comment by capitaladot** [comment]
Thanks, will fix.

**Comment by alphalas** [comment]
Unable to recreate the bug with Legio:Cybernetica.

**Comment by alphalas** [comment]
rolled into #868
