### ISSUE TITLE
Allied list "... must have x more selections of Y..." 

### ISSUE THREAD

**Issue by cowomo404** [BSData/horus-heresy#858]
I'm getting a weird and unexpected validation error which seems to be worse as the list get bigger. I'm not really sure if this is a math/logic issue or there is a rule some where I'm missing.

I have an Astartes army with Militia allies (2,500)

In the allies force I have a 

- Force commander w/ survivors of the dark age Provenance - **HQ**
- 2x units of grenadiers. - compulsory **Troop** (per Provenance)
- Sentinel scout squadron - **Fast**

AFAIK - allies formations must have 1 troop and can have up to 2.

When ever I add compulsory for the primary formation I start to receive a validation error that says I must have X more selections of Militia/Cult (minimum Y)
It seems the more troops I had in the primary detachment the more troops I must have in the allied force. Additionally the Minimum number seems to rise (even though the max really is 2.

Seems to be a math/logic bug - but I'm not 100%. Either way it isn't an expected behavior.
Working backwards:

Legal primary detachment (3 troops) - Allies requires 3 more + minimum of 7
![3-6](https://cloud.githubusercontent.com/assets/13860904/24577637/30250212-1697-11e7-9102-7157e25de37c.jpg)

Legal primary detachment (2 troops) - Allies requires 2 more + minimum of 6
![2-6](https://cloud.githubusercontent.com/assets/13860904/24577646/68a4fe6c-1697-11e7-8154-7110f6faf67c.jpg)

Not legal primary detachment (1 troops) - Allies requires 1 more + minimum of 5
![1-5](https://cloud.githubusercontent.com/assets/13860904/24577652/83d396a8-1697-11e7-9340-e17fb61e2d0c.jpg)

Not legal primary detachment (0 troops) - Allies good
![good](https://cloud.githubusercontent.com/assets/13860904/24577656/920ff4dc-1697-11e7-9a5c-2d09bdfbd7f9.jpg)

This doesn't make any sense to me... bug?

Using BattleScribe v2.00.15.72 (but errors show up on mobile (iOS) as well
Legiones Astartes: Age of Darkness Army List v257 (Age of Darkness)
Imperialis Militia and Cults Army List v41 (Allied Detachment)

**Comment by capitaladot** [comment]
We have discovered that this Rite of War was implemented with a major
misunderstanding, and Legiones Astartes was added to a large number of
units that should not have it.

**Comment by alphalas** [comment]
@capitolidot  that's more than just the LA applied to things that shouldn't have it – that shouldn't be happening at all unless he has AoDC selected.

OP, please purge and redownload all data - follow up if error continues or not please.

**Comment by cowomo404** [comment]
Not sure what "OP" means in the context of git, but I'll assume you were talking to me. Yes, I've tried removing and reloading with the current data and the issue persists.

**Comment by cowomo404** [comment]
Also @capitaladot I'm not using a right of war, so I'm not sure I understand  what you mean by the RoW was implemented incorrectly. The list has just 2 plain formations; 1 primary, 1 allied.

**Comment by alphalas** [comment]
He's referring to Armies of Dark Compliance- we had implemented it a few releases ago, and then realized we over-implemented. That's why you're seeing "must have more militia/cults" - but that should only trigger if you're using the AoDC detachment.
