### ISSUE TITLE
Dreadnought Drop pod pts

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#860]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.32

**Platform:** Android

**Dropbox:** No

**Description:** Pts price for legion drop pods are listed as 100 when buying a dedicated transport for a cortus class dreadnought when it should be 65.

**Comment by zopha** [comment]
A dreadnought droppod is 100 points. A Cortus gets access to a dreadnought drop pod as a dedicated transport, which costs 100 points, not a legion drop pod. Unless this is for a rite of war or some other modification?
