### ISSUE TITLE
Legion and RoW modifications made possible with multiple category selection

### ISSUE THREAD

**Issue by alphalas** [BSData/horus-heresy#863]
I Legion - Dark Angels

- [x] Ironwing Protocol
  - [x] Half the units must have the Tank type
  - [x] Dust of a Thousand Worlds to Tanks, allowing them to ignore the first failed Dangerous Terrain roll. 
  - [x] Goliaths of War - All Dreadnoughts have Fear and Tank hunter rules
  
- [x] Ravenwing
  - [x] Sky Hunter and Outriders are the only Troops choices available
  - [x] Only vehicles with Skimmer or Flyer type
  - [x] No Lords of War that aren't Flyer
  - [x] Independent Characters must have a Bike or Jetbike
  - [x] Scour the Land - Characters may take Rad Grenades for +5 points

----

III Legion - Emperors Children

- [x] 3rd Company Elite	
  - [x] Kakophoni squads as Troops and gain Relentless
  - [x] Any infantry with power armour or artificer armour may take Sonic Shriekers 2pts per model. There seem to be some places around the file where this was grant erroneously. Consolidate these all to the single shared entry.
  - [x] Traitor Only
  - [x] May not take a Space Marine Allied Detachment

- [x] The Maru Skara
  - [x] Must take a Legion Champion
  - [x] May not take a Fortification or Allied Space Marine Detachment
  - [x] May not take units with the Immobile, Heavy or Slow & Purposeful rules

----

IV Legion - Iron Warriors

- [x] Hammer of Olympia
  - [x] All Vehicles with the tank type and Walkers gain Extra Armour, no cost
  - [x] Siege Engineers: A primary detachment using this Rite of War may take an additional Heavy Support choice 
  - [x] MUST take either a Warsmith or Siege Breaker as its Compulsory HQ choice.
  - [x] MUST take more Heavy Support choices than Fast Attack choices.
  - [x] MUST take an additional Compulsory Troops choice
  - [x] May not take a Space Marine Allied Detachment

- [x] The Ironfire
  - [x] Must always be the Attacker where the distinction is made
  - [x] May not take a Fortification or Space Marine Allied Detachment

----

V Legion - White Scars

- [x] The Sagyar Mazan
  - [x] Must use a White Scars unit that has Master of the Legion and only in a Shattered Legions themed army.
  - [x] Loyalist Only
  - [x] May never contain more Vehicles than it has units with the Infantry type

- [x] The Chogorian Brotherhood	
  - [x] Skyhunter and Outrider squads count as troops choices and are scoring
  - [x] All models with Bike or Jetbike gain Hit & Run
  - [x] Any Infantry unit with No Heavy, Salvo or Ordnance weapons gains Hit & Run & Outflank
  - [x] Any Infantry unit with Heavy, Salvo or Ordnance weapons gains Outflank
  - [x] Warlord must be on a bike/jetbike
  - [x] All compulsory troops MUST be Skyhunters or Outriders 
  - [x] Not have more Fast Attack than Heavy

----

VI Legion - Space Wolves

- [x] Pale Hunters
  - [x] All infantry units except for those in Terminator armour gain Hit & Run (with 1D6 modified to 3D6) FIXED 06/07/21
  - [x] No Immobile units
  - [x] No Slow and Purposeful units
  - [x] No Artillery
  - [x] No Drop Pods
  - [x] Limited to 1 Heavy Support choice  FIXED 06/07/21
  - [x] No Allied Space marines

- [x] The Bloodied Claw
  - [x] All Grey Slayer and Assault Squads in this Detachment gain the Furious Assault special rule FIXED 06/07/21
  - [x] The Detachment gains the Howl of the Death Wolf special rule
  - [x] No Immobile units
  - [x] No Slow and Purposeful units
  - [x] No Artillery
  - [x] No Allied Space marines

----

VII Legion - Imperial Fists

- [x] Stone Gauntlet
  - [x] Phalanx Warders make be taken as troops
  - [x] Any model equipped with either a boarding shield or storm shield who is in unit coherency with at least two other models who also fit these criteria gains a +1 bonus to their Toughness  (MUST BE CHECKED BY PLAYER)
  - [x] Compulsory Troops choices must be made up of Legion Breacher squads.
  - [x] No models can deploy using Deep Strike (MUST BE CHECKED BY PLAYER)
  - [x] Cannot take more Elites and Fast Attack choices in total than Troop choices : Fixed  11/06/21
  - [x] 1 Consul selection only with the exception of Legion Champion

- [x] Hammerfall Strike Force
  - [x] Phalanx Warders make be taken as troops : Fixed  11/06/21
  - [x] Teleport transponders may be taken by any Infantry at 15pts per squad and 10pts for an IC
  - [x] May not include a Fortification or Allied Detachment
  - [x] Any vehicles taken in the army must begin the game held in Reserve (MUST BE CHECKED BY PLAYER)

----

VIII Legion - Night Lords

- [x] Terror Assault
  - [x] Terror Squads & Raptor are compulsory troops
  - [x] Tac Squads, Vet Tac Squads, and Terror squads may take Kharybdis Dreadclaw pods or Drop pods as DT
  - [x] 3+ Troops min
  - [x] max1 HS
  - [x] No Fort
  - [x] No Allied SM

----

IX Legion  - Blood Angels

- [x] Day of Revelation
  - [x] Compulsory HQ and Troops must have Jump Packs... (YIKES) FiXED 07/Sept/21
  - [x] Compulsory (1) Fast Attack must have Flyer or Deep Strike rule FiXED 07/Sept/21
  - [x] No Lords of War other than Flyers or Primarch Sanguinius
  - [x] No Forts
  - [x] No Sentry Guns

- [x] Day of Sorrows
  - no limitations in list building

----

X Legion - Iron Hands

- [x] The head of the Gorgon
  - [x] flamer may upgrade to graviton for +10pts, Blessed autosimulacra free on vehicles
  - [x] battle-automanta maniples as elites, units of 10 models or less that can take rhion may take LR Proteus/Phobos
  - [x] Max1 FA
  - [x] max1 Consul, except for Forge Lord
  - [x] no allies

- [x] Company of Bitter Iron
  - [x] Medusan Imortals are troops
  - [x] Hatred (Traitor) FiXED 07/Sept/21
  - [x] Loyalist
  - [x] No Allies
  - [x] No Manus

----

XII Legion - World Eaters

- [x] Beserker Assault
  - [x] +1 compulsory troop (3+ instead of 2+)
  - [x] no more tanks or flyers then units of infantry
  - [x] max1 consul, no lib
  - [x] No forts
  - [x] No SM allies

- [x] The Crimson Path
  - [x] No Immobile/Slow and Purposeful
  - [x] No Fort
  - [x] No SM Allied

----

XIII Legion - Ultramarines

- [x] The logos Lectora
  - [x] Must take either Master of Signal or Damocles in addition to compulsory hq
  - [x] +1 compulsory troop (3+ instead of 2+)
  - [x] no more tanks or flyers then units of infantry
  - [x] No Infiltrators or Deep Strikers FiXEDish 07/Sept/21 (resrtictions must be enforced by player, but hidden things like drop pods and termites 07/Sept/21

- [ ] Vigil Opertii Mission (Hopefully fixable later)
  - [ ] Must have Militia Allied detachment, with Gene-Crafted provenance
  - [ ] No Levy Squads
  - [x] Loyalist only
  - [x] Must include Vigilator  FiXED 07/Sept/21

----

XIV Legion - Death Guard

- [x] The Reaping
  - [x] Vet tacs and Heavy Support squads may be taken as non-compulsory troops
  - [x] all units gain move through cover (Its in the ROW but not in each individual units. This enhancement could be added with a hidden/show for the rule if the RoW is selected)
  - [x] Any Character or IC may be given rad grenades at 10pts
  - [x] No Deep Strike
  - [x] Max1 FA

- [x] Creeping death
  - [x] death Guard, Traitor
  - [x] Must include Siege Breaker
  - [x] No Fort
  - [x] No Allied

----

XV Legion - Thousand Sons

- [x] The Axis of Dissolution
  - [x] The Alembic of Adamant FIXED 07/Sept/21
  - [x] The Caustic of Grace FIXED 07/Sept/21
  - [x] The Transition of Vitriol:
  - [x] Troops Choices must be max size FIXED 07/Sept/21
  - [x] May not have more vehicles with the Tank or Flyer type than they have Infantry units FIXED 07/Sept/21

 - [x] The Guard of the Crimson King
  - [x] Astral Warfare FIXED 07/Sept/21
  - [x] Wreathed in Lightning, they Rend the Veil FIXED 07/Sept/21
  - [x] The Initiates of the Scarab (Must have Sekhmets as Compulsory Troops, Sekhmets may be taken as Optional Troops choices of desired) FIXED 07/Sept/21
  - [x] The Bidding of the Crimson King (Magnus may be taken as HQ and does not count as Lord of War)
  - [x] Must have Magnus, Ahriman or Praetor with psychic Mastery Level 3 FIXED 07/Sept/21
  - [x] May not have more Vehicles than Legiones Astartes units. FIXED 07/Sept/21
  - [x] May not take Allied Detachments or Fortifications FIXED 07/Sept/21

----

XVI Legion - Sons of Horus

- [x] The Black Reaving
  - [x] Reavers are troops
  - [x] Justaerin gain Deep Strike
  - [x] Must take master of signal in addition to Compulsory HQ 
  - [x] Must take more Fast attack then Heavy Support : Fixed  11/06/21
  - [x] +1 compulsory troop (3+ instead of 2+) : Fixed  11/06/21
  - [x] No Fort

- [x] The Long March 
  - [x] SoH, Traitor
  - [x] No Slow and purposeful, unless Deep Strike or deployed in vehicle
  - [x] No Fort
  - [x] No Allies

----

XVII Legion - Word Bearers
- [x] The Dark Brethren
  - [x] all IC have Preferred Enemy (Loyalist SM) FIXED 07/Sept/21
  - [x] Must take at least one Diabolist
  - [x] Max1 HS FiXED 07/Sept/21
  - [x] No Fort
  - [x] No Allied Marines

- [x] The last of the Serrated Sun
  - [x] All infantry must deploy by Drop Pod, Deep Strike, or Flyer (MUST BE CHECKED BY PLAYER)
  - [x] No Immobile units
  - [x] No Fort
  - [x] No Allied

----

XVIII Legion - Salamanders
- [x] The Covenant of Fire
  - [x] All Meltaguns, Inferno Pistols, and Multi-Meltas are Master-Crafted : Hopefully Fixed  11/06/21
  - [x] All Vehicles have a 5++ vs Melta, Volkite, Plasma, and flamer weapons, and also against meltabombs : Hopefully Fixed  11/06/21
  - [x] Pyroclasts are non-compulsory troops
  - [x] all units gain Move through cover : Fixed  11/06/21
  - [x] May not Deep Strike  (MUST BE CHECKED BY PLAYER)
  - [x] May not take more HS AND FA then total of Troops : Fixed  11/06/21
  - [x] No Forts
  - [x] max1 Consul, except for Champion

- [x] The Awakening Fire
  - [x] Infantry have Fear FIXED 07/Sept/21
  - [x] Librarian has access to Fury of the Salamander FIXED 07/Sept/21
  - [x] Must Include Chaplain FIXED 07/Sept/21
  - [x] No Vulkan FIXED 07/Sept/21
  - [x] No Fort FIXED 07/Sept/21
  - [x] No Allied
  - [x] Only one each of Jump Infantry, Jet Bikes, Skimmers, or Flyers FIXED 07/Sept/21

----

XIX Legion - Raven Guard
- [x] Decapitation Strike
  - [x] all LA units gain Preferred Enemy (Independent Characters) FiXED 07/Sept/21 Part 2
  - [x] Tacs, Vet Tacs, Tac Support, Seekers, and Heavy Support squads may take drop pod as long as there aren't too many models to fit in Drop pod
  - [x] deathstorm Drop pods are Elite
  - [x] Max1 HS
  - [x] Max1 Consul FiXED 07/Sept/21 Part 2
  - [x] No Forts
  - [x] No allied SM

- [x] Liberation Force
  - [x] No units with Immobile or Slow and Purposeful special rule
  - [x] Loyalist
  - [x] No Fort

----

XX Legion - Alpha Legion

- [x] Coils of the Hydra:
  - [x] Rewards of treason - 1 Legion Specific unit from any other Legion as elite choice
  - [x] +1 compulsory troop (3+ instead of 2+)
  - [x] Infantry that cannot take DT, Infiltrate, or Deep strike may not be taken (MUST BE CHECKED BY PLAYER)
  - [x] max1 Consul, except for Vigilator FiXED 07/Sept/21 Part 2
  - [x] No Fort
  - [x] No allied SM

- [x] The Headhunter Leviathan
  - [x] Headhunters as troops
  - [x] Sudden Strike: if your army's Primary Detachment is using this Rite of War, you may re-roll the dice to see who gets the first turn.
  - [x] False Flags
  - [x] The Alpha legion must kill the enemy Warlord by the end of the game - If they do not, their opponent earns an additional D3 Victory points at the end of the game.
  - [x] No Allies
----

Shattered Legions

- [x] After Istvaan
 - [x] Min 1 Praetor OR Centurion of Iron Hands, Raven Guard, AND Salamanders
 - [x] ERROR: Legion Veteran Tactical Squads may be taken as non-compulsory Troops  FiXED 07/Sept/21 Part 2
 - [x] ERROR: Blood Price is not shown: "When the Slay the Warlord Secondary Objective is in play, the Shattered Legion army gains not one, but D3 Victory points for achieving this objective."

- [x] Hunter-Killer Mission
 - [x] Recon squads are not Support Squads
 - [x] Seekers are non-compulsory Troops
 - [x] Run them Down: Enemy units that are entirely wiped out earn their army an additional Victory point in missions where Victory points are used to determine the winner. If the unit is destroyed in a Sweeping Advance, then not 1 but D3 additional Victory points are awarded
 - [x] Jaws of the Trap: When rolling to determine which table edge an Outflanking unit arrives by, if a 6 is rolled, the controlling player may choose to bring the unit into play from any table edge they wish (including the opposing player's or their own table edge).
 - [x] Traitors only.
 - [x] Must use Emperors Children  FiXED 07/Sept/21 Part 2
 - [x] Must contain units from at least two different Legions  FiXED 07/Sept/21 Part 2
 - [x] "The army may never earn Victory Points for controlling Objective markers, terrain or areas of the table."

----

Non-restricted 

- [x] Orbital Assault
  - [x] Create Deep Strike tag
  - [x] May take Drop Pod instead of Rhino DT  
  - [x] Dread Talons May take Drop Pods
  - [x] Terminators gain Deep Strike FIXED: 15/06/21
  - [x] Rapiers may take Pods
  - [x] Deathstorm may be taken as FA
  - [x] Must have Deep Strike tag, or have at least as many Vehicles with Deep Strike tag as it has Infantry that does not have Deep Strike tag (MUST BE CHECKED BY PLAYER)
  - [x] No Forts

- [x] Armored Spearhead
  - [x] Units may take LR Phobos/Proteus instead of Rhino DT
  - [x] All units must take DT - no more units then vehicles with transcap (MUST BE CHECKED BY PLAYER)
  - [x] No Forts

- [x] Angel's Wrath
  - [x] Jump Infantry Gains Hit&Run FIXED: 15/06/21
  - [x] May take Storm Eagle instead of Rhino as DT
  - [x] Storm Eagle and Fire Raptors gain Strafing Run FIXED: 15/06/21
  - [x] Only Units with Jump Infantry, Skimmer, and Jetbike type, as well as infantry that starts inside flyers or skimmers may be chosen as part of this list, with no more infantry then Flyer/Skimmers with transcap (MUST BE CHECKED BY PLAYER)
  - [x] No Tanks (Unless Skimmer/Flyer) FIXED: 15/06/21
  - [x] No Forts

- [x] Pride of the Legion
  - [x] Vet Tacs, Terminator Squads, and/or Legion-Specific Term squads may be taken as Troops, and are compulsory
  - [x] Command squads may take LR Proteus/Phobos
  - [x] No Allies
  - [x] More Units with LA then without FIXED: 15/06/21

- [x] Armored Breakthrough
  - [x] Tanks with 3HP or less gain Fast FIXED: 15/06/21
  - [x] All infantry units that can do so must be mounted in DT, and there must be greater than or equal to the number of Infantry units without DT options as Transport Vehicles (Tank or SHV) (MUST BE CHECKED BY PLAYER)
  - [x] No more Skimmers then Flyers then it has Tank FIXED: 15/06/21
  - [x] No Forts
  - [x] No Immobile

- [x] Primarch's Chosen
  - [x] Vet Tacs or Legion Terminators as compulsory troops
  - [x] More Units with LA then without FIXED: 15/06/21
  - [x] No LoW

- [x] Brethren of Iron
  - [x] castellax may be support troops
  - [x] Vorax may be support FA
  - [x] Domitar may be support Elites
  - [x] any techmarine may take cortex controller for +15pts
  - [x] No more Automanta then units with LA FIXED: 16/06/21
  - [x] Min one model with cortex controller for every 3 Cybernetic Cortex unit
  - [x] No Paragon of Metal FIXED: 16/06/21
  - [x] Forge Lord/Iron Father/Warsmith must be additional compulsory HQ
  - [x] Only Consuls may be FL or Praevan

- [x] Fury of the Ancients
  - [x] Troops Contemptors and Legion dreads
  - [x] Must include FL and PM
  - [x] No allies
  - [x] No Forts

- [x] Outcast Sons
  - [x] Salamanders, Raven Guard, Iron Hands, Imperial Fists, Space Wolves, BA, Whit Scars, DA, or Ultramarines only
  - [x] More troops then Elites FIXED: 16/06/21
  - [x] No Loyalist-only Units

- [x] Sky hunter Phalanx
  - [x] Skyhunters are troops
  - [x] Vehicles must be Flyer/Skimmer
  - [x] Infantry must be mounted in flyers/Skimmers (MUST BE CHECKED BY PLAYER)
  - [x] Otherwise, only jetbikes (MUST BE CHECKED BY PLAYER)
  - [x] No Forts
  - [x] No Allies

- [x] Orphans of Betrayal
  - [x] Sons of Horus, Death Guard, World Eaters, Emperor’s Children, Iron Warriors, Word Bearers, Alpha Legion, Night Lords, or Thousand Sons only
  - [x] No Traitor Only Units
  - [x] No Allied SM
  - [x] No Forts
  - [x] More Troops then HS FIXED: 16/06/21

- [x] Drop Assault Vanguard
  - [x] Assault Squads are compulsory
  - [x] Deep strikers or embarked on flyers only (MUST BE CHECKED BY PLAYER)
  - [x] No Immobile
  - [x] No Fort
  - [x] No Allies

- [x] Legion Recon Company
  - [x] must include additional compulsory legion recon squad FIXED: 16/06/21
  - [x] No Terminator Armor

- [ ] ZM Assault Force
  - [ ] Restrict Teleport Assault to only appear when ZM Assault Force Rite is selected NEED TO GET BACK TO LATER!
  - [x] Units limited to 15 marines at most. FIXED: 16/06/21
  - [ ] No Vehicles other then walkers NEED TO GET BACK TO LATER!
  - [ ] no SHV/GC NEED TO GET BACK TO LATER!

- [x] Sacrificial offering:
  - [x] Must Include Allied Militia detachment FIXED: 16/06/21
  - [x] Must include Fort
  - [x] No units with Immobile or Slow and Purposeful rules FIXED: 16/06/21
  - [x] No models that deploy via Deep Strike (MUST BE CHECKED BY PLAYER)
  - [x] Traitor only

**Comment by capitaladot** [comment]
Did Goliaths of War for Ironwing Protocol make it in? If not, could be ported from the 1.x file; gives Dreads Tank Hunter and Monster Hunter.

**Comment by IdleMuse** [comment]
The Black Reaving doesn't correctly increase the required Troops by 1

**Comment by alphalas** [comment]
Just in case anyone is following this thread, the next update of BS *should* make implementing parts of this much easier.

**Comment by TomTheHand** [comment]
For Ravenwing Protocol, "Sky Hunter and Outriders are the only Troops choices available" is checked off as complete. However, Reconnaissance Squads are still available for selection and should be removed. In addition, Sky Hunter and Outrider Troops are still counting as Fast Attack as well, so if you add more than three to Troops you will receive a "too many selections from Fast Attack" message.

**Comment by Camyron** [comment]
This issue seems to be being ignored, but worth noting the space wolf rite "the pale hunters" doesn't stop the detachment from taking allied detachments.

**Comment by Mayegelt** [comment]
I have no idea how much of this list needs doing. Might be worth reposting it up and checking if there are still work to do.
Hopefully I've solved the allies thing with a pull request.

**Comment by Mayegelt** [comment]
Making some headway on this today. Will hopefully be able to go through and finish all this in the next few weeks.

**Comment by CodicierDio** [comment]
This screenshot should summarise what want to report. The allied detachment issue is not limited to this Legion or Rite of War, though. 
![8B3C162E-2266-4D39-BE57-2B12F137D707](https://user-images.githubusercontent.com/72138253/107121267-689f2300-6889-11eb-9376-44dda0980fc0.png)

**Comment by CodicierDio** [comment]
![1A873373-EF6E-46F4-8772-27367E3CAA89](https://user-images.githubusercontent.com/72138253/107121305-a56b1a00-6889-11eb-8263-9be6eae126c5.png)
![3463EE62-45F8-4482-9719-2736F737A895](https://user-images.githubusercontent.com/72138253/107121308-a7cd7400-6889-11eb-915a-3e406472d60f.png)
![9B7DFE1B-BC15-4999-87F4-E430C4CC0E5D](https://user-images.githubusercontent.com/72138253/107121312-a8660a80-6889-11eb-8d6c-b738df26701a.png)

**Comment by Mayegelt** [comment]
![IMG_20210206_150812](https://user-images.githubusercontent.com/20280410/107122019-5d4df680-688d-11eb-8692-cd7277db8c55.jpg)
@CodicierDio 
Hi ya. Please update to latest version. I think it's 622 or 623 now. Should be resolved in there. If you are having probs downloading. Check the new guide as appspot hates heresy now.

**Comment by CodicierDio** [comment]
Thanks. I will look at that guide.

**Comment by CodicierDio** [comment]
It worked! Thanks.

**Comment by CodicierDio** [comment]
Why am I now getting an error saying that a Predator Squadron cannot have a Command Tank?

**Comment by Mayegelt** [comment]
Looks like another bug I've fixed my end after the last push. I think I caused an issue when I did the big legion row fix.

**Comment by CodicierDio** [comment]
Good, because that would offend my II Legion sensibilities if was some rule I had missed.

**Comment by CodicierDio** [comment]
When will that become live. I have deleted and updated the data to no effect.

**Comment by Mayegelt** [comment]
I attempt to do things in batches were a can. ATM I'm partway through trying to sort the Chogorian Brotherhood RoW. Need to spend a couple of hours to give infantry squads a couple of rules. One of which is conditional on if the unit has any Heavy or Salvo weapons.

**Comment by Mayegelt** [comment]
@CodicierDio a branch is up and hopefully will be live soon

**Comment by marius-karus** [comment]
I have encountered a bug for the "After Isstvan" Rite of War. In the effects of the rite it states that Veteran Tactical Squads can be taken as non-compulsory troop choices, while the limitation to this is that the force cannot contain more Tactical Squads than it contains Veteran Tactical Squads.  However, the Veteran Tactical Squads do not appear in the "Troops" section of the force. Could you please look into this?

**Comment by Mayegelt** [comment]
Will do @marius-karus 
I'm working my way from top to bottom of the list above. So it will take me a while to get down there. But I will get there.

**Comment by CodicierDio** [comment]
I can see that it’s not checked off but most of The Head Of The Gorgon works, apart from Forgelord + 1 Consul. It won’t let me take the consul when I already have the Forgelord. Also, remember it allows non-Space Marine Allied Detachments.

**Comment by LachrimallusExterminator** [comment]
I raised a new issue about Macharius weapon options for when you get round to it. My old username was CodicierDio.

**Comment by LachrimallusExterminator** [comment]
You are making great progress. Well done!
