### ISSUE TITLE
Legion Falchion - Points wrong and missing upgrade option

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#864]
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.31

**Platform:** Android

**Dropbox:** No

**Description:** Legion Falchion rules incorrectly state points as 530, when they are 525. Does not include upgrade option of Neutron Wave Capacitor for 35pts.

**Comment by capitaladot** [comment]
Another new red book change lost in the BS2 migration. A survey of all
units is needed.

**Comment by zopha** [comment]
The Neutron Wave Capacitor is there, just go into the Volcano cannon and you can add it.

Data file screenshot for reference. I've checked in the current release and it's present, the points correction will be included in the next release.

![2017-04-12 16_02_55-data editor 2 00 15 - legiones astartes_ age of darkness army list](https://cloud.githubusercontent.com/assets/1666415/24964572/8de6af80-1f99-11e7-8fab-3f3ac2a5bf30.png)
