### ISSUE TITLE
Castellax automata problems

### ISSUE THREAD

**Issue by Krimdar** [BSData/horus-heresy#868]
Hey there, 

with the Castellax' move to the basic Horus Heresy catalogue (obviously for sharing purposes) several problems occurred:

~~- no preselected Mauler Bolt Cannon~~
~~- no preselected Bolters~~
~~- no preselected Shock Chargers~~
~~- misspelled Mauler Bolt Cannon~~
~~- misspelled Shock Chargers~~
(fixed by @alphalas)

Also there is no support for the Legio Cybernetica (compulsory units, initiative buff, cortex buff, victory conditions) yet.

![screen](https://cloud.githubusercontent.com/assets/20644972/24399134/6f740c00-13b4-11e7-8462-fc9c77a6b30d.jpg)
-@alphalas

I fixed these issues in my local catalogue, but unfortunately it got overwritten even though I incremented the revision number way above the current release. Therefore it would be nice, if you could fix these issues. :)

If time is a too limiting factor, I'd be happy to modify the catalogue on github myself.

Kind regards

**Comment by zopha** [comment]
I belive the missing preeselected options are due to how Battlescribe handles the GST and groups, anything that's set to default doesn't carry over to the main army list. Unless that's changed with recent updates?

How did you handle the compulsory limitations? Any help is welcome, jump on to https://gitter.im and we can get talking.

**Comment by alphalas** [comment]
hey @krimdar, if you could upload your fix here on git, we could easily implement it in.

**Comment by capitaladot** [comment]
Cybernetica was implemented in the 1.x file. Could re-convert that file and try pasting some of the stuff in.

**Comment by alphalas** [comment]
combined into #553
