### ISSUE TITLE
outrider melta bombs

### ISSUE THREAD

**Issue by apalosaa** [BSData/horus-heresy#871]
only accounts for one model not each model when purchasing the meltabomb upgrade for the squad under "additional wargear"

**Comment by zopha** [comment]
Looks like it was set to increment on a the Sergeant rather than per model.

**Comment by apalosaa** [comment]
Still seems to charge a flat 10 points for the entire squad under Additional Wargear.

**Comment by alphalas** [comment]
It was only just committed- has not yet been released

**Comment by capitaladot** [comment]
Maybe helpful to close these with the "fixes" tag on release?

**Comment by alphalas** [comment]
Then we would have to keep track of every change made until release.

**Comment by capitaladot** [comment]
Tagging makes that relatively simple. Just create a tag with the next
release number.

**Comment by alphalas** [comment]
I understand that - however means we need to check every change made before we release instead of tagging with every commit.

**Comment by zopha** [comment]
Can you use tagging to autoclose an issue on release like you can with
"fixes #" in the commit comment?
