### ISSUE TITLE
Acastus Knight Porphyrion: Wrong FoC choice in Questoris Knights list.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#872]
**File:** (HH) Mechanicum - Questoris Knight.catz

**BattleScribe version:** 2.00.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When selecting the Acastus Knight Porphyrion in the Questoris Crusade list it is only able to be selected as a LOW.  I believe this is an error.  The PDF states it can be a LOW in the Mechanicum or Questoris Knights list.  It also states that it subject to the Household Ranks rule. Only Knights taken as part of the force org can be assigned ranks. In fact it specifies two ranks it cannot be assigned. (Scion Aspirant, Scion Uhlan) So I submit that classifying the Pophyrion as a LOW in a Questoris list is a mistake. I believe the sentence was parsed wrong, LOW only applies to the Mechanicum.

**Comment by zopha** [comment]
Yes, it should only be available as with a knight rank in the Questoris list, it was set up like that but was removed when knights were moved to the main GST file so needs to be re-implemented.

**Comment by capitaladot** [comment]
Shows as wrong FoC choice in some lists, therefor, bug.
