### ISSUE TITLE
Tactical Support Points 

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#876]
Tactical support per model weapon upgrade points have been broken by some change. Each model pays a per model upgrade cost, but only the cost for five models is ever charged.

**Comment by zopha** [comment]
Is this on mobile? Desktop is working. I've made some updates for how the calculation works. It's changed to increment per model rather than by a selection of an individual entry.

**Comment by capitaladot** [comment]
Android, I'm afraid. I hate these "works on desktop" things... Reminiscent
of all of the 1.x iOS math bugs.

**Comment by zopha** [comment]
Yes. Extremely annoying. I'll test on android a little later and see,
internet is too patchy while commuting.

**Comment by zopha** [comment]
Ah, double commits probably confused github. This should have closed with the merge.
