### ISSUE TITLE
Sons of Horus - Anvillus Pattern Dreadclaw Drop Pod

### ISSUE THREAD

**Issue by paulwelch93** [BSData/horus-heresy#886]
Just a quick heads up, the Sons of Horus' Anvillus Pattern Dreadclaw Drop Pod points cost is 100 instead of the normal 115 for other Legions.

**Comment by capitaladot** [comment]
@paulwelch93 are you saying it should cost less because of something from a Legiones Astartes Age of Darkness Legions or Book 1? If so, the rules text and a citation would help.

**Comment by alphalas** [comment]
Actually in the latest red book it's 100pts

**Comment by alphalas** [comment]
Also it is now SoH exclusive

**Comment by paulwelch93** [comment]
Here's the relivent rules page taken from the Legion Astartes Age of Darkness Legions eBook page 82

Sons of Horus Dedicated Transport - 100pts

It can be taken as a dedicated transport for the following units;

Justarian Terminators
Legion Terminator Squad
Legion Dreadnaught (Talon of 1)
Legion Seeker Squad
Reaver Attack Squad
Legion Command Squad

All other rules are the same as the normal rules laid out on page 55 of the Legion Astartes eBook

**Comment by alphalas** [comment]
Pg 55 of the newest red book is rampager squads - anvillus is now SoH exclusive

**Comment by alphalas** [comment]
You are correct about 100pt though
