### ISSUE TITLE
Join request

### ISSUE THREAD

**Issue by martijndoornik** [BSData/horus-heresy#888]
Hey guys! 

Currently working on some Thousand Sons Horus Heresy stuff, but realised I wasn't added here (I am in de 40K datafiles). Anyone willing to add me here too? :)

**Comment by alphalas** [comment]
as soon as @amis92 approves you you'll be good to go - please join us on Gitter so we can get you up to speed of what's going on.

**Comment by zopha** [comment]
:+1:

Good to have you on the team @martijndoornik come say hello on [Gitter](https://gitter.im/BSData/horus-heresy)!
