### ISSUE TITLE
Legion Specific Rites of War

### ISSUE THREAD

**Issue by paulwelch93** [BSData/horus-heresy#89]
Hi,

First time poster, firstly I'd like to say a huge thanks for all the work that you are doing!

I have a question about Legion specific Rites of War, and how they can be applied to units and the categories that they are allocated too. I ask, mainly about the Raven Guard one, that allow Tactical, Veteran, Tactical Support, Seeker and Heavy Support Squads to take a Drop Pod as a dedicated transport, and that the player can take Deathstorm Drop Pods as Elites instead of Heavy Support.

I understand that this can be worked around, but would rather be able to have a completely accurate entry to use during a game

**Comment by Millicant** [comment]
This seems to be working as intended.  Are you asking how to use the Rites of War in Battlescribe?  Simply select a unit that can take a Rite of War (units with the Master of the Legion special rule) select Master of the Legion, under which you will find  Rite of War.
