### ISSUE TITLE
Thousand Sons Post Release Issue Omnibus

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#896]
- [x] ~~TK Legiones Astartes missing long-form rules text~~ -all pertinent rules are present - @alphalas
- [x] Heavy support Plasma Cannon option missing link, points to Soul Blaze
- [x] Probably best to check all units for Brotherhood of Psykers
- [x] IC Psyker Mastery is listed as "Mastery Level x1" but may be taken twice
- [x] ~~HQ choices should be validated to require "Mastery Level x1" above for at least one character in Force (presumably the warlord), which probably precludes taking Master of Armour~~ -not practical to impliment- @alphalas
- [x] ~~Axis of Dissolution missing complete text~~ -all pertinent rules are present - @alphalas
- [x] ~~Aether-fire cannon on Castellax-Achea - Change to Aether-flame~~ - I believe this is a typo; there is no aether-flame cannon profile. -@alphalas
- [x] Sekhmet Terminators
  - [x] Cost 295 - Change to 255
  - [x] Add Asphex Shells profile, all their bolter weapons have it at no extra cost
  - [x] Add Stubborn USR
  - [x] Add Brotherhood of Psykers (Level 2)
  - [x] Add access to Spartan when six to ten models.
  - [x] Remove access to Phobos/Proteus when more than five models
- [x] Khenetai Blade
  - [x] Link Force USR to Force Sword
  - [x] Hand Flamer and Plasma Pistol have no cost

**Comment by zopha** [comment]
Breachers get Dark Channeling under Word Beares legion rules when they take a Diabolist so may just be set to the wrong conditions. Looking at the book only generic units that get access to brotherhood of psykers are Veteran Tacticals and Terminator squad.

**Comment by capitaladot** [comment]
Asphyx Shells missing rules/profile
