### ISSUE TITLE
Secutarii misses

### ISSUE THREAD

**Issue by Hasfodel** [BSData/horus-heresy#910]
- profile of the kinetic hammershot of the secutarii pelatas is missing
- Secutarii Axiarch don't have any weapon options

Thx guys :))

**Comment by Hasfodel** [comment]
Oh and the profile of the kinetic hammershot of the secutarii pelatas is missing

**Comment by zopha** [comment]
Some of the Secutarii stuff got messed up in one of the updates. I'll have a look at them today and get them fixed.  The Axiarch has no cost and it's default wargear isn't constrained properly.

http://i.imgur.com/KaKD1r2.png
