### ISSUE TITLE
Varous 1ksons bugs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#912]
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.00.33

**Platform:** Android

**Dropbox:** No

**Description:** Cheers for the Thousand Sons update. A couple more TS notes.

Magnus needs the option to take a command squad.
Same for Ahriman and Amon (with no Terminator armour option)

The Osiron Dreadnought should be a HQ choice.

The Praetor upgrade power weapon to force weapon option makes you pay 5 pts twice.
The power weapon upgrade to force weapon should be available for centurions also.

Sekhmet are listed as having power weapons, this should be force weapons.

**Comment by alphalas** [comment]
Osiron are not HQ - any contemptor can simply be upgraded

**Comment by MountyChris** [comment]
Where the thousand Sons unit unique are introduced in inferno, the Osiron dreadnought is listed as a HQ choice.

**Comment by alphalas** [comment]
![img_0926](https://cloud.githubusercontent.com/assets/15703066/25655325/848ffcc8-2fc2-11e7-97ae-bfb25f356e13.PNG)

No it's not.

**Comment by MountyChris** [comment]
Its on the other page, at the top. 
![45bp6pw_d](https://cloud.githubusercontent.com/assets/23583974/25655694/b87e0266-2fed-11e7-9a48-62f0f86f3ffa.jpg)

**Comment by alphalas** [comment]
...well I'll be damned. God damnit FW that's not how youre supposed do stuff.

**Comment by alphalas** [comment]
![img_0928](https://cloud.githubusercontent.com/assets/15703066/25656159/b187ffc0-2fc5-11e7-945b-4e31c8df02b2.PNG)

To be fair, I'm not sure I should however- we know the book is full of awful typos/errors/omissions, and that supports the way the data is constructed.

**Comment by zopha** [comment]
Although I can't say 100% it's a mis-print it really looks like a mis-print. The FW store page says it's an Elite choice and its book profile says it's an upgrade for a Contemptor. We don't have a HQ profile for it (only the section in brackets) or Contemptors in the book so I'm not sure how it could be taken as a HQ unless a rite of war moves a Contemptor to the HQ slot for Thousand Sons.
