### ISSUE TITLE
Cyberthuergy: Magos Dominus

### ISSUE THREAD

**Issue by dragoruss** [BSData/horus-heresy#92]
I couldn't properly articulate the issue/question with a previous post--apologies.  I described the issue as Rite of War, but actually meant Cyberthuergy.

The question:

There aren't drop downs/toggles for Cybertheurgy.  Will this be an addition/ allowed for under the Magos Dominus?

BTW, detailed work to date and without a doubt awesome!!  Thanks!

**Comment by Millicant** [comment]
Hey there,

No, Cybertheurgy will not be added.  This isn't necessarily a list-building item.  

You're welcome!  Thanks for the comments, and please let me know of any other bugs you find.
