### ISSUE TITLE
Veteran tactical squad volkite serpenta

### ISSUE THREAD

**Issue by Zuul-DG** [BSData/horus-heresy#94]
I am reciving an error message when I try to replace veterans bolt pistols for the volkite serpentas.

![screen shot 2015-03-02 at 10 09 09 pm](https://cloud.githubusercontent.com/assets/11285258/6456436/e4f4e174-c128-11e4-9ef8-3af9b54dbcf2.png)

**Comment by Millicant** [comment]
I cannot duplicate this error - it seems to be working fine.  Please supply me some more data about the rest of the list so I can try to duplicate.
