### ISSUE TITLE
Erroneously Marked with Legiones Astartes 

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#944]
- [x] Master of the Legion 
- [x] Predator
- [x] Vindicator
- [x] Land Raider
- [x] Achilles 
- [x] Sicaran
- [x] Venator 
- [x] Scorpius 
- [x] Artillery Battery
- [x] Storm Eagle
- [x] Xiphon
- [x] Fire Raptor
- [x] Caestus 
- [x] Lightning 
- [x] Avenger 
- [x] Landspeer
- [x] Javelin 
- [x] Malcador 
- [x] Fellblade
- [x] Typhon
- [x] Cerberus
- [x] Falchion 
- [x] Glaive
- [x] Stormblade
- [x] Dreadnought 
- [x] Cortis
- [x] Contemptor 
- [x] Deredeo
- [x] Leviathan

**Comment by capitaladot** [comment]
Fixed?

**Comment by alphalas** [comment]
yup. i was just check marking as i was going through.

**Comment by capitaladot** [comment]
Derp, I forgot dreads
