### ISSUE TITLE
Legion Terminator Squad points value

### ISSUE THREAD

**Issue by cowomo404** [BSData/horus-heresy#947]
Looks like a slight lapse in the data again.
Legion terminator squads are showing as 210 points rather than the expected 175 points.

It appears that the cost of 7 points is being added for combi-bolters to each model adding an erroneous 35 points to the squad.

Terminator squads have combi-bolters included in their squad cost as standard and should not include the option to replace their combi-bolters with combi-bolters ** they may add a combi-weapon for 7 points (also listed incorrectly).

![screen shot 2017-05-07 at 02 02 33](https://cloud.githubusercontent.com/assets/13860904/25778628/455d3336-32c9-11e7-9d29-de8024c46f35.jpg)

![screen shot 2017-05-07 at 02 03 18](https://cloud.githubusercontent.com/assets/13860904/25778631/66445692-32c9-11e7-91d9-6d62291da5c4.jpg)

Additionally all of the upgrade options have the incorrect points costs 
![screen shot 2017-05-07 at 02 06 04](https://cloud.githubusercontent.com/assets/13860904/25778642/cddb72cc-32c9-11e7-9eab-2500b4b68943.jpg)

- Combi-weapon is +7 points not +10
- Volkite Charger is + 7 points not + 10
- Chainfists is +10 points not free
- Lightning claw is +5 points not free
- Power fist is +5 points not +15
- Thunder hammer is +10 points not +20
- Adding an additional Terminator is +30 not +37

It also appears that the heavy weapon options (1 for every 5 terminators) is missing
this should include

- Heavy Flamer
- Reaper Autocannon
- Plasma Blaster

*** this is v84 of the Warhammer 30,000 - The Horus Heresy update May 5th 2017, 8:35:07 PM

**Comment by alphalas** [comment]
Was fixed last night, just didn't release yet
