### ISSUE TITLE
Coils of the Hydra

### ISSUE THREAD

**Issue by Sychophant** [BSData/horus-heresy#956]
The Thousand Sons and Space Wolves unique units have not yet been included in The Rewards of Treason selection list.

**Comment by Sychophant** [comment]
Also another side note. The Firedrake Terminators sargent doesn't have the option for a storm shield.

**Comment by alphalas** [comment]
actually he does, it's just a piece of wargear that is set to be hidden unless sallies ;)

**Comment by Sychophant** [comment]
That may be true, but they're allowed the purchase them when used with The Rewards of Treason.

**Comment by alphalas** [comment]
yup, i'm aware - will be fixed in my next push.

**Comment by Sychophant** [comment]
<3
