### ISSUE TITLE
Heavy Support and Tactical Support Points Math Broken 

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#967]
Not charging points per model on weapons.

**Comment by alphalas** [comment]
![image](https://cloud.githubusercontent.com/assets/15703066/26030661/eea0f7ea-3826-11e7-90b7-bc02fa749fd1.png)
![image](https://cloud.githubusercontent.com/assets/15703066/26030665/f98ea940-3826-11e7-90c6-f6bdd353f0a4.png)
