### ISSUE TITLE
Cannot make selections in army list

### ISSUE THREAD

**Issue by tbynum17** [BSData/horus-heresy#983]
Have latest version.  Deleted and re-downloaded Battlescribe and Horus Heresy data.  Using Legion Astartes and Age of Darkness Force Org.  Orange "plus signs" are missing.  Cannot make any selections under unit types (HQ, Troops, Elite, etc...).  All unit choices are greyed out and not selectable.

Battlescribe worked just fine on my iPad until latest version update.

Thanks for your attention.

**Comment by alphalas** [comment]
This is a BattleScribe bug, not a data bug.

**Comment by Jonskichov** [comment]
@tbynum17 this was fixed in version 2.00.23 which just went live - make sure you update

**Comment by tbynum17** [comment]
Thanks, Jon.  New version works.  I appreciate it!
