### ISSUE TITLE
Space Wolves issues

### ISSUE THREAD

**Issue by darkestvisions** [BSData/horus-heresy#987]
1. Grey Slayers Huscarl still gives "must have 1 more selections of Chainsword or Combat Blade (minimum 1)" when another weapon (such as Frost Claw) is selected.

2. Points values for Grey Slayer Huscarl frost weapons are incorrect (e.g. Frost Claw showing as 5pts instead of 15pts). Typically a frost weapon is 5pts, but this is 15 as per the Grey Slayers unit page in Inferno.

3. Cannot add frost weapons to a Legion Centurion.

4. Received error "Legion Terminator Sergeant must have 1 more selections from Exchange Power Weapon for: (minimum 1)" when he has a pair of lightning claws chosen.

5. Perhaps a bigger issue - "Legiones Astartes: Age of Darkness Army List v436 (The Age of Darkness) must have 1 more selections of Legion Praetor (minimum 1)". Army contains a non-Consul Centurion which should fulfil the compulsory HQ but doesn't seem to do this.

**Comment by alphalas** [comment]
closed by #990
