### ISSUE TITLE
"may replace with" per model does not re-calculate correctly. 

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#989]
Examples present in Legion Tactical Support Squad, Legion Heavy Support Squad, and Skyslayer Jetbikes. 
Bugged behavior (incorrect arithmetic)  presents based on order of operations in incrementing models and selection of one of the "all models may replace" option group selections. 
Additionally, later incrementing or decrementing model count is not reflected correctly in the accumulated total cost of the aforementioned options.

**Comment by kryanth** [comment]
This is possibly an issue with Battlescribe not refreshing/recalculating options when the model count is incremented.

**Comment by alphalas** [comment]
No that's exactly what it is - we know. @capitoladot likes having trackers open
