### ISSUE TITLE
Legion Artillery Tanks missing pintel options 

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#995]

**Comment by zopha** [comment]
Did you fix this or could it have been a Battlescribe bug?

![2017-06-09 10_22_47-roster editor v2 01 00 - new roster warhammer 30 000 - the horus heresy v85](https://user-images.githubusercontent.com/1666415/26969457-b2ed9424-4cfd-11e7-9271-8d04b1fa2ff9.png)

**Comment by capitaladot** [comment]
Fixed last night
